### ISSUE TITLE
Broken build error with order of addons array in main.js

### ISSUE THREAD

**Issue by astrotim** [storybookjs/storybook#10116]
In an attempt to implement the `main.js` declarative configuration, we discovered that the order of presets can cause a broken build with the error

> ERR! TypeError: Invalid attempt to spread non-iterable instance

Initially, we had `@storybook/addons` is first in the addons array, which was producing the following build error: 

```
info @storybook/react v5.3.12
...
info => Loading presets
info => Loading presets
info => Loading custom manager config.
ERR! TypeError: Invalid attempt to spread non-iterable instance
ERR!     at _nonIterableSpread (/node_modules/@storybook/addon-knobs/dist/preset/index.js:35:39)
ERR!     at _toConsumableArray (/node_modules/@storybook/addon-knobs/dist/preset/index.js:33:95)
ERR!     at Object.config (/node_modules/@storybook/addon-knobs/dist/preset/index.js:60:20)
ERR!     at /node_modules/@storybook/core/dist/server/presets.js:261:72
ERR!     at async createPreviewEntry (/node_modules/@storybook/core/dist/server/preview/entries.js:24:19)
ERR!     at async Object.entries (/node_modules/@storybook/core/dist/server/preview/preview-preset.js:42:27)
ERR!     at async getPreviewWebpackConfig (/node_modules/@storybook/core/dist/server/config.js:30:19)
ERR!     at async Promise.all (index 1)
ERR!     at async buildDevStandalone (/node_modules/@storybook/core/dist/server/build-dev.js:343:9)
ERR!     at async buildDev (/node_modules/@storybook/core/dist/server/build-dev.js:415:3)
...
...
...

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

The main.js configuration was:

```
module.exports = {
  stories: ['../src/**/*.story.(js|mdx)'],
  addons: [
    '@storybook/addons',
    '@storybook/addon-knobs',
    '@storybook/addon-viewport'
  ],
  presets: [postcssPreset, babelPreset]
};
```

If we changed the order of the addons array to have `@storybook/addons` last, this error does not occur.

```
addons: [
  '@storybook/addon-knobs',
  '@storybook/addon-viewport',
  '@storybook/addons',
],
```

**System:**

Storybook v5.3.12

```
$ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Safari: 12.1.1
```

**Additional context**

**Comment by shilman** [comment]
@astrotim I think you should remove `@storybook/addons` from the array entirely. It's a library, not an addon...

**Comment by astrotim** [comment]
OK thanks Michael, I'll remove it and see how we go.
