### ISSUE TITLE
v6.0.0-alpha.27 Storyshots addon: storyshots found 0 stories

### ISSUE THREAD

**Issue by Dashue** [storybookjs/storybook#10148]
**Describe the bug**
V6 storyshots isn't finding any stories

**Code snippets**
```
import initStoryshots from "@storybook/addon-storyshots";
import { render } from "@testing-library/react";

const reactTestingLibrarySerializer = {
    print: (val: any, serialize: any) => serialize(val.container.firstChild),
    test: (val: any) => val && val.hasOwnProperty("container"),
};

initStoryshots({
    framework: "react",
    renderer: render,
    snapshotSerializers: [reactTestingLibrarySerializer],
    storyKindRegex: /^((?!.*?DontTest).)*$/,
});
```

**System:**
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.14.2 - C:\Program Files (x86)\Nodist\bin\node.EXE
    npm: 6.9.0 - C:\Program Files (x86)\Nodist\bin\npm.EXE
  Browsers:
    Edge: 44.18362.449.0

**Additional context**
Package json excerpt of dependencies and devdependencies
```
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/react-fontawesome": "~0.1.9",
    "@material-ui/lab": "^4.0.0-alpha.46",
    "@material-ui/pickers": "^4.0.0-alpha.4",
    "@material-ui/styles": "^4.9.6",
    "autosuggest-highlight": "^3.1.1",
    "express": "^4.17.1",
    "express-basic-auth": "^1.2.0",
    "moment": "^2.24.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.7",
    "@fortawesome/pro-light-svg-icons": "^5.12.1",
    "@fortawesome/pro-regular-svg-icons": "^5.12.1",
    "@fortawesome/pro-solid-svg-icons": "^5.12.1",
    "@harelpls/storybook-addon-materialui": "^1.0.2",
    "@material-ui/core": "^4.9.6",
    "@storybook/addon-actions": "v6.0.0-alpha.27",
    "@storybook/addon-backgrounds": "v6.0.0-alpha.27",
    "@storybook/addon-centered": "v6.0.0-alpha.27",
    "@storybook/addon-console": "^1.2.1",
    "@storybook/addon-docs": "v6.0.0-alpha.27",
    "@storybook/addon-knobs": "v6.0.0-alpha.27",
    "@storybook/addon-links": "v6.0.0-alpha.27",
    "@storybook/addon-notes": "5.3.17",
    "@storybook/addon-storyshots": "v6.0.0-alpha.27",
    "@storybook/addon-storysource": "v6.0.0-alpha.27",
    "@storybook/addon-viewport": "v6.0.0-alpha.27",
    "@storybook/addons": "v6.0.0-alpha.27",
    "@storybook/preset-typescript": "1.2.2",
    "@storybook/react": "v6.0.0-alpha.27",
    "@testing-library/jest-dom": "^5.1.1",
    "@testing-library/react": "^10.0.1",
    "@types/autosuggest-highlight": "^3.1.0",
    "@types/jest": "^25.1.4",
    "@types/react": "^16.9.23",
    "babel-loader": "^8.0.6",
    "chokidar-cli": "^2.1.0",
    "fork-ts-checker-webpack-plugin": "^4.1.0",
    "jest": "^25.1.0",
    "react": "^16.13.0",
    "react-docgen-typescript-loader": "^3.7.1",
    "react-is": "^16.13.0",
    "react-test-renderer": "^16.13.0",
    "style-dictionary": "2.8.3",
    "ts-jest": "^25.2.1",
    "ts-loader": "^6.2.1",
    "typescript": "^3.8.3"
  }
```

Jest Config
```
module.exports = {
  // The root of your source code, typically /src
  // `<rootDir>` is a token Jest substitutes
  roots: ["<rootDir>/src"],

  // Jest transformations -- this adds support for TypeScript
  // using ts-jest
  transform: {
    "^.+\\.(js|ts|tsx)?$": "ts-jest"
  },

  transformIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/src/components/shared/MomentDateAdapter.ts",
    "<rootDir>/src/components/DatePicker.tsx",
    "<rootDir>/src/components/DatePickerStatic.tsx",
  ],


  // Runs special logic, such as cleaning up components
  // when using React Testing Library and adds special
  // extended assertions to Jest
  setupFilesAfterEnv: ["@testing-library/jest-dom/extend-expect"],

  // Test spec file resolution pattern
  // Matches parent folder `__tests__` and filename
  // should contain `test` or `spec`.
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
  testPathIgnorePatterns: ['index.ts'],

  // Module file extensions for importing
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"]
};
```
Tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "allowJs": true,
    "checkJs": true,
  },
  "include": [
    "typings.d.ts",
    ".story-helpers/**/*.(ts|tsx)",
    ".storybook/**/*.(ts|tsx)",
    "src/**/*.(ts|tsx)",
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by Dashue** [comment]
@shilman 

I've got bandwidth and happy to do further testing if I can to either figure out what I'm doing wrong or to help resolve the issue before anyone else comes across it

**Comment by shilman** [comment]
@igor-dv @Hypnosphi any chance one of you can point @Dashue in the right direction?

**Comment by Dashue** [comment]
Happy to help out with this, now running v6.0.0-alpha.33 and am seeing a different error now:

```
 Test suite failed to run

    Cannot find module 'spdx-license-ids' from 'scan.js'

    Require stack:
      node_modules/spdx-expression-parse/scan.js
      node_modules/spdx-expression-parse/index.js
      node_modules/validate-npm-package-license/index.js
      node_modules/normalize-package-data/lib/fixer.js
      node_modules/normalize-package-data/lib/normalize.js
      node_modules/read-pkg/index.js
      node_modules/read-pkg-up/index.js
      node_modules/@storybook/addon-storyshots/dist/frameworks/hasDependency.js
      node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js
      node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js
      node_modules/@storybook/addon-storyshots/dist/api/index.js
      node_modules/@storybook/addon-storyshots/dist/index.js
      src/__tests__/Storyshots.test.tsx

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:296:11)
      at Object.<anonymous> (node_modules/spdx-expression-parse/scan.js:4:11)
```

**Comment by Dashue** [comment]
Following up on this.
Jest does run for a long time before stating 0 tests found/
I'm guessing either it receives an error that isn't surfaced, or it genuinely cannot find any tests. 
I'll include my folder hierarchy and code for the relevant files below.

```
 Test suite failed to run

    storyshots found 0 stories

       7 | };
       8 |
    >  9 | initStoryshots({
         |               ^
      10 |     framework: "react",
      11 |     renderer: render,
      12 |     snapshotSerializers: [reactTestingLibrarySerializer],

      at Object.testStorySnapshots [as default] (node_modules/@storybook/addon-storyshots/dist/api/index.js:96:15)
      at Object.<anonymous> (src/__tests__/Storyshots.test.tsx:9:15)

Test Suites: 1 failed, 16 passed, 17 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        34.122 s
```

./storybook/main.ts
```

module.exports = {
  stories: [
    "../src",
    "../stories/**/*.stories.(tsx)",
  ],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-docs",
    "@storybook/addon-knobs/register",
    "@storybook/addon-storysource",
    "@storybook/addon-viewport/register",
    "@storybook/addon-notes/register-panel",
  ],
  presets: [
    {
      name: "@storybook/preset-typescript",
    }
  ],
  webpackFinal: (config: any) => {
    config.resolve.plugins.push(new TsconfigPathsPlugin({ configFile: "./tsconfig.json" }));
    return config;
  }
};
```

./src/_tests_/Storyshots.test.ts
```
import initStoryshots from "@storybook/addon-storyshots";
import { render } from "@testing-library/react";

const reactTestingLibrarySerializer = {
    print: (val: any, serialize: any) => serialize(val.container.firstChild),
    test: (val: any) => val && val.hasOwnProperty("container"),
};

initStoryshots({
    framework: "react",
    renderer: render,
    snapshotSerializers: [reactTestingLibrarySerializer],
    storyKindRegex: /^((?!.*?DontTest).)*$/,
});
```

./jest.config.js
```
const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig-base.json');

module.exports = {
  preset: 'ts-jest',

  setupFilesAfterEnv: ["@testing-library/jest-dom/extend-expect"],

  testPathIgnorePatterns: ['index.ts',
    // 'Storyshots.test.tsx'
  ],

  moduleFileExtensions: ["ts", "tsx", 'js', 'json'],

  reporters: ['default', 'jest-junit'],

  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/src/' }),
};
```

Folder structure
```
root/.storybook
root/src/__tests__
root/src/__tests__/storyshots.tests.ts
root/src/components
root/stories
root/jest.config.js
```

**Comment by piemasters** [comment]
I just updated to `6.0-beta.21` and i got some snapshots created. I also got a ton of configuration errors & warnings so going to work through that, but I recommend updating and see if you have any luck.

**Comment by piemasters** [comment]
I also just found that updating the glob in main.js seems to break storyshots so check that - https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
