### ISSUE TITLE
`process.execArgv` is not present in `process` mock

### ISSUE THREAD

**Issue by vgrinko** [storybookjs/storybook#10222]
**Describe the bug**
```
TypeError: Cannot read property 'length' of undefined
    at includes (http://localhost:6006/vendors~main.4c4076e4ee76841a6395.bundle.js:115112:31)
    at push../node_modules/resolve-package-path/lib/should-preserve-symlinks.js.module.exports (http://localhost:6006/vendors~main.4c4076e4ee76841a6395.bundle.js:115120:52)
    at Object.<anonymous> (http://localhost:6006/vendors~main.4c4076e4ee76841a6395.bundle.js:114902:25)
    at Object../node_modules/resolve-package-path/lib/resolve-package-path.js (http://localhost:6006/vendors~main.4c4076e4ee76841a6395.bundle.js:115097:30)
    at __webpack_require__ (http://localhost:6006/runtime~main.4c4076e4ee76841a6395.bundle.js:785:30)
    at fn (http://localhost:6006/runtime~main.4c4076e4ee76841a6395.bundle.js:151:20)
    at Object../node_modules/resolve-package-path/index.js 
```
this is caused by `process.execArgv` not being present in the `process` shim for the browser. I tried all these options:
`true`, `mock`, `empty`, `false` as described here https://webpack.js.org/configuration/node/
But issue only goes away if I explicitly set `process.execArgv=[]` using debugger.

Looking at all options - is there a hook I can use to shim this attribute for `process` object?

**To Reproduce**
I am trying to add storybook to an existing ember project
```
npx -p @storybook/cli sb init
yarn add @storybook/ember-cli-storybook
ember build
yarn start-storybook -p 6006 -s dist
```

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/5897153/77688725-c9698980-6f5d-11ea-8522-7aceddadb3ef.png)

**System:**
System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.16.0 - ~/.volta/tools/image/node/12.16.0/6.13.4/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.13.4 - ~/.volta/tools/image/node/12.16.0/6.13.4/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.17 => 5.3.17
    @storybook/addon-links: ^5.3.17 => 5.3.17
    @storybook/addons: ^5.3.17 => 5.3.17
    @storybook/ember: ^5.3.17 => 5.3.17
    @storybook/ember-cli-storybook: ^0.2.0 => 0.2.0

**Comment by vgrinko** [comment]
I resolved this by using custom webpack config in storybook - by aliasing (basically, mocking in this case) the module which had a codepath, which referenced this browser incompatible code (`should-preserve-symlinks`).

**.storybook/shouldPreserveSymlinksMock.js**
`module.exports = ()=>true;
`

**.storybook/main.js**
```
const path = require('path');
module.exports = {
  stories: ['../stories/**/*.stories.js'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],
  webpackFinal: async (config, configType) => {
    config.node = {fs: 'empty', child_process: 'empty', process: 'mock'};
    config.resolve.alias = {
      ...config.resolve.alias,
      './should-preserve-symlinks': path.resolve(__dirname, 'shouldPreserveSymlinksMock.js'),
    };
    return config;
  },
};
```

So I am unblocked now.
