### ISSUE TITLE
Can't install @storybook/channel-postmessage@5.3.18

### ISSUE THREAD

**Issue by do87** [storybookjs/storybook#10284]
**Describe the bug**
Can't install @storybook/channel-postmessage@5.3.18

**To Reproduce**
1. run `npm install @storybook/channel-postmessage@5.3.18`

Error log below

**Expected behavior**
Package is installed successfully

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 12.8.1 - ~/homebrew/bin/node
    npm: 6.12.1 - ~/homebrew/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 68.4.1
    Safari: 13.1
```

**Additional context**
```
1 verbose cli   '@storybook/channel-postmessage@^5.3.18'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.8.1
4 verbose npm-session 350e5c5bab042fff
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@storybook%2fchannel-postmessage 217ms (from cache)
8 silly fetchPackageMetaData error for @storybook/channel-postmessage@^5.3.18 Unexpected end of JSON input while parsing near '...71\nvaHxCYfLh+lBkhrO9'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 255ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...71\nvaHxCYfLh+lBkhrO9'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/homebrew/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
11 verbose stack     at /homebrew/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by shilman** [comment]
@do87 looks like a caching issue. can you clear your NPM cache and try again?

**Comment by do87** [comment]
hi @shilman,
i tried running npm install -f which should skips cache, and i still got the same problem
Same issue occurs on my Azure DevOps agent as well
