### ISSUE TITLE
TypeError: Cannot read property 'baseUrl' of undefined

### ISSUE THREAD

**Issue by ConnorDY** [storybookjs/storybook#10369]
**Describe the bug**

I used `npx -p @storybook/cli sb init` to add Storybook to my Angular component library monorepo (using Lerna).

Upon running, `npm run storybook`, I get the following output:

```
info @storybook/angular v5.3.18
info 
info => Loading presets
info => Loading presets
info => Adding stories defined in ".storybook/main.js".
info => Found custom tsconfig.json
info => Using default Webpack setup.
info => Using angular project 'core' for configuring Storybook.
ERR! TypeError: Cannot read property 'baseUrl' of undefined
ERR!     at getTsConfigOptions (/path/to/project/node_modules/@storybook/angular/dist/server/angular-cli_config.js:41:44)
ERR!     at Object.getAngularCliWebpackConfigOptions (/path/to/project/node_modules/@storybook/angular/dist/server/angular-cli_config.js:100:20)
ERR!     at Object.webpackFinal (/path/to/project/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js:7:56)
ERR!     at /path/to/project/node_modules/@storybook/core/dist/server/presets.js:261:72
ERR!  TypeError: Cannot read property 'baseUrl' of undefined
ERR!     at getTsConfigOptions (/path/to/project/node_modules/@storybook/angular/dist/server/angular-cli_config.js:41:44)
ERR!     at Object.getAngularCliWebpackConfigOptions (/path/to/project/node_modules/@storybook/angular/dist/server/angular-cli_config.js:100:20)
ERR!     at Object.webpackFinal (/path/to/project/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js:7:56)
```

My `tsconfig.json` files are as follows.

`projects/core/tsconfig.lib.json`:
```json
{
  "extends": "../../tsconfig.lib.json"
}
```

`tsconfig.lib.json`:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "types": [],
    "lib": ["dom", "es2018"]
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  },
  "exclude": ["**/*.spec.ts", "**/*.stories.ts"]
}
```

`tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"]
  }
}
```

**To Reproduce**
Described above.

**Expected behavior**
The storybook runs as expected.

**Screenshots**
N/A

**Code snippets**
Included above.

**System:**

```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-actions: ^5.3.18 => 5.3.18 
    @storybook/addon-links: ^5.3.18 => 5.3.18 
    @storybook/addon-notes: ^5.3.18 => 5.3.18 
    @storybook/addons: ^5.3.18 => 5.3.18 
    @storybook/angular: ^5.3.18 => 5.3.18 
```

**Additional context**
N/A

**Comment by ConnorDY** [comment]
Any updates on this? I've tried adding `baseUrl` to my other `tsconfig.json` files, but that doesn't seem to change anything.

**Comment by matheo** [comment]
@ConnorDY I suggest you to use the latest `v6.0.0-beta`.
I've managed to make it work for my lerna monorepo.

**Comment by bbfrancis** [comment]
@ConnorDY @matheo - Fixing my angular.json tsConfig value solved the issue for me. Figured I'd throw it out there if it helps anyone else
