### ISSUE TITLE
build-storybook fails with error "don't know how to turn this value into a node"

### ISSUE THREAD

**Issue by nanandn** [storybookjs/storybook#10948]
The "build-storybook" script fails with error "don't know how to turn this value into a node".
Here is the stack trace.

```
ERR! => Failed to build the preview
ERR! ./node_modules/simplebar/dist/simplebar.min.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error: /Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/simplebar/dist/simplebar.min.js: don't know how to turn this value into a node
ERR!     at Object.valueToNode (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/types/lib/converters/valueToNode.js:87:9)
ERR!     at PluginPass.Expression (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/babel-plugin-minify-constant-folding/lib/index.js:195:26)
ERR!     at PluginPass.newFn (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/visitors.js:220:17)
ERR!     at newFn (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/visitors.js:179:21)
ERR!     at NodePath._call (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/path/context.js:55:20)
ERR!     at NodePath.call (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/path/context.js:42:17)
ERR!     at NodePath.visit (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/path/context.js:90:31)
ERR!     at TraversalContext.visitQueue (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!     at NodePath.visit (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/path/context.js:97:18)
ERR!     at TraversalContext.visitQueue (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/Users/anarasimhan/Development/git_repositories/work/table/storybook-develop/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!  @ ./node_modules/simplebar-react/dist/simplebar-react.js 8:171-191 8:231-275
ERR!  @ ./node_modules/@storybook/components/dist/ScrollArea/ScrollArea.js
ERR!  @ ./node_modules/@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.js
ERR!  @ ./node_modules/@storybook/components/dist/blocks/Source.js
ERR!  @ ./node_modules/@storybook/components/dist/blocks/index.js
ERR!  @ ./node_modules/@storybook/components/dist/index.js
ERR!  @ ./node_modules/@storybook/addon-docs/dist/blocks/index.js
ERR!  @ ./node_modules/@storybook/addon-docs/blocks.js
ERR!  @ ./.storybook/preview.js
```

**To Reproduce**
1. Run "npm run build-storybook".

**Expected behavior**
The build to be sucessfull.

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/Development/git_repositories/work/table/storybook-develop/node_modules/.bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 5.3.18 => 5.3.18
    @storybook/addon-actions: 5.3.18 => 5.3.18
    @storybook/addon-console: ^1.2.1 => 1.2.1
    @storybook/addon-docs: 5.3.18 => 5.3.18
    @storybook/addon-knobs: 5.3.18 => 5.3.18
    @storybook/addon-links: 5.3.18 => 5.3.18
    @storybook/addon-storysource: 5.3.18 => 5.3.18
    @storybook/react: 5.3.18 => 5.3.18

**Additional context**
Works fine in development mode (npm run storybook).

**Comment by nanandn** [comment]
The issue seems to be with the minify preset. It seems to work if I remove it.
