### ISSUE TITLE
Storybook beta blowing up since beta.7

### ISSUE THREAD

**Issue by kodmunki** [storybookjs/storybook#10955]
**Describe the bug**
Ever since beta-6 I get the following error when trying to run storybook:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports"` It appears to be rooted in `getManagerWebpackConfig (/Users/kodmunki/source/kodmunki/ku4/web/ku4web-component/node_modules/@storybook/core/dist/server/manager/manager-config.js:83:18)`

**To Reproduce**
1. install beta.7+
2. run `start-storybook -s www,assets -p 6006` _(obviously you may not have www or assets)_

**Expected behavior**
Storybook should start as it has through version 5 and up to version 6.0.0-beta.6

**System:**
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Edge: 83.0.478.37
    Firefox: 76.0
    Safari: 13.1
  npmPackages:
    @storybook/addon-a11y: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-actions: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-docs: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-google-analytics: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-knobs: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-links: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
    @storybook/addon-storyshots: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addon-viewport: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/addons: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/react: 6.0.0-beta.16 => 6.0.0-beta.16 
    @storybook/theming: 6.0.0-beta.16 => 6.0.0-beta.16

**Comment by matheo** [comment]
it's noticeable that `@storybook/addon-notes` was deprecated on `alpha.6`
you should remove it and re-install cleaning up the lock file:
`rm -Rf node_modules package-lock.json && npm i` (if you use npm)
`rm -Rf node_modules yarn.lock && yarn` (if you use yarn)
I haven't seen that error and I've been working with `v6.0.0` since alpha days, upgraded from v5 too.

**Comment by kodmunki** [comment]
Damn! That seemed really promising. Thank you for taking the time to share! It didn’t work, but could you tell me where you are finding your latest info on the progress of beta, i.e. `addon-notes` was deprecated? I have been trying to find the “source of truth” release notes. Are they GitHub? Is there a forum? Are there multiple? I would GREATLY appreciate your sharing where you are finding the most relevant information. It would be a massive help! — Thanks for the info you already shared! I hope you’d take a moment to LMK where you are finding the docs on the progression through beta. I really appreciate it! ;)

**Comment by shilman** [comment]
@kodmunki All 6.0 breaking changes are documented in [MIGRATION.md](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-53x-to-60x)

**Comment by MarcusNotheis** [comment]
I'm facing the same error when using node 12.17.0. 
If I downgrade to node 12.16.3 everything works fine. Might this be related to the removal of the [`--experimental-modules`](https://nodejs.org/en/blog/release/v12.17.0/#ecmascript-modules-experimental-modules-flag-removal)?

Environment Info:
System: macOS 10.15.4
Node: 12.17.0
yarn: 1.22.7

Storybook Dependencies:
```json
"@storybook/addon-actions": "6.0.0-beta.17",
"@storybook/addon-controls": "^6.0.0-beta.17",
"@storybook/addon-docs": "6.0.0-beta.17",
"@storybook/addon-toolbars": "6.0.0-beta.17",
"@storybook/addons": "6.0.0-beta.17",
"@storybook/cli": "6.0.0-beta.17",
"@storybook/react": "6.0.0-beta.17",
"@storybook/theming": "6.0.0-beta.17",
```
main.js:
```js
module.exports = {
    stories: ['../docs/**/*.stories.mdx', '../packages/**/*.stories.mdx', '../packages/**/*.stories.[tj]sx'],
    addons: [
        '@storybook/addon-toolbars',
        '@storybook/addon-docs',
        '@storybook/addon-controls',
        '@storybook/addon-actions'
    ],
    webpack: async (config, { configType }) => {
        // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
        // You can change the configuration based on that.
        // 'PRODUCTION' is used when building the static version of storybook.

        config.module.rules.push({
            test: /assets\/.*\.json$/,
            use: 'file-loader',
            type: 'javascript/auto'
        });

        return config;
    }
};
```

**Comment by kodmunki** [comment]
Thank you Michael and Marcus! Going through MIGRATION.md and downgrading to 12.6.3 (I was running node 14 until beta.7 broke everything) fixed my issues. I am still not sure I understand why node v14 was working up to beta.7. I may have to do some more reading. Thank you both for sharing all of the info. Its greatly appreciated!

**Comment by fernandopasik** [comment]
Looks like this issue is happening here
https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/manager/manager-config.js#L18

In my case, it's breaking with rollup package.json

```
WARN Unable to close preview build!
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /project/node_modules/rollup/package.json
ERR!     at applyExports (internal/modules/cjs/loader.js:491:9)
ERR!     at resolveExports (internal/modules/cjs/loader.js:507:23)
ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
ERR!     at resolveFileName (/project/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/project/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/project/node_modules/resolve-from/index.js:46:47)
ERR!     at /project/node_modules/@storybook/core/dist/server/manager/manager-config.js:52:38
ERR!     at Array.map (<anonymous>)
ERR!     at getAutoRefs (/project/node_modules/@storybook/core/dist/server/manager/manager-config.js:51:109)
ERR!     at async getManagerWebpackConfig (/project/node_modules/@storybook/core/dist/server/manager/manager-config.js:83:18)
ERR!  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /project/node_modules/rollup/package.json
ERR!     at applyExports (internal/modules/cjs/loader.js:491:9)
ERR!     at resolveExports (internal/modules/cjs/loader.js:507:23)
ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
ERR!     at resolveFileName (/project/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/project/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/project/node_modules/resolve-from/index.js:46:47)
ERR!     at /project/node_modules/@storybook/core/dist/server/manager/manager-config.js:52:38
ERR!     at Array.map (<anonymous>)
ERR!     at getAutoRefs (/project/node_modules/@storybook/core/dist/server/manager/manager-config.js:51:109)
ERR!     at async getManagerWebpackConfig (/project/node_modules/@storybook/core/dist/server/manager/manager-config.js:83:18) {
ERR!   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by shilman** [comment]
Thanks @fernandopasik, that looks like it could be a bug. Does anybody have a repro repo we could look at?

**Comment by fernandopasik** [comment]
I could break one of my repos to have this. But I guess I wanted to ask a bit of context for this commit https://github.com/storybookjs/storybook/commit/68518998de06495fd9b923c67d0a218e2d213260

**Comment by fernandopasik** [comment]
I've created a branch `storybook-beta-update` in my repo 
https://github.com/fernandopasik/hello-web-components/tree/storybook-beta-update

if you run `yarn start` it will start storybook and show this error

**Comment by fernandopasik** [comment]
If we agree maybe of doing a try/catch in this line and return undefined https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/manager/manager-config.js#L18

I would raise a PR with that

**Comment by ndelangen** [comment]
@fernandopasik I tried your reproduction repo but this is what I see:
<img width="1052" alt="Screenshot 2020-06-04 at 15 46 23" src="https://user-images.githubusercontent.com/3070389/83764762-9e489800-a67a-11ea-8fa1-74b575c40649.png">

**Comment by fernandopasik** [comment]
Are you running this from master or from the branch `storybook-beta-update`?

**Comment by fernandopasik** [comment]
Looking at the package `resolve-from` the line that's blowing up is https://github.com/sindresorhus/resolve-from/blob/master/index.js#L43

**Comment by ndelangen** [comment]
What am I doing wrong?
<img width="1437" alt="Screenshot 2020-06-04 at 16 09 20" src="https://user-images.githubusercontent.com/3070389/83768279-dc47bb00-a67e-11ea-82a1-866180800a34.png">

**Comment by fernandopasik** [comment]
oh what node.js version are you running? This happens with > 12.17.0 and 14

**Comment by fernandopasik** [comment]
I'm looking at a similar issue in https://github.com/then/is-promise/issues/13

They are commenting about a `exports` field in package.json, and rollup has that. Not sure what the root cause still but this is my last clue.

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.22 containing PR #11023 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by fernandopasik** [comment]
I've updated my repo with the latest beta, works great, thanks!
