### ISSUE TITLE
Urgent | Storybook build failing in Jenkins | V5.3.9

### ISSUE THREAD

**Issue by SMOHA786** [storybookjs/storybook#10977]
Can some one help with the below issue, seeing this issue all of sudden, everything was working fine till noon.

`yarn version: v1.22.4
`
### Package version.
`
"@storybook/addon-a11y": "^5.3.5",
"@storybook/addon-actions": "^5.3.9",
"@storybook/addon-knobs": "^5.3.9",
"@storybook/addon-links": "^5.3.9",
"@storybook/addons": "^5.3.9",
"@storybook/preset-typescript": "^1.2.0",
"@storybook/react": "^5.3.9",
"@storybook/storybook-deployer": "^2.8.1",
"@babel/core": "^7.10.1",
"babel-loader": "^8.1.0"
`

### Error Log

`[0m[91mERR! => Failed to build the preview
[0m[91mERR! ./.storybook/generated-entry.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /usr/src/app/shared-component-library/node_modules/@babel/helper-compilation-targets/package.json
ERR!     at applyExports (internal/modules/cjs/loader.js:491:9)
ERR!     at resolveExports (internal/modules/cjs/loader.js:507:23)
ERR![0m[91m     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR![0m[91m     at require (internal/modules/cjs/helpers.js:72:18)
ERR![0m[91m     at Object.<anonymous> (/usr/src/app/shared-component-library/node_modules/@babel/preset-env/lib/debug.js:8:33)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR![0m[91m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
[0m[91mERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR!     at require (internal/modules/cjs/helpers.js:72:18)
ERR![0m[91m     at Object.<anonymous> (/usr/src/app/shared-component-library/node_modules/@babel/preset-env/lib/index.js:11:14)
ERR![0m[91m     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js main[4]
[0m[91mERR! ./.storybook/preview.js
ERR![0m[91m Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /usr/src/app/shared-component-library/node_modules/@babel/helper-compilation-targets/package.json
ERR![0m[91m     at applyExports (internal/modules/cjs/loader.js:491:9)
ERR!     at resolveExports (internal/modules/cjs/loader.js:507:23)
ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
[0m[91mERR![0m[91m     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
ERR![0m[91m     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
ERR![0m[91m     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR!     at require (internal/modules/cjs/helpers.js:72:18)
ERR!     at Object.<anonymous> (/usr/src/app/shared-component-library/node_modules/@babel/preset-env/lib/debug.js:8:33)
ERR![0m[91m     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR![0m[91m     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
ERR![0m[91m     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR![0m[91m     at require (internal/modules/cjs/helpers.js:72:18)
ERR!     at Object.<anonymous> (/usr/src/app/shared-component-library/node_modules/@babel/preset-env/lib/index.js:11:14)
[0m[91mERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js main[2]
[0m[91m(node:26) UnhandledPromiseRejectionWarning: [object Object]
[0m[91m(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0m[91m(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0m[91merror Command failed with exit code 1.
[0minfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build-storybook' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE`

**Comment by tooppaaa** [comment]
Is this working locally ?
What is your jenkins environment ?

I would suggest checking node versions.

**Comment by SMOHA786** [comment]
> Is this working locally ?
> What is your jenkins environment ?
> 
> I would suggest checking node versions.

Thank you, its node version issue. Now it is resolved. Closing this

**Comment by miriamso** [comment]
I have the same issue. `build:storybook` works locally but fails in Jenkins
both versions of node are equal
