### ISSUE TITLE
Angular Change Detection fail with storyshots

### ISSUE THREAD

**Issue by silinca18** [storybookjs/storybook#11053]
**Basic Angular Component:**
@Component({
  selector: 'list',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom,
})

export class ListComponent implements AfterViewInit {
  isViewInitialized = false;
  
  constructor() {}

  ngAfterViewInit() {
    this.isViewInitialized = true;
  }
}

**Storybook Story for ListComponent:** 
storiesOf(`${storyPath(__dirname)}List`, module)
  .addDecorator(moduleMetadata({
    declarations: [ ListComponent ]
  }))
  .add('Default', () => ({
    component: ListComponent,
    template: `
      <list>
        <h1 slot="title">How can I help you?</h1>
        <ul slot="listItems">
          <li>
            <p>content.</p>
            <a href="/demo/">Contact Us</a>
          </li>
        </ul>
      </list>
    `,
  }),
  {
    notes: XhrBaTertiaryCtaListNotes
  })

With these when i do storyshot test it keeps throwing me :

 ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: false'. Current value: 'ngIf: 
true'.

      at viewDebugError (../packages/core/src/view/errors.ts:37:15)
      at expressionChangedAfterItHasBeenCheckedError (../packages/core/src/view/errors.ts:23:10)
      at checkBindingNoChanges (../packages/core/src/view/util.ts:103:11)
      at checkNoChangesNodeInline (../packages/core/src/view/view.ts:473:20)
      at checkNoChangesNode (../packages/core/src/view/view.ts:461:5)
      at debugCheckNoChangesNode (../packages/core/src/view/services.ts:465:28)
      at debugCheckDirectivesFn (../packages/core/src/view/services.ts:393:7)
      at Object.eval [as updateDirectives] (ng:/DynamicTestModule/XhrBaTertiaryCtaListComponent.ngfactory.js:28:5)
      at Object.debugUpdateDirectives [as updateDirectives] (../packages/core/src/view/services.ts:385:19)
      at checkNoChangesView (../packages/core/src/view/view.ts:341:12)
      at callViewAction (../packages/core/src/view/view.ts:597:11)
      at execComponentViewsAction (../packages/core/src/view/view.ts:559:7)
      at checkNoChangesView (../packages/core/src/view/view.ts:344:3)
      at callViewAction (../packages/core/src/view/view.ts:597:11)
      at execComponentViewsAction (../packages/core/src/view/view.ts:559:7)
      at checkNoChangesView (../packages/core/src/view/view.ts:344:3)
      at callViewAction (../packages/core/src/view/view.ts:597:11)
      at execEmbeddedViewsAction (../packages/core/src/view/view.ts:580:9)
      at checkNoChangesView (../packages/core/src/view/view.ts:342:3)
      at callViewAction (../packages/core/src/view/view.ts:597:11)
      at execComponentViewsAction (../packages/core/src/view/view.ts:559:7)
      at checkNoChangesView (../packages/core/src/view/view.ts:344:3)
      at callWithDebugContext (../packages/core/src/view/services.ts:629:23)
      at Object.debugCheckNoChangesView [as checkNoChangesView] (../packages/core/src/view/services.ts:350:10)
      at ViewRef_.Object.<anonymous>.ViewRef_.checkNoChanges (../packages/core/src/view/refs.ts:267:37)
      at ComponentFixture.Object.<anonymous>.ComponentFixture.checkNoChanges (../../packages/core/testing/src/component_fixture.ts:130:51)
      at ComponentFixture.Object.<anonymous>.ComponentFixture._tick (../../packages/core/testing/src/component_fixture.ts:109:12)
      at ../../packages/core/testing/src/component_fixture.ts:120:36
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:302:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
      at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:178:50)
      at ComponentFixture.detectChanges (../../packages/core/testing/src/component_fixture.ts:120:19)
      at node_modules/@storybook/addon-storyshots/dist/frameworks/angular/renderTree.js:46:14
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
      at node_modules/zone.js/dist/zone.js:891:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:35)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:148:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:40)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:51)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:601:39)

Somehow storyshots clash with angular ngAfterViewInit. Any ideas?

**Comment by silinca18** [comment]
Up

**Comment by ConnorDY** [comment]
Can we re-open this? I am experiencing the same issue.

**Comment by shilman** [comment]
@ConnorDY Try upgrading to 6.2-alpha:

```
npx sb@next upgrade --prerelease
```

There was a recent update to angular which might have fixed it.
