### ISSUE TITLE
[v6.0.0-beta.30][addon-docs]: broken build because of acorn-jsx

### ISSUE THREAD

**Issue by Kosai106** [storybookjs/storybook#11205]
**Describe the bug**
Unable to build or preview Storybook due to an issue with [acorn-jsx](https://github.com/acornjs/acorn-jsx) - Only when using `addon-docs`.

**To Reproduce**
1. Have a repo with Storybook, addon-docs and MDX files prepared.
1. Follow the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#60-docs-breaking-changes) from `5.3` to `6.0.0-beta.30`.
2. run the `start-storybook` command.
4. See error.

**Expected behavior**
Following the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#60-docs-breaking-changes), the following should be enough to get up and running with TypeScript and docs, except it doesn't. (See error in the **Code snippets** section).
```js
module.exports = {
  stories: ["../src/**/*.stories.@(mdx|tsx)"],
  addons: [
    ...
    "@storybook/addon-docs" // or "@storybook/addon-docs/preset"
  ]
};
```
**Actual behavior**
Doing the following instead works, however:

- `MDX` complains about a missing loader.
- The prop tables are saying `Args unsupported. See Args documentation for your framework.`.
- Components are cropped in the story preview on docs.
- None of the documentation is rendered.
```js
module.exports = {
  stories: ["../src/**/*.stories.@(mdx|tsx)"],
  addons: [
    ...
    "@storybook/addon-docs/register"
  ]
};
```

**Screenshots**
Storybook `5.3.18`:
<img width="1920" alt="Screenshot 2020-06-16 at 18 43 59" src="https://user-images.githubusercontent.com/6379824/84802895-828dac00-b001-11ea-991d-0d5fa9679f31.png">

Storybook `6.0.0-beta.30`
<img width="1920" alt="Screenshot 2020-06-16 at 18 44 06" src="https://user-images.githubusercontent.com/6379824/84802995-a650f200-b001-11ea-8790-9be3886b4f58.png">

**Code snippets**
```zsh
ERROR in /Users/oesterkilde/Projects/satellite/node_modules/acorn-jsx/index.js
Module build failed (from /Users/oesterkilde/Projects/satellite/node_modules/babel-loader/lib/index.js):
TypeError: /Users/oesterkilde/Projects/satellite/node_modules/acorn-jsx/index.js: (0 , _helperModuleTransforms.getModuleName) is not a function
    at PluginPass.exit (/Users/oesterkilde/Projects/satellite/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:140:70)
    at newFn (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/Users/oesterkilde/Projects/satellite/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (/Users/oesterkilde/Projects/satellite/node_modules/@babel/core/lib/transformation/index.js:119:29)
    at runSync (/Users/oesterkilde/Projects/satellite/node_modules/@babel/core/lib/transformation/index.js:48:5)
    at runAsync (/Users/oesterkilde/Projects/satellite/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at /Users/oesterkilde/Projects/satellite/node_modules/@babel/core/lib/transform.js:34:34
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/acornParser.js 18:39-59
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/inspectValue.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/lib/inspection/index.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/propTypes/rawDefaultPropResolvers.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/propTypes/handleProp.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/extractProps.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/extractArgTypes.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/config.js
 @ /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js
 @ multi /Users/oesterkilde/Projects/satellite/node_modules/@storybook/core/dist/server/common/polyfills.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-a11y/dist/a11yRunner.js-generated-other-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-a11y/dist/a11yHighlight.js-generated-other-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js /Users/oesterkilde/Projects/satellite/node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./.storybook/preview.tsx-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

**System:**
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 76.0.1
    Safari: 13.1.1
```

**Additional context**
Somewhat related issue: https://github.com/storybookjs/storybook/issues/10828

**Comment by shilman** [comment]
@Kosai106 do you have a public repro repo i can look at?

**Comment by Kosai106** [comment]
@shilman not right now but I will create one in just a minute.

**Comment by Kosai106** [comment]
I tried a hail Mary and deleted my `node_modules` and `yarn.lock` file and it seems to work (Tested on two computers). 🙌 

I feel a little dumb for not trying this to begin with.

**Comment by vfonic** [comment]
I had the exact same error.

I ran `npx -p @storybook/cli sb init` in an existing repo and got this error after running `yarn run storybook`. It's the first time that I'm trying to setup and use Storybook so I spent quite a while trying to figure out what could be the issue.

Removing `node_modules` and running `yarn` fixed the issue... :/
