### ISSUE TITLE
"TypeError: args.flat is not a function" when running yarn storybook on brand new CRA project

### ISSUE THREAD

**Issue by jfarris587** [storybookjs/storybook#11234]
**Describe the bug**

The below errors when runnin `yarn storybook`

```
 yarn storybook
yarn run v1.13.0
$ start-storybook -p 9009 -s public
info @storybook/react v5.3.19
info
info => Loading static files from: /Users/jordanfarris/Documents/storybook-typescript/public .
info => Loading presets
info => Loading presets
info => Adding stories defined in ".storybook/main.js".
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
ERR! TypeError: args.flat is not a function
ERR!     at Object.exports.mergePlugins (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/helpers/mergePlugins.js:29:17)
ERR!     at Object.exports.webpack (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/index.js:135:184)
ERR!     at accumulationPromise.then.newConfig (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/core/dist/server/presets.js:261:72)
ERR!  { TypeError: args.flat is not a function
ERR!     at Object.exports.mergePlugins (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/helpers/mergePlugins.js:29:17)
ERR!     at Object.exports.webpack (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/index.js:135:184)
ERR!     at accumulationPromise.then.newConfig (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/core/dist/server/presets.js:261:72)
ERR!   stack:
ERR!    'TypeError: args.flat is not a function\n    at Object.exports.mergePlugins (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/helpers/mergePlugins.js:29:17)\n    at Object.exports.webpack (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/preset-create-react-app/dist/index.js:135:184)\n    at accumulationPromise.then.newConfig (/Users/jordanfarris/Documents/storybook-typescript/node_modules/@storybook/core/dist/server/presets.js:261:72)' }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

✨  Done in 15.87s.

```

**To Reproduce**
1. `npx create-react-app storybook-typescript --typescript`
2. `cd storybook-app`
3. `npx -p @storybook/cli sb init`
4. `yarn storybook`

`yarn start` appropriately starts the CRA dev server

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/presets/pull/154 and released as `@storybook/preset-create-react-app@3.1.2`. Please upgrade & try again!
