### ISSUE TITLE
 transformation/file/file is not found

### ISSUE THREAD

**Issue by xxvii27** [storybookjs/storybook#11261]
**Describe the bug**
Run `yarn storybook` got the error that transformation/file/file is not found.
Seems to originate from the mdx loader onto the babel.

**To Reproduce**
Add. storybook/addon-docs, and include the preset

**Expected behavior**
No error when running

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.
.storybook./main.js
```
  module.exports = {
    stories: ['../webapp/febuild/js/stories/**/*.stories.js'],
    addons: ['@storybook/addon-actions', '@storybook/addon-links', '@storybook/addon-docs/preset'],
    webpackFinal: async config => {
      // do mutation to the config

      return config;
    },
  };
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Xeon(R) CPU @ 2.00GHz
  Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
  npmPackages:
    @storybook/addon-actions: ^5.3.19 => 5.3.19
    @storybook/addon-docs: ^5.3.19 => 5.3.19
    @storybook/addon-links: ^5.3.19 => 5.3.19
    @storybook/addons: ^5.3.19 => 5.3.19
    @storybook/react: ^5.3.19 => 5.3.19
```

**Additional context**

```
ERR! Require stack:
ERR! - /home/llesmancom/appfe/node_modules/@mdx-js/mdx/node_modules/@babel/core/lib/index.js
ERR! - /home/llesmancom/appfe/node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/addon-docs/mdx-compiler-plugin.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/addon-docs/dist/preset.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/addon-docs/preset.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/core/dist/server/presets.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/core/dist/server/config.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/core/server.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/react/dist/server/index.js
ERR! - /home/llesmancom/appfe/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR!     at require (internal/modules/cjs/helpers.js:72:18)
ERR!     at Object.<anonymous> (/home/llesmana_whova_com/appfe/node_modules/@mdx-js/mdx/node_modules/@babel/core/lib/index.js:177:36)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:1026:19)
ERR!     at require (internal/modules/cjs/helpers.js:72:18)
ERR!     at Object.<anonymous> (/home/llesmana_whova_com/appfe/node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js:1:25)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1138:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:986:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
ERR!  Error: Cannot find module './transformation/file/file'
```

**Comment by shilman** [comment]
Do you have a public repro repo I can look at?

**Comment by xxvii27** [comment]
hmm, I just tried create an empty repo with no source code and do quick install of storybook and same thing happens. I can push that if it helps

**Comment by xxvii27** [comment]
https://github.com/xxvii27/storybook-test

**Comment by xxvii27** [comment]
Nvm seems I got it working on another machine might be some problem with the node / npm version there

**Comment by xxvii27** [comment]
what is the recommended npm / noder version BTW?

**Comment by shilman** [comment]
i think node 12 / npm latest? but should work with a pretty wide range

**Comment by xxvii27** [comment]
hmm weird, anyway thanks for the replies, closing this

**Comment by kettanaito** [comment]
Deleting `package-lock.json`/`yarn.lock` and re-installing dependencies resolved this issue for me.

**Comment by pudjo** [comment]
I delete package-lock.json/yarn.lock and run yarn install --force.
