### ISSUE TITLE
Get error when run yarn storybook command

### ISSUE THREAD

**Issue by oussama-he** [storybookjs/storybook#11353]
I started to learn storybook vue version. I followed the steps in this [page](https://www.learnstorybook.com/intro-to-storybook/vue/en/get-started/).
But when I run the `yarn storybook`command  I get this error:

```
WARN Unable to close preview build!
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
ERR!     at validateString (internal/validators.js:117:11)
ERR!     at Object.join (path.js:1039:7)
ERR!     at _default (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:148:32)
ERR!     at Object.managerWebpack (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-preset.js:37:38)
ERR!     at /home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/presets.js:261:72
ERR!  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
ERR!     at validateString (internal/validators.js:117:11)
ERR!     at Object.join (path.js:1039:7)
ERR!     at _default (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:148:32)
ERR!     at Object.managerWebpack (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-preset.js:37:38)
ERR!     at /home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/presets.js:261:72 {
ERR!   stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined\n' +
ERR!     '    at validateString (internal/validators.js:117:11)\n' +
ERR!     '    at Object.join (path.js:1039:7)\n' +
ERR!     '    at _default (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:148:32)\n' +
ERR!     '    at Object.managerWebpack (/home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/manager/manager-preset.js:37:38)\n' +
ERR!     '    at /home/oussama/dev-place/vuejs/taskbox/node_modules/@storybook/core/dist/server/presets.js:261:72',
ERR!   code: 'ERR_INVALID_ARG_TYPE'
ERR! }
```
Any help, please?
Thank you in advance.

**Comment by shilman** [comment]
Please file an issue here: https://github.com/chromaui/learnstorybook.com/
