### ISSUE TITLE
Storybook Docs custom Preview component access to Story source code

### ISSUE THREAD

**Issue by dej611** [storybookjs/storybook#11498]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a documentation with Storybook and migrating to the new addon-docs tool.
One more feature I tried to implement was a link to open the story source code in tools such CodeSandbox or Stackblitz.

So far I tried the following things in a `mdx` file:
* Create a custom `MyPreview` component where I try to access to the `SourceContext` as comsumer with the `useContext` hook - the error below appeared.
* I've read through the addon `Preview` component from `addon-docs/blocks` source code and tried to implement a 1-1 version on my `MyPreview`, just to intercept the source code content via the React `Context`, without particular success. Same error as above - the error is only raised by the `SourceContext` and not by the `DocsContext`.
* I've also tried to access the same context within the `Preview` component from `addon-docs/blocks`, still same error.

Maybe there's some other way to get it, but those weree my attempts so far.

<img width="1225" alt="Screenshot 2020-07-10 at 19 04 41" src="https://user-images.githubusercontent.com/924948/87180145-41c34300-c2e0-11ea-8e68-6b12b66dca81.png">

Here's the error full stack:
```js
TypeError: Cannot read property '_context' of undefined
    at useContext (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:182537:17)
    at CodeSandboxPreview (http://localhost:9001/main.3a5a94e6d0d91475036e.bundle.js:767:79)
    at renderWithHooks (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:158647:18)
    at mountIndeterminateComponent (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:161326:13)
    at beginWork (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:162440:16)
    at HTMLUnknownElement.callCallback (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:144032:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:144081:16)
    at invokeGuardedCallback (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:144136:31)
    at beginWork$1 (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:167047:7)
    at performUnitOfWork (http://localhost:9001/vendors~main.3a5a94e6d0d91475036e.bundle.js:165998:12)
```

**Describe the solution you'd like**
I'd like to have a way to access the source code of a Story somehow. The `Context` access would be fine.

**Are you able to assist bring the feature to reality?**
Yes, I can possibly.

**Comment by shilman** [comment]
@kevin940726 is this something you can help with?

**Comment by dej611** [comment]
Just to leave a little bit more context, sorry the pun, I've already looked at the [remark-codesandbox](https://github.com/kevin940726/remark-codesandbox) integration (which is great btw!) but in my case I need the Story source code access. :)

**Comment by shilman** [comment]
Aha, sorry I didn't read the issue closely--I was just heading to sleep when I read this. The `SourceContext` is provided by the `SourceContainer` component, which is instantiated in the `DocsContainer` component:

https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/DocsContainer.tsx#L79

I'm not sure why you wouldn't be able to access context from within your DocBlock... 🤔

**Comment by dej611** [comment]
I had some time to get back on this and do some more investigation: the main problem here is that from outside it is not possible to get access to the `SourceContext` as the `SourceContainer` module is not exported in the `addon-docs` bundle.

I managed to get it working on my local machine with a custom version of the addon, having one more export for the `SourceContainer` module:

```js
...
export * from './Source';
export * from './SourceContainer';
...
```
