### ISSUE TITLE
Webpack build failing when setting args for React storybook component

### ISSUE THREAD

**Issue by nad182** [storybookjs/storybook#11504]
**Describe the bug**
When running start-storybook script in React project with Typescript, the script is failing during the webpack build stage at 70% if I'm trying to set `args` for the component. If args are not being set, the build is successful, but the storybook is empty.

An example of `args`:
```jsx
TestButton.args = {
  label: 'Hello',
  onClick: action('clicked'),
  color = { color(colorLabel, defaultColorValue) },
}
```

**To Reproduce**

**Expected behavior**
Successful webpack build.

**Screenshots**

**Code snippets**
```
70%` sealing React Docgen Typescript Plugin node_modules/typescript/lib/typescript.js:11742
        return node.kind === 244 /* FunctionDeclaration */;
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isFunctionDeclaration (/node_modules/typescript/lib/typescript.js:11742:21)
    at Object.getEffectiveTypeAnnotationNode (/node_modules/typescript/lib/typescript.js:16741:37)
    at getIsContextSensitiveAssignmentOrContextType (/node_modules/typescript/lib/typescript.js:55427:52)
    at getContextualTypeForBinaryOperand (/node_modules/typescript/lib/typescript.js:55375:44)
    at getContextualType (/node_modules/typescript/lib/typescript.js:55725:28)
    at getApparentTypeOfContextualType (/node_modules/typescript/lib/typescript.js:55622:17)
    at checkObjectLiteral (/node_modules/typescript/lib/typescript.js:56157:34)
    at checkExpressionWorker (/node_modules/typescript/lib/typescript.js:61672:28)
    at checkExpression (/node_modules/typescript/lib/typescript.js:61595:38)
    at checkExpressionCached (/node_modules/typescript/lib/typescript.js:61273:38)
    at getInitializerTypeFromAssignmentDeclaration (/node_modules/typescript/lib/typescript.js:41811:97)
    at getWidenedTypeForAssignmentDeclaration (/node_modules/typescript/lib/typescript.js:41715:123)
    at getTypeOfVariableOrParameterOrPropertyWorker (/node_modules/typescript/lib/typescript.js:42106:21)
    at getTypeOfVariableOrParameterOrProperty (/node_modules/typescript/lib/typescript.js:42036:28)
    at getTypeOfSymbol (/node_modules/typescript/lib/typescript.js:42364:24)
    at getTypeOfSymbolAtLocation (/node_modules/typescript/lib/typescript.js:54341:20)
```

**System:**
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/addon-controls: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/addon-docs: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/addon-info: ^6.0.0-alpha.2 => 6.0.0-alpha.2 
    @storybook/addon-knobs: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/addon-links: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/addon-notes: ^6.0.0-alpha.6 => 6.0.0-alpha.6 
    @storybook/addons: ^6.0.0-rc.2 => 6.0.0-rc.2 
    @storybook/preset-create-react-app: ^3.1.3 => 3.1.3 
    @storybook/react: ^6.0.0-rc.2 => 6.0.0-rc.2 

**Additional context**
Filing the issue according to the request from @shilman in Discord channel.

**Comment by shilman** [comment]
A couple things are wrong here:
1) you probably shouldn't be mixing args/controls and knobs in the same story -- it might work but we don't support it
2) this is not valid JS/TS AFAIK

```js
color = { color(colorLabel, defaultColorValue) },
```
