### ISSUE TITLE
proxy not working for storybook

### ISSUE THREAD

**Issue by bsdis** [storybookjs/storybook#11551]
To make storybook truly useful it is necessary to be able to interact with a backend storage. That seems to be not really possible. The closest description i have found is a 4 year old issue: https://github.com/storybookjs/storybook/issues/208 which seems to not work anymore.
I am quite amazed how it is possible that this is not a built in feature and i don't understand why there is not a bigger demand for that feature.
I have the following in my .storybook/middleware.js:
```javascript
const { createProxyMiddleware } = require("http-proxy-middleware");

const apiProxy = createProxyMiddleware("/api", {
  target: "http://localhost:8000",
});

module.exports = apiProxy;
```
however when i run `npm run storybook` i get this warning:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at matchSingleStringPath (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/context-matcher.js:43:21)
    at Object.match (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/context-matcher.js:12:16)
    at HttpProxyMiddleware.shouldProxy (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:69:35)
    at HttpProxyMiddleware.<anonymous> (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:27:22)
    at Generator.next (<anonymous>)
    at /Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:4:12)
    at HttpProxyMiddleware.middleware (/Users/baba/projects/z-ui/frontend/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:26:47)
    at _default (/Users/baba/projects/z-ui/frontend/node_modules/@storybook/core/dist/server/dev-server.js:152:3)
    at buildDevStandalone (/Users/baba/projects/z-ui/frontend/node_modules/@storybook/core/dist/server/build-dev.js:343:38)
    at async buildDev (/Users/baba/projects/z-ui/frontend/node_modules/@storybook/core/dist/server/build-dev.js:415:3)
(node:31019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

And the proxying is not working i.e. when trying to access .e.g. 
`stageResponse = await axios.post<StageRemote>("api/org/stage/create", {...` via storybook, it tries to go directly to localhost:9009 where storybook is running instead of going to localhost:8000 which is where it should be proxied to.

Why is this not working, and what needs to be done to be able to proxy requests to the correct backend?

**Comment by Snowshield** [comment]
@bsdis, i try solution from https://github.com/storybookjs/storybook/issues/208#issuecomment-306953718 with your import declaration and it works for me.

```js
const { createProxyMiddleware } = require("http-proxy-middleware");

module.exports = function expressMiddleware (router) {
  router.use('/api', createProxyMiddleware({
    target: "http://localhost:8000",
    changeOrigin: true
  }))
}
```
