### ISSUE TITLE
docs(6.0.0-rc.14) Error: [object Object] is not a valid preset

### ISSUE THREAD

**Issue by qkreltms** [storybookjs/storybook#11676]
**Describe the bug**
I tried using ```.mdx```
An error occurs: Error: [object Object] is not a valid preset 

versions
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
    "@storybook/addon-docs": "^6.0.0-rc.14",
```
main.js
```js
module.exports = {
  stories: ["../src/stories/**/*.stories.(ts|tsx|js|jsx|mdx)"],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    {
      name: '@storybook/addon-docs',
      options: {
        configureJSX: true,
        babelOptions: {},
        sourceLoaderOptions: null,
      },
    },
  ],
};
```
**To Reproduce**
I followed this [instruction](https://gist.github.com/shilman/bc9cbedb2a7efb5ec6710337cbd20c0c#step-2-initialize-storybook-w-ts)  with docs (6.0.0-rc.14)

**Expected behavior**
mdx files should show on storybook.

**Code snippets**
```
D:\playground\storybook\my-app4>yarn storybook
yarn run v1.22.4
$ start-storybook -p 9009 -s public
info @storybook/react v5.3.19
info
? Port 9009 is not available. Would you like to run Storybook on port 9010 instead? Yes
info => Loading static files from: D:\playground\storybook\my-app4\public .
info => Loading presets
WARN   Failed to load preset: {"name":"D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\addon-docs\\preset.js","options":{"configureJSX":true}} on level 1
ERR! Error: [object Object] is not a valid preset
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:206:11)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:194:18)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at getPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:279:25)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\manager\manager-config.js:46:40)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\dev-server.js:57:53)
ERR!     at buildDevStandalone (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\build-dev.js:343:38)
ERR!  { Error: [object Object] is not a valid preset
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:206:11)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:194:18)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at getPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:279:25)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\manager\manager-config.js:46:40)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\dev-server.js:57:53)
ERR!     at buildDevStandalone (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\build-dev.js:343:38)
ERR!   stack:
ERR!    'Error: [object Object] is not a valid preset\n    at loadPreset (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:206:11)\n    at presets.reduce (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:230:20)\n    at Array.reduce (<anonymous>)\n    at loadPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:229:18)\n    at loadPreset (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:194:18)\n    at presets.reduce (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:230:20)\n    at Array.reduce (<anonymous>)\n    at loadPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:229:18)\n    at getPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:279:25)\n    at _default (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\manager\\manager-config.js:46:40)\n    at _default (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\dev-server.js:57:53)\n    at buildDevStandalone (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\build-dev.js:343:38)' }
info => Loading presets
WARN   Failed to load preset: {"name":"D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\addon-docs\\preset.js","options":{"configureJSX":true}} on level 1
ERR! Error: [object Object] is not a valid preset
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:206:11)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:194:18)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at getPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:279:25)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\config.js:48:40)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\dev-server.js:96:106)
ERR!     at buildDevStandalone (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\build-dev.js:343:38)
ERR!  { Error: [object Object] is not a valid preset
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:206:11)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at loadPreset (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:194:18)
ERR!     at presets.reduce (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:230:20)
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:229:18)
ERR!     at getPresets (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\presets.js:279:25)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\config.js:48:40)
ERR!     at _default (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\dev-server.js:96:106)
ERR!     at buildDevStandalone (D:\playground\storybook\my-app4\node_modules\@storybook\core\dist\server\build-dev.js:343:38)
ERR!   stack:
ERR!    'Error: [object Object] is not a valid preset\n    at loadPreset (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:206:11)\n    at presets.reduce (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:230:20)\n    at Array.reduce (<anonymous>)\n    at loadPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:229:18)\n    at loadPreset (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:194:18)\n    at presets.reduce (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:230:20)\n    at Array.reduce (<anonymous>)\n    at loadPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:229:18)\n    at getPresets (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\presets.js:279:25)\n    at _default (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\config.js:48:40)\n    at _default (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\dev-server.js:96:106)\n    at buildDevStandalone (D:\\playground\\storybook\\my-app4\\node_modules\\@storybook\\core\\dist\\server\\build-dev.js:343:38)' }
info => Adding stories defined in ".storybook\main.js".
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack setup.
webpack built e22dfa9d419ba682c176 in 12285ms
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 5.3.19 started                         │
│   16 s for manager and 16 s for preview            │
│                                                    │
│    Local:            http://localhost:9010/        │
│    On your network:  http://192.168.0.153:9010/    │
│                                                    │
╰────────────────────────────────────────────────────╯
```
**Additional context**
Downgrading to ```"@storybook/addon-docs": "^5.3.19",``` fixes this issue.

**Comment by shilman** [comment]
`npx sb@next upgrade --prerelease`
