### ISSUE TITLE
Failure when custom-elements-json misses an element definition

### ISSUE THREAD

**Issue by priandsf** [storybookjs/storybook#11831]
**Describe the bug**
When custom-element.json misses the definition and the element is referenced in a story, storybook fails, displaying an exception. Even worse, the whole storybook doesn't load, not even the story list. So the other stories are not available.

**To Reproduce**
Create a web component story and reference an element that is not in your custom-elements.json:
export default {
    title: 'failing story',
    component: 'fake-component'
}
Start storybook
using Storybook 6.0.0-rc.28

**Expected behavior**
We should have a clear message stating that it can't find the definition for "fake-component". The rest of storybook should load, and at least the other stories should work.

**Screenshots**
Cannot read property 'attributes' of undefined
TypeError: Cannot read property 'attributes' of undefined
    at extractArgTypesFromElements (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:10384:109)
    at extractArgTypes (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:10392:10)
    at enhanceArgTypes (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:9978:58)
    at _this$_argTypesEnhanc._argTypesEnhancers.reduce.Object.assign.__isArgsStory (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:15746:21)
    at Array.reduce (<anonymous>)
    at StoryStore.addStory (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:15744:59)
    at Object.api.add (http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:14207:25)
    at http://localhost:6006/vendors~main.d6c54eb9db58fd371579.bundle.js:28209:16
    at Array.forEach (<anonymous>)
...

**Comment by Marklb** [comment]
It isn't unique to web-components, I got this earlier when I updated one of my Angular apps. I thought something must have been messed up with a locally cached file or something, because I restarted Storybook and didn't get the error. Didn't realize I accidentally fixed it when I made a change to the tsconfig I use for `compdoc`

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.7 containing PR #12012 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.
