### ISSUE TITLE
Ember Stories not Shown when Using Unicode Characters

### ISSUE THREAD

**Issue by gossi** [storybookjs/storybook#11853]
I'm using SB `v6-rc.29`. I love it for ember it is almost usable without any special config, even in combination with typescript, this is impressive (at least for addons, still need to check apps).

However, I realized one problem with unicode characters.
This is the code for my story:

```ts
export const Accessibility = () => {
  return {
    template: hbs`
      <Button aria-label="Go Tomster!">
        <span aria-hidden="true">🐹</span>
      </Button>
    `
  };
};
```

Which results in this error (it shows warning, but all the stories do not render):

```
WARNING in ../packages/buttons/addon/components/button/stories.ts
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/thomas/code/packages/hokulea/packages/buttons/addon/components/button/stories.ts: Can't reference '{"id":"GV7bUfA4","block":"{\"symbols\":[],\"statements\":[[2,\"\\n      \"],[8,\"button\",[[24,\"aria-label\",\"Go Tomster!\"]],[[],[]],[[\"default\"],[{\"statements\":[[2,\"\\n        \"],[10,\"span\"],[14,\"aria-hidden\",\"true\"],[12],[2,\"🐹\"],[13],[2,\"\\n      \"]],\"parameters\":[]}]]],[2,\"\\n    \"]],\"hasEval\":false,\"upvars\":[]}","meta":{}}' as a bare identifier (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/Users/thomas/code/packages/hokulea/node_modules/@babel/core/lib/transformation/file/file.js:248:12)
    at NodePath.buildCodeFrameError (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/path/index.js:144:21)
    at PluginPass.Identifier (/Users/thomas/code/packages/hokulea/node_modules/@babel/plugin-transform-unicode-escapes/lib/index.js:96:20)
    at newFn (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitQueue (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:118:21)
    at TraversalContext.visitSingle (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/thomas/code/packages/hokulea/node_modules/@babel/traverse/lib/context.js:140:19)
 @ (?:^|\/)\.).)*?)\/)stories\.ts)$ (../packages sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)stories\.ts)$) ./buttons/addon/components/button/stories.ts
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ../node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-other-entry.js ../node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ../node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ../node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

Now, if I add this loader back on my `.storybook/main.js`, it will work:

```js
const hbsBabelLoader = {
  loader: "babel-loader",
  options: {
    presets: ['@babel/preset-env', '@babel/preset-typescript'],
    plugins: [
      [
        require.resolve('babel-plugin-htmlbars-inline-precompile'),
        {
          precompile,
          modules: {
            'ember-cli-htmlbars': 'hbs',
            'ember-cli-htmlbars-inline-precompile': 'default',
            'htmlbars-inline-precompile': 'default',
          }
        }
      ]
    ]
  }
};

// ...

// add the loader to webpack

    config.module.rules.push({
      test: /\.ts$/,
      use: [
        hbsBabelLoader
      ],
    });
```

Then this will work. My assumption:

When removing it, it will take the loader decided in here: https://github.com/storybookjs/storybook/blob/1c7f120c401d5a8f51645f830dde7e4acd4e3bb1/lib/core/src/server/preview/babel-loader-preview.js#L5 + all later additions (such as the plugin added by ember). Amongst all them, it will have the same parts as my own `hbsBabelLoader`. Probably some of the additional stuff has an issue on unicode characters - that's my guess on the moment

**Comment by gossi** [comment]
I think I can close this bug here. This is not only affecting storybook but also embers pipeline (such as testing).

The reason: An interplay between babel unicode emoji transform and htmlbars inline precompile.

Please refer to:

- Bug: emberjs/ember.js#19251
- Testcase: ember-cli/babel-plugin-htmlbars-inline-precompile#297

Workarounds:

- Drop IE11 from targets compilation 💪
- Exclude babel transform unicode emoji (refer to referenced bug)
- Run your own transform (refer to first post)
