### ISSUE TITLE
Storybook Docs spread syntax not working

### ISSUE THREAD

**Issue by BaR488** [storybookjs/storybook#11886]
**Describe the bug**
Spread syntax don't work in mdx story file.

**To Reproduce**
We use angular storybook.
I try to create story with CSF:

myfile.stories.ts
```
export default {
    title: 'Components/EiisMenu',
    decorators: [
        moduleMetadata({
            imports: [
                EiisMenuModule,
                BrowserAnimationsModule,
                EiisMenuWikiModule
            ],
        }),
        withKnobs
    ],
    parameters: {
        subcomponents: {EiisMenuComponent, EiisMenuTriggerComponent,  EiisMenuItemComponent}
    },
    includeStories: []
};
```

Then in mdx file i try to use spread syntax like this:

myfile.stories.mdx
```
import meta from 'myfile.stories.ts';
<Meta
    {...meta}/>
```

```
Module build failed (from ./node_modules/@mdx-js/loader/index.js):
TypeError: Cannot read property 'name' of undefined
    at /Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:78:19
    at Array.find (<anonymous>)
    at getAttr (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:77:29)
    at genMeta (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:221:15)
    at getExports (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:304:15)
    at /Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:407:19
    at Array.forEach (<anonymous>)
    at extractExports (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:406:17)
    at Compiler (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/@storybook/addon-docs/dist/mdx/mdx-compiler-plugin.js:454:14)
    at Function.stringify (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/unified/index.js:354:12)
    at pipelineStringify (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/unified/index.js:41:18)
    at wrapped (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/trough/wrap.js:25:19)
    at next (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/trough/index.js:57:24)
    at done (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/trough/wrap.js:55:16)
    at done (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/unified/index.js:35:7)
    at done (/Users/boriskarabanov/dev/work/proit/projects/eiis-gui/node_modules/unified/index.js:314:11)
```

**System:**

```

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 70.0.1
    Safari: 13.1.2
```

**Comment by shilman** [comment]
That's not supported by our MDX to CSF compiler, you'll need specify the `Meta` attributes individually.

**Comment by BaR488** [comment]
> That's not supported by our MDX to CSF compiler, you'll need specify the `Meta` attributes individually.

Do you plan to support spread syntax in MDX to CSF compiler.

**Comment by shilman** [comment]
> Do you plan to support spread syntax in MDX to CSF compiler?

PRs welcome!

**Comment by andrewplummer** [comment]
This has caused me frustration as well. MDX is by definition JSX embedded inside markdown yet it seems basic JSX syntax doesn't work (same goes for HOCs which also don't work).

I get that it's evolving and likely complicated but at the very least there should be a big red note in the [docs](https://storybook.js.org/docs/react/writing-docs/mdx#gatsby-focus-wrapper) explaining the limitations here.
