### ISSUE TITLE
Unable to build Storybook after upgrading to v6 (complains about invalid import)

### ISSUE THREAD

**Issue by WesCossick** [storybookjs/storybook#12119]
**Describe the bug**
Unable to build Storybook after upgrade to v6, due to a `'import' and 'export' may only appear at the top level` error message.

**To Reproduce**

1. Run `yarn build-storybook` in project with the below code snippet
2. See error

**Expected behavior**
The build to succeed as it did before upgrading to v6.

**Code snippets**
The file it's complaining about is:

```typescript
// Imports
import React from 'react';
import { Switch, Route } from 'react-router-dom';
import NotFound from 'shareables/admin-template/components/pages/not-found';
import MemberView from 'components/sections/members/views/member';
import AccountView from 'components/sections/members/views/account';
import Invite from 'components/sections/members/invite';
import ImportMembers from 'components/sections/members/import';
import EditAccount from 'components/sections/members/edit-account';
import ReviewAccounts from 'components/sections/members/review-accounts';
import Addresses from 'components/sections/members/addresses';
import UpsertAddress from 'components/sections/members/upsert-address';
import EditAddress from 'components/sections/members/upsert-address/edit';
import SuspendAccount from 'components/sections/members/suspend-account';
import MergeAccounts from 'components/sections/members/merge-accounts';
import ViewMember from 'components/sections/members/view-member';
import EditMember from 'components/sections/members/edit-member';
import Privileges from 'components/sections/members/privileges';


// Function component
const SectionRoutes: React.FC = () => {
	// Return JSX
	return (
		<Switch>
			<Route exact path='/members/' component={MemberView} />
			<Route exact path='/members/invite' component={Invite} />
			<Route exact path='/members/import' component={ImportMembers} />
			<Route exact path='/members/accounts/' component={AccountView} />
			<Route exact path='/members/accounts/review' component={ReviewAccounts} />
			<Route exact path='/members/accounts/:accountID/addresses/' component={Addresses} />
			<Route exact path='/members/accounts/:accountID/addresses/add' component={UpsertAddress} />
			<Route exact path='/members/accounts/:accountID/addresses/:addressID/edit' component={EditAddress} />
			<Route exact path='/members/accounts/:accountID/edit' component={EditAccount} />
			<Route exact path='/members/accounts/:accountID/suspend' component={SuspendAccount} />
			<Route exact path='/members/accounts/:accountID/merge' component={MergeAccounts} />
			<Route exact path='/members/:memberID/view' component={ViewMember} />
			<Route exact path='/members/:memberID/edit' component={EditMember} />
			<Route exact path='/members/:memberID/privileges' component={Privileges} />
			<Route component={NotFound} />
		</Switch>
	);
};

export default SectionRoutes;
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 75.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-essentials: 6.x.x => 6.0.12 
    @storybook/preset-create-react-app: 3.x.x => 3.1.4 
    @storybook/react: 6.x.x => 6.0.12
```

**Command output**
```
yarn run v1.22.4
$ build-storybook -s public
info @storybook/react v6.0.12
info 
info clean outputDir..
info => Copying static files from: public
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Compiling manager..
info => manager built (6.81 s)
info => Building preview..
info => Loading preview config..
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook/main.js".
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Loading custom Webpack config (full-control mode).
info => Compiling preview..
ERR! => Failed to build the preview
ERR! chunk 10
ERR! 10.b56061dc1f39660b1727.bundle.js
ERR! /node_modules/babel-loader/lib/index.js??ref--7-oneOf-1!/node_modules/eslint-loader/dist/cjs.js??ref--6-0!/src/components/sections/members/section-routes.tsx cd3e7398b9ebabdf40900430b9d5259f
ERR! 'import' and 'export' may only appear at the top level (18:4)
ERR! | try {
ERR! |     // @ts-ignore
ERR! |     import.displayName = "import";
ERR! |     // @ts-ignore
ERR! |     import.__docgenInfo = { "description": "", "displayName": "import", "props": {} };
ERR! SyntaxError: /node_modules/babel-loader/lib/index.js??ref--7-oneOf-1!/node_modules/eslint-loader/dist/cjs.js??ref--6-0!/src/components/sections/members/section-routes.tsx cd3e7398b9ebabdf40900430b9d5259f
ERR! 'import' and 'export' may only appear at the top level (18:4)
ERR! | try {
ERR! |     // @ts-ignore
ERR! |     import.displayName = "import";
ERR! |     // @ts-ignore
ERR! |     import.__docgenInfo = { "description": "", "displayName": "import", "props": {} };
ERR!     at Parser.pp$4.raise (/node_modules/acorn/dist/acorn.js:2825:15)
ERR!     at Parser.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:859:18)
ERR!     at Parser.pp$1.parseBlock (/node_modules/acorn/dist/acorn.js:1161:23)
ERR!     at Parser.pp$1.parseTryStatement (/node_modules/acorn/dist/acorn.js:1064:23)
ERR!     at Parser.pp$1.parseStatement (/node_modules/acorn/dist/acorn.js:838:34)
ERR!     at Parser.pp$1.parseTopLevel (/node_modules/acorn/dist/acorn.js:746:23)
ERR!     at Parser.parse (/node_modules/acorn/dist/acorn.js:553:17)
ERR!     at Function.parse (/node_modules/acorn/dist/acorn.js:576:37)
ERR!     at Function.parse (/node_modules/@storybook/core/node_modules/webpack/lib/Parser.js:2409:22)
ERR!     at ConcatenatedModule.source (/node_modules/@storybook/core/node_modules/webpack/lib/optimize/ConcatenatedModule.js:716:19)
ERR!     at ModuleTemplate.render (/node_modules/@storybook/core/node_modules/webpack/lib/ModuleTemplate.js:54:32)
ERR!     at /node_modules/@storybook/core/node_modules/webpack/lib/Template.js:233:28
ERR!     at Array.map (<anonymous>)
ERR!     at Function.renderChunkModules (/node_modules/@storybook/core/node_modules/webpack/lib/Template.js:230:30)
ERR!     at JavascriptModulesPlugin.renderJavascript (/node_modules/@storybook/core/node_modules/webpack/lib/JavascriptModulesPlugin.js:159:34)
ERR!     at Object.render (/node_modules/@storybook/core/node_modules/webpack/lib/JavascriptModulesPlugin.js:107:14)
(node:83910) UnhandledPromiseRejectionWarning: [object Object]
(Use `node --trace-warnings ...` to show where the warning was created)
(node:83910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:83910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by WesCossick** [comment]
Moving the `ImportMembers` component from `.../import` to `.../import-members` works around the issue, but is sort of a bandaid.

**Comment by WesCossick** [comment]
Bump. Bug remains.

**Comment by WesCossick** [comment]
Bump.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by WesCossick** [comment]
This came from a large private repo, but I could potentially create a public version that reproduces the issue if it's truly necessary. Based on my comment above, it looks like it's caused by having an import ending in `/import` since renaming it to `/import-members` fixed the issue.

**Comment by ndelangen** [comment]
Without a reproduction there's nothing we can really do.
