### ISSUE TITLE
source-loader fails if code has an exported value

### ISSUE THREAD

**Issue by sergeyt** [storybookjs/storybook#12351]
**Describe the bug**

@storybook/source-loader fails on adding export const

**To Reproduce**

```typescript
// adding such export breaks source loader
export const treeData = [];
```
source-loader fails with the error:

```
Module build failed (from ./node_modules/@storybook/source-loader/dist/index.js):
TypeError: Cannot read property 'type' of null
    at /node_modules/@storybook/source-loader/dist/abstract-syntax-tree/parse-helpers.js:96:75
    at Array.find (<anonymous>)
    at findTemplate (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/parse-helpers.js:88:16)
    at expandBindExpression (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/parse-helpers.js:119:22)
    at handleExportedName (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/parse-helpers.js:131:14)
    at Controller.enter (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/traverse-helpers.js:161:58)
    at Controller.__execute (/node_modules/estraverse/estraverse.js:330:31)
    at Controller.traverse (/node_modules/estraverse/estraverse.js:434:28)
    at Object.traverse (/node_modules/estraverse/estraverse.js:646:27)
    at findExportsMap (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/traverse-helpers.js:151:14)
    at generateStoriesLocationsMap (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/generate-helpers.js:220:61)
    at inject (/node_modules/@storybook/source-loader/dist/abstract-syntax-tree/inject-decorator.js:65:66)
    at readAsObject (/node_modules/@storybook/source-loader/dist/dependencies-lookup/readAsObject.js:26:48)
    at readStory (/node_modules/@storybook/source-loader/dist/dependencies-lookup/readAsObject.js:42:10)
    at Object.transform (/node_modules/@storybook/source-loader/dist/build.js:13:38)
 @ \.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$ (./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$) ./purejs/grid/basic.stories.ts
 @ ./.storybook/generated-stories-entry.js
```

**Expected behavior**

Such exports must be ignored

**System:**

```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.21 => 6.0.21
    @storybook/addon-actions: ^6.0.21 => 6.0.21
    @storybook/addon-essentials: ^6.0.21 => 6.0.21
    @storybook/addon-links: ^6.0.21 => 6.0.21
    @storybook/addon-storysource: ^6.0.21 => 6.0.21
    @storybook/html: ^6.0.21 => 6.0.21
```

**Comment by sergeyt** [comment]
`findTemplate` function fails on [line 39](https://github.com/storybookjs/storybook/blob/master/lib/source-loader/src/abstract-syntax-tree/parse-helpers.js#L39).

```javascript
  if (
      node.type === 'ExportNamedDeclaration' &&
      node.declaration &&
      node.declaration.type === 'VariableDeclaration'
    ) {
      declarations = node.declaration.declarations;
    }
```

i.e. we can add `node.declaration &&` precondition check as quick fix.

but this does not provide a full solution since such export is displayed as story and when clicking on such story, it fails.

as workaround don't write such exports or wrap such values into functions

**Comment by shilman** [comment]
@sergeyt all named exports are treated as stories in CSF. you can exclude certain exports if needed:

https://storybook.js.org/docs/react/api/csf#non-story-exports

**Comment by sergeyt** [comment]
@shilman yes I figured this out. IMO source-loader could handle this mistake to make it safer. I don't mind if you close this one.

**Comment by shilman** [comment]
Closing this. I'm simplifying source loader and might try to address this in the rewrite.
