### ISSUE TITLE
Running npx build-storybook -o ../ permanently erases parent directory from hard drive 

### ISSUE THREAD

**Issue by whenmoon** [storybookjs/storybook#12352]
**Describe the bug**
Running `npx build-storybook -o ../` throws error and permanently erases parent directory from hard drive.

**To Reproduce**
npx build-storybook -o ../

**Expected behavior**
A production build of storybook is created

**Code snippets**
```bash
npx build-storybook -o ../

info @storybook/react v5.3.1
info
info clean outputDir..
cp: no such file or directory: .../node_modules/@storybook/core/dist/server/public/favicon.ico
info => Copying prebuild dll's..
cp: no such file or directory: .../node_modules/@storybook/core/dll/*
info => Building manager..
info => Loading manager config..
(node:1543) UnhandledPromiseRejectionWarning: Error: Cannot find module './manager/manager-preset.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at buildManager (.../controls-library/node_modules/@storybook/core/dist/server/build-static.js:167:27)
    at buildStaticStandalone (.../node_modules/@storybook/core/dist/server/build-static.js:245:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
(node:1543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**System:**
  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.21.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 78.0.2
    Safari: 12.1.1

**Additional context**
All contents of parent folder deleted (removed from hard drive - not in trash) apart from a folder called `sb_dll`

**Comment by ndelangen** [comment]
uhm... yeah that makes sense?

run this instead:
```
npx build-storybook
```
