### ISSUE TITLE
Support for styled-components

### ISSUE THREAD

**Issue by Gieted** [storybookjs/storybook#12387]
```jsx
// Button.jsx

function Button({title, onClick}) {
  return (
    <div className="Button">
      <h1>{ title }</h1>
      <button onClick={onClick}>Click me!</button>
    </div>
  );
}

Button.defaultProps = {
  title: 'My Button'
};

export default styled(Button)`
  background-color: red;
`;
```

```jsx
// Button.stories.jsx

export default {
  title: 'Button',
  component: Button
}

export const Default = (args) => <Button {...args}  />;
```

Storybook seems to not be able to read React components correctly if they are passed through `styled` from styled-components. Controls aren't automatically generated and actions aren't logged.

Is there any way to make styled-components and Storybook work together?

**Comment by shilman** [comment]
Related: #11933 which is the typescript equivalent of this issue

I don't see any typescript types or proptypes on your component. Is that a copy-paste error?

What happens when you run `react-docgen` directly on your component? That's what we use under the hood. If it fails, we can either look for a fix there or try to figure out an appropriate way to preprocess the component.

**Comment by Gieted** [comment]
I'm not sure what you mean by "a copy-paste error". 

`react-docgen` gives:
```
Error with path "src/Button/Button.jsx": Error: No suitable component definition found.
Error: No suitable component definition found.
    at parse (C:\Users\Gieted\Projekty\test\node_modules\react-docgen\dist\parse.js:74:9)
    at Object.defaultParse [as parse] (C:\Users\Gieted\Projekty\test\node_modules\react-docgen\dist\main.js:61:29)
    at parse (C:\Users\Gieted\Projekty\test\node_modules\react-docgen\bin\react-docgen.js:106:17)
    at C:\Users\Gieted\Projekty\test\node_modules\react-docgen\bin\react-docgen.js:210:32
    at FSReqCallback.oncomplete (fs.js:169:5)
```

**Comment by shilman** [comment]
What happens when you declare prop types for your component?

**Comment by Gieted** [comment]
```tsx
// Button.tsx

export type ButtonProps = {
  title: string,
  onClick: () => void
}

function Button({title, onClick}: ButtonProps) {
  return (
    <div className="Button">
      <h1>{ title }</h1>
      <button onClick={onClick}>Click me!</button>
    </div>
  );
}

Button.defaultProps = {
  title: 'My Button'
};

export default styled(Button)`
  background-color: red;
`;
```

```tsx
//Button.stories.tsx

export default {
  title: 'Button',
  component: Button
} as Meta

export const Default: Story<ButtonProps> = (args) => <Button {...args}  />;


It's exactly the same for a typescript project.

**Comment by shilman** [comment]
Closing this as a duplicate to #11933
