### ISSUE TITLE
Missing Migration for Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.

### ISSUE THREAD

**Issue by jsoref** [storybookjs/storybook#12579]
**Describe the bug**

> (node:16713) DeprecationWarning: Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.
> Read more about it in the migration guide: https://github.com/storybookjs/storybook/blob/master/MIGRATION.md

**To Reproduce**

1. Read #10553
1. See error
1. Read hint
1. Follow url to https://github.com/storybookjs/storybook/blob/master/MIGRATION.md
1. Search for `Configuration files`

**Expected behavior**
A section that talks about
> Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.

**Screenshots**

**Code snippets**

**System:**

**Additional context**

**Comment by jsoref** [comment]
For reference, this is the input I'm looking at: https://github.com/argoproj/argo-ui/blob/master/.storybook/config.js
I tried following the updated instructions from #12582, but even
```
diff --git a/.storybook/config.js b/.storybook/config.js
deleted file mode 100644
index 94f6c46..0000000
--- a/.storybook/config.js
+++ /dev/null
@@ -1,9 +0,0 @@
-import { configure } from '@storybook/react';
-
-// automatically import all files ending in *.stories.js
-const req = require.context('../stories', true, /.stories.tsx$/);
-function loadStories() {
-  req.keys().forEach((filename) => req(filename));
-}
-
-configure(loadStories, module);
diff --git a/.storybook/main.js b/.storybook/main.js
new file mode 100644
index 0000000..69850e9
--- /dev/null
+++ b/.storybook/main.js
@@ -0,0 +1,4 @@
+module.exports = {
+  stories: ['../stories/**/*.stories.tsx'],
+  addons: [''],
+};
```
fails fairly miserably:
```
$ build-storybook -o ./dist/storybook
info @storybook/react v6.0.21
info
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
WARN   Failed to load preset: {"name":"","type":"presets"} on level 1
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at validateString (internal/validators.js:121:11)
ERR!     at Module.require (internal/modules/cjs/loader.js:1082:3)
ERR!     at require (internal/modules/cjs/helpers.js:73:18)
ERR!     at interopRequireDefault (argoproj/argo-ui/node_modules/@storybook/core/dist/server/presets.js:149:16)
```

Rough sense of the environment:
```
$ egrep 'dev|story' package.json
        "build": "build-storybook -o ./dist/storybook",
        "start": "start-storybook -p 6006"
        "history": "^4.7.2",
    "devDependencies": {
        "@dump247/storybook-state": "^1.5.0",
        "@storybook/addon-actions": "^6.0.21",
        "@storybook/addon-links": "^6.0.21",
        "@storybook/addons": "^6.0.21",
        "@storybook/react": "^6.0.21",
        "@types/history": "^4.7.8",
        "@types/storybook__addon-actions": "^5.2.1",
        "@types/storybook__addon-knobs": "^5.2.1",
        "@types/storybook__addon-links": "^5.2.1",
        "@types/storybook__addon-notes": "^5.0.2",
        "@types/storybook__addon-options": "^5.2.1",
        "@types/storybook__react": "^5.2.1",
        "webpack-dev-server": "^3.7.2"
```

**Comment by FedericoOdigeo** [comment]
I have also upgraded with npx command and i'm facing this issue

**Comment by mzedeler** [comment]
+1

**Comment by DarioRega** [comment]
+1
