### ISSUE TITLE
Cannot read property 'publicPath' of undefined

### ISSUE THREAD

**Issue by PaulExina** [storybookjs/storybook#12595]
```
ERR! TypeError: Cannot read property 'publicPath' of undefined
ERR!     at /Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/dev-server.js:116:43
ERR!     at async Promise.all (index 1)
ERR!     at async buildDevStandalone (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:438:28)
ERR!     at async buildDev (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:520:3)
ERR!  TypeError: Cannot read property 'publicPath' of undefined
ERR!     at /Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/dev-server.js:116:43
ERR!     at async Promise.all (index 1)
ERR!     at async buildDevStandalone (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:438:28)
ERR!     at async buildDev (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:520:3) {
ERR!   stack: "TypeError: Cannot read property 'publicPath' of undefined\n" +
ERR!     '    at /Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/dev-server.js:116:43\n' +
ERR!     '    at async Promise.all (index 1)\n' +
ERR!     '    at async buildDevStandalone (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:438:28)\n' +
ERR!     '    at async buildDev (/Users/paulexina/Documents/workspace/app.october.eu/node_modules/@storybook/core/dist/server/build-dev.js:520:3)'
ERR! }
```
**To Reproduce**

Run `npm run storybook` after setup and initialization.

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.0.22 => 6.0.22 
    @storybook/addon-essentials: ^6.0.22 => 6.0.22 
    @storybook/addon-links: ^6.0.22 => 6.0.22 
    @storybook/ember: ^6.0.22 => 6.0.22 
```

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by PaulExina** [comment]
Since I am trying to use it in my professional environnement, I can not share the repository with you.
What more informations do you need ?

**Comment by shilman** [comment]
Based on the error it looks like the output of your `webpack` or `webpackFinal` config is null, or doesn't contain the `output` field.

If you provide a repro repo somebody can tell you exactly what's wrong.
