### ISSUE TITLE
Could not find plugin "proposal-class-properties".

### ISSUE THREAD

**Issue by rwieruch** [storybookjs/storybook#12592]
Just in case anyone is running into this. I ran into the following bug when starting Storybook after upgrading it from **5.3.19**  to **6.0.22**:

```
ERROR in ./.storybook/generated-refs.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/.storybook/generated-refs.js: Could not find plugin "proposal-class-properties". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/preset-env/lib/index.js")
    at getPlugin (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/preset-env/lib/index.js:67:11)
    at /Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/preset-env/lib/index.js:258:62
    at Array.map (<anonymous>)
    at /Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/preset-env/lib/index.js:258:43
    at /Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/gensync/index.js:254:32)
    at evaluateAsync (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/gensync/index.js:284:5)
    at Function.errback (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/gensync/index.js:108:7)
    at errback (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/gensync/index.js:183:31)
    at onFirstPause (/Users/mydspr/Developer/Repos/Trumpf/treact-ui/ui-components/node_modules/gensync/index.js:209:13)
    at Generator.next (<anonymous>)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core/dist/client/manager/index.js ./node_modules/@storybook/addon-knobs/dist/register.js ./node_modules/@storybook/addon-a11y/dist/register.js ./node_modules/@storybook/addon-storysource/register.js ./node_modules/@storybook/addon-docs/dist/register.js ./.storybook/generated-refs.js main[7]
```

In order to fix this, I had to upgrade my Babel dependencies (I am using a custom Webpack/Babel configuration if it matters):

`npx npm-check-updates '/babel/' -u`

With an `npm install` everything worked as expected, after following the other migration instructions.

**Comment by myufa** [comment]
What were your babel deps and webpack version?
