### ISSUE TITLE
"yarn dev" results to  "too many open files, watch 'src'"

### ISSUE THREAD

**Issue by profanis** [storybookjs/storybook#12642]
**Describe the bug**
I followed the steps that are described in the [contribution readme](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#pull-requests-prs) file, and I can not have the app running because of the following error.

The error is:

```
[1] @storybook/addon-storyshots: Error: EMFILE: too many open files, watch 'src'
[1] @storybook/addon-storyshots:     at FSWatcher.start (internal/fs/watchers.js:169:26)
[1] @storybook/addon-storyshots:     at Object.watch (fs.js:1422:11)
[1] @storybook/addon-storyshots:     at createFsWatchInstance (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:38:15)
[1] @storybook/addon-storyshots:     at setFsWatchListener (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:81:15)
[1] @storybook/addon-storyshots:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:233:14)
[1] @storybook/addon-storyshots:     at FSWatcher.NodeFsHandler._handleDir (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:429:19)
[1] @storybook/addon-storyshots:     at FSWatcher.<anonymous> (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:477:19)
[1] @storybook/addon-storyshots:     at FSWatcher.<anonymous> (/home/fanis/projects/contributions/storybook/node_modules/@babel/cli/node_modules/chokidar/lib/nodefs-handler.js:482:16)
[1] @storybook/addon-storyshots:     at FSReqCallback.oncomplete (fs.js:169:5) {
[1] @storybook/addon-storyshots:   errno: -24,
[1] @storybook/addon-storyshots:   syscall: 'watch',
[1] @storybook/addon-storyshots:   code: 'EMFILE',
[1] @storybook/addon-storyshots:   path: 'src',
[1] @storybook/addon-storyshots:   filename: 'src'
[1] @storybook/addon-storyshots: }
[1] @storybook/addon-storyshots-puppeteer: Failed to compile js
[1] lerna ERR! cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-babel.js exited 1 in '@storybook/addon-storyshots-puppeteer'
[1] lerna ERR! cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-babel.js stdout:
[1] Successfully compiled 0 files with Babel (153ms).
```

**To Reproduce**

1. `git clone https://github.com/storybookjs/storybook.git`
2. `cd storybook`
3. `yarn bootstrap --core`
4. `yarn dev`

**Expected behavior**
Compile the app and start a web server

**System**
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.18.3 - ~/nodeenvs/12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/nodeenvs/12.18.3/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
  npmPackages:
    @storybook/eslint-config-storybook: ^2.4.0 => 2.4.0 
    @storybook/linter-config: ^2.5.0 => 2.5.0 
    @storybook/semver: ^7.3.2 => 7.3.2 
```

**Comment by shilman** [comment]
we have a new command, `yarn build [a b c] --watch` where `a b c` are the suffixes of the packages you're working on, e.g. `yarn build core client-api addon-docs components --watch`. @yannbf can you update the contributing docs?

**Comment by yannbf** [comment]
No need to update, [it's already there](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#building-specific-packages)!

**Comment by profanis** [comment]
If the `yarn dev` is not a valid command or has issues (like the one I mentioned), maybe a fix on the  [initial-setup](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#initial-setup) with a link to the [building specific packages](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#building-specific-packages) would do the trick.

**Comment by profanis** [comment]
> we have a new command, `yarn build [a b c] --watch` where `a b c` are the suffixes of the packages you're working on, e.g. `yarn build core client-api addon-docs components --watch`. @yannbf can you update the contributing docs?

Thanks for this @shilman!

**Comment by profanis** [comment]
> No need to update, [it's already there](https://github.com/storybookjs/storybook/blob/next/CONTRIBUTING.md#building-specific-packages)!

@yannbf I'd like to contribute with a snippet [here](https://storybook.js.org/docs/angular/writing-stories/decorators).
Do I have to run another command apart from `yarn start`?

**Comment by yannbf** [comment]
Hey @profanis, so actually the documentation is in another repository called [frontpage](https://github.com/storybookjs/frontpage). The snippets are extracted from the monorepo, so you don't really need to build the monorepo, just build and run frontpage but edit the files which are linked from the monorepo. If you need further assistance let me know!

**Comment by profanis** [comment]
> Hey @profanis, so actually the documentation is in another repository called [frontpage](https://github.com/storybookjs/frontpage). The snippets are extracted from the monorepo, so you don't really need to build the monorepo, just build and run frontpage but edit the files which are linked from the monorepo. If you need further assistance let me know!

Thanks for this @yannbf
