### ISSUE TITLE
build-storybook returns 0 status code when error happens

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#12858]
**Describe the bug**
`build-storybook` can error out and should set a non-zero status code, but it sets the status code to 0

**To Reproduce**
Run with an invalid configuration and observe status code of 0

**Expected behavior**
status code is non-zero to indicate that an error happened.

**Additional context**
Here's an example output (we had `terser` and `terser-webpack-plugin` resolved to a 5.x release and it broke with a recent update but the build didn't fail like it should have because the status code was 0):
```
info @storybook/react v5.3.21
info 
info clean outputDir..
info => Copying static files from: ./public
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Loading custom babel config
info => Loading custom manager config.
info => Compiling manager..
(node:10659) UnhandledPromiseRejectionWarning: ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, parallel?, minify?, terserOptions?, extractComments? }
    at validate (/Users/dlj/projects/sb_test/node_modules/terser-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new TerserPlugin (/Users/dlj/projects/sb_test/node_modules/terser-webpack-plugin/dist/index.js:32:31)
    at Object.apply (/Users/dlj/projects/sb_test/node_modules/webpack/lib/WebpackOptionsDefaulter.js:310:6)
    at WebpackOptionsApply.process (/Users/dlj/projects/sb_test/node_modules/webpack/lib/WebpackOptionsApply.js:481:16)
    at webpack (/Users/dlj/projects/sb_test/node_modules/webpack/lib/webpack.js:57:48)
    at /Users/dlj/projects/sb_test/node_modules/@storybook/core/dist/server/build-static.js:47:26
    at new Promise (<anonymous>)
    at compileManager (/Users/dlj/projects/sb_test/node_modules/@storybook/core/dist/server/build-static.js:46:10)
    at buildManager (/Users/dlj/projects/sb_test/node_modules/@storybook/core/dist/server/build-static.js:177:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:66:3)
(node:10659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by shilman** [comment]
Closing as dupe to #10405
