### ISSUE TITLE
Clean vue 3 project and storybook 6.1 not working

### ISSUE THREAD

**Issue by eikooc** [storybookjs/storybook#13224]
**Describe the bug**
Storybook does not compile vue project because it cannot find a specific module (`vue/dist/vue.esm.js`)

**To Reproduce**

1. clone https://github.com/eikooc/test-storybook-vue3 or start a clean vue3 project
2. Run `npm install`
3. Run `npm run storybook`
4. See error:
```
> test-storybook@0.1.0 storybook /home/vue/test-storybook
> start-storybook -p 6006

info @storybook/vue v6.1.2
info 
info => Using prebuilt manager
info => Loading presets
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook/main.js"
ERR! Error: Cannot find module 'vue/dist/vue.esm.js'
ERR! Require stack:
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/config.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/server.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/index.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:83:19)
ERR!     at Object.webpack (/home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js:42:23)
ERR!     at /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js:259:28
ERR!     at async startPreview (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:367:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:454:28)
ERR!     at async buildDevStandalone (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:311:33)
ERR!     at async buildDev (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:374:3)
ERR!  Error: Cannot find module 'vue/dist/vue.esm.js'
ERR! Require stack:
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/config.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/core/server.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/index.js
ERR! - /home/vue/test-storybook/node_modules/@storybook/vue/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:83:19)
ERR!     at Object.webpack (/home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js:42:23)
ERR!     at /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js:259:28
ERR!     at async startPreview (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:367:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:454:28)
ERR!     at async buildDevStandalone (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:311:33)
ERR!     at async buildDev (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:374:3) {
ERR!   stack: "Error: Cannot find module 'vue/dist/vue.esm.js'\n" +
ERR!     'Require stack:\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/core/dist/server/config.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-static.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/core/server.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/vue/dist/server/index.js\n' +
ERR!     '- /home/vue/test-storybook/node_modules/@storybook/vue/bin/index.js\n' +
ERR!     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)\n' +
ERR!     '    at Function.resolve (internal/modules/cjs/helpers.js:83:19)\n' +
ERR!     '    at Object.webpack (/home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js:42:23)\n' +
ERR!     '    at /home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js:259:28\n' +
ERR!     '    at async startPreview (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:367:23)\n' +
ERR!     '    at async Promise.all (index 0)\n' +
ERR!     '    at async storybookDevServer (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/dev-server.js:454:28)\n' +
ERR!     '    at async buildDevStandalone (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:311:33)\n' +
ERR!     '    at async buildDev (/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-dev.js:374:3)',
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/home/vue/test-storybook/node_modules/@storybook/vue/dist/server/framework-preset-vue.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/core/dist/server/presets.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/core/dist/server/config.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/core/dist/server/build-static.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/core/server.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/vue/dist/server/index.js',
ERR!     '/home/vue/test-storybook/node_modules/@storybook/vue/bin/index.js'
ERR!   ]
ERR! }
```

**Expected behavior**
Storybook to work

**System**
```
Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (24) x64 AMD Ryzen 9 3900 12-Core Processor
  Binaries:
    Node: 12.16.1 - /tmp/fnm-shell-4106273/bin/node
    npm: 6.14.8 - /tmp/fnm-shell-4106273/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 83.0
  npmPackages:
    @storybook/addon-actions: ^6.1.2 => 6.1.2 
    @storybook/addon-essentials: ^6.1.2 => 6.1.2 
    @storybook/addon-links: ^6.1.2 => 6.1.2 
    @storybook/vue: ^6.1.2 => 6.1.2
```

**Comment by shilman** [comment]
Storybook does not support Vue3 yet. Closing as dupe to #10654

**Comment by Pashkella** [comment]
Same problem. @shilman is it worth waiting for vue 3 support in the next version of storybook?
