### ISSUE TITLE
Compiling error (terser-webpack-plugin)

### ISSUE THREAD

**Issue by yury-tyshkevich** [storybookjs/storybook#13246]
**Describe the bug**
Compiling error

**To Reproduce**
Run `npm run build-storybook`

**Expected behavior**
No errors.

**Screenshots**
```
info => Compiling preview..
0% compilingERR! TypeError: The 'compilation' argument must be an instance of Compilation
ERR!     at Function.getCompilationHooks (/home/dev/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:119:10)
ERR!     at /home/dev/node_modules/terser-webpack-plugin/dist/index.js:571:67
...
```

**System**
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 15.2.1 - /usr/bin/node
    npm: 7.0.14 - /usr/bin/npm
  Browsers:
    Chrome: 87.0.4280.66
    Firefox: 83.0
  npmPackages:
    @storybook/addon-actions: ^6.1.2 => 6.1.2 
    @storybook/addon-essentials: ^6.1.2 => 6.1.2 
    @storybook/addon-links: ^6.1.2 => 6.1.2 
    @storybook/react: ^6.1.2 => 6.1.2 
```

**Additional context**
Webpack 5.6.0

**Comment by shilman** [comment]
Webpack 5 is not currently supported. closing as duplicate to #9216
