### ISSUE TITLE
Noticing ReactDebugCurrentFrame errors when clicking fast

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [storybookjs/storybook#13256]
**Describe the bug**
When I click quickly through stories, I sometimes see an error stating:
```sh
ReactDebugCurrentFrame$1.setExtraStackFrame is not a function

TypeError: ReactDebugCurrentFrame$1.setExtraStackFrame is not a function
    at setCurrentlyValidatingElement (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:10712:32)
    at checkPropTypes (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:10754:11)
    at updateMemoComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17094:9)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19128:16)
    at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23928:14)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22764:12)
    at workLoopSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22695:5)
    at renderRootSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22658:7)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22281:18)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:21869:7)`
```

I can identify at least one component where this happens, but inconsistently. In fact, this error is inconsistently showing up and not easily reproducible; although, I've seen it 5 times while testing Storybook `6.1.5` in this project in the past few minutes.

Based on the console output, looks like something on my end, but the only error showing is from something I don't control.

I don't remember seeing this error in Storybook v5.

**To Reproduce**

1. Open Storybook
1. Click around the sidebar very quickly on stories which auto-opens the first item.
1. See error.

**Expected behavior**
I should see the correctly rendered story.

**Screenshots**
![image](https://user-images.githubusercontent.com/45860344/100150827-e1373b80-2e65-11eb-88c3-ff215b2c7074.png)
![image](https://user-images.githubusercontent.com/45860344/100150875-f9a75600-2e65-11eb-8035-9c57c791e17e.png)

**Code snippets**
Don't know what code samples would be helpful as it seems pretty random right now. Potentially, this shows up when `Button` renders from this project. If so, I can look into seeing what configuration of props can randomly cause this issue.

**System**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.41)
```

**Additional context**
N/A

**Comment by KevinGhadyani-minted** [comment]
Looks like this might be related to component errors, but I'm not sure as this didn't happen prior to Storybook 6.
