### ISSUE TITLE
somke-test broken with manager-cache

### ISSUE THREAD

**Issue by NewFuture** [storybookjs/storybook#13262]
**Describe the bug**
manager-cache will break the somke-test

**To Reproduce**
```
npx start-storybook --smoke-test --ci
```

First-time run (never build)
```
webpack built 63fdee694f60db7dafce in 22963ms
ERR! Error: ENOENT: no such file or directory, open '***\node_modules\.cache\storybook\public\preview-stats.json'
ERR!  [Error: ENOENT: no such file or directory, open '***\node_modules\.cache\storybook\public\preview-stats.json'] {      
ERR!   errno: -4058,
ERR!   code: 'ENOENT',
ERR!   syscall: 'open',
ERR!   path: '***\\node_modules\\.cache\\storybook\\public\\preview-stats.json'
ERR! }
```
run after a successful build
```
webpack built 63fdee694f60db7dafce in 22757ms
ERR! TypeError: stats.toJson is not a function
ERR!     at writeStats (***\node_modules\@storybook\core\dist\server\build-dev.js:81:142)
ERR!     at outputStats (***\node_modules\@storybook\core\dist\server\build-dev.js:268:9)
ERR!     at async buildDevStandalone (***\node_modules\@storybook\core\dist\server\build-dev.js:320:7)
ERR!     at async buildDev (***\node_modules\@storybook\core\dist\server\build-dev.js:374:3)
ERR!  TypeError: stats.toJson is not a function
ERR!     at writeStats (***\node_modules\@storybook\core\dist\server\build-dev.js:81:142)
ERR!     at outputStats (***\node_modules\@storybook\core\dist\server\build-dev.js:268:9)
ERR!     at async buildDevStandalone (***\node_modules\@storybook\core\dist\server\build-dev.js:320:7)
ERR!     at async buildDev (***\node_modules\@storybook\core\dist\server\build-dev.js:374:3)
```

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.66
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.41)
  npmPackages:
    @storybook/addon-essentials: ^6.1.6 => 6.1.6
    @storybook/addon-links: ^6.1.6 => 6.1.6
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.1.6 => 6.1.6
```

**Additional context**
it works when disabled manager-cache.
```
npx start-storybook --smoke-test --ci --no-manager-cache
```
it runs ok.

**Comment by ghengeveld** [comment]
Thanks! Smoke tests shouldn't be using a cached manager at all.

**Comment by NewFuture** [comment]
yes 😸

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.7 containing PR #13266 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.
