### ISSUE TITLE
[@storybook/angular] ts-loader error when not using a custom .storybook/tsconfig.json

### ISSUE THREAD

**Issue by earshinov** [storybookjs/storybook#13381]
**Describe the bug**

When not using a custom `.storybook/tsconfig.json`, `start-storybook` prints the following error coming from `ts-loader`:

```
WARNING in ./src/app/stories/ladda.stories.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.isAbsolute (path.js:353:5)
    at findConfigFile (C:\dev\storybook-repro\node_modules\ts-loader\dist\config.js:57:14)
    at Object.getConfigFile (C:\dev\storybook-repro\node_modules\ts-loader\dist\config.js:8:28)
    at successfulTypeScriptInstance (C:\dev\storybook-repro\node_modules\ts-loader\dist\instances.js:38:40)
    at Object.getTypeScriptInstance (C:\dev\storybook-repro\node_modules\ts-loader\dist\instances.js:34:12)
    at Object.loader (C:\dev\storybook-repro\node_modules\ts-loader\dist\index.js:18:41)
 @ \.)(?=.)[^\\/]*?\.stories\.(ts|js))$ (./src sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(ts|js))$) ./app/stories/ladda.stories.ts
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./src/css/app.scss
```

This error doesn't prevent Storybook from starting, but it is empty (no stories are displayed).

`build-storybook` is affected in the same way (an error message + no stories).

**Version information**

Since this error wasn't reported before, I guess there is something specific in my environment

```
$ node --version
v14.15.0
```

```
$ yarn list @storybook/cli @storybook/angular
├─ @storybook/angular@6.1.10
└─ @storybook/cli@6.1.10
```

```
$ yarn list ts-loader
└─ ts-loader@6.2.2
```

```
$ npx sb@next info
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.193
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @storybook/angular: ^6.1.10 => 6.1.10
    @storybook/cli: ^6.1.10 => 6.1.10
    @storybook/preset-scss: ^1.0.3 => 1.0.3
```

The ts-loader version is fairly old, but that's what is required by `@storybook/angular` (https://unpkg.com/@storybook/angular@6.1.10/package.json):

```
"dependencies": [
  ...
  "ts-loader": "^6.0.1",
```

**To reproduce**

```
$ git clone https://github.com/earshinov/storybook-repro.git
$ git checkout tsloader-configfile-undefined
$ yarn
$ # Make sure to use node.js v14
$ yarn run storybook:serve
```

**Root cause**

This bug seems to be caused by this change: https://github.com/storybookjs/storybook/commit/60a085065be6db6459ed64d2d1cdfabbb49d6d2e#diff-84700a27ae3705820768bec04c205e7b10fb14193bcc771b3831b1a3cc8d9f1c

Previously you had:

```
if (configFilePath) {	
  tsLoaderOptions.configFile = configFilePath;	
}
```

…and after the change:

```
configFile: configFilePath ? configFilePath : undefined,
```

(which was later changed into `configFile: configFilePath || undefined` in `master`).

When there is no `.storybook/tsconfig.json`, `configFilePath` is `undefined`, resulting in the following ts-config loader options:

```
options: {
  transpileOnly: true,
  compilerOptions: { emitDecoratorMetadata: true },
  configFile: undefined
}
```

You can see it for yourself by printing the webpack config in `.storybook/main.js`:

```
module.exports = {
  stories: // ...
  addons: // ...
  webpackFinal: async (config, { configType }) => {
    console.log("Webpack config")
    console.dir(config, { depth: null })
    return config;
  },
};
```

Now, ts-loader does the following to produce the final configuration (https://github.com/TypeStrong/ts-loader/blob/v6.2.2/src/index.ts#L301):

```
 const options = Object.assign(
    {},
    {
      // ...
      configFile: 'tsconfig.json',
    },
    loaderOptions
  );
```

Presence of `configFile: undefined` in `loaderOptions` makes it `undefined` in the final options, instead of the expected default `'tsconfig.json'`. This `configFile: undefined` then causes the error I posted above when ts-loader tries to read the config: https://github.com/TypeStrong/ts-loader/blob/v6.2.2/src/config.ts#L98.

**Possible fix**

```
diff --git a/app/angular/src/server/ts_config.ts b/app/angular/src/server/ts_config.ts
index bb0581335f..6acdac7353 100644
--- a/app/angular/src/server/ts_config.ts
+++ b/app/angular/src/server/ts_config.ts
@@ -11,12 +11,16 @@ function resolveTsConfig(tsConfigPath: string): string | undefined {
 }
 
 export default function (configDir: string) {
-  const configFilePath = resolveTsConfig(path.resolve(configDir, 'tsconfig.json'));
-  return {
+  const tsLoaderOptions = {
     transpileOnly: true,
     compilerOptions: {
       emitDecoratorMetadata: true,
     },
-    configFile: configFilePath || undefined,
   };
+
+  const configFilePath = resolveTsConfig(path.resolve(configDir, 'tsconfig.json'));
+  if (configFilePath)
+    tsLoaderOptions.configFile = configFilePath;
+
+  return tsLoaderOptions;
 }
```

**Workaround**

In `.storybook/main.js`:

```js
module.exports = {
  stories: // ...
  addons: // ...
  webpackFinal: async (config, { configType }) => {

    // A workaround for https://github.com/storybookjs/storybook/issues/13381
    function checkUse(use) {
      if (use.loader && use.loader.includes('ts-loader') && 'configFile' in use.options && use.options.configFile === undefined)
        delete use.options.configFile;
    }
    for (let rule of config.module.rules) {
      if (rule.use)
        for (let use of rule.use)
          checkUse(use);
      else
        checkUse(rule);
    }

    return config;
  },
};
```

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.8 containing PR #13382 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
