### ISSUE TITLE
Internal vuetify methods error

### ISSUE THREAD

**Issue by kauanschaeffer** [storybookjs/storybook#13532]
**Describe the bug**
I'm having an issue with 2 stories that don't load the canvas preview. I'm using Storybook with vue and vuetify, I have some components working, but these 2 I can't figure whats happenning.

1st error:
```
Cannot read property 'mobile' of undefined
TypeError: Cannot read property 'mobile' of undefined
    at VueComponent.isMobile (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:289475:23)
    at Watcher.get (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243936:25)
    at Watcher.evaluate (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:244041:21)
    at VueComponent.computedGetter [as isMobile] (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:244291:17)
    at VueComponent.genHeaders (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:262289:24)
    at VueComponent.genDefaultScopedSlot (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:262621:178)
    at Object.normalized [as default] (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:242050:37)
    at Proxy.render (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:261032:66)
    at VueComponent.Vue._render (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243005:22)
    at VueComponent.updateComponent (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243523:21)
```

2nd error:

```
color.match is not a function
TypeError: color.match is not a function
    at isCssColor (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:293452:29)
    at VueComponent.setBackgroundColor (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:288363:78)
    at VueComponent.__cachedBackground (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:272617:46)
    at Watcher.get (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243936:25)
    at Watcher.evaluate (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:244041:21)
    at Proxy.computedGetter (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:244291:17)
    at Proxy.render (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:272762:54)
    at VueComponent.Vue._render (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243005:22)
    at VueComponent.updateComponent (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243523:21)
    at Watcher.get (http://localhost:6006/vendors~main.e70571d3f211d58c4b4d.bundle.js:243936:25)
```

**Expected behavior**
Canvas preview load correctly.

**System**
  System:
    OS: Linux 5.0 Linux Mint 19.3 (Tricia)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 82.0.3
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/vue: ^6.1.11 => 6.1.11

**Comment by kauanschaeffer** [comment]
2nd error isnt happening anymore, but the first one persists on canvas screen, even though on docs screen it works fine, did anyone had this problem?

**Comment by nurkenn-keda** [comment]
Interestingly, if you wrap the offending component with 
`template:
 <v-app>
     <MyComponent />
</v-app>`
it'll render to the 'canvas', but Vuetify will complain that it wasn't bootstraped properly. 'Doc' tab on Storybook will fail however.

You can test this bug easily by trying to render <v-data-table>
Hopefully there's a resolution to this since my team is having the same issues as well

**Comment by kauanschaeffer** [comment]
> Interestingly, if you wrap the offending component with
> `template: <v-app> <MyComponent /> </v-app>`
> it'll render to the 'canvas', but Vuetify will complain that it wasn't bootstraped properly. 'Doc' tab on Storybook will fail however.
> 
> You can test this bug easily by trying to render
> Hopefully there's a resolution to this since my team is having the same issues as well

That's true, I tested it and my 'doc' tab now shows the following error:

```
TypeError: Cannot read property 'dark' of undefined
    at VueComponent.isDark (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:251882:34)
    at Watcher.get (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:243936:25)
    at Watcher.evaluate (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:244041:21)
    at VueComponent.computedGetter [as isDark] (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:244291:17)
    at VueComponent.themeClasses (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:290929:29)
    at Watcher.get (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:243936:25)
    at Watcher.evaluate (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:244041:21)
    at Proxy.computedGetter (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:244291:17)
    at Proxy.render (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:251899:15)
    at VueComponent.Vue._render (http://localhost:6006/vendors~main.81d3bd85fd1d0ea8d977.bundle.js:243005:22)
```

**Comment by piscis** [comment]
I'll noticed a similar problem when I upgraded from vuetify 2.3.20 to 2.4 suddenly all my stories referencing $vuetify.icons.X 
 in a v-icon component complained about not being able to render. Downgrade from 2.4 to 2.3.23 helped and my storybook / vuetify setup worked again.

The error is similar to the one above not finding the dark property

**Comment by nurkenn-keda** [comment]
Tried Vuetify@2.3.23 and the problem still persists

**Comment by dayre** [comment]
I got this error after upgrading to Storybook 6.1.11.

Adding a <v-app> wrapper around my story template fixed the "Cannot read property 'mobile' of undefined" error for me.  

It looks like the vuetify breakpoints object isn't being defined... i'm using a data-table component with custom slots in mine and everything was working before an upgrade to storybook 6.1.11 (can't remember my previous version of storybook).   Issue occurred with both Vuetify 2.3.21 and 2.4.0, so i think the issue must be with Storybook as that's the only thing thats changed for me.

**Comment by dayre** [comment]
Using Vuetify 2.4.0 and Storybook 6.1.11.

If i disable the docs addon, i get no errors.

**Comment by matheuzsrlog** [comment]
I had the same problem. Follows from the error:
`Cannot read property 'dark' of undefined TypeError: Cannot read property 'dark' of undefined at VueComponent.isDark
(http://localhost:6006/vendors-main.le4de5d77f20337b076f.bundle.js:250463:34) at Watcher.get (http://localhost:6006/vendors-main.le4de5d77120337b076f.bundle.js:242517:25) at Watcher.evaluate (http://localhost:6006/vendors-main.le4de5d77f20337b076f.bundle.js:242622:21) at VueComponent.computedGetter (as isDark] (http://localhost:6006/vendors-main.le4de5d77120337b076f.bundle.js:242872:17) at VueComponent. themeClasses (http://localhost:6006/vendors--main.le4de5d77f20337b076f.bundle.js:289510:29) at Watcher.get (http://localhost:6006/vendors-main.le4de5d77120337b076f.bundle.js:242517:25) at Watcher.evaluate (http://localhost:6006/vendors-main.le4de5d77f20337be76f.bundle.js:242622:21)`

**Comment by leoclipet** [comment]
Same kind of issues for me as well

TypeError: Cannot read property 'smAndDown' of undefined
    at VueComponent.hideScroll

**Comment by kauanschaeffer** [comment]
I've found out that somehow the vuetify lang object is getting undefined, if you wrap this inside your vuetify config the error changes:
```
  lang: {
    t: {
      noDataText: ''
    }
  }
```
And if you disable your docs (or essentials) addon your storybook will work.
Btw, I use chrome, if I change to firefox, the error message changes, but I think that the problem is the same.
Still no solution for this, any ideas?

**Comment by kauanschaeffer** [comment]
I think that this problem is related to this issue one: https://github.com/storybookjs/storybook/issues/7593

**Comment by nurkenn-keda** [comment]
Hi @kauanschaeffer , I've found a workaround for this issue

Basically you have to pass in your vuetify instance to your story templates.
Example (in .stories.js) below:

``` js
import vuetify from '@/plugins/vuetify'

const Template = (args, { argTypes }) => ({
  vuetify, // <- Insert vuetify here
  props: Object.keys(argTypes),
  components: { MyComponent},
  template: `
    <MyComponent
      v-bind="$props"
      />
  `
})
```

I've also answered your SO question.
Cheers

**Comment by kauanschaeffer** [comment]
> Hi @kauanschaeffer , I've found a workaround for this issue
> 
> Basically you have to pass in your vuetify instance to your story templates.
> Example (in .stories.js) below:
> 
> ```js
> import vuetify from '@/plugins/vuetify'
> 
> const Template = (args, { argTypes }) => ({
>   vuetify, // <- Insert vuetify here
>   props: Object.keys(argTypes),
>   components: { MyComponent},
>   template: `
>     <MyComponent
>       v-bind="$props"
>       />
>   `
> })
> ```
> 
> I've also answered your SO question.
> Cheers

It does work as a workaround... Waiting for a final fix to this.

**Comment by stanislavhh** [comment]
It seems to happen not only for vuetify, but for any plugin inside preview.js file. Have the same issue for i18n.
vuetify version: 2.3.21
vue-i18n: 8.22.2

**Comment by KaelWD** [comment]
This is because of the new Vue instance `@storybook/addon-docs` creates: https://github.com/storybookjs/storybook/blob/fdf716713f93421c1bf722bc436285888cb971aa/addons/docs/src/frameworks/vue/sourceDecorator.ts#L39

If there's some way to get the actual root instance where decorators are applied, passing that through with `new Vue({ parent: root })` would fix this bug.

**Comment by shilman** [comment]
@phated is this something you can look at? ☝️

**Comment by pocka** [comment]
> This is because of the new Vue instance @storybook/addon-docs creates: 

That the "extra Vue instance problem" was solved in v6.2.0-beta.2 FYI.

https://github.com/storybookjs/storybook/releases/tag/v6.2.0-beta.2

**Comment by shilman** [comment]
Nice, thanks @pocka ! closing 💯

**Comment by hereiscasio** [comment]
@shilman 
I found that this issue still existed after I use the latest version of Storybook (i.e. 6.2.0-rc.11 at now)
the error message just the same as @kauanschaeffer reported
and [the workaround](https://github.com/storybookjs/storybook/issues/13532#issuecomment-767277470) still works

but I hope I can just upgrade to certain version which I don't need to use workaround

**Comment by shilman** [comment]
@pocka any idea what @hereiscasio needs to do to get the fix?

**Comment by pocka** [comment]
@hereiscasio 
Hmm... what's your problem actually? Injecting `vuetify` to component options (or via a decorator) is required (we can't inject it into root options though). If your problem is "an error happens with a decorator that injects vuetify, but works with [the local injection workaround](https://github.com/storybookjs/storybook/issues/13532#issuecomment-767277470)", it seems the same as [this](https://github.com/storybookjs/storybook/issues/7593#issuecomment-791465127), and I'm afraid to say I can't help, sorry (precondition obscure and probably `@storybook/vue` things). Maybe other Storybook for Vue team members could have an idea for that.

**Comment by hereiscasio** [comment]
@pocka, @shilman

My problem just the same as [this](https://github.com/storybookjs/storybook/issues/13532#issuecomment-767277470)

some stories use Vuetify component without issues
but some of them(i.e. v-data-table) will

anyway

I think the workaround is already enough(i.e. inject Vuetify instance into every story)
thx anyway
