### ISSUE TITLE
Doesn't work with Angular 11

### ISSUE THREAD

**Issue by gcherem** [storybookjs/storybook#13693]
**Describe the bug**

I select any story but it is not rendered at the canvas.

**To Reproduce**

I followed the instructions from `https://storybook.js.org/docs/angular/get-started/`, I can navigate to `http://localhost:6006/` and browse the `EXAMPLE` folder, but **my** stories are not renderized at the canvas.

**Expected behavior**

I can see both `Active` and `Inactive` stories at the sidebar, but when I select one of them nothing is renderized at the canvas as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/47535363/105364434-eac9ef00-5bdb-11eb-9a03-1551e4927db7.png)

**Code snippets**

**survey-card.stories.ts**
```typescript
import { SurveyCardComponent } from './survey-card.component';

export default {
  title: 'Survey/Card',
  component: SurveyCardComponent,
};


export const Active = () => ({
  component: SurveyCardComponent,
  props: {
    id: 1,
    surveyName: 'My Survey Active',
    nps: 70,
    customers: 32000,
    responses: 15000,
    active: true,
  },
});

export const Inactive = () => ({
  component: SurveyCardComponent,
  props: {
    id: 1,
    surveyName: 'My Survey Inactive',
    nps: 70,
    customers: 32000,
    responses: 15000,
    active: false,
  },
});
```

**System**
```
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 78.0.2
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.1.14 => 6.1.14 
    @storybook/addon-essentials: ^6.1.14 => 6.1.14 
    @storybook/addon-links: ^6.1.14 => 6.1.14 
    @storybook/angular: ^6.1.14 => 6.1.14 
```
and Angular 11

**Comment by ChazUK** [comment]
Are there any errors in the console?

**Comment by shilman** [comment]
possible dupe to #13689

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13704 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by gcherem** [comment]
> Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13704 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
> 
> Closing this issue. Please re-open if you think there's still more to do.

After upgrade, I can see the following error at the canvas:

```
Template parse errors:
The pipe 'translate' could not be found 
...
```
![image](https://user-images.githubusercontent.com/47535363/105727921-54166e80-5f0a-11eb-8b62-c8ba6dbf58c7.png)

```
Template parse errors:
The pipe 'translate' could not be found (" fxFlex="33%">
      <div class="mat-title align-right info-margins right-margin-16">
        {{ nps[ERROR ->]? nps : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margi"): ng:///DynamicModule/SurveyCardComponent.html@8:14
The pipe 'translate' could not be found ("CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margin-16">{{[ERROR ->]'CAPTION.NPS' | translate}}</div>
    </div>
    <mat-divider vertical="true"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@10:61
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" class="mat-caption align-right right-margin-16">{{'CAPTION.NPS' | translate}}</div>
    </div>
    [ERROR ->]<mat-divider vertical="true"></mat-divider>
    <div fxFlex="33%">
      <div class="mat-title align-"): ng:///DynamicModule/SurveyCardComponent.html@12:4
The pipe 'shortNumber' could not be found ("fxFlex="33%">
      <div class="mat-title align-right info-margins right-margin-16">
          {{ cu[ERROR ->]stomers? (customers | shortNumber) : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-ca"): ng:///DynamicModule/SurveyCardComponent.html@15:15
The pipe 'translate' could not be found ("ass="mat-title align-right info-margins right-margin-16">
          {{ customers? (customers | short[ERROR ->]Number) : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-mar"): ng:///DynamicModule/SurveyCardComponent.html@15:42
The pipe 'translate' could not be found ("CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margin-16">{{[ERROR ->]'CAPTION.CUSTOMERS' | translate}}</div>
    </div>
    <mat-divider vertical="true"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@17:61
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("="mat-caption align-right right-margin-16">{{'CAPTION.CUSTOMERS' | translate}}</div>
    </div>
    [ERROR ->]<mat-divider vertical="true"></mat-divider>
    <div fxFlex="33%">
      <div class="mat-title align-"): ng:///DynamicModule/SurveyCardComponent.html@19:4
The pipe 'translate' could not be found ("lex="33%">
      <div class="mat-title align-right info-margins">
        {{ responses? (responses +[ERROR ->] '%') : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right">{{'CAPTION"): ng:///DynamicModule/SurveyCardComponent.html@22:34
The pipe 'translate' could not be found ("onses + '%') : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right">{{[ERROR ->]'CAPTION.RESPONSES' | translate}}</div>
    </div>
  </div>
"): ng:///DynamicModule/SurveyCardComponent.html@24:45
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>
  </div>
  [ERROR ->]<mat-divider class="h-divider"></mat-divider>
  <div fxLayout="row" class="card-footer">
    <mat-sli"): ng:///DynamicModule/SurveyCardComponent.html@27:2
Can't bind to 'disabled' since it isn't a known property of 'mat-slide-toggle'.
1. If 'mat-slide-toggle' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <div fxLayout="row" class="card-footer">
    <mat-slide-toggle
      [ERROR ->][disabled]="changingActive"
      [checked]="active"
      (change)="onChangeActiveSlide($event)"
"): ng:///DynamicModule/SurveyCardComponent.html@30:6
Can't bind to 'checked' since it isn't a known property of 'mat-slide-toggle'.
1. If 'mat-slide-toggle' is an Angular component and it has 'checked' input, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <mat-slide-toggle
      [disabled]="changingActive"
      [ERROR ->][checked]="active"
      (change)="onChangeActiveSlide($event)"
      fxFlex="90px">
"): ng:///DynamicModule/SurveyCardComponent.html@31:6
The pipe 'translate' could not be found ("
      (change)="onChangeActiveSlide($event)"
      fxFlex="90px">
  [ERROR ->]    {{'CAPTION.ACTIVE' | translate}}
    </mat-slide-toggle>
    <div fxFlex class="spinner" *ngIf="c"): ng:///DynamicModule/SurveyCardComponent.html@34:2
'mat-slide-toggle' is not a known element:
1. If 'mat-slide-toggle' is an Angular component, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  <mat-divider class="h-divider"></mat-divider>
  <div fxLayout="row" class="card-footer">
    [ERROR ->]<mat-slide-toggle
      [disabled]="changingActive"
      [checked]="active"
"): ng:///DynamicModule/SurveyCardComponent.html@29:4
'mat-spinner' is not a known element:
1. If 'mat-spinner' is an Angular component, then verify that it is part of this module.
2. If 'mat-spinner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </mat-slide-toggle>
    <div fxFlex class="spinner" *ngIf="changingActive">
        [ERROR ->]<mat-spinner diameter="16"></mat-spinner>
    </div>
    <div fxFlex>
"): ng:///DynamicModule/SurveyCardComponent.html@37:8
The pipe 'translate' could not be found ("
      fxFlexAlign="end end"
      mat-icon-button
      matTooltip="{{[ERROR ->]'TOOLTIP.ACTIONS' | translate}}"
      [matMenuTriggerFor]="cardMenu"
    >
"): ng:///DynamicModule/SurveyCardComponent.html@46:20
Can't bind to 'matTooltip' since it isn't a known property of 'button'. ("
      fxFlexAlign="end end"
      mat-icon-button
      [ERROR ->]matTooltip="{{'TOOLTIP.ACTIONS' | translate}}"
      [matMenuTriggerFor]="cardMenu"
    >
"): ng:///DynamicModule/SurveyCardComponent.html@46:6
Can't bind to 'matMenuTriggerFor' since it isn't a known property of 'button'. ("
      mat-icon-button
      matTooltip="{{'TOOLTIP.ACTIONS' | translate}}"
      [ERROR ->][matMenuTriggerFor]="cardMenu"
    >
      <mat-icon>more_vert</mat-icon>
"): ng:///DynamicModule/SurveyCardComponent.html@47:6
'mat-icon' is not a known element:
1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
2. If 'mat-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      [matMenuTriggerFor]="cardMenu"
    >
      [ERROR ->]<mat-icon>more_vert</mat-icon>
    </button>
  </div>
"): ng:///DynamicModule/SurveyCardComponent.html@49:6
'mat-card' is not a known element:
1. If 'mat-card' is an Angular component, then verify that it is part of this module.
2. If 'mat-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-card>
  <div class="upper-bar" [ngClass]="upperBarClass"></div>
  <div class="rectangle">
"): ng:///DynamicModule/SurveyCardComponent.html@0:0
There is no directive with "exportAs" set to "matMenu" ("
</mat-card>

<mat-menu [ERROR ->]#cardMenu="matMenu">
  <ng-template let-item let-last="last" ngFor [ngForOf]="cardMenuItems">
    <bu"): ng:///DynamicModule/SurveyCardComponent.html@54:10
The pipe 'translate' could not be found ("
      [ngClass]="{ 'mat-menu-item-warn': item.warn }"
    >
      <span>{{ [ERROR ->]item.title | translate }}</span>
    </button>
    <mat-divider *ngIf="item.divider"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@61:15
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      <span>{{ item.title | translate }}</span>
    </button>
    [ERROR ->]<mat-divider *ngIf="item.divider"></mat-divider>
  </ng-template>
</mat-menu>
"): ng:///DynamicModule/SurveyCardComponent.html@63:4
'mat-menu' is not a known element:
1. If 'mat-menu' is an Angular component, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</mat-card>

[ERROR ->]<mat-menu #cardMenu="matMenu">
  <ng-template let-item let-last="last" ngFor [ngForOf]="cardMenuItems"): ng:///DynamicModule/SurveyCardComponent.html@54:0
Error: Template parse errors:
The pipe 'translate' could not be found (" fxFlex="33%">
      <div class="mat-title align-right info-margins right-margin-16">
        {{ nps[ERROR ->]? nps : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margi"): ng:///DynamicModule/SurveyCardComponent.html@8:14
The pipe 'translate' could not be found ("CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margin-16">{{[ERROR ->]'CAPTION.NPS' | translate}}</div>
    </div>
    <mat-divider vertical="true"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@10:61
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" class="mat-caption align-right right-margin-16">{{'CAPTION.NPS' | translate}}</div>
    </div>
    [ERROR ->]<mat-divider vertical="true"></mat-divider>
    <div fxFlex="33%">
      <div class="mat-title align-"): ng:///DynamicModule/SurveyCardComponent.html@12:4
The pipe 'shortNumber' could not be found ("fxFlex="33%">
      <div class="mat-title align-right info-margins right-margin-16">
          {{ cu[ERROR ->]stomers? (customers | shortNumber) : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-ca"): ng:///DynamicModule/SurveyCardComponent.html@15:15
The pipe 'translate' could not be found ("ass="mat-title align-right info-margins right-margin-16">
          {{ customers? (customers | short[ERROR ->]Number) : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-mar"): ng:///DynamicModule/SurveyCardComponent.html@15:42
The pipe 'translate' could not be found ("CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right right-margin-16">{{[ERROR ->]'CAPTION.CUSTOMERS' | translate}}</div>
    </div>
    <mat-divider vertical="true"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@17:61
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("="mat-caption align-right right-margin-16">{{'CAPTION.CUSTOMERS' | translate}}</div>
    </div>
    [ERROR ->]<mat-divider vertical="true"></mat-divider>
    <div fxFlex="33%">
      <div class="mat-title align-"): ng:///DynamicModule/SurveyCardComponent.html@19:4
The pipe 'translate' could not be found ("lex="33%">
      <div class="mat-title align-right info-margins">
        {{ responses? (responses +[ERROR ->] '%') : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right">{{'CAPTION"): ng:///DynamicModule/SurveyCardComponent.html@22:34
The pipe 'translate' could not be found ("onses + '%') : 'CAPTION.NA'| translate }}
      </div>
      <div class="mat-caption align-right">{{[ERROR ->]'CAPTION.RESPONSES' | translate}}</div>
    </div>
  </div>
"): ng:///DynamicModule/SurveyCardComponent.html@24:45
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>
  </div>
  [ERROR ->]<mat-divider class="h-divider"></mat-divider>
  <div fxLayout="row" class="card-footer">
    <mat-sli"): ng:///DynamicModule/SurveyCardComponent.html@27:2
Can't bind to 'disabled' since it isn't a known property of 'mat-slide-toggle'.
1. If 'mat-slide-toggle' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <div fxLayout="row" class="card-footer">
    <mat-slide-toggle
      [ERROR ->][disabled]="changingActive"
      [checked]="active"
      (change)="onChangeActiveSlide($event)"
"): ng:///DynamicModule/SurveyCardComponent.html@30:6
Can't bind to 'checked' since it isn't a known property of 'mat-slide-toggle'.
1. If 'mat-slide-toggle' is an Angular component and it has 'checked' input, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <mat-slide-toggle
      [disabled]="changingActive"
      [ERROR ->][checked]="active"
      (change)="onChangeActiveSlide($event)"
      fxFlex="90px">
"): ng:///DynamicModule/SurveyCardComponent.html@31:6
The pipe 'translate' could not be found ("
      (change)="onChangeActiveSlide($event)"
      fxFlex="90px">
  [ERROR ->]    {{'CAPTION.ACTIVE' | translate}}
    </mat-slide-toggle>
    <div fxFlex class="spinner" *ngIf="c"): ng:///DynamicModule/SurveyCardComponent.html@34:2
'mat-slide-toggle' is not a known element:
1. If 'mat-slide-toggle' is an Angular component, then verify that it is part of this module.
2. If 'mat-slide-toggle' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  <mat-divider class="h-divider"></mat-divider>
  <div fxLayout="row" class="card-footer">
    [ERROR ->]<mat-slide-toggle
      [disabled]="changingActive"
      [checked]="active"
"): ng:///DynamicModule/SurveyCardComponent.html@29:4
'mat-spinner' is not a known element:
1. If 'mat-spinner' is an Angular component, then verify that it is part of this module.
2. If 'mat-spinner' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </mat-slide-toggle>
    <div fxFlex class="spinner" *ngIf="changingActive">
        [ERROR ->]<mat-spinner diameter="16"></mat-spinner>
    </div>
    <div fxFlex>
"): ng:///DynamicModule/SurveyCardComponent.html@37:8
The pipe 'translate' could not be found ("
      fxFlexAlign="end end"
      mat-icon-button
      matTooltip="{{[ERROR ->]'TOOLTIP.ACTIONS' | translate}}"
      [matMenuTriggerFor]="cardMenu"
    >
"): ng:///DynamicModule/SurveyCardComponent.html@46:20
Can't bind to 'matTooltip' since it isn't a known property of 'button'. ("
      fxFlexAlign="end end"
      mat-icon-button
      [ERROR ->]matTooltip="{{'TOOLTIP.ACTIONS' | translate}}"
      [matMenuTriggerFor]="cardMenu"
    >
"): ng:///DynamicModule/SurveyCardComponent.html@46:6
Can't bind to 'matMenuTriggerFor' since it isn't a known property of 'button'. ("
      mat-icon-button
      matTooltip="{{'TOOLTIP.ACTIONS' | translate}}"
      [ERROR ->][matMenuTriggerFor]="cardMenu"
    >
      <mat-icon>more_vert</mat-icon>
"): ng:///DynamicModule/SurveyCardComponent.html@47:6
'mat-icon' is not a known element:
1. If 'mat-icon' is an Angular component, then verify that it is part of this module.
2. If 'mat-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      [matMenuTriggerFor]="cardMenu"
    >
      [ERROR ->]<mat-icon>more_vert</mat-icon>
    </button>
  </div>
"): ng:///DynamicModule/SurveyCardComponent.html@49:6
'mat-card' is not a known element:
1. If 'mat-card' is an Angular component, then verify that it is part of this module.
2. If 'mat-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-card>
  <div class="upper-bar" [ngClass]="upperBarClass"></div>
  <div class="rectangle">
"): ng:///DynamicModule/SurveyCardComponent.html@0:0
There is no directive with "exportAs" set to "matMenu" ("
</mat-card>

<mat-menu [ERROR ->]#cardMenu="matMenu">
  <ng-template let-item let-last="last" ngFor [ngForOf]="cardMenuItems">
    <bu"): ng:///DynamicModule/SurveyCardComponent.html@54:10
The pipe 'translate' could not be found ("
      [ngClass]="{ 'mat-menu-item-warn': item.warn }"
    >
      <span>{{ [ERROR ->]item.title | translate }}</span>
    </button>
    <mat-divider *ngIf="item.divider"></mat-divider>
"): ng:///DynamicModule/SurveyCardComponent.html@61:15
'mat-divider' is not a known element:
1. If 'mat-divider' is an Angular component, then verify that it is part of this module.
2. If 'mat-divider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
      <span>{{ item.title | translate }}</span>
    </button>
    [ERROR ->]<mat-divider *ngIf="item.divider"></mat-divider>
  </ng-template>
</mat-menu>
"): ng:///DynamicModule/SurveyCardComponent.html@63:4
'mat-menu' is not a known element:
1. If 'mat-menu' is an Angular component, then verify that it is part of this module.
2. If 'mat-menu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</mat-card>

[ERROR ->]<mat-menu #cardMenu="matMenu">
  <ng-template let-item let-last="last" ngFor [ngForOf]="cardMenuItems"): ng:///DynamicModule/SurveyCardComponent.html@54:0
    at syntaxError (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:23504:19)
    at TemplateParser.parse (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:33752:19)
    at JitCompiler._parseTemplate (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49505:37)
    at JitCompiler._compileTemplate (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49493:69)
    at http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49437:46
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49437:19)
    at http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49350:18
    at Object.then (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:23494:52)
    at JitCompiler._compileModuleAndComponents (http://localhost:6006/vendors~main.5c05aab7bafcfb40884a.bundle.js:49349:26)
```

**Comment by gcherem** [comment]
> Are there any errors in the console?



> Are there any errors in the console?

Yes, see my reply to @shilman

**Comment by ChazUK** [comment]
You need to add pipes and modules to the decorators to your stories default export

```
import { moduleMetadata } from '@storybook/angular';

export default {
  title: 'Card/Active',
  decorators: [
    moduleMetadata({
      imports: [...],
      declarations: [...],
    }),
  ],
};
```

**Comment by gcherem** [comment]
> You need to add pipes and modules to the decorators to your stories default export
> 
> ```
> import { moduleMetadata } from '@storybook/angular';
> 
> export default {
>   title: 'Card/Active',
>   decorators: [
>     moduleMetadata({
>       imports: [...],
>       declarations: [...],
>     }),
>   ],
> };
> ```

Thank you for the quick reply. I just did it, and now the error changed to  `(kindDecorators || []).forEach is not a function` Any idea?:

```
(kindDecorators || []).forEach is not a function
TypeError: (kindDecorators || []).forEach is not a function
    at http://localhost:6006/vendors~main.bba1c4e2ab26144b5771.bundle.js:184331:30
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.bba1c4e2ab26144b5771.bundle.js:184273:11
    at ConfigApi.configure (http://localhost:6006/vendors~main.bba1c4e2ab26144b5771.bundle.js:166231:7)
    at Object.configure (http://localhost:6006/vendors~main.bba1c4e2ab26144b5771.bundle.js:184428:17)
    at push../node_modules/@storybook/angular/dist/client/preview/index.js.exports.configure (http://localhost:6006/vendors~main.bba1c4e2ab26144b5771.bundle.js:163580:26)
    at Object.<anonymous> (http://localhost:6006/main.bba1c4e2ab26144b5771.bundle.js:17:36)
    at Object../.storybook/generated-stories-entry.js (http://localhost:6006/main.bba1c4e2ab26144b5771.bundle.js:18:30)
    at __webpack_require__ (http://localhost:6006/runtime~main.bba1c4e2ab26144b5771.bundle.js:849:30)
    at fn (http://localhost:6006/runtime~main.bba1c4e2ab26144b5771.bundle.js:151:20)
```

**Comment by ChazUK** [comment]
It's probably better to use the docs for this. The syntax I posted above might only work in version 5 and not in version 6

https://storybook.js.org/docs/angular/writing-stories/decorators

**Comment by gcherem** [comment]
Thank you @ChazUK, I followed the docs and refactored the 'decorators' clause to v6, the error inside the canvas disappeared, but nothing is rendered yet. Now it is complaining `No provider for Router!` at console:

```
ERROR Error: NullInjectorError: No provider for Router!
    at NullInjector.get (core.js:10823) [angular]
    at resolveToken (core.js:11562) [angular]
    at tryResolveToken (core.js:11507) [angular]
    at StaticInjector.get (core.js:11402) [angular]
    at resolveToken (core.js:11562) [angular]
    at tryResolveToken (core.js:11507) [angular]
    at StaticInjector.get (core.js:11402) [angular]
    at resolveNgModuleDep (core.js:23661) [angular]
    at NgModuleRef_.get (core.js:24194) [angular]
    at resolveDep (core.js:24563) [angular]
    at createClass (core.js:24444) [angular]
    at createDirectiveInstance (core.js:24319) [angular]
    at createViewNodes (core.js:31451) [angular]
    at createRootView (core.js:31360) [angular]
```

**Comment by ChazUK** [comment]
Add RouterTestingModule instead of RouterModule

**Comment by gcherem** [comment]
**BINGO!**

it worked! Thank you @ChazUK!

**Comment by timvandaatselaar** [comment]
@gcherem I have the same problem, how did you manage to fix this?

`he pipe 'translate' could not be found`
