### ISSUE TITLE
@storybook/addon-storyshots-puppeteer fails to handle CSS: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by kettanaito** [storybookjs/storybook#13801]
**Describe the bug**
When running a test with `@storybook/addon-storyshots-puppeteer` and loading a story that renders a component with a `*.css` file imported, the following exception is thrown:

```
    Unexpected error while loading ./GitHubUser.stories.js: SyntaxError: Unexpected token '.'

      at Object.warn (../../node_modules/@storybook/client-logger/dist/index.js:53:73)
      at ../../node_modules/@storybook/core/dist/client/preview/loadCsf.js:149:34
          at Array.forEach (<anonymous>)
      at ../../node_modules/@storybook/core/dist/client/preview/loadCsf.js:142:20
          at Array.forEach (<anonymous>)
      at ../../node_modules/@storybook/core/dist/client/preview/loadCsf.js:141:12
      at ConfigApi.configure (../../node_modules/@storybook/client-api/dist/config_api.js:26:7)
```

Removing the CSS file import solves the issue. 

**To Reproduce**

Create the following React component:

```jsx
// Box.js
import React from 'react'
import './styles.css'

export default Box = () => {
  return <div className="box">Content</div>
}
```

```css
/* styles.css */
.box { background-color: red; }
```

Create the following story:

```js
// stories/Box.story.js
import Box from '../Box'

export default {
  title: 'Box',
  component: Box,
}

export const Default = () => <Box />

// Add a test suite with "@storybook/addon-storyshots-puppeteer":
Default.parameters = {
  async puppeteerTest(page) {
    await page.$('.box')
  }
}
```

Create a test suite:

```js
// Box.test.js
import initStoryshots from '@storybook/addon-storyshots'
import { puppeteerTest } from '@storybook/addon-storyshots-puppeteer'

initStoryshots({
  test: puppeteerTest(),
})
```

Run the test with `npm test`, given you have Jest installed. No custom Jest configuration is provided (no `jest.config.js` at all). 

**Expected behavior**
Storybook build during the test run doesn't crash and can handle the CSS import as it does in development mode. 

**System**
```
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 84.0.2
    Safari: 13.1.1
```

**Comment by fyrkant** [comment]
I'm having the same problem in my app, any ideas on how to fix this?

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
