### ISSUE TITLE
Storybook Web Components example has broken canvas

### ISSUE THREAD

**Issue by danielsimao** [storybookjs/storybook#13952]
**Problem:**
I have installed the initial boilerplate for web components and the canvas is broken in every story. Docs sections works perfectly.

```
Right-hand side of 'instanceof' is not an object
TypeError: Right-hand side of 'instanceof' is not an object
    at StoryRenderer.renderMain [as render] (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:159722:15)
    at StoryRenderer._callee3$ (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:155785:29)
    at tryCatch (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:33489:40)
    at Generator.invoke [as _invoke] (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:33719:22)
    at Generator.next (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:33544:21)
    at asyncGeneratorStep (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:155412:103)
    at _next (http://localhost:6006/vendors~main.6fbfb46e4dfa2e01976c.bundle.js:155414:194)
```

**Steps to reproduce the behavior:**
1. npx -p @storybook/cli sb init -t web_components
2. npm run storybook
3. Select a story and canvas sections should be open by default

**Expected Behaviour:**
The expected behaviour would be to have the component displayed in the respective canvas.

**Screenshots**
![image](https://user-images.githubusercontent.com/43269067/108372946-41d0dd00-71f7-11eb-8090-e40360aa8588.png)

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by petergaal91** [comment]
I also facing with the same issue, but the reason is: tried to use lit-element@3 which is not supported (yet).

[Related Issue](https://github.com/storybookjs/storybook/issues/13489)

Hope it's helps to someone

**Comment by shilman** [comment]
@petergaal91 good news, i think we're going to tackle that one in 6.3
