### ISSUE TITLE
Module build failed (from ./node_modules/@storybook/core/node_modules/babel-loader/lib/index.js): Error: Plugin/Preset files are not allowed to export objects, only functions.

### ISSUE THREAD

**Issue by gokulyc** [storybookjs/storybook#14003]
**Describe the bug**
Unable to use story book.

1. In command prompt

```
F:\Github_ssd\react_demo\my-app>yarn storybook
yarn run v1.22.5
$ start-storybook -p 6006
info @storybook/react v6.1.18
info
info => Using prebuilt manager
info => Loading presets
info => Loading 1 config file in "./.storybook"
info => Loading 7 other files in "./.storybook"
info => Adding stories defined in ".storybook\main.js"
info => Using default Webpack setup
webpack built 518683d1c15364fa11e6 in 9569ms
× ｢wdm｣: Hash: 518683d1c15364fa11e6
Version: webpack 4.46.0
Time: 9569ms
Built at: 02/22/2021 1:33:14 PM
                                          Asset       Size        Chunks                                Chunk Names
                                    iframe.html   4.38 KiB                [emitted]
            main.518683d1c15364fa11e6.bundle.js   12.5 KiB          main  [emitted] [immutable]         main
        main.518683d1c15364fa11e6.bundle.js.map  250 bytes          main  [emitted] [dev]               main
    runtime~main.518683d1c15364fa11e6.bundle.js   33.5 KiB  runtime~main  [emitted] [immutable]         runtime~main
runtime~main.518683d1c15364fa11e6.bundle.js.map   34.7 KiB  runtime~main  [emitted] [dev]               runtime~main
    vendors~main.518683d1c15364fa11e6.bundle.js   6.24 MiB  vendors~main  [emitted] [immutable]  [big]  vendors~main
vendors~main.518683d1c15364fa11e6.bundle.js.map   5.99 MiB  vendors~main  [emitted] [dev]               vendors~main
Entrypoint main [big] = runtime~main.518683d1c15364fa11e6.bundle.js runtime~main.518683d1c15364fa11e6.bundle.js.map vendors~main.518683d1c15364fa11e6.bundle.js vendors~main.518683d1c15364fa11e6.bundle.js.map main.518683d1c15364fa11e6.bundle.js main.518683d1c15364fa11e6.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 172 bytes {main} [built]
[./.storybook/generated-stories-entry.js] 1.8 KiB {main} [built] [failed] [1 error]
[./.storybook/preview.js-generated-config-entry.js] 1.8 KiB {main} [built] [failed] [1 error]
[./.storybook/storybook-init-framework-entry.js] 1.8 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/addon-actions/dist/preset/addArgs.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js] 2.38 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] 7.68 KiB {vendors~main} [built]
    + 1879 hidden modules

ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/@storybook/core/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In F:\Github_ssd\react_demo\my-app\node_modules\babel-preset-react-app\index.js
    at createDescriptor (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:135:29)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:140:25
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[2]

ERROR in ./.storybook/preview.js-generated-config-entry.js
Module build failed (from ./node_modules/@storybook/core/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In F:\Github_ssd\react_demo\my-app\node_modules\babel-preset-react-app\index.js
    at createDescriptor (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:135:29)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:140:25
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[10]

ERROR in ./.storybook/generated-stories-entry.js
Module build failed (from ./node_modules/@storybook/core/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In F:\Github_ssd\react_demo\my-app\node_modules\babel-preset-react-app\index.js
    at createDescriptor (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:416:26)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:374:7
    at Generator.next (<anonymous>)
    at loadFileChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:228:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\config-chain.js:135:29)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:101:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at F:\Github_ssd\react_demo\my-app\node_modules\@babel\core\lib\config\partial.js:140:25
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[11]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.39 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/core/node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 2.04 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Expected behavior**
To Use working application.

**Screenshots**
![image](https://user-images.githubusercontent.com/13468848/108679878-27f30b00-7513-11eb-843c-922b04f465a6.png)

**System**

```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.74)
  npmPackages:
    @storybook/addon-actions: ^6.1.18 => 6.1.18
    @storybook/addon-essentials: ^6.1.18 => 6.1.18
    @storybook/addon-links: ^6.1.18 => 6.1.18
    @storybook/react: ^6.1.18 => 6.1.18
```

**Comment by shilman** [comment]
Do you have a repro repo you can share?

Do you have a custom babel config? If so, maybe try deleting it and seeing if that fixes the problem? From there maybe you can narrow it down.

**Comment by gokulyc** [comment]
> Do you have a repro repo you can share?
> 
> Do you have a custom babel config? If so, maybe try deleting it and seeing if that fixes the problem? From there maybe you can narrow it down.

## My Code repository :  

https://gitlab.com/gokulyc/react_demo

**Comment by halimb** [comment]
@shilman I'm having the exact same issue with vue.

**Reproduction steps:**

1. create a vue app: `vue init webpack`
2. npx sb init
3. yarn storybook

**Comment by shilman** [comment]
@gokulyc i was able to get your repo running by deleting these lines of the package.json

```
  "babel": {
    "presets": [
      "react-app"
    ]
  },
```

**Comment by gokulyc** [comment]
> @gokulyc i was able to get your repo running by deleting these lines of the package.json
> 
> ```
>   "babel": {
>     "presets": [
>       "react-app"
>     ]
>   },
> ```

I think it's required for react application, will react app can be built after doing that change???

- will check in my local environment once

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
