### ISSUE TITLE
Support for webpack 5 in @storybook/addon-actions

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#14057]
**Is your feature request related to a problem? Please describe**

Support for [webpack 5 has been released](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324) and doing some initial testing is resulting in errors with `@storybook/addon-actions`

**Describe the solution you'd like**

Use of `@storybook/addon-actions` works with webpack 5

**Describe alternatives you've considered**

Workaround to be able to run storybook with `@storybook/addon-actions` using webpack 5

**Are you able to assist to bring the feature to reality?**

Glad to help

**Additional context**

Here's the error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/addon-actions/dist/preview/action.js' in '/Users/dlj/projects/myproj/lib/components/templates/ReportViewer'
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/Compilation.js:1664:28
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:708:13
    at eval (eval at create (/Users/dlj/projects/myproj/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:272:22
    at eval (eval at create (/Users/dlj/projects/myproj/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:632:24
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:774:8
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:894:5
    at /Users/dlj/projects/myproj/node_modules/neo-async/async.js:6883:13
    at /Users/dlj/projects/myproj/node_modules/webpack/lib/NormalModuleFactory.js:877:45
    at finishWithoutResolve (/Users/dlj/projects/myproj/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/dlj/projects/myproj/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/dlj/projects/myproj/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/dlj/projects/myproj/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve '@storybook/addon-actions/dist/preview/action.js' in '/Users/dlj/projects/myproj/lib/components/templates/ReportViewer'
  Parsed request is a module
  using description file: /Users/dlj/projects/myproj/lib/components/package.json (relative path: ./templates/ReportViewer)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/dlj/projects/myproj/lib/components/templates/ReportViewer/node_modules doesn't exist or is not a directory
      /Users/dlj/projects/myproj/lib/components/templates/node_modules doesn't exist or is not a directory
      looking for modules in /Users/dlj/projects/myproj/lib/components/node_modules
        /Users/dlj/projects/myproj/lib/components/node_modules/@storybook/addon-actions doesn't exist
      /Users/dlj/projects/myproj/lib/node_modules doesn't exist or is not a directory
      looking for modules in /Users/dlj/projects/myproj/node_modules
        existing directory /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions
          using description file: /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/package.json (relative path: .)
            using description file: /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/package.json (relative path: ./dist/preview/action.js)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js doesn't exist
              .mjs
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.mjs doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.jsx doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.tsx doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.json doesn't exist
              .cjs
                Field 'browser' doesn't contain a valid alias configuration
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js.cjs doesn't exist
              as directory
                /Users/dlj/projects/myproj/node_modules/@storybook/addon-actions/dist/preview/action.js doesn't exist
      looking for modules in /Users/dlj/projects/node_modules
        /Users/dlj/projects/node_modules/@storybook/addon-actions doesn't exist
      /Users/dlj/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by joao-pedrozo** [comment]
Have you already checked this repo? https://github.com/jean-leonco/storybook-webpack-5

**Comment by daveisfera** [comment]
`@storybook/addon-actions` is in `package.json` in that repo, but I don't see it used anywhere in the code

**Comment by shilman** [comment]
@daveisfera I'm unable to repro this in the storybook monorepo. I don't think it's webpack5-related, but if you have a public repro I'm happy to take a look!

**Comment by daveisfera** [comment]
We removed our direct uses of `@storybook/addon-actions` by using Controls, so it's working now
