### ISSUE TITLE
Storybook experiences a hard crash on reloading after fixing SCSS Syntax errors in a React project

### ISSUE THREAD

**Issue by juliankrieger** [storybookjs/storybook#14144]
When editing an SCSS file and saving it with a Syntax error, Storybook correctly reports the syntax error in the correct line. After fixing (or changing anything else in that file for that matter), Storybook and/or the underlying Webpack Dev Server experiences a hard crash. It has to be manually restarted and may only work after deleting `node_modules/.cache` beforehand.

**To Reproduce**

1. Setup basic React Storybook Project with TypeScript and the following configuration files
main.js
```
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials", "@storybook/preset-create-react-app"]
};
```
preview.js
```
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}
```

2. Create basic React component with correcponding module.scss
button.js
```
import styles from 'button.module.scss'

export const Button = () =>  <button className={styles.button}>Some Button</button>
```
button.module.scss
```
.button {
  color: red;
}
```
button.stories.tsx
```
import React from "react";
import { Button } from "./button";
import { Story } from "@storybook/react";

export default {
  title: "button",
  component: button
};

const Template = () => <Button />;
export const Standard = Template.bind({});
```

3. Introduced syntax error in button.module.scss and save
```
.button {
 color: ; // notice empty color property
}
```
4. Read correct error statement
```
ERROR in ./src/components/controls/Button/Button.module.scss (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--9-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-7-4!./src/components/controls/Button/Button.module.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected expression.
   ╷
2 │   color: ;
   │            ^
   ╵
  /Users/julian.krieger/Dev/xxx/xxx/xxxt/src/components/controls/Button/button.module.scss 2:6  root stylesheet
 @ ./src/components/controls/Button/Button.module.scss xxx
 @ ./src/components/controls/Button/Button.tsx
 @ ./src/components/controls/Button/Button.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx))$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./node_modules/react-dev-utils/webpackHotDevClient.js
```

5. Correct Syntax error and save
button.module.scss
```
.button {
  color: red;
}
```
6. Experience hard crash
```
webpack building...
webpack built 7183e199ff9d68c7f1ed in 752ms
Assertion failed: (napi_create_string_utf8(env, events->events[idx].path, NAPI_AUTO_LENGTH, &args[0]) == napi_ok), function fse_dispatch_event, file ../src/fsevents.c, line 147.
[1]    21971 abort      npm run storybook
```

7. Try to restart 
``` 
ERR! SyntaxError: /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7: Unexpected end of JSON input
ERR!     at JSON.parse (<anonymous>)
ERR!     at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/file-system-cache/node_modules/jsonfile/index.js:36:18
ERR!     at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/graceful-fs/graceful-fs.js:123:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
ERR!  SyntaxError: /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7: Unexpected end of JSON input
ERR!     at JSON.parse (<anonymous>)
ERR!     at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/file-system-cache/node_modules/jsonfile/index.js:36:18
ERR!     at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/graceful-fs/graceful-fs.js:123:16
ERR!     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
ERR!   stack: 'SyntaxError: /Users/julian.krieger/Dev/xxx/xxx/xxx//node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7: Unexpected end of JSON input\n' +
ERR!     '    at JSON.parse (<anonymous>)\n' +
ERR!     '    at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/file-system-cache/node_modules/jsonfile/index.js:36:18\n' +
ERR!     '    at /Users/julian.krieger/Dev/xxx/xxx/xxx/node_modules/graceful-fs/graceful-fs.js:123:16\n' +
ERR!     '    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)'
ERR! }

```
8. Delete `node_modules/.cache`
9. Restart
10. Works as expected again

**Expected behavior**
Storybook builds without error after fixing SCSS Syntax error, like it would if the file were a JS file.

**System**
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.1.14 => 6.1.14 
    @storybook/addon-essentials: ^6.1.14 => 6.1.14 
    @storybook/addon-links: ^6.1.14 => 6.1.14 
    @storybook/node-logger: ^6.1.14 => 6.1.14 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.14 => 6.1.14 

**Additional context**

**Comment by juliankrieger** [comment]
@shilman can you add appropriate labels (maybe `app:react`, `webpack` and `typescript`)? Thanks in advance!

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by juliankrieger** [comment]
@shilman It turned out to be an issue with us using Storybook 6.1.14 in combination with NPM v7 and React 17. Upgrading via `npx sb upgrade --prerelease` fixed the issue

**Comment by shilman** [comment]
Pretty weird! Glad you got it sorted
