### ISSUE TITLE
Webpack5: DefinePlugin error (parser.isAsiPosition is not a function) in storybook with addons

### ISSUE THREAD

**Issue by azangru** [storybookjs/storybook#14174]
**Describe the bug**
While going through the [instructions](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324) for testing Storybook's Webpack5 support, I am seeing the following errors that appear to be related to Webpack DefinePlugin. The errors seem to be caused by addons (e.g. `@storybook/addon-viewport`). I have not checked whether disabling the addons will make the errors go away.

```
ERROR in ./node_modules/@emotion/sheet/dist/sheet.browser.esm.js                                                                                                                                          Module parse failed: parser.isAsiPosition is not a function                                                                                                                                               
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders                                        
TypeError: parser.isAsiPosition is not a function                                                                                                                                                         
    at [path-to-project-folder]/node_modules/webpack/lib/DefinePlugin.js:233:18                                                                                               
    at SyncBailHook.eval [as call] (eval at create ([path-to-project-folder]/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)       
    at Parser.walkMemberExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1958:35)                                  
    at Parser.walkExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1610:10)                                        
    at Parser.walkLeftRightExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1748:8)                                
    at Parser.walkBinaryExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1753:8)                                   
    at Parser.walkExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1589:10)                                        
    at Parser.walkConditionalExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1804:9)                              
    at Parser.walkExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1598:10)                                        
    at Parser.walkAssignmentExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1793:8)                               
    at Parser.walkExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1583:10)                                        
    at Parser.walkExpressionStatement ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1022:8)                                
    at Parser.walkStatement ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:964:10)                                          
    at Parser.walkStatements ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:868:9)                                          
    at [path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1017:9
    at Parser.inBlockScope ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:2060:3)
 @ ./node_modules/@emotion/core/dist/core.browser.esm.js 8:0-44 76:21-31
 @ ./node_modules/@storybook/theming/dist/esm/index.js
 @ ./node_modules/@storybook/addon-viewport/dist/esm/Tool.js
 @ ./node_modules/@storybook/addon-viewport/dist/esm/register.js
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core-client/dist/esm/manager/index.js ./node_modules/@storybook/addon-docs/
dist/esm/register.js ./node_modules/@storybook/addon-controls/dist/esm/register.js ./node_modules/@storybook/addon-actions/dist/esm/register.js ./node_modules/@storybook/addon-backgrounds/dist/esm/regis
ter.js ./node_modules/@storybook/addon-viewport/dist/esm/register.js ./node_modules/@storybook/addon-toolbars/dist/esm/register.js ./.storybook/generated-refs.js
```

```
ERROR in ./node_modules/invariant/invariant.js                                                                                                                                                            
Module parse failed: parser.isAsiPosition is not a function                                                                                                                                               
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders                                        
TypeError: parser.isAsiPosition is not a function                                                                                                                                                         
    at [path-to-project-folder]/node_modules/webpack/lib/DefinePlugin.js:233:18                                                                                               
    at SyncBailHook.eval [as call] (eval at create ([path-to-project-folder]/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)       
    at Parser.walkMemberExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1958:35)                                  
    at Parser.walkExpression ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1610:10)                                        
    at Parser.walkVariableDeclaration ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:1469:32)                               
    at Parser.walkStatement ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:997:10)                                          
    at Parser.walkStatements ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:868:9)                                          
    at Parser.parse ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/Parser.js:2297:9)                                                  
    at [path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/NormalModule.js:482:32                                                           
    at [path-to-project-folder]/node_modules/@storybook/core-server/node_modules/webpack/lib/NormalModule.js:358:12                                                           
    at [path-to-project-folder]/node_modules/@storybook/core-server/node_modules/loader-runner/lib/LoaderRunner.js:373:3                                                      
    at iterateNormalLoaders ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/loader-runner/lib/LoaderRunner.js:214:10)                              
    at Array.<anonymous> ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/loader-runner/lib/LoaderRunner.js:205:4)                                  
    at Storage.finished ([path-to-project-folder]/node_modules/@storybook/core-server/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)                       
    at [path-to-project-folder]/node_modules/@storybook/core-server/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9                                           
    at [path-to-project-folder]/node_modules/graceful-fs/graceful-fs.js:123:16                                                                                                
 @ ./node_modules/react-helmet-async/lib/index.module.js 1:97-122 1:10211-10212 1:10559-10560                                                                                                             
 @ ./node_modules/@storybook/ui/dist/esm/index.js                                                                                                                                                         
 @ ./node_modules/@storybook/core-client/dist/esm/manager/index.js                                                                                                                                        
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./.storybook/manager.js ./node_modules/@storybook/core-client/dist/esm/manager/index.js ./node_modules/@storybook/addon-docs/
dist/esm/register.js ./node_modules/@storybook/addon-controls/dist/esm/register.js ./node_modules/@storybook/addon-actions/dist/esm/register.js ./node_modules/@storybook/addon-backgrounds/dist/esm/regis
ter.js ./node_modules/@storybook/addon-viewport/dist/esm/register.js ./node_modules/@storybook/addon-toolbars/dist/esm/register.js ./.storybook/generated-refs.js    
```

**To Reproduce**
1. Check out [the repo branch](https://github.com/Ensembl/ensembl-client/tree/update-webpack)
2. `npm ci`
3. `npm run storybook`
4. See the errors in the console

**System**
-  Binaries
   * Node: 14.15.1
   * npm: 7.5.4
- npmPackages:
   * @storybook/addon-essentials: 6.2.0-beta.10 => 6.2.0-beta.10 
   * @storybook/addons: 6.2.0-beta.10 => 6.2.0-beta.10 
   * @storybook/builder-webpack5: 6.2.0-beta.10 => 6.2.0-beta.10 
   * @storybook/react: 6.2.0-beta.10 => 6.2.0-beta.10 
   * @storybook/theming: 6.2.0-beta.10 => 6.2.0-beta.10

**Comment by indiejoseph** [comment]
+1

**Comment by shilman** [comment]
Hmm following your repro instructions succeeds for me... 🤔 

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 15.10.0 - ~/n/bin/node
    npm: 7.5.3 - ~/n/bin/npm
  npmPackages:
    @storybook/addon-essentials: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/addons: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/builder-webpack5: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/react: 6.2.0-beta.10 => 6.2.0-beta.10
    @storybook/theming: 6.2.0-beta.10 => 6.2.0-beta.10
```
