### ISSUE TITLE
Story with storiesOf() is not working in v6.2.0-rc.0

### ISSUE THREAD

**Issue by mgameover** [storybookjs/storybook#14242]
**Describe the bug**
storiesOf() is not working, throws the error: **Can't construct a query for the property "storyComponentElementRef" of "StorybookWrapperComponent" since the query selector wasn't defined**.

**To Reproduce**
That can be reproduced with the official samples.
1. Run [angular-cli](https://github.com/storybookjs/storybook/tree/v6.2.0-rc.0/examples/angular-cli) project
2. Go to "Story with storiesOf()" - "with text" 
3. See error:
```
VM123 vendors~main.42039db96db3fdb2f309.bundle.js:325992 Unhandled Promise rejection: Can't construct a query for the property "storyComponentElementRef" of "StorybookWrapperComponent" since the query selector wasn't defined. ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't construct a query for the property "storyComponentElementRef" of "StorybookWrapperComponent" since the query selector wasn't defined.
    at VM123 vendors~main.42039db96db3fdb2f309.bundle.js:69235
    at Array.forEach (<anonymous>)
    at _loop_1 (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:69232)
    at extractQueriesMetadata (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:69247)
    at directiveMetadata (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:69193)
    at Function.get (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:69076)
    at getComponentDef (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:42423)
    at verifyDeclarationsHaveDefinitions (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:68733)
    at Array.forEach (<anonymous>)
    at verifySemanticsOfNgModuleDef (VM123 vendors~main.42039db96db3fdb2f309.bundle.js:68708) Error: Can't construct a query for the property "storyComponentElementRef" of "StorybookWrapperComponent" since the query selector wasn't defined.
    at http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:69235:35
    at Array.forEach (<anonymous>)
    at _loop_1 (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:69232:31)
    at extractQueriesMetadata (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:69247:13)
    at directiveMetadata (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:69193:26)
    at Function.get (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:69076:64)
    at getComponentDef (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:42423:20)
    at verifyDeclarationsHaveDefinitions (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:68733:23)
    at Array.forEach (<anonymous>)
    at verifySemanticsOfNgModuleDef (http://localhost:9008/vendors~main.42039db96db3fdb2f309.bundle.js:68708:22)
api.onUnhandledError @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:325992
handleUnhandledRejection @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:326020
_loop_2 @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:326011
api.microtaskDrainDone @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:326015
drainMicroTaskQueue @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:325517
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:325410
invokeTask @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:326546
globalZoneAwareCallback @ VM123 vendors~main.42039db96db3fdb2f309.bundle.js:326583
postMessage (async)
(anonymous) @ vendors~main.cb7e4ea007e060c4f002.bundle.js:49293
send @ vendors~main.cb7e4ea007e060c4f002.bundle.js:49291
handler @ vendors~main.cb7e4ea007e060c4f002.bundle.js:29529
emit @ vendors~main.cb7e4ea007e060c4f002.bundle.js:29539
emit @ vendors~main.cb7e4ea007e060c4f002.bundle.js:22708
(anonymous) @ vendors~main.cb7e4ea007e060c4f002.bundle.js:46955
commitHookEffectListMount @ vendors~main.cb7e4ea007e060c4f002.bundle.js:127858
commitPassiveHookEffects @ vendors~main.cb7e4ea007e060c4f002.bundle.js:127896
callCallback @ vendors~main.cb7e4ea007e060c4f002.bundle.js:108315
invokeGuardedCallbackDev @ vendors~main.cb7e4ea007e060c4f002.bundle.js:108364
invokeGuardedCallback @ vendors~main.cb7e4ea007e060c4f002.bundle.js:108419
flushPassiveEffectsImpl @ vendors~main.cb7e4ea007e060c4f002.bundle.js:130980
unstable_runWithPriority @ vendors~main.cb7e4ea007e060c4f002.bundle.js:134216
runWithPriority$1 @ vendors~main.cb7e4ea007e060c4f002.bundle.js:119166
flushPassiveEffects @ vendors~main.cb7e4ea007e060c4f002.bundle.js:130947
(anonymous) @ vendors~main.cb7e4ea007e060c4f002.bundle.js:130826
workLoop @ vendors~main.cb7e4ea007e060c4f002.bundle.js:134160
flushWork @ vendors~main.cb7e4ea007e060c4f002.bundle.js:134115
performWorkUntilDeadline @ vendors~main.cb7e4ea007e060c4f002.bundle.js:133727
```

**Screenshots**
![image](https://user-images.githubusercontent.com/62712576/111232802-d857aa80-85b9-11eb-9ff9-797624a7806f.png)

**System**
Environment Info:
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.82
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.54)
  npmPackages:
    @storybook/addon-a11y: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-actions: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-backgrounds: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-controls: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-docs: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-jest: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-knobs: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-links: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-storyshots: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addon-storysource: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/addons: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/angular: 6.2.0-rc.0 => 6.2.0-rc.0
    @storybook/source-loader: 6.2.0-rc.0 => 6.2.0-rc.0

**Comment by shilman** [comment]
I'm not seeing that in the example: https://next--storybookjs.netlify.app/angular-cli/?path=/docs/legacy-story-with-storiesof--with-text

Can you provide another repro?

**Comment by mgameover** [comment]
Hi @shilman,
It looks like the issue was in `node_modules`, I guess some of the packages were not updated when I switched from v6.1   
I deleted that folder and run `npm i` once again - [angular-cli](https://github.com/storybookjs/storybook/tree/v6.2.0-rc.0/examples/angular-cli) sample works fine now.
Thanks!
