### ISSUE TITLE
Storybook not working with Gatsby v3

### ISSUE THREAD

**Issue by maxthrottleup** [storybookjs/storybook#14273]
**Describe the bug**
Storybook is not working with the latest version of Gatsby v3. It seems that the issue is that Gatsby needs only Webpack 5 to be installed and Storybook 6.2 (the one that has Webpack 5) still requires Webpack 4 to be installed. But I could be wrong here. Any advice will be greatly appreciated. We really don't want to remove Storybook from our CI/CD pipeline.

**To Reproduce**

1. gatsby new storybook-test https://github.com/gatsbyjs/gatsby-starter-default
1. cd storybook-test
1. npx sbnext init --builder webpack5
1. npm run storybook

**Expected behavior**
I expect Storybook to build and start serving the preview on localhost port 6006 as usual.

**Code snippets**
This is where it gets stuck.

```
29% building 2/13 entries 2896/2896 dependencies 506/761 modules(node:72392) UnhandledPromiseRejectionWarning: TypeError: compilation.getAssetPath is not a function
    at /Users/max/WebstormProjects/storybook-test/node_modules/html-webpack-plugin/index.js:169:25
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Watching.js:51:19)
    at /Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
(node:72392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
99% done plugins webpack-hot-middlewarewebpack built preview 0c93ce49d51e49e63820 in 2956ms
```

Just clarifying that the build process stops here. It does not start serving on port 6006.

**System**

```
 System:
    OS: macOS 11.2.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.3 => 6.2.0-rc.4 
    @storybook/addon-essentials: ^6.2.0-rc.3 => 6.2.0-rc.4 
    @storybook/addon-links: ^6.2.0-rc.3 => 6.2.0-rc.4 
    @storybook/builder-webpack5: ^6.2.0-rc.3 => 6.2.0-rc.4 
    @storybook/react: ^6.2.0-rc.3 => 6.2.0-rc.4
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200086242226182) by [Unito](https://www.unito.io/learn-more)

**Comment by Niznikr** [comment]
Are you using yarn resolutions for handling Webpack 5 as a dependency? See [this repo](https://github.com/jean-leonco/storybook-webpack-5) for an example. We have been able to use Gatsby v3 and Storybook 6.2 with Webpack 5 together in a monorepo fine using resolutions.

**Comment by maxthrottleup** [comment]
@Niznikr We are not using yarn, I have not used it before. Could you please elaborate more on how this can be done? If you could provide the steps on how to set it up with the Gatsby starter, it could really help.

Thanks!

**Comment by Niznikr** [comment]
Sure! Just use `yarn` instead of `npm` to install your dependencies and have a resolutions field with Webpack 5 in your package.json before running the install [as seen here](https://github.com/jean-leonco/storybook-webpack-5/blob/main/package.json#L10).

**Comment by maxthrottleup** [comment]
Thank you @Niznikr for your help.

For others encountering the same problem, I created a [repo](https://github.com/maxthrottleup/storybook-test) with Gatsby v3 and Storybook 6.2. Here are the steps to get both running:

1. git clone https://github.com/maxthrottleup/storybook-test.git
2. cd storybook-test
3. yarn install

And then we'll be able to run Gatsby or Storybook like this:
Gatsby: gatsby develop
Storybook: yarn run storybook

**A longer explanation of what I did**

1. I created a Gatsby site based on the gatsby-starter-default. Instructions [here](https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-default/)
2. Removed the node_modules and the package-json.lock
3. Merged the code to the Storybook Webpack 5 starter [repo](https://github.com/jean-leonco/storybook-webpack-5) provided earlier. 
4. Replaced the yarn resolutions for the ones suggested by Gatsby on the v2-v3 migration guide [here](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#handling-dependencies-for-plugins-that-are-not-yet-updated).

And that's it!

I would really like to keep using npm instead of yarn, but I am glad that there's the workaround for now. My next step will be to test this repo with Gatsby Cloud and Chromatic, which is our current CI/CD pipeline.

**Comment by maxthrottleup** [comment]
@shilman I don't know if this should still be considered as "has workaround". Although the solution that suggested @Niznikr and the repo that I set up works (using version `6.2.0-alpha.30`), the Storybook build crashes when I upgrade to version `6.2.0-rc.6`. I created a branch called "[rc-6](https://github.com/maxthrottleup/storybook-test/tree/rc-6)" on my previous repo so we can replicate this issue.

The error is the following:

```
10% building 0/1 entries 0/0 dependencies 0/0 modulesWARN Force closed preview build
ERR! TypeError: Cannot read property 'data' of undefined
ERR!     at setData (/Users/max/WebstormProjects/storybook-test/node_modules/webpack-virtual-modules/index.js:84:15)
ERR!     at CachedInputFileSystem.finalInputFileSystem._writeVirtualFile (/Users/max/WebstormProjects/storybook-test/node_modules/webpack-virtual-modules/index.js:118:9)
ERR!     at VirtualModulesPlugin.writeModule (/Users/max/WebstormProjects/storybook-test/node_modules/webpack-virtual-modules/index.js:64:24)
ERR!     at /Users/max/WebstormProjects/storybook-test/node_modules/webpack-virtual-modules/index.js:165:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at afterResolversHook (/Users/max/WebstormProjects/storybook-test/node_modules/webpack-virtual-modules/index.js:164:40)
ERR!     at Hook.eval [as call] (eval at create (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
ERR!     at Hook.CALL_DELEGATE [as _call] (/Users/max/WebstormProjects/storybook-test/node_modules/tapable/lib/Hook.js:14:14)
ERR!     at WebpackOptionsApply.process (/Users/max/WebstormProjects/storybook-test/node_modules/webpack/lib/WebpackOptionsApply.js:602:33)
ERR!     at createCompiler (/Users/max/WebstormProjects/storybook-test/node_modules/webpack/lib/webpack.js:78:28)
ERR!     at create (/Users/max/WebstormProjects/storybook-test/node_modules/webpack/lib/webpack.js:118:16)
ERR!     at webpack (/Users/max/WebstormProjects/storybook-test/node_modules/webpack/lib/webpack.js:142:32)
ERR!     at Object.f [as get] (/Users/max/WebstormProjects/storybook-test/node_modules/webpack/lib/index.js:41:15)
ERR!     at Object.start (/Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/dist/cjs/manager/builder.js:116:27)
ERR!     at async Promise.all (index 1)
ERR!     at async storybookDevServer (/Users/max/WebstormProjects/storybook-test/node_modules/@storybook/core-server/dist/cjs/dev-server.js:103:28)
```

Additionally just wanted to report here that I tried with these suggested [resolutions](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#yarn-resolutions) as well with no success.

**Comment by chris-erickson** [comment]
I got the whole thing "working" with webpack 5 but none of my Gatsby styles or CSS class names (using SASS and CSS Modules) are present in the output.  Any idea what part of the chain I'm missing?

**Comment by TheFirstMe** [comment]
Storybook v6 seems to be working fine with Gatsby v3 even with npm. I followed the same steps on Gatsby docs for setting up Storybook v5

**Comment by pmccreadycs** [comment]
@chris-erickson did you manage to find a way around it by any chance? I'm having the same issue

**Comment by pmccreadycs** [comment]
Hope this helps others. I managed to solve my issue with Gatsby 3 and Storybook 6.2.5 (with Webpack5). I initially followed https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324

I had to change my main.js file to include the following webpack config:

```javascript
module.exports = {
  stories: ["../src/**/*.stories.{js,jsx}"],
  addons: [
    "@storybook/addon-docs",
    "@storybook/addon-actions",
    "@storybook/addon-controls",
    "@storybook/addon-a11y",
    "@storybook/addon-viewport",
  ],
  // https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324
  core: {
    builder: "webpack5",
  },
  webpackFinal: async (config) => {
    // https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/
    config.module.rules.push({
      test: /\.(js)$/,
      use: [
        {
          loader: require.resolve("babel-loader"),
          options: {
            presets: [
              // use @babel/preset-react for JSX and env (instead of staged presets)
              require.resolve("@babel/preset-react"),
              require.resolve("@babel/preset-env"),
            ],
            plugins: [
              // use @babel/plugin-proposal-class-properties for class arrow functions
              require.resolve("@babel/plugin-proposal-class-properties"),
              // use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
              require.resolve("babel-plugin-remove-graphql-queries"),
              // use babel-plugin-react-docgen to ensure PropTables still appear
              require.resolve("babel-plugin-react-docgen"),
            ],
          },
        },
      ],
      exclude: [/node_modules\/(?!(gatsby)\/)/],
    })

    config.module.rules.push({
      test: /\.s[ac]ss$/i,
      oneOf: [
        // module.scss files (e.g component styles.module.scss)
        // https://webpack.js.org/loaders/style-loader/#modules
        {
          test: /\.module\.s?css$/,
          use: [
            // Add exports of a module as style to DOM
            {
              loader: "style-loader",
              options: {
                esModule: true,
                modules: {
                  namedExport: true,
                },
              },
            },
            // Loads CSS file with resolved imports and returns CSS code
            {
              loader: "css-loader",
              options: {
                modules: true,
                esModule: true,
                modules: {
                  namedExport: true,
                },
              },
            },
            // Loads and compiles a SASS/SCSS file
            "sass-loader"
          ],
        },
        // scss files that are not modules (e.g. custom.scss)
        {
          use: [
            // Add exports of a module as style to DOM
            "style-loader",
            // Loads CSS file with resolved imports and returns CSS code
            "css-loader",
            // Loads and compiles a SASS/SCSS file
            "sass-loader"
          ],
        }
      ]
    })

    return config
  }
}
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
