### ISSUE TITLE
addon-jest doesn't work with webpack 5

### ISSUE THREAD

**Issue by j3rem1e** [storybookjs/storybook#14319]
**Describe the bug**

When using addon-jest with the webpack5 builder, the stories fail with this error : 

```
TypeError: (0 , upath__WEBPACK_IMPORTED_MODULE_11__.normalize) is not a function
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:7717:75
    at Array.find (<anonymous>)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:7716:45
    at Array.map (<anonymous>)
    at findTestResults (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:7708:35)
    at emitAddTests (http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:7737:12)
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:7759:7
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:8952:21
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:26526:28
    at http://localhost:6006/vendors-node_modules_storybook_addon-actions_dist_esm_preset_addArgs_js-generated-other-entry-54cc83.iframe.bundle.js:26532:17
```

This addon uses upath in the browser which need the path module. In webpack5, this module doesn't have an automatic polyfill.

**Screenshots**
<img width="1426" alt="Capture d’écran 2021-03-23 à 18 51 56" src="https://user-images.githubusercontent.com/2384547/112194532-44b15a00-8c09-11eb-8964-d09a324d5424.png">

**System**

```
Environment Info:

  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.8 => 6.2.0-rc.8
    @storybook/addon-essentials: ^6.2.0-rc.8 => 6.2.0-rc.8
    @storybook/addon-jest: ^6.2.0-rc.8 => 6.2.0-rc.8
    @storybook/addon-links: ^6.2.0-rc.8 => 6.2.0-rc.8
    @storybook/addon-svelte-csf: ^1.0.0 => 1.0.0
    @storybook/builder-webpack5: ^6.2.0-rc.8 => 6.2.0-rc.8
    @storybook/svelte: ^6.2.0-rc.8 => 6.2.0-rc.8
```

**Comment by j3rem1e** [comment]
As a workaround, it is solved by adding `config.resolve.fallback.path = require.resolve("path-browserify");` in a webpackFinal function in `.storybook/main.js`.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
