### ISSUE TITLE
M1 running development mode will return error and macbook start lagging

### ISSUE THREAD

**Issue by heysyam99** [storybookjs/storybook#14412]
**Describe the bug**
I am M1 user but after running `yarn dev`, an error occurred and my macbook start lagging.

**To Reproduce**

1. `git clone https://github.com/storybookjs/storybook.git`
2. `cd storybook`
3. `yarn bootstrap --core`
4. `yarn test`
5. `yarn dev`

**Expected behavior**
To start the project in development mode

**Screenshots**

**System**
`yarn run v1.22.10
$ concurrently --kill-others "yarn dev:tsc" "yarn dev:babel"
$ lerna exec --scope @storybook/* --parallel -- cross-env-shell node \$LERNA_ROOT_PATH/scripts/utils/watch-babel.js
$ lerna exec --scope @storybook/* --parallel -- cross-env-shell node \$LERNA_ROOT_PATH/scripts/utils/watch-tsc.js
[1] lernalerna notice cli v3.22.1
[1]  notice cli v3.22.1
[0] lerna notice filter including "@storybook/*"
[1] lerna notice filter including "@storybook/*"
[1] lerna info filter [ '@storybook/*' ]
[0] lerna info filter [ '@storybook/*' ]
[0] lerna info Executing command in 66 packages: "cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-tsc.js"
[1] lerna info Executing command in 66 packages: "cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-babel.js"
[1] @storybook/example-devkits: No src dir
[1] @storybook/client-logger: internal/modules/cjs/loader.js:883
[1] @storybook/client-logger:   throw err;
[1] @storybook/client-logger:   ^
[1] @storybook/client-logger: Error: Cannot find module 'shelljs'
[1] @storybook/client-logger: Require stack:
[1] @storybook/client-logger: - /Users/heysyam99/Projects/storybook/scripts/utils/compile-babel.js
[1] @storybook/client-logger: - /Users/heysyam99/Projects/storybook/scripts/utils/watch-babel.js
[1] @storybook/client-logger:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[1] @storybook/client-logger:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[1] @storybook/client-logger:     at Module.require (internal/modules/cjs/loader.js:952:19)
[1] @storybook/client-logger:     at require (internal/modules/cjs/helpers.js:88:18)
[1] @storybook/client-logger:     at Object.<anonymous> (/Users/heysyam99/Projects/storybook/scripts/utils/compile-babel.js:4:15)
[1] @storybook/client-logger:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1] @storybook/client-logger:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1] @storybook/client-logger:     at Module.load (internal/modules/cjs/loader.js:928:32)
[1] @storybook/client-logger:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1] @storybook/client-logger:     at Module.require (internal/modules/cjs/loader.js:952:19) {
[1] @storybook/client-logger:   code: 'MODULE_NOT_FOUND',
[1] @storybook/client-logger:   requireStack: [
[1] @storybook/client-logger:     '/Users/heysyam99/Projects/storybook/scripts/utils/compile-babel.js',
[1] @storybook/client-logger:     '/Users/heysyam99/Projects/storybook/scripts/utils/watch-babel.js'
[1] @storybook/client-logger:   ]
[1] @storybook/client-logger: }
[1] @storybook/builder-webpack5: internal/fs/utils.js:307
[1] @storybook/builder-webpack5:     throw err;
[1] @storybook/builder-webpack5:     ^
[1] @storybook/builder-webpack5: Error: ENFILE: file table overflow, open '/Users/heysyam99/Projects/storybook/node_modules/shelljs/src/test.js'
[1] @storybook/builder-webpack5:     at Object.openSync (fs.js:476:3)
[1] @storybook/builder-webpack5:     at Object.readFileSync (fs.js:377:35)
[1] @storybook/builder-webpack5:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1090:18)
[1] @storybook/builder-webpack5:     at Module.load (internal/modules/cjs/loader.js:928:32)
[1] @storybook/builder-webpack5:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1] @storybook/builder-webpack5:     at Module.require (internal/modules/cjs/loader.js:952:19)
[1] @storybook/builder-webpack5:     at require (internal/modules/cjs/helpers.js:88:18)
[1] @storybook/builder-webpack5:     at /Users/heysyam99/Projects/storybook/node_modules/shelljs/shell.js:25:3
[1] @storybook/builder-webpack5:     at Array.forEach (<anonymous>)
[1] @storybook/builder-webpack5:     at Object.<anonymous> (/Users/heysyam99/Projects/storybook/node_modules/shelljs/shell.js:24:23) {
[1] @storybook/builder-webpack5:   errno: -23,
[1] @storybook/builder-webpack5:   syscall: 'open',
[1] @storybook/builder-webpack5:   code: 'ENFILE',
[1] @storybook/builder-webpack5:   path: '/Users/heysyam99/

Projects/storybook/node_modules/shelljs/src/test.js'
[1] @storybook/builder-webpack5: }
[1] @storybook/node-logger: internal/fs/utils.js:307
[1] @storybook/node-logger:     throw err;
[1] @storybook/node-logger:     ^
[1] @storybook/node-logger: Error: ENFILE: file table overflow, open '/Users/heysyam99/Projects/storybook/node_modules/cross-env/src/index.js'
[1] @storybook/node-logger:     at Object.openSync (fs.js:476:3)
[1] @storybook/node-logger:     at Object.readFileSync (fs.js:377:35)
[1] @storybook/node-logger:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1090:18)
[1] @storybook/node-logger:     at Module.load (internal/modules/cjs/loader.js:928:32)
[1] @storybook/node-logger:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1] @storybook/node-logger:     at Module.require (internal/modules/cjs/loader.js:952:19)
[1] @storybook/node-logger:     at require (internal/modules/cjs/helpers.js:88:18)
[1] @storybook/node-logger:     at Object.<anonymous> (/Users/heysyam99/Projects/storybook/node_modules/cross-env/src/bin/cross-env-shell.js:3:18)
[1] @storybook/node-logger:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1] @storybook/node-logger:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
[1] @storybook/node-logger:   errno: -23,
[1] @storybook/node-logger:   syscall: 'open',
[1] @storybook/node-logger:   code: 'ENFILE',
[1] @storybook/node-logger:   path: '/Users/heysyam99/Projects/storybook/node_modules/cross-env/src/index.js'
[1] @storybook/node-logger: }
[1] @storybook/addon-viewport: Error: ENFILE: file table overflow, open '/Users/heysyam99/Projects/storybook/node_modules/@babel/traverse/lib/path/inference/inferer-reference.js'
[1] @storybook/addon-viewport:     at Object.openSync (fs.js:476:3)
[1] @storybook/addon-viewport:     at Object.readFileSync (fs.js:377:35)
[1] @storybook/addon-viewport:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1090:18)
[1] @storybook/addon-viewport:     at Module.load (internal/modules/cjs/loader.js:928:32)
[1] @storybook/addon-viewport:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1] @storybook/addon-viewport:     at Module.require (internal/modules/cjs/loader.js:952:19)
[1] @storybook/addon-viewport:     at require (internal/modules/cjs/helpers.js:88:18)
[1] @storybook/addon-viewport:     at Object.<anonymous> (/Users/heysyam99/Projects/storybook/node_modules/@babel/traverse/lib/path/inference/inferers.js:38:48)
[1] @storybook/addon-viewport:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1] @storybook/addon-viewport:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
[1] @storybook/addon-viewport:   errno: -23,
[1] @storybook/addon-viewport:   syscall: 'open',
[1] @storybook/addon-viewport:   code: 'ENFILE',
[1] @storybook/addon-viewport:   path: '/Users/heysyam99/Projects/storybook/node_modules/@babel/traverse/lib/path/inference/inferer-reference.js'
[1] @storybook/addon-viewport: }
[1] lerna ERR! cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-babel.js exited 1 in '@storybook/core-common'
[1] lerna ERR! cross-env-shell node $LERNA_ROOT_PATH/scripts/utils/watch-babel.js exited 1 in '@storybook/core-common'
[1] lerna WARN complete Waiting for 60 child processes to exit. CTRL-C to exit immediately.
[0] @storybook/addon-a11y: 9:07:04 PM - Starting compilation in watch mode...
[0] @storybook/addon-actions: 9:07:05 PM - Starting compilation in watch mode...
[0] @storybook/addon-backgrounds: 9:07:05 PM - Starting compilation in watch mode...
[0] @storybook/addon-controls: 9:07:05 PM - Starting compilation in watch mode...
[0] @storybook/addon-cssresources: 9:07:07 PM - Starting compilation in watch mode...
[0] @storybook/addon-design-assets: 9:07:08 PM - Starting compilation in watch mode...
[0] @storybook/addon-docs: 9:07:08 PM - Starting compilation in watch mode...
[0] @storybook/addon-essentials: 9:07:08 PM - Starting compilation in watch mode...
[0] @storybook/addon-events: 9:07:06`

**Comment by shilman** [comment]
If you know the packages you'll be working on, e.g. `@storybook/addon-docs` and `@storybook/components`, you can run the following instead which is much more efficient:

```
yarn build addon-docs components --watch
```

We'll be improving the contributor/maintainer DX dramatically in 6.3

**Comment by heysyam99** [comment]
> If you know the packages you'll be working on, e.g. `@storybook/addon-docs` and `@storybook/components`, you can run the following instead which is much more efficient:
> 
> ```
> yarn build addon-docs components --watch
> ```
> 
> We'll be improving the contributor/maintainer DX dramatically in 6.3

This helps me to run it, thank you very much @shilman
