### ISSUE TITLE
Error when there is a simple quote in the project path.

### ISSUE THREAD

**Issue by Gagaro** [storybookjs/storybook#14638]
**Describe the bug**

If there is a simple quote (`'`) in the project path, then the `npm run storybook` command does not work. Note that there is a `test ' test` directory in the log below:

```
ModuleParseError: Module parse failed: Unexpected token (8:116)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| /* eslint-disable import/no-unresolved */
> import { addDecorator, addParameters, addLoader, addArgTypesEnhancer } from 'C:/Users/Gagaro/PycharmProjects/test ' test/node_modules/@storybook/client-api';
| import { logger } from 'C:/Users/Gagaro/PycharmProjects/test ' test/node_modules/@storybook/client-logger';
| import * as config from 'C:/Users/Gagaro/PycharmProjects/test ' test/node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js';
    at handleParseError (C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:891:19)
    at C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:992:5
    at processResult (C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:718:11)
    at C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:778:5
    at C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:406:3
    at iterateNormalLoaders (C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:232:10)
    at C:\Users\Gagaro\PycharmProjects\test ' test\node_modules\@storybook\builder-webpack5\node_modules\loader-runner\lib\LoaderRunner.js:223:4
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
```

**To Reproduce**
Any project with a simple quote in its path.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.128
    Edge: Spartan (44.18362.1474.0)
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.9 => 6.3.0-alpha.9
    @storybook/addon-essentials: ^6.3.0-alpha.9 => 6.3.0-alpha.9
    @storybook/addon-links: ^6.3.0-alpha.9 => 6.3.0-alpha.9
    @storybook/builder-webpack5: ^6.3.0-alpha.9 => 6.3.0-alpha.9
    @storybook/vue3: ^6.3.0-alpha.9 => 6.3.0-alpha.9
```

**Comment by Maokli** [comment]
try the following 
import { addDecorator, addParameters, addLoader, addArgTypesEnhancer } from "C:/Users/Gagaro/PycharmProjects/test ' test/node_modules/@storybook/client-api";

**Comment by Gagaro** [comment]
It is not in any of my files.

Please see https://github.com/Gagaro/storybook-quote-bug for a way to reproduce.

**Comment by Gagaro** [comment]
Reproduced on Linux:

```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz
  Binaries:
    Node: 14.16.0 - ~/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 87.0
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.9 => 6.3.0-alpha.9 
    @storybook/addon-essentials: ^6.3.0-alpha.9 => 6.3.0-alpha.9 
    @storybook/addon-links: ^6.3.0-alpha.9 => 6.3.0-alpha.9 
    @storybook/vue3: ^6.3.0-alpha.9 => 6.3.0-alpha.9 
```

**Comment by Gagaro** [comment]
@shilman can you reflag this as a bug please?

**Comment by valentinpalkovic** [comment]
Thanks for the report! The failing `generated-stories-entry.js` template that interpolated raw project paths around `addDecorator`/`addParameters` was removed when `@storybook/client-api` was deleted (v8) and the preview bootstrap was rewritten. v10's bootstrap doesn't string-interpolate paths the same way, so this is resolved.
