### ISSUE TITLE
Webpack 5 upgrade - Error: Duplicate plugin/preset detected.

### ISSUE THREAD

**Issue by AriaMoradpour** [storybookjs/storybook#14671]
**What's the problem?**
Clear and concise statement of what's troubling you.
After upgrading to the latest version and using webpack 5, storybook does not start. i get the following unhandled promise rejection thrown. 

```
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js",
    "dirname": "/Users/ariamoradpour/dev/apfm/web-lighthouse",
    "ownPass": false,
    "file": {
      "request": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js",
      "resolved": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js"
    }
  },
  {
    "alias": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js",
    "dirname": "/Users/ariamoradpour/dev/apfm/web-lighthouse",
    "ownPass": false,
    "file": {
      "request": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js",
      "resolved": "/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/@babel/preset-typescript/lib/index.js"
    }
  }
```
**Is there documentation on this?**
https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade
**Additional context**

**Comment by AriaMoradpour** [comment]
I can resolve the issue after removing  `presets: ['@storybook/preset-typescript'],` in  my main.js file, but then i get a lot of  errors. 

---
errors after 
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'components/leadgen/ui-leadgen-form-block/mock-data' in '/Users/ariamoradpour/dev/apfm/web-lighthouse/src/modules/ui-leadgen-module'
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/Compilation.js:1735:28
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:726:13
    at eval (eval at create (/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:642:24
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:796:8
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:916:5
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/neo-async/async.js:6883:13
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/lib/NormalModuleFactory.js:899:45
    at finishWithoutResolve (/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve 'components/leadgen/ui-leadgen-form-block/mock-data' in '/Users/ariamoradpour/dev/apfm/web-lighthouse/src/modules/ui-leadgen-module'
  Parsed request is a module
  using description file: /Users/ariamoradpour/dev/apfm/web-lighthouse/package.json (relative path: ./src/modules/ui-leadgen-module)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/ariamoradpour/dev/apfm/web-lighthouse/src/modules/ui-leadgen-module/node_modules doesn't exist or is not a directory
      /Users/ariamoradpour/dev/apfm/web-lighthouse/src/modules/node_modules doesn't exist or is not a directory
      /Users/ariamoradpour/dev/apfm/web-lighthouse/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules
        /Users/ariamoradpour/dev/apfm/web-lighthouse/node_modules/components doesn't exist
      /Users/ariamoradpour/dev/apfm/node_modules doesn't exist or is not a directory
      /Users/ariamoradpour/dev/node_modules doesn't exist or is not a directory
      /Users/ariamoradpour/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```
----
main.js

```
module.exports = {
  core: {
    builder: "webpack5",
  },
  stories: [
    '../src/ui-docs/**/*.stories.mdx',
    '../src/ui-kit/**/*.stories.(tsx|mdx)',
    '../src/components/**/*.stories.(tsx|mdx)',
    '../src/modules/**/*.stories.(tsx|mdx)',
  ],
  addons: ['@storybook/addon-docs', '@storybook/addon-viewport'],
  // presets: ['@storybook/preset-typescript'],
};
```

**Comment by shilman** [comment]
@AriaMoradpour if you upgrade to 6.2, it has typescript support built in

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
