### ISSUE TITLE
tsconfig could not be read on windows

### ISSUE THREAD

**Issue by Jakob-em** [storybookjs/storybook#14703]
**Describe the bug**
It seems like the recent changes (https://github.com/storybookjs/storybook/pull/14358) to the angular configuration detection broke something on windows.
This makes the current prerelease version unusable on windows.
If I try to run storybook in a new angular project I get the following **error**:
```
info => Using angular project "storybook-test" for configuring Storybook
ERR! => Could not get angular cli webpack config
ERR! Error: Error: ENOENT: no such file or directory, lstat 'C:/C/work/storybook-test/tsconfig.app.json'
ERR!     at Object.lstatSync (fs.js:1077:3)
ERR!     at NodeJSFileSystem.NodeJSReadonlyFileSystem.lstat (C:\work\storybook-test\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\node_js_file_system.js:107:23)
ERR!     at calcProjectFileAndBasePath (C:\work\storybook-test\node_modules\@angular\compiler-cli\src\perform_compile.js:127:33)
ERR!     at Object.readConfiguration (C:\work\storybook-test\node_modules\@angular\compiler-cli\src\perform_compile.js:161:22)
ERR!     at Object.readTsconfig (C:\work\storybook-test\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:26:29)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:155:67
ERR!     at step (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:44:71
ERR!     at new Promise (<anonymous>)
ERR!     at __awaiter (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:40:12)
ERR!     at buildWebpackConfigOptions (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:135:12)
ERR!     at Object.<anonymous> (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:196:42)
ERR!     at step (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:44:71
ERR!
ERR!     at Object.readTsconfig (C:\work\storybook-test\node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:28:15)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:155:67
ERR!     at step (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:44:71
ERR!     at new Promise (<anonymous>)
ERR!     at __awaiter (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:40:12)
ERR!     at buildWebpackConfigOptions (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:135:12)
ERR!     at Object.<anonymous> (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:196:42)
ERR!     at step (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:69:23)
ERR!     at Object.next (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:50:53)
ERR!     at C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:44:71
ERR!     at new Promise (<anonymous>)
ERR!     at __awaiter (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:40:12)
ERR!     at Object.extractAngularCliWebpackConfig (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\angular-devkit-build-webpack.js:190:12)
ERR!     at Object.<anonymous> (C:\work\storybook-test\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js:106:73)
```

**To Reproduce**
```
ng new storybook-test
cd storybook-test
npx sb@next init
npm run storybook
```
**System**
```
Environment Info:

  System:
    OS: Windows 10
  Binaries:
    Node: 14.16.1
    Yarn: 1.22.4
    npm: 6.14.13
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/addon-essentials: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/addon-links: ^6.3.0-alpha.14 => 6.3.0-alpha.14
    @storybook/angular: ^6.3.0-alpha.14 => 6.3.0-alpha.14

Angular version: 11.2.11
```

**Additional context**
I am not 100% sure that this is related to windows, because I didn't have time to test it on mac/linux yet, but looking at the error (`C:/C/work/storybook-test/tsconfig.app.json`) it seems to be related to the file resolution on windows.

**Comment by clipvision** [comment]
I have the same problem too, I was testing the alpha version for the rendering on toolbar buttons click.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.16 containing PR #14747 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Jakob-em** [comment]
I can confirm that it's working with `v6.3.0-alpha.16`. Thanks for the quick fix 🎉
