### ISSUE TITLE
Unable to start @storybook/lit 6.3.0-alpha.22

### ISSUE THREAD

**Issue by Niznikr** [storybookjs/storybook#14882]
**Describe the bug**
When trying to start Storybook lit with `node_modules/@storybook/lit/bin/index.js` the following error is returned:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../dist/cjs/server'
Require stack:
- /Users/rniznik/Documents/pharos/node_modules/@storybook/lit/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/rniznik/Documents/pharos/node_modules/@storybook/lit/bin/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rniznik/Documents/pharos/node_modules/@storybook/lit/bin/index.js'
  ]
}
```

Upon inspection, the `dist` directory is indeed missing from the package. Perhaps it is not building when installed?

**To Reproduce**

1. Add `@storybook/lit` to a project.
2. Try running `start-storybook`

**System**
```
Environment Info:

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Edge: 90.0.818.56
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-a11y: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-actions: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-backgrounds: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-controls: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-docs: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-google-analytics: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storysource: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addon-viewport: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/addons: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/builder-webpack5: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/lit: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/react: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/source-loader: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
    @storybook/theming: ^6.3.0-alpha.22 => 6.3.0-alpha.22 
```

**Comment by shilman** [comment]
Thanks @Niznikr! It appears that the `dist` folder didn't make it into the release somehow. I'll try to re-release now and see if I can figure out what's going wrong in the publishing step.
