### ISSUE TITLE
[manager-webpack5] Cannot find module '../presets/manager-preset'

### ISSUE THREAD

**Issue by JounQin** [storybookjs/storybook#15018]
**Describe the bug**

```log
ERR! Error: Cannot find module '../presets/manager-preset'
ERR! Require stack:
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/manager-webpack5/dist/cjs/index.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/server.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/dist/ts3.9/server/build.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/bin/build.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
ERR!     at Object.<anonymous> (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/manager-webpack5/dist/cjs/index.js:443:28)
ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:32:36
ERR!     at getManagerBuilder (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:31:24)
ERR!     at buildStaticStandalone (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js:93:24)
ERR!     at Object.buildStatic (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js:149:5)
ERR!  Error: Cannot find module '../presets/manager-preset'
ERR! Require stack:
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/manager-webpack5/dist/cjs/index.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/server.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/dist/ts3.9/server/build.js
ERR! - /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/bin/build.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
ERR!     at Object.<anonymous> (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/manager-webpack5/dist/cjs/index.js:443:28)
ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at /home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:32:36
ERR!     at getManagerBuilder (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:31:24)
ERR!     at buildStaticStandalone (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js:93:24)
ERR!     at Object.buildStatic (/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js:149:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/manager-webpack5/dist/cjs/index.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/build-static.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/core/server.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/dist/ts3.9/server/build.js',
ERR!     '/home/jenkins/agent/workspace/frontend/frontend-common-snippet/node_modules/@storybook/angular/bin/build.js'
ERR!   ]
ERR! }
```

**To Reproduce**

N/A

**System**

```log
Environment Info:

  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 87.0
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.3.0-alpha.41 => 6.3.0-alpha.41 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-knobs: ^6.3.0-alpha.21 => 6.3.0-alpha.21 
    @storybook/angular: ^6.3.0-alpha.41 => 6.3.0-alpha.41 
    @storybook/builder-webpack5: ^6.3.0-alpha.41 => 6.3.0-alpha.41 
    @storybook/manager-webpack5: ^6.3.0-alpha.37 => 6.3.0-alpha.37 
    @storybook/source-loader: ^6.3.0-alpha.41 => 6.3.0-alpha.41
```

**Additional context**

Change it to `./presets/manager-preset` works to me locally.

**Comment by shilman** [comment]
Please upgrade `@storybook/manager-webpack5` to `6.3.0-alpha.41`
