### ISSUE TITLE
Storybook webpack 5 Validation Error

### ISSUE THREAD

**Issue by Skellord** [storybookjs/storybook#15028]
Have a problem with run storybook after clean istall 
<pre>
<code>
npx sb@next init --builder webpack5
</code>
</pre>
Webpack version 5.37.1, yarn resolutions added.
Devdependencies
<pre>
<code>
    "@storybook/addon-actions": "^6.3.0-alpha.43",
    "@storybook/addon-essentials": "^6.3.0-alpha.43",
    "@storybook/addon-links": "^6.3.0-alpha.43",
    "@storybook/builder-webpack5": "^6.3.0-alpha.43",
    "@storybook/manager-webpack5": "^6.3.0-alpha.41",
    "@storybook/node-logger": "^6.3.0-alpha.43",
    "@storybook/preset-create-react-app": "^3.1.7",
    "@storybook/react": "^6.3.0-alpha.43"
</code>
</pre>
Error:
<pre>
<code>
ERR! ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
ERR!  - options has an unknown property 'sourceMap'. These properties are valid:
ERR!    object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
ERR!     at validate (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\schema-utils\dist\validate.js:104:11)
ERR!     at new TerserPlugin (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\terser-webpack-plugin\dist\index.js:131:31)
ERR!     at module.exports (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\react-scripts\config\webpack.config.js:246:9)
ERR!     at Object.webpack (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\preset-create-react-app\dist\index.js:108:57)
ERR!     at C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-common\dist\cjs\presets.js:274:28
ERR!     at async Object.start (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:74:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\dev-server.js:123:28)
ERR!     at async buildDevStandalone (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:110:31)
ERR!     at async buildDev (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:152:5)
ERR!  ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
ERR!  - options has an unknown property 'sourceMap'. These properties are valid:
ERR!    object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
ERR!     at validate (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\schema-utils\dist\validate.js:104:11)
ERR!     at new TerserPlugin (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\terser-webpack-plugin\dist\index.js:131:31)
ERR!     at module.exports (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\react-scripts\config\webpack.config.js:246:9)
ERR!     at Object.webpack (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\preset-create-react-app\dist\index.js:108:57)
ERR!     at C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-common\dist\cjs\presets.js:274:28
ERR!     at async Object.start (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:74:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\dev-server.js:123:28)
ERR!     at async buildDevStandalone (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:110:31)
ERR!     at async buildDev (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:152:5) {
ERR!   errors: [
ERR!     {
ERR!       keyword: 'additionalProperties',
ERR!       dataPath: '',
ERR!       schemaPath: '#/additionalProperties',
ERR!       params: [Object],
ERR!       message: 'should NOT have additional properties',
ERR!       schema: false,
ERR!       parentSchema: [Object],
ERR!       data: [Object]
ERR!     }
ERR!   ],
ERR!   schema: {
ERR!     definitions: { Rule: [Object], Rules: [Object] },
ERR!     title: 'TerserPluginOptions',
ERR!     type: 'object',
ERR!     additionalProperties: false,
ERR!     properties: {
ERR!       test: [Object],
ERR!       include: [Object],
ERR!       exclude: [Object],
ERR!       terserOptions: [Object],
ERR!       extractComments: [Object],
ERR!       parallel: [Object],
ERR!       minify: [Object]
ERR!     },
ERR!     default: {
ERR!       definitions: [Object],
ERR!       title: 'TerserPluginOptions',
ERR!       type: 'object',
ERR!       additionalProperties: false,
ERR!       properties: [Object]
ERR!     }
ERR!   },
ERR!   headerName: 'Terser Plugin',
ERR!   baseDataPath: 'options',
ERR!   postFormatter: null
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\sisyphus\Documents\Projects\frontend-cub>yarn storybook
yarn run v1.22.10
$ start-storybook -p 6006
info @storybook/react v6.3.0-alpha.43
info
info => Loading presets
info => Loading 1 config file in "C:\Users\sisyphus\Documents\Projects\frontend-cub\.storybook"
info => Loading 7 other files in "C:\Users\sisyphus\Documents\Projects\frontend-cub\.storybook"
info => Adding stories defined in "C:\Users\sisyphus\Documents\Projects\frontend-cub\.storybook\main.js"
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
ERR! ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
ERR!  - options has an unknown property 'sourceMap'. These properties are valid:
ERR!    object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
ERR!     at validate (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\schema-utils\dist\validate.js:104:11)
ERR!     at new TerserPlugin (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\terser-webpack-plugin\dist\index.js:131:31)
ERR!     at module.exports (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\react-scripts\config\webpack.config.js:246:9)
ERR!     at Object.webpack (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\preset-create-react-app\dist\index.js:108:57)
ERR!     at C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-common\dist\cjs\presets.js:274:28
ERR!     at async Object.start (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:74:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\dev-server.js:123:28)
ERR!     at async buildDevStandalone (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:110:31)
ERR!     at async buildDev (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:152:5)
ERR!  ValidationError: Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
ERR!  - options has an unknown property 'sourceMap'. These properties are valid:
ERR!    object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
ERR!     at validate (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\schema-utils\dist\validate.js:104:11)
ERR!     at new TerserPlugin (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\terser-webpack-plugin\dist\index.js:131:31)
ERR!     at module.exports (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\react-scripts\config\webpack.config.js:246:9)
ERR!     at Object.webpack (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\preset-create-react-app\dist\index.js:108:57)
ERR!     at C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-common\dist\cjs\presets.js:274:28
ERR!     at async Object.start (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:74:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\dev-server.js:123:28)
ERR!     at async buildDevStandalone (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:110:31)
ERR!     at async buildDev (C:\Users\sisyphus\Documents\Projects\frontend-cub\node_modules\@storybook\core-server\dist\cjs\build-dev.js:152:5) {
ERR!   errors: [
ERR!     {
ERR!       keyword: 'additionalProperties',
ERR!       dataPath: '',
ERR!       schemaPath: '#/additionalProperties',
ERR!       params: [Object],
ERR!       message: 'should NOT have additional properties',
ERR!       schema: false,
ERR!       parentSchema: [Object],
ERR!       data: [Object]
ERR!     }
ERR!   ],
ERR!   schema: {
ERR!     definitions: { Rule: [Object], Rules: [Object] },
ERR!     title: 'TerserPluginOptions',
ERR!     type: 'object',
ERR!     additionalProperties: false,
ERR!     properties: {
ERR!       test: [Object],
ERR!       include: [Object],
ERR!       exclude: [Object],
ERR!       terserOptions: [Object],
ERR!       extractComments: [Object],
ERR!       parallel: [Object],
ERR!       minify: [Object]
ERR!     },
ERR!     default: {
ERR!       definitions: [Object],
ERR!       title: 'TerserPluginOptions',
ERR!       type: 'object',
ERR!       additionalProperties: false,
ERR!       properties: [Object]
ERR!     }
ERR!   },
ERR!   headerName: 'Terser Plugin',
ERR!   baseDataPath: 'options',
ERR!   postFormatter: null
ERR! }
</code>
</pre>

**To Reproduce**
Failed to create repro

**System**
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)

**Comment by Skellord** [comment]
I solved this problem with install terser-webpack-plugin
