### ISSUE TITLE
`Unexpected default export without title: undefined` Error when loading simple mdx story

### ISSUE THREAD

**Issue by jeremytenjo** [storybookjs/storybook#15097]
**Describe the bug**
`Unexpected default export without title: undefined` error when loading simple mdx story

**To Reproduce**
1. Create story called `sb.intro.mdx` 
2. Add following content to `sb.intro.mdx`: 
```mdx
import { Meta } from '@storybook/addon-docs/blocks'

<Meta title='Introduction' />

## Useweb

A set of tools to improve dev experience and app production.

```
3. Start storybook
4. Result 
![image](https://user-images.githubusercontent.com/25231946/120120843-13578c00-c16e-11eb-94fe-f75f0107aa73.png)

**System**

```
❯ npx sb@next info

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1.1
```

**Additional context**

```json
    "storybook": "^6.3.0-beta.4",
    "storybook-addon-figma": "^0.1.0",
    "storybook-addon-next-router": "^2.0.4",
    "storybook-addon-responsive-views": "^2.3.0",
    "@storybook/addon-actions": "^6.3.0-beta.4",
    "@storybook/addon-controls": "^6.3.0-beta.4",
    "@storybook/addon-docs": "^6.3.0-beta.4",
    "@storybook/react": "^6.3.0-beta.4",
```

`main.js`

```js
const webpack = require('./webpack')

module.exports = {
  stories: ['../src/**/sb.stories.@(js|mdx)', '../src/sb.intro.mdx'],
  features: {
    buildStoriesJson: true,
  },
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-controls',
    './plugins/GithubCodeViewer',
  ],
  webpackFinal: async (defaultConfig) => {
    return webpack(defaultConfig)
  },
}
```

**Comment by bdefore** [comment]
Similar error for me on 6.3.0-rc.5:

```
Error: Unexpected default export without title: undefined
    at http://localhost:6006/main.iframe.bundle.js:60973:15
    at Array.forEach (<anonymous>)
    at http://localhost:6006/main.iframe.bundle.js:60966:11
    at ConfigApi.configure (http://localhost:6006/main.iframe.bundle.js:44769:7)
    at Object.configure (http://localhost:6006/main.iframe.bundle.js:61097:17)
    at configure (http://localhost:6006/main.iframe.bundle.js:62202:24)
    at Object../.storybook/generated-stories-entry.js (http://localhost:6006/main.iframe.bundle.js:87708:36)
    at __webpack_require__ (http://localhost:6006/main.iframe.bundle.js:1071118:33)
    at http://localhost:6006/main.iframe.bundle.js:1072396:11
    at http://localhost:6006/main.iframe.bundle.js:1072399:12
```

**Comment by shilman** [comment]
See the note about filenames here:

https://storybook.js.org/docs/react/writing-docs/mdx#mdx-file-names

Closing!
