### ISSUE TITLE
Storybook not compile source monaco-editor

### ISSUE THREAD

**Issue by IvanovRoman** [storybookjs/storybook#15208]
I am get this error
```
(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\contrib\suggest\media\suggestStatusBar.css Unknown word

> 1 | import api from "!../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../../css-loader/dist/cjs.js!./suggestStatusBar.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\contrib\zoneWidget\zoneWidget.css Unknown word

> 1 | import api from "!../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../css-loader/dist/cjs.js!./zoneWidget.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\standalone\browser\accessibilityHelp\accessibilityHelp.css Unknown word

> 1 | import api from "!../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../../css-loader/dist/cjs.js!./accessibilityHelp.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\standalone\browser\iPadShowKeyboard\iPadShowKeyboard.css Unknown word

> 1 | import api from "!../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../../css-loader/dist/cjs.js!./iPadShowKeyboard.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\standalone\browser\inspectTokens\inspectTokens.css Unknown word

> 1 | import api from "!../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../../css-loader/dist/cjs.js!./inspectTokens.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\standalone\browser\quickInput\standaloneQuickInput.css Unknown word

> 1 | import api from "!../../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../../css-loader/dist/cjs.js!./standaloneQuickInput.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\editor\standalone\browser\standalone-tokens.css Unknown word

> 1 | import api from "!../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../css-loader/dist/cjs.js!./standalone-tokens.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) E:\work\webui\node_modules\monaco-editor\esm\vs\platform\contextview\browser\contextMenuHandler.css Unknown word

> 1 | import api from "!../../../../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    | ^
  2 |             import content from "!!../../../../../../css-loader/dist/cjs.js!./contextMenuHandler.css";
  3 |

    at E:\work\webui\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\work\webui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\work\webui\node_modules\postcss-loader\dist\index.js:102:7)

```
This is code `contextMenuHandler.css`
```
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

.context-view .monaco-menu {
	min-width: 130px;
}

```
This is my main.js
```
const path = require('path');
const webpack = require('webpack');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-postcss",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-knobs",
  ],
  reactOptions: {
    fastRefresh: true
  },
  typescript: {
    check: false,
    checkOptions: {},
  },
  webpackFinal: async (config) => {
    config.entry = [
      './src/entry/styles-examples.scss',
      './src/stories/config.ts',
      ...config.entry,
    ],
    config.module.rules.push({
      test: /\.tsx?$/,
      use: [
        {
          loader: 'ts-loader',
          options: {
            configFile: path.resolve(__dirname, '../tsconfig.build.json'),
            transpileOnly: true
          }
        }
      ]
    },
    {
      test: /\.ttf$/,
      use: [
        {
          loader: 'file-loader',
          options: {
            esModule: false
          }
        }
      ]
    },
    {
      test: /\.scss$/,
      include: path.resolve(__dirname, '../src/entry/styles-examples.scss'),
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            import: false,
            url: false
          }
        },
        {
          loader: "postcss-loader",
          options: {
            postcssOptions: {
              plugins: [],
            },
          }
        },
        'sass-loader']
    },
    {
      test: /\.scss$/,
      exclude: path.resolve(__dirname, '../src/entry/styles-examples.scss'),
      use: [
        {
          loader: 'dts-css-modules-loader',
          options: {
            namedExport: true,
            banner: "// This file is generated automatically"
          }
        },
        {
          loader: 'css-loader',
          options: {
            modules: {
              compileType: "module",
              mode: "local",
              localIdentName: '[local]',
              exportLocalsConvention: "camelCaseOnly",
              exportOnlyLocals: true,
              namedExport: true
            },
            import: false,
            url: false
          }
        },
        'sass-loader'
      ]
    },
    {
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    },
    {
      test: /\.svg$/,
      use: 'null-loader'
    });

    config.resolve.modules = [
      path.resolve(__dirname, '..', 'src'),
      path.resolve(__dirname, '..', 'json'),
      path.resolve(__dirname, '..', 'node_modules')
    ];

    config.resolve.alias = {
      ...config.resolve.alias,
      bluebird: path.resolve('node_modules/bluebird/js/browser/bluebird'),
      html2canvas: path.resolve('node_modules/html2canvas/dist/html2canvas.esm'),
      json: path.resolve('json/')
    }

    config.plugins.push(
      new webpack.ProvidePlugin({
        Promise: 'bluebird'
      }),
      new MonacoWebpackPlugin({
        languages: ['ini', 'python', 'r', 'sql', 'xml']
      })
    );

    return config;
  }
}

```

**Comment by bboydflo** [comment]
@IvanovRoman have you fixed this issue? I get the exact same issue.

**Comment by IvanovRoman** [comment]
> @IvanovRoman have you fixed this issue? I get the exact same issue.

Yes. I changed configuration.
```
const path = require('path');
const webpack = require('webpack');

// uses to generate unique identifier for each build for caching purposes
const HASH = Math.round(Date.now() / 1000).toString();
// check exist loader with that rule in storybook (webpack.config) if created folder 'static/media'
const loaderRule = String(/\.(svg|ico|jpg|jpeg|png|apng|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/);

module.exports = {
  framework: "@storybook/react",
  core: {
    builder: "webpack5",
  },
  stories: [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-controls",
  ],
  reactOptions: {
    fastRefresh: true
  },
  typescript: {
    check: false,
    checkOptions: {},
  },
  webpackFinal: async (config) => {
    config.entry = [
      './src/stories/config.ts',
      ...config.entry,
    ],
    config.module.rules = config.module.rules.filter(rule => String(rule.test) !== loaderRule);
    config.module.rules.push(
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              configFile: path.resolve(__dirname, '../tsconfig.build.json'),
              transpileOnly: true
            }
          }
        ]
      },
      {
        test: /\.ttf$/,
        type: 'asset',
      },
      {
        test: /\.scss$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              import: false,
              url: false
            }
          },
          'postcss-loader',
          'sass-loader']
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'dts-css-modules-loader',
            options: {
              namedExport: true,
              banner: "// This file is generated automatically"
            }
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                mode: "local",
                localIdentName: '[local]',
                exportLocalsConvention: "camelCaseOnly",
                exportOnlyLocals: true,
                namedExport: true
              },
              import: false,
              url: false
            }
          },
          'sass-loader'
        ]
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.svg$/,
        use: 'null-loader'
      });

    config.resolve.modules = [
      ...config.resolve.modules,
      path.resolve(__dirname, '..', 'src'),
      path.resolve(__dirname, './json')
    ];

    config.resolve.alias = {
      ...config.resolve.alias,
      bluebird: path.resolve('node_modules/bluebird/js/browser/bluebird'),
      html2canvas: path.resolve('node_modules/html2canvas/dist/html2canvas.esm'),
      json: path.resolve('json/')
    }

    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.HASH': HASH
      }),
      new webpack.ProvidePlugin({
        Promise: 'bluebird'
      })
    );

    return config;
  }
```

**Comment by bboydflo** [comment]
@IvanovRoman thanks. In my case I was applying some rules to storybook in `webpackFinal` that were already applied by the default webpack config. After removing those it works again.
