### ISSUE TITLE
Unable to install storybook using npx sb init

### ISSUE THREAD

**Issue by johnwp** [storybookjs/storybook#15269]
**Describe the bug**
I'm not able to install storybook using `$ npx sb init`

**To Reproduce**
1. `$ npx create-react-app my-app` — Success
2. `$ cd my-app` — Success
3. `$ npx sb init` — Fail

Results of `$ npx sb init`:
```
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2021-06-16T18_30_26_494Z-debug.log
Install for [ 'sb@latest' ] failed with code 1
```

**System**
node version: v14.6.0
npx version: 10.2.2

Results of `$ npx sb@next info`:
```
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2021-06-16T18_35_25_810Z-debug.log
Install for [ 'sb@next' ] failed with code 1
```

**Additional Context**
Contents of `/Users/john/.npm/_logs/2021-06-16T18_30_26_494Z-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/Users/john/.config/yarn/global/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'sb@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/john/.npm/_npx/87575',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.6.0
4 verbose npm-session 1fd809a896d05ea6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 http://registry.npmjs.org/sb 190ms (from cache)
8 silly pacote tag manifest for sb@latest fetched in 221ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /Users/john/.config/yarn/global/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (fs.js:177:5)
10 verbose cwd /Users/john/projects/king-react-components
11 verbose Darwin 20.5.0
12 verbose argv "/usr/local/bin/node" "/Users/john/.config/yarn/global/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "sb@latest" "--global" "--prefix" "/Users/john/.npm/_npx/87575" "--loglevel" "error" "--json"
13 verbose node v14.6.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]
```

**Comment by shilman** [comment]
Did you try this? https://stackoverflow.com/questions/63429304/npm-err-cb-apply-is-not-a-function

**Comment by johnwp** [comment]
Apparently, there was an issue with my installation. Thanks.

**Comment by kahlan88** [comment]
I have the same problem. Not resolved by following https://stackoverflow.com/questions/63429304/npm-err-cb-apply-is-not-a-function (I only have `npx` and `rimraf` as my global npm packages and deleted `npm cache`. No luck.
I still get:

```
npm ERR! cb.apply is not a function
Install for [ 'storybook@latest' ] failed with code 1
```

Are there any manual instructions to install `storybook`?
