### ISSUE TITLE
Storybook and material cant find parent style sheet on snap shot test

### ISSUE THREAD

**Issue by dhall2211** [storybookjs/storybook#15289]
**Describe the bug**
I have a storybook project with Webpack 5.7.3 and material ui. When I run my snap shot tests in jest all test passed but I receive two different console warning messages multiple times .

1. parentStylesSheet undefined (6x)

 ```
● Console

    console.warn
      Warning: [JSS] Cannot set property 'parentStyleSheet' of undefined

      at Object.warning (node_modules/tiny-warning/dist/tiny-warning.cjs.js:13:15)
      at insertRule (node_modules/jss/dist/jss.cjs.js:1764:72)
      at DomRenderer.insertRule (node_modules/jss/dist/jss.cjs.js:1921:22)
      at DomRenderer.insertRules (node_modules/jss/dist/jss.cjs.js:1881:12)
      at DomRenderer.deploy (node_modules/jss/dist/jss.cjs.js:1868:12)
      at StyleSheet.deploy (node_modules/jss/dist/jss.cjs.js:1200:38)
      at StyleSheet.attach (node_modules/jss/dist/jss.cjs.js:1079:30)
      at attach (node_modules/@material-ui/styles/makeStyles/makeStyles.js:139:18)
```

2 JSS Rule is not linked (3x)

 ```
console.warn
      Warning: [JSS] Rule is not linked. Missing sheet option "link: true".

      at Object.warning (node_modules/tiny-warning/dist/tiny-warning.cjs.js:13:15)
      at StyleRule.prop (node_modules/jss/dist/jss.cjs.js:239:74)
      at Array.onChangeValue (node_modules/jss-plugin-camel-case/dist/jss-plugin-camel-case.cjs.js:61:10)
      at PluginsRegistry.onChangeValue (node_modules/jss/dist/jss.cjs.js:1317:54)
      at StyleRule.prop (node_modules/jss/dist/jss.cjs.js:220:43)
      at Array.onUpdate (node_modules/jss-plugin-rule-value-function/dist/jss-plugin-rule-value-function.cjs.js:69:21)
      at PluginsRegistry.onUpdate (node_modules/jss/dist/jss.cjs.js:1305:32)
      at RuleList.updateOne (node_modules/jss/dist/jss.cjs.js:979:13)

```
What i can see is happening is that the makeStyles tries to attach and deploy the stylesheet but since it doesnt find one, the insert rule in the jss sees it as empty styling so it throws an error. 

In the webpack config it seems like this has not been accounted for... however i could be wrong? below is my webpack config along with a copy of the config object. any insight to this issue is greatly appreciated! 

```
const { merge } = require('webpack-merge');

const maxAssetSize = 1024 * 1024;

module.exports = {
  stories: ['../stories/**/*.stories.@(ts|tsx|mdx)'],
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-toolbars',
    '@storybook/addon-viewport',
    '@etchteam/storybook-addon-status/register',
    '@storybook/addon-contexts/register'
  ],
  typescript: {
    reactDocgenTypescriptOptions: {
      skipChildrenPropWithoutDoc: false,
      shouldRemoveUndefinedFromOptional: true,
    },
  },
  webpackFinal: async (config, { configType }) => {

    return merge(config, {
      optimization: {
        splitChunks: {
          chunks: 'all',
          minSize: 30 * 1024,
          maxSize: maxAssetSize,
        },
      },
      performance: {
        maxAssetSize: maxAssetSize,
      },
    });
  },
};


```
config obj

```
{{
  name: 'preview',
  mode: 'development',
  bail: false,
  devtool: 'cheap-module-source-map',
  entry: [
    'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\core-server\\dist\\cjs\\globals\\polyfills.js',
    'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\core-server\\dist\\cjs\\globals\\globals.js',
    'C:\\Projekte\\VD.React.Library\\.storybook\\storybook-init-framework-entry.js',
    'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\addon-docs\\dist\\esm\\frameworks\\common\\config.js-generated-other-entry.js',
    'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\addon-docs\\dist\\esm\\frameworks\\react\\config.js-generated-other-entry.js',
    'C:\\Projekte\\VD.React.Library\\.storybook\\preview.js-generated-config-entry.js',
    'C:\\Projekte\\VD.React.Library\\.storybook\\generated-stories-entry.js',
    'C:\\Projekte\\VD.React.Library\\node_modules\\webpack-hot-middleware\\client.js?reload=true&quiet=false&noInfo=undefined'
  ],
  output: {
    path: 'C:\\Projekte\\VD.React.Library\\node_modules\\.cache\\storybook\\public',
    filename: '[name].iframe.bundle.js',
    publicPath: ''
  },
  watchOptions: { aggregateTimeout: 10, ignored: /node_modules/ },
  plugins: [
    FilterWarningsPlugin { exclude: [Array] },
    VirtualModulesPlugin { _staticModules: [Object] },
    HtmlWebpackPlugin {
      options: [Object],
      childCompilerHash: undefined,
      assetJson: undefined,
      hash: undefined,
      version: 4
    },
    DefinePlugin { definitions: [Object] },
    WatchMissingNodeModulesPlugin {
      nodeModulesPath: 'C:\\Projekte\\VD.React.Library\\node_modules'
    },
    HotModuleReplacementPlugin {
      options: {},
      multiStep: undefined,
      fullBuildTimeout: 200,
      requestTimeout: 10000
    },
    CaseSensitivePathsPlugin {
      options: {},
      logger: [Object [console]],
      pathCache: Map(0) {},
      fsOperations: 0,
      primed: false
    },
    ProgressPlugin {
      profile: false,
      handler: undefined,
      modulesCount: 500,
      showEntries: false,
      showModules: true,
      showActiveModules: true
    },
    DefinePlugin { definitions: {} },
    DocgenPlugin {
      name: 'React Docgen Typescript Plugin',
      options: [Object]
    }
  ],
  module: {
    rules: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  resolve: {
    extensions: [
      '.mjs', '.js',
      '.jsx', '.ts',
      '.tsx', '.json',
      '.cjs'
    ],
    modules: [ 'node_modules' ],
    mainFields: [ 'browser', 'module', 'main' ],
    alias: {
      '@emotion/core': 'C:\\Projekte\\VD.React.Library\\node_modules\\@emotion\\core',
      '@emotion/styled': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\theming\\node_modules\\@emotion\\styled',
      'emotion-theming': 'C:\\Projekte\\VD.React.Library\\node_modules\\emotion-theming',
      '@storybook/addons': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\addons',
      '@storybook/api': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\api',
      '@storybook/channels': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\channels',
      '@storybook/channel-postmessage': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\channel-postmessage',
      '@storybook/components': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\components',
      '@storybook/core-events': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\core-events',
      '@storybook/router': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\router',
      '@storybook/theming': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\theming',
      '@storybook/semver': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\semver',
      '@storybook/client-api': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\client-api',
      '@storybook/client-logger': 'C:\\Projekte\\VD.React.Library\\node_modules\\@storybook\\builder-webpack4\\node_modules\\@storybook\\client-logger',
      react: 'C:\\Projekte\\VD.React.Library\\node_modules\\react',
      'react-dom': 'C:\\Projekte\\VD.React.Library\\node_modules\\react-dom'
    },
    plugins: [ [Object] ]
  },
  resolveLoader: { plugins: [ [Object] ] },
  optimization: {
    splitChunks: { chunks: 'all', minSize: 30720, maxSize: 1048576 },
    runtimeChunk: true,
    sideEffects: true,
    usedExports: true,
    minimizer: []
  },
  performance: { hints: false, maxAssetSize: 1048576 }
}

```

**Comment by markhughes** [comment]
This is not storybook specific, this is due to jest

**Comment by ndelangen** [comment]
The future of storyshots is the test-runner:
https://storybook.js.org/docs/react/writing-tests/test-runner#page-top

And use the play function for expectations:
https://storybook.js.org/docs/react/writing-stories/play-function#page-top

We will not be making any improvement / changes to storyshots.
