### ISSUE TITLE
(0 , upath__WEBPACK_IMPORTED_MODULE_10__.normalize) is not a function - @storybook/addon-jest

### ISSUE THREAD

**Issue by silverboyir** [storybookjs/storybook#15340]
**Describe the bug**
after I add the 

```
import results from '../.jest-test-results.json';

addDecorator(
  withTests({
    results,
  })
);
```
to the preview.js file I get "(0 , upath__WEBPACK_IMPORTED_MODULE_10__.normalize) is not a function" in all stories page

```

TypeError: (0 , upath__WEBPACK_IMPORTED_MODULE_10__.normalize) is not a function
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:21470:75
    at Array.find (<anonymous>)
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:21469:45
    at Array.map (<anonymous>)
    at findTestResults (http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:21461:35)
    at emitAddTests (http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:21490:12)
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:21512:7
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:22813:21
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:25119:12
    at http://localhost:6006/vendors-node_modules_material-ui_core_esm_Button_Button_js-node_modules_material-ui_core_esm_-c5a436.iframe.bundle.js:25138:12
```

Storybook 6.3.0 
webpack 5

with Webpack 4 and the older version of Storybook everything works fine

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by ibohatyrchuk** [comment]
@silverboyir I have the same issue.
Solution of @tassoevan in https://github.com/storybookjs/storybook/issues/14856 works for me.

**Comment by henrycity** [comment]
> @silverboyir I have the same issue.
> Solution of @tassoevan in #14856 works for me.

Thanks, this works for me too.
