### ISSUE TITLE
Upgrade from 6.2.9 -> 6.3.2, now Docs are all blank

### ISSUE THREAD

**Issue by Greenie10** [storybookjs/storybook#15462]
**Describe the bug**
On upgrade from 6.2.9 to 6.3.2, viewing any Docs page is blank.  Console error many times over, with the same error, eg:

```
Canvas.js:48 Uncaught TypeError: Cannot read property 'id' of undefined
    at Canvas.js:48
    at Array.map (<anonymous>)
    at getPreviewProps (Canvas.js:47)
    at Canvas (Canvas.js:64)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
```

```
The above error occurred in the <Canvas> component:
    at Canvas (http://localhost:6006/vendors~main.iframe.bundle.js:66137:77)
    at http://localhost:6006/vendors~main.iframe.bundle.js:4232:30
    at wrapper (http://localhost:6006/vendors~main.iframe.bundle.js:4227:25)
    at http://localhost:6006/vendors~main.iframe.bundle.js:4232:30
    at MDXContent (http://localhost:6006/main.iframe.bundle.js:47507:25)
    at AddContext (http://localhost:6006/vendors~main.iframe.bundle.js:63508:24)
    at page
    at push../node_modules/styled-components/dist/styled-components.browser.cjs.js.exports.ThemeProvider (http://localhost:6006/vendors~main.iframe.bundle.js:344171:23884)
    at div
    at Styled(div)
    at div
    at Styled(div)
    at MDXProvider (http://localhost:6006/vendors~main.iframe.bundle.js:4217:46)
    at ThemeProvider
    at SourceContainer (http://localhost:6006/vendors~main.iframe.bundle.js:67059:23)
    at DocsContainer (http://localhost:6006/vendors~main.iframe.bundle.js:66364:22)
    at container (http://localhost:6006/main.iframe.bundle.js:102:27)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**System**
Environment Info:
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/GitHub/titan/node_modules/.bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: 6.3.2 => 6.3.2
    @storybook/addon-essentials: 6.3.2 => 6.3.2
    @storybook/addons: 6.3.2 => 6.3.2
    @storybook/react: 6.3.2 => 6.3.2

**Additional context**

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by Greenie10** [comment]
Tried again today, with Storybook 6.3.4, and issue is no longer present. I guess something fixed it :D
