### ISSUE TITLE
Not able to install storybook into an Angular 9 application

### ISSUE THREAD

**Issue by thiagosbrito** [storybookjs/storybook#15467]
Hello,

I'm facing an issue while trying to add storybook to an existing project.

The project runs:
```
"@angular-devkit/build-angular": "~0.901.9",
"@angular-devkit/build-ng-packagr": "~0.901.9",
"@angular/animations": "~9.1.11",
"@angular/cli": "~9.1.9",
"@angular/common": "~9.1.11",
"@angular/compiler": "~9.1.11",
"@angular/compiler-cli": "~9.1.11",
"@angular/core": "~9.1.11",
"@angular/forms": "~9.1.11",
"@angular/language-service": "~9.1.11",
"@angular/platform-browser": "~9.1.11",
"@angular/platform-browser-dynamic": "~9.1.11",
"@angular/router": "^9.1.11",
"@ngrx/effects": "~8.6.0",
"@ngrx/store": "~8.6.0",
"@types/express": "^4.17.1",
"@types/jasmine": "~2.8.8",
"@types/jasminewd2": "~2.0.3",
"@types/node": "^12.11.1",
```
Trying to install using: npx sb init but I'm getting the following error:

```
$ npx -p @storybook/cli sb init --type angular
####......] - postinstall: info lifecycle @storybook/cli@6.3.2~postinstall: @storybook/cli@6.3.2pes@7.14.5
sb init - the simplest way to add a Storybook to your project. 

• Installing Storybook for user specified project type. ✓
• Adding Storybook support to your "Angular" app
    TypeError: Invalid Version: undefined
   at new SemVer (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\node_modules\@storybook\semver\classes\semver.js:72:13)
   at compare (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\node_modules\@storybook\semver\functions\compare.js:6:10)
   at Object.gte (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\node_modules\@storybook\semver\functions\gte.js:6:10)
   at generator (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\dist\cjs\generators\ANGULAR\index.js:53:38)
   at runGenerator (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\dist\cjs\initiate.js:169:37)
   at installStorybook (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\dist\cjs\initiate.js:223:10)
   at _default (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\dist\cjs\initiate.js:296:10)
   at Command.<anonymous> (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\dist\cjs\generate.js:38:696)
   at Command.listener [as _actionHandler] (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\node_modules\commander\index.js:426:31)
   at Command._parseCommand (C:\Users\UX159567\AppData\Roaming\npm-cache\_npx\47868\node_modules\@storybook\cli\node_modules\commander\index.js:1002:14) 
   ```

**Comment by shilman** [comment]
closing as dupe to #15260
