### ISSUE TITLE
Webpack 5:  Storybook crashes after initial build, when any update is applied

### ISSUE THREAD

**Issue by TerrySlack** [storybookjs/storybook#15475]
**Describe the bug**
Using Webpack 5 witt Storybook (also with webpack 5 enabled).  Run the initial build, Storybook works fine.  Update any file and it crashes.

**To Reproduce**
Download the latest SB (6.3.2) create a story.  run yarn; yarn storybook.
Story appears without issues.  Update any line of code, whether in the stoy or in a component and Storybook crashes.

**System**
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
  npmPackages:
    @storybook/addon-actions: ^6.3.2 => 6.3.2
    @storybook/addon-essentials: ^6.3.2 => 6.3.2
    @storybook/addon-links: ^6.3.2 => 6.3.2
    @storybook/addon-viewport: ^6.3.2 => 6.3.2
    @storybook/builder-webpack5: ^6.3.2 => 6.3.2
    @storybook/manager-webpack5: ^6.3.2 => 6.3.2
    @storybook/react: ^6.3.2 => 6.3.2

**Additional context**
99% done plugins webpack-hot-middlewarewebpack built preview 66350c0623c3431bf5e0 in 1193ms
webpack building...
3% setup watch runC:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\json\JsonGenerator.js:119
                let data = module.buildInfo.jsonData;
                                            ^

TypeError: Cannot read property 'jsonData' of undefined
    at JsonGenerator.getSize (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\json\JsonGenerator.js:119:31)
    at NormalModule.size (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\NormalModule.js:1224:43)
    at NormalModule.cleanupForCache (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\NormalModule.js:364:9)
    at NormalModuleFactory.cleanupForCache (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\NormalModuleFactory.js:670:11)
    at Compiler._cleanupLastNormalModuleFactory (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Compiler.js:383:34)
    at Compiler.createNormalModuleFactory (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Compiler.js:1049:8)
    at Compiler.newCompilationParams (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Compiler.js:1071:30)
    at Compiler.compile (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Compiler.js:1082:23)
    at C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Watching.js:188:19
    at _next0 (eval at create (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at eval (eval at create (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:40:1)
    at watchRunHook (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\@storybook\builder-webpack5\node_modules\webpack-virtual-modules\lib\index.js:236:13)
    at Hook.eval [as callAsync] (eval at create (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at run (C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Watching.js:142:33)
    at C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\Watching.js:129:6
    at C:\AAAA\RocketPlan\StoryBook-Bug-Fix\webapp.rocketplantech.com\node_modules\webpack\lib\HookWebpackError.js:68:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by peiris** [comment]
For anyone looking for a temporary solution,

`.storybook/main.js`

```
module.exports = {
  ...
  webpackFinal: async (config, { configType }) => {
    ...

    config.cache = false
    return config
  },
}
```

https://github.com/webpack/webpack/issues/13691

**Comment by shilman** [comment]
closing as dupe to #15463
