### ISSUE TITLE
Stopped working after updating to Angular 12

### ISSUE THREAD

**Issue by MurhafSousli** [storybookjs/storybook#15599]
**Describe the bug**

After updating to Angular 12, the storybook stopped working, throwing the following: 

```
ERR! Error: Cannot find module '@storybook/builder-webpack5'
ERR! Require stack:
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/server.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/dist/ts3.9/server/index.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at getPreviewBuilder (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:31:42)
ERR!     at buildDevStandalone (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-dev.js:99:71)
ERR!     at async Object.buildDev (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5)
ERR!  Error: Cannot find module '@storybook/builder-webpack5'
ERR! Require stack:
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/server.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/dist/ts3.9/server/index.js
ERR! - /Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at getPreviewBuilder (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js:31:42)
ERR!     at buildDevStandalone (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-dev.js:99:71)
ERR!     at async Object.buildDev (/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-dev.js:154:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/utils/get-preview-builder.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/build-static.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/core/server.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/dist/ts3.9/server/index.js',
ERR!     '/Users/murhaf.sousliboehringer-ingelheim.com/Desktop/Work/plf-fe-components/node_modules/@storybook/angular/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**To Reproduce**

I only did `ng update @angular/cli @angular/core`

**System**

Environment Info:
```
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.67
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4 
    @storybook/addon-essentials: ^6.3.4 => 6.3.4 
    @storybook/addon-links: ^6.3.4 => 6.3.4 
    @storybook/angular: ^6.3.4 => 6.3.4 
    @storybook/builder-webpack5: ^6.3.4 => 6.3.4 
```

**Additional context**

I saw an existing issue which was closed, but it is unclear what is the fix? I saw many different fixes that worked for others, but couldn't get one. shouldn't you point to the fix before closing the ticket?

**Comment by MurhafSousli** [comment]
Found the solution in the changelog https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-12-upgrade
