### ISSUE TITLE
Angular 12 fails with webpack exception

### ISSUE THREAD

**Issue by tomsontom** [storybookjs/storybook#15603]
**Describe the bug**
I followed a tutorial (https://dev.to/activenode/angular-10-storybook-npm-package-ng-design-system-step-by-step-2dn2) to setup a angular libary project with storybook but it fails with the following exception

```
ERR! => Could not get angular cli webpack config
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
ERR!     at validateString (internal/validators.js:124:11)
ERR!     at Object.resolve (path.js:980:7)
ERR!     at /Users/tomschindl/.../.../.../node_modules/@storybook/angular/dist/ts3.9/server/angular-devkit-build-webpack.js:140:47
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4 
    @storybook/addon-essentials: ^6.3.4 => 6.3.4 
    @storybook/addon-links: ^6.3.4 => 6.3.4 
    @storybook/angular: ^6.3.4 => 6.3.4 
    @storybook/builder-webpack5: ^6.3.4 => 6.3.4 
    @storybook/manager-webpack5: ^6.3.4 => 6.3.4 
```

**Comment by tomsontom** [comment]
So i instrumented the code a bit and i think the problem is that the library project in `angular.json` looks like this
```json
...
    "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "project": "projects/..../ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/.../tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "projects/.../tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },

```

So the `options` does not contain `tsConfig`

**Comment by Marklb** [comment]
I think this is the same as #15246.

**Comment by tomsontom** [comment]
That's right
