### ISSUE TITLE
Cannot read property 'story' of undefined after saving the story (hmr)

### ISSUE THREAD

**Issue by may17** [storybookjs/storybook#15660]
**Describe the bug**
When i started npm run storybook, everytime i changed some story the reload fails with the message in the browser:

```
TypeError: Cannot read property 'story' of undefined
    at normalizeV2 (http://localhost:6006/vendors~main.iframe.bundle.js:12023:23)
    at http://localhost:6006/vendors~main.iframe.bundle.js:11853:112
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.iframe.bundle.js:11851:20
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.iframe.bundle.js:11781:11
    at ConfigApi.configure (http://localhost:6006/vendors~main.iframe.bundle.js:8890:7)
    at Object.configure (http://localhost:6006/vendors~main.iframe.bundle.js:11912:17)
    at configure (http://localhost:6006/vendors~main.iframe.bundle.js:13129:24)
    at Object.<anonymous> (http://localhost:6006/main.iframe.bundle.js:18:36)
```

The webpack preview build shows no problems and everything seems been fine. But i recognized that the chrome devTools conole prints out: Unexpected story export "NoComparisonData": expected function, received "undefined".

**To Reproduce**

main.js
```js
const path = require('path')
const rootPath = path.resolve(__dirname, '../')

module.exports = {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)',
    '../components/**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: [
    '@storybook/addon-links',
    // The docs plugin has a problem with vuetify. We need to disable it as long as there is no bugix.
    // @see https://github.com/storybookjs/storybook/issues/7593#issuecomment-735987350
    {
      name: "@storybook/addon-essentials",
      options: {
        docs: false
      }
    },
    '@storybook/addon-controls',
  ],
  webpackFinal: (config) => {
    const eslintLoader = {
      enforce: 'pre',
      test: /\.(js|vue)$/,
      loader: 'eslint-loader',
      exclude: /(node_modules)/,
      options: {
        fix: true,
      }
    }

    config.module.rules.push(eslintLoader)
    config.module.rules.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'sass-loader'],
      include: path.resolve(__dirname, '../'),
    });

    config.resolve.alias = {
      ...config.resolve.alias,
      '~': rootPath,
      '~~': rootPath,
      '@': rootPath
    }
    return config
  }
}
```

preview.js
```js
import Vue from 'vue'
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
import VueI18n from 'vue-i18n'
import langData from '../lang'
import '@mdi/font/css/materialdesignicons.css'
import '@fortawesome/fontawesome-free/css/all.css'
import './style.scss'
import vuetifyBaseConfig from '../vuetify.config'
import { initializeWorker, mswDecorator } from 'msw-storybook-addon';
import { plainVueAutoLoader } from '@/plugins/componentAutoloader'

initializeWorker();

Vue.use(plainVueAutoLoader)
Vue.use(VueI18n)
Vue.use(Vuetify)

Vue.component('nuxt-link', {
  props:   ['to'],
  methods: {
    log() {
      action('link target')(this.to)
    },
  },
  template: '<a href="#" @click.prevent="log()"><slot>NuxtLink</slot></a>',
})

const i18n = new VueI18n({
  locale: 'de',
  locales: ['de', 'en'],
  messages: langData()
})

const vuetifyConfig = new Vuetify({
  theme: vuetifyBaseConfig.theme
})

export const decorators = [
  mswDecorator,
  (story, context) => {
    const wrapped = story(context)

    return Vue.extend({
      components: { wrapped },
      vuetify: vuetifyConfig,
      i18n,
      template: '<v-app><v-main><wrapped/></v-main></v-app>'
    })
  },
];

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  backgrounds: {
    default: 'gray',
    values: [
      {
        name: 'white',
        value: '#ffffff',
      },
      {
        name: 'gray',
        value: '#EFF1F3',
      },
    ],
  },
}
```

**System**
```
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: 91.0.864.71
    Firefox: 86.0.1
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.3.4 => 6.3.4 
    @storybook/addon-controls: ^6.3.4 => 6.3.4 
    @storybook/addon-essentials: ^6.3.4 => 6.3.4 
    @storybook/addon-links: ^6.3.4 => 6.3.4 
    @storybook/vue: ^6.3.4 => 6.3.4 
```
**Additional context**
storybook msw plugin is used but imho there exists no relation to the problem.

I use vuetify and i know that there exists an open issue here but i am not sure if they have any relation.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Here's how to [create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by may17** [comment]
@shilman I've tried it out yesterday while creating this issue, but it ended up in an error:

An error occurred while executing: `yarn install`
Command output was:
Usage Error: The nearest package directory (/PATH/TO/MY/VUE/PROJECT/my-repro) doesn't seem to be part of the project declared in /PATH/TO.

Any recommendations to fix it?

**Comment by shilman** [comment]
@may17 does it work if you run it outside of your project directory?

**Comment by may17** [comment]
Nope, sorry doesn't work for me. Seems that project root detection does not work in my case. Can I set it manually?

**Comment by ksbulgakov** [comment]
@may17 Hi! In my case problem was in other story which data I accidentally changed. So I worked on the new one but It falls down with the same error each time when it should be updated. Try to check if storybook works in your project with default stories which come after init. If it work fine add your stories one by one to find out which one breaks storybook.
So I fix data that uses another story and problem has gone.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
