### ISSUE TITLE
Module build failed (from ./node_modules/babel-loader/lib/index.js): Error: .presets must be an array, or undefined

### ISSUE THREAD

**Issue by sha256rma** [storybookjs/storybook#15685]
**Describe the bug**

I get the following error when running `yarn storybook`:

```
ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
```

```
ERROR in ./.storybook/config.js-generated-config-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
```

The full error is pasted below:

`$ yarn storybook`

```
yarn run v1.22.10
$ start-storybook -p 9001 -c .storybook
info @storybook/vue v6.3.6
info 
info => Loading presets
(node:41862) DeprecationWarning: Configuration files such as "config", "presets" and "addons" are deprecated and will be removed in Storybook 7.0.
Read more about it in the migration guide: https://github.com/storybookjs/storybook/blob/master/MIGRATION.md#to-mainjs-configuration
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading 1 config file in "/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/.storybook"
info => Using implicit CSS loaders
info => Using default Webpack4 setup
(node:41862) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
10% building 3/4 modules 1 active /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
info => Ignoring cached manager due to change in manager config
ℹ ｢wdm｣: wait until bundle finished: 
webpack built preview 2d5bf9284f2ce1afdf74 in 3980ms
✖ ｢wdm｣: Hash: 2d5bf9284f2ce1afdf74
Version: webpack 4.46.0
Time: 3980ms
Built at: 07/26/2021 4:33:15 PM
                            Asset       Size        Chunks                          Chunk Names
                      iframe.html   4.45 KiB                [emitted]               
            main.iframe.bundle.js   6.31 KiB          main  [emitted]               main
        main.iframe.bundle.js.map  221 bytes          main  [emitted] [dev]         main
    runtime~main.iframe.bundle.js   33.5 KiB  runtime~main  [emitted]               runtime~main
runtime~main.iframe.bundle.js.map   34.7 KiB  runtime~main  [emitted] [dev]         runtime~main
    vendors~main.iframe.bundle.js    767 KiB  vendors~main  [emitted]        [big]  vendors~main
vendors~main.iframe.bundle.js.map    707 KiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generated-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 76 bytes {main} [built]
[./.storybook/config.js-generated-config-entry.js] 1.61 KiB {main} [built] [failed] [1 error]
[./.storybook/storybook-init-framework-entry.js] 1.61 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js] 97 bytes {vendors~main} [built]
[./node_modules/@storybook/core-client/node_modules/core-js/features/symbol/index.js] 489 bytes {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/global/window.js] 232 bytes {vendors~main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {vendors~main} [built]
[./node_modules/regenerator-runtime/runtime.js] 24.3 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.17 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 7.68 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/node_modules/strip-ansi/index.js] (webpack)-hot-middleware/node_modules/strip-ansi/index.js 161 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.35 KiB {vendors~main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
    + 305 hidden modules

ERROR in ./.storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:164:11)
    at assertPluginList (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:233:15)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:118:5
    at Array.forEach (<anonymous>)
    at validateNested (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:94:21)
    at validate (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:85:10)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:204:34
    at cachedFunction (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/caching.js:60:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:251:28)
    at sync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:89:14)
    at buildRootChain (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:94:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:149:25
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generated-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[2]

ERROR in ./.storybook/config.js-generated-config-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:164:11)
    at assertPluginList (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:233:15)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:118:5
    at Array.forEach (<anonymous>)
    at validateNested (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:94:21)
    at validate (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:85:10)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:204:34
    at cachedFunction (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/caching.js:60:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:251:28)
    at sync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:89:14)
    at buildRootChain (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:94:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:149:25
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/config.js-generated-config-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[3]
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.23 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:164:11)
    at assertPluginList (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:233:15)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:118:5
    at Array.forEach (<anonymous>)
    at validateNested (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:94:21)
    at validate (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:85:10)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:204:34
    at cachedFunction (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/caching.js:60:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:251:28)
    at sync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:89:14)
    at buildRootChain (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:94:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:149:25
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/babel-loader/lib/index.js:59:103
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .presets must be an array, or undefined
    at assertArray (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:164:11)
    at assertPluginList (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/option-assertions.js:233:15)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:118:5
    at Array.forEach (<anonymous>)
    at validateNested (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:94:21)
    at validate (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/validation/options.js:85:10)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:204:34
    at cachedFunction (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/caching.js:60:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:251:28)
    at sync (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/gensync/index.js:89:14)
    at buildRootChain (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/config-chain.js:94:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/@babel/core/lib/config/partial.js:149:25
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/<USERNAME>/<PROJECT_DIR>/<PROJECT>/node_modules/babel-loader/lib/index.js:59:103
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**To Reproduce**

I ran:

```
yarn add --dev @storybook/vue
yarn add --dev babel-loader vue-loader vue-template-compiler
yarn add --dev @babel/core babel-preset-vue
```

which gave me the following versions:

```
"vue": "2.6.14",
"babel-loader": "^8.2.2",
"babel-preset-vue": "^2.0.2",
"vue-loader": "^15.9.6",
"vue-template-compiler": "^2.6.14",
"@storybook/vue": "^6.3.6",
"@babel/core": "^7.14.8",
```

**System**

Environment Info:

```
  System:
    OS: macOS 11.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/<PROJECT_DIR>/<PROJECT>/node_modules/.bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 14.1.2
  npmPackages:
    @storybook/vue: ^6.3.6 => 6.3.6 
```

**Additional context**

I am using `Vue v2.6.14`.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏
