### ISSUE TITLE
Webpack 4 + Storybook 6.3.7 is broken

### ISSUE THREAD

**Issue by deviprsd** [storybookjs/storybook#15883]
**Describe the bug**
When I run storybooks this is the error I get, I haven't been able to downgrade and check

**To Reproduce**
```
create-single-spa --moduleType util-module --framework react
...move src code, make some tsconfig and webpack changes
npx sb init
storybook run
```

```js
info => Using default Webpack4 setup
(node:46909) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
0% compilingERR! TypeError: Cannot read property 'get' of undefined
ERR!     at exports.provide (/Users/deviprsd/Documents/block5/react-core/node_modules/webpack/lib/util/MapHelpers.js:17:20)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/webpack/lib/DefinePlugin.js:290:6
ERR!     at SyncHook.eval [as call] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
ERR!     at SyncHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/Users/deviprsd/Documents/block5/react-core/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Watching._go (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:41:32)
ERR!  TypeError: Cannot read property 'get' of undefined
ERR!     at exports.provide (/Users/deviprsd/Documents/block5/react-core/node_modules/webpack/lib/util/MapHelpers.js:17:20)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/webpack/lib/DefinePlugin.js:290:6
ERR!     at SyncHook.eval [as call] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
ERR!     at SyncHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/Users/deviprsd/Documents/block5/react-core/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Watching._go (/Users/deviprsd/Documents/block5/react-core/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:41:32)
```

**System**
```console
Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 7.21.0 - ~/Documents/block5/react-core/node_modules/.bin/npm
  Browsers:
    Edge: 92.0.902.73
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.7 => 6.3.7 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-essentials: ^6.3.7 => 6.3.7 
    @storybook/addon-knobs: ^6.2.0 => 6.3.0 
    @storybook/addon-links: ^6.3.7 => 6.3.7 
    @storybook/node-logger: ^6.1.21 => 6.3.7 
    @storybook/preset-create-react-app: ^3.1.7 => 3.2.0 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.3.7 => 6.3.7
```

**Comment by dwhieb** [comment]
I had this same issue. Downgrading all my Storybook packages to v6.3.6 did fix the problem.

**Comment by GoldenaArcher** [comment]
Same here, I ran `npx -p @storybook/cli sb init` to download the latest version v6.3.12, which also triggers the same error.
