### ISSUE TITLE
vue3 sfc + tsx parse error

### ISSUE THREAD

**Issue by StarHosea** [storybookjs/storybook#16036]
**Describe the bug**
Cannot parse vuesfc + tsx , by webpack5 builder。 But vite builder work fine

**To Reproduce**
my componet use in stories.js
```vue
// test.vue
<script lang="tsx">
import {defineComponent} from 'vue'
export default defineComponent({
  setup(){
    return ()=>{
      return <div>Test Tsx</div>
    }
  }
})
</script>

```

```
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: E:\WorkSpace\Tw\tw-library-vue3\packages\tw-editor-ui\stories\layouts\tw-panel\S01_基本使用.vue: Unterminated regular expression. (7:19)

   5 |         return () => {
   6 |             return Test;
>  7 |             Tsx < /div>;
     |                    ^
   8 |         };
   9 |     }
  10 | });
    at Object._raise (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:807:17)
    at Object.raiseWithData (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:800:17)
    at Object.raise (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:761:17)
    at Object.readRegexp (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:2371:20)
    at Object.parseExprAtom (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:11406:16)
    at Object.parseExprAtom (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:7169:20)
    at Object.parseExprSubscripts (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:11102:23)
    at Object.parseUpdate (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:11082:21)
    at Object.parseMaybeUnary (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:11060:23)
    at Object.parseExprOpBaseRightExpr (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10996:34)
    at Object.parseExprOpRightExpr (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10989:21)
    at Object.parseExprOp (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10947:27)
    at Object.parseExprOps (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10909:17)
    at Object.parseMaybeConditional (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10877:23)
    at Object.parseMaybeAssign (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10835:21)
    at Object.parseExpressionBase (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@babel\parser\lib\index.js:10775:23)
    at processResult (E:\WorkSpace\Tw\tw-library-vue3\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:721:19)
    at E:\WorkSpace\Tw\tw-library-vue3\node_modules\@storybook\builder-webpack5\node_modules\webpack\lib\NormalModule.js:827:5
    at E:\WorkSpace\Tw\tw-library-vue3\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at E:\WorkSpace\Tw\tw-library-vue3\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (E:\WorkSpace\Tw\tw-library-vue3\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at E:\WorkSpace\Tw\tw-library-vue3\node_modules\babel-loader\lib\index.js:59:103

```

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.4 - E:\DevEnv\nodejs\node.EXE
    Yarn: 1.17.3 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - E:\DevEnv\nodejs\npm.CMD
  Browsers:
    Chrome: 93.0.4577.63
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)

**Additional context**
Vue: 3.2.7
Builder:  webpack5
"@storybook/addon-actions": "^6.3.7",
"@storybook/addon-essentials": "^6.3.7",
"@storybook/addon-links": "^6.3.7",
"@storybook/addon-storysource": "^6.3.7",
"@storybook/builder-webpack5": "^6.3.7",
"@storybook/manager-webpack5": "^6.3.7",
"@storybook/vue3": "^6.3.7",

**Comment by IanVS** [comment]
If you're still having a problem with this in recent storybook versions, please let me know and I'll re-open this.
