### ISSUE TITLE
[6.4.0-alpha.38] When using `storyStoreV7`, _this5.renderToDOM is not a function

### ISSUE THREAD

**Issue by IanVS** [storybookjs/storybook#16084]
**Describe the bug**
I'm trying out storyStoreV7, and while my MDX introduction story renders correctly, none of my react component stories do.  Instead, I get this error for all my stories:

```
TypeError: _this5.renderToDOM is not a function
    at _callee8$ (http://localhost:6006/vendors~main.iframe.bundle.js:26558:33)
    at tryCatch (http://localhost:6006/vendors~main.iframe.bundle.js:191048:40)
    at Generator.invoke [as _invoke] (http://localhost:6006/vendors~main.iframe.bundle.js:191278:22)
    at Generator.next (http://localhost:6006/vendors~main.iframe.bundle.js:191103:21)
    at asyncGeneratorStep (http://localhost:6006/vendors~main.iframe.bundle.js:25810:103)
    at _next (http://localhost:6006/vendors~main.iframe.bundle.js:25812:194)
```

**To Reproduce**
This reproduces easily in a clean project by turning the feature on.

```
features: {
  storyStoreV7: true,
},
```

**System**
```
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.4.0/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Firefox: 91.0.1
    Safari: 14.1.2
```

**Additional context**
I also have `previewCsfV3` and `babelModeV7` enabled, if that matters.

**Comment by shilman** [comment]
Did you try adding `@storybook/react` to your list of `addons` in `.storybook/main.js`? We still haven't documented the V7 stuff yet, which is why we haven't announced it.

**Comment by IanVS** [comment]
That does indeed solve the issue, thanks.

**Comment by the-ult** [comment]
> Did you try adding @storybook/react to your list of addons in .storybook/main.js? We still haven't documented the V7 stuff yet, which is why we haven't announced it.

When adding `@storybook/angular` to the `main.js`

```js
module.exports = {
  stories: [],
  addons: ['@storybook/angular', '@storybook/addon-essentials'],
  features: {
    storyStoreV7: true,
    previewCsfV3: true,
  },
};
```

I get the following error:
```
Error: Cannot find module './dist/esm/client/preview/config'
Require stack:
- .../node_modules/@storybook/angular/preset.js
- .../node_modules/@storybook/core-common/dist/cjs/presets.js
- .../node_modules/@storybook/core-common/dist/cjs/index.js
- .../node_modules/@storybook/core-server/dist/cjs/index.js
- .../node_modules/@storybook/core/dist/cjs/server.js
- .../node_modules/@storybook/core/server.js
- .../node_modules/@nrwl/storybook/src/executors/storybook/storybook.impl.js
- .../node_modules/@nrwl/tao/src/shared/workspace.js
- .../node_modules/@nrwl/tao/src/commands/run.js
- .../node_modules/@nrwl/tao/index.js
- .../node_modules/@nrwl/cli/lib/run-cli.js
```

Does the angular plugin needs some additional settings?

**Comment by shilman** [comment]
@the-ult there should be a file `/node_modules/@storybook/angular/dist/esm/client/preview/config.js`. is there?

**Comment by the-ult** [comment]
package.json:
```json
"@storybook/addon-actions": "6.4.0-beta.1",
    "@storybook/addon-essentials": "6.4.0-beta.1",
    "@storybook/addon-jest": "6.3.8",
    "@storybook/addon-links": "6.3.8",
    "@storybook/angular": "6.4.0-beta.1",
    "@storybook/builder-webpack5": "6.4.0-beta.1",
    "@storybook/manager-webpack5": "6.4.0-beta.1",  
```

Seems like there is no `esm` folder

<img width="391" alt="Screenshot 2021-09-27 at 21 09 22" src="https://user-images.githubusercontent.com/4863062/134969957-7a277b13-7672-4af2-bcbd-8dcf59e6dbef.png">

**Comment by the-ult** [comment]
@shilman 
Looking at the https://github.com/storybookjs/storybook/blob/next/app/angular/package.json
it seems like it is not yet updated for `esm`

`storybook/react` has the following in `package.json`
```json
"main": "dist/cjs/client/index.js",
  "module": "dist/esm/client/index.js",
  "types": "dist/ts3.9/client/index.d.ts",
  "typesVersions": {
    "<3.8": {
      "dist/ts3.9/*": [
        "dist/ts3.4/*"
      ]
    }
  },
```

while angular still has:
```json
"main": "dist/ts3.9/client/index.js",
  "module": "dist/ts3.9/client/index.js",
  "types": "dist/ts3.9/client/index.d.ts",
  "typesVersions": {
    "<3.8": {
      "dist/ts3.9/*": [
        "dist/ts3.4/*"
      ]
    }
  },
```

**Comment by literalpie** [comment]
If it's helpful, [here](https://github.com/literalpie/sb-ng-performance/tree/storystorev7-angular) is a branch with a reproduction.

**Comment by shilman** [comment]
@ndelangen @kroeder any idea what's up with this? ☝️

**Comment by ksorv** [comment]
For me, I had a small bug in my code:

```jsx
export default {
    name: 'Publisher/AccountSelector',
    component: AccountSelector
}
```

It should have been:

```jsx
export default {
    title: 'Publisher/AccountSelector',
    component: AccountSelector
}
```

It was supposed to be 'title' and i wrote 'name' instead.
