### ISSUE TITLE
Angular regression `Error trying to diff '[...]' Only arrays and iterables are allowed`

### ISSUE THREAD

**Issue by stefan-schweiger** [storybookjs/storybook#16108]
**Describe the bug**
Somewhere after `6.4.0-alpha.33` my stories which have an array property with a initial value started to break.

```
@Component({
  selector: 'app-toolbar',
  template: `<div
      class="texteditor-toolbar"
      role="toolbar"
      aria-orientation="horizontal"
    >
      <ng-container *ngFor="let tool of toolbar; let i = index">
        <button
          class="texteditor-toolbar-action"
          [title]="tool.title"
          tabindex="-1"
        >
          {{ tool.icon }}
        </button>
      </ng-container>
    </div>`,
})
export default class ToolbarComponent {
  public toolbar: ToolConfig[] = [
    {
      action: 'heading',
      options: { level: 1 },
      icon: 'heading1',
      title: 'Heading 1',
    },
    {
      action: 'heading',
      options: { level: 2 },
      icon: 'heading2',
      title: 'Heading 2',
    },
  ];
}
```

This code results in the following error in the console:

```
Error trying to diff '[
    {
      action: 'heading',
      options: { level: 1 },
      icon: 'heading1',
      title: 'Heading 1',
    },
    {
      action: 'heading',
      options: { level: 2 },
      icon: 'heading2',
      title: 'Heading 2',
    },
  ]'. Only arrays and iterables are allowed
```

This appears to happen because storybook tries to set the value of the array it extracted from compodoc as a string. When  I add `/** @ignore */` to this property it doesn't happen anymore, because the property is excluded from the documentation. But this isn't really desirable.

**To Reproduce**
https://github.com/stefan-schweiger/sb-angular-iterator-bug

**System**
```
System:
  OS: Windows 10 10.0.19043
  CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
Binaries:
  Node: 14.17.6 - C:\Program Files\nodejs\node.EXE       
  Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
npmPackages:
  @storybook/addon-actions: ^6.4.0-alpha.39 => 6.4.0-alpha.39
  @storybook/addon-essentials: ^6.4.0-alpha.39 => 6.4.0-alpha.39
  @storybook/addon-links: ^6.4.0-alpha.39 => 6.4.0-alpha.39
  @storybook/angular: ^6.4.0-alpha.39 => 6.4.0-alpha.39
  @storybook/builder-webpack5: ^6.4.0-alpha.39 => 6.4.0-alpha.39
  @storybook/manager-webpack5: ^6.4.0-alpha.39 => 6.4.0-alpha.39
```

**Comment by daan93** [comment]
I noticed boolean properties also get set to false and can't be updated by the component after that. This also breaks my stories. Shouldn't properties, outputs and methods not be controls anyway? To me it only makes sense for inputs to be editable.

**Comment by fimius23** [comment]
+1

**Comment by nagashimam** [comment]
> Somewhere after 6.4.0-alpha.33 my stories which have an array property with a initial value started to break.

Does anyone know why we stopped using eval() in [this commit](https://github.com/storybookjs/storybook/commit/9f24a7993b0f10f81d3b1691b17b7b8d0f0d5557#diff-4363e51a0fc41312a0a9ff70bffdcbafe3b027cc494529b2d2a918ae7ef11d3bL161)? Maybe because it can be vulnerable to script injection?

If using eval() isn't option, it's hard to correctly parse properties that are array of some type because compodoc just says `"type": "[]"` and we don't know what kind of array. We could return undefined for array [like this](https://github.com/nagashimam/storybook/commit/5f1f9917acf452258f95328f5e057186e1fe0d9b) to prevent stories from breaking, though it's not ideal.

**Comment by stefan-schweiger** [comment]
I think this is still an issue.

**Comment by wesself** [comment]
Yes, this is also an issue for me since we upgrade to angular 13 with Storybook version 6.4.14.
Getting this now.

**Comment by paradox37** [comment]
Still an issue with Storybook 6.4.19

**Comment by himanshu-mobstac** [comment]
@shilman @stefan-schweiger Can you please fix this.

**Comment by GrumpyMeow** [comment]
Indeed.. It's (again) an issue with Storybook v6.4.20.

**Comment by stirelli** [comment]
Do we have any update on this one ? I'm also facing the same issue. At least a way to get rid of this issue ?

**Comment by stirelli** [comment]
After digging in, I found out the issue is related with compodoc actually. 
https://github.com/storybookjs/storybook/issues/17004

**Comment by elliottregan** [comment]
I ran into this, too. Seems like public class properties are being evaluated as a string, instead of an array.

This is happening in Angular 12.

**Comment by seelam621** [comment]
main.js:1 ERROR Error: NG0900
    at e.value (main.js:1:491478)
    at F.value (main.js:1:337876)
    at hs (main.js:1:380317)
    at pa (main.js:1:380120)
    at fo (main.js:1:379805)
    at Rd (main.js:1:406708)
    at Object.Od (main.js:1:406604)
    at template (958.js:1:105148)
    at uf (main.js:1:410323)
    at _a (main.js:1:409032)
es @ main.js:1
value @ main.js:1
(anonymous) @ main.js:1
B.invoke @ polyfills.js:1
B.run @ polyfills.js:1
value @ main.js:1
value @ main.js:1
(anonymous) @ main.js:1
B.invoke @ polyfills.js:1
onInvoke @ main.js:1
B.invoke @ polyfills.js:1
B.run @ polyfills.js:1
value @ main.js:1
next @ main.js:1
value @ main.js:1
value @ main.js:1
value @ main.js:1
value @ main.js:1
value @ main.js:1
value @ main.js:1
Lh @ main.js:1
N_ @ main.js:1
onInvokeTask @ main.js:1
B.invokeTask @ polyfills.js:1
B.runTask @ polyfills.js:1
B.invokeTask @ polyfills.js:1
ie @ polyfills.js:1
ye @ polyfills.js:1
xe @ polyfills.js:1
main.js:1 ERROR Error: NG0900


iam getting this error in console.when i something on the web application

**Comment by softdays** [comment]
Reproduced with SB 6.5.15

**Comment by valentinpalkovic** [comment]
Thanks for the detailed bisect. The root cause was compodoc serializing the array initializer to a string and Storybook re-applying it via `argType.defaultValue` inference — that inference path was removed in v7 (defaults now come from story-level `args`, which preserve the real array), and the Angular renderer was overhauled in v8/v9. Closing as resolved by the v7-v9 changes; please open a fresh ticket with a v10 repro if the symptom recurs.
