### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by literalpie** [storybookjs/storybook#16355]
**Describe the bug**
Storybook does not run with the latest Angular 13 RC. There seems to be a problem with using `require` in framework-preset-angular-ivy

<details>
  <summary>Failed to load preset error message:</summary>
<code>
info @storybook/angular v6.4.0-beta.11
info 
info => Loading presets
WARN   Failed to load preset: "/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js"
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js not supported.
ERR! Instead change the require of index.js in /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at interopRequireDefault (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20)
ERR!     at /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:236:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:235:18)
ERR!     at getPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:293:23)
ERR!     at loadAllPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:318:10)
ERR!     at buildDevStandalone (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:48)
ERR!     at async Object.buildDev (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:160:5)
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js not supported.
ERR! Instead change the require of index.js in /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js to a dynamic import() which is available in all CommonJS modules.
ERR!     at Object.<anonymous> (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at interopRequireDefault (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20)
ERR!     at /Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:236:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:235:18)
ERR!     at getPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:293:23)
ERR!     at loadAllPresets (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-common/dist/cjs/presets.js:318:10)
ERR!     at buildDevStandalone (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:48)
ERR!     at async Object.buildDev (/Users/bkindle/Documents/Development/temp/sb-ng-performance/node_modules/@storybook/core-server/dist/cjs/build-dev.js:160:5) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
</code>
</details>

**To Reproduce**
Add storybook to any Angular 13 project, or see [this reproduction branch](https://github.com/literalpie/sb-ng-performance/tree/ng-13).

**System**
```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 3.0.1 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-docs: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-essentials: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/addon-links: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/angular: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/builder-webpack5: ^6.4.0-beta.11 => 6.4.0-beta.11 
    @storybook/manager-webpack5: ^6.4.0-beta.11 => 6.4.0-beta.11 
```

**Additional context**
Angular just entered the Release Candidate phase.

**Comment by literalpie** [comment]
@shilman FYI angular 13 is now released
