### ISSUE TITLE
Storybook fails with Angular 12 and webpack5

### ISSUE THREAD

**Issue by nicolae536** [storybookjs/storybook#16367]
**Describe the bug**
After updating to angular 12 the project seems to run fine but storybook stopped working. I get the following error form the console

```
info @storybook/angular v6.3.12
info
info => Loading presets
WARN   Failed to load preset: {"name":"D:\\Workspace\\Organiztions\\houzy\\angular-frontend\\node_modules\\@storybook\\angular\\dist\\ts3.9\\client\\index.js","type":"presets"} on level 1
ERR! TypeError: Cannot set properties of undefined (setting 'STORYBOOK_ENV')
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\preview\globals.js:9:28)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\preview\index.js:16:1)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\index.js:13:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!  TypeError: Cannot set properties of undefined (setting 'STORYBOOK_ENV')
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\preview\globals.js:9:28)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\preview\index.js:16:1)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\@storybook\angular\dist\ts3.9\client\index.js:13:17)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
info => Loading 1 config file in "D:\Workspace\Organiztions\houzy\angular-frontend\.storybook"
info => Loading 9 other files in "D:\Workspace\Organiztions\houzy\angular-frontend\.storybook"
info => Adding stories defined in "D:\Workspace\Organiztions\houzy\angular-frontend\.storybook\main.js"
info => Found custom tsconfig.json
Warning: Entry point 'ng2-pdf-viewer' contains deep imports into 'D:/Workspace/Organiztions/houzy/angular-frontend/node_modules/pdfjs-dist/es5/build/pdf', 'D:/Workspace/Organiztions/houzy/angular-frontend/node_modules/pdfjs-dist/es5/web/pdf_viewer'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "houzy:build" for configuring Storybook
info => Using angular-cli webpack config
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
7% setup compile fork-ts-checker-webpack-pluginStarting type checking service...
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Ignoring cached manager due to change in D:\Workspace\Organiztions\houzy\angular-frontend\.storybook\tsconfig.json
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/17 entries 32/87 dependencies 2/28 modulesnode:internal/event_target:774
  process.nextTick(() => { throw err; });
                           ^

Error [ERR_INTERNAL_ASSERTION]: Unknown worker message type message
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:371:5)
    at Function.fail (node:internal/assert:20:9)
    at Worker.[kOnMessage] (node:internal/worker:320:12)
    at MessagePort.<anonymous> (node:internal/worker:204:57)
    at ZoneDelegate.invokeTask (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\zone.js\dist\zone.js:434:35)
    at Zone.runTask (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\zone.js\dist\zone.js:205:51)
    at ZoneTask.invokeTask [as invoke] (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\zone.js\dist\zone.js:516:38)
    at invokeTask (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\zone.js\dist\zone.js:1656:18)
    at MessagePort.globalZoneAwareCallback (D:\Workspace\Organiztions\houzy\angular-frontend\node_modules\zone.js\dist\zone.js:1682:21)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:559:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'ERR_INTERNAL_ASSERTION'
}
```

**To Reproduce**
I will try to provide a repo for the reproduction

**System**
```
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.50)
  npmPackages:
    @storybook/addon-actions: 6.3.12 => 6.3.12
    @storybook/addon-essentials: 6.3.12 => 6.3.12
    @storybook/addon-links: 6.3.12 => 6.3.12
    @storybook/angular: 6.3.12 => 6.3.12
    @storybook/builder-webpack5: ^6.3.12 => 6.3.12
    @storybook/manager-webpack5: ^6.3.12 => 6.3.12
```

**Additional context**
I can try to help with the reproduction maybe it's just a node version issue ? 🤔  The error seems pretty cryptic to me

**Comment by shilman** [comment]
Try upgrading to the latest prerelease:

```
npx sb@next upgrade --prerelease
```

Does that fix it?

**Comment by nicolae536** [comment]
@shilman @ThibaudAV 
I managed to fix also that error it seems the `esm` folder doesn't exist in your dist folder.
Final fix was:
Installing `@angular-devkit/architect`
Than going into `node_modules\@storybook\angular\preset.js` and changing it to be like this 
```
function config(entry = []) {
  return [...entry, require.resolve('./dist/ts3.9/client/preview/config')];
}

module.exports = {
  config,
};
```
I changed `./dist/esm/client/preview/config` to `./dist/ts3.9/client/preview/config`

And then the project started working now I have some errors in the browser regarding accessing `add` on an elementClassList.
But I think this I can manage if you are able to fix this problem so that I can update the project to the working storybook version

**Comment by shilman** [comment]
@nicolae536 Thanks so much for the fix. We'll get that updated in the next day or two, just want to double check with @ThibaudAV

**Comment by nicolae536** [comment]
@shilman any news on this was it fixed ?

**Comment by the-ult** [comment]
Seems to be fixed:
https://github.com/storybookjs/storybook/issues/16084
