### ISSUE TITLE
Storybook HTML + Vite Builder fails with Invalid WebSocket Frame

### ISSUE THREAD

**Issue by spaceninja** [storybookjs/storybook#16616]
**Describe the bug**
I tried creating a barebones Storybook HTML + Vite builder, and it crashes on startup with the following error:

```
$ yarn storybook
yarn run v1.22.11
$ start-storybook -p 6006
info @storybook/html v6.4.0-beta.29
info 
info => Loading presets
Pre-bundling dependencies:
  @base2/pretty-print-object
  @emotion/core
  @emotion/is-prop-valid
  @emotion/styled
  @mdx-js/react
  (...and 68 more)
(this will be run only when your dependencies or config have changed)
info => Using prebuilt manager
╭───────────────────────────────────────────────────╮
│                                                   │
│   Storybook 6.4.0-beta.29 for Html started        │
│   822 ms for preview                              │
│                                                   │
│    Local:            http://localhost:6006/       │
│    On your network:  http://192.168.1.10:6006/    │
│                                                   │
╰───────────────────────────────────────────────────╯
11:51:30 AM [vite] new dependencies found: @storybook/html, updating...
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-SSJTNKAE.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-A67CITS2.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-L7IACPKD.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-35YZ7F37.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-ZDMJQJP6.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-FIXK7XEI.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-QMLIUZKE.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-RIKFAQEX.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-HG3UJIHK.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-BREKZL7B.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-JKXZNSO4.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-ZG5NMPL6.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-DTZRYZH3.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-RP5NREEG.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-TY6DTUNP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-SOWE4IYI.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-YKBTDVUD.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-NFBPIU5F.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-SL4AQEKD.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-NVLT2GSS.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-4ZGKT66R.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-HDSG622B.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-LTJYI4XO.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-TO7GQLCP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-LGJWHP3V.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-YOCZHAJ6.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-E42FT3TI.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-RZ3O4VAQ.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-AKDXD5X2.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-HKTLQ3VE.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-B4UTLCPF.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-3PTJL3DD.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-TLDBNVGF.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-2K4I45XJ.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-TFJ7WVS5.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-OVAWAKSM.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-FFTI4HRF.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-ALKUSHJJ.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-2RQP3VRT.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-YDHHRTKG.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-CWPAOAYP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-5QA5WRKK.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-LXJSBPNY.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-QT3W5IBM.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-XQNLW25O.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-PQII2DDC.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-6WHSCYI5.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-FNR67VXA.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-PVTB34RP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-NL5CSRYA.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-JG7EYYDK.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-QUWNMKPI.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-V7XICNMP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-34GBQZSP.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-UPDQLB4G.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-VAJ4LHDR.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-GJ7JSVYZ.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-JST3G223.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-IIWOVGRQ.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-MNFM4AN4.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/regenerator-runtime_runtime_js.js?v=ef3e2fa4.
11:51:30 AM [vite] Failed to load source map for /node_modules/.vite/chunk-NSX6RLV7.js?v=ef3e2fa4.
node:events:371
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 52525
    at Receiver$1.controlMessage (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50517:18)
    at Receiver$1.getData (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50385:42)
    at Receiver$1.startLoop (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50110:22)
    at Receiver$1._write (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:50045:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver$1.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:52459:37)
    at Socket.emit (node:events:406:35)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket$2 instance at:
    at Receiver$1.receiverOnError (/Users/scott/Sites/storybook-vite/node_modules/vite/dist/node/chunks/dep-85dbaaa7.js:52346:13)
    at Receiver$1.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_INVALID_CLOSE_CODE',
  [Symbol(status-code)]: 1002
}
error Command failed with exit code 1.
```

**To Reproduce**
```
yarn init
yarn add -D vite
npx sb@next init --builder storybook-builder-vite
yarn storybook
```

Repo here: https://github.com/spaceninja/storybook-vite

**System**

Environment Info:
```
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Edge: 95.0.1020.44
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.4.0-beta.29 => 6.4.0-beta.29 
    @storybook/addon-essentials: ^6.4.0-beta.29 => 6.4.0-beta.29 
    @storybook/addon-links: ^6.4.0-beta.29 => 6.4.0-beta.29 
    @storybook/html: ^6.4.0-beta.29 => 6.4.0-beta.29 
```

**Comment by shilman** [comment]
Please file Vite-related issues in https://github.com/eirslett/storybook-builder-vite/

Closing this for now. Thank you! 🙏
