### ISSUE TITLE
npx sb upgrade "No storybook core packages found."

### ISSUE THREAD

**Issue by totszwai** [storybookjs/storybook#16620]
**Describe the bug**
Trying to run `npx sb upgrade`. Upgrade says "Done" but then throws an `UnhandledPromiseRejection`

```
npx sb upgrade
 • Checking for latest versions of '@storybook/*' packagesinfo ,Upgrading /home/projects/blah/icons/package.json
info 
info All dependencies match the latest package versions :)
info ,npx: installed 314 in 21.042s
info 
info 
 • Installing upgrades • Preparing to install dependencies. ✓


yarn install v1.22.15
warning package.json: No license field
warning ../../package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning @blah/icons@0.3.0: No license field
[1/5] Validating package.json...
warning @blah/icons@0.3.0: No license field
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @storybook/preset-create-react-app@3.2.0" has unmet peer dependency "@storybook/node-logger@*".
warning "@storybook/preset-create-react-app > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has unmet peer dependency "react-refresh@>=0.8.3 <0.10.0".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > @typescript-eslint/eslint-plugin@5.3.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@5.3.0" has unmet peer dependency "eslint@*".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > eslint-utils@3.0.0" has unmet peer dependency "eslint@>=5".
warning " > @typescript-eslint/parser@5.3.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "storybook > @storybook/cli@6.3.12" has unmet peer dependency "jest@*".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 50.85s.
. ✓
WARN No storybook core packages found.
WARN 'npm ls | grep storybook' can show if multiple versions are installed.
(node:3163754) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined
    at checkVersionConsistency (/home/projects/blah/icons/node_modules/storybook/node_modules/@storybook/cli/dist/cjs/upgrade.js:63:46)
    at upgrade (/home/projects/blah/icons/node_modules/storybook/node_modules/@storybook/cli/dist/cjs/upgrade.js:142:19)
    at Command.<anonymous> (/home/projects/blah/icons/node_modules/storybook/node_modules/@storybook/cli/dist/cjs/generate.js:42:407)
    at Command.listener [as _actionHandler] (/home/projects/blah/icons/node_modules/storybook/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/home/projects/blah/icons/node_modules/storybook/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/home/projects/blah/icons/node_modules/storybook/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/home/projects/blah/icons/node_modules/storybook/node_modules/commander/index.js:970:12)
    at Command.parse (/home/projects/blah/icons/node_modules/storybook/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/home/projects/blah/icons/node_modules/storybook/node_modules/@storybook/cli/dist/cjs/generate.js:127:70)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**To Reproduce**
- From storybook 6.3.10
- Ran `npx sb upgrade`, it upgraded it to 6.3.12, and it threw the above error message
- Every subsequence run of `npx sb upgrade` will keep throwing the error message...

**System**
```

Environment Info:

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (16) x64 Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz
  Binaries:
    Node: 12.22.6 - ~/.config/nvm/versions/node/v12.22.6/bin/node
    Yarn: 1.22.15 - ~/.config/nvm/versions/node/v12.22.6/bin/yarn
    npm: 6.14.15 - ~/.config/nvm/versions/node/v12.22.6/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Firefox: 90.0
  npmPackages:
    @storybook/addon-actions: ^6.3.12 => 6.3.12 
    @storybook/addon-essentials: ^6.3.12 => 6.3.12 
    @storybook/addon-links: ^6.3.12 => 6.3.12 
    @storybook/components: ^6.3.12 => 6.3.12 
    @storybook/core: ^6.3.12 => 6.3.12 
    @storybook/core-events: ^6.3.12 => 6.3.12 
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0 
    @storybook/preset-typescript: ^3.0.0 => 3.0.0 
    @storybook/react: ^6.3.12 => 6.3.12 
    @storybook/theming: ^6.3.12 => 6.3.12 
```

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.30 containing PR #16622 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
