### ISSUE TITLE
Use `Storybook` in a project built by `Sveltekit` to report an error: `Must use import to load ES Module`

### ISSUE THREAD

**Issue by DanaCoding** [storybookjs/storybook#16680]
**Describe the bug**
![image](https://user-images.githubusercontent.com/93444868/141693984-dda2aea5-298f-4f4d-a3cb-e14d4fa12e32.png)
```shell
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'storybook'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v14.13.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:F:\workspace\svelte-demo\.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:C:\Users\Administrator\.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\Administrator\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 739d589aaf252fd0
20 timing npm:load Completed in 22ms
21 timing command:run Completed in 2990ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1047:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid svelte-demo@0.0.1
24 verbose cwd F:\workspace\svelte-demo
25 verbose Windows_NT 10.0.19042
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "storybook"
27 verbose node v14.13.1
28 verbose npm  v7.6.3
29 error code 1
30 error path F:\workspace\svelte-demo
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c start-storybook -p 6006
33 verbose exit 1
```

**To Reproduce**
> Execute in the root directory of the project built by sveltekit:

```base
npx sb@next init
```

> Start storybook

```base
npm run storybook
```

**System**
```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/addon-essentials: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/addon-links: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0
    @storybook/svelte: ^6.4.0-rc.1 => 6.4.0-rc.1
```

**Additional context**
https://github.com/sveltejs/kit/issues/2801

**Comment by bluwy** [comment]
We should close this as this has been answered at https://github.com/sveltejs/kit/discussions/2803

**Comment by Myrmod** [comment]
> We should close this as this has been answered at [sveltejs/kit#2803](https://github.com/sveltejs/kit/discussions/2803)

In the linked discussion we have 2 workarounds, however the actual problem is, that storybook is not correctly initialized, out of the box, to run a SvelteKit project using ESM.

**Comment by benmccann** [comment]
If you create a Storybook project today it will create the `main` file with a `.cjs` extension and so it will work
