### ISSUE TITLE
Angular 10.1.4 Error '@angular-devkit/build-angular/src/webpack/configs'

### ISSUE THREAD

**Issue by Marklb** [storybookjs/storybook#16691]
**Describe the bug**
There was a question on Discord about Storybook `6.4.0-rc.1` throwing an error with Angular `10.1.4`. I created a new Angular `10.1.4` app and initialized Storybook `64.0-rc.1` and got the same error. The app did seem to work for me, but it was a new project and only had the same stories added by `sb init`. I haven't tried debugging what config the build ended up using. So, I am not sure if this is from a check that didn't need to be logged or if it affected the build.

My assumption is that #16644 may have caused it, but I haven't tried to confirm that.

The error when using `npm run storybook`:

<details>
<summary>Details</summary>

```sh
WARN   Failed to load preset: {"name":"C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\framework-preset-angular-cli.js","type":"presets"} on level 2
ERR! Error: Cannot find module '@angular-devkit/build-angular/src/webpack/configs'
ERR! Require stack:
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\angular-cli-webpack-12.2.x.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-common\dist\cjs\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core\server.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\bin\index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\angular-cli-webpack-12.2.x.js:57:10)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js:79:36)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!  Error: Cannot find module '@angular-devkit/build-angular/src/webpack/configs'
ERR! Require stack:
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\angular-cli-webpack-12.2.x.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-common\dist\cjs\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\core\server.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\index.js
ERR! - C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\bin\index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\angular-cli-webpack-12.2.x.js:57:10)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (C:\Users\mberry\dev_home\tmp\example-app\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js:79:36)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\angular-cli-webpack-12.2.x.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\framework-preset-angular-cli.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\core-common\\dist\\cjs\\presets.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\core-common\\dist\\cjs\\index.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\core-server\\dist\\cjs\\index.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\core\\dist\\cjs\\server.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\core\\server.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\index.js',
ERR!     'C:\\Users\\mberry\\dev_home\\tmp\\example-app\\node_modules\\@storybook\\angular\\bin\\index.js'
ERR!   ]
ERR! }
```
</details>

The user also mentioned the following warning. I don't know what their styles look like or project dependencies, so I am not sure if it is related. In the projected I created, I tried using `/` for division and didn't get the warning.

<details>
<summary>Details</summary>

```sh
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

</details>

**To Reproduce**
I created a new project with `npx -p @angular/cli@10.1.4 ng new example-app --style=scss`, then added Storybook with `npx sb@6.4.0-rc.1 init`.

**System**
```sh
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53), ChromiumDev (97.0.1069.0)
  npmPackages:
    @storybook/addon-actions: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/addon-essentials: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/addon-links: ^6.4.0-rc.1 => 6.4.0-rc.1
    @storybook/angular: ^6.4.0-rc.1 => 6.4.0-rc.1
```

**Additional context**
Discord message that asked about the problem: https://discord.com/channels/486522875931656193/490770949910691862/909823122759381103

**Comment by jldavis33** [comment]
I've also hit the same issue with Angular 10.2.5 and storybook 6.4.13

**Comment by msjahun** [comment]
I've also hit the same issue Angular 10
Angular CLI: 10.2.4
Node: 14.15.0
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.4
@angular-devkit/build-angular   0.1002.4
@angular-devkit/core            10.2.4
@angular-devkit/schematics      10.2.4
@angular/cli                    10.2.4
@schematics/angular             10.2.4
@schematics/update              0.1002.4
ng-packagr                      10.1.2
rxjs                            6.6.7
typescript                      4.5.5

Storybook 6.4.19

**Comment by valentinpalkovic** [comment]
Storybook for Angular requires Angular 18+ (per the v9 release; current peer range `>=18.0.0 < 22.0.0`), so Angular 10.1.4 is several majors below supported. Closing as out-of-scope; if you upgrade to a supported Angular version and still hit a `@angular-devkit/build-angular` resolution issue, please open a fresh issue with a v10 repro.
