### ISSUE TITLE
Storybook 6.4 with Angular 13 breaks lifecycle hooks of abstract component

### ISSUE THREAD

**Issue by dkimmich-onventis** [storybookjs/storybook#16838]
**Describe the bug**
In my Angular 13 project using Storybook 6.4, I am using an abstract component to destroy Observables. There I provide a subject, and in `ngOnDestroy()` that subject is completed. Since Storybook 6.4, I am getting a runtime error in those stories where I use that abstract component:

> this.destroy$.next is not a function

It seems like the subject is already destroyed.

**To Reproduce**
https://github.com/dsimon-onventis/storybook-lifecycle-errors-repro

Open one of the "Button" stories, and then navigate to another story.

**System**
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 3.1.1 - /usr/bin/yarn
    npm: 8.1.4 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
  npmPackages:
    @storybook/addon-actions: ^6.4.1 => 6.4.1
    @storybook/addon-docs: ^6.4.1 => 6.4.1
    @storybook/addon-essentials: ^6.4.1 => 6.4.1
    @storybook/addon-links: ^6.4.1 => 6.4.1
    @storybook/angular: ^6.4.1 => 6.4.1
    @storybook/builder-webpack5: ^6.4.1 => 6.4.1
    @storybook/manager-webpack5: ^6.4.1 => 6.4.1

**Additional context**
With `angularLegacyRendering` set to true, there are no runtime errors.

**Comment by dsimon-onventis** [comment]
This is still an issue...

**Comment by f4irline** [comment]
Having this issue as well

**Comment by fikkatra** [comment]
Having the same issue. In my case, it's not ngDestroy, but ngAfterViewInit. This lifecycle hook code:
```
private sizeChangedSubject = new Subject<void>();

public ngAfterViewInit(): void {
  setTimeout(() => {
    this.sizeChangedSubject.next();
  }, 0);
}
```

produces the error:

> ERROR TypeError: this.sizeChangedSubject.next is not a function

**Comment by jasonhodges** [comment]
Experiencing this issue as well when navigating between stories.
 
this.destroy$.next is not a function. 
`ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  `}

**Comment by railsstudent** [comment]
I have this issue and cannot upgrade to latest version of storybook

**Comment by shilman** [comment]
For people experiencing this issue:
- does the workaround work for you?
- have you tried the angular builder https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sb-angular-builder

**Comment by dsimon-onventis** [comment]
I'm already using the angular builder, same issue. For me, the workaround works.

**Comment by f4irline** [comment]
> For people experiencing this issue:
> 
> * does the workaround work for you?
> * have you tried the angular builder https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sb-angular-builder

I'm using the Angular builder as well. The workaround works but for some reason breaks other stuff, like changes in `@Input()` values not being reflected in the Storybook UI

**Comment by ld210** [comment]
This is still an issue with Storybook 6.4.22 and Angular 13.3. 
Workaround looks to be working, but i haven't yet tested all stories.

**Comment by kailo777** [comment]
Hey @all, 

The fix to set angularLegacyRendering seems to work

**Comment by dsimon-onventis** [comment]
In my real project the error is gone after updating to Storybook 6.5, however in the reproduction repo the error still appears. Can't tell why, will keep you updated.

**Comment by ld210** [comment]
Issue is still there with 6.5, if i remove "angularLegacyRendering", the OnDestroy hook breaks storybook.

**Comment by nattySP** [comment]
I am having this problem as well. 
@storybook/angular v6.5.12 (also tried v6.5.13)
@angular v13.3.11
I am using the builder.

- There are no abstract components involved when I get the ` this.destroyed$.next is not a function` error when its called from ngOnDestroy. The component class member declaration looks like `private readonly destroyed$ = new Subject<void>();`
- Although the workaround of setting `angularLegacyRendering: true` fixes this issue, it breaks `build-storybook`, apparently because it is forcing re-initialization (a.k.a. duplication) of Storybooks DynamicModule when switching between stories (https://github.com/storybookjs/storybook/blob/v6.5.12/app/angular/src/client/preview/angular/helpers.ts#L206), which is causing the following error: 

```
StorybookModule.js:33 Unhandled Promise rejection: Type AppComponent is part of the declarations of 2 modules: DynamicModule and DynamicModule! Please consider moving AppComponent to a higher module that imports DynamicModule and DynamicModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in DynamicModule and DynamicModule. ; Zone: <root> ; Task: Promise.then ; Value: Error: Type AppComponent is part of the declarations of 2 modules: DynamicModule and DynamicModule! Please consider moving AppComponent to a higher module that imports DynamicModule and DynamicModule. You can also create a new NgModule that exports and includes AppComponent then import that NgModule in DynamicModule and DynamicModule.
    at verifySemanticsOfNgModuleDef (StorybookModule.js:33:1)
    at DynamicModule.get (StorybookModule.js:33:1)
    at getInjectorDef (StorybookModule.js:33:1)
    at R3Injector.processInjectorType (StorybookModule.js:33:1)
    at StorybookModule.js:33:1
    at StorybookModule.js:33:1
    at Array.forEach (<anonymous>)
    at deepForEach (StorybookModule.js:33:1)
    at new R3Injector (StorybookModule.js:33:1)
    at createInjectorWithoutInjectorInstances (StorybookModule.js:33:1)
```

The AppComponent in question is https://github.com/storybookjs/storybook/blob/v6.5.12/app/angular/src/client/preview/angular/components/app.component.ts

**Comment by SadScream** [comment]
The problem is in the Compdoc library. Add comment @ignore on the property that is converted to a string by mistake and the problem will disappear.
e.g.
```
  /**
   * @ignore
   */
  usefulProperty = {};
```

**Comment by valentinpalkovic** [comment]
The legacy Angular renderer that caused `destroy$.next is not a function` was removed in Storybook 7 (`parameters.angularLegacyRendering` is gone), and Angular <18 is no longer supported (Storybook v9 requires Angular 18+). Closing as out-of-scope; please open a fresh issue with a v10 + Angular 18+ repro if you still see lifecycle issues.
