### ISSUE TITLE
Upgrading from 6.3 to 6.4 crashing when running upgrade command

### ISSUE THREAD

**Issue by samesfahani-tuplehealth** [storybookjs/storybook#16864]
**Describe the bug**
Upgrading from 6.3 to 6.4 crashing when running upgrade command. It correctly bumps version numbers in package.json, but fails during the `🔎 checking 'mainjsFramework'` step.

**To Reproduce**
Reproducing it is going to be a challenge as it's an existing app. I'm hoping the stack trace may shed some light into something obvious.

**System**
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: 6.4.3 => 6.4.3 
    @storybook/addon-links: 6.4.3 => 6.4.3 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-storyshots: 6.4.3 => 6.4.3 
    @storybook/addons: 6.4.3 => 6.4.3 
    @storybook/core: 6.4.3 => 6.4.3 
    @storybook/react: 6.4.3 => 6.4.3 

**Stack trace**
```
$ npx sb@next upgrade                                                                                                                                        1 ✘  40s  02:26:23 PM 
 • Checking for latest versions of '@storybook/*' packagesinfo ,Using yarn
info Upgrading /Users/samesfahani/t/mono/package.json
info 
info  @storybook/addon-actions     6.3.12  →  6.4.3     
info  @storybook/addon-links       6.3.12  →  6.4.3     
info  @storybook/addon-storyshots  6.3.12  →  6.4.3     
info  @storybook/addons            6.3.12  →  6.4.3     
info  @storybook/core              6.3.12  →  6.4.3     
info  @storybook/react             6.3.12  →  6.4.3     
info 
info Run yarn install to install new versions.
info 
info ,npx: installed 249 in 6.149s
info 
info 
 • Installing upgrades • Preparing to install dependencies. ✓


yarn install v1.22.15
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @nestjs/testing@7.6.18" has unmet peer dependency "@nestjs/common@^7.0.0".
warning " > @nestjs/testing@7.6.18" has unmet peer dependency "@nestjs/core@^7.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning " > @storybook/addons@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/addons@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > markdown-to-jsx@7.1.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-actions > @storybook/components > react-colorful@5.5.0" has unmet peer dependency "react@>=16.8.0".
warning "@storybook/addon-actions > @storybook/components > react-colorful@5.5.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@13.5.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize@8.3.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip > react-popper@2.2.5" has unmet peer dependency "react@^16.8.0 || ^17".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-composed-ref@1.1.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest > use-isomorphic-layout-effect@1.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/api@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/api@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-actions > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-links > @storybook/router@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/addons > @storybook/router > react-router@6.0.2" has unmet peer dependency "react@>=16.8".
warning "@storybook/addon-actions > @storybook/addons > @storybook/router > react-router-dom@6.0.2" has unmet peer dependency "react@>=16.8".
warning "@storybook/addon-actions > @storybook/addons > @storybook/router > react-router-dom@6.0.2" has unmet peer dependency "react-dom@>=16.8".
warning "@storybook/addon-storyshots > preact-render-to-string@5.1.19" has unmet peer dependency "preact@>=10".
warning "@storybook/addon-storyshots > react-test-renderer@17.0.2" has unmet peer dependency "react@17.0.2".
warning "@storybook/addon-storyshots > react-test-renderer > react-shallow-renderer@16.14.1" has unmet peer dependency "react@^16.0.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-common@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-common@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/client-api@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/client-api@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/preview-web@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/preview-web@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/react > @storybook/store@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/react > @storybook/store@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > @storybook/core@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/core@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui > downshift@6.1.7" has unmet peer dependency "react@>=16.12.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react@>= 16.3.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react-dom@>= 16.3.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui > react-helmet-async@1.1.2" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core-client > @storybook/ui > react-helmet-async@1.1.2" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server > @storybook/builder-webpack4@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server > @storybook/builder-webpack4@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-storyshots > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > @storybook/react@6.4.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/react@6.4.3" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/react > @storybook/react-docgen-typescript-plugin > react-docgen-typescript@2.1.1" has incorrect peer dependency "typescript@>= 4.3.x".
warning " > @testing-library/react@10.4.9" has unmet peer dependency "react@*".
warning " > @testing-library/react@10.4.9" has unmet peer dependency "react-dom@*".
warning " > @testing-library/react-hooks@3.7.0" has unmet peer dependency "react@>=16.9.0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
warning " > mobx-logger@0.7.1" has unmet peer dependency "mobx@>= 4.0.0".
warning " > pdfjs-dist@2.10.377" has unmet peer dependency "worker-loader@^3.0.7".
warning " > postcss-normalize@10.0.1" has unmet peer dependency "browserslist@>= 4".
warning "postcss-normalize > postcss-browser-comments@4.0.0" has unmet peer dependency "browserslist@>=4".
warning " > react-test-renderer@16.12.0" has unmet peer dependency "react@^16.0.0".
warning "storybook-addon-designs > @figspec/react@1.0.0" has unmet peer dependency "react@^16.14.0 || ^17.0.0".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > @fullcalendar/react@4.4.2" has incorrect peer dependency "react@^16.7.0".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > @fullcalendar/react@4.4.2" has incorrect peer dependency "react-dom@^16.7.0".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > material-ui-nested-menu-item@1.0.2" has unmet peer dependency "@material-ui/core@^4.9.0".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > material-ui-nested-menu-item@1.0.2" has unmet peer dependency "@material-ui/icons@^4.5.1".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > material-ui-nested-menu-item@1.0.2" has unmet peer dependency "clsx@^1.0.4".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > recoil@0.0.10" has incorrect peer dependency "react@^16.13.1".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > recoil@0.0.10" has incorrect peer dependency "react-dom@^16.13.1".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > swr@0.2.3" has incorrect peer dependency "react@^16.11.0".
warning "workspace-aggregator-24223103-b92a-43dc-98a5-b1f1e92fc8f9 > @app/app > use-methods@0.5.1" has incorrect peer dependency "react@^16.8.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 15.86s.
. ✓
WARN Found 4 outdated packages (relative to '@storybook/addon-actions@6.4.3')
WARN Please make sure your packages are updated to ensure a consistent experience.
WARN - @storybook/node-logger@6.3.12
WARN - @storybook/addon-postcss@2.0.0
WARN - @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0
WARN - @storybook/babel-plugin-require-context-hook@1.0.1
🔎 checking 'cra5'
🔎 checking 'webpack5'
🔎 checking 'angular12'
🔎 checking 'mainjsFramework'
(node:9584) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at readFile (fs.js:342:10)
    at go$readFile (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/graceful-fs/graceful-fs.js:118:14)
    at Object.readFile (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/graceful-fs/graceful-fs.js:115:12)
    at /Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at Object.readFile (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/universalify/index.js:7:14)
    at _callee$ (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:355:37)
    at tryCatch (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:60:103)
    at _next (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:62:194)
    at /Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:62:364
    at new Promise (<anonymous>)
    at /Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:62:97
    at readConfig (/Users/samesfahani/.npm/_npx/9584/lib/node_modules/sb/node_modules/@storybook/csf-tools/dist/cjs/ConfigFile.js:370:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.4 containing PR #16866 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
thanks @samesfahani-tuplehealth! 🙏
