### ISSUE TITLE
bunch of ModuleNotFoundError errors when storybook is installed in a separate repository

### ISSUE THREAD

**Issue by gajus** [storybookjs/storybook#16974]
Our project structure:

```
/
/node_modules
/src/
/storybook/node_modules
/storybook/.storybook/main.js
/webpack.config.js
/.babelrc.js
```

`main.js` looks like this:

```

const path = require('path');
const { TsconfigPathsPlugin } = require('tsconfig-paths-webpack-plugin');

module.exports = {
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-controls',
    '@storybook/addon-links',
  ],
  core: {
    builder: 'webpack5',
  },
  features: {
    babelModeV7: true,
  },
  stories: [
    path.resolve(__dirname, '../../src/**/*.stories.mdx'),
    path.resolve(__dirname, '../../src/**/*.stories.@(js|jsx|ts|tsx)')
  ],
  webpackFinal: async (config) => {
    config.resolve.plugins = [
      ...(config.resolve.plugins || []),
      new TsconfigPathsPlugin({
        baseUrl: path.resolve(__dirname, '../../src'),
        configFile: path.resolve(__dirname, '../../tsconfig.json'),
      }),
    ];

    config.module.rules[0].use[0].options.cwd = path.resolve(__dirname, '../..');

    return config
  },
};
```

This setup produces a ton of errors:

```
ModuleNotFoundError: Module not found: Error: Can't resolve '../src/theme' in '/Users/gajus/Documents/dev/contra/contra-web-app/storybook/.storybook'
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/neo-async/async.js:6883:13
    at Array.<anonymous> (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:947:14)
    at arrayEachFunc (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/neo-async/async.js:2517:19)
    at Object.parallel (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/neo-async/async.js:6858:9)
    at NormalModuleFactory._resolveResourceErrorHints (/Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:870:12)
    at /Users/gajus/Documents/dev/contra/contra-web-app/storybook/node_modules/webpack/lib/NormalModuleFactory.js:831:18
resolve '../src/theme' in '/Users/gajus/Documents/dev/contra/contra-web-app/storybook/.storybook'
  using description file: /Users/gajus/Documents/dev/contra/contra-web-app/storybook/package.json (relative path: ./.storybook)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/gajus/Documents/dev/contra/contra-web-app/storybook/package.json (relative path: ./src/theme)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.jsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.tsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.json doesn't exist
      .cjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme.cjs doesn't exist
      as directory
        /Users/gajus/Documents/dev/contra/contra-web-app/storybook/src/theme doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

We are trying to avoid installing Storybook along with the main application.

**Comment by gajus** [comment]
Turned out to be a bug in a relay Babel plugin.
