### ISSUE TITLE
Storybook won’t read my custom webpack configuration

### ISSUE THREAD

**Issue by Haraldson** [storybookjs/storybook#17118]
**Describe the bug**
I am unable to get Storybook to read my webpack configuration, which is needed in order to load `react-dom` from `@hot-loader/react-dom`, among other things.

**To Reproduce**
I am unable to make a repro, as I’m trying to implement Storybook into an existing and rather large closed-source project.
The way I went about this was

1. `yarn add storybook`
1. Manually used the `init` subcommand which did its thing, detected React and installed corresponding plugins etc.
1. Enriched `.storybook/main.js`:
    ```javascript
    webpackFinal: async config => {
        config.resolve.alias = {
            ...config.resolve.alias,
            'react-dom': '@hot-loader/react-dom',
            package: `${__dirname}/package.json`
        }
    
        return config
    }
    ```

1. I’ve also added a `.storybook/babel.config.js` just in case:
    ```javascript
    module.exports = {
        rootMode: 'upward'
    }
    ```

1. The end result is that my configuration isn’t read/used, as far as I can understand. The `--debug-webpack` flag does nothing. 

My current theory is that React/framework specific dependencies are attempted loaded _before_ the custom webpack configuration, which in my case won’t work, as I’m using `@hot-loader/react-dom` in `react-dom`’s place, for instance.

<details>
<summary>Output:</summary>

```shell
➜ yarn storybook --debug-webpack
yarn run v1.22.10
$ start-storybook -p 6006 --debug-webpack
info @storybook/react v6.4.9
info 
info => Loading presets
WARN   Failed to load preset: "/Users/hein/www/project/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js"
ERR! Error: Cannot find module 'react-dom/package.json'
ERR! Require stack:
ERR! - /Users/hein/www/project/node_modules/@storybook/ui/noop.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at resolveFileName (/Users/hein/www/project/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/Users/hein/www/project/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/Users/hein/www/project/node_modules/resolve-from/index.js:46:47)
ERR!     at Object.<anonymous> (/Users/hein/www/project/node_modules/@storybook/ui/paths.js:18:24)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Users/hein/www/project/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js:63:38)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!  Error: Cannot find module 'react-dom/package.json'
ERR! Require stack:
ERR! - /Users/hein/www/project/node_modules/@storybook/ui/noop.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at resolveFileName (/Users/hein/www/project/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/Users/hein/www/project/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/Users/hein/www/project/node_modules/resolve-from/index.js:46:47)
ERR!     at Object.<anonymous> (/Users/hein/www/project/node_modules/@storybook/ui/paths.js:18:24)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/Users/hein/www/project/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js:63:38)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [ '/Users/hein/www/project/node_modules/@storybook/ui/noop.js' ]
ERR! }
info => Loading custom babel config as JS
ERR! Error: Cannot find module 'react-dom/package.json'
ERR! Require stack:
ERR! - /Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js
ERR! - /Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/presets/preview-preset.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core/server.js
ERR! - /Users/hein/www/project/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at _default (/Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:199:52)
ERR!     at async storybookDevServer (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:109:58)
ERR!     at async buildDevStandalone (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: Cannot find module 'react-dom/package.json'
ERR! Require stack:
ERR! - /Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js
ERR! - /Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/presets/preview-preset.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/presets.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/hein/www/project/node_modules/@storybook/core/server.js
ERR! - /Users/hein/www/project/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - /Users/hein/www/project/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at _default (/Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:199:52)
ERR!     at async storybookDevServer (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:109:58)
ERR!     at async buildDevStandalone (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/builder-webpack4/dist/cjs/presets/preview-preset.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/presets.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/core-common/dist/cjs/index.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/core/server.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/react/dist/cjs/server/index.js',
ERR!     '/Users/hein/www/project/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```
</details>

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.yvm/shim/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 92.0
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9 
    @storybook/addon-essentials: ^6.4.9 => 6.4.9 
    @storybook/addon-links: ^6.4.9 => 6.4.9 
    @storybook/react: ^6.4.9 => 6.4.9 
```

**Additional context**
Came here after being encouraged by @shilman in this [twitter thread](https://twitter.com/mshilman/status/1478028496526278657).

**Comment by shilman** [comment]
Hi @Haraldson, thanks for the thorough report. As far as I can tell, this is the problem: https://github.com/storybookjs/storybook/blob/next/lib/builder-webpack4/src/preview/iframe-webpack.config.ts#L240

This line is is setting up Storybook's `react-dom` in node. Your code is trying to override this. However, this code is crashing, so it doesn't even get that far, and therefore can't even configure webpack.

Are you doing some yarn magic whereby `react-dom` doesn't even get installed? If so, could you try to disable that for debugging purposes?

**Comment by Haraldson** [comment]
Hi again @shilman! The vanilla `react-dom` isn’t installed, and I’m relying on Webpack’s `resolve.alias` to redirect references to the overridden `@hot-loader` version of it as shown in the Webpack override example.

Am I to understand your reply as it not being possible to _first_ read the Webpack configuration, and _then_ load dependencies based on what’s in it? If so – is it possible to give Storybook its own, more locally scoped, dependencies? I’m thinking of a `package.json` and `node_modules` within the `.storybook` folder – is that something that would work, or does everything have to use the same root `package.json` and its dependencies?

**Comment by Haraldson** [comment]
I got this up and running using a package.json alias. Perhaps this should be documented as a known gotcha? I would‘ve expected Webpack overrides to be loaded before dependencies, as Webpack can directly impact how dependencies are loaded and from where.

**Comment by shilman** [comment]
Hi @Haraldson Sorry, this got lost in a flood of holiday notifications and I'm still catching up. I'd welcome a PR if you want to document this. However I suspect this as an advanced use case that might be better served by your writeup here.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
