### ISSUE TITLE
TypeError: element.className.split is not a function

### ISSUE THREAD

**Issue by AlexanderKaran** [storybookjs/storybook#17126]
**Describe the bug**
After upgrading our CRA to the latest version and updating Storybook to work with Webpack five a lot of stories are no longer building and we get the following error:

```
Error: Evaluation failed: TypeError: element.className.split is not a function
    at rewriteStyleSheets (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2884004)
    at Object.<anonymous> (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2886526)
    at https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:393162
    at Array.forEach (<anonymous>)
    at Channel.handleEvent (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:393137)
    at handler (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:391844)
    at Channel.emit (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:391899)
    at https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:523613
    at _callee12$ (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:521673)
    at tryCatch (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2807089)
    at ExecutionContext._evaluateInternal (/var/task/capture-v3/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:218:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/var/task/capture-v3/build/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)
    at async /var/task/capture-v3/build/bundle.js:614897:7
    at async NavigatorWatcher2.waitForIdle (/var/task/capture-v3/build/bundle.js:608234:9)
    at async PuppeteerRenderer.renderSpec (/var/task/capture-v3/build/bundle.js:614860:25)
    at async PuppeteerRenderer.renderSnapshot (/var/task/capture-v3/build/bundle.js:614763:21)
    at async PuppeteerRenderer.captureSpecs (/var/task/capture-v3/build/bundle.js:614712:18)
    at async PuppeteerRenderer.executeWithCallback (/var/task/capture-v3/build/bundle.js:614952:14)
Metadata
{
  "stack": "<stack trace above>",
  "name": "Error",
  "message": "Evaluation failed: TypeError: element.className.split is not a function\n    at rewriteStyleSheets (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2884004)\n    at Object. (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2886526)\n    at https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:393162\n    at Array.forEach ()\n    at Channel.handleEvent (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:393137)\n    at handler (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:391844)\n    at Channel.emit (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:391899)\n    at https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:523613\n    at _callee12$ (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:521673)\n    at tryCatch (https://6124ac6f27789e003a225658-nywihedjna.chromatic.com/892.58fbb12a.iframe.bundle.js:2:2807089)"
}
```

We are using Emotion but the components work fine in the app and also work fine when the app is built too

**To Reproduce**
Upgrade to React Scripts 5 and update Storybook

**System**
```
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: 96.0.1054.62
    Firefox: 91.0.1
    Safari: 15.2
  npmPackages:
    @storybook/addon-a11y: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/addon-actions: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-essentials: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/addon-links: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/builder-webpack5: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/manager-webpack5: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/node-logger: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.5.0-alpha.6 => 6.5.0-alpha.7 
    @storybook/testing-react: ^1.2.2 => 1.2.2 
```

**Comment by AlexanderKaran** [comment]
Digging further into this issue and it seems to be on any component that has an SVG in it. So maybe it is something to do with emotion and storybook

**Comment by AlexanderKaran** [comment]
Can confirm SVG work perfectly in dev and production for the app it is only in Storybook where they die

**Comment by AlexanderKaran** [comment]
Add the following to main.js does nothing:

```
features: {
 	emotionAlias: false,
 },
```

Adding the following make it initial load but the second you click the story then the error comes back

```
	webpackFinal: async (config) => {
		return {
			...config,
			resolve: {
				...config.resolve,
				alias: {
					...config.resolve.alias,
					"@emotion/core": toPath("node_modules/@emotion/react"),
					// You should add this row
					"@emotion/styled": toPath("node_modules/@emotion/styled"),
					"emotion-theming": toPath("node_modules/@emotion/react"),
				},
			},
		};
	},
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by AlexanderKaran** [comment]
Every time I try to make one it fails not sure why. Would it help to make our Storybook in Chromatic public for a while, more than happy to also upload a striped down version of the code here to as well

**Comment by AlexanderKaran** [comment]
Here is a clone 
[clone.zip](https://github.com/storybookjs/storybook/files/7818656/clone.zip)

npm install 

Then you can run the storybook with npm run storybook which I have added one story in so you can see the issue

You can also use npm run school-app to see the component then work fine in the app

**Comment by shilman** [comment]
It looks like the error is coming from `storybook-addon-pseudo-states`... that doesn't mean that it's a bug in the addon, but I would start there. If I remove the addon it fixes the problem

**Comment by AlexanderKaran** [comment]
Thank you so much. Completely forgot to check the add ons, feel so stupid ha
