### ISSUE TITLE
Adding storybook to vue3/tailwind/typescript project won't start

### ISSUE THREAD

**Issue by paltman** [storybookjs/storybook#17169]
**Describe the bug**
Following the instructions to add storybook to my Vue3/Tailwind/Typescript project, I get errors when trying to start up storybook.

**To Reproduce**
`npx sb init`
`yarn storybook`

I don't think the `sb repro` applies here because this seems to be an issue with the startup, not how it runs.

**System**
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/paltman/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/Users/paltman/.nvm/versions/node/v14.17.5/bin/node" "/Users/paltman/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paltman/.npm/_npx/5429/lib/node_modules/sb/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.15 - ~/Development/[redacted]/node_modules/.bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.9
    @storybook/addon-essentials: ^6.4.9 => 6.4.9
    @storybook/addon-links: ^6.4.9 => 6.4.9
    @storybook/vue3: ^6.4.9 => 6.4.9
```

**Additional context**

```
% yarn storybook
yarn run v1.22.11
$ start-storybook -p 6006
info @storybook/vue3 v6.4.9
info
info => Loading presets
info => Using implicit CSS loaders
info => Using prebuilt manager
info => Using default Webpack4 setup
ERR! TypeError: Cannot read property 'NormalModule' of undefined
ERR!     at VueLoaderPlugin.apply (/Users/paltman/Development/[redacted]/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at Object.start (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError: Cannot read property 'NormalModule' of undefined
ERR!     at VueLoaderPlugin.apply (/Users/paltman/Development/[redacted]/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at Object.start (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jonniebigodes** [comment]
@paltman thanks for reaching out to us with your issue, before mentioning the steps i took to triage the issue, I want to ask you which instructions are you referring when adding Storybook? 

- Created a new Vue 3 project  using `vue create` 
- Configured the project to enable TypeScript support
- Added Storybook by running `npx sb init`
- Installed Tailwind and necessary dependencies with `yarn add -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9`. The versions of `postcss` and `autoprefixer` were necessary to make this work, as I wasn't able to run Storybook with the latest versions.
- Created a `tailwind.config.js` with the following inside to enable Vue support, as per the official instructions.
```js
// tailwind.config.js
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  purge: [
    "./layouts/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```
- Created a `postcss.config.js` file with the following inside:
```js
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```
- Installed [@storybook/addon-postcss](https://storybook.js.org/addons/@storybook/addon-postcss) and configured it in my `.storybook/main.js` as such:
```js
// .storybook/main.js
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-postcss", // addon postcss added
  ],
  framework: "@storybook/vue3",
};
```
- Created a `index.css` file under the `src` directory with the following and imported it in my `.storybook/preview.js`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
```js
// .storybook/preview.js

import "../src/index.css";
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

```

- Created a small component and  to test it with the following code:
```html
<!-- src/components/SampleComponent.vue -->

<template>
  <div class="border-8 border-red-800">
    <h1>Example component with VUE 3 and TS AND TAILWIND</h1>
    <p class="text-3xl font-bold underline">
      someProp has value of{{ someProp }}
    </p>
    <p class="text-3xl font-bold underline">
      otherProp has value of{{ otherProp }}
    </p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    someProp: {
      type: String,
      default: "Something value",
    },
    otherProp: {
      type: Number,
      default: 33,
    },
  },
});
</script>

<style></style>
```

```js
// src/components/SampleComponent.stories.js

import SampleComponent from "./SampleComponent.vue";

export default {
  comopnent: SampleComponent,
  title: "SampleComponent",
};

const Template = (args) => ({
  components: { SampleComponent },
  setup() {
    return { args };
  },
  template: '<SampleComponent v-bind="args" />',
});

export const Default = Template.bind({});
Default.args = {
  someProp: "some example value",
  otherProp: 32,
};
```
- Started Storybook and i'm presented with:
<img width="1440" alt="Vue_3_tailwind_ts_storybook_running" src="https://user-images.githubusercontent.com/22988955/149416177-7df0f0b5-4048-4ee1-8597-11bdbb0db183.png">

Sorry for the styling, it was created as an example for demonstration purposes.

Let me know if you want to me to push this to a repo so that you can look at it and compare it with your own code.

In the meantime I'm going to test this a bit more with the latest versions of PostCSS and Tailwind and see if I missed any configuration.

Let us know of any feedback so that we can close this issue, or continue working on it until we find a suitable solution.

Have a great day.

Stay safe

**Comment by paltman** [comment]
Thanks for this.  I've made the adjustments per your steps but still getting same results:

```
 % yarn storybook
yarn run v1.22.11
$ start-storybook -p 6006
info @storybook/vue3 v6.4.9
info 
info => Loading presets
info => Using PostCSS preset with postcss@7.0.39
info => Using default Webpack4 setup
ERR! TypeError: Cannot read property 'NormalModule' of undefined
ERR!     at VueLoaderPlugin.apply (/Users/paltman/Development/[redacted]/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at Object.start (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError: Cannot read property 'NormalModule' of undefined
ERR!     at VueLoaderPlugin.apply (/Users/paltman/Development/[redacted]/node_modules/vue-loader/dist/pluginWebpack5.js:44:47)
ERR!     at webpack (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at Object.start (/Users/paltman/Development/[redacted]/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:92:18)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/paltman/Development/[redacted]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
```

I am not using a vue-cli created project but one that i setup myself that integrates with my Django backend and have my own webpack.config.js at the project level that builds my project.  i have renamed that to just take it out of contention.

I am using webpack v5 though and i see the output talking about v4 and wonder if i have some version conflict causing that `NormalModule` error.

Here is my package.json requirements if helpful:

```json
{
  "main": "index.js",
  "scripts": {
    "start": "HOT_RELOAD=1 webpack serve --mode development",
    "build": "NODE_ENV=production webpack --mode production",
    "lint": "eslint --ext js --ext ts --ext vue static/src/js",
    "test": "vue-cli-service test:unit --maxWorkers=1",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "private": true,
  "engines": {
    "node": "14.17"
  },
  "dependencies": {
    "@apollo/client": "^3.4.16",
    "@fontsource/inter": "^4.5.0",
    "@headlessui/vue": "^1.4.1",
    "@heroicons/vue": "^1.0.4",
    "@sentry/tracing": "^6.12.0",
    "@sentry/vue": "^6.12.0",
    "@tailwindcss/forms": "^0.3.4",
    "@vue/apollo-composable": "^4.0.0-alpha.14",
    "@vue/apollo-option": "^4.0.0-alpha.14",
    "@vuelidate/core": "^2.0.0-alpha.28",
    "@vuelidate/validators": "^2.0.0-alpha.23",
    "chart.js": "^3.5.1",
    "graphql": "15.6.0",
    "libphonenumber-js": "^1.9.39",
    "mixpanel-browser": "^2.41.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat",
    "vue": "^3.2.19",
    "vue-gtag-next": "^1.14.0",
    "vue-inline-svg": "^3.1.0",
    "vue-meta": "^3.0.0-alpha.9",
    "vue-router": "4",
    "vuelidate": "^0.7.6",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@popperjs/core": "^2.10.2",
    "@sentry/webpack-plugin": "^1.17.2",
    "@storybook/addon-actions": "^6.4.9",
    "@storybook/addon-essentials": "^6.4.9",
    "@storybook/addon-links": "^6.4.9",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/vue3": "^6.4.9",
    "@types/jest": "^27.0.2",
    "@types/mixpanel-browser": "^2.35.7",
    "@types/webpack-env": "^1.16.2",
    "@typescript-eslint/eslint-plugin": "^4.33.0",
    "@typescript-eslint/parser": "^4.33.0",
    "@vue/cli-plugin-babel": "^4.5.13",
    "@vue/cli-plugin-unit-jest": "^5.0.0-beta.4",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.2.19",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-rc.15",
    "@vue/vue3-jest": "^27.0.0-alpha.1",
    "apollo": "^2.33.6",
    "autoprefixer": "^9",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^4.0.0",
    "copy-webpack-plugin": "^9.0.1",
    "css-loader": "^6.2.0",
    "css-minimizer-webpack-plugin": "^3.1.0",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-import-resolver-webpack": "^0.13.1",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-vue": "^7.19.0",
    "file-loader": "^6.2.0",
    "fork-ts-checker-webpack-plugin": "^6.3.3",
    "imports-loader": "^3.0.0",
    "jest": "^27.2.4",
    "jest-transform-graphql": "^2.1.0",
    "mini-css-extract-plugin": "^2.3.0",
    "postcss": "^7",
    "postcss-loader": "^6.1.1",
    "sass": "^1.42.1",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "terser-webpack-plugin": "^5.2.4",
    "ts-jest": "^27.0.5",
    "ts-loader": "^9.2.6",
    "typescript": "^4.4.3",
    "vue-loader": "^16.8.3",
    "vue-style-loader": "^4.1.2",
    "webpack": "^5.56.1",
    "webpack-bundle-analyzer": "^4.4.2",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.3.1",
    "webpack-manifest-plugin": "^4.0.2"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "jest": {
    "preset": "@vue/cli-plugin-unit-jest",
    "transform": {
      "\\.(gql|graphql)$": "jest-transform-graphql",
      "^.+\\.ts$": "ts-jest",
      "^.+\\.vue$": "@vue/vue3-jest"
    },
    "clearMocks": true,
    "transformIgnorePatterns": [
      "/node_modules/(?!@babel)"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "static/src/js/**/*.{js,ts,vue}",
      "!**/node_modules/**",
      "!**/__generated__/**"
    ],
    "coverageReporters": [
      "json",
      "html",
      "text-summary"
    ],
    "coverageDirectory": "./js-coverage",
    "moduleNameMapper": {
      "^@/(.*)$": "<rootDir>/static/src/$1"
    },
    "moduleFileExtensions": [
      "js",
      "vue",
      "ts"
    ]
  }
}
```

**Comment by ranjanngc** [comment]
This error comes when you use webpack 5 with vue CLI. This seems a bug in storybook js

**Comment by jonniebigodes** [comment]
@paltman sorry for the delayed response on this issue, but I appreciate the follow-up nonetheless; one thing you've mentioned piqued my curiosity; in your comment, you're mentioning that you're using webpack 5 with a custom implementation, correct? And looking at your package.json, it seems that when you spun up Storybook into your project, you probably ran `npx sb init`, and during the install process, it installed and configured itself for Webpack 4. This is based on the following missing dependencies `@storybook/builder-webpack5` and `@storybook/manager-webpack5`. With that in mind, could you add them to your development dependencies and update your `.storybook/main.js` to the following so that it can pick up on webpack 5:

```js

// .storybook/main.js
module.exports = {
  stories: ["you-stories-go-here],
  addons: ["your-addons-go here"],
  framework: "@storybook/vue3", 
  core: {
    builder: "webpack5", //This will tell Storybook to use Webpack 5
  },
};

```

What I would like for you to do is a test on your end with the steps I've mentioned and report back so that we can close this issue, or continue to work on it until we find a suitable solution.



@ranjanngc doing a bit of digging it seems that Webpack 5 was added quite recently to the Vue CLI, probably during the shift from Vue 2 to Vue 3 becoming the default framework version. And with the Storybook CLI might not pick it up correctly, but at least you can circumvent it by adding the packages I've mentioned manually to an existing project. Or if you're adding Storybook to a Vue project you can add set it up with Webpack 5 support by running the following install command `npx sb init --builder webpack5` . This will automatically add in the necessary dependencies and configures Storybook for Webpack 5.

**Comment by paltman** [comment]
Thanks!

I'm off and running now.  Was able to get things working with PostCSS v8 and autoprefixer v10.

### `.storybook/main.js`

```javascript
module.exports = {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
          postcssOptions: {
            plugins: [
              require('tailwindcss')(),
              require('autoprefixer')(),
            ],
          },
        },
      },
    },
  ],
  framework: '@storybook/vue3',
  core: {
    builder: 'webpack5',
  },
}
```

### `babel.config.js`

Needed to do this to silence some warnings.

```javascript
{
  presets: [
    '@vue/cli-plugin-babel/preset',
  ],
  plugins: [
    [
      '@babel/plugin-proposal-private-property-in-object',
      {
        loose: true,
      },
    ],
    [
      '@babel/plugin-proposal-class-properties',
      {
        loose: true,
      },
    ],
    [
      '@babel/plugin-proposal-private-methods',
      {
        loose: true,
      },
    ],
  ],
};
```

Appreciate all your help!

**Comment by jonniebigodes** [comment]
That's great to hear @paltman ! Glad that you managed to solve your issue. Sorry about the delayed response on this 🙏 !

Hope you have a great day!

Stay safe

**Comment by MisterNox** [comment]
Thanks, it helped me as well.

I would suggest to add `npx sb init --type vue3 --builder webpack5` to the docs (at least in the troubleshot section) in order to help people to check if their problem is just webpack related for vue3.

Thanks again.
