### ISSUE TITLE
Storyshots integration with Next TypeScript app fails with "Cannot read properties of undefined (reading 'addEventListener')" error

### ISSUE THREAD

**Issue by ashwanth1109** [storybookjs/storybook#17219]
**Describe the bug**
I'm facing an issue when I try to integrate storyshots with nextjs.

You can find the issue reproduced here:
https://github.com/ashwanth1109/next-story-shots

**To Reproduce**
- Clone the repo from https://github.com/ashwanth1109/next-story-shots
- Run `npm i && npm test`

**Additional context**
The error is as follows:
```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\yarn\bin\yarn.js" test
yarn run v1.22.15
$ jest
ts-jest[main] (WARN) Replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.j
s" in the 'transform' section of your Jest config with just "ts-jest".
 FAIL  test/stories.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'addEventListener')

      at new PostmsgTransport (node_modules/@storybook/channel-postmessage/dist/cjs/index.js:135:18)
      at createChannel (node_modules/@storybook/channel-postmessage/dist/cjs/index.js:409:19)
      at start (node_modules/@storybook/core-client/dist/cjs/preview/start.js:95:49)
      at Object.<anonymous> (node_modules/@storybook/react/dist/cjs/client/preview/index.js:18:29)
      at Object.<anonymous> (node_modules/@storybook/react/dist/cjs/client/index.js:69:16)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/react/loader.js:23:26)
      at Object.loadFramework [as default] (node_modules/@storybook/addon-storyshots/dist/ts3.9/frameworks/frameworkLoader.js:26:
19)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:42:39)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.729 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

Kindly help with understanding why this happens

**Comment by ashwanth1109** [comment]
Never mind, I've managed to resolve the issue. I needed to configure jest-dom to get it to work. I've pushed the fix to my repository in case anyone else runs into a similar issue:
https://github.com/ashwanth1109/next-story-shots

## Fix:


- Add `@testing-library/jest-dom` as a dev dependency.
```sh
npm i -D @testing-library/jest-dom
```

- Create a `jest.config.js` file in the root of your repository.
```js
const nextJest = require('next/jest')

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    // Handle module aliases (this will be automatically configured for you soon)
    '^@/components/(.*)$': '<rootDir>/components/$1',

    '^@/pages/(.*)$': '<rootDir>/pages/$1',
  },
  testEnvironment: 'jest-environment-jsdom',
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
module.exports = createJestConfig(customJestConfig)
```

- Create a `jest.setup.js` file in the root of your repository.
```js
// Optional: configure or set up a testing framework before each test.
// If you delete this file, remove `setupFilesAfterEnv` from `jest.config.js`

// Used for __tests__/testing-library.js
// Learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom/extend-expect'
```
