### ISSUE TITLE
Storybook/addon-a11y shows Unhandled Promise rejection: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function in Angular Storybook

### ISSUE THREAD

**Issue by railsstudent** [storybookjs/storybook#17210]
**Describe the bug**
Install add-a11y to Angular storybook and run storybook.  Accessibility tab displays but "Initializaing...." loading message displays.
When I open dev console of chrome, this is the error trace:

Storybook/addon-a11y shows Unhandled Promise rejection: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function

zone.js:1102 Unhandled Promise rejection: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function
    at _callee3$ (a11yRunner.js:161:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (a11yRunner.js:5:1)
    at _next (a11yRunner.js:7:1)
    at a11yRunner.js:7:1
    at new ZoneAwarePromise (zone.js:1340:1)
    at a11yRunner.js:7:1
    at getParams (a11yRunner.js:194:1) TypeError: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function
    at _callee3$ (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90757:59)
    at tryCatch (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:194739:40)
    at Generator.invoke [as _invoke] (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:194970:22)
    at Generator.next (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:194795:21)
    at asyncGeneratorStep (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90601:103)
    at _next (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90603:194)
    at http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90603:364
    at new ZoneAwarePromise (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:212888:33)
    at http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90603:97
    at getParams (http://localhost:6006/vendors-node_modules_angular_common___ivy_ngcc___fesm2015_http_js-node_modules_fortawesome_an-514ab4.iframe.bundle.js:90790:18)

**To Reproduce**
https://github.com/railsstudent/ng-spanish-menu/tree/storybook-a11y
Check out the branch and run npm run storybook to launch the standalone app

**System**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
  Binaries:
    Node: 14.18.2 - ~/.volta/tools/image/node/14.18.2/bin/node
    npm: 7.24.2 - ~/.volta/tools/image/npm/7.24.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.0
  npmPackages:
    @storybook/addon-a11y: ^6.4.12 => 6.4.12 
    @storybook/addon-actions: 6.3.12 => 6.3.12 
    @storybook/addon-docs: 6.3.12 => 6.3.12 
    @storybook/addon-essentials: 6.3.12 => 6.3.12 
    @storybook/addon-links: 6.3.12 => 6.3.12 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/angular: 6.3.12 => 6.3.12 
    @storybook/builder-webpack5: 6.3.12 => 6.3.12 
    @storybook/manager-webpack5: 6.3.12 => 6.3.12 

**Additional context**

**Comment by shilman** [comment]
All of your storybook package versions should match.

You can do this automatically (recommended) by:
- stable: `npx sb upgrade`
- prerelease: `npx sb upgrade --prerelease`

Closing this for now. Please let me know if there's more to be done here!

**Comment by PeteJStewart** [comment]
I'm also getting this issue, and it's not resolved by running `npx sb upgrade`

I'm running storybook with nuxt, but otherwise there's nothing particularly unusual going on.

Here are the relevant packages I'm using.

```json
"@nuxtjs/storybook": "^4.2.0",
"@storybook/addon-a11y": "^6.4.17",
"@storybook/addon-actions": "^6.4.17",
"@storybook/addon-docs": "^6.4.17",
"@storybook/addon-essentials": "^6.4.17",
"@storybook/addon-links": "^6.4.17",
"@storybook/vue": "^6.4.17",
"storybook-addon-designs": "^6.2.1",
```

And here's the error I'm seeing in the console

```
Uncaught (in promise) TypeError: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function
    at _callee3$ (a11yRunner.js:161:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (a11yRunner.js:5:1)
    at _next (a11yRunner.js:7:1)
    at a11yRunner.js:7:1
    at new Promise (<anonymous>)
    at a11yRunner.js:7:1
    at getParams (a11yRunner.js:194:1)
```

The error is shown to be due to `a11yRunner.js:161` and for me, the Accessibility tab just says 'initializing...'

Any ideas?

**Comment by ju-Skinner** [comment]
> I'm also getting this issue, and it's not resolved by running `npx sb upgrade`
> 
> I'm running storybook with nuxt, but otherwise there's nothing particularly unusual going on.
> 
> Here are the relevant packages I'm using.
> 
> ```json
> "@nuxtjs/storybook": "^4.2.0",
> "@storybook/addon-a11y": "^6.4.17",
> "@storybook/addon-actions": "^6.4.17",
> "@storybook/addon-docs": "^6.4.17",
> "@storybook/addon-essentials": "^6.4.17",
> "@storybook/addon-links": "^6.4.17",
> "@storybook/vue": "^6.4.17",
> "storybook-addon-designs": "^6.2.1",
> ```
> 
> And here's the error I'm seeing in the console
> 
> ```
> Uncaught (in promise) TypeError: globalWindow.__STORYBOOK_STORY_STORE__.loadStory is not a function
>     at _callee3$ (a11yRunner.js:161:1)
>     at tryCatch (runtime.js:63:1)
>     at Generator.invoke [as _invoke] (runtime.js:294:1)
>     at Generator.next (runtime.js:119:1)
>     at asyncGeneratorStep (a11yRunner.js:5:1)
>     at _next (a11yRunner.js:7:1)
>     at a11yRunner.js:7:1
>     at new Promise (<anonymous>)
>     at a11yRunner.js:7:1
>     at getParams (a11yRunner.js:194:1)
> ```
> 
> The error is shown to be due to `a11yRunner.js:161` and for me, the Accessibility tab just says 'initializing...'
> 
> Any ideas?

I ran into this issue as well. I ran this command `npx sb@latest upgrade`. which solved it. Most people have suggesting running `npx sb upradge`, but that had no affect for me. Let me know if that helps with your issue
