### ISSUE TITLE
Build-storybook on CRA: TypeError MiniCssExtractPlugin is not a constructor

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17246]
On latest version of Storybook with CRA:

```
$ npx sb@next repro -t cra cra-repro-next
$ cd cra-repro-next && yarn build-storybook

ERR! TypeError: MiniCssExtractPlugin is not a constructor
ERR!     at module.exports (/Users/shilman/projects/testing/cra-repro-next/node_modules/react-scripts/config/webpack.config.js:664:9)
ERR!     at Object.webpack (/Users/shilman/projects/testing/cra-repro-next/node_modules/@storybook/preset-create-react-app/dist/index.js:115:57)
ERR!     at /Users/shilman/projects/testing/cra-repro-next/node_modules/@storybook/core-common/dist/cjs/presets.js:279:28
ERR!     at async Object.build (/Users/shilman/projects/testing/cra-repro-next/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:165:16)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (/Users/shilman/projects/testing/cra-repro-next/node_modules/@storybook/core-server/dist/cjs/build-static.js:175:28)
ERR!     at async buildStatic (/Users/shilman/projects/testing/cra-repro-next/node_modules/@storybook/core-server/dist/cjs/build-static.js:195:5)
```

**Comment by benjaminpapillault-maif** [comment]
https://github.com/facebook/create-react-app/issues/11930

**Comment by ImNM** [comment]
@benjaminpapillault-maif  thank you

**Comment by valentinpalkovic** [comment]
Closing as obsolete. The `build-storybook` binary was removed in 7.0 (replaced by `storybook build`), CRA4 support was dropped at the same time, and CRA itself was deprecated by the React team in 2025. The crash is inside `react-scripts/config/webpack.config.js` which is no longer part of any supported Storybook path. We now recommend `@storybook/react-vite` for CRA projects.
