### ISSUE TITLE
[6.4.16] Error building angular storybook (ERR_REQUIRE_ESM)

### ISSUE THREAD

**Issue by DavidDudson** [storybookjs/storybook#17371]
**Describe the bug**

Both `start-storybook` and `build-storybook` fail with:

```
info @storybook/angular v6.4.16
info
info => Cleaning outputDir: /Users/XXX/repos/XXX/storybook-static
info => Loading presets
info => Compiling manager..
info => Compiling preview..
info => Using implicit CSS loaders
ERR! Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/XXX/repos/XXX/node_modules/@angular/core/fesm2015/core.mjs not supported.
ERR! Instead change the require of /Users/XXX/repos/XXX/node_modules/@angular/core/fesm2015/core.mjs to a dynamic import() which is available in all CommonJS modules.
ERR!     at /Users/XXX/repos/XXX/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-cli.js:99:99
ERR!  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/XXX/repos/XXX/node_modules/@angular/core/fesm2015/core.mjs not supported.
ERR! Instead change the require of /Users/XXX/repos/XXX/node_modules/@angular/core/fesm2015/core.mjs to a dynamic import() which is available in all CommonJS modules.
ERR!     at /Users/XXX/repos/XXX/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-cli.js:99:99 {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
error Command failed with exit code 1.
```

Note: Everything builds fine in 6.4.15

**System**
```
Environment Info:

  System:
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 93.0
    Safari: 15.3
  npmPackages:
    @storybook/addon-a11y: ^6.4.16 => 6.4.16
    @storybook/addon-actions: ^6.4.16 => 6.4.16
    @storybook/addon-essentials: ^6.4.16 => 6.4.16
    @storybook/addon-links: ^6.4.16 => 6.4.16
    @storybook/angular: ^6.4.16 => 6.4.16
    @storybook/builder-webpack5: ^6.4.16 => 6.4.16
    @storybook/manager-webpack5: ^6.4.16 => 6.4.16
```

**Additional context**
Typescript version is 4.5.5
Angular is 13.1.X

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.17 containing PR #17372 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.29 containing PR #17372 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by DavidDudson** [comment]
@shilman Thankyou very much for the quick fix. I've updated to 6.4.17 and it works perfectly.
