### ISSUE TITLE
`babelModeV7` should use `babel.config.json` at monorepo root

### ISSUE THREAD

**Issue by aaronadamsCA** [storybookjs/storybook#17398]
(Note this is now a bug report, not a feature request.)

**Is your feature request related to a problem? Please describe**
I've implemented Storybook at `/packages/ui/.storybook` in a monorepo, and it took me a while to realize `babelModeV7` doesn't use `/babel.config.json` at the monorepo root.

This causes strange failures, like TypeScript files failing due to Flow parse errors.

**Describe the solution you'd like**
- Make Storybook use the monorepo Babel config.
- Consider failing if no Babel config is found, rather than using a strange default that is completely different from v6 behaviour.

**Describe alternatives you've considered**
Creating a local `.babelrc.json` does not work, because it does not apply to files in other packages, which are then parsed using a weird partial config coming from somewhere inside Storybook.

**Are you able to assist to bring the feature to reality?**
Possibly?

**Additional context**
Disabling `babelModeV7` works around the issue for now, but given it becomes the standard in v7, and given the stated intent is for Storybook to use our project's Babel config, I'd like to figure out how to help make this happen.

**Reproduction**
https://github.com/aaronadamsCA/storybook-issue-17398

Try running Storybook in `packages/ui/` and it will fail with parse errors:

<details>

```
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /workspaces/storybook-babel-issue/packages/ui/src/ButtonStack/ButtonStack.stories.tsx: Missing semicolon. (6:50)

  4 | import { ButtonStack as Component } from "./ButtonStack";
  5 |
> 6 | const VARIANTS = ["contained", "outlined", "text"] as const;
    |                                                   ^
  7 |
  8 | const meta: ComponentMeta<typeof Component> = {
  9 |   component: Component,
    at instantiate (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
    at toParseError (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error.js:58:12)
    at Object.raise (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
    at Object.semicolon (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/util.js:146:10)
    at Object.parseVarStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:904:10)
    at Object.parseStatementContent (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:391:21)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:329:17)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:1926:26)
    at Object.parseBlockOrModuleBlockBody (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:1082:25)
    at Object.parseBlockBody (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:1058:10)
    at processResult (/workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:758:19)
    at /workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:860:5
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /workspaces/storybook-babel-issue/node_modules/babel-loader/lib/index.js:59:103
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /workspaces/storybook-babel-issue/packages/mui-theme-base/src/index.ts: Only declares and type imports are allowed inside declare module. (10:2)

   8 |
   9 | declare module "@mui/material/styles" {
> 10 |   interface TypographyVariantsOptions {
     |   ^
  11 |     systemFontFamily?: TypographyStyleOptions["fontFamily"];
  12 |   }
  13 |
    at instantiate (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
    at toParseError (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error.js:58:12)
    at Object.raise (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
    at Object.expectContextual (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/util.js:108:20)
    at Object.flowParseDeclareModule (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:520:16)
    at Object.flowParseDeclare (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:469:23)
    at Object.parseExpressionStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:1948:25)
    at Object.parseStatementContent (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:477:19)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:329:17)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:1926:26)
    at processResult (/workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:758:19)
    at /workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:860:5
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /workspaces/storybook-babel-issue/node_modules/babel-loader/lib/index.js:59:103
```

</details>

Try renaming `.babelrc.json.example` to `.babelrc.json` and it will still fail with parse errors, because the local Babel configuration does not apply to files in other monorepo packages:

<details>

```
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /workspaces/storybook-babel-issue/packages/mui-theme-base/src/index.ts: Only declares and type imports are allowed inside declare module. (10:2)

   8 |
   9 | declare module "@mui/material/styles" {
> 10 |   interface TypographyVariantsOptions {
     |   ^
  11 |     systemFontFamily?: TypographyStyleOptions["fontFamily"];
  12 |   }
  13 |
    at instantiate (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
    at toParseError (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parse-error.js:58:12)
    at Object.raise (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
    at Object.expectContextual (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/util.js:108:20)
    at Object.flowParseDeclareModule (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:520:16)
    at Object.flowParseDeclare (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:469:23)
    at Object.parseExpressionStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:1948:25)
    at Object.parseStatementContent (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:477:19)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/parser/statement.js:329:17)
    at Object.parseStatement (/workspaces/storybook-babel-issue/node_modules/@babel/parser/src/plugins/flow/index.js:1926:26)
    at processResult (/workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:758:19)
    at /workspaces/storybook-babel-issue/node_modules/webpack/lib/NormalModule.js:860:5
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/workspaces/storybook-babel-issue/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /workspaces/storybook-babel-issue/node_modules/babel-loader/lib/index.js:59:103
```

</details>

**Comment by marckassay** [comment]
Fyi, to my surprise, `babel.config.json` isn't available in all versions of Babel according to their docs:

> Note: babel.config.json is supported from Babel 7.8.0. In older Babel 7 versions, only babel.config.js is supported. ~[ref](https://babeljs.io/docs/en/options#rootmode)

I'm not sure what version of Babel you might have been using as a dependency of Storybook.

**Comment by aaronadamsCA** [comment]
That's good to know; I took a look, and by February 2 we were already on Babel 7.16.12, so I don't think that was it.

**Comment by shilman** [comment]
@ndelangen  is this something you can help out with?

**Comment by aaronadamsCA** [comment]
I am re-debugging this now and I'm not completely sure my original report was accurate.

I'll close this until I'm sure there's an issue, in which case I'll reopen it.

**Comment by aaronadamsCA** [comment]
Re-opened with a reproduction!

**Comment by Bidrman** [comment]
@aaronadamsCA  hey, any update on this issue? It seems like we are facing the same problem in our project.  Interesting fact is, that when we swap babel.config for .babelrc.json and set it correctly, then Storybook takes the settings correctly. However its just a workaround how to deal with this issue.

**Comment by aaronadamsCA** [comment]
Still having problems, now trying with the Storybook v7 alpha and it's the same situation: Storybook tries to parse our TypeScript as either JavaScript or Flow.

Our Babel config is not very complex:

```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ]
}
```

With only a `babel.config.json` in the monorepo root, Storybook gives syntax errors whenever it encounters any TypeScript syntax.

If I copy the contents of the file to `.babelrc.json` in our Storybook package, for some reason Storybook starts trying to parse TypeScript files from other packages using the Flow parser:

<details>

```
ModuleBuildError: Module build failed (from ../../node_modules/babel-loader/lib/index.js):
SyntaxError: /workspaces/repo/packages/storybook-utils/src/index.ts: Support for the experimental syntax 'flow' isn't currently enabled (1:8):

> 1 | export type { ExampleCardProps } from "./ExampleCard";
    |        ^
  2 | export { ExampleCard } from "./ExampleCard";
  3 | export type { ExampleCardContentProps } from "./ExampleCardContent";
  4 | export { ExampleCardContent } from "./ExampleCardContent";

Add @babel/preset-flow (https://github.com/babel/babel/tree/main/packages/babel-preset-flow) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-flow) to the 'plugins' section to enable parsing.
    at instantiate (/workspaces/repo/node_modules/@babel/parser/lib/index.js:65:32)
    at constructor (/workspaces/repo/node_modules/@babel/parser/lib/index.js:356:12)
    at JSXParserMixin.raise (/workspaces/repo/node_modules/@babel/parser/lib/index.js:3297:19)
    at JSXParserMixin.expectOnePlugin (/workspaces/repo/node_modules/@babel/parser/lib/index.js:3346:18)
    at JSXParserMixin.isExportDefaultSpecifier (/workspaces/repo/node_modules/@babel/parser/lib/index.js:13862:16)
    at JSXParserMixin.maybeParseExportDefaultSpecifier (/workspaces/repo/node_modules/@babel/parser/lib/index.js:13758:14)
    at JSXParserMixin.parseExport (/workspaces/repo/node_modules/@babel/parser/lib/index.js:13684:29)
    at JSXParserMixin.parseStatementContent (/workspaces/repo/node_modules/@babel/parser/lib/index.js:12723:25)
    at JSXParserMixin.parseStatement (/workspaces/repo/node_modules/@babel/parser/lib/index.js:12624:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/workspaces/repo/node_modules/@babel/parser/lib/index.js:13190:25)
    at JSXParserMixin.parseBlockBody (/workspaces/repo/node_modules/@babel/parser/lib/index.js:13183:10)
    at JSXParserMixin.parseProgram (/workspaces/repo/node_modules/@babel/parser/lib/index.js:12541:10)
    at JSXParserMixin.parseTopLevel (/workspaces/repo/node_modules/@babel/parser/lib/index.js:12531:25)
    at JSXParserMixin.parse (/workspaces/repo/node_modules/@babel/parser/lib/index.js:14329:10)
    at parse (/workspaces/repo/node_modules/@babel/parser/lib/index.js:14373:38)
    at parser (/workspaces/repo/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/workspaces/repo/node_modules/@babel/core/lib/transformation/normalize-file.js:64:38)
    at normalizeFile.next (<anonymous>)
    at run (/workspaces/repo/node_modules/@babel/core/lib/transformation/index.js:20:50)
    at run.next (<anonymous>)
    at transform (/workspaces/repo/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/workspaces/repo/node_modules/gensync/index.js:220:32)
    at /workspaces/repo/node_modules/gensync/index.js:228:13
    at async.call.result.err.err (/workspaces/repo/node_modules/gensync/index.js:189:11)
    at /workspaces/repo/node_modules/gensync/index.js:158:13
    at /workspaces/repo/node_modules/@babel/core/lib/gensync-utils/async.js:95:7
    at /workspaces/repo/node_modules/gensync/index.js:96:35
    at step (/workspaces/repo/node_modules/gensync/index.js:237:14)
    at /workspaces/repo/node_modules/gensync/index.js:228:13
    at async.call.result.err.err (/workspaces/repo/node_modules/gensync/index.js:189:11)
    at processResult (/workspaces/repo/node_modules/webpack/lib/NormalModule.js:488:23)
    at /workspaces/repo/node_modules/webpack/lib/NormalModule.js:566:9
    at /workspaces/repo/node_modules/loader-runner/lib/LoaderRunner.js:360:14
    at /workspaces/repo/node_modules/loader-runner/lib/LoaderRunner.js:226:14
    at context.callback (/workspaces/repo/node_modules/loader-runner/lib/LoaderRunner.js:115:16)
    at /workspaces/repo/node_modules/babel-loader/lib/index.js:66:108
```

</details>

**Comment by shilman** [comment]
@aaronadamsCA that's pretty weird. are you sure you've completely upgraded to SB7? AFAIK there is nothing in v7 that references flow. Do you have a reproduction repo you can share?

**Comment by aaronadamsCA** [comment]
@shilman, I will try to upgrade this issue's reproduction repository to the v7 alpha now.

BTW, did anyone ever get a chance to review the original repro? It does seem to be the same fundamental problem.

**Comment by aaronadamsCA** [comment]
@shilman, I've added Storybook 7 examples to the repro repo, and documented the result of each example:

https://github.com/aaronadamsCA/storybook-issue-17398#readme

Only Storybook 6 using the built-in Babel config runs correctly.

**Comment by remleduff** [comment]
I am having the exact same problem in my own project where I'm trying to move storybook to a subfolder.

However, I just tried your reproduction repo, and it didn't work for the v6 case for me either. Could this be node version related? I'm on a pretty old version and get these messages when I npm install:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '18.12.1' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

**Comment by aaronadamsCA** [comment]
@remleduff The reproduction repository uses Yarn, so `yarn install` would probably be better. There's a chance the dependencies are just shaking out a bit differently between Yarn and NPM.

**Comment by ndelangen** [comment]
oh, this looks fun 🙅 

Maybe we should upgrade storybook to use babel-loader v9 ?
@nicoabie would you be able to pair with me on this some day next week?

**Comment by nonlogos** [comment]
> With
> 
> ```js
> babel: (config) => {
>     return {
>     ...config, configFile: path.resolve(__dirname, "../../../babel.config.json"),
>     }
>   },
> ```
> 
> I was able to make storybook read the proper file but now it complains
> 
> TypeError: [BABEL]: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "Identifier" (While processing: /Users/nicoabie/Development/rematter/Universe/node_modules/@babel/preset-env/lib/index.js)
> 
> Updating babel-loader to latest 9.1.2 solved that issue
> 
> Now I got type errors in stories (?)
> 
> listing all the plugins as shown here https://storybook.js.org/docs/7.0/react/configure/babel made those errors disappear
> 
> now I have a TypeError: /Users/nicoabie/.../storybook-config-entry.js: Property body[0] of BlockStatement expected node to be of a type ["Statement"] but instead got "ReturnStatement"

Any update on this? I ran into the same issue and upgrading to `9.1.2` works, but installing any of the plugins listed [here](https://storybook.js.org/docs/7.0/react/configure/babel) caused errors. Our storybook is installed in one of the packages in a monorepo. We used `babel.config.json` at the storybook root level because we needed to import external ts files. Would love some help on this 🙏

**Comment by heath-freenome** [comment]
@ndelangen Do you know if the `babel-loader` v9 will find babel configs inside of the `package.json` files?

**Comment by ndelangen** [comment]
I imagine it would, but the ones to ask would be the babel team I'm afraid.

Let me know if you find an answer?

**Comment by shilman** [comment]
@ndelangen let's take a look at this one together. i have the repro on my machine

**Comment by shilman** [comment]
Looked at this with @ndelangen and Storybook is working as intended, i.e. it's using Babel's default behavior.

By default babel sets the root to the current working directory, which is why it's not finding the babelrc at the project root. To work around this, add the following to your `.storybook/main.ts`:

```ts
export default {
  babel: (config) => {
    return { ...config, rootMode: 'upward' };
  },
};
```

For more information on Babel's root handling, please see the Babel docs here: https://babeljs.io/docs/options#rootmode

**Comment by aaronadamsCA** [comment]
GREAT find, thank you @shilman!

**Comment by shilman** [comment]
@aaronadamsCA That's so great. Your comment made my day!!! 🙌

**Comment by burketyler** [comment]
> @VictorGlindasPaf That doesn't seem like the same issue to me.
> 
> > expected node to be of a type ["Statement"] but instead got "ReturnStatement"
> 
> I'm not sure what this means, but it might hint at multiple conflicting versions of babel.

@VictorGlindasPaf I ran into the same error after migrating from 6.5.15. The migration scripts did a good job of handling the upgrade, however as @ndelangen has commented there appears to be an issue with conflicting babel versions. Not much online related to that error, so hopefully someone will find this useful.

**Issue**

`@storybook/react-webpack5` was installed via the migration script, which depends on `@storybook/builder-webpack5@7.0.5` which in turn depends on `"@babel/core": "^7.12.10"` and `"babel-loader": "^9.0.0"`. Based on the latest releases for those packages they resolve to `@babel/core@7.17.15` and `@babel-loader@9.1.2` for me.

The cause of the error appears to be an incompatibility between `@babel/core@7.17.15` and `@babel-loader@9.1.2`. 

**Workaround**

Modifying my lockfile manually to force `@babel/core` to the latest version (`7.21.4`) fixes the issue. Which can be done (a little) more gracefully using yarn or npm resolutions to override the dependency structure:

`yarn set resolution @babel/core@npm:^7.12.10 7.21.4`

**Cause**

The `babel-loader@9.1.2` package.json lists `@babel/core^7.12.0` as a peer dependency but it's using `^7.19.6` as a dev dependency, so I wonder if the peer dependency didn't get updated correctly. This mismatch might be whats causing confusion for consumers of the package as it indicates it's ok to use a version that appears to be incompatible.

```json
"peerDependencies": {
    "@babel/core": "^7.12.0",
  },
  "devDependencies": {
    "@babel/core": "^7.19.6",
  },
```

**Comment by morinted** [comment]
> Modifying my lockfile manually to force `@babel/core` to the latest version (`7.21.4`) fixes the issue.

Thank you, that worked for me! 🎉

A little heavy handed, but adding:

```json
  "resolutions": {
    "@babel/core": "^7.21.4"
  }
```

to my root `package.json` fixed my issue.

My issue manifested as:

```
node_modules/webpack/lib/NormalModule.js:751
				const error = new ModuleBuildError(err, {
				              ^

ModuleBuildError: Module build failed (from ../../node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js):
node_modules/@babel/types/lib/definitions/utils.js:131
    throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
          ^

TypeError: @babel/template placeholder "FILENAME": Property arguments[2] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "StringLiteral"
```

**Comment by nicoabie** [comment]
Property source of ImportDeclaration expected node to be of a type ["StringLiteral"] but instead got "StringLiteral"

I was importing from antd and it needed an es module so import now from antd/es
