### ISSUE TITLE
Storybook with Angular 13 lib fails

### ISSUE THREAD

**Issue by Tatsianacs** [storybookjs/storybook#17396]
**Describe the bug**
Storybook run fails due to the following error:
**ModuleNotFoundError: Module not found: Error: Package path ./README.md is not exported from package D:\projects\test-name\node_modules\@company\icons (see exports field in
D:\projects\test-name\node_modules\@company\icons\package.json)**

Angular 13 Angular Package Format now contains exports in package.json and somehow it fails storybook (the project itsel is working, so the problem only in storybook)

**To Reproduce**
it is hard before it fails with the private library. When Angular 12 is used for this internal library -> no exports section in package.json -> no error when running storybook. In Angular 13 additional section appeared and it fails storybook.
I tried to include in tsconfig - skipLibCheck, exclude node_modules - no success
I modified node_modules and this lib package.json manually (removed exports section) and storybook is running without error.
So the problem is with exports section that Angular 13 adds.

`99% done plugins webpack-hot-middlewarewebpack built preview dbf3a479262b39ae4c53 in 48556ms
ModuleNotFoundError: Module not found: Error: Package path ./README.md is not exported from package D:\projects\iq-test-name\node_modules\@company\icons (see exports field in
D:\projects\test-name\node_modules\@company\icons\package.json)
    at D:\projects\itest-name\node_modules\webpack\lib\Compilation.js:2013:28
    at D:\projects\test-namenode_modules\webpack\lib\NormalModuleFactory.js:795:13
    at eval (eval at create (D:\projects\test-name\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:275:22
    at eval (eval at create (D:\projects\test-name\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:431:22
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:124:11
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:667:25
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:852:8
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:972:5
    at D:\projects\test-name\node_modules\webpack\node_modules\neo-async\async.js:6883:13
    at D:\projects\test-name\node_modules\webpack\lib\NormalModuleFactory.js:955:45
    at finishWithoutResolve (D:\projects\test-name\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at D:\projects\test-name\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at D:\projects\test-name\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (D:\projects\test-name\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
`

**System**
Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
  npmPackages:
    @storybook/addon-a11y: ^6.4.0 => 6.4.14
    @storybook/addon-actions: ^6.4.0 => 6.4.14
    @storybook/addon-backgrounds: ^6.4.0 => 6.4.14
    @storybook/addon-docs: ^6.4.0 => 6.4.14
    @storybook/addon-essentials: ^6.4.0 => 6.4.14
    @storybook/addon-knobs: ^6.3.1 => 6.4.0
    @storybook/addon-storysource: ^6.4.0 => 6.4.14
    @storybook/addons: ^6.4.0 => 6.4.14
    @storybook/angular: ^6.4.0 => 6.4.14
    @storybook/builder-webpack5: ^6.4.0 => 6.4.14
    @storybook/manager-webpack5: ^6.4.0 => 6.4.14

**Comment by Tatsianacs** [comment]
I found the issue - docs in storybook tries to load Readme, I removed it and storybook is runnig
Closing
