### ISSUE TITLE
Run and build error only in ubuntu.

### ISSUE THREAD

**Issue by dmc31a42** [storybookjs/storybook#17408]
**Describe the bug**
Only in ubuntu, build storybook fail. In windows, it works.
I made react project in Windows.
```bash
create-react-app project-name --template typescript
cd project-name
npx sb init
```
and failed chromatic in Github Action.
It failed to building storybook in ubuntu, too.

**~~(Added) If make project in ubuntu and build in windows, it works~~**
**(Added)Now able to build in ubuntu. only not work in Github Action**

**To Reproduce**
In ubuntu,
```bash
git clone https://github.com/dmc31a42/storybook-build-error-6.4.18
cd storybook-build-error-6.4.18
npm install && npm run build-storybook
```

**System (Window)**
```
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.76)
  npmPackages:
    @storybook/addon-actions: ^6.4.18 => 6.4.18
    @storybook/addon-essentials: ^6.4.18 => 6.4.18
    @storybook/addon-links: ^6.4.18 => 6.4.18
    @storybook/builder-webpack5: ^6.4.18 => 6.4.18
    @storybook/manager-webpack5: ^6.4.18 => 6.4.18
    @storybook/node-logger: ^6.4.18 => 6.4.18
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0
    @storybook/react: ^6.4.18 => 6.4.18
```

**Console result (Windows)**
```bash
storybook-win>npm install && npm run build-storybook
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[##################] / reify:@storybook/core-common: timing reifyNode:node_modules/@babel/runtime Completed in 41102ms

added 2606 packages, and audited 2607 packages in 1m
[##################] / reify:@storybook/core-common: timing reifyNode:node_modules/@babel/runtime Completed in 41102ms
308 packages are looking for funding
  run `npm fund` for details

37 vulnerabilities (22 moderate, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> cupnote@0.1.0 build-storybook
> build-storybook -s public

info @storybook/react v6.4.18
info
info => Cleaning outputDir: storybook-win\storybook-static
(node:6856) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Copying static files: ./public => ./
info => Compiling preview..
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
info => Preview built (1.33 min)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets:
WARN   529.b48eb5b1.iframe.bundle.js (2.18 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (2.21 MiB)
WARN       runtime~main.27d5426b.iframe.bundle.js
WARN       529.b48eb5b1.iframe.bundle.js
WARN       main.d16d663e.iframe.bundle.js
WARN       static/css/main.a75c978a.css
WARN
info => Output directory: storybook-win\storybook-static
```

**System (Ubuntu)**
```bash
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    @storybook/addon-actions: ^6.4.18 => 6.4.18
    @storybook/addon-essentials: ^6.4.18 => 6.4.18
    @storybook/addon-links: ^6.4.18 => 6.4.18
    @storybook/builder-webpack5: ^6.4.18 => 6.4.18
    @storybook/manager-webpack5: ^6.4.18 => 6.4.18
    @storybook/node-logger: ^6.4.18 => 6.4.18
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0
    @storybook/react: ^6.4.18 => 6.4.18
```
**Console result (Ubuntu)**
```bash
nakwonchoi@NakWonCHOIDesk1:~$ git clone https://github.com/dmc31a42/storybook-build-error-6.4.18
Cloning into 'storybook-ubuntu'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 64 (delta 7), reused 64 (delta 7), pack-reused 0
Unpacking objects: 100% (64/64), 532.99 KiB | 1.13 MiB/s, done.
nakwonchoi@NakWonCHOIDesk1:~$ cd storybook-ubuntu/
nakwonchoi@NakWonCHOIDesk1:~/storybook-ubuntu$ npm install && npm run build-storybook
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 2606 packages, and audited 2607 packages in 13m

308 packages are looking for funding
  run `npm fund` for details

37 vulnerabilities (22 moderate, 15 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> cupnote@0.1.0 build-storybook
> build-storybook -s public

info @storybook/react v6.4.18
info
info => Cleaning outputDir: /home/nakwonchoi/storybook-ubuntu/storybook-static
(node:458) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Copying static files: ./public => ./
info => Compiling preview..
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
ERR! => Failed to build the preview
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
ERR! TypeError: Cannot read properties of null (reading 'tagName')
ERR!     at parse (/home/nakwonchoi/storybook-ubuntu/node_modules/svg-parser/dist/svg-parser.umd.js:279:15)
ERR!     at jsxPlugin (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/plugin-jsx/lib/index.js:18:41)
ERR!     at run (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:18:16)
ERR!     at convert (/home/nakwonchoi/storybook-ubuntu/node_modules/@svgr/core/lib/convert.js:26:10)
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:200:62
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Cache.shutdown (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Cache.js:150:23)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1212:15
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Compiler.close (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1205:23)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:199:20
ERR!     at finalCallback (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:441:32)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:458:13
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at onCompiled (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:456:21)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1183:17
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:200:62
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Cache.shutdown (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Cache.js:150:23)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1212:15
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Compiler.close (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1205:23)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:199:20
ERR!     at finalCallback (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:441:32)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:458:13
ERR!     at Hook.eval [as callAsync] (eval at create (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/nakwonchoi/storybook-ubuntu/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at onCompiled (/home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:456:21)
ERR!     at /home/nakwonchoi/storybook-ubuntu/node_modules/webpack/lib/Compiler.js:1183:17
```

**Additional context**

**Comment by dmc31a42** [comment]
It was mistake to use lfs.
