### ISSUE TITLE
Storybook Preact 6.4 missing react modules ( Failed to load preset)

### ISSUE THREAD

**Issue by iondrimba** [storybookjs/storybook#17585]
**Describe the bug**
When trying to run `npm run storybook` with storybook 6.4 preact an exception is thrown about missing `react` module

**To Reproduce**
I've tried to use `npx sb@next repro` and got this error: 

```
🏗 Bootstrapping preact project (this might take a few minutes)
npx preact-cli@latest create preactjs-templates/default preact --install=false --git=false
- Creating project
✔ Done!

To get started, cd into the new directory:
  cd preact

To start a development live-reload server:
  npm run dev

To create a production build (in ./build):
  npm run build

To start a production HTTP/2 server:
  npm run serve


🧶 Installing Yarn 2
yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules
/bin/sh: 1: yarn: not found
An error occurred while executing: `yarn set version berry && yarn config set enableGlobalCache true && yarn config set nodeLinker node-modules`
🚨 Installing Yarn 2 failed
🚨 Failed to create repro
Error: Error: command exited with code: 127: 
    at repro (/home/ion/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/cjs/repro.js:172:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
So I made a reproducible repo using a clean install of `nextjs-preact` and `storybook-preact`
https://github.com/iondrimba/bug-storybook-preact

Added Github Actions to emulate the problem https://github.com/iondrimba/bug-storybook-preact/actions

### Error I'm getting is this:
```
info @storybook/preact v6.4.19
info 
info => Loading presets
WARN   Failed to load preset: "/home/ion/nextjs-preact-storybook/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js"
ERR! Error: Cannot find module '/home/ion/nextjs-preact-storybook/node_modules/react/package.json.js'
ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at resolveFileName (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:46:47)
ERR!     at Object.<anonymous> (/home/ion/nextjs-preact-storybook/node_modules/@storybook/ui/paths.js:17:18)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/home/ion/nextjs-preact-storybook/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js:63:38)
ERR!  Error: Cannot find module '/home/ion/nextjs-preact-storybook/node_modules/react/package.json.js'
ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at resolveFileName (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:29:39)
ERR!     at resolveFrom (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:43:9)
ERR!     at module.exports (/home/ion/nextjs-preact-storybook/node_modules/resolve-from/index.js:46:47)
ERR!     at Object.<anonymous> (/home/ion/nextjs-preact-storybook/node_modules/@storybook/ui/paths.js:17:18)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:999:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (/home/ion/nextjs-preact-storybook/node_modules/@storybook/manager-webpack4/dist/cjs/presets/manager-preset.js:63:38) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   path: '/home/ion/nextjs-preact-storybook/node_modules/react/package.json'
ERR! }
ERR! Error: Cannot find module '/home/ion/nextjs-preact-storybook/node_modules/react/package.json.js'
ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at _default (/home/ion/nextjs-preact-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:196:46)
ERR!     at async Object.start (/home/ion/nextjs-preact-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:91:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: Cannot find module '/home/ion/nextjs-preact-storybook/node_modules/react/package.json.js'
ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at _default (/home/ion/nextjs-preact-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js:196:46)
ERR!     at async Object.start (/home/ion/nextjs-preact-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:91:16)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/dev-server.js:126:28)
ERR!     at async buildDevStandalone (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/home/ion/nextjs-preact-storybook/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   path: '/home/ion/nextjs-preact-storybook/node_modules/react/package.json'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**System**
```sh
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0.1
```
**Additional context**
This looks like the same problem on issue https://github.com/storybookjs/storybook/issues/17448

Installing `react` and `react-dom` as devDependencies fixed the problem but I dont know if its the right fix

**Comment by 13tales** [comment]
I'm also having this issue when trying to add Storybook to a new Preact project using the "Widget-Typescript" Preact-CLI template.
Adding React to a Preact project does _not_ seem like the right fix 😝

**Comment by drianoaz** [comment]
@13tales 

https://github.com/storybookjs/storybook/issues/17448#issuecomment-1069666765 here I left some details on how I made it work in my project

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
