### ISSUE TITLE
Vue3, TypeScript, Custom Webpack v5 - SyntaxError: Unexpected Indentifier

### ISSUE THREAD

**Issue by paltman** [storybookjs/storybook#17650]
**Describe the bug**

`SortableTableHeader.vue`:

```vue
<template>
  <span class="cursor-pointer space-x-4 flex hover:text-gray-800" @click.prevent="onClick">
    <slot />
    <span v-if="active" class="my-auto h-5 w-5">
      <SortAscendingIcon v-if="ascending" />
      <SortDescendingIcon v-else />
    </span>
  </span>
</template>

<script lang="ts">
  import { defineComponent, PropType } from 'vue';
  import { SortAscendingIcon, SortDescendingIcon } from '@heroicons/vue/solid';
  import { SortableColumns } from './types';

  export default defineComponent({
    props: {
      columnKey: {
        type: String as PropType<SortableColumns>,
        required: true,
      },
      ascending: {
        type: Boolean,
        default: true,
      },
      active: {
        type: Boolean,
        default: false,
      },
    },
    components: {
      SortAscendingIcon,
      SortDescendingIcon,
    },
    emits: {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      'sort-by': (_c: SortableColumns) => true,
    },
    setup(props, { emit }) {
      const onClick = () => {
        emit('sort-by', props.columnKey);
      };

      return {
        onClick,
      };
    },
  });
</script>
```

`SortableTableHeader.stories.js`:
```js
// eslint-disable-next-line import/no-extraneous-dependencies
import { action } from '@storybook/addon-actions';

import SortableTableHeader from './SortableTableHeader.vue';

export default {
  component: SortableTableHeader,
};

const Template = args => ({
  components: { SortableTableHeader },
  template: `<SortableTableHeader @sort-by="log" v-bind="${args}">Column Header</SortableTableHeader>`,
  methods: {
    log: action('log'),
  },
});

export const Default = Template.bind({});
Default.args = {
  columnKey: 'my-column',
};

export const AscendingActive = Template.bind({});
AscendingActive.args = {
  ...Default.args,
  active: true,
  ascending: true,
};

export const DescendingActive = Template.bind({});
DescendingActive.args = {
  ...AscendingActive.args,
  ascending: false,
};
```

`main.js`:
```js
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
  stories: [
    '../static/src/js/**/*.stories.@(js|jsx|ts|tsx)'
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
          postcssOptions: {
            plugins: [
              require('tailwindcss')(),
              require('autoprefixer')(),
            ],
          },
        },
      },
    },
  ],
  framework: '@storybook/vue3',
  core: {
    builder: 'webpack5',
  },
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.ts$/,
      use: [
       {
         loader: 'ts-loader',
         options: { appendTsSuffixTo: [/\.vue$/], transpileOnly: true, happyPackMode: false },
       },
      ],
    });
    // config.plugins = config.resolve.plugins || [];
    config.plugins.push(new ForkTsCheckerWebpackPlugin(
      {
        typescript: {
          extensions: {
            vue: {
              enabled: true,
              compiler: '@vue/compiler-sfc',
            },
          },
          diagnosticOptions: {
            semantic: true,
            syntactic: false,
          },
        },
      },
    ));
    console.log(config.plugins);
    // config.resolve.plugins = config.resolve.plugins || [];
    // config.resolve.plugins.push(new TsconfigPathsPlugin({}));
    return config;
  },
}
```

Exception:
```
SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at compileToFunction (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:76499:21)
    at finishComponentSetup (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:35745:36)
    at setupStatefulComponent (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:35675:9)
    at setupComponent (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:35605:11)
    at mountComponent (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:33460:13)
    at processComponent (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:33435:17)
    at patch (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:33039:21)
    at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:33575:21)
    at ReactiveEffect.run (http://localhost:6006/vendors-node_modules_heroicons_vue_solid_esm_index_js-node_modules_storybook_addon-actions_di-1d4607.iframe.bundle.js:28232:29)
```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "allowJs": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "static/src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "static/src/**/*.ts",
    "static/src/**/*.tsx",
    "static/src/**/*.vue",
    "static/tests/**/*.ts",
    "static/tests/**/*.tsx",
  ],
  "exclude": [
    "node_modules"
  ],
  "typeRoots": [
    "./node_modules/@types",
    "./static/src/gql/types"
  ],
  "types": ["mixpanel"]
}
```

I only get this on refresh.  On initial load, all the controls display as expected, however Canvas is blank.  Upon refresh, Canvas is filled in with black background with red border with the above stack trace.

**System**
```
% npx sb@next info
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/paltman/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/Users/paltman/.nvm/versions/node/v14.17.5/bin/node" "/Users/paltman/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/paltman/.npm/_npx/48493/lib/node_modules/sb/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.15 - ~/<redacted>/node_modules/.bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: ^6.4.9 => 6.4.19
    @storybook/addon-essentials: ^6.4.9 => 6.4.19
    @storybook/addon-links: ^6.4.9 => 6.4.19
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/builder-webpack5: ^6.4.19 => 6.4.19
    @storybook/manager-webpack5: ^6.4.19 => 6.4.19
    @storybook/vue3: ^6.4.9 => 6.4.19
```

**Additional context**

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
