### ISSUE TITLE
Angular-cli `start-storybook` broken in `next`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#17673]
When you run the following in `next` the page gets stuck in a loading state:

```sh
yarn bootstrap --core
cd examples/angular-cli
yarn storybook
```

The error in the browser console is:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (runtime~main.iframe.bundle.js:854:30)
    at fn (runtime~main.iframe.bundle.js:151:20)
    at Module.../../lib/store/dist/esm/index.js (main.iframe.bundle.js:27381:64)
```

I bisected through the commit history and it looks like this commit is the culprit: 

https://github.com/storybookjs/storybook/commit/64677960a88da014fa9eb8751f44240ab47be777#diff-86945e899053d8dac571e858d3d2810b394d1240c46a55bc5f568bd645d9ff8aR261

Specifically `usedExports: isProd,` in `builder-webpack4`

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.47 containing PR #17674 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
