### ISSUE TITLE
Addon-docs empty with .mdx 

### ISSUE THREAD

**Issue by josefkvist** [storybookjs/storybook#17739]
**Describe the bug**
Error occurs on the docs tab when using .mdx-stories.  Am I doing something wrong or is this a bug?

```
index.js:51 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at sanitize (index.js:51:1)
    at sanitizeSafe (index.js:58:1)
    at toId (index.js:72:1)
    at lookupStoryId (Story.js:42:1)
    at getStoryId (Story.js:50:1)
    at Story (Story.js:115:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)

react-dom.development.js:19527 The above error occurred in the <Story> component:
    in Story (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in wrapper (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in MDXContent (created by page)
    in AddContext (created by page)
    in page
    in div (created by Context.Consumer)
    in Styled(div) (created by DocsContainer)
    in div (created by Context.Consumer)
    in Styled(div) (created by DocsContainer)
    in MDXProvider (created by DocsContainer)
    in ThemeProvider (created by DocsContainer)
    in SourceContainer (created by DocsContainer)
    in DocsContainer
```

**To Reproduce**

main.js
```
module.exports = {
  stories: ["../src/**/*.stories.mdx"],
  // Add any Storybook addons you want here: https://storybook.js.org/addons/
  addons: ["@storybook/addon-docs"],
  webpackFinal: async (config) => {
    config.module.rules.push({
      test: /\.(ts|tsx)$/,
      loader: require.resolve("babel-loader"),
      options: {
        presets: [["react-app", { flow: false, typescript: true }]],
      },
    });
    config.resolve.extensions.push(".ts", ".tsx");

    return config;
  },
};

````

Header.stories.mdx
```
import { Meta, Story, Canvas } from "@storybook/addon-docs";
import { H1, H2, H3, H4 } from "./Headers";
<Meta title="HeadersMeta" />;

# HeadersTitle

Some text here

<Story name="HeadersStory">
  <div>
    <H1>Header 1</H1>
    <H2>Header 2</H2>
    <H3>Header 3</H3>
    <H4>Header 4</H4>
  </div>
</Story>

```

[Link to repro](https://github.com/josefkvist/storybook-mdx-repro) 

**System**
```

Environment Info:

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.39)
  npmPackages:
    @storybook/addon-a11y: ^6.4.19 => 6.4.19
    @storybook/addon-docs: ^6.4.19 => 6.4.19
    @storybook/addon-storysource: ^6.4.19 => 6.4.19
    @storybook/react: ^6.3.7 => 6.4.19

```

**Additional context**
I'm using @storybook/react and typescript

**Comment by josefkvist** [comment]
Solved this by adding a new line between imports and <Meta> and removing the semi-colon on the <Meta>-tag

**Comment by JamesPHoughton** [comment]
I ran into this today as well - including a blank line between imports did fix the problem, but only after several hours of frustration. Is it possible to remove this particular "feature" of the syntax, or document it?

**Comment by josefkvist** [comment]
@JamesPHoughton I changed approach after this. Changed it to using *.stories.tsx with *.mdx on the side with [this](https://storybook.js.org/docs/react/writing-docs/docs-page#with-mdx-documentation)

had to add this to make typescript happy:
``` javascript
/** ./src/types.d.ts */
declare module "*.mdx" {
  const docs: any; // Add better type definitions here if desired.
  export default docs;
}
```

and this under compilerOptions in tsconfig.json:
``` json
  "typeRoots": [
      "./src/types.d.ts"
    ]
```
