### ISSUE TITLE
[Angular - Storybook] Error: No configuration files have been found in your configDir

### ISSUE THREAD

**Issue by behsayah** [storybookjs/storybook#17751]
**Describe the bug**
I'm trying to create a new angular workspace without root application (Component Library) and storybook. 
I've created the workspace and add storybook into it. Configuration files exist inside the project but Storybook can not find configuration file.

**To Reproduce**
1. ng new test --createApplication=false
2. cd test
3. ng g library foo
4. ng generate application demo --routing=true
5. npx sb init
6. npm run storybook

**System**
ERR! Error: No configuration files have been found in your configDir ([PATH]/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles ([PATH]/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets ([PATH]/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets ([PATH]/node_modules/@storybook/core-common/dist/cjs/presets.js:342:131)
ERR!     at buildDevStandalone ([PATH]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:104:48)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Object.buildDev ([PATH]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: No configuration files have been found in your configDir ([PATH]/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles ([PATH]/node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js:50:11)
ERR!     at loadCustomPresets ([PATH]/node_modules/@storybook/core-common/dist/cjs/utils/load-custom-presets.js:19:62)
ERR!     at loadAllPresets ([PATH]/node_modules/@storybook/core-common/dist/cjs/presets.js:342:131)
ERR!     at buildDevStandalone ([PATH]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:104:48)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async Object.buildDev ([PATH]/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

**Additional context**
Project's file structure:
_As you can see the configuration file does exist_
![Screen Shot 2022-03-17 at 10 33 08 PM](https://user-images.githubusercontent.com/21294962/158876895-79892072-044f-44ca-8cad-4f3c732783c2.png)

**Comment by MBelniak** [comment]
In my case configDir was always "<process_cwd>/.storybook" despite of setting it via -c option. I realized I had commander@7.0.0 in package.json in resolutions (pnpm>overrides to be exact) and after I downgraded commander to 6.2.1 configDir was set properly. Maybe that will guide you to a solution for your problem.

**Comment by Nielssg** [comment]
Hoping this might temporarily fix things for people or point someone in the right direction: by editing the `validate-configuration-files.js` file (`node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js`, 6.5.0-beta.8), simply adding the following line in the exists method at line 44 will solve the issue (note: only local node modules, it's a bandaid, NOT a solution, and make sure a main.js exists):

```
if (file === "main") return true;
```

It will signal Storybook that the main file should exist, and it will actually load it correcly, so it seems like the path resolving fails for some reason. After typing this, I found an issue has been created which links with this issue. On windows, it seems to use backslashes, which the path will not resolve and therefore, no file can be found. 

[Issue #18226 ](https://github.com/storybookjs/storybook/issues/18226)

**Comment by TheLonelyMillennial** [comment]
> Hoping this might temporarily fix things for people or point someone in the right direction: by editing the `validate-configuration-files.js` file (`node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js`, 6.5.0-beta.8), simply adding the following line in the exists method at line 44 will solve the issue (note: only local node modules, it's a bandaid, NOT a solution, and make sure a main.js exists):
> 
> ```
> if (file === "main") return true;
> 
> // (or better, actually fix the path resolving temporary)
> 
> return !!_glob.default.sync(_path.default.resolve(configDir, `${file}${extensionsPattern}`).split(_path.default.sep).join("/")).length;
> ```
> 
> It will signal Storybook that the main file should exist, and it will actually load it correcly, so it seems like the path resolving fails for some reason. After typing this, I found an issue has been created which links with this issue. On windows, it seems to use backslashes, which the path will not resolve and therefore, no file can be found.
> 
> [Issue #18226 ](https://github.com/storybookjs/storybook/issues/18226)

That worked for me for me using `@storybook/react`, though since I'm on Windows I'm not sure how to test on a Mac. If future developers opt for this path, I recommend using [patch-package](https://github.com/ds300/patch-package) until this gets addressed in another release. ([Here's a tutorial on using patch-package](https://medium.com/@gitaumoses4/patching-and-making-persistent-changes-to-an-npm-package-in-node-modules-1ad4cb7c2f64) that I followed)

**Comment by xavigimenezsanchez** [comment]
This error is also happening to me. However, I'm working with react. The temporary solution given by @TheLonelyMillennial is working for me.

**Comment by QuerGamer** [comment]
> This error is also happening to me. However, I'm working with react. The temporary solution given by @TheLonelyMillennial is working for me.

yea i have the same problem but the fix did not help for me.

**Comment by manuelgarciacr** [comment]
Same with vue :
    "vue": "^3.2.13",
    "@storybook/vue3": "^6.0.26",

**Comment by xavigimenezsanchez** [comment]
I've just re-install all the projects packages and it's working.

**Comment by darioscattolini** [comment]
> That worked for me for me using `@storybook/react`, though since I'm on Windows I'm not sure how to test on a Mac. If future developers opt for this path, I recommend using [patch-package](https://github.com/ds300/patch-package) until this gets addressed in another release. ([Here's a tutorial on using patch-package](https://medium.com/@gitaumoses4/patching-and-making-persistent-changes-to-an-npm-package-in-node-modules-1ad4cb7c2f64) that I followed)

@TheLonelyMillennial I run `npx patch-package @storybook` after editing the file in node_modules, but the patch file is not built. CLI outputs:
```
patch-package 6.4.7
Applying patches...
No patch files found
```
Have you done it this way? I couldn't find anything useful in Google on this issue.

**Comment by razdu** [comment]
thanks @xavigimenezsanchez . that was easy to solve thanks to your comment. worked like a charm!

**Comment by zwang1-godaddy** [comment]
> Hoping this might temporarily fix things for people or point someone in the right direction: by editing the `validate-configuration-files.js` file (`node_modules/@storybook/core-common/dist/cjs/utils/validate-configuration-files.js`, 6.5.0-beta.8), simply adding the following line in the exists method at line 44 will solve the issue (note: only local node modules, it's a bandaid, NOT a solution, and make sure a main.js exists):
> 
> ```
> if (file === "main") return true;
> 
> // (or better, actually fix the path resolving temporary)
> 
> return !!_glob.default.sync(_path.default.resolve(configDir, `${file}${extensionsPattern}`).split(_path.default.sep).join("/")).length;
> ```
> 
> It will signal Storybook that the main file should exist, and it will actually load it correcly, so it seems like the path resolving fails for some reason. After typing this, I found an issue has been created which links with this issue. On windows, it seems to use backslashes, which the path will not resolve and therefore, no file can be found.
> 
> [Issue #18226 ](https://github.com/storybookjs/storybook/issues/18226)

This works for me temporarily on my local. Do we have a permanent solution?

**Comment by navernoedenis** [comment]
Faced with the same problem. After some time of finding the solution, I found the reason.
In my case it happened because my root folder contained brackets in the name. 

before renaming:
- "[name] - client"

after renaming:  
- "name - client"

And everything started working like it should have.

**Comment by elenachiosa** [comment]
> Faced with the same problem. After some time of finding the solution, I found the reason. In my case it happened because my root folder contained brackets in the name.
> 
> before renaming:
> 
> * "[name] - client"
> 
> after renaming:
> 
> * "name - client"
> 
> And everything started working like it should have.

Thank you so much! This was the issue for me as well.

**Comment by ofhope** [comment]
I'm seeing this error while upgrading on a Windows machine. Not sure if its a glob issue or some other missconfiguration.

```
Error: No configuration files have been found in your configDir (...)
Storybook needs "main.js" file, please add it (or pass a custom config dir flag to Storybook to tell where your main.js file is located at).
    at validateConfigurationFiles
Node.js v18.18.2    
```

I was on `@storybook/react: ^6.5.15`. I tried upgrading to 7 with `npx storybook@latest init`. The migration succeeded but when attempting to run it can't find the `main.ts` config.

I thought I'd try the beta to see if it would fix the issue, but the same error is produced now on `8.0.0-beta.3` after running `npx storybook@next upgrade`.

**Comment by valentinpalkovic** [comment]
@ofhope Can you provide a minimal reproduction?
