### ISSUE TITLE
sb + vite + vue: No docs.container on docs tab on clean setup

### ISSUE THREAD

**Issue by webdesignberlin** [storybookjs/storybook#17773]
**Describe the bug**
Docs Page doesnt work >6.5.0-alpha.47 with vite setup.

**To Reproduce**
Via Repo: https://github.com/webdesignberlin/sb-builder-vite-no-container
Or via Steps:

Node 16
`npm init vue@latest`
```
✔ Project name: … latest-test
✔ Add TypeScript? … Yes
✔ Add JSX Support? … No
✔ Add Vue Router for Single Page Application development? … No
✔ Add Pinia for state management? … No
✔ Add Vitest for Unit Testing? … Yes
✔ Add Cypress for End-to-End testing? … Yes
✔ Add ESLint for code quality? … Yes
✔ Add Prettier for code formatting? … No
```
`npm install`
Run SB init:
`npx sb@next init --builder storybook-builder-vite`
Run Storybook:
`npm run storybook`
go to some docs page get following
Error:
`
Uncaught (in promise) Error: No `docs.container` set, did you run `addon-docs/preset`?
    at _callee$ (renderDocs-LVJGRNMN.js:110:19)
    at tryCatch (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:45:44)
    at Generator.invoke [as _invoke] (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:182:26)
    at Generator.next (:6007/node_modules/.vite-storybook/chunk-2ZKQNBD4.js?v=506d2ae8:78:25)
    at asyncGeneratorStep (renderDocs-LVJGRNMN.js:64:24)
    at _next (renderDocs-LVJGRNMN.js:82:9)
    at renderDocs-LVJGRNMN.js:87:7
    at new Promise (<anonymous>)
    at renderDocs-LVJGRNMN.js:79:12
    at _renderDocsAsync (renderDocs-LVJGRNMN.js:166:27)
renderDocs.js:39 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'container')
    at _callee$ (renderDocs.js:39:32)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at asyncGeneratorStep (renderDocs.js:5:99)
    at _next (renderDocs.js:7:194)
    at renderDocs.js:7:364
    at new Promise (<anonymous>)
    at renderDocs.js:7:97
    at renderDocsAsync (renderDocs.js:17:27)
_callee$ @ renderDocs.js:39
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ renderDocs.js:5
_next @ renderDocs.js:7
(anonym) @ renderDocs.js:7
(anonym) @ renderDocs.js:7
renderDocsAsync @ renderDocs.js:17
renderDocs @ renderDocs.js:13
_callee2$ @ DocsRender.js:127
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
renderDocs @ renderDocs.js:13
_callee2$ @ DocsRender.js:127
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
(anonym) @ DocsRender.js:9
(anonym) @ DocsRender.js:9
render @ DocsRender.js:140
_callee$ @ DocsRender.js:87
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
Promise.then (async)
asyncGeneratorStep @ DocsRender.js:7
_next @ DocsRender.js:9
(anonym) @ DocsRender.js:9
(anonym) @ DocsRender.js:9
renderToElement @ DocsRender.js:98
_callee12$ @ PreviewWeb.js:934
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonym) @ runtime.js:119
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
Promise.then (async)
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
Promise.then (async)
asyncGeneratorStep3 @ PreviewWeb.js:8
_next @ PreviewWeb.js:10
(anonym) @ PreviewWeb.js:10
(anonym) @ PreviewWeb.js:10
renderSelection @ PreviewWeb.js:949
onSetCurrentStory @ PreviewWeb.js:560
(anonym) @ index.js:168
handleEvent @ index.js:167
(anonym) @ index.js:52
handler @ index.js:101
handleEvent @ index.js:286
postMessage (async)
(anonym) @ main.f1159ece7311d200d210.manager.bundle.js:2
send @ main.f1159ece7311d200d210.manager.bundle.js:2
handler @ main.f1159ece7311d200d210.manager.bundle.js:2
emit @ main.f1159ece7311d200d210.manager.bundle.js:2
emit @ main.f1159ece7311d200d210.manager.bundle.js:2
(anonym) @ main.f1159ece7311d200d210.manager.bundle.js:2
Ii @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Vj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
exports.unstable_runWithPriority @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
cg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Dj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
yj @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
(anonym) @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
exports.unstable_runWithPriority @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
cg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
fg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
gg @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
Ga @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
gd @ vendors~main.d735861ee42d9ccf0ed5.manager.bundle.js:2
`

**System**
```
Note: current replaced with 6.5.0-alpha.47 cause this version works. 6.5.0-alpha.49 dont.
Environment Info:

  System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.3
  npmPackages:
    @storybook/addon-actions: 6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-essentials: 6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/addon-links: 6.5.0-alpha.47 => 6.5.0-alpha.47 
    @storybook/vue3: 6.5.0-alpha.47 => 6.5.0-alpha.47 
```

**Additional context**
This seems to be an issue in the latest alpha versions. Using 6.5.0-alpha.47 avoids the problem. https://github.com/eirslett/storybook-builder-vite/issues/285#issuecomment-1073987187

**Comment by shilman** [comment]
@IanVS so I took a look at this one and it's pretty weird. Findings so far:
- The example works if you unset the builder (i.e. use webpack4 builder)
- When I comment in the vite-builder node_modules, i can see that `addDecorator` is apparently being called, even on the most recent alphas

Can we pair for a few mins and see if we can get to the bottom of it together?

**Comment by IanVS** [comment]
I'm still digging in on this, but I did find that the bug disappears when enabling `storyStoreV7`, for whatever that's worth.

**Comment by IanVS** [comment]
The cause seems to be this line: https://github.com/storybookjs/storybook/pull/17697/files#diff-5cad30d66c64b95fd0bda3d47cb948001dfc2b14a805b964fb90e11cb9399331R1

If I change back to `'./dist/cjs/server/framework-preset-vue3'` in my node_modules, the storybook loads up correctly.

**Comment by IanVS** [comment]
Alright, digging just a bit deeper, I found that if I remove the import of `prepareForInline` from `@storybook/vue3/dist/esm/client/docs/config.js`, then docs build correctly again.  Digging one layer deeper, it's the import of `app` from `..index` (which is a re-export of a few other things).  If I change that import to `import { storybookApp as app } from '../preview/render';`, then stories build fine.  My guess at this point is that the problem has something to do with `@storybook/vue3/dist/esm/client/preview/index.js` being imported twice, which creates two different `api` variables, the second of which won't have all the parameters that have already been added.

**Comment by IanVS** [comment]
Alright, I think I've got a fix: https://github.com/eirslett/storybook-builder-vite/pull/289.

**Comment by lostdesign** [comment]
@IanVS we've tested `0.1.22` together with `6.5.0-alpha.51` and it works for us, unless `<Description>` is being used. Two new errors would show up - but unsure wether that tag should be used or not.


```html
import { Meta, Description } from '@storybook/addon-docs';

<Meta title="Docs/Introduction" parameters={{
    previewTabs: {
        canvas: { hidden: true },
        docs: { hidden: true },
    },
    viewMode: 'docs'
}}/>


<Description>
    # Some heading
    some text
</Description>
```

**This will throw**

```
Uncaught TypeError: can't access property "fonts", theme.typography is undefined
    withReset2 index-7209f724.js:297
    handleInterpolation index.js:1357
    serializeStyles2 index.js:1478
    Styled index.js:2049
    React 16
    _renderDocsAsync/_callee/_callee$/< renderDocs.js:100
    _callee$ renderDocs.js:99
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep renderDocs.js:5
    _next renderDocs.js:7
    promise callback*asyncGeneratorStep renderDocs.js:5
    _next renderDocs.js:7
    _asyncToGenerator renderDocs.js:7
    _asyncToGenerator renderDocs.js:7
    _renderDocsAsync renderDocs.js:110
    renderDocsAsync renderDocs.js:17
    renderDocs renderDocs.js:13
    _callee2$ DocsRender.js:127
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep DocsRender.js:7
    _next DocsRender.js:9
    promise callback*asyncGeneratorStep DocsRender.js:7
    _next DocsRender.js:9
    _asyncToGenerator DocsRender.js:9
    _asyncToGenerator DocsRender.js:9
    render DocsRender.js:140
    _callee$ DocsRender.js:87
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep DocsRender.js:7
    _next DocsRender.js:9
    promise callback*asyncGeneratorStep DocsRender.js:7
    _next DocsRender.js:9
    _asyncToGenerator DocsRender.js:9
    _asyncToGenerator DocsRender.js:9
    renderToElement DocsRender.js:98
    _callee12$ PreviewWeb.js:934
    tryCatch runtime.js:63
    invoke runtime.js:294
    defineIteratorMethods runtime.js:119
    asyncGeneratorStep3 PreviewWeb.js:8
    _next PreviewWeb.js:10
    promise callback*asyncGeneratorStep3 PreviewWeb.js:8
    _next PreviewWeb.js:10
    promise callback*asyncGeneratorStep3 PreviewWeb.js:8
    _next PreviewWeb.js:10
    _asyncToGenerator3 PreviewWeb.js:10
    _asyncToGenerator3 PreviewWeb.js:10
    renderSelection PreviewWeb.js:949
    _callee3$ PreviewWeb.js:328
```

```
The above error occurred in the <Context.Consumer> component:
Styled(div)
Description$12@http://localhost:6006/node_modules/.vite-storybook/chunk-MODEQS3L.js?v=c70e7d92:4684:18
DescriptionContainer2@http://localhost:6006/node_modules/.vite-storybook/@storybook_addon-docs.js?v=c70e7d92:1795:47
MDXCreateElement<@http://localhost:6006/node_modules/.vite-storybook/chunk-7VIYWAEF.js?v=c70e7d92:135:24
wrapper@http://localhost:6006/node_modules/.vite-storybook/chunk-7VIYWAEF.js?v=c70e7d92:130:20
MDXCreateElement<@http://localhost:6006/node_modules/.vite-storybook/chunk-7VIYWAEF.js?v=c70e7d92:135:24
MDXContent@http://localhost:6006/src/docs/Introduction.stories.mdx?t=1648484189979&import:8:20
AddContext2@http://localhost:6006/node_modules/.vite-storybook/@storybook_addon-docs.js?v=c70e7d92:1955:18
page
div
Styled(div)
div
Styled(div)
MDXProvider2@http://localhost:6006/node_modules/.vite-storybook/chunk-7VIYWAEF.js?v=c70e7d92:121:23
ThemeProvider
SourceContainer@http://localhost:6006/node_modules/@storybook/addon-docs/dist/esm/blocks/SourceContainer.js:36:18
DocsContainer@http://localhost:6006/node_modules/@storybook/addon-docs/dist/esm/blocks/DocsContainer.js:36:17

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

Just leaving it here as reference. It works without `<Description>`.

**Comment by tmeasday** [comment]
OK, I am investigating this issue again as the fix in https://github.com/storybookjs/builder-vite/pull/289 seems like maybe it was the wrong direction.

Here's one level deeper analysis that [@IanVS's original breakdown above](https://github.com/storybookjs/storybook/issues/17773#issuecomment-1078636434):

 - The fundamental problem is that `@storybook/core-client`'s `start()` gets called twice, creating two `PreviewWeb` objects (one of which gets the parameter, the other which does the rendering).
 - `start()` [is called by](https://github.com/storybookjs/storybook/blob/5982475373a7a7beccacf9dc14b552e0208f4254/app/react/src/client/preview/index.tsx#L20) `@storybook/vue3/dist/esm/client/preview/index.js` at the **top level**
 - As mentioned and is clear from the workaround, the issue is that `prepareForInline.js` ends importing that file.

In theory it shouldn't matter how many times a file is `import`-ed, code that runs at the top-level should only run once. However, what's happening here is something to do with the way that Vite builds bundles for various packages in `node_modules`. In this case, it builds a bundle `@storybook_vue3.js` which includes all this code, and then imports the individual files from the package as they are referenced from the user's SB.

**Comment by IanVS** [comment]
I've opened https://github.com/storybookjs/builder-vite/pull/305 and tried to summarize what's going on to the best of my knowledge, even though it's still a bit hazy to me.
