### ISSUE TITLE
Unable to render mdx in alpha version

### ISSUE THREAD

**Issue by brendonco** [storybookjs/storybook#17770]
**Describe the bug**
Unable to render MDX file in Storybook 6.5.0-alpha.49

```
WARN � Extraction error on stories\CHANGELOG.stories.mdx: Error: Not supported
(node:3084) UnhandledPromiseRejectionWarning: Error: Not supported
    at readCsfOrMdx (\node_modules\@storybook\csf-tools\index.cjs:12:11)
    at async StoryIndexGenerator.extractStories (\node_modules\@storybook\core-server\dist\cjs\utils\StoryIndexGenerator.js:121:18)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async StoryIndexGenerator.ensureExtracted (\node_modules\@storybook\core-server\dist\cjs\utils\StoryIndexGenerator.js:103:13)

 Extraction error on stories\CHANGELOG.stories.mdx: Error: Not supported
WARN � Extraction error on stories\CHANGELOG.stories.mdx: Error: Not supported
```

**To Reproduce**
 npx sb upgrade --prerelease

**System**
Environment Info:

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  Binaries:
    Node: 12.16.0 - ~\SoftwaresInstalled\node-v12.16.0-win-x64\node.EXE
    npm: 6.13.4 - ~\SoftwaresInstalled\node-v12.16.0-win-x64\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/addon-essentials: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/addon-links: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/addon-postcss: ^2.0.0 => 2.0.0
    @storybook/addon-storyshots: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/addon-storysource: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/addons: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/builder-webpack5: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/manager-webpack5: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/react: ^6.5.0-alpha.49 => 6.5.0-alpha.49
    @storybook/theming: ^6.5.0-alpha.49 => 6.5.0-alpha.49
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
