### ISSUE TITLE
"npx sb" fails on Windows

### ISSUE THREAD

**Issue by yairEO** [storybookjs/storybook#17869]
Hi, I wanted to open an issue and found myself opening this issue first because I've followed the instructions below on my *Windows 10* (*Terminal* ran as admin):

> Please create a reproduction by running `npx sb@next repro`

## Result:

```
🏃 Starting for react latest

🏗 Bootstrapping react project (this might take a few minutes)
mkdir react && cd react && touch yarn.lock && yarn init --yes && yarn add react react-dom
'touch' is not recognized as an internal or external command,
operable program or batch file.
An error occurred while executing: `mkdir react && cd react && touch yarn.lock && yarn init --yes && yarn add react react-dom`
🚨 Bootstrapping react failed
🚨 Failed to create repro
Error: Error: command exited with code: 1:
    at repro (C:\Users\Yaire\.pnpm-store\v3\tmp\_npx\22952\5\node_modules\.pnpm\@storybook+cli@6.5.0-alpha.55\node_modules\@storybook\cli\dist\cjs\repro.js:172:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Windows doesn't have `touch` command so I [found a workaround](https://stackoverflow.com/a/30019017/104380) 

I also have tried to install `yarn` and **now it works**. 
(Why *yarn* and not *pnpm*...)

---
I suggest these things be mentioned as **hard  requirements** prior to running the `npx sb@next repro` command on Windows

**Comment by kaiyoma** [comment]
@yairEO You should try doing your web development in git bash for windows or WSL, not Windows command prompt or PowerShell. I think you're going to find a lot of tools and libraries depend on a Unix-style shell for things to work properly. Trying to do web development in a pure Windows shell will probably lead to a lot of frustration. (Speaking as someone who has done web development in Windows 10 for 6+ years.)

Git Bash for Windows: https://gitforwindows.org/
WSL: https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by yairEO** [comment]
@kaiyoma - Thanks but I have already been doing that for years already. Never use `cmd` and definitely not `PowerShell` (succeeded by `Terminal`). I normally use `git bash` as the default on *vscode* terminal

**Comment by kaiyoma** [comment]
Interesting that `touch` isn't working then, since it's definitely part of the distribution (I use it all the time). I tried running the `repro` command myself and ran into a different problem: https://github.com/storybookjs/storybook/issues/17986 (the `repro` tool requires yarn)

**Comment by vladgorbachev** [comment]
npx works fine,
but after
```
'start-storybook' is not recognized as an internal or external command,
```
alpha31, react 18.2.0

**Comment by IanVS** [comment]
@vladgorbachev there are some changes in 7.0 to the way storybook is run.  You can check out https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700, and can also run `npx sb@future automigrate` to handle most of the changes from 6.5 to 7.0.

**Comment by valentinpalkovic** [comment]
> The `sb` binary and its `repro` subcommand were removed during the v7 CLI rewrite (the `touch yarn.lock` script no longer exists). Repros are now generated via `storybook create` and shared sandbox templates, all of which work on Windows. Closing as obsolete.
