### ISSUE TITLE
Upgrading React Scripts to 5+ - storybook borks with error in storybookDevServer

### ISSUE THREAD

**Issue by davesag** [storybookjs/storybook#18010]
**Describe the bug**

I've upgraded React Scripts from 4 to 5, run `npx sb@next upgrade` and allowed it to set the flag for `cra5`. Now when starting storybook I get

```
info @storybook/react v6.4.22
info 
info => Loading presets
info => Serving static files from ././public at /
ERR! TypeError: details.family.toLowerCase is not a function
ERR!     at /Users/me/my-project/node_modules/ip/lib/ip.js:385:39
ERR!     at Array.filter (<anonymous>)
ERR!     at /Users/me/my-project/node_modules/ip/lib/ip.js:384:37
ERR!     at Array.map (<anonymous>)
ERR!     at ip.address (/Users/me/my-project/node_modules/ip/lib/ip.js:379:37)
ERR!     at getServerAddresses (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/utils/server-address.js:20:55)
ERR!     at storybookDevServer (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:91:67)
ERR!     at async buildDevStandalone (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  TypeError: details.family.toLowerCase is not a function
ERR!     at /Users/me/my-project/node_modules/ip/lib/ip.js:385:39
ERR!     at Array.filter (<anonymous>)
ERR!     at /Users/me/my-project/node_modules/ip/lib/ip.js:384:37
ERR!     at Array.map (<anonymous>)
ERR!     at ip.address (/Users/me/my-project/node_modules/ip/lib/ip.js:379:37)
ERR!     at getServerAddresses (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/utils/server-address.js:20:55)
ERR!     at storybookDevServer (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/dev-server.js:91:67)
ERR!     at async buildDevStandalone (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/me/my-project/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
```

My `main.js` is

```js
// use commonjs style code for this.
const path = require('path');

module.exports = {
  stories: ['../src/**/*.stories.@(js|mdx)'],
  staticDirs: ['../public'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/preset-create-react-app', 'storybook-dark-mode'],
  // allow use of `import from 'x'` to import from '../src/x'
  webpackFinal: async config => ({ ...config,
    resolve: { ...config.resolve,
      modules: [...(config.resolve.modules || []), path.resolve(__dirname, '../src')]
    }
  }),
  core: {
    builder: 'webpack5'
  }
}
```

**System**

```
  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    npm: 8.6.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 97.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.4.22 => 6.4.22 
    @storybook/addon-docs: ^6.4.22 => 6.4.22 
    @storybook/addon-essentials: ^6.4.22 => 6.4.22 
    @storybook/addon-links: ^6.4.22 => 6.4.22 
    @storybook/builder-webpack5: ^6.4.22 => 6.4.22 
    @storybook/manager-webpack5: ^6.4.22 => 6.4.22 
    @storybook/node-logger: ^6.4.22 => 6.4.22 
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0 
    @storybook/react: ^6.4.22 => 6.4.22 
```

**Comment by audishos** [comment]
i was seeing this as well and noticed that you're using node 18. i switched back to 16 and that resolved it. it looks like this is a breaking change related to the upgrade.

**Comment by davesag** [comment]
> i was seeing this as well and noticed that you're using node 18. i switched back to 16 and that resolved it. it looks like this is a breaking change related to the upgrade.

Yep rolling back to Node 17.9.0 and running `npm ci` to nuke and rebuild the node_modules fixed the issue.
