### ISSUE TITLE
sb build fail because `package.json` can't be found in parent directory 

### ISSUE THREAD

**Issue by israelKusayev** [storybookjs/storybook#18229]
**Describe the bug**
I'm trying to upgrade my project to `react-18` so in order to do that I needed to upgrade sb to the next version
So I upgraded from version `6.4.22` to `6.5.0-beta.8`
My app and storybook are running as before
But when I try to build storybook I immediately get an error

I use a monorepo called `apps` and inside I have my client called `pq-client`
I run the build from the pq-client directory but in the error it looks like he can't find a `package.json` file inside `apps` (the parent directory)

```
> pq-client@0.1.0 build:storybook
> build-storybook -s public

info @storybook/react v6.5.0-beta.8
info 
info => Cleaning outputDir: /Users/israelk/workspace/tmp/apps/pq-client/storybook-static
(node:18215) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Copying static files: ./public => ./
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: /Users/israelk/workspace/tmp/apps/package.json: ENOENT: no such file or directory, open '/Users/israelk/workspace/tmp/apps/package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.readFileSync (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/jsonfile/index.js:50:22)
    at getMonorepoType (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/@storybook/telemetry/dist/cjs/get-monorepo-type.js:46:38)
    at _callee2$ (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:210:65)
    at tryCatch (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:72:103)
    at _next (/Users/israelk/workspace/tmp/apps/pq-client/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:74:194) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/israelk/workspace/tmp/apps/package.json'
}
```
**To Reproduce**
I can't reproduce it in a new app
I'm using `cra` and I can give additional info if needed
**System**

**Environment Info:**
  System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/addon-actions: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/addon-essentials: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/addon-interactions: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/addon-links: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/addon-storysource: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/builder-webpack5: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/manager-webpack5: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/node-logger: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/preset-create-react-app: ^4.1.0 => 4.1.0 
    @storybook/react: ^6.5.0-beta.8 => 6.5.0-beta.8 
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Comment by potob** [comment]
The same issue also occurs with me.
It seems to work until version `6.5.0-beta.1`

**Comment by TrevorSayre** [comment]
Possible duplicate of https://github.com/storybookjs/storybook/issues/18229

**Comment by mrkiffie** [comment]
I have encountered the same issue when upgrading to `v6.5.0`.

In my case, the issue is caused by the storybook setup being located in a repo that is itself a git submodule of another repo.

The telemetry code tries to determine what type of repository setup it being run in. It incorrectly assumes that if there is no `.git` directory in the current directory that it should traverse up the tree until it finds a `.git` directory. This results in it leaving the repository that has the storybook config and entering the parent repo. When the parent repository doesn't have a `package.json` file, the error reported above is encountered. 

There are several reasons that I can think of that would cause the `.git` directory to not be in the root of the git repo:
- Submodules
- Multiple working trees
- Running git init with `--separate-git-dir` config

A better way to determine a git repo's root directory would be to use something like `git rev-parse --show-toplevel`

### Telemetry

Attempting to disable the telemetry does not prevent the telemetry code from running.

I've tried setting the env `STORYBOOK_DISABLE_TELEMETRY=1`. I've tried passing in `--disable-telemetry`. I've tried disabling the telemetry in `main.js` by setting `disableTelemetry: true`. None of these options prevent the telemetry code from running and causing this issue.

### To Reproduce

I've created a [repo with a submodule](https://github.com/mrkiffie/storybook-parent-repo#storybook-submodule-repo-issue) that can be used to reproduce the issue.

Let me know if I can provide any additional information.

**Comment by IanVS** [comment]
This is fixed in https://github.com/storybookjs/storybook/pull/18259.  Please try out [6.5.2](https://github.com/storybookjs/storybook/releases/tag/v6.5.2) and let us know if you're still having problems.
