### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push') in preview-preset with custom webpack config

### ISSUE THREAD

**Issue by ntucker** [storybookjs/storybook#18279]
**Describe the bug**
```bash
info => Cleaning outputDir: /home/circleci/project/examples/typescript/storybook-static
info => Loading presets
info => Compiling manager..
info => Compiling preview..
info => Loading custom babel config as JS
ERR! TypeError: Cannot read properties of undefined (reading 'push')
ERR!     at Object.babel (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js:37:18)
ERR!     at /home/circleci/project/node_modules/@storybook/core-common/dist/cjs/presets.js:294:28
ERR!     at async getConfig (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:51:22)
ERR!     at async builderGeneratorFn (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:198:16)
ERR!     at async Object.build (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:286:14)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (/home/circleci/project/node_modules/@storybook/core-server/dist/cjs/build-static.js:218:28)
ERR!     at async buildStatic (/home/circleci/project/node_modules/@storybook/core-server/dist/cjs/build-static.js:254:5)
ERR!  TypeError: Cannot read properties of undefined (reading 'push')
ERR!     at Object.babel (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/presets/preview-preset.js:37:18)
ERR!     at /home/circleci/project/node_modules/@storybook/core-common/dist/cjs/presets.js:294:28
ERR!     at async getConfig (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:51:22)
ERR!     at async builderGeneratorFn (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:198:16)
ERR!     at async Object.build (/home/circleci/project/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:286:14)
ERR!     at async Promise.all (index 1)
ERR!     at async buildStaticStandalone (/home/circleci/project/node_modules/@storybook/core-server/dist/cjs/build-static.js:218:28)
ERR!     at async buildStatic (/home/circleci/project/node_modules/@storybook/core-server/dist/cjs/build-static.js:254:5)
info => Loading presets
lerna ERR! yarn run build:storybook exited 1 in 'example-typescript'
```

Which means in

```js
var babel = async function (config, options) {
  // FIXME: Add this to overrides to only apply to story files
  config.plugins.push('babel-plugin-named-exports-order');
  return config;
};
```

`config` is undefined.

I'm having trouble understanding where this comes from.. as the `@storybook/core-common/dist/cjs/presets.js:294:28`
refers to this line:

```js
      return accumulationPromise.then(function (newConfig) {
        return extensionFn.call(context.preset, newConfig, context.combinedOptions);
      });
```

But why is newConfig undefined? Which means accumulationPromise resolved to undefined? But what is it? This path is so abstract it's unclear how it works together.

**To Reproduce**
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.

1) https://github.com/ntucker/anansi/pull/1512
2) yarn install
3) yarn build:pkg
4) cd examples/typescript
5) yarn storybook

**System**
Please paste the results of `npx sb@next info` here.

```
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
```

[This system is diff from my stacktrace but local reproduces in the same way]

**Additional context**

- Storybook 6.5.3
- Using custom webpack config (that worked with 6.4 of storybook)

### main.js

```js
module.exports = {
  core: {
    builder: "webpack5",
  },
  stories: ['../**/*.stories.tsx'],
  addons: [
    '@storybook/addon-essentials'
  ],
  typescript: {
    reactDocgen: 'react-docgen-typescript',
  },
  reactOptions: {
    fastRefresh: true,
  },
};
```

### preview.tsx

```js
import { Suspense } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { CacheProvider, NetworkManager } from '@rest-hooks/core';
import { NetworkErrorBoundary } from 'rest-hooks';
import 'style/main.scss';


const managers = [new NetworkManager()]
export const decorators = [
  (Story) => (
  <CacheProvider managers={managers}>
    <MemoryRouter initialEntries={['/']}>
      <Suspense fallback={'loading'}>
        <NetworkErrorBoundary>
          <Story/>
        </NetworkErrorBoundary>
      </Suspense>
    </MemoryRouter>
  </CacheProvider>
  )
];
```

### .storybook/.babelrc.js

```js
module.exports = {
  presets: [['@anansi/babel-preset', { typing: 'typescript' }]],
};
```

**Comment by shilman** [comment]
closing as dupe to #18263
