### ISSUE TITLE
After upgrading from version 6.4.19 to 6.5.3 Storybook build fails

### ISSUE THREAD

**Issue by AngelaCandela** [storybookjs/storybook#18291]
**Describe the bug**
After the upgrade from version 6.4.19 to 6.5.3 Storybook build fails when running `npm run storybook`. The error is the following:
```
Error: NormalModuleFactory.beforeResolve (IgnorePlugin, IgnorePlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
at /app/node_modules/webpack/lib/NormalModuleFactory.js:789:11
at Hook.eval [as callAsync] (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
at NormalModuleFactory.create (/app/node_modules/webpack/lib/NormalModuleFactory.js:768:28)
at Compilation._factorizeModule (/app/node_modules/webpack/lib/Compilation.js:1973:11)
at /app/node_modules/webpack/lib/util/AsyncQueue.js:303:10
at Hook.eval [as callAsync] (eval at create (/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
at AsyncQueue._startProcessing (/app/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
at AsyncQueue._ensureProcessing (/app/node_modules/webpack/lib/util/AsyncQueue.js:280:12)
at processImmediate (node:internal/timers:466:21)
```
**System**
Environment Info:
```
  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (3) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 14.19.2 - /usr/bin/node
    npm: 7.20.5 - ~/.local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0
```
**Additional context**
`.storybook/main.ts` configuration:
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "@storybook/preset-create-react-app"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "webpack5"
  }
}
```
`package.json`:
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@reactour/tour": "^2.10.3",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.1",
    "@types/node": "^16.11.26",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.13",
    "leaflet": "^1.7.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-leaflet": "^3.2.5",
    "react-scripts": "5.0.0",
    "react-search-box": "^2.2.1",
    "react-select": "^5.3.1",
    "styled-components": "^5.3.3",
    "typescript": "^4.6.2",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 6006 -s public",
    "build-storybook": "build-storybook -s public",
    "storybook-docs": "start-storybook --docs --no-manager-cache",
    "postinstall": "patch-package"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "overrides": [
      {
        "files": [
          "**/*.stories.*"
        ],
        "rules": {
          "import/no-anonymous-default-export": "off"
        }
      }
    ]
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "devDependencies": {
    "@storybook/addon-actions": "^6.5.3",
    "@storybook/addon-essentials": "^6.5.3",
    "@storybook/addon-interactions": "^6.5.3",
    "@storybook/addon-links": "^6.5.3",
    "@storybook/builder-webpack5": "^6.5.3",
    "@storybook/manager-webpack5": "^6.5.3",
    "@storybook/node-logger": "^6.5.3",
    "@storybook/preset-create-react-app": "^4.1.0",
    "@storybook/react": "^6.5.3",
    "@storybook/testing-library": "^0.0.11",
    "@types/leaflet": "^1.7.9",
    "@types/styled-components": "^5.1.24",
    "patch-package": "^6.4.7",
    "webpack": "^5.70.0"
  }
}
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by fregante** [comment]
Duplicate of https://github.com/storybookjs/storybook/issues/18276
