### ISSUE TITLE
[Angular] Unable to start storybook using the latest version (6.5.4)

### ISSUE THREAD

**Issue by Tim-arts** [storybookjs/storybook#18301]
**Describe the bug**
After upgrading to the latest version, I have multiple errors while launching Storybook:
```js
WARN   Failed to load preset: {"type":"presets","name":"C:\\Users\\user\\Desktop\\storybook-chrono-saeiv\\node_modules\\@storybook\\angular\\dist\\ts3.9\\server\\framework-preset-angular-cli.js"} on level 2
ERR! Error: Cannot find module '@angular-devkit/architect'
ERR! Require stack:
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-common\dist\cjs\index.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core\server.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\dist\ts3.9\server\index.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at Object.<anonymous> (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\dist\ts3.9\server\framework-preset-angular-cli.js:36:21)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!  Error: Cannot find module '@angular-devkit/architect'
ERR! Require stack:
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules
```

After installing `@angular-devkit/architect` as a dev dependency, it fixes the issue above but then I encounter the following one:

```js
ERR! Error: Cannot find module 'style-loader'
ERR! Require stack:
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\preset-scss\index.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-common\dist\cjs\index.js  
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-server\dist\cjs\index.js  
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core\server.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\dist\ts3.9\server\index.js
ERR! - C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\angular\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at Object.webpack (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\preset-scss\index.js:33:35)
ERR!     at C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-common\dist\cjs\presets.js:294:28
ERR!     at starterGeneratorFn (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:116:16)
ERR!     at Object.start (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\builder-webpack5\dist\cjs\index.js:272:14)
ERR!     at async Promise.all (index 0)
ERR!     at storybookDevServer (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-server\dist\cjs\dev-server.js:207:28)
ERR!     at buildDevStandalone (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-server\dist\cjs\build-dev.js:120:31)
ERR!     at Object.buildDev (C:\Users\user\Desktop\storybook-chrono-saeiv\node_modules\@storybook\core-server\dist\cjs\build-dev.js:174:5)
```

And I'm stuck here so far, I believe the MDX issue will kick in after resolving this one.

**To Reproduce**
I have not been able to make any reproduction so far, and the Storybook reproduction tool is broken.

**System**
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
  npmPackages:
    @storybook/addon-a11y: ^6.5.4 => 6.5.4
    @storybook/addon-actions: ^6.5.4 => 6.5.4
    @storybook/addon-docs: ^6.5.4 => 6.5.4
    @storybook/addon-essentials: ^6.5.4 => 6.5.4
    @storybook/addon-interactions: ^6.5.4 => 6.5.4
    @storybook/addon-links: ^6.5.4 => 6.5.4
    @storybook/addon-storysource: ^6.5.4 => 6.5.4
    @storybook/addons: 6.5.4 => 6.5.4
    @storybook/angular: ^6.5.4 => 6.5.4
    @storybook/builder-webpack5: ^6.5.4 => 6.5.4
    @storybook/manager-webpack5: ^6.5.4 => 6.5.4
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/testing-library: ^0.0.11 => 0.0.11
    @storybook/theming: 6.5.4 => 6.5.4

**Comment by alvaromartmart** [comment]
Same here 😞

**Comment by LucasDshg** [comment]
Did u try to install style-loader?

**Comment by rodoabad** [comment]
<img width="383" alt="Screenshot 2022-06-21 at 11 18 28 PM" src="https://user-images.githubusercontent.com/1240667/174942502-87c52fb4-8578-4742-9c98-509b5fa64eb1.png">

There shouldn't be any need to install `style-loader`.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
