### ISSUE TITLE
CLI: Deal with the case where builder & render are known but framework is unknown

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#18360]

**Comment by domyen** [comment]
In cases where there isn't a predefined version, perhaps the CLI can ask the user to eject there own custom pair of renderer  & builder?

```
This project uses Marko and Vite. Storybook doesn't have an automatic configuration for this pair of libraries yet.
Would you like to create your own configuration?
Y/N

#if marko renderer exists
	We found a Marko renderer to render your component. Add it to your config?
	Y/N
#else 
	We couldn't find a renderer for your component. Choose from an existing renderer or create your own.
	[ React, HTML, Vue, etc..., Create your own »]
# endif

#if Vite builder exists
	We found a Vite builder to build your component code. Add it to your config?
	Y/N
#else 
	We couldn't find a builder for your component. Choose from an existing builder or create your own.
	[Webpack4, Webpack5, Snowpack, etc..., Create your own »]
# endif
```

**Comment by SardukarSilver** [comment]
any chance it will be fixed?

**Comment by 9mbs** [comment]
Hi all 👋 thank you for linking this issue in the CLI error. Is there any sort of work-around for this for the immediate time being? 

I'm seeing this in a clean vite app:

```sh
 npx sb init --builder @storybook/builder-vite

Need to install the following packages:
  sb@7.0.11
Ok to proceed? (y) 

 storybook init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
(node:39669) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 • Adding Storybook support to your "React" app
     Error: Sorry, for now, you can not do this, please use a framework such as @storybook/react-webpack5

https://github.com/storybookjs/storybook/issues/18360
    at baseGenerator (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/cli/dist/generate.js:42:11013)
    at async generator3 (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/cli/dist/generate.js:50:5065)
    at async installStorybook (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/cli/dist/generate.js:332:791)
    at async doInitiate (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/cli/dist/generate.js:337:707)
    at async withTelemetry (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/core-server/dist/index.js:35:3422)
    at async initiate (/Users/hi-matbub/.npm/_npx/d28cfb4b54958d89/node_modules/@storybook/cli/dist/generate.js:348:109)
```

The repo if that is needed: https://github.com/9mbs/connect-readme/tree/main/workspaces/components

**Comment by yannbf** [comment]
Hey @9mbs could you please just try `npx storybook@latest init`? The configuration should be automatically detected, or you would get a prompt, so there's no need to pass `--builder` anymore. Could you also please share where you got the `npx sb init --builder @storybook/builder-vite` command from?

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.12 containing PR #22559 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb@latest upgrade
```

**Comment by valentinpalkovic** [comment]
This was a v7-transition triage item: the framework concept has since stabilised with a canonical framework package for every supported renderer×builder combination (16 in v10). The "unknown framework" fallback proposal is no longer needed. Closing as superseded by the v8/v9 framework rollout.
