### ISSUE TITLE
When install Storybook, the project's build failed: "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by fuechter** [storybookjs/storybook#18391]
I installed StorybookJS in an existing project, which builds with Webpack 4. But before installing Storybook, the build works normally, after installing Storybook, the build stops working.

With the following error message:

```
Failed to compile.

Class extends value undefined is not a constructor or null
```

But if I remove these storybook's packages, the project's build run normally:

```
    "@storybook/addon-actions": "6.5.5",
    "@storybook/addon-essentials": "6.5.5",
    "@storybook/addon-interactions": "6.5.5",
    "@storybook/addon-links": "6.5.5",
    "@storybook/builder-webpack4": "6.5.5",
    "@storybook/manager-webpack4": "6.5.5",
    "@storybook/react": "6.5.5",
    "@storybook/testing-library": "0.0.11",
```

A full successful message before install Storybook:

```
Creating an optimized production build...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.7.2

Please only submit bug reports when using the officially supported version.

=============

File sizes after gzip:

  254.09 KB  build/static/js/2.cac7ddd1.chunk.js
  118.28 KB  build/static/js/main.a2711361.chunk.js
  3.85 KB    build/static/css/main.a9a13da9.chunk.css
  3.13 KB    build/static/css/2.759e0710.chunk.css
  784 B      build/static/js/runtime-main.504c5795.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
```

A full error message after install Storybook:

```
Creating an optimized production build...
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.3

Please only submit bug reports when using the officially supported version.

=============
Failed to compile.

Class extends value undefined is not a constructor or null
```

**System**
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1

 **Binaries:**
    Node: 17.3.1 - ~/.nvm/versions/node/v17.3.1/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.1/bin/npm

 **Browsers:**
    Safari: 14.0.3

The storybook's build only work fine.

**Comment by yannbf** [comment]
Hey @fuechter sorry you're experiencing trouble!

I've seen this error happen when there are typos with class based components like this:

```js
import React, { Component } from 'react'

// Error, should be Component
class MyComponent extends component {}

// Error, should be Component
class MyComponent extends Coomponent {}
```

How did you install Storybook? Was it via `npx sb init`? If you're using CRA you should have [@storybook/preset-create-react-app](https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app) installed and registered as an addon too

**Comment by fuechter** [comment]
Hello @yannbf :)

So, why error happen I know, but I find on the whole project and doesn't have any component using Class with extends. It's have only `interface` (Typescript) with extends, but is correctly.

I did install Storybook via `npx storybook init`. This project started with CRA, but sometime react-scripts was ejected, to customize some scripts to the project's need. So if add [@storybook/preset-create-react-app](https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app) on storybook addon, this error happen: 

```
> npm run storybook                                                                                                                                    [INSERT]

> odash-instancias@1.0.0 storybook
> NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006

info @storybook/react v6.5.5
info 
info => Loading presets
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info Addon-docs: using MDX1
ops
info => Using default Webpack4 setup
ERR! WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[2].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at starterGeneratorFn (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
ERR!  - configuration.module.rules[2].oneOf[9].type should be one of these:
ERR!    "javascript/auto" | "javascript/dynamic" | "javascript/esm" | "json" | "webassembly/experimental"
ERR!    -> Module type to use for the module
ERR!     at webpack (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/webpack/lib/webpack.js:31:9)
ERR!     at starterGeneratorFn (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/Users/fuechter/Documents/tetris/bitbucket/odash-instancias/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
```

But some stranger things happened, if I install `@storybook/preset-create-react-app` but don't register as an addon, the storybook's build and the project's build works fine. o.O

**Comment by kevinlin505** [comment]
@fuechter any luck on this one? I am getting something similar with my application. In my case, I have a third party SDK that I am using with my app, and everything works fine with the app itself. But when I try to run storybook, it's in a infinite loading state with the this console error `html-message.js:2 Uncaught TypeError: Class extends value undefined is not a constructor or null1`. Looking this the location on where this happens, it's complaining a extends that happens on the SDK's type file which everything seems fine to me.

![Screen Shot 2023-02-02 at 11 55 13 PM](https://user-images.githubusercontent.com/5324658/216515712-01fcddf3-336b-4bfe-8228-2fb3493c05a3.png)

**Comment by shilman** [comment]
Can you check whether this is still a problem in 7.0? Migration guide: https://storybook.js.org/migration-guides/7.0

Or if you're creating a new project, just:

```
npx sb@next init
```

**Comment by fristaildg** [comment]
I'm having this issue when upgrading to storybook 7 and switching builders from webpack to vite. Any idea?
