### ISSUE TITLE
Fails to install with CRA TS out-of-the-box.

### ISSUE THREAD

**Issue by jolindroth** [storybookjs/storybook#18403]
**Describe the bug**
Fails to install with CRA TS out-of-the-box.

**To Reproduce**
1. Run npx create-react-app my-app --template typescript
2. Run npx storybook init
3. Run npm run storybook

**System**
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.30)
  npmPackages:
    @storybook/addon-actions: ^6.5.6 => 6.5.6
    @storybook/addon-essentials: ^6.5.6 => 6.5.6
    @storybook/addon-interactions: ^6.5.6 => 6.5.6
    @storybook/addon-links: ^6.5.6 => 6.5.6
    @storybook/builder-webpack5: ^6.5.6 => 6.5.6
    @storybook/manager-webpack5: ^6.5.6 => 6.5.6
    @storybook/node-logger: ^6.5.6 => 6.5.6
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2
    @storybook/react: ^6.5.6 => 6.5.6
    @storybook/testing-library: ^0.0.11 => 0.0.11

**Additional context**

Noted that `npx sb@next info` identifies my OS as OS: Windows 10 10.0.22000, but I am running Windows 11 10.0.22000.

**Error output:** 
```
> my-app@0.1.0 storybook
> start-storybook -p 6006 -s public

info @storybook/react v6.5.6
info
(node:14500) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Serving static files from ./public at /
info Addon-docs: using MDX1
info => Loading Webpack configuration from `node_modules\react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/16 entries 2/16 dependencies 0/2 modules
info => Ignoring cached manager due to change in manager config
<i> [webpack-dev-middleware] wait until bundle finished
69% building finish ReactRefreshPluginassets by chunk 6.29 MiB (id hint: vendors)
  assets by status 5.87 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_manager_js-node_modules_storybook_addon-backgrou-076004.manager.bundle.js 4.79 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_formatter-9bb0ae57_js.manager.bundle.js 813 KiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_esm_OverlayScrollbars-9b821cbe_js.manager.bundle.js 295 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_syntaxhighlighter-b09267a2_js.manager.bundle.js 205 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_WithTooltip-2fc4c925_js.manager.bundle.js 126 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_Color-01c31ae2_js.manager.bundle.js 83 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_esm_GlobalScrollAreaStyles-8793ce4a_js.manager.bundle.js 15.6 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.2 KiB [emitted] (name: runtime~main)
asset index.html 3.57 KiB [emitted]
asset main.manager.bundle.js 1.5 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.27 KiB [emitted]
Entrypoint main [big] 4.8 MiB = runtime~main.manager.bundle.js 14.2 KiB vendors-node_modules_storybook_addon-actions_manager_js-node_modules_storybook_addon-backgrou-076004.manager.bundle.js 4.79 MiB main.manager.bundle.js 1.5 KiB
orphan modules 1.03 MiB [orphan] 147 modules
runtime modules 8.7 KiB 15 modules
javascript modules 5.57 MiB 929 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]

WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'

1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

manager (webpack 5.73.0) compiled with 2 warnings in 6319 ms
99% done plugins webpack-hot-middlewarewebpack built preview 7a1ada3dafe7e2057b2b in 10444ms
WARN Force closed manager build
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\repos\front-end-mentor\interactive-rating-component-main\my-app\src\stories\Button.stories.tsx: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "debug". (While processing: "C:\\repos\\front-end-mentor\\interactive-rating-component-main\\my-app\\node_modules\\babel-preset-react-app\\index.js")
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\create.js:58:11)
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\index.js:19:10)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:44:33)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:186:15)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\config\full.js:229:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at processResult (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:860:5    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-loader\lib\index.js:59:103
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\repos\front-end-mentor\interactive-rating-component-main\my-app\src\stories\Header.stories.tsx: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "debug". (While processing: "C:\\repos\\front-end-mentor\\interactive-rating-component-main\\my-app\\node_modules\\babel-preset-react-app\\index.js")
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\create.js:58:11)
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\index.js:19:10)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:44:33)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:186:15)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\config\full.js:229:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at processResult (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:860:5    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-loader\lib\index.js:59:103
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\repos\front-end-mentor\interactive-rating-component-main\my-app\src\stories\Page.stories.tsx: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "debug". (While processing: "C:\\repos\\front-end-mentor\\interactive-rating-component-main\\my-app\\node_modules\\babel-preset-react-app\\index.js")
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\create.js:58:11)
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\index.js:19:10)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:44:33)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:186:15)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\config\full.js:229:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at processResult (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:860:5    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-loader\lib\index.js:59:103
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\repos\front-end-mentor\interactive-rating-component-main\my-app\.storybook\preview.js-generated-config-entry.js: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: "debug". (While processing: "C:\\repos\\front-end-mentor\\interactive-rating-component-main\\my-app\\node_modules\\babel-preset-react-app\\index.js")
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\create.js:58:11)
    at module.exports (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-preset-react-app\index.js:19:10)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:44:33)
    at async (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:186:15)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\gensync\index.js:216:13
    at Generator.next (<anonymous>)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\config\full.js:229:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\@babel\core\lib\gensync-utils\async.js:25:3)
    at Generator.next (<anonymous>)
    at processResult (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:758:19)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\webpack\lib\NormalModule.js:860:5    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:400:11
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\repos\front-end-mentor\interactive-rating-component-main\my-app\node_modules\babel-loader\lib\index.js:59:103

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
No issues found.
99% done plugins webpack-hot-middlewarewebpack built preview 1a1fd3c2d761e65117eb in 1439ms
No issues found.
× Would you like to send crash reports to Storybook? ... yes


attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```

**Comment by jolindroth** [comment]
The issues was caused by having NODE_ENV=debug.
