### ISSUE TITLE
Fresh storybook install fails after `npm update`

### ISSUE THREAD

**Issue by chriskuech** [storybookjs/storybook#18552]
**Describe the bug**

**To Reproduce**
1. Create a `vite` project.
2. Add storybook: `npx storybook init`.
3. Build and run storybook.
4. Note that system runs as expected.
5. Update packages: `npm update`
6. Build and run storybook.
7. Observe the build error:
  ```
  info => Compiling manager..
  vite v2.9.12 building for production...
  ✓ 3 modules transformed.
  [vite]: Rollup failed to resolve import "@storybook/preview-web" from "../../../../virtual:/@storybook/builder-vite/vite-app.js".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  transforming (1371) node_modules/@testing-library/user-event/dist/keyboard/shared/fireInputEvent.jsinfo => Manager built (13 s)
  ERR! Error: [vite]: Rollup failed to resolve import "@storybook/preview-web" from "../../../../virtual:/@storybook/builder-vite/vite-app.js".
  ERR! This is most likely unintended because it can break your application at runtime.
  ERR! If you do want to externalize this module explicitly add it to
  ERR! `build.rollupOptions.external`
  ERR!     at onRollupWarning (/Users/christopherkuech/Repositories/web-client/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
  ERR!     at onwarn (/Users/christopherkuech/Repositories/web-client/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
  ERR!     at Object.onwarn (/Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:23226:13)
  ERR!     at ModuleLoader.handleResolveId (/Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:22510:26)
  ERR!     at /Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:22471:26
  ERR!  Error: [vite]: Rollup failed to resolve import "@storybook/preview-web" from "../../../../virtual:/@storybook/builder-vite/vite-app.js".
  ERR! This is most likely unintended because it can break your application at runtime.
  ERR! If you do want to externalize this module explicitly add it to
  ERR! `build.rollupOptions.external`
  ERR!     at onRollupWarning (/Users/christopherkuech/Repositories/web-client/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41772:19)
  ERR!     at onwarn (/Users/christopherkuech/Repositories/web-client/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:41588:13)
  ERR!     at Object.onwarn (/Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:23226:13)
  ERR!     at ModuleLoader.handleResolveId (/Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:22510:26)
  ERR!     at /Users/christopherkuech/Repositories/web-client/node_modules/rollup/dist/shared/rollup.js:22471:26 {
  ERR!   watchFiles: [
  ERR!     '/Users/christopherkuech/Repositories/web-client/iframe.html',
  ERR!     '/virtual:/@storybook/builder-vite/vite-app.js',
  ERR!     'vite/modulepreload-polyfill',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/vite/package.json',
  ERR!     '/virtual:/@storybook/builder-vite/setup-addons.js',
  ERR!     '/virtual:/@storybook/builder-vite/storybook-stories.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/react/package.json',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-links/package.json',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-actions/package.json',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-interactions/package.json',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/react/dist/esm/client/docs/config.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/react/dist/esm/client/preview/config.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-links/preview.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-actions/preview.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/node_modules/@storybook/addon-interactions/preview.js',
  ERR!     '/Users/christopherkuech/Repositories/web-client/.storybook/preview.js',
  ERR!     'vite/preload-helper'
  ERR!   ]
  ERR! }
  ```

**System**

Environment Info:

  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9
    @storybook/addon-essentials: ^6.5.9 => 6.5.9
    @storybook/addon-interactions: ^6.5.9 => 6.5.9
    @storybook/addon-links: ^6.5.9 => 6.5.9
    @storybook/builder-vite: ^0.1.36 => 0.1.36
    @storybook/react: ^6.5.9 => 6.5.9
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Additional context**
I have also observed #18448 in my repros of this issue.

**Comment by CrisOspina** [comment]
Hi, same error, has anyone found a solution? in my case build-storybook from vercel

```bash
vite v3.2.4 building for production...
--
11:01:14.773 | transforming...
11:01:14.890 | ✓ 3 modules transformed.
11:01:14.890 | [vite]: Rollup failed to resolve import "@storybook/preview-web" from "../../../../virtual:/@storybook/builder-vite/vite-app.js".
info => Manager built (27 s)
--
11:01:39.396 | ERR! Error: [vite]: Rollup failed to resolve import "@storybook/preview-web" from "../../../../virtual:/@storybook/builder-vite/vite-app.js".
11:01:39.397 | ERR! This is most likely unintended because it can break your application at runtime.
11:01:39.397 | ERR! If you do want to externalize this module explicitly add it to
11:01:39.397 | ERR! `build.rollupOptions.external`
```

**Comment by unional** [comment]
Getting these errors when running storybook.

```sh
[plugin:vite:import-analysis] Failed to resolve import "@storybook/preview-web" from "..\..\..\..\..\virtual:\@storybook\builder-vite\vite-app.js". Does the file exist?
/virtual:/@storybook/builder-vite/vite-app.js:1:45
1  |  import { composeConfigs, PreviewWeb } from '@storybook/preview-web';
   |                                              ^
2  |      import { ClientApi } from '@storybook/client-api';
3  |      import '/virtual:/@storybook/builder-vite/setup-addons.js';
```

**Comment by Th3S4mur41** [comment]
Seeing something similar here:

```sh
[vite]: Rollup failed to resolve import "@storybook/preview-web" from "/virtual:/@storybook/builder-vite/vite-app.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
transforming (16) ../../node_modules/@storybook/types/dist/index.mjsinfo => Copying static files: /workspaces/web/node_modules/@atos-parallel/icons at /workspaces/web/packages/docs/dist/
transforming (90) ../../node_modules/@storybook/manager-api/node_modules/semver/internal/constants.jsERR! Error: [vite]: Rollup failed to resolve import "@storybook/preview-web" from "/virtual:/@storybook/builder-vite/vite-app.js".
ERR! This is most likely unintended because it can break your application at runtime.
ERR! If you do want to externalize this module explicitly add it to
ERR! `build.rollupOptions.external`
ERR!     at onRollupWarning (file:///workspaces/web/packages/docs/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44772:19)
ERR!     at onwarn (file:///workspaces/web/packages/docs/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44542:13)
ERR!     at Object.onwarn (file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:24643:13)
ERR!     at ModuleLoader.handleInvalidResolvedId (file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:23327:26)
ERR!     at file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:23287:26
ERR!  Error: [vite]: Rollup failed to resolve import "@storybook/preview-web" from "/virtual:/@storybook/builder-vite/vite-app.js".
ERR! This is most likely unintended because it can break your application at runtime.
ERR! If you do want to externalize this module explicitly add it to
ERR! `build.rollupOptions.external`
ERR!     at onRollupWarning (file:///workspaces/web/packages/docs/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44772:19)
ERR!     at onwarn (file:///workspaces/web/packages/docs/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44542:13)
ERR!     at Object.onwarn (file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:24643:13)
ERR!     at ModuleLoader.handleInvalidResolvedId (file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:23327:26)
ERR!     at file:///workspaces/web/packages/docs/node_modules/rollup/dist/es/shared/rollup.js:23287:26 {
ERR!   watchFiles: [
ERR!     '/workspaces/web/packages/docs/iframe.html',
ERR!     '/virtual:/@storybook/builder-vite/vite-app.js',
ERR!     '\x00vite/modulepreload-polyfill',
ERR!     '/virtual:/@storybook/builder-vite/setup-addons.js',
ERR!     '/virtual:/@storybook/builder-vite/storybook-stories.js',
ERR!     '/workspaces/web/packages/docs/.storybook/preview.js',
ERR!     '\x00vite/preload-helper'
ERR!   ]
ERR! }
npm ERR! Lifecycle script `build:storybook` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @atos-parallel/docs@1.4.0 
npm ERR!   at location: /workspaces/web/packages/docs 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @atos-parallel/docs@1.4.0 
npm ERR!   at location: /workspaces/web/packages/docs 
```

**Comment by valentinpalkovic** [comment]
`@storybook/preview-web` was consolidated into `@storybook/preview-api` in v7 and then into `storybook/preview-api` in v9; `@storybook/builder-vite` was bundled into framework packages (e.g. `@storybook/react-vite`). The Rollup import failure here can no longer occur on current Storybook. Closing as obsolete.
