### ISSUE TITLE
@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236             compilation.hooks.additionalTreeRuntimeRequirements.tap(        ^  TypeError: Cannot read properties of undefined (reading 'tap')

### ISSUE THREAD

**Issue by michaelVictoriaDev** [storybookjs/storybook#18615]
**Describe the bug**
```
npm run dev

> @prosperna/alpha-component-library@0.5.22 dev
> npm run storybook


> @prosperna/alpha-component-library@0.5.22 storybook /Users/mrvictoria/Desktop/Prosperna/alpha-component-library
> start-storybook -p 6006 -s public

info @storybook/react v6.3.11
info
info => Loading presets
info => Serving static files from ./public at /
info => Loading 1 config file in "/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/.storybook"
info => Loading 9 other files in "/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/.storybook"
info => Adding stories defined in "/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/.storybook/main.js"
info => Using prebuilt manager
info => Loading Webpack configuration from `node_modules/react-scripts`
info => Removing existing JavaScript and TypeScript rules.
info => Modifying Create React App rules.
info => Using default Webpack4 setup
0% compiling/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236
            compilation.hooks.additionalTreeRuntimeRequirements.tap(
                                                                ^

TypeError: Cannot read properties of undefined (reading 'tap')
    at /Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:236:65
    at SyncHook.eval [as call] (eval at create (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:17:1)
    at SyncHook.lazyCompileHook (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
    at _next1 (eval at create (/Users/mrvictoria/Desktop/Prosperna/alpha-component-library/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @prosperna/alpha-component-library@0.5.22 storybook: `start-storybook -p 6006 -s public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @prosperna/alpha-component-library@0.5.22 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrvictoria/.npm/_logs/2022-07-01T07_35_30_796Z-debug.log
```

**System**
Please paste the results of `npx sb@next info` here.
```

Environment Info:

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 16.15.0 - /usr/local/opt/nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.11 - /usr/local/opt/nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.17 - ~/Desktop/Prosperna/alpha-component-library/node_modules/.bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Edge: 103.0.1264.44
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^6.3.11 => 6.3.11
    @storybook/addon-essentials: ^6.3.11 => 6.3.11
    @storybook/addon-links: ^6.3.11 => 6.3.11
    @storybook/cli: ^6.3.11 => 6.3.11
    @storybook/node-logger: ^6.3.11 => 6.3.11
    @storybook/preset-create-react-app: ^3.2.0 => 3.2.0
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/react: ^6.3.11 => 6.3.11
```
**Additional context**
Having a weird issue with webpack you might encounter this ? need help..

**Comment by bandinopla** [comment]
and? what was the solution? how is this issue closed without a solution? is this what we are doing now?...

**Comment by Mikadv** [comment]
I had the same issue and now I wonder what was the solution? @michaelVictoriaDev

**Comment by valentinpalkovic** [comment]
The issue is pretty old. @Mikadv Do you experience the same issue with the latest Storybook version and Webpack5?
