### ISSUE TITLE
what is problem?

### ISSUE THREAD

**Issue by neko113** [storybookjs/storybook#18733]
yarn create vite // react-ts
      npx sb init
      yarn storybook 

package.json

        {
          "name": "hello-components",
          "private": true,
          "version": "0.0.0",
          "type": "module",
          "scripts": {
            "dev": "vite",
            "build": "tsc && vite build",
            "preview": "vite preview",
            "storybook": "start-storybook -p 6006",
            "build-storybook": "build-storybook"
          },
          "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0"
          },
          "devDependencies": {
            "@babel/core": "^7.18.6",
            "@storybook/addon-actions": "^6.5.9",
            "@storybook/addon-essentials": "^6.5.9",
            "@storybook/addon-interactions": "^6.5.9",
            "@storybook/addon-links": "^6.5.9",
            "@storybook/builder-vite": "^0.2.0",
            "@storybook/react": "^6.5.9",
            "@storybook/testing-library": "^0.0.13",
            "@types/react": "^18.0.15",
            "@types/react-dom": "^18.0.6",
            "@vitejs/plugin-react": "^2.0.0",
            "babel-loader": "^8.2.5",
            "typescript": "^4.6.4",
            "vite": "^3.0.0"
          }
        }
        
ERROR

❯ yarn storybook
yarn run v1.22.19
warning ../../package.json: No license field
$ start-storybook -p 6006
info @storybook/react v6.5.9
info 
info => Loading presets
info Addon-docs: using MDX1
info => Using implicit CSS loaders
(node:38287) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

info => Using default Webpack4 setup
10% building 1/3 modules 2 active ...ipt-storybook-minimal/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
info => Ignoring cached manager due to change in manager config
10% building 1/5 modules 4 active ...ktop/vite-react-typescript-storybook-minimal/node_modules/@storybook/core-client/dist/esm/globals/globals.jsℹ ｢wdm｣: wait until bundle finished: 
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/kms/Desktop/vite-react-typescript-storybook-minimal/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by neko113** [comment]
Sorry. I changed main.js to main.cjs and nvm version to LTS and it worked fine.
