### ISSUE TITLE
`start-storybook` silently fails, `build-storybook` succeeds

### ISSUE THREAD

**Issue by TheeMattOliver** [storybookjs/storybook#18776]
**Describe the bug**

In a new project, observing that `start-storybook` silently fails while `build-storybook` succeeds

```
Uncaught TypeError: Cannot read properties of undefined (reading 'configure')
    at ./generated-stories-entry.js (generated-stories-entry.js:6:1)
    at __webpack_require__ (bootstrap:853:1)
    at fn (bootstrap:150:1)
    at 0 (storybook-init-framework-entry.js:1:1)
    at __webpack_require__ (bootstrap:853:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.iframe.bundle.js:1:57
```

**To Reproduce**

### Clone repro

`git clone https://github.com/TheeMattOliver/sb-start-storybook-silent-fail-repro.git`

### Install 

```
cd sb-start-storybook-silent-fail-repro
yarn
```
### Start Storybook

`yarn storybook`

Observe silent failure; warning:

```
WARNING in ./node_modules/@storybook/react/node_modules/acorn-jsx/index.js 63:37-43
"export 'default' (imported as '_acorn') was not found in 'acorn'
 @ ./node_modules/@storybook/react/dist/esm/client/docs/lib/inspection/acornParser.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/lib/inspection/inspectValue.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/lib/inspection/index.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/propTypes/rawDefaultPropResolvers.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/propTypes/handleProp.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/extractProps.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/extractArgTypes.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/config.js
 @ ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-interactions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

WARNING in ./generated-stories-entry.js 8:27-42
"export 'default' (imported as '_storybookReact') was not found in '@storybook/react'
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-interactions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
```

### Build Storybook

`yarn build-storybook`

Open index.html in browser, observe success

**System**

```
 npx sb@next info

Environment Info:

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 100.0.1
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/react: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 

```

**Additional context**

Typescript 4.7.4

Here is the result of `npm ls webpack`:

```
├─┬ @storybook/addon-essentials@6.5.9
│ ├─┬ @storybook/addon-docs@6.5.9
│ │ └─┬ babel-loader@8.2.5
│ │   └── webpack@4.46.0 deduped
│ └─┬ @storybook/core-common@6.5.9
│   ├─┬ babel-loader@8.2.5
│   │ └── webpack@4.46.0 deduped
│   ├─┬ fork-ts-checker-webpack-plugin@6.5.2
│   │ └── webpack@4.46.0 deduped
│   └── webpack@4.46.0 deduped
├─┬ @storybook/builder-webpack4@6.5.9
│ ├─┬ babel-loader@8.2.5
│ │ └── webpack@4.46.0 deduped
│ ├─┬ css-loader@3.6.0
│ │ └── webpack@4.46.0 deduped
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@4.46.0 deduped
│ ├─┬ html-webpack-plugin@4.5.2
│ │ └── webpack@4.46.0 deduped
│ ├─┬ postcss-loader@4.3.0
│ │ └── webpack@4.46.0 deduped
│ ├─┬ raw-loader@4.0.2
│ │ └── webpack@4.46.0 deduped
│ ├─┬ style-loader@1.3.0
│ │ └── webpack@4.46.0 deduped
│ ├─┬ terser-webpack-plugin@4.2.3
│ │ └── webpack@4.46.0 deduped
│ ├─┬ url-loader@4.1.1
│ │ └── webpack@4.46.0 deduped
│ ├─┬ webpack-dev-middleware@3.7.3
│ │ └── webpack@4.46.0 deduped
│ ├─┬ webpack-filter-warnings-plugin@1.2.1
│ │ └── webpack@4.46.0 deduped
│ └─┬ webpack@4.46.0
│   └─┬ terser-webpack-plugin@1.4.5
│     └── webpack@4.46.0 deduped
├─┬ @storybook/manager-webpack4@6.5.9
│ ├─┬ @storybook/core-client@6.5.9
│ │ └── webpack@4.46.0 deduped
│ ├─┬ babel-loader@8.2.5
│ │ └── webpack@4.46.0 deduped
│ ├─┬ css-loader@3.6.0
│ │ └── webpack@4.46.0 deduped
│ ├─┬ style-loader@1.3.0
│ │ └── webpack@4.46.0 deduped
│ └── webpack@4.46.0 deduped
├─┬ @storybook/react@6.5.9
│ ├─┬ @pmmmwh/react-refresh-webpack-plugin@0.5.7
│ │ └── webpack@5.73.0 deduped
│ ├─┬ @storybook/core@6.5.9
│ │ ├─┬ @storybook/core-server@6.5.9
│ │ │ └── webpack@4.46.0 deduped
│ │ └── webpack@5.73.0 deduped
│ ├─┬ @storybook/react-docgen-typescript-plugin@1.0.2-canary.6.9d540b91e815f8fc2f8829189deb00553559ff63.0
│ │ └── webpack@5.73.0 deduped
│ └─┬ webpack@5.73.0
│   └─┬ terser-webpack-plugin@5.3.3
│     └── webpack@5.73.0 deduped
├─┬ babel-loader@8.0.4
│ └── webpack@4.46.0 deduped
└─┬ css-loader@3.1.0
  └── webpack@4.46.0 deduped

```

There's also a 65,000 line console warning:

```
Invalid HMR message: {"name":"preview","action":"sync","time":11943,"hash":"47ca1c8cb4b815ea4c3c","warnings":["./node_modules/acorn-jsx/index.js 63:37-43\n\"export 'default' (imported as '_acorn') was not found in 'acorn'","./generated-stories-entry.js 8:27-42\n\"export 'default' (imported as '_storybookReact') was not found in '@storybook/react'"],"errors":[],"modules":{"0":"multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ....
:"./node_modules/util/node_modules/inherits/inherits_browser.js","./node_modules/util/support/isBufferBrowser.js":"./node_modules/util/support/isBufferBrowser.js","./node_modules/util/util.js":"./node_modules/util/util.js","./node_modules/uuid-browser/lib/bytesToUuid.js":"./node_modules/uuid-browser/lib/bytesToUuid.js","./node_modules/uuid-browser/lib/rng-browser.js":"./node_modules/uuid-browser/lib/rng-browser.js","./node_modules/uuid-browser/v4.js":"./node_modules/uuid-browser/v4.js","./node_modules/webpack-hot-middleware/client-overlay.js":"(webpack)-hot-middleware/client-overlay.js","./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined":"(webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined","./node_modules/webpack-hot-middleware/process-update.js":"(webpack)-hot-middleware/process-update.js","./node_modules/webpack/buildin/global.js":"(webpack)/buildin/global.js","./node_modules/webpack/buildin/harmony-module.js":"(webpack)/buildin/harmony-module.js","./node_modules/webpack/buildin/module.js":"(webpack)/buildin/module.js","./node_modules/xtend/immutable.js":"./node_modules/xtend/immutable.js","./src sync recursive ^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|ts|tsx))$":"./src sync ^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|ts|tsx))$","./src sync recursive ^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.mdx)$":"./src sync ^\\.(?:(?:^|\\/|(?:(?:(?!(?:^|\\/)\\.).)*?)\\/)(?!\\.)(?=.)[^/]*?\\.stories\\.mdx)$","./src/Box.tsx":"./src/Box.tsx","./src/Stack.tsx":"./src/Stack.tsx","./src/index.ts":"./src/index.ts","./src/stories/Box.stories.tsx":"./src/stories/Box.stories.tsx","./src/stories/Stack.stories.tsx":"./src/stories/Stack.stories.tsx","./stitches.config.js":"./stitches.config.js","./storybook-init-framework-entry.js":"./storybook-init-framework-entry.js"}}
TypeError: strip is not a function
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
