### ISSUE TITLE
"Invalid version" on build-storybook

### ISSUE THREAD

**Issue by lauterry** [storybookjs/storybook#18791]
Hi

When running `build-storybook`, I got the following error : 

```
**(node:89) UnhandledPromiseRejectionWarning: Error: Invalid version: "2022-07-25-secu-merge-ek"**
    at Object.fixVersionField (/builds/perfectstay/marketing/front/node_modules/normalize-package-data/lib/fixer.js:191:13)
    at /builds/perfectstay/marketing/front/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (/builds/perfectstay/marketing/front/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at AsyncFunction.module.exports.sync (/builds/perfectstay/marketing/front/node_modules/read-pkg/index.js:37:36)
    at AsyncFunction.module.exports.sync (/builds/perfectstay/marketing/front/node_modules/read-pkg-up/index.js:27:24)
    at _callee2$ (/builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:317:46)
    at tryCatch (/builds/perfectstay/marketing/front/node_modules/@storybook/addon-docs/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/builds/perfectstay/marketing/front/node_modules/@storybook/addon-docs/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/builds/perfectstay/marketing/front/node_modules/@storybook/addon-docs/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:66:103)
    at _next (/builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:68:194)
    at /builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:68:3[64](https://gitlab.com/perfectstay/marketing/front/-/jobs/2770797573#L64)
    at new Promise (<anonymous>)
    at /builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:[68](https://gitlab.com/perfectstay/marketing/front/-/jobs/2770797573#L68):97
    at getStorybookMetadata (/builds/perfectstay/marketing/front/node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js:343:18)
```

Indeed, in my work project, the version in the package.json is `2022-07-25-secu-merge-ek`.

We have our custom versioning system.

The problem is that I cannot build storybook anymore.

Is there a way to disable the check on package.json version please or can you remove the check on your side ?

I'm using : 

```
 "@storybook/addon-actions": "^6.5.9",
  "@storybook/addon-essentials": "^6.5.9",
  "@storybook/addon-interactions": "^6.5.9",
  "@storybook/addon-links": "^6.5.9",
  "@storybook/builder-webpack5": "^6.5.9",
  "@storybook/manager-webpack5": "^6.5.9",
  "@storybook/react": "^6.5.9",
  "@storybook/testing-library": "^0.0.13",
```

Best regards

**Comment by DaviesCooper** [comment]
I get the same thing even with a version of "1.x" where x is greater than 9

**Comment by valentinpalkovic** [comment]
To not be blocked the whole time, please try to opt-out from telemetry until the error is not resolved (https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out)

```js
// .storybook/main.js

module.exports = {
  core: {
    disableTelemetry: true, // 👈 Disables telemetry
  },
};
```

@ndelangen Very likely caused by `read-pkg-up` package in `https://github.com/storybookjs/storybook/blob/next/code/lib/telemetry/src/storybook-metadata.ts`, which `normalises` package.json data per default. The https://github.com/npm/normalize-package-data#what-normalization-currently-entails package is throwing an error if the package.json version doesn't follow semver versioning.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.18 containing PR #18806 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
