### ISSUE TITLE
Error: PostCSS plugin postcss-preset-env requires PostCSS 8.

### ISSUE THREAD

**Issue by niloofar-deriv** [storybookjs/storybook#18823]
![Screenshot from 2022-07-31 08-39-58](https://user-images.githubusercontent.com/93518187/182018655-fe96f284-50c8-431d-addc-32d1cc09c1ce.png)
Hi, I'm using storybook with react and lerna. when I run `npm run storybook` I got these error

```
ERROR in /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/components/PropTable/style.css (/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/css-loader/dist/cjs.js??ref--7-1!/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js??ref--7-2!/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/components/PropTable/style.css)
Module build failed (from /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-preset-env requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/builder-webpack4/node_modules/postcss-loader/dist/index.js:95:20)
 @ /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/components/PropTable/style.css 2:26-204 53:4-74:5 56:18-196
 @ /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/components/PropTable/components/Table.js
 @ /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/components/PropTable/index.js
 @ /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/addon-info/dist/index.js
 @ ./stories/wizard/wizard.stories.js
 @ ./stories sync \.stories\.js$
 @ ./.storybook/config.js
 @ ./.storybook/config.js-generated-config-entry.js
 @ multi /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/core-client/dist/esm/globals/globals.js /home/niloofar/Desktop/projects/deriv-app/node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js /home/niloofar/Desktop/projects/deriv-app/node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./.storybook/config.js-generated-config-entry.js
```

**I'm using these versions:**
"postcss-loader": "^7.0.1",
"postcss-preset-env": "^7.7.2",
"postcss-scss": "^4.0.4",
"@storybook/addon-actions": "^6.5.9",
"@storybook/addon-info": "^5.3.21",
"@storybook/addon-links": "^6.5.9",
"@storybook/addon-notes": "^5.3.21",
"@storybook/addon-viewport": "^6.5.9",
"@storybook/addons": "^6.5.9",
"@storybook/react": "^6.5.9",
"@storybook/source-loader": "^6.5.9",
"@storybook/storybook-deployer": "^2.8.12",
"@storybook/addon-knobs": "^6.4.0",
"@wapps/storybook-addon-state": "0.0.4",

Can anybody help me with this issue?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

Storybook no longer has a postcss dep in SB7 and we recommend https://storybook.js.org/addons/@storybook/addon-styling/ for styling issues
