### ISSUE TITLE
Build error with gatsby

### ISSUE THREAD

**Issue by AienTech** [storybookjs/storybook#18855]
Hey there,

We currently have a setup with Gatsby and Storybook. The storybook config is as follows:

```javascript
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-a11y",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-actions",
    "storybook-addon-gatsby",
    "storybook-addon-apollo-client",
    {
      name: "@storybook/addon-postcss",
      options: {
        cssLoaderOptions: {
          // When you have splitted your css over multiple files
          // and use @import('./other-styles.css')
          importLoaders: 1,
        },
        postcssLoaderOptions: {
          // When using postCSS 8
          implementation: require("postcss"),
        },
      },
    },
  ],
  framework: "@storybook/react",
  core: {
    builder: "webpack5",
  },
  webpackFinal: async (config) => {
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/];
    config.module.rules[0].exclude = [/core-js/];
    config.resolve.mainFields = ["browser", "module", "main"];
    return config;
  },
};
```

Unfortunately when running the command `build-storybook -o public/storybook/` we face the following issue:

```
$ build-storybook -o public/storybook/
info @storybook/react v6.5.9
info 
info => Cleaning outputDir: /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/public/storybook/
info => Loading presets
info Found existing addon "@storybook/addon-actions", skipping.
info => Loading custom manager config
info => Compiling manager..
info => Compiling preview..
info => Loading custom manager config
info Addon-docs: using MDX1
info => Using PostCSS preset with postcss@8.4.14
info => Using default Webpack5 setup
17% building 2/16 entries 7599/7700 dependencies 668/1927 modules[BABEL] Note: The code generator has deoptimised the styling of /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/axe-core/axe.js as it exceeds the max of 500KB.
17% building 2/16 entries 7700/8131 dependencies 672/1928 modulesinfo => Manager built (43 s)
18% building 2/16 entries 8900/9039 dependencies 761/2020 modules[BABEL] Note: The code generator has deoptimised the styling of /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/lottie-web/build/player/lottie.js as it exceeds the max of 500KB.
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '@gatsbyjs/reach-router/lib/utils' in '/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/dist'
ERR! Did you mean 'utils.js'?
ERR! BREAKING CHANGE: The request '@gatsbyjs/reach-router/lib/utils' failed to resolve only because it was resolved as fully specified
ERR! (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
ERR! The extension in the request is mandatory for it to be fully specified.
ERR! Add the extension to the request.
64% building 16/16 entries 12325/12377 dependencies 2052/2294 modulesERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@gatsbyjs/reach-router/lib/utils' in '/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/dist'
ERR! Did you mean 'utils.js'?
ERR! BREAKING CHANGE: The request '@gatsbyjs/reach-router/lib/utils' failed to resolve only because it was resolved as fully specified
ERR! (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
ERR! The extension in the request is mandatory for it to be fully specified.
ERR! Add the extension to the request.
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/Compilation.js:2016:28
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:798:13
ERR!     at eval (eval at create (/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:270:22
ERR!     at eval (eval at create (/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:434:22
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:116:11
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:670:25
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:855:8
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:975:5
ERR!  ModuleNotFoundError: Module not found: Error: Can't resolve '@gatsbyjs/reach-router/lib/utils' in '/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/dist'
ERR! Did you mean 'utils.js'?
ERR! BREAKING CHANGE: The request '@gatsbyjs/reach-router/lib/utils' failed to resolve only because it was resolved as fully specified
ERR! (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
ERR! The extension in the request is mandatory for it to be fully specified.
ERR! Add the extension to the request.
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/Compilation.js:2016:28
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:798:13
ERR!     at eval (eval at create (/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:270:22
ERR!     at eval (eval at create (/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:434:22
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:116:11
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:670:25
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:855:8
ERR!     at /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/webpack/lib/NormalModuleFactory.js:975:5
ERR! resolve '@gatsbyjs/reach-router/lib/utils' in '/Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/dist'
ERR!   Parsed request is a module
ERR!   using description file: /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/package.json (relative path: ./dist)
ERR!     Field 'browser' doesn't contain a valid alias configuration
ERR!     resolve as module
ERR!       /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/dist/node_modules doesn't exist or is not a directory
ERR!       looking for modules in /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/node_modules
ERR!         /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/gatsby-link/node_modules/@gatsbyjs/reach-router doesn't exist
ERR!       /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/node_modules doesn't exist or is not a directory
ERR!       looking for modules in /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules
ERR!         existing directory /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/@gatsbyjs/reach-router
ERR!           using description file: /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/@gatsbyjs/reach-router/package.json (relative path: .)
ERR!             using description file: /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/@gatsbyjs/reach-router/package.json (relative path: ./lib/utils)
ERR!               Field 'browser' doesn't contain a valid alias configuration
ERR!               /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/frontend-v2/node_modules/@gatsbyjs/reach-router/lib/utils doesn't exist
ERR!       /Users/aiensaidi/WeAreGroup/Projects/yes/open-banking/node_modules doesn't exist or is not a directory
ERR!       /Users/aiensaidi/WeAreGroup/Projects/yes/node_modules doesn't exist or is not a directory
ERR!       /Users/aiensaidi/WeAreGroup/Projects/node_modules doesn't exist or is not a directory
ERR!       /Users/aiensaidi/WeAreGroup/node_modules doesn't exist or is not a directory
ERR!       /Users/aiensaidi/node_modules doesn't exist or is not a directory
ERR!       /Users/node_modules doesn't exist or is not a directory
ERR!       /node_modules doesn't exist or is not a directory
info => Loading presets
info Found existing addon "@storybook/addon-actions", skipping.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

do I have to provide more context?

**Comment by AienTech** [comment]
are there any news regarding this one here?

I have been trying to test different approaches to get it fixed, unfortunately, there were no luck finding a solution.

**Comment by shilman** [comment]
@AienTech It looks like you're either using a `.mjs` file or have set `type: 'module'` in some package.json and it's messing up some reference to `@gatsbyjs/reach-router/lib/utils` (which I'd expect will work in CJS but will fail in ESM). Is that enough to help you diagnose? If not, and you can provide a publicly accessible reproduction I could take a quick look and see if I can make sense of it.

**Comment by AienTech** [comment]
Thanks @shilman, im gonna test it in a few hours and will report back. In any case this is a good point you mentioned. Thanks for the hint

**Comment by AienTech** [comment]
@shilman regarding the module config, we do not use `module` anywhere in our code. So this is not (as far as I looked) not configured.

I tried to create an example project to share with you, but it seems that on that scale, everything is working as expected.

Things I checked were:
1. `package.json` and the package versions
2. using the same lock file in the example project
3. using almost-the-same components in it

in case it would help, here's our `package.json`:

```json
{
  "author": "WeAreGroup",
  "dependencies": {
    "@apollo/client": "^3.6.6",
    "@headlessui/react": "1.4.1",
    "@heroicons/react": "1.0.4",
    "@reach/router": "^1.3.4",
    "@sentry/gatsby": "^7.3.0",
    "@sentry/tracing": "^7.3.0",
    "@storybook/addon-a11y": "^6.4.9",
    "@storybook/addons": "^6.4.9",
    "@storybook/theming": "^6.4.9",
    "@tailwindcss/forms": "0.3.3",
    "@tailwindcss/typography": "0.4.1",
    "apollo": "^2.34.0",
    "apollo-boost": "^0.4.9",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-upload-client": "16.0.0",
    "autoprefixer": "^10.3.4",
    "canvas": "^2.8.0",
    "connect-history-api-fallback": "^2.0.0",
    "date-fns": "2.23.0",
    "dotenv": "10.0.0",
    "express": "^4.18.1",
    "gatsby": "^4.13.0",
    "gatsby-plugin-gatsby-cloud": "^4.9.1",
    "gatsby-plugin-image": "^2.3.0",
    "gatsby-plugin-manifest": "^4.3.0",
    "gatsby-plugin-offline": "^5.3.0",
    "gatsby-plugin-postcss": "^5.9.0",
    "gatsby-plugin-react-helmet": "^5.3.0",
    "gatsby-source-filesystem": "^4.3.0",
    "i18next": "^21.2.0",
    "i18next-browser-languagedetector": "^6.1.2",
    "i18next-http-backend": "^1.3.1",
    "intl-tel-input": "^17.0.15",
    "isomorphic-fetch": "^3.0.0",
    "jwt-decode": "3.1.2",
    "lodash.debounce": "^4.0.8",
    "lottie-react": "^2.1.0",
    "moment": "^2.29.3",
    "phone": "^3.1.17",
    "postcss-import": "^14.0.2",
    "prop-types": "15.7.2",
    "react": "^16.14.0",
    "react-datepicker": "^4.5.0",
    "react-device-detect": "^2.1.2",
    "react-dom": "^16.14.0",
    "react-dropdown-select": "^4.8.0",
    "react-helmet": "6.1.0",
    "react-i18next": "^11.12.0",
    "react-icomoon": "^2.4.2",
    "react-icons": "^4.3.1",
    "react-intl-tel-input-v2": "^1.0.8",
    "react-lottie": "^1.2.3",
    "react-pdf": "^5.5.0",
    "react-select-country-list": "^2.2.3",
    "react-simple-tooltip": "^2.6.3",
    "react-toastify": "^8.2.0",
    "react-tooltip": "^4.2.21",
    "tailwindcss": "^2.2.15"
  },
  "resolutions": {
    "graphql": "15.x"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@graphql-codegen/cli": "^1.21.3",
    "@graphql-codegen/fragment-matcher": "^1.17.4",
    "@storybook/addon-actions": "^6.4.9",
    "@storybook/addon-essentials": "^6.4.9",
    "@storybook/addon-links": "^6.4.9",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/builder-webpack5": "^6.4.9",
    "@storybook/client-api": "^6.0.0",
    "@storybook/manager-webpack5": "^6.4.9",
    "@storybook/react": "^6.4.9",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.0.0",
    "cssnano": "5.0.8",
    "eslint": "7.32.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-prettier": "8.3.0",
    "eslint-loader": "4.0.2",
    "eslint-plugin-css-modules": "2.11.0",
    "eslint-plugin-graphql": "4.0.0",
    "eslint-plugin-import": "2.24.2",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-react": "7.25.3",
    "eslint-plugin-react-hooks": "4.2.0",
    "eslint-plugin-storybook": "^0.5.3",
    "eslint-webpack-plugin": "^3.1.1",
    "gatsby-plugin-eslint": "4.0.2",
    "postcss": "^8.4.5",
    "prettier": "2.4.1",
    "storybook-addon-apollo-client": "^4.0.9",
    "storybook-addon-gatsby": "0.0.3",
    "typescript": "^4.6.2",
    "webpack": "^5.70.0"
  },
  "license": "RESTRICTED",
  "name": "TPP",
  "scripts": {
    "apollo:schema": "apollo client:download-schema --endpoint=http://localhost:7777/graphql schema.json",
    "build": "gatsby build",
    "clean": "gatsby clean",
    "dev": "npm run develop",
    "develop": "gatsby develop",
    "serve": "gatsby serve",
    "postinstall": "npm run build",
    "start": "node server.js",
    "storybook": "start-storybook -p 6006 -s ./.storybook/public",
    "build-storybook": "build-storybook -o public/storybook/"
  },
  "version": "0.0.1",
  "engines": {
    "node": "14.x"
  }
}
```

also storybook's `manager.js`:
```javascript
import { addons } from "@storybook/addons";
import theme from "./theme";

addons.setConfig({
  theme: theme,
});
```

storybook's `preview.js`:
```javascript
import "../src/styles/global.css";
import { MockedProvider } from "@apollo/client/testing"; // Use for Apollo Version 3+

export const parameters = {
  layout: "fullscreen",
  backgrounds: {
    values: [
      {
        name: "default",
        value: "#F2F2F2",
      },
    ],
  },
  apolloClient: {
    MockedProvider,
    // any props you want to pass to MockedProvider on every story
  },
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
```

**Comment by zhyd1997** [comment]
_**Original Error:**_ 
> ERR! Module not found: Error: Can't resolve '@gatsbyjs/reach-router/lib/utils' in '.../frontend-v2/node_modules/gatsby-link/dist'
>
>ERR! Did you mean 'utils.js'?
>
> ERR! BREAKING CHANGE: The request '@gatsbyjs/reach-router/lib/utils' failed to resolve only because it was resolved as fully specified
>
> ERR! (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
>
> ERR! The extension in the request is mandatory for it to be fully specified.
>
> ERR! Add the extension to the request.

As we seen, the error was reported by `@gatsbyjs/reach-router`, so I searched online and found that there's a `module` field in `package.json`:

https://github.com/gatsbyjs/reach-router/blob/20fcc5e6035b90830f8bafdbad5ff03fbe479f2e/package.json#L6

`module` field seems that is different from `"type": "module"`, and it's not included in [npm documentation](https://docs.npmjs.com/cli/v8/configuring-npm/package-json), but here's an explanation:

[esbuild-API-`module`](https://esbuild.github.io/api/#main-fields)

> node uses "type": "module" instead

from here, I guess the error was caused by `module` field in [@gatsbyjs/reach-route](https://github.com/gatsbyjs/reach-router) 👀 .

**Comment by AienTech** [comment]
@zhyd1997 yeah, it seems to be the issue.

@shilman can we do anything here to have it fixed as soon as possible? since this is quite a blocking point for further development of the software.

tnx

**Comment by zhyd1997** [comment]
@AienTech 

Could you run
`npm ls @gastsbyjs/reach-route` if you're using `npm` or
`yarn why @gatsbyjs/reach-route` if you're using `yarn` for package management?

Maybe there're other alternative packages that do not rely on `@gatsbyjs/reach-route`?

**Comment by AienTech** [comment]
good point @zhyd1997!

here's the result:

```bash
❯ yarn why @gatsbyjs/reach-route
yarn why v1.22.18
warning package.json: License should be a valid SPDX license expression
[1/4] 🤔  Why do we have the module "@gatsbyjs/reach-route"...?
[2/4] 🚚  Initialising dependency graph...
warning TPP@0.0.1: License should be a valid SPDX license expression
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 1.19s.
```

**Comment by AienTech** [comment]
yeah @zhyd1997, this is quite a mystery for me too.

although, we do use `@reach/router`, yet I'm not sure if `@gatsbyjs/reach-route` is being used as a peer dependency or not

**Comment by zhyd1997** [comment]
@AienTech 

It's here: https://github.com/gatsbyjs/gatsby/blob/240dfac529d7501f8497d72da28e8f3150b8e0c2/packages/gatsby-link/package.json#L40

and the package called `gatsby-link` is a dependency of `gatsby`, you can try `yarn why gatsby-link` again to verify it.

**Comment by shilman** [comment]
@AienTech can you trace through the code and find out what code is referencing `/util` instead of `/util.js`, and then either (1) update that code, or (2) eliminate that dependency chain somehow? without a reproduction there is very little we can do from here.

See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce) if you'd like to provide one and I could take a look.

**Comment by AienTech** [comment]
thanks @zhyd1997 for the hint!

sure @shilman, I will do it, I understand that how helpful the example project is, yet I wasn't able to reproduce the error myself in an example, even by using the same dependency and versions.

**Comment by zhyd1997** [comment]
@AienTech 

try set `auto-install-peers=true` as this [discussion](https://github.com/gatsbyjs/gatsby/discussions/35313#discussioncomment-3130798) talked about.
