### ISSUE TITLE
Undifned required prop errors on storyshot when managed by argTypes

### ISSUE THREAD

**Issue by soullivaneuh** [storybookjs/storybook#18903]
**Describe the bug**

If I manage required prop of a component by the `argTypes` options of the related story, I have `console.error` log report telling the value is undefined. 

**To Reproduce**

1. Clone this repro repository branch: https://github.com/soullivaneuh/storybook-repro/tree/args-types-required-props
2. run `npm install`
3. run `npm run test:snapshot`

Output:

```
  console.error
    Warning: Failed prop type: The prop `onClose` is marked as required in `ForwardRef(SwipeableDrawer)`, but its value is `undefined`.
        at SwipeableDrawer (/home/sullivan/p/github.com/soullivaneuh/storybook-repro/node_modules/@mui/material/node/SwipeableDrawer/SwipeableDrawer.js:158:43)
        at Sidebar (/home/sullivan/p/github.com/soullivaneuh/storybook-repro/src/stories/Sidebar.tsx:24:3)
        at storyFn

      28 | }) => {
      29 |   return (
    > 30 |     <SwipeableDrawer
         |     ^
      31 |       data-testid="sidebar"
      32 |       elevation={1}
      33 |       anchor="left"

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:87:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:61:7)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:631:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1164:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1284:7)
      at Sidebar (src/stories/Sidebar.tsx:30:5)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18)

  console.error
    Warning: Failed prop type: The prop `onOpen` is marked as required in `ForwardRef(SwipeableDrawer)`, but its value is `undefined`.
        at SwipeableDrawer (/home/sullivan/p/github.com/soullivaneuh/storybook-repro/node_modules/@mui/material/node/SwipeableDrawer/SwipeableDrawer.js:158:43)
        at Sidebar (/home/sullivan/p/github.com/soullivaneuh/storybook-repro/src/stories/Sidebar.tsx:24:3)
        at storyFn

      28 | }) => {
      29 |   return (
    > 30 |     <SwipeableDrawer
         |     ^
      31 |       data-testid="sidebar"
      32 |       elevation={1}
      33 |       anchor="left"

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:87:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:61:7)
      at checkPropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:631:11)
      at validatePropTypes (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1164:7)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1284:7)
      at Sidebar (src/stories/Sidebar.tsx:30:5)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16305:18
```

**System**

```
Environment Info:

  System:
    OS: Linux 5.18 Manjaro Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Firefox: 103.0.1
  npmPackages:
    @storybook/addon-actions: ^6.5.10 => 6.5.10 
    @storybook/addon-docs: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/addon-interactions: ^6.5.10 => 6.5.10 
    @storybook/addon-links: ^6.5.10 => 6.5.10 
    @storybook/addon-storyshots: ^6.5.10 => 6.5.10 
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10 
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10 
    @storybook/node-logger: ^6.5.10 => 6.5.10 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.10 => 6.5.10 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**

As a workaround, I have to mock the `console.log` functions on the storyshot test file:

```typescript
global.console = {
  ...console,
  log: jest.fn(),
  debug: jest.fn(),
  info: jest.fn(),
  warn: jest.fn(),
  error: jest.fn(),
};
```

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
