### ISSUE TITLE
[ANGULAR] [7.0.0-alpha.19] Cannot find module y18n/build/index

### ISSUE THREAD

**Issue by wouter-willems** [storybookjs/storybook#18926]
**Describe the bug**
When running `npx sb dev` for version `7.0.0-alpha.19` with an angular repository, i get the following error:

```
npx sb dev
@storybook/cli v7.0.0-alpha.19

info => Loading presets
info => Loading presets
info => Loading presets
info => Starting manager..
info => Found custom tsconfig.json
autoprefixer: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
info Addon-docs: using MDX1
info => Using implicit CSS loaders
WARN Force closed manager build
ERR! Error: Cannot find module '/Users/.../node_modules/y18n/build/index'
ERR! Require stack:
ERR! - /Users/.../node_modules/yargs/build/index.cjs
ERR! - /Users/.../node_modules/yargs/helpers/index.js
ERR! - /Users/.../node_modules/@angular/cli/src/command-builder/command-module.js
ERR! - /Users/.../node_modules/@angular/cli/lib/cli/index.js
ERR! - /Users/.../node_modules/@storybook/angular/dist/types/server/framework-preset-angular-cli.js
ERR! - /Users/.../node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/.../node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js
ERR! - /Users/.../node_modules/@storybook/telemetry/dist/cjs/index.js
ERR! - /Users/.../node_modules/@storybook/cli/dist/cjs/initiate.js
ERR! - /Users/.../node_modules/@storybook/cli/dist/cjs/generate.js
ERR! - /Users/.../node_modules/@storybook/cli/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._resolveFilename (/Users/.../node_modules/esbuild-register/dist/node.js:4765:40)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/Users/.../node_modules/yargs/build/index.cjs:1:59774)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Object.newLoader (/Users/.../node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/Users/.../node_modules/esbuild-register/dist/node.js:4801:24)
ERR!  Error: Cannot find module '/Users/.../node_modules/y18n/build/index'
ERR! Require stack:
ERR! - /Users/.../node_modules/yargs/build/index.cjs
ERR! - /Users/.../node_modules/yargs/helpers/index.js
ERR! - /Users/.../node_modules/@angular/cli/src/command-builder/command-module.js
ERR! - /Users/.../node_modules/@angular/cli/lib/cli/index.js
ERR! - /Users/.../node_modules/@storybook/angular/dist/types/server/framework-preset-angular-cli.js
ERR! - /Users/.../node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/.../node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js
ERR! - /Users/.../node_modules/@storybook/telemetry/dist/cjs/index.js
ERR! - /Users/.../node_modules/@storybook/cli/dist/cjs/initiate.js
ERR! - /Users/.../node_modules/@storybook/cli/dist/cjs/generate.js
ERR! - /Users/.../node_modules/@storybook/cli/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.Module._resolveFilename (/Users/.../node_modules/esbuild-register/dist/node.js:4765:40)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:952:19)
ERR!     at require (internal/modules/cjs/helpers.js:88:18)
ERR!     at Object.<anonymous> (/Users/.../node_modules/yargs/build/index.cjs:1:59774)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
ERR!     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
ERR!     at Object.newLoader (/Users/.../node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/Users/.../node_modules/esbuild-register/dist/node.js:4801:24) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/.../node_modules/yargs/build/index.cjs',
ERR!     '/Users/.../node_modules/yargs/helpers/index.js',
ERR!     '/Users/.../node_modules/@angular/cli/src/command-builder/command-module.js',
ERR!     '/Users/.../node_modules/@angular/cli/lib/cli/index.js',
ERR!     '/Users/.../node_modules/@storybook/angular/dist/types/server/framework-preset-angular-cli.js',
ERR!     '/Users/.../node_modules/@storybook/core-common/dist/index.js',
ERR!     '/Users/.../node_modules/@storybook/telemetry/dist/cjs/storybook-metadata.js',
ERR!     '/Users/.../node_modules/@storybook/telemetry/dist/cjs/index.js',
ERR!     '/Users/.../node_modules/@storybook/cli/dist/cjs/initiate.js',
ERR!     '/Users/.../node_modules/@storybook/cli/dist/cjs/generate.js',
ERR!     '/Users/.../node_modules/@storybook/cli/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**System**
Environment Info:

  System:
    OS: macOS 11.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @storybook/addon-actions: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/addon-essentials: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/addon-interactions: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/addon-links: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/angular: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/builder-webpack5: ^7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/cli: 7.0.0-alpha.19 => 7.0.0-alpha.19 
    @storybook/manager-webpack5: ^7.0.0-alpha.10 => 7.0.0-alpha.10 
    @storybook/testing-library: ^0.0.14-next.0 => 0.0.14-next.0 

**Additional context**
In my package.json, i set my type to `module`.
I checked my node_modules, and the `y18n/build/index.cjs` does exist, so i dont get why it is throwing an error.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
