### ISSUE TITLE
[7.0 alpha] React unsupported renderer error

### ISSUE THREAD

**Issue by yogarasu** [storybookjs/storybook#19096]
**Describe the bug**

I get React unsupported renderer error.

```
yogarasu test %npx sb init

 storybook init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
 • Adding Storybook support to your "Create React App" based project

     Error: Unsupported renderer: react
    at componentsPath (/xxxx/test/node_modules/@storybook/cli/dist/cjs/helpers.js:225:11)
    at async copyComponents (/xxxx/test/node_modules/@storybook/cli/dist/cjs/helpers.js:237:31)
    at async baseGenerator (/xxxx/test/node_modules/@storybook/cli/dist/cjs/generators/baseGenerator.js:172:5)
    at async generator (/xxxx/test/node_modules/@storybook/cli/dist/cjs/generators/REACT_SCRIPTS/index.js:57:3)
    at async initiate (/xxxx/test/node_modules/@storybook/cli/dist/cjs/initiate.js:267:3)
```

**To Reproduce**

```zsh
npx create-react-app test --template typescript
cd test
npm i -D @storybook/cli@^7.0.0-alpha.29
npx sb init
```

**System**

```
Environment Info:

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.8.0 - ~/.volta/tools/image/node/18.8.0/bin/node
    npm: 8.19.0 - ~/.volta/tools/image/npm/8.19.0/bin/npm
  npmPackages:
    @storybook/cli: ^7.0.0-alpha.29 => 7.0.0-alpha.29 
```

**Comment by yogarasu** [comment]
In the first place, it was said that CRA was not supported, so it was closed.
