### ISSUE TITLE
Angular How to make basic FormControl work in Storybook

### ISSUE THREAD

**Issue by baruch1995** [storybookjs/storybook#19101]
### Discussed in https://github.com/storybookjs/storybook/discussions/19043

<div type='discussions-op-text'>

<sup>Originally posted by **baruch1995** August 29, 2022</sup>
I asked already in StackOverflow: "Angular How to make basic FormControl work in Storybook"
https://stackoverflow.com/questions/73520031/angular-how-to-make-basic-formcontrol-work-in-storybook

My problem is that I can't create a simple formControl (which needs ReactiveFormsModule) to run correctly in StoryBook.
I have this error in devtools:
```
ERROR TypeError: control.registerOnChange is not a function
    at setUpModelChangePipeline (forms.mjs:3160:1)
    at setUpControl (forms.mjs:2990:1)
    at FormControlDirective.ngOnChanges (forms.mjs:4625:1)
    at FormControlDirective.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1523:1)
    at callHook (core.mjs:2505:1)
    at callHooks (core.mjs:2464:1)
    at executeCheckHooks (core.mjs:2396:1)
    at selectIndexInternal (core.mjs:9830:1)
    at ɵɵadvance (core.mjs:9819:1)
    at TaskComponent_Template (template.html:3:8)
```

But the code below works well when running "ng s -o".
What can I do?

Below is my code:

task.component.ts
```

import { Component,  } from '@angular/core';
import { FormControl } from '@angular/forms';


@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})
export class TaskComponent   {
  name = new FormControl('my text');
}
```

task.component.css
```
.wrapper {
    display: flex;
}
```

task.component.html
```
<div class="wrapper">
    <input type="text" [formControl]="name" />
    <p>Value: {{ name.value }}</p>
</div>
```

task.component.stories.ts
```
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { Meta, Story, moduleMetadata } from '@storybook/angular';

import { TaskComponent } from './task.component';

export default {
  title: 'MyTask',
  component: TaskComponent,
  decorators: [
    moduleMetadata({
      imports: [CommonModule, ReactiveFormsModule],
      declarations: [TaskComponent],
      providers: [],
    }),
  ],
} as Meta;


const Template: Story = (args) => ({
  props: args,
});

export const BasicTask = Template.bind({});
```
</div>

**Comment by ndelangen** [comment]
If your component needs certain props to work, you should supply all those props. It only makes sense your component throws an error, right?
