### ISSUE TITLE
Failed to build the preview => Cannot get final name for export '__esModule' of ./src/node_modules/pretty-format/build/index.js

### ISSUE THREAD

**Issue by jasuno** [storybookjs/storybook#19117]
**Describe the bug**
When trying to run  yarn build-storybook i'm faced with a plug in error

```
ERR!     at Compiler.close (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/lib/Compiler.js:1218:23)
ERR!     at /Users/jasonmatthews/Documents/kera-story-book/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:233:20
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /Users/jasonmatthews/Documents/kera-story-book/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:234:62
ERR!     at /Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/lib/HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Cache.shutdown (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/lib/Cache.js:150:23)
ERR!     at /Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/lib/Compiler.js:1225:15
ERR!     at Hook.eval [as callAsync] (eval at create (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Compiler.close (/Users/jasonmatthews/Documents/kera-story-book/node_modules/webpack/lib/Compiler.js:1218:23)
ERR!     at /Users/jasonmatthews/Documents/kera-story-book/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:233:20
info => Loading presets
error Command failed with exit code 1.
```
**System**
Environment Info:

  ***System:***
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 ***Binaries:***
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  ***Browsers:***
    Chrome: 105.0.5195.102
    Safari: 15.3
  ***npmPackages:***
    @storybook/addon-actions: ^6.5.10 => 6.5.10 
    @storybook/addon-essentials: ^6.5.10 => 6.5.10 
    @storybook/addon-interactions: ^6.5.10 => 6.5.10 
    @storybook/addon-links: ^6.5.10 => 6.5.10 
    @storybook/builder-webpack5: ^6.5.10 => 6.5.10 
    @storybook/manager-webpack5: ^6.5.10 => 6.5.10 
    @storybook/node-logger: ^6.5.10 => 6.5.10 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.10 => 6.5.10 
    @storybook/testing-library: ^0.0.13 => 0.0.13

**Comment by mr-remington** [comment]
I just stumbled into this, appears to be reproducible using a simple web app and the following docker file:
```
FROM node:16.15.1 as build

WORKDIR /wee

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build-storybook
```

**Comment by valentinpalkovic** [comment]
This was a webpack5+babel-loader exports-naming collision in the v6 standalone `@storybook/builder-webpack5` against `pretty-format`. That standalone package was retired in v7 (bundled into framework packages) and the preview build moved to SWC; `pretty-format` is no longer pulled in by the addon chain. Closing as obsolete.
