### ISSUE TITLE
SvelteKit Story disappears if contains nested SCSS styles

### ISSUE THREAD

**Issue by finalspy** [storybookjs/storybook#19131]
**Describe the bug**
I use storybook on a SvelteKit project + SCSS
SCSS works fine in Sveltekit, i mean I can @import @mixins, or use nested styles.
SCSS works fine in Storybook when included from the components being tested (I mean scss declared in the componenet not the story).
Things like "@import @mixins" works fine in the <style> part of the Story. 
But as soon as I nest a style in another one in the <style> part of the Storys, this story dispapears from the browser.

You can try something like : 
```html
<!-- SCSSTest.stories.svelte -->
<script>
  import { Meta, Story } from "@storybook/addon-svelte-csf";
</script>

<Meta title="SCSSTest" />
<Story name="Primary">
  <div class="parent">
    <div>Test SCSS support in Storybook for Svelte</div>
    <div class="child">Should appear in green</div>
  </div>
</Story>

<style lang="scss">
  .parent {
    color: blue;

    .child {
      color: green;
    }
  }
</style>

```
Like that the story isn't displayed.
Remove the nested .child style and it appears properly.

**To Reproduce**
Wasn't able to run this command successfully :  `npx sb@next repro` 

**System**
```
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.15.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    @storybook/addon-actions: ^6.5.9 => 6.5.9 
    @storybook/addon-essentials: ^6.5.9 => 6.5.9 
    @storybook/addon-interactions: ^6.5.9 => 6.5.9 
    @storybook/addon-links: ^6.5.9 => 6.5.9 
    @storybook/addon-svelte-csf: ^2.0.6 => 2.0.6 
    @storybook/builder-webpack4: ^6.5.9 => 6.5.9 
    @storybook/manager-webpack4: ^6.5.9 => 6.5.9 
    @storybook/preset-scss: ^1.0.3 => 1.0.3 
    @storybook/svelte: ^6.5.9 => 6.5.9 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Additional context**
Here's the trace in my developer console 
```
Unexpected error while loading ./_ions/SCSSTEST.stories.svelte: Module build failed (from ./node_modules/.pnpm/@storybook+addon-svelte-csf@2.0.6_3yriknnyu7vebsp22jt4f57l2i/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/svelte-stories-loader.js):
ParseError: Identifier is expected
    at error (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:17805:20)
    at Parser$1.error (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:17881:10)
    at Object.read_style [as read] (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:14414:21)
    at tag (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:16787:34)
    at new Parser$1 (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:17840:22)
    at parse$3 (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:17972:21)
    at Object.compile (/home/username/workspaces/project/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/compiler.js:32355:18)
    at extractStories (/home/username/workspaces/project/node_modules/.pnpm/@storybook+addon-svelte-csf@2.0.6_3yriknnyu7vebsp22jt4f57l2i/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/extract-stories.js:49:32)
    at Object.transformSvelteStories (/home/username/workspaces/project/node_modules/.pnpm/@storybook+addon-svelte-csf@2.0.6_3yriknnyu7vebsp22jt4f57l2i/node_modules/@storybook/addon-svelte-csf/dist/cjs/parser/svelte-stories-loader.js:64:55)
 ./src/components/_ions/SCSSTEST.stories.svelte@http://localhost:6006/main.13444370247f0484f97e.hot-update.js:11:7
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
fn@http://localhost:6006/runtime~main.iframe.bundle.js:151:20
webpackContext@http://localhost:6006/main.iframe.bundle.js:249:9
./node_modules/.pnpm/@storybook+core-client@6.5.9_inmxuyxj2svarauupj5pt4ekma/node_modules/@storybook/core-client/dist/esm/preview/executeLoadable.js/executeLoadable/</<@http://localhost:6006/vendors~main.iframe.bundle.js:7495:32
./node_modules/.pnpm/@storybook+core-client@6.5.9_inmxuyxj2svarauupj5pt4ekma/node_modules/@storybook/core-client/dist/esm/preview/executeLoadable.js/executeLoadable/<@http://localhost:6006/vendors~main.iframe.bundle.js:7493:18
executeLoadable@http://localhost:6006/vendors~main.iframe.bundle.js:7492:10
executeLoadableForChanges@http://localhost:6006/vendors~main.iframe.bundle.js:7541:35
getProjectAnnotations@http://localhost:6006/vendors~main.iframe.bundle.js:7783:128
configure@http://localhost:6006/vendors~main.iframe.bundle.js:7819:9
configure@http://localhost:6006/vendors~main.iframe.bundle.js:17226:10
./generated-stories-entry.js/<@http://localhost:6006/main.iframe.bundle.js:208:36
./generated-stories-entry.js@http://localhost:6006/main.iframe.bundle.js:209:30
__webpack_require__@http://localhost:6006/runtime~main.iframe.bundle.js:854:30
hotApplyInternal@http://localhost:6006/runtime~main.iframe.bundle.js:750:33
hotApply@http://localhost:6006/runtime~main.iframe.bundle.js:412:19
cb@http://localhost:6006/vendors~main.iframe.bundle.js:74006:36
./node_modules/.pnpm/webpack-hot-middleware@2.25.1/node_modules/webpack-hot-middleware/process-update.js/module.exports/check/<@http://localhost:6006/vendors~main.iframe.bundle.js:74021:11
```

Not sure if this is a storybook problem or maybe an *addon-svelte-csf* one ...

**Comment by IanVS** [comment]
We've released a sveletkit storybook framework in the latest 7.0 beta versions.  Can you please try upgrading with `npx sb@next upgrade --prerelease` and letting us know if you're still having problems?

**Comment by finalspy** [comment]
I'll need some time to migrate the original project I noticed the problems on, because i'm not working on it my self nowadays.
We'll get back to you asap

**Comment by finalspy** [comment]
A co worker tested migration to version 7.
Seems there's still a problem, but story now display error (pages disappeared in previous version).
Here's an exemple of those error message: 
![screenshot_from_2023-01-03_16-15-51](https://user-images.githubusercontent.com/413502/210521323-1410d660-0147-463f-b3d9-499dda32dfcd.png)

**Comment by IanVS** [comment]
It looks like the styles aren't being treated as scss. Can you share a minimal reproduction we can look into?
