### ISSUE TITLE
Angular  Digest method not supported

### ISSUE THREAD

**Issue by scottfwalter** [storybookjs/storybook#19201]
**Describe the bug**
I upgraded to Angular 14 and I can't get storybook to build successfullly.  I use
```
    "docs:json": "compodoc -p ./tsconfig.json -e json -d ./projects/storybook",
    "storybook": "npm run docs:json && start-storybook -p 6006 -c ./projects/storybook/.storybook -s ./projects/storybook/.storybook/assets",

 npm run storybook
```

but I get:

```
<i> [webpack-dev-middleware] wait until bundle finished
99% done plugins webpack-hot-middlewarewebpack built preview e26b051da4afc323c53a in 16967ms
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Digest method not supported
    at /Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at processResult (/Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/webpack/lib/NormalModule.js:713:19)
    at /Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/webpack/lib/NormalModule.js:819:5
    at /Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Volumes/T16-Skyhopper/cxone/libs/cxone-ds-components/node_modules/@ngtools/webpack/src/ivy/loader.js:81:9
```

**System**
Here are the relevant packages I have installed:

```
    "@angular-devkit/build-angular": "^14.2.2",
    "@angular-eslint/builder": "^14.0.0",
    "@angular-eslint/eslint-plugin": "^14.0.0",
    "@angular-eslint/eslint-plugin-template": "^14.0.0",
    "@angular-eslint/schematics": "^14.0.0",
    "@angular-eslint/template-parser": "^14.0.0",
    "@angular/cli": "^14.2.2",
    "@angular/compiler-cli": "^14.2.2",
    "@babel/core": "^7.17.10",
    "@compodoc/compodoc": "^1.1.19",
    "@playwright/test": "1.23.4",
    "@storybook/addon-actions": "^6.4.22",
    "@storybook/addon-docs": "^6.4.22",
    "@storybook/addon-essentials": "^6.4.22",
    "@storybook/addon-interactions": "^6.4.22",
    "@storybook/addon-links": "^6.4.22",
    "@storybook/angular": "^6.4.22",
    "@storybook/builder-webpack5": "^6.4.22",
    "@storybook/manager-webpack5": "^6.4.22",
    "@storybook/testing-library": "^0.0.11",
    "@storybook/theming": "^6.4.22",
```

**Comment by BojanKogoj** [comment]
Same error, upgraded to Angular v14.2.2 and @storybook/angular to 6.5.12.

**Comment by BojanKogoj** [comment]
Updating webpack to 5.74.0 fixed the issue.

**Comment by scottfwalter** [comment]
> Updating webpack to 5.74.0 fixed the issue.

That worked for me as well.  Although I am hesitant about using a version of Webpack not certified by Angular.

**Comment by valentinpalkovic** [comment]
Thanks for the original report! This was filed against Storybook 6.5 / `start-storybook`, which was removed in 7.0 (`start-storybook` → `storybook dev`, and the bundled webpack moved out of `@storybook/builder-webpack5` into the framework). Angular projects on Storybook 8/9/10 use the `ng run :storybook` builder against your own Angular webpack, so the "Digest method not supported" mismatch no longer applies. Closing as obsolete — please open a fresh issue with a v10 repro if it reappears.
