### ISSUE TITLE
Svelte Typescript installation from beginning but fails to start up

### ISSUE THREAD

**Issue by hepiBatman** [storybookjs/storybook#19309]
**Describe the bug**
Install Svelte Typescript then add Storybook but get error on startup.

**To Reproduce**
npm create vite@latest myapp -- --template svelte
npx: installed 1 in 0.838s
✔ Select a framework: › Svelte
✔ Select a variant: › TypeScript

cd myapp
npm install
npx sb init
yarn storybook
yarn run v1.22.19

`
(node:90824) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/user1/bit/x/myapp/svelte.config.js
require() of ES modules is not supported.
require() of /Users/user1/bit/x/myapp/svelte.config.js from /Users/user1/bit/x/myapp/.storybook/main.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename svelte.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/user1/bit/x/myapp/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/user1/bit/x/myapp/.storybook/main.cjs:16:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
`

**System**
Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v14.18.3/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 103.0.1
    Safari: 15.6.1

**Additional context**
No issue with Histoire.

**Comment by doolijb** [comment]
Has been happening to be with vite+svelte on every fresh install. Fix is to replace `require` in `.storybook/main.cjs` to `import`.
As so:
```js
"svelteOptions": {
    "preprocess": import("../svelte.config.js").preprocess
  },
  ```
