### ISSUE TITLE
Run generate-repros.sh has an error in generating Vue-CLI (Vue2 JS)

### ISSUE THREAD

**Issue by jeanpierrecarvalho** [storybookjs/storybook#19323]
**Describe the bug**
Run generate-repros.sh has an error in generating Vue-CLI (Vue2 JS)

**To Reproduce**
Run generate-repros.sh script

```
Command failed with exit code 127: yarn create vite . --template react
/bin/sh: 1: /home/*******/.yarn/bin/create-vite: not found
error Command failed.
Exit code: 127
Command: /home/*******/.yarn/bin/create-vite
Arguments: . --template react
Directory: /home/*******/storybook/repros/react-vite/default-js/before-storybook

Output:

    at makeError (/home/*******/storybook/scripts/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/*******/storybook/scripts/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /home/*******/storybook/scripts/next-repro-generators/generate-repros.ts:130:9

(Use `node --trace-warnings ...` to show where the warning was created)
(node:254812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:254812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**System**

Environment Info:

OS Name: Ubuntu 22.04.1 LTS
OS Type: 64-bit

Processor: 11th Gen Intel® Core™ i9-11900K @ 3.50GHz × 16
Memory: 32,0 GiB
Graphics: Mesa Intel® Graphics (RKL GT1)

Binaries:

Node: v14.20.0
Yarn: 1.22.18
Npm: 8.9.2

**Additional context**
No issue with Histoire.

**Comment by valentinpalkovic** [comment]
Thanks for filing! `generate-repros.sh` and the Vue-CLI/Vue 2 repro target it tried to create no longer exist — Vue 2 was dropped in 8.0 and the contributor sandbox tooling has been rewritten since. Closing as obsolete.
