### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (2:39)

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#19378]
**Describe the bug**
Yesterday our storybook was working fine, but today we seem to have a new unexpected error:

```
@foo/box-core: (node:53366) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (2:39)
@foo/box-core:     at Object._raise (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:541:17)
@foo/box-core:     at Object.raiseWithData (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:534:17)
@foo/box-core:     at Object.raise (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:495:17)
@foo/box-core:     at Object.unexpected (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:3580:16)
@foo/box-core:     at Object.jsxParseIdentifier (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7250:12)
@foo/box-core:     at Object.jsxParseNamespacedName (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7260:23)
@foo/box-core:     at Object.jsxParseAttribute (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7345:22)
@foo/box-core:     at Object.jsxParseOpeningElementAfterName (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7366:28)
@foo/box-core:     at Object.jsxParseOpeningElementAt (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7359:17)
@foo/box-core:     at Object.jsxParseElementAt (/Users/dpeck/foo/box/node_modules/@babel/parser/lib/index.js:7391:33)
@foo/box-core: (node:53366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 56)
@foo/box-core: webpack building...
@foo/box-core: webpack built preview e04161d0c9d39937544d in 318ms
```

**System**

devDependencies:
```
"@storybook/addon-actions": "6.5.9",
"@storybook/addon-controls": "6.5.9",
"@storybook/addon-docs": "6.5.9",
"@storybook/addon-knobs": "6.4.0",
"@storybook/addon-links": "6.5.9",
"@storybook/addons": "6.5.9",
"@storybook/preset-scss": "1.0.3",
"@storybook/react": "6.5.9",
"@storybook/theming": "6.5.9",
```

**Comment by dep** [comment]
This was a syntax error within a storybook entry on my part, whoops.

```
<Meta
-  title="Core/Form Elements/Checkboxes",
+  title="Core/Form Elements/Checkbox"
  ...
/>
```
