### ISSUE TITLE
Getting "TypeError: Cannot read property 'initializationPromise' of undefined" on Storyshots after upgrading to React Native 0.66

### ISSUE THREAD

**Issue by matt-dalton** [storybookjs/storybook#19381]
**Describe the bug**
After upgrading to React Native 0.66, our `@storybook/addon-storyshots` storyshot tests now give:
```

    TypeError: Cannot read property 'initializationPromise' of undefined

       7 | // This will automatically generate snapshot tests from
       8 | // anything added to storybook
    >  9 | initStoryshots({ test: multiSnapshotWithOptions() })
         |                              ^
      10 |

      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/index.js:40:44)
      at Object.<anonymous> (App/Components/Storybook/__tests__/storyshots.test.js:9:30)
```

**To Reproduce**
```
Please create a reproduction by running `npx sb@next repro` and following the instructions. Read our [documentation](https://storybook.js.org/docs/react/contribute/how-to-reproduce) to learn more about creating reproductions.
Paste your repository and deployed reproduction here. We prioritize issues with reproductions over those without.
```
I tried running this, but there didn't seem to be an option for React Native, and the command crashed
**System**

Environment Info:

  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1 Pro
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.26 
    @storybook/addon-ondevice-notes: ^5.3.23 => 5.3.26 
    @storybook/addon-storyshots: ^6.5.12 => 6.5.12 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 

**Additional context**
My Jest config is:
```
 "jest": {
    "preset": "react-native",
    "testEnvironment": "jsdom",
    "testMatch": [
      "<rootDir>/**/*.(test|tests).(ts|tsx|js)"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!(@react-native|react-native|@react-native-community|@invertase|@react-navigation|react-native-(.*?)|react-relay-network-modern|date-fns/esm)/)",
      "/node_modules/(?!native-base)/"
    ],
    "transform": {
      "^[./a-zA-Z0-9$_-]+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$": "<rootDir>/node_modules/react-native/jest/assetFileTransformer.js",
      "^.+\\.jsx?$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      ".*(ts|tsx|js|jsx)$": "babel-jest"
    },
    "setupFiles": [
      "./Tests/jestConfig.js",
      "./node_modules/react-native-gesture-handler/jestSetup.js",
      "./__mocks__/finimize-native-modules.js"
    ],
    "setupFilesAfterEnv": [
      "@testing-library/jest-native/extend-expect"
    ],
    "moduleFileExtensions": [
      "js",
      "json",
      "jsx",
      "ts",
      "tsx",
      ".ios.ts",
      ".android.ts",
      "node"
    ],
    "moduleNameMapper": {
      "\\.svg": "<rootDir>/__mocks__/svgMock.js"
    },
    "testPathIgnorePatterns": [
      "/__generated__/"
    ]
  },
```

I trigger the snapshots using 
```
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots'

beforeEach(() => {
    jest.useFakeTimers()
})

// This will automatically generate snapshot tests from
// anything added to storybook
initStoryshots({ test: multiSnapshotWithOptions({}) })
```

**Comment by ketimaBU** [comment]
Facing the same issue here :/ after upgrading react to 18, and RN to 0.70

**Comment by AlexandreCornillon** [comment]
Same issue here. Have solution to restore storyshots ?

**Comment by Levin-nik** [comment]
I have updated the package.

`"@storybook/addon-storyshots": "v7.0.0-beta.8"`

And used this patch.

```
diff --git a/node_modules/@storybook/addon-storyshots/dist/types/api/index.js b/node_modules/@storybook/addon-storyshots/dist/types/api/index.js
index 5a8e067..fff6516 100644
--- a/node_modules/@storybook/addon-storyshots/dist/types/api/index.js
+++ b/node_modules/@storybook/addon-storyshots/dist/types/api/index.js
@@ -36,7 +36,6 @@ function testStorySnapshots(options = {}) {
     // will run *immediately* (in the same tick), and thus the `snapshotsTests`, and
     // subsequent calls to `it()` etc will all happen within this tick, which is required
     // by Jest (cannot add tests asynchronously)
-    globalWindow.__STORYBOOK_STORY_STORE__.initializationPromise.then(() => {
         const data = storybook.raw().reduce((acc, item) => {
             if (storyNameRegex && !item.name.match(storyNameRegex)) {
                 return acc;
@@ -76,6 +75,5 @@ function testStorySnapshots(options = {}) {
         else {
             throw new Error('storyshots found 0 stories');
         }
-    });
 }
 exports.default = testStorySnapshots;
```

Hope it helps

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
