### ISSUE TITLE
Digest method not supported

### ISSUE THREAD

**Issue by naveenkal** [storybookjs/storybook#19393]
### Discussed in https://github.com/storybookjs/storybook/discussions/19392

<div type='discussions-op-text'>

<sup>Originally posted by **naveenkal** October  7, 2022</sup>
I upgraded to Angular 14 and I can't get storybook to build successfully.

Getting below error :

99% done plugins webpack-hot-middlewarewebpack built preview c4fd3adfedabce8e8e4b in 28712ms
WARN Force closed manager build
ModuleBuildError: Module build failed (from /node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Digest method not supported
    at /node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at processResult (/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:701:19)
    at /node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModule.js:807:5
    at /node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /node_modules/@ngtools/webpack/src/ivy/loader.js:81:9
ModuleBuildError: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Digest method not supported

Here are the relevant packages I have installed:

   "@angular-devkit/build-angular": "14.2.0",
    "@angular-eslint/eslint-plugin": "14.0.0",
    "@angular-eslint/eslint-plugin-template": "14.0.0",
    "@angular-eslint/template-parser": "14.0.0",
    "@angular/cli": "~14.2.0",
    "@angular/compiler-cli": "14.2.0",
    "@angular/language-service": "14.2.0",
    "@storybook/angular": "6.5.11",
    "@storybook/builder-webpack5": "6.5.11",
    "@storybook/manager-webpack5": "6.5.11",

</div>

**Comment by ndelangen** [comment]
@naveenkal is this still an issue in 7.0 beta?

**Comment by valentinpalkovic** [comment]
Thanks! This duplicates #19201 — same Angular 14 + SB 6.5 "Digest method not supported" caused by the bundled `@storybook/builder-webpack5` webpack mismatching `@ngtools/webpack`. Builder-webpack5 was consolidated into the framework in 7.0 and `ndelangen` asked for a 7.0-beta confirmation in 2023-01 that never came. Closing as obsolete; happy to look at a v10 repro.
