### ISSUE TITLE
storybook/react is missing renderToDOM function

### ISSUE THREAD

**Issue by MarcelGeo** [storybookjs/storybook#19391]
**Describe the bug**
Cannot start sb dev without error in alpha.35 version. UI is blocked by missin renderToDOM field.

**To Reproduce**
run

npm run storybook caused error

ERR! Error: Cannot find module '@storybook\react\preset'
ERR! Require stack:
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1028:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at $ (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:6:16)
ERR!     at fr (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:20:118)
ERR!     at ye (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:20:207)
ERR!     at C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:22:323
ERR!     at Array.map (<anonymous>)
ERR!     at A (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:22:310)
ERR!     at be (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:22:821)
ERR!     at pr (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\node_modules\@storybook\core-common\dist\index.js:22:1117)
ERR!     at buildDevStandalone (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-server\dist\cjs\build-dev.js:117:50)
ERR!     at async un (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\dist\generate.js:258:1900)
ERR!  Error: Cannot find module '@storybook\react\preset'

UI error

Expected your framework's preset to export a `renderToDOM` field.

Perhaps it needs to be upgraded for Storybook 6.4?

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field

storybook=

**System**
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 16.17.0 - ~\AppData\Local\nvs\default\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - ~\AppData\Local\nvs\default\npm.CMD
  Browsers:
    Chrome: 106.0.5249.91
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.34), ChromiumDev (107.0.1402.2)
  npmPackages:
    @storybook/addon-actions: 7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-essentials: 7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/builder-vite: 0.2.3 => 0.2.3
    @storybook/cli: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/react: 7.0.0-alpha.35 => 7.0.0-alpha.35

**Additional context**

**Comment by BillyCatchpole** [comment]
I had the same problem, but adding the following to the main.js resolved it for me

`  "addons": [
    "@storybook/addon-essentials",
  ],`

**Comment by IanVS** [comment]
@MarcelGeo Canyou run `npx sb@next info` and share the output here?  That will show us what versions of storybook packages you have installed.

**Comment by MarcelGeo** [comment]
@IanVS 

I hate it in description:

@storybook/addon-actions: 7.0.0-alpha.35 => 7.0.0-alpha.35
@storybook/addon-essentials: 7.0.0-alpha.35 => 7.0.0-alpha.35
@storybook/builder-vite: 0.2.3 => 0.2.3
@storybook/cli: ^7.0.0-alpha.35 => 7.0.0-alpha.35
@storybook/react: 7.0.0-alpha.35 => 7.0.0-alpha.35

**Comment by IanVS** [comment]
Ah, you'll need to update builder-vite to 7.0, the same alpha as the rest.

**Comment by hanscl** [comment]
I had the same problem and was able to fix it after some trial and error with dependencies in `packages.json` and `.storybook/main.js`.

I got this output when running storybook -- even though it's just warning, this was the last step for me to get this resolved:
```
WARN Storybook support for Create React App is now a separate preset.
WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
WARN The built-in preset has been disabled in Storybook 6.0.
```

Here is my output from `npx sb@next info`:
```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 103.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/addon-essentials: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/addon-interactions: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/addon-links: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/builder-vite: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/builder-webpack5: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/cli: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/manager-webpack5: ^7.0.0-alpha.10 => 7.0.0-alpha.10
    @storybook/node-logger: ^7.0.0-alpha.34 => 7.0.0-alpha.38
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2
```

My `.storybook/main.js` file:
```JS
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/preset-create-react-app',
  ],
  framework: '@storybook/react-webpack5',
  features: {
    storyStoreV7: true,
  },
  core: {
    builder: '@storybook/builder-webpack5',
  },
};
```

**Comment by MarcelGeo** [comment]
I updated package @storybook/builder-vite to the same version:

npmPackages:
    @storybook/addon-actions: 7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/addon-essentials: 7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/builder-vite: 7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/cli: ^7.0.0-alpha.35 => 7.0.0-alpha.35
    @storybook/react: 7.0.0-alpha.35 => 7.0.0-alpha.35

Error while building still there:

```
info Found existing addon "@storybook/addon-actions", skipping.
info => Loading presets
WARN   Failed to load preset: "@storybook\\react\\preset"
ERR! Error: Cannot find module '@storybook\react\preset'
ERR! Require stack:
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1028:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at $ (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:6:16)
ERR!     at fr (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:20:118)
ERR!     at ye (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:20:207)
ERR!     at C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:22:323
ERR!     at Array.map (<anonymous>)
ERR!     at A (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:22:310)
ERR!  Error: Cannot find module '@storybook\react\preset'
ERR! Require stack:
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\cli\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:804:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1028:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at $ (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:6:16)
ERR!     at fr (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:20:118)
ERR!     at ye (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:20:207)
ERR!     at C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:22:323
ERR!     at Array.map (<anonymous>)
ERR!     at A (C:\Users\marcel.kocisek\Documents\sppd-webapp\node_modules\@storybook\core-common\dist\index.js:22:310) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'C:\\Users\\marcel.kocisek\\Documents\\sppd-webapp\\node_modules\\@storybook\\core-common\\dist\\index.js',
ERR!     'C:\\Users\\marcel.kocisek\\Documents\\sppd-webapp\\node_modules\\@storybook\\telemetry\\dist\\index.js',
ERR!     'C:\\Users\\marcel.kocisek\\Documents\\sppd-webapp\\node_modules\\@storybook\\cli\\dist\\generate.js',
ERR!     'C:\\Users\\marcel.kocisek\\Documents\\sppd-webapp\\node_modules\\@storybook\\cli\\bin\\index.js'
ERR!   ]
ERR! }
info Found existing addon "@storybook/addon-actions", skipping.
info => Serving static files from ./.\public at /
info => Starting manager..
[@vitejs/plugin-react] You should stop using "vite:react-jsx" since this plugin conflicts with it.
[@vitejs/plugin-react] You should stop using "vite:react-jsx" since this plugin conflicts with it. (x2)
╭──────────────────────────────────────────────────╮
│                                                  │
│   Storybook 7.0.0-alpha.35 for react started     │
│   1.95 s for manager and 1.52 s for preview      │
│                                                  │
│    Local:            http://localhost:6006/      │
│    On your network:     │
│                                                  │
╰──────────────────────────────────────────────────╯
15:15:14 [vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename 'C:\PATH\node_modules\.vite-storybook\deps_temp' -> 'C:\PATH\node_modules\.vite-storybook\deps'
```

preset does not exists

**Comment by IanVS** [comment]
@MarcelGeo can you share your `main.cjs`?  

@hanscl Glad you got it working.  FWIW, you no longer need to specify `core.builder` in 7.0 config.  That's handled by the `framework` now.

**Comment by MarcelGeo** [comment]
Hi @IanVS , my main.ts

Error in interface import, but only ts error.

```[typescript]
import react from '@vitejs/plugin-react';
import type { StorybookViteConfig } from '@storybook/builder-vite';

const config: StorybookViteConfig = {
    framework: {
        name: '@storybook/react',
        options: {
            react: react
        }
    },
    stories: [
        '../src/**/*.stories.tsx',
        '../src/**/*.story.tsx'
    ],
    addons: [
        '@storybook/addon-essentials',
        '@storybook/addon-actions'
    ],
    core: {
        builder: '@storybook/builder-vite',
    },
    staticDirs: ['../public'],
    async viteFinal(config, options) {
        config.css = {
            ...config.css,
            preprocessorOptions: {
                less: {
                    javascriptEnabled: true,
                },
            },
        };
        config.plugins = [
            ...config.plugins.filter((plugin) => {
                /** @ts-ignore */
                if (Array.isArray(plugin) && plugin[0].name === 'vite:react-babel') {
                    return false
                }
                return true;
            }),
            react({
                babel: {
                    plugins: [
                        ["@babel/plugin-proposal-decorators", { "legacy": true }]
                    ]
                },
            }),
        ];
        return config;
    },
};

module.exports = config;
```

**Comment by IanVS** [comment]
@MarcelGeo if you're using 7.0, there are some changes that are needed to your config file.  See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field for details, but basically you need to change the `framework` to `@storybook/react-vite` (and install it if it's not already installed in your project, with the same version as the other packages).  Also note, that you don't need to use `viteFinal` anymore, if all you're doing is duplicating config from your `vite.config.js` file, since storybook will read that config automatically now in 7.0.

**Comment by MarcelGeo** [comment]
@IanVS this was helpfull.

**Comment by mandarini** [comment]
@IanVS it's not working on v`7.0.0-beta.25`. `@storybook/react-vite` does not read the vite config automatically, and I still need to use `viteFinal`.

Here is my reproduction repository:
[https://github.com/mandarini/imported-libs](https://github.com/mandarini/imported-libs)

Please read README, it has info on how to reproduce. Essentially:

```
git checkout storybook-7
rm -rf node_modules yarn-lock.json && yarn
npx nx build-storybook main-vite
```

and then go to `apps/main-vite/.storybook/main.js`, remove `viteFinal` and try to build again. It will fail to find the paths.

**Comment by IanVS** [comment]
@mandarini this is because your `vite.config.ts` is not in the same folder as you're running the command from (not in CWD).  A new option was recently added to handle this case, so in the most recent betas, you can update your `main.js` like this:

```js
framework: {
    name: '@storybook/react-vite',
    options: {
      builder: {
        viteConfigPath: 'apps/main-vite/vite.config.ts',
      },
    },
  },
```

When I try this in your repo, after updating to beta.34, it builds fine after removing viteFinal.

**Comment by mandarini** [comment]
Ohhh perfect, thanks!!!! I'll make sure to include this in our generators! Thanks!

**Comment by ZiedHf** [comment]
I get the same error just atfer a fresh storybook install and small change in the package.json.

So let me explain

I have a monorepo and I installed storybook in it's own folder using `npx`

`npx storybook init -p tsx -b vite --package-manager yarn1`

I added my first package and re-installed
See the dependencies, that's the only change I made

```
// storybook/package.json
"devDependencies": {
        "@storybook/addon-essentials": "7.0.0-beta.36",
        "@storybook/addon-interactions": "7.0.0-beta.36",
        "@storybook/addon-links": "7.0.0-beta.36",
        "@storybook/blocks": "7.0.0-beta.36",
        "@storybook/react": "7.0.0-beta.36",
        "@storybook/react-vite": "7.0.0-beta.36",
        "@storybook/testing-library": "0.0.13",
        "prop-types": "15.8.1",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "storybook": "7.0.0-beta.36"
    },
    "dependencies": {
        "@my-packages/package1": "*"
    },
```

Re-installing, and boom 💥 
```
yarn run v1.22.18
$ storybook dev -p 6006
@storybook/cli v7.0.0-beta.36

WARN   Failed to load preset: "@storybook\\react-vite\\preset"
ERR! Error: Cannot find module '@storybook\react-vite\preset'
ERR! Require stack:
ERR! - C:\Workspace\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\Workspace\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\Workspace\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\Workspace\node_modules\@storybook\cli\bin\index.js
ERR! - C:\Workspace\node_modules\storybook\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:6:21)
ERR!     at getContent (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:10:331)
ERR!     at loadPreset (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:10:516)
ERR!     at C:\Workspace\node_modules\@storybook\core-common\dist\index.js:12:409
ERR!     at Array.map (<anonymous>)
ERR!     at loadPresets (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:12:391)
ERR!  Error: Cannot find module '@storybook\react-vite\preset'
ERR! Require stack:
ERR! - C:\Workspace\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\Workspace\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\Workspace\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\Workspace\node_modules\@storybook\cli\bin\index.js
ERR! - C:\Workspace\node_modules\storybook\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!     at interopRequireDefault (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:6:21)
ERR!     at getContent (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:10:331)
ERR!     at loadPreset (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:10:516)
ERR!     at C:\Workspace\node_modules\@storybook\core-common\dist\index.js:12:409
ERR!     at Array.map (<anonymous>)
ERR!     at loadPresets (C:\Workspace\node_modules\@storybook\core-common\dist\index.js:12:391) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'C:\\Workspace\\node_modules\\@storybook\\core-common\\dist\\index.js',
ERR!     'C:\\Workspace\\node_modules\\@storybook\\telemetry\\dist\\index.js',
ERR!     'C:\\Workspace\\node_modules\\@storybook\\cli\\dist\\generate.js',
ERR!     'C:\\Workspace\\node_modules\\@storybook\\cli\\bin\\index.js',
ERR!     'C:\\Workspace\\node_modules\\storybook\\index.js'
ERR!   ]
ERR! }
ERR! Error: no builder configured!
ERR!     at getPreviewBuilder (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:10:1912)
ERR!     at buildDevStandalone (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:33:2135)
ERR!     at async withTelemetry (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:33:5540)
ERR!     at async dev (C:\Workspace\node_modules\@storybook\cli\dist\generate.js:420:3117)
ERR!  Error: no builder configured!
ERR!     at getPreviewBuilder (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:10:1912)
ERR!     at buildDevStandalone (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:33:2135)
ERR!     at async withTelemetry (C:\Workspace\node_modules\@storybook\core-server\dist\index.js:33:5540)
ERR!     at async dev (C:\Workspace\node_modules\@storybook\cli\dist\generate.js:420:3117)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```

My storybook info

```
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Workspace\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.180
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
  npmPackages:
    @storybook/addon-essentials: 7.0.0-beta.36 => 7.0.0-beta.36
    @storybook/addon-interactions: 7.0.0-beta.36 => 7.0.0-beta.36
    @storybook/addon-links: 7.0.0-beta.36 => 7.0.0-beta.36
    @storybook/blocks: 7.0.0-beta.36 => 7.0.0-beta.36
    @storybook/react: 7.0.0-beta.36 => 7.0.0-beta.36
    @storybook/react-vite: 7.0.0-beta.36 => 7.0.0-beta.36
```

Now, even when I remove the dependency, storybook still display the error.

**Comment by ZiedHf** [comment]
@IanVS thank you for you reply.

Maybe this will help someone else :

I had to try `npx storybook@next init -p tsx -b vite --package-manager yarn1 --type react` with the [turbo repo basic example](https://github.com/vercel/turbo/tree/main/examples/basic) to see if that works.

Under package I created a new storybook folder just next to the ui folder
I installed vite, added the ui workspace to package.json

-- apps
   --- web
   --- docs
-- packages
   --- ui
   --- storybook

```
// packages/storybook/packages.json
{
  "name": "storybook",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "storybook": "7.0.0-rc.1",
    "ui": "workspace:*"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "7.0.0-rc.1",
    "@storybook/addon-interactions": "7.0.0-rc.1",
    "@storybook/addon-links": "7.0.0-rc.1",
    "@storybook/blocks": "7.0.0-rc.1",
    "@storybook/react": "7.0.0-rc.1",
    "@storybook/react-vite": "7.0.0-rc.1",
    "@storybook/testing-library": "0.0.14-next.1",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "vite": "^4.1.4"
  },
  "scripts": {
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  }
}
```

For some reason storybook fails to resolve entry for package "ui"

`13:44:42 [vite] Internal server error: Failed to resolve entry for package "ui". The package may have incorrect main/module/exports specified in its package.json.`

So I had to add an alias to viteFinal in main.js

```
async viteFinal(config) {
    return mergeConfig(config, {
      resolve: {
        alias: {
          ui: "../../ui",
        },
      },
    });
  },
```
