### ISSUE TITLE
storybook v7 / vue is missing renderToDOM function - alpha.37

### ISSUE THREAD

**Issue by samydoesit** [storybookjs/storybook#19479]
**Describe the bug**
Tried to migrate our vue storybook project from 6.5 to latest alpha.37.

Probably a duplicate of #19391
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/15785987/195730465-2f1b9b60-a802-4570-82e6-42d486b21ffc.png">

**System**
```
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.17.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 103.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-docs: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/addon-essentials: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/addon-interactions: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/builder-vite: 0.2.4 => 0.2.4 
    @storybook/core-client: ^7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/csf-tools: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/jest: 0.0.10 => 0.0.10 
    @storybook/node-logger: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/store: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/test-runner: 0.9.0 => 0.9.0 
    @storybook/testing-library: 0.0.13 => 0.0.13 
    @storybook/ui: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/vue3: 7.0.0-alpha.37 => 7.0.0-alpha.37 
    @storybook/vue3-vite: 7.0.0-alpha.37 => 7.0.0-alpha.37
```

**Comment by IanVS** [comment]
Can you please share your `.storybook/main.js`?  And double-check that you've run the migration steps in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md.  Running `npx sb@next automigrate` should take care of most of it.

**Comment by samydoesit** [comment]
Storybook [main.ts](https://github.com/samydoesit/vue-turbo-starter/blob/update-to-storybook7/apps/storybook/.storybook/main.ts) looks like this:

```
import { resolve } from 'path'
import type { StorybookViteConfig } from '@storybook/builder-vite'
import Unocss from 'unocss/vite'

const config: StorybookViteConfig = {
  stories: [
    '../stories/**/*.stories.@(js|jsx|ts|tsx|mdx)',
    '../../../packages/ui/src/components/**/*.stories.@(js|jsx|ts|tsx|mdx)',
  ],
  features: {
    interactionsDebugger: true,
    buildStoriesJson: true,
  },
  framework: '@storybook/vue3-vite',
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  viteFinal (config, { configType }) {
    config.resolve.alias = {
      ...config.resolve.alias,
      '@ui': resolve(__dirname, '../../../packages/ui/src'),
    }
    config.plugins = config.plugins ?? []
    config.plugins.push(
      Unocss(),
    )

    if (configType !== 'PRODUCTION') {
      config.optimizeDeps.include = [
        ...(config?.optimizeDeps?.include ?? []),
      ]
    }

    return config
  },
}

export default config
```

Running `npx sb@next automigrate` is unable to detect storybook version because of pnpm.
I tried to double check the migration steps and i can not see any issues.

**Comment by IanVS** [comment]
Ah, sorry I didn't see this before, the problem is:

```
@storybook/builder-vite: 0.2.4 => 0.2.4 
```

This can be removed, since the correct version will be installed by `@storybook/vue3-vite`

Now that I think about it, I've seen this error before.  Can I ask how you did the initial upgrade?  Did you use `npx sb@next upgrade --prerelease`?  We may need to add a step to that script to remove the vite builder.

**Comment by samydoesit** [comment]
Output of `npm ls @storybook/builder-vite`
```
monorepo-turbo-starter git:(update-to-storybook7) npm ls @storybook/builder-vite
monorepo-vue-starter@0.0.0 /Users/sam/Dev/monorepo-turbo-starter
├── @storybook/builder-vite@7.0.0-alpha.40 extraneous -> ./node_modules/.pnpm/@storybook+builder-vite@7.0.0-alpha.40_56jbash75ng5psbctf36wqywr4/node_modules/@storybook/builder-vite
└─┬ @storybook/vue3-vite@7.0.0-alpha.40 extraneous -> ./node_modules/.pnpm/@storybook+vue3-vite@7.0.0-alpha.40_7stpasuheilyvp7llxncnaotee/node_modules/@storybook/vue3-vite
  └── @storybook/builder-vite@7.0.0-alpha.40 extraneous -> ./node_modules/.pnpm/@storybook+builder-vite@7.0.0-alpha.40_56jbash75ng5psbctf36wqywr4/node_modules/@storybook/builder-vite
```
🤔

**Comment by samydoesit** [comment]
I tried again `npx sb@next upgrade --prerelease` and it works like you said.

It has also updated:
```
"@storybook/test-runner": "0.9.1--canary.e75bcdb.0",
"@storybook/testing-library": "0.0.14-next.0",
```


Vite will now be resolved correctly with a `pnpm.override` in place i have update the [repo branch](https://github.com/samydoesit/vue-turbo-starter/tree/update-to-storybook7/apps/storybook) but am still stuck here:
```
sb:dev: 18:41:52 [vite] Internal server error: Missing "./dist/esm/globals/globals.js" export in "@storybook/core-client" package
sb:dev:   Plugin: vite:import-analysis
sb:dev:   File: /virtual:/@storybook/builder-vite/vite-app.js
sb:dev:       at bail (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:33858:8)
sb:dev:       at resolve (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:33935:10)
sb:dev:       at resolveExports (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:35294:12)
sb:dev:       at resolveDeepImport (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:35312:31)
sb:dev:       at tryNodeResolve (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:35020:20)
sb:dev:       at Context.resolveId (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:34781:28)
sb:dev:       at processTicksAndRejections (node:internal/process/task_queues:96:5)
sb:dev:       at async Object.resolveId (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:41338:32)
sb:dev:       at async TransformContext.resolve (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:41107:23)
sb:dev:       at async normalizeUrl (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:38020:34)
sb:dev:       at async TransformContext.transform (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:38159:47)
sb:dev:       at async Object.transform (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:41410:30)
sb:dev:       at async loadAndTransform (file:///Users/sam/Dev/monorepo-turbo-starter/node_modules/.pnpm/vite@3.2.0-beta.2/node_modules/vite/dist/node/chunks/dep-0856a44a.js:37804:29)
sb:dev: [unocss] entry module not found, have you add `import 'uno.css'` in your main entry?
```
<img width="895" alt="image" src="https://user-images.githubusercontent.com/15785987/197008212-ae89aaf2-1e82-4927-b780-e4796e4a53d4.png">

**Comment by IanVS** [comment]
Since the vite builder is at `7.0.0-alpha.40`, are all the rest of your dependencies as well?  You might consider removing your lockfile and node_modules, and re-creating it with a fresh install, to be sure everything's at the same version.  I think you still have a mismatch somewhere.

**Comment by samydoesit** [comment]
I got it.

I have accidentally added this
`"storybook": "future",`
changed it to:
`"storybook": "7.0.0-alpha.40",`

Now it works storybook v7 is running. 💪
