### ISSUE TITLE
7.0.0-alpha.40: Illegal export statement in @mdx-js/react

### ISSUE THREAD

**Issue by AprilArcus** [storybookjs/storybook#19561]
### Describe the bug

With 7.0.0-alpha.40, Jest complains:

```
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /path/to/my/repo/node_modules/@mdx-js/react/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export {
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (../../node_modules/@storybook/addon-docs/dist/cjs/DocsRenderer.js:16:15)
```

I have Babel configured to transpile a set of opt-in node modules using `babel.config.js` in my monorepo root and `rootMode: 'upward'` in my babel-jest config, and I have added `@mdx/react` to my opt-in list. Note that when I disable babel entirely, I receive a more straightforward error:

```
/path/to/my/repo/packages/jest-config/src/setupJest.js:2
    import { noisyTests } from './noisyTests';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)
```

**Comment by AprilArcus** [comment]
A little `console.log` debugging shows that no `options` are being passed to `requireModule` in `node_modules/jest-runtime/build/index.js`, so the babel transformer is being bypassed.

**Comment by valentinpalkovic** [comment]
This was a 7.0-alpha issue where addon-docs still bundled `@mdx-js/react@1`; addon-docs now uses `@mdx-js/react@3` and MDX1 was removed entirely in Storybook 8, so the CJS `DocsRenderer.js`/`@mdx-js/react@1` parse error no longer occurs. Closing as resolved.
