### ISSUE TITLE
[Bug]: Webpack 5 needed for nullish coalition but webpack 5 and esm dont work

### ISSUE THREAD

**Issue by The-Code-Monkey** [storybookjs/storybook#19674]
### Describe the bug

So i have a ESM repo that a package breaks when you update it to the latest version for some reason due to nullish coalition.

but when i setup webpack 5 i get this error on boot.

```ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/iv0706/code/TechStack/node_modules/@storybook/client-api' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
Did you mean 'index.js'?
BREAKING CHANGE: The request '/Users/iv0706/code/TechStack/node_modules/@storybook/client-api' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/iv0706/code/TechStack/node_modules/neo-async/async.js:6883:13
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next0 (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:40:47
    at _next0 (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:132:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:53:42
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:38:14
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve '/Users/iv0706/code/TechStack/node_modules/@storybook/client-api' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
  using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./.storybook)
    Field 'browser' doesn't contain a valid alias configuration
    root path /Users/iv0706/code/TechStack/packages/components
      using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./Users/iv0706/code/TechStack/node_modules/@storybook/client-api)
        Field 'browser' doesn't contain a valid alias configuration
        /Users/iv0706/code/TechStack/packages/components/Users/iv0706/code/TechStack/node_modules/@storybook/client-api doesn't exist
    using description file: /Users/iv0706/code/TechStack/package.json (relative path: ./node_modules/@storybook/client-api)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/iv0706/code/TechStack/node_modules/@storybook/client-api is not a file
ModuleNotFoundError: Module not found: Error: Can't resolve './ThemedWrapper' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
Did you mean 'ThemedWrapper.tsx'?
BREAKING CHANGE: The request './ThemedWrapper' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/iv0706/code/TechStack/node_modules/neo-async/async.js:6883:13
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:892:17
    at finishResolved (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:294:11)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:362:25
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:434:24
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at done (/Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:271:14)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:177:36
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/iv0706/code/TechStack/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/Users/iv0706/code/TechStack/node_modules/webpack/lib/CacheFacade.js:137:15)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:173:18
    at jobDone (/Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:1995:5)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:2275:8
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (/Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:2866:13
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
resolve './ThemedWrapper' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
  using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./.storybook)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./.storybook/ThemedWrapper)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/iv0706/code/TechStack/packages/components/.storybook/ThemedWrapper doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve './i18n' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
Did you mean 'i18n.ts'?
BREAKING CHANGE: The request './i18n' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/iv0706/code/TechStack/node_modules/neo-async/async.js:6883:13
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/NormalModuleFactory.js:892:17
    at finishResolved (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:294:11)
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:362:25
    at /Users/iv0706/code/TechStack/node_modules/enhanced-resolve/lib/Resolver.js:434:24
    at eval (eval at create (/Users/iv0706/code/TechStack/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at done (/Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:271:14)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:177:36
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/iv0706/code/TechStack/node_modules/webpack/lib/Cache.js:107:20)
    at ItemCacheFacade.store (/Users/iv0706/code/TechStack/node_modules/webpack/lib/CacheFacade.js:137:15)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/cache/ResolverCachePlugin.js:173:18
    at jobDone (/Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:1995:5)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:2275:8
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (/Users/iv0706/code/TechStack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (/Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at /Users/iv0706/code/TechStack/node_modules/webpack/lib/FileSystemInfo.js:2866:13
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
resolve './i18n' in '/Users/iv0706/code/TechStack/packages/components/.storybook'
  using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./.storybook)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/iv0706/code/TechStack/packages/components/package.json (relative path: ./.storybook/i18n)
      Field 'browser' doesn't contain a valid alias configuration
      /Users/iv0706/code/TechStack/packages/components/.storybook/i18n doesn't exist

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

info => Loading presets
error Command failed with exit code 1.
```

### To Reproduce

```shell
https://github.com/The-Code-Monkey/TechStack/tree/dev/packages/components
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0
```

**Comment by seonghyeonkimm** [comment]
I faced the same problem recently, Did you find solution?

**Comment by seonghyeonkimm** [comment]
I solved the problem following [this comment](https://github.com/storybookjs/storybook/issues/14938).

**Comment by shilman** [comment]
closing as dupe to #14938
