### ISSUE TITLE
[Bug]: storyshots does not work with vue3

### ISSUE THREAD

**Issue by inthegreenwild** [storybookjs/storybook#19693]
### Describe the bug

Storyshots does not work with Vue3

Error: 
 FAIL  ./storyshots.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:172:18)
      at node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:309:23)

Dependencies: 
```
  "dependencies": {
    "@storybook/addon-storyshots": "^6.5.13",
    "jest-environment-jsdom": "^29.2.2",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@babel/core": "^7.19.6",
    "@storybook/addon-actions": "^6.5.13",
    "@storybook/addon-essentials": "^6.5.13",
    "@storybook/addon-interactions": "^6.5.13",
    "@storybook/addon-links": "^6.5.13",
    "@storybook/builder-vite": "^0.2.5",
    "@storybook/testing-library": "0.0.13",
    "@storybook/vue3": "^6.5.13",
    "@vitejs/plugin-vue": "^3.1.0",
    "@vue/vue3-jest": "^28.1.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^28.0.0",
    "babel-loader": "^8.2.5",
    "jest": "^28.0.0",
    "vite": "^3.1.0",
    "vue-loader": "^16.8.3"
  }
}
```

### To Reproduce

```shell
A repo has been made here https://github.com/inthegreenwild/storyshots-failure 

Clone and run `npm test`
```

### System

```shell
Environment Info:

  System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.62
    Firefox: 103.0.2
    Safari: 16.0
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/addon-storyshots: ^6.5.13 => 6.5.13 
    @storybook/builder-vite: ^0.2.5 => 0.2.5 
    @storybook/testing-library: 0.0.13 => 0.0.13 
    @storybook/vue3: ^6.5.13 => 6.5.13
```

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
