### ISSUE TITLE
[Bug]: v7 build fails with "Invalid option in build() call: "tsconfigRaw"

### ISSUE THREAD

**Issue by rogerfar** [storybookjs/storybook#19792]
### Describe the bug

When running a vite project v7 it errors out with:
```
PS C:\Projects\sbvite> npm run storybook

> sbvite@1.0.0 storybook
> storybook dev -p 6006

@storybook/cli v7.0.0-alpha.48

✘ [ERROR] Invalid option in build() call: "tsconfigRaw"

    C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:12:
      244 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:13)
    at flagsForBuildOptions (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:435:3)
    at buildOrServeContinue (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1228:9)
    at Object.buildOrServe (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1173:9)
    at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2109:14)
    at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2284:67
    at MessagePort.<anonymous> (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2303:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)

✘ [ERROR] Invalid option in build() call: "tsconfigRaw"

    C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:12:
      244 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:13)
    at flagsForBuildOptions (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:435:3)
    at buildOrServeContinue (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1228:9)
    at Object.buildOrServe (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1173:9)
    at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2109:14)
    at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2284:67
    at MessagePort.<anonymous> (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2303:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)

ERR! Error: Build failed with 1 error:
ERR! C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"
ERR!     at failureErrorWithLog (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1624:15)
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1143:18
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1138:9
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:678:9
ERR!     at handleIncomingPacket (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:775:9)
ERR!     at Socket.readFromStdout (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:644:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR!  Error: Build failed with 1 error:
ERR! C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"
ERR!     at failureErrorWithLog (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1624:15)
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1143:18
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1138:9
ERR!     at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:678:9
ERR!     at handleIncomingPacket (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:775:9)
ERR!     at Socket.readFromStdout (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:644:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10) {
ERR!   errors: [
ERR!     {
ERR!       id: '',
ERR!       pluginName: '',
ERR!       text: 'Invalid option in build() call: "tsconfigRaw"',
ERR!       location: [Object],
ERR!       notes: [],
ERR!       detail: Error: Invalid option in build() call: "tsconfigRaw"
ERR!           at checkForInvalidFlags (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:244:13)
ERR!           at flagsForBuildOptions (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:435:3)
ERR!           at buildOrServeContinue (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1228:9)
ERR!           at Object.buildOrServe (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:1173:9)
ERR!           at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2110:17
ERR!           at new Promise (<anonymous>)
ERR!           at Object.build (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2109:14)
ERR!           at C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2284:67
ERR!           at MessagePort.<anonymous> (C:\Projects\sbvite\node_modules\esbuild\lib\main.js:2303:9)
ERR!           at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### To Reproduce

```shell
`npx storybook@next init`
choose `svelte`.
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.48 => 7.0.0-alpha.48
    @storybook/addon-interactions: ^7.0.0-alpha.48 => 7.0.0-alpha.48
    @storybook/addon-links: ^7.0.0-alpha.48 => 7.0.0-alpha.48
    @storybook/svelte: ^7.0.0-alpha.48 => 7.0.0-alpha.48
    @storybook/svelte-webpack5: ^7.0.0-alpha.48 => 7.0.0-alpha.48
    @storybook/testing-library: ^0.0.13 => 0.0.13
```
```


### Additional context

_No response_

**Comment by amccloud** [comment]
Running into the same on a react project migration to 7.0.0-alpha.48. Was previously using 6 with:

```ts
    core: { 
        builder: "webpack5" 
    },
```

Now using `framework: "@storybook/react-webpack5"`

**Comment by ermik** [comment]
`tsconfigRaw` is a Transformer API option; affected functionality seems to be using Builder API which supports `tsconfig` (without `raw`) [parameter](https://esbuild.github.io/api/#tsconfig).

**Comment by tmeasday** [comment]
This was resolved with a reversion in `esbuild-register`: https://github.com/egoist/esbuild-register/commit/4d83bae16838a231fa830cfa14d77f92944700e2

**Comment by elie222** [comment]
Run `npm i esbuild` for anyone else that runs into this. This fixed it for me.
