### ISSUE TITLE
[Bug]: `storybook init` doesn't work with `pnpm`

### ISSUE THREAD

**Issue by NatoBoram** [storybookjs/storybook#19811]
### Describe the bug

I'm trying to create a new project with SvelteKit, TypeScript and Storybook but it's pretty difficult. I'm encountering a wide range of issues.

This one is about setting up the project in a fresh, new, extra virgin workspace.

1. Despite the project being setup with `pnpm`, having a `pnpm-lock.yaml` and no `package-lock.json`, the dependencies that `storybook` installs are fetched through `npm`, drastically increasing the install time.
2. It doesn't work

### To Reproduce

```shell
pnpm create svelte@latest test_project
# ✔ Which Svelte app template? › Skeleton project
# ✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
# ✔ Add ESLint for code linting? … Yes
# ✔ Add Prettier for code formatting? … Yes
# ✔ Add Playwright for browser testing? … Yes

cd test_project
pnpm i
pnpx storybook init
```

### System

```shell
Environment Info:

  System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 106.0.3
```

### Additional context

```typescript
 storybook init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
    Detected vite project, setting builder to @storybook/builder-vite
info Configuring preprocessor from 'svelte.config.js'
 • Adding Storybook support to your "Svelte" app

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:./src/types

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nato/.npm/_logs/2022-11-11T21_17_23_773Z-debug-0.log
An error occurred while installing dependencies.


 ERROR  Command failed with exit code 1: /home/nato/.local/share/pnpm/store/v3/tmp/dlx-100191/node_modules/.bin/storybook init

pnpm: Command failed with exit code 1: /home/nato/.local/share/pnpm/store/v3/tmp/dlx-100191/node_modules/.bin/storybook init
    at makeError (/home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:22415:17)
    at handlePromise (/home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:22986:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:193613:7)
    at async /home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:200906:21
    at async main (/home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:200877:34)
    at async runPnpm (/home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:201101:5)
    at async /home/nato/.cache/node/corepack/pnpm/7.15.0/dist/pnpm.cjs:201093:7
```

**Comment by NatoBoram** [comment]
Got it. We have to replace `pnpx storybook init` by this:

```sh
pnpm i -g storybook@next
storybook init
```

However, this means the instructions at https://storybook.js.org/docs/svelte/get-started/install are wrong.
