### ISSUE TITLE
[Bug]:Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function

### ISSUE THREAD

**Issue by amolbs2106** [storybookjs/storybook#19922]
### Describe the bug

Getting below error for one of the custom element in angular:

Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at TabsComponent.LifecycleElement [as constructor] (lifecycleElement.js:9:28)
    at TabsComponent.CustomElement [as constructor] (customElement.js:22:47)
    at new TabsComponent (tabs.js:32:47)
    at DefaultDomRenderer2.createElement (platform-browser.mjs:549:25)
    at BaseAnimationRenderer.createElement (animations.mjs:240:30)
    at createElementNode (core.mjs:7023:25)
    at ɵɵelementStart (core.mjs:14562:43)
    at WktaaeClientAddModalComponent_Template (template.html:4:9)
    at executeTemplate (core.mjs:9647:9)
    at renderView (core.mjs:9447:13)

**Comment by valentinpalkovic** [comment]
This is a classic ES5-target custom-elements transpilation error from the 2022 Angular/webpack toolchain (down-leveling `class extends HTMLElement`). Angular now requires v18+ with a modern build target and the webpack5 web-components builder was dropped in v9. Closing as stale  -  please open a fresh issue with a v10 + Angular 18+ repro if it persists.
