### ISSUE TITLE
[Nextjs 13]: preview.js-generated-config-entry.js.ts doesn't exist

### ISSUE THREAD

**Issue by BibiSebi** [storybookjs/storybook#19941]
### Describe the bug

Today I was trying to create a project using Nextjs 13 + Storybook, however no success so far. 

I have tried it with multiple node versions but this is the current one I am using:
```
node: v18.8.0
npm: 8.18.0
```

Here are my dependencies from `package.json`:
```
"dependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.28.0",
    "eslint-config-next": "13.0.4",
    "next": "13.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@storybook/addon-actions": "^6.5.13",
    "@storybook/addon-essentials": "^6.5.13",
    "@storybook/addon-interactions": "^6.5.13",
    "@storybook/addon-links": "^6.5.13",
    "@storybook/builder-webpack5": "^6.5.13",
    "@storybook/manager-webpack5": "^6.5.13",
    "@storybook/react": "^6.5.13",
    "@storybook/testing-library": "^0.0.13",
    "babel-loader": "^8.3.0",
    "eslint-plugin-storybook": "^0.6.7"
  }
```

I also configured the following inside `next.config.js`:
```
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  webpack: (
      config,
      { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }
  ) => {
    // Important: return the modified config
    return config
  },
}

module.exports = nextConfig
```

added a `.babelrc` with: 
```
{
  "presets": ["next/babel"],
  "plugins": []
}
```
and a `.npmrc`: 

`legacy-peer-deps=true`

To run it I used `npm run storybook` and I am getting the following error: 

```
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/user/Documents/workspace/storyblok/next-a11y/.storybook/preview.js-generated-config-entry.js' in '/Users/user/Documents/workspace/storyblok/next-a11y'
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/neo-async/async.js:6883:13
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/AliasPlugin.js:125:14
    at next (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/forEachBail.js:14:3)
    at forEachBail (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/forEachBail.js:24:9)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/AliasPlugin.js:51:5
    at _next0 (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/user/Documents/workspace/storyblok/next-a11y/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at callback (/Users/user/Documents/workspace/storyblok/next-a11y/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:211:21)
```

### System

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.4
  npmPackages:
    @storybook/addon-actions: ^6.5.13 => 6.5.13 
    @storybook/addon-essentials: ^6.5.13 => 6.5.13 
    @storybook/addon-interactions: ^6.5.13 => 6.5.13 
    @storybook/addon-links: ^6.5.13 => 6.5.13 
    @storybook/builder-webpack5: ^6.5.13 => 6.5.13 
    @storybook/manager-webpack5: ^6.5.13 => 6.5.13 
    @storybook/react: ^6.5.13 => 6.5.13 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by BibiSebi** [comment]
Found an answer in [#19927](https://github.com/storybookjs/storybook/issues/19927)
