### ISSUE TITLE
[Bug]: @storybook/react 7.0.0-alpha.54 not working with @storybook/react-vite 7.0.0-alpha.46

### ISSUE THREAD

**Issue by itsjoekent** [storybookjs/storybook#20013]
### Describe the bug

In upgrading from @storybook/react from 7.0.0-alpha.43 to @storybook/react 7.0.0-alpha.54, we are encountering an error loading any story in our storybook.

```
Expected your framework's preset to export a `renderToDOM` field.
Perhaps it needs to be upgraded for Storybook 6.4?
More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#mainjs-framework-field
```

This document suggests we add a `framework` field to our `main.js` file, which we have,

```js
framework: '@storybook/react-vite',
```

### To Reproduce

We are currently running Storybook 7 with the following packages,

```shell
    "@storybook/addon-a11y": "^7.0.0-alpha.43",
    "@storybook/addon-actions": "7.0.0-alpha.43",
    "@storybook/addon-docs": "^7.0.0-alpha.43",
    "@storybook/addon-essentials": "^7.0.0-alpha.43",
    "@storybook/addon-knobs": "^6.0.21",
    "@storybook/addons": "^7.0.0-alpha.43",
    "@storybook/builder-vite": "^7.0.0-alpha.46",
    "@storybook/mdx2-csf": "^0.1.0-next.2",
    "@storybook/react": "^7.0.0-alpha.54",
    "@storybook/react-vite": "^7.0.0-alpha.46",
```

And the following configuration,

```js
const { mergeConfig } = require('vite');
const tsconfigPaths = require('vite-tsconfig-paths').default;
const checker = require('vite-plugin-checker').default;

module.exports = {
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-essentials',
    '@storybook/addon-actions',
    '@storybook/addon-a11y',
  ],
  core: { builder: '@storybook/builder-vite' },
  features: {
    previewMdx2: true,
  },
  framework: '@storybook/react-vite',
  staticDirs: ['../src'],
  stories: [
    '../src/components/**/*.stories.mdx',
    '../src/themes/*.stories.mdx',
  ],
  typescript: {
    reactDocgenTypescriptOptions: {
      skipChildrenPropWithoutDoc: true,
      shouldExtractLiteralValuesFromEnum: true,
      shouldRemoveUndefinedFromOptional: true,
      // We have a custom prop filter, but removed it here since it seemed irrelevant to the error.
      propFilter: prop => {},
    },
  },
  viteFinal: config =>
    mergeConfig(config, {
      define: {
        'process.env': {
          NODE_ENV: process.env.NODE_ENV,
        },
      },
      plugins: [tsconfigPaths(), checker({ typescript: true })],
    }),
};
```

### System

```shell
Environment Info:

  System:
    OS: macOS 11.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
    Safari: 15.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-alpha.43 => 7.0.0-alpha.43 
    @storybook/addon-actions: 7.0.0-alpha.43 => 7.0.0-alpha.43 
    @storybook/addon-docs: ^7.0.0-alpha.43 => 7.0.0-alpha.43 
    @storybook/addon-essentials: ^7.0.0-alpha.43 => 7.0.0-alpha.43 
    @storybook/addon-knobs: ^6.0.21 => 6.4.0 
    @storybook/addons: ^7.0.0-alpha.43 => 7.0.0-alpha.43 
    @storybook/builder-vite: ^7.0.0-alpha.46 => 7.0.0-alpha.46 
    @storybook/mdx2-csf: ^0.1.0-next.2 => 0.1.0-next.2 
    @storybook/react: ^7.0.0-alpha.54 => 7.0.0-alpha.54 
    @storybook/react-vite: ^7.0.0-alpha.46 => 7.0.0-alpha.46
```

**Comment by yannbf** [comment]
Hey @itsjoekent please make sure that your storybook packages are aligned with their versions. Can you pick one version and update all of them to that version,preferably the most recent? Thanks!

**Comment by itsjoekent** [comment]
@yannbf Thanks for the suggestion, this leads to a different error when I pin all of the packages to `^7.0.0-alpha.55`

```
> sb build -c .storybook -o .out

@storybook/cli v7.0.0-alpha.43

info => Cleaning outputDir: /.out

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

info => Loading presets
info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
info => Building manager..
✘ [ERROR] Could not resolve "undefined/manager"

✘ [ERROR] Could not resolve "undefined/manager"

✘ [ERROR] Could not resolve "undefined/manager"

✘ [ERROR] Could not resolve "undefined/manager"

✘ [ERROR] Could not resolve "undefined/manager"

✘ [ERROR] Could not resolve "undefined/manager"

info => Loading presets
info Found existing addon "@storybook/addon-docs", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
✔ Would you like to send crash reports to Storybook? … yes
ERR! Error: Build failed with 6 errors:
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! ...
ERR!     at failureErrorWithLog (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1624:15)
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1266:28
ERR!     at runOnEndCallbacks (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1046:63)
ERR!     at buildResponseToResult (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1264:7)
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1377:14
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:678:9
ERR!     at handleIncomingPacket (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:775:9)
ERR!     at Socket.readFromStdout (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:644:7)
ERR!     at Socket.emit (node:events:390:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!  Error: Build failed with 6 errors:
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! error: Could not resolve "undefined/manager"
ERR! ...
ERR!     at failureErrorWithLog (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1624:15)
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1266:28
ERR!     at runOnEndCallbacks (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1046:63)
ERR!     at buildResponseToResult (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1264:7)
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:1377:14
ERR!     at /Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:678:9
ERR!     at handleIncomingPacket (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:775:9)
ERR!     at Socket.readFromStdout (/Users/joe.kent/dev/arcadia/shrike/node_modules/esbuild/lib/main.js:644:7)
ERR!     at Socket.emit (node:events:390:28)
ERR!     at addChunk (node:internal/streams/readable:315:12) {
ERR!   errors: [
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     },
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: null,
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'Could not resolve "undefined/manager"'
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }
```

**Comment by itsjoekent** [comment]
Hi @yannbf I did some more digging into where this bug above might be coming from,

I put a console log [here](https://github.com/storybookjs/storybook/blob/next/code/lib/core-common/src/presets.ts#L104) 

```
console.log(name, ' -- ', managerFile);
```

and this is the output I'm getting,

```
@storybook/addon-docs  --  undefined
@storybook/addon-essentials  --  undefined
@storybook/addon-actions  --  /Users/joe.kent/dev/arcadia/shrike/node_modules/@storybook/addon-actions/manager
@storybook/addon-a11y  --  /Users/joe.kent/dev/arcadia/shrike/node_modules/@storybook/addon-a11y/manager
info Found existing addon "@storybook/addon-docs", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
@storybook/addon-essentials/controls  --  undefined/manager
@storybook/addon-essentials/backgrounds  --  undefined/manager
@storybook/addon-essentials/viewport  --  undefined/manager
@storybook/addon-essentials/toolbars  --  undefined/manager
@storybook/addon-essentials/measure  --  undefined/manager
@storybook/addon-essentials/outline  --  undefined/manager
@storybook/addon-essentials/highlight  --  undefined
@storybook/react  --  undefined
```

I am guessing the `undefined/manager` here explains why the above error is happening.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by stephenh** [comment]
FWIW @yannbf I was getting this error too, following the migration guide, I'd added:

```
  "devDependencies": {
    "storybook": "future"
  }
```

To my package.json, but for some reason yarn was resolving that to an older version:

```
$ yarn storybook
@storybook/cli v7.0.0-alpha.34

...lots of errors about `undefined/manager`...
```

Even though I was using "future" and the rest of my `@storybook/*` deps were 7.0.0-beta.55.

Setting `storybook` exactly to the same version as the rest of my deps worked:

```
    "storybook": "^7.0.0-beta.55",
```

Is this expected? Fwiw I've never seen/used the "future" semver version before, but dunno, doesn't seem like it was working for me. I'm using yarn 3.2.4:

```
$ ls .yarn/releases/
yarn-3.2.4.cjs*
```

In a pretty stock, non-workspace yarn setup:

```
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
```

**Comment by onionhammer** [comment]
Just got this error with latest storybook alpha

**Comment by stephenh** [comment]
@onionhammer does it work if you set the `"storybook"` dep to the same version as the rest of the `@storybook/*` dependencies? Like for me that was:

```
    "storybook": "^7.0.0-beta.55",
```

**Comment by onionhammer** [comment]
@stephenh I'm not getting it anymore, I think I saw this exception, I had messed something up with the storybook version.

**Comment by Kephass** [comment]
Why is this issue closed? I'm getting the same issue. Did anyone find a workaround?

**Comment by hanifmhd** [comment]
any update on this? i get the same error

**Comment by shawnb-gv** [comment]
Did anyone ever solve this? We're having the same issue.

**Comment by yannbf** [comment]
@Kephass @shawnb-gv @hanifmhd please list every storybook dependency and version you have. That includes the `@storybook/*` packages but also the `storybook` package. If they all have the same number in your package json, they could still be misaligned because of your lock files, so please try deleting your lock files and reinstalling, then report back <3

**Comment by shawnb-gv** [comment]
Deleting the lock file and reinstalling dependencies fixed it. Thanks!
