### ISSUE TITLE
Ensure error message you get when using storiesOf in ssv7 mode is very clear

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20146]
Does it explain what's wrong? Does it link to the appropriate MIGRATION.md entry? Does the MIGRATION.md explain what to do to upgrade (or downgrade to ssv6)?

- [ ] Test in Vite project
- [ ] Test in Webpack project
- [ ] Do we want to add an automigration as well?

**Comment by tmeasday** [comment]
Currently (in Vite, although I think likely the same in WP), it says on the terminal:

```
WARN 🚨 Unable to index ./src/components/IAlert/examples/index-storiesOf.stories.ts:
WARN   Error: CSF: unexpected storiesOf call /Users/tom/GitHub/inkline/inkline/src/components/IAlert/examples/index-storiesOf.stories.ts (line 14, col 0)
WARN
WARN More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#story-store-v7
WARN     at enter (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:66:5304)
WARN     at NodePath._call (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:26692)
WARN     at NodePath.call (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:26514)
WARN     at NodePath.visit (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:27650)
WARN     at TraversalContext.visitQueue (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:61144)
WARN     at TraversalContext.visitSingle (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:60779)
WARN     at TraversalContext.visit (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:61469)
WARN     at traverseNode (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:62041)
WARN     at NodePath.visit (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:27819)
WARN     at TraversalContext.visitQueue (/Users/tom/GitHub/inkline/inkline/node_modules/@storybook/csf-tools/dist/index.js:58:61144)
```

The place it points to (https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#story-store-v7) is a 6.5 migration note and isn't super helpful.
