### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading '__emotion_styles')

### ISSUE THREAD

**Issue by iweurman** [storybookjs/storybook#20162]
### Describe the bug

I'm using the latest material ui v5 and storybook packages.
When trying to run a dom snapshot test using the @storybook/addon-storyshots addon
it giving me the following error:

`TypeError: Cannot read properties of undefined (reading '__emotion_styles')

      4 | import i18n, { supportedLanguages, defaultLanguage } from '../src/i18n'
      5 | import { Suspense } from 'react'
    > 6 | import {
        | ^
      7 |   ThemeProvider,
      8 |   GlobalStyleProvider,

      at internal_processStyles (node_modules/@mui/styled-engine/node/index.js:70:25)
      at node_modules/@mui/system/createStyled.js:100:45
      at Object.<anonymous> (node_modules/@mui/material/Modal/Modal.js:49:42)
      at Object.<anonymous> (node_modules/@mui/material/Modal/index.js:25:38)
      at Object.<anonymous> (node_modules/@mui/material/Dialog/Dialog.js:16:37)
      at Object.<anonymous> (node_modules/@mui/material/Dialog/index.js:22:38)
      at Object.<anonymous> (node_modules/@mui/material/index.js:1411:39)`

**Comment by utkarsh22garg** [comment]
Any updates ? Facing the same issue

**Comment by mnajdova** [comment]
We cannot know what may be the issue without a clear reproduction. Which version of emotion are you using?

**Comment by ndelangen** [comment]
Without a reproduction, there is nothing we can really do here.

I suspect it's very likely fixed in storybook 7.0 beta, but there's no way to know without a repro.
