### ISSUE TITLE
[Bug]: esbuild fails with `ERROR: Invalid option in build() call: "jsxImportSource"`

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20215]
### Describe the bug

We use `jsxImportSource` as an option to `esbuild`:

https://github.com/storybookjs/storybook/blob/aa110b9a3b7e01c4a6ab0a5b499ab02d04d50266/code/lib/builder-manager/src/index.ts#L66

However the feature was introduced in `0.14.51`: https://github.com/evanw/esbuild/pull/2349

And we only depend on 

https://github.com/storybookjs/storybook/blob/aa110b9a3b7e01c4a6ab0a5b499ab02d04d50266/code/lib/builder-manager/package.json#L52

### To Reproduce

```shell
Not 100% clear, somehow it happened in that in this project that has no other clear dependency on `esbuild` I ended up with `0.14.49`. The error is:


✘ [ERROR] Invalid option in build() call: "jsxImportSource"

    /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:241:12:
      241 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:241:13)
    at flagsForBuildOptions (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:424:3)
    at buildOrServeContinue (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1213:9)
    at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1142:13

ERR! Error: Build failed with 1 error:
ERR! /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:241:12: ERROR: Invalid option in build() call: "jsxImportSource"
ERR!     at failureErrorWithLog (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1605:15)
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1131:18
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1126:9
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:666:9
ERR!     at handleIncomingPacket (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:763:9)
ERR!     at Socket.readFromStdout (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:632:7)
ERR!     at Socket.emit (node:events:390:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR!  Error: Build failed with 1 error:
ERR! /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:241:12: ERROR: Invalid option in build() call: "jsxImportSource"
ERR!     at failureErrorWithLog (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1605:15)
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1131:18
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:1126:9
ERR!     at /Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:666:9
ERR!     at handleIncomingPacket (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:763:9)
ERR!     at Socket.readFromStdout (/Users/tom/GitHub/inkline/inkline/node_modules/esbuild/lib/main.js:632:7)
ERR!     at Socket.emit (node:events:390:28)
```

**Comment by tmeasday** [comment]
Note that it was easily fixed in this project via `npm upgrade esbuild`, which took it to `0.14.54`

**Comment by ndelangen** [comment]
related: #20199

**Comment by tmeasday** [comment]
Ok, will close, thanks @ndelangen
