### ISSUE TITLE
[Bug]: [7.0.0-beta.21]: SyntaxError: Identifier '__esbuild_register_import_meta_url__' has already been declared

### ISSUE THREAD

**Issue by Semigradsky** [storybookjs/storybook#20418]
### Describe the bug

After updating from `7.0.0-beta.14` to `7.0.0-beta.15` I have this error:

```
ERR! /home/dmitry/P/ui-kit/node_modules/@storybook/builder-manager/node_modules/find-cache-dir/index.js:2
ERR! const __esbuild_register_import_meta_url__ = require("url").pathToFileURL(__filename).href;
ERR!       ^
ERR!
ERR! SyntaxError: Identifier '__esbuild_register_import_meta_url__' has already been declared
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1088:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1123:27)
ERR!     at Module._compile (/home/dmitry/P/ui-kit/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at extensions..js (/home/dmitry/P/ui-kit/node_modules/esbuild-register/dist/node.js:4814:15)
ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
ERR!     at Module._load (node:internal/modules/cjs/loader:878:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (/home/dmitry/P/ui-kit/node_modules/@storybook/builder-manager/dist/index.js:1:3099)
```

I use `framework: '@storybook/react-webpack5',` in my `.storybook/main.ts`.

@ndelangen maybe it related to 30e3d45e599402c1329d199862763c957a5560a4?

### System

```shell
Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.2.0 - ~/.yarn/bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```

### Additional context

`7.0.0-beta.14` works nice.

**Comment by Semigradsky** [comment]
`find-cache-dir@4` is esm module

**Comment by marvinroger** [comment]
I'm also having this issue, using `framework: '@storybook/react-vite'`

**Comment by LorenzoLeonardini** [comment]
Same with `@storybook/sveltekit`

**Comment by MarksCode** [comment]
Also getting this

**Comment by furkanalptokac** [comment]
Same error, 7.0.0-beta.19

**Comment by ndelangen** [comment]
Does someone have a reproduction for me ready to use?

I just got back from my vacation, and will prioritize solving this next early week

**Comment by LorenzoLeonardini** [comment]
Hi here is my reproduction with my Svelte project setup:
https://github.com/LorenzoLeonardini/storybook-issue-reproduction

**Comment by Semigradsky** [comment]
New error in v21 after #20532:
```
WARN   Failed to load preset: ".../node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js"
ERR! .../node_modules/@storybook/builder-webpack5/node_modules/slash/index.js:2
ERR! const __esbuild_register_import_meta_url__ = require("url").pathToFileURL(__filename).href;
ERR!       ^
ERR!
ERR! SyntaxError: Identifier '__esbuild_register_import_meta_url__' has already been declared
ERR!     at Object.compileFunction (node:vm:360:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1088:15)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1123:27)
ERR!     at Module._compile (/home/dmitry/P/ui-kit/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at extensions..js (/home/dmitry/P/ui-kit/node_modules/esbuild-register/dist/node.js:4814:15)
ERR!     at Module.load (node:internal/modules/cjs/loader:1037:32)
ERR!     at Module._load (node:internal/modules/cjs/loader:878:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1061:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (.../node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:1:1627)
```

@ndelangen `@storybook/builder-webpack5` uses `slash@5` but it is esm module too.

**Comment by ndelangen** [comment]
@Semigradsky thanks for reporting, I'll downgrade that!

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.23 containing PR #20543 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tdryjard** [comment]
Cause for me : 
`/tsconfig.json

"paths": {
      "*": ["src/*", "node_modules/*"]
    }`
