### ISSUE TITLE
[Bug]: [v7.0.0-beta.15] Typescript `import type` can't be parsed (by default)

### ISSUE THREAD

**Issue by ivangabriele** [storybookjs/storybook#20423]
### Describe the bug

Storybook v7 supports Typescript [out of the box](https://storybook.js.org/docs/7.0/react/configure/typescript) but when I use `import type`, Babel doesn't seem to be able to parse it. Here is an error output example:

```
99% done plugins webpack-hot-middlewarewebpack built preview eb84d52cefbfef7fb40b in 5012ms
WARN Force closed manager build
99% end closing watch compilationWARN Force closed preview build
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/ivan/Workspace/singularity-ui/test/src/Button.stories.ts: Unexpected token, expected "from" (1:12)

> 1 | import type { Meta, StoryObj } from '@storybook/react';
    |             ^
  2 | import { Button } from './Button';
  3 | const meta = ({
  4 |   title: 'Button',
    at instantiate (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:66:32)
    at constructor (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:357:12)
    at JSXParserMixin.raise (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:3298:19)
    at JSXParserMixin.unexpected (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:3331:16)
    at JSXParserMixin.expectContextual (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:3647:18)
    at JSXParserMixin.parseImport (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:14193:12)
    at JSXParserMixin.parseStatementContent (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:12780:25)
    at JSXParserMixin.parseStatementLike (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:12669:17)
    at JSXParserMixin.parseModuleItem (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:12653:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:13254:36)
    at JSXParserMixin.parseBlockBody (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:13247:10)
    at JSXParserMixin.parseProgram (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:12567:10)
    at JSXParserMixin.parseTopLevel (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:12557:25)
    at JSXParserMixin.parse (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:14396:10)
    at parse (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/parser/lib/index.js:14440:38)
    at parser (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/core/lib/parser/index.js:42:34)
    at parser.next (<anonymous>)
    at normalizeFile (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/core/lib/transformation/normalize-file.js:65:38)
    at normalizeFile.next (<anonymous>)
    at run (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/home/ivan/Workspace/singularity-ui/test/node_modules/@babel/core/lib/transform.js:23:41)
    at transform.next (<anonymous>)
    at step (/home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:221:32)
    at /home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:229:13
    at async.call.result.err.err (/home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:190:11)
    at /home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:159:13
    at /home/ivan/Workspace/singularity-ui/test/node_modules/@babel/core/lib/gensync-utils/async.js:96:7
    at /home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:97:35
    at step (/home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:238:14)
    at /home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:229:13
    at async.call.result.err.err (/home/ivan/Workspace/singularity-ui/test/node_modules/gensync/index.js:190:11)
    at processResult (/home/ivan/Workspace/singularity-ui/test/node_modules/webpack/lib/NormalModule.js:489:23)
    at /home/ivan/Workspace/singularity-ui/test/node_modules/webpack/lib/NormalModule.js:567:9
    at /home/ivan/Workspace/singularity-ui/test/node_modules/loader-runner/lib/LoaderRunner.js:361:14
    at /home/ivan/Workspace/singularity-ui/test/node_modules/loader-runner/lib/LoaderRunner.js:227:14
    at context.callback (/home/ivan/Workspace/singularity-ui/test/node_modules/loader-runner/lib/LoaderRunner.js:116:16)
    at /home/ivan/Workspace/singularity-ui/test/node_modules/babel-loader/lib/index.js:67:108
```

### To Reproduce

1. Create a Typescript (v4.9.4) + React (v18) project
2. Add a TSX file with an `import type { MyType } from 'my/path'`
3. Run `npx storybook@next init`
4. Run `npm run storybook`

In order to ease the reproduction I [created a repo](https://github.com/ivangabriele/issue__storybookjs__storybookjs__01).

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (48) x64 AMD Ryzen Threadripper 2970WX 24-Core Processor
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.3.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/addon-interactions: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/addon-links: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/blocks: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/react: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/react-webpack5: ^7.0.0-beta.15 => 7.0.0-beta.15 
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

**Comment by fmal** [comment]
@ivangabriele i guess you need to provide babel config with `@babel/preset-typescript` to make it work, see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#babel-mode-v7-exclusively

**Comment by ivangabriele** [comment]
Oh so that's rather v7 documentation that's incorrect? Specifically:

> Storybook has built-in TypeScript support, so your TypeScript project should work with zero configuration needed.

Should I make a PR to update that statement?

**Comment by pixeliner** [comment]
Had the same issue. 
As @ivangabriele suggested, shouldn't the docs be corrected?

So the steps that worked for me are:
- `npx sb@next babelrc` This will add a .babelrc.json config (I added the Typescript and React presets.
- add `babelModeV7: true` to the main.js **features** options

**Comment by IanVS** [comment]
@yannbf is working on a PR that will run the `sb babelrc` step as an automigration: https://github.com/storybookjs/storybook/pull/20341

**Comment by soulsam480** [comment]
> Had the same issue. As @ivangabriele suggested, shouldn't the docs be corrected?
> 
> So the steps that worked for me are:
> 
> * `npx sb@next babelrc` This will add a .babelrc.json config (I added the Typescript and React presets.
> * add `babelModeV7: true` to the main.js **features** options

Hey @pixeliner , I'm also having the same issue. I added one `babel.config.js` file, but storybook isn't even reading the file Same with all kinds of babel config files (.babelrc, .babelrc.json stc.). debugging the webpack config shows, the presets and plugins from the babel config are not there. @IanVS can you help ? thx 🙏🏽

**Comment by ivangabriele** [comment]
Just FYI I suggested to update the doc in #20341.

**Comment by shilman** [comment]
Crikey!! I just released [v7.0.0-beta.27 (release)](https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.27) containing PR https://github.com/storybookjs/storybook/pull/20341 that references this issue. Upgrade today to the @next NPM tag to try it out!

npx sb@next upgrade --prerelease
Closing this issue. Please re-open if you think there's still more to do.

**Comment by shaohaolin** [comment]
I'm using v7.00-beta.30, and the monorepo setup still has the problem.
For people that have storybooks for each package and have a monorepo setup, like Turborepo. You would need to rename the automatically generated ".babelrc.json" file to "babel.config.json" or add a "babel.config.json" file to the root directory.

Should we add a step to the auto-migration step to detect monorepo and add `babel.config.json`?

**Comment by ndelangen** [comment]
Even if we defer the "is this a monorepo?" problem to be solved by some other package, even if we defer "where's the right place to write the babelrc?" to another package, and the question of "what's the right filename for babel to be configured in at this location?"... even if we're not having to maintain this code ourselves...

...Then we'll still be on the hook for supporting all of that.

I fear we'll get questions why this isn't working for some unknown environment.

I fear that if we're going to be adding stuff/config to the root of a project we know nothing about we might break other parts of that monorepo. Which -again- we'll be on the hook for, supporting that.

**Comment by adamdiestelkamp** [comment]
Thanks @shaohaolin very much for that tidbit. Helped us get unstuck in our monorepo.

**Comment by dalafik** [comment]
I faced this issue with Storybook 7.0.4 for react-webpack5.
The solution was not to only add `babel.config.json`, but also tweak some of its settings (as described [here](https://babeljs.io/docs/babel-preset-typescript#options)):
```json
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-typescript",
      {
        "onlyRemoveTypeImports": true,
        "allExtensions": true,
        "isTSX": true
      }
    ]
  ]
}
```
To check if the correct config file is loaded, [this method](https://storybook.js.org/docs/vue/configure/babel#troubleshooting) can help.

**Comment by isimmons** [comment]
I ran into this issue using test-runner on a vite project with storybook 7.0.20 and react 18. Everything else worked without a babel config up to this point.

The demo code from [Here](https://storybook.js.org/docs/react/writing-tests/accessibility-testing#setup) throws syntax errors when the tests run.

Before adding the babel.config.json shown above by @dalafik , I changed the code to
```javascript
const { injectAxe, checkA11y } = require( 'axe-playwright');

const a11yConfig = {
  async preRender(page) {
    await injectAxe(page);
  },
  async postRender(page) {
    await checkA11y(page, '#storybook-root', {
      detailedReport: true,
      detailedReportOptions: {
        html: true,
      },
    });
  },
};

module.exports = a11yConfig;
```
and it works but with no autocomplete because of the missing type import

After adding the babel config this works great

```javascript
import { injectAxe, checkA11y } from 'axe-playwright';
import { TestRunnerConfig } from '@storybook/test-runner';

const a11yConfig: TestRunnerConfig = {
  async preRender(page) {
    await injectAxe(page);
  },
  async postRender(page) {
    await checkA11y(page, '#storybook-root', {
      detailedReport: true,
      detailedReportOptions: {
        html: true,
      },
    });
  },
};

export default a11yConfig;
```

**Comment by hugoschellinger** [comment]
Even after test all issue, this problem persist for me. Any other solutions for v7.2.1 ?

**Comment by arudenkoofficial** [comment]
Thanks @shaohaolin for recipe! 
It works for me now with `storybok@7.6.10` within lerna monorepo. The only difference is that I've renamed `babel.config.json` in the package root, not the monorepo root
