### ISSUE TITLE
[Bug]: Module build error when migrating from SB version 6.1.5 to 6.5.15

### ISSUE THREAD

**Issue by marjon4** [storybookjs/storybook#20437]
### Describe the bug

So I want to migrate my project to the latest Storybook version but there seems to be a problem with prettier inside @zeplin package if I'm understanding the console log error message right.. Saw a similar issue with an earlier Storybook version that was fixed by locking the prettier version to. 2.3.0 which I've tried but with no luck. Any ideas??

Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/bvx959/Azure/ica-elements/node_modules/@zeplin/storybook-inspector/node_modules/prettier/standalone.js: Expected atom at position 0
    {{(.+?)}}
    ^
    at bail (:1337/Users/bvx959/Azure/ica-elements/node_modules/regjsparser/parser.js:1135:13)
    at parseTerm (:1337/Users/bvx959/Azure/ica-elements/node_modules/regjsparser/parser.js:486:9)
    at parseAlternative (:1337/Users/bvx959/Azure/ica-elements/node_modules/regjsparser/parser.js:457:21)
    at parseDisjunction (:1337/Users/bvx959/Azure/ica-elements/node_modules/regjsparser/parser.js:437:16)
    at parse (:1337/Users/bvx959/Azure/ica-elements/node_modules/regjsparser/parser.js:1150:18)
    at rewritePattern (:1337/Users/bvx959/Azure/ica-elements/node_modules/regexpu-core/rewrite-pattern.js:339:15)
    at PluginPass.RegExpLiteral (:1337/Users/bvx959/Azure/ica-elements/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js:92:49)
    at newFn (:1337/Users/bvx959/Azure/ica-elements/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (:1337/Users/bvx959/Azure/ica-elements/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (:1337/Users/bvx959/Azure/ica-elements/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at ./node_modules/@zeplin/storybook-inspector/node_modules/prettier/standalone.js (vendors~main.manager.bundle.js:214078:7)
    at __webpack_require__ (runtime~main.manager.bundle.js:85:30)
    at 413 (vendors~main.manager.bundle.js:205305:20262)
    at n (vendors~main.manager.bundle.js:205305:20953)
    at 538 (vendors~main.manager.bundle.js:205305:8029)
    at n (vendors~main.manager.bundle.js:205305:20953)
    at 25 (vendors~main.manager.bundle.js:205305:4352)
    at n (vendors~main.manager.bundle.js:205305:20953)
    at 236 (vendors~main.manager.bundle.js:205305:12419)
    at n (vendors~main.manager.bundle.js:205305:20953)

**Comment by valentinpalkovic** [comment]
This report is against Storybook 6.5.15 with `@storybook/addon-storyshots`, `@storybook/source-loader`, and `@storybook/theming` as standalone packages  -  all removed or restructured in 7.0-9.0  -  combined with a third-party addon (`@zeplin/storybook-inspector`) bundling an ancient Prettier version. That entire toolchain no longer exists in any supported Storybook setup. Closing as obsolete.
