### ISSUE TITLE
[Bug]: [7.0.0-beta.19]: using pnpm with nextjs, module not found: Error: Can't resolve 'style-loader'

### ISSUE THREAD

**Issue by ArianHamdi** [storybookjs/storybook#20468]
### Describe the bug

Running storybook by pnpm in a nextjs app throws the error "can't resolve 'style-loader'".

### To Reproduce

```shell
1. pnpm create next-app storybook.
2. cd ./storybook.
3. pnpm dlx storybook@next init --package-manager=pnpm.
4. pnpm run storybook.

The following error is thrown :
Module not found: Error: Can't resolve 'style-loader.

P.S : Works fine by yarn & npm.
```

### System

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.21.0
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
  npmPackages:
    @storybook/addon-essentials: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/addon-interactions: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/addon-links: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/blocks: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/nextjs: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/react: 7.0.0-beta.19 => 7.0.0-beta.19
    @storybook/testing-library: 0.0.13 => 0.0.13
```

**Comment by binaryartifex** [comment]
can confirm. similar setup (windows 11, using pnpm, same dependencies....). i have to install css-loader and style-loader manually otherwise either the .css file imported into preview.ts errors or I get the "can't find x-loader" errors as above

**Comment by amery** [comment]
could --shamefully-hoist solve this?

**Comment by IanVS** [comment]
>could --shamefully-hoist solve this?

It's possible, but our goal is to avoid requiring that.  We've done a lot of work already to clean things up so that we don't rely on hoisting, looks like we just have a bit more to do here for next.js.

**Comment by ndelangen** [comment]
@valentinpalkovic I see you're requested to work on this..

I just skimmed this after a week of vacation, so take my take on this with a gram of salt, but we should likely add a regular dependency on the style-loader somewhere, and possibly, wrap the reference to it with `require.resolve`. I'm not sure that second part is truly necessary.

**Comment by rhuanbello** [comment]
Fixed by running `pnpm -D css-loader style-loader postcss-loader`

**Comment by yannbf** [comment]
FYI this is a current limitation that is documented in the README of the `@storybook/nextjs` package:
https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/README.md#notes-for-yarn-v2-and-v3-users

Just seems to not be related only to yarn2+

**Comment by Seefer** [comment]
I was running into that issue but since upgrading `pnpm` to version `8.1.1` and running `pnpm dlx sb@next init` that installs Storybook version `7.1.0-alpha.0`, it seems to install and work fine on my Windows 11 system with node version `18.15.0`.

**Comment by valentinpalkovic** [comment]
The issue was resolved with https://github.com/storybookjs/storybook/issues/21605

**Comment by dep** [comment]
I'm having the same problem in my repo:

```
"@storybook/addon-actions": "7.0.7",
"@storybook/addon-docs": "7.0.7",
"@storybook/addon-knobs": "7.0.0",
"@storybook/addon-links": "7.0.7",
"@storybook/addons": "7.0.6",
"@storybook/preset-scss": "1.0.3",
"@storybook/react": "7.0.7",
"@storybook/theming": "7.0.7",
```

Error:

```
@foo/box-signals: Module not found: Error: Can't resolve 'style-loader' in '/Users/baz/foo/box/applications/react/modern/signals'
@foo/box-signals:  @ ./src/components/BulkActionsSelect.jsx 4:0-48 53:88-103
@foo/box-signals:  @ ./src/components/FilterSignalsPanel.jsx 7:0-52 57:53-70
@foo/box-signals:  @ ./src/components/Signals.jsx 6:0-54 122:39-57
@foo/box-signals:  @ ./src/components/App.jsx 6:0-32 35:38-45
@foo/box-signals:  @ ./src/index.jsx 8:0-35 48:36-39
@foo/box-signals: ERROR in ./src/components/SplashSelector.jsx 5:0-39
```

Any help is appreciated!

**Comment by dep** [comment]
Adding a framework got me past the error, thanks @IanVS !

**Comment by dep** [comment]
I was able to bypass that error by removing this addon

```
require("@foo/webpack-config-titan/src/webpack.sass.storybook.main"),
```

But I have one more:

```
R! /home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13
ERR! class IssueWebpackError extends webpack_1.default.WebpackError {
ERR!                                                   ^
ERR! 
ERR! TypeError: Class extends value undefined is not a constructor or null
ERR!     at Object.<anonymous> (/home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13:51)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ERR!     at Module._compile (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ERR!     at Object.newLoader (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!  /home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13
ERR! class IssueWebpackError extends webpack_1.default.WebpackError {
ERR!                                                   ^
ERR! 
ERR! TypeError: Class extends value undefined is not a constructor or null
ERR!     at Object.<anonymous> (/home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13:51)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ERR!     at Module._compile (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ERR!     at Object.newLoader (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by dep** [comment]
Resolved that error, now have this one:

```
@foo/box-legacy-web: /Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:761
@foo/box-legacy-web: 				const error = new ModuleBuildError(err, {
@foo/box-legacy-web: 				              ^
@foo/box-legacy-web: ModuleBuildError: Module build failed (from ../../node_modules/@storybook/mdx2-csf/loader.js):
@foo/box-legacy-web: Unexpected `VariableDeclaration` in code: only import/exports are supported
@foo/box-legacy-web:     at null.processResult (/Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:761:19)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:863:5)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:400:11)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:252:18)
@foo/box-legacy-web:     at null.context.callback (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
@foo/box-legacy-web:     at Object.loader (/Users/bar/foo/box/node_modules/@storybook/mdx2-csf/loader.js:32:12)
@foo/box-legacy-web: /Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:761
@foo/box-legacy-web: 				const error = new ModuleBuildError(err, {
@foo/box-legacy-web: 				              ^
@foo/box-legacy-web: ModuleBuildError: Module build failed (from ../../node_modules/@storybook/mdx2-csf/loader.js):
@foo/box-legacy-web: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
@foo/box-legacy-web:     at null.processResult (/Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:761:19)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/webpack/lib/NormalModule.js:863:5)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:400:11)
@foo/box-legacy-web:     at null.<anonymous> (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:252:18)
@foo/box-legacy-web:     at null.context.callback (/Users/bar/foo/box/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
@foo/box-legacy-web:     at Object.loader (/Users/bar/foo/box/node_modules/@storybook/mdx2-csf/loader.js:32:12)
@foo/box-legacy-web: WARN Broken build, fix the error above.
@foo/box-legacy-web: WARN You may need to refresh the browser.
```

**Comment by IanVS** [comment]
@dep I'd suggest opening a new issue, or hopping into the discord (discord.gg/storybook) to get help with this further, since it's no longer related to this issue.

**Comment by Demi1024** [comment]
> I'm having the same problem in my repo:
> 
> ```
> "@storybook/addon-actions": "7.0.7",
> "@storybook/addon-docs": "7.0.7",
> "@storybook/addon-knobs": "7.0.0",
> "@storybook/addon-links": "7.0.7",
> "@storybook/addons": "7.0.6",
> "@storybook/preset-scss": "1.0.3",
> "@storybook/react": "7.0.7",
> "@storybook/theming": "7.0.7",
> ```
> 
> Error:
> 
> ```
> @foo/box-signals: Module not found: Error: Can't resolve 'style-loader' in '/Users/baz/foo/box/applications/react/modern/signals'
> @foo/box-signals:  @ ./src/components/BulkActionsSelect.jsx 4:0-48 53:88-103
> @foo/box-signals:  @ ./src/components/FilterSignalsPanel.jsx 7:0-52 57:53-70
> @foo/box-signals:  @ ./src/components/Signals.jsx 6:0-54 122:39-57
> @foo/box-signals:  @ ./src/components/App.jsx 6:0-32 35:38-45
> @foo/box-signals:  @ ./src/index.jsx 8:0-35 48:36-39
> @foo/box-signals: ERROR in ./src/components/SplashSelector.jsx 5:0-39
> ```
> 
> Any help is appreciated!

same problem, can anyone help?
