### ISSUE TITLE
[Bug]: Unexpected closing tag t may happen when the tag has already been closed by another

### ISSUE THREAD

**Issue by RAJEEV2510** [storybookjs/storybook#20480]
### Describe the bug

When we use multiple params show error.
Unexpected closing tag "lib-tree-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:507) (at formatter-0d5cb0eb.js:31:1)
> 1 | <lib-tree-view theme=""dark"" treeID="123" toolbarButtons="{}" availableGroups="{}" (onNodeSelected)="onNodeSelected($event)" (onNodeUnSelected)="onNodeUnSelected($event)" (onNodeChecked)="onNodeChecked($event)" (onNodeUnChecked)="onNodeUnChecked($event)" (onNodeSingleClick)="onNodeSingleClick($event)" (onNodedoubleClick)="onNodedoubleClick($event)" (onNodeContextmenuClicked)="onNodeContextmenuClicked($event)" (toolbarButtonClicked)="toolbarButtonClicked($event)" (onNodeExpand)="onNodeExpand($event)"></lib-tree-view>

### To Reproduce

```shell
For Reproduce input multiple parameters
```

### System

```shell
Unexpected closing tag "lib-tree-view". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:507) (at formatter-0d5cb0eb.js:31:1)
> 1 | <lib-tree-view theme=""dark"" treeID="123" toolbarButtons="{}" availableGroups="{}" (onNodeSelected)="onNodeSelected($event)" (onNodeUnSelected)="onNodeUnSelected($event)" (onNodeChecked)="onNodeChecked($event)" (onNodeUnChecked)="onNodeUnChecked($event)" (onNodeSingleClick)="onNodeSingleClick($event)" (onNodedoubleClick)="onNodedoubleClick($event)" (onNodeContextmenuClicked)="onNodeContextmenuClicked($event)" (toolbarButtonClicked)="toolbarButtonClicked($event)" (onNodeExpand)="onNodeExpand($event)"></lib-tree-view>
```

**Comment by RAJEEV2510** [comment]
use in this way theme="'dark'"

 <lib-tree-view theme="dark" treeID="123" toolbarButtons="{}" availableGroups="{}" (onNodeSelected)="onNodeSelected($event)" (onNodeUnSelected)="onNodeUnSelected($event)" (onNodeChecked)="onNodeChecked($event)" (onNodeUnChecked)="onNodeUnChecked($event)" (onNodeSingleClick)="onNodeSingleClick($event)" (onNodedoubleClick)="onNodedoubleClick($event)" (onNodeContextmenuClicked)="onNodeContextmenuClicked($event)" (toolbarButtonClicked)="toolbarButtonClicked($event)" (onNodeExpand)="onNodeExpand($event)"></lib-tree-view>
