### ISSUE TITLE
[Bug]: npm run storybook return FileNotFound error in some special case

### ISSUE THREAD

**Issue by danny-huang-openfind** [storybookjs/storybook#20629]
### Describe the bug

When I call `npm run storybook`, it then return me an FileNotFound error. I tried to dived into the library and I found that this may caused by the function called `routePathIsBad` which can be found in compodoc and used at line 6550. The path it received is actually no problem before that if statement, but then after executing this block, the path will fix into a strange format and cause the error.

### To Reproduce

```shell
Since this error looks like it only can reproduce in a very specific situation, here is a repo I have already reproduce it, please clone it and try to run storybook on it.

https://github.com/danny-huang-openfind/storybook-error-test
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.28 => 7.0.0-beta.28
    @storybook/addon-interactions: ^7.0.0-beta.28 => 7.0.0-beta.28
    @storybook/addon-links: ^7.0.0-beta.28 => 7.0.0-beta.28
    @storybook/angular: ^7.0.0-beta.28 => 7.0.0-beta.28
    @storybook/blocks: ^7.0.0-beta.28 => 7.0.0-beta.28
    @storybook/testing-library: ^0.0.13 => 0.0.13
```

### Additional context

This is the error message when it happened:

Unhandled Rejection at: Promise {
  <rejected> FileNotFoundError: File not found: E:/Programming/Web/storybookErrorTest/src/test/test-routing.ts
      at DirectoryCoordinator.addSourceFileAtPath (E:\Programming\Web\storybookErrorTest\node_modules\ts-morph\dist\ts-morph.js:18643:19)
      at Project.addSourceFileAtPath (E:\Programming\Web\storybookErrorTest\node_modules\ts-morph\dist\ts-morph.js:20088:51)
      at _loop_3 (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6567:33)
      at RouterParserUtil.cleanFileSpreads (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6597:17)
      at AngularDependencies.getSourceFileDecorators (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9605:32)
      at E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9397:31
      at Array.map (<anonymous>)
      at AngularDependencies.getDependencies (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9386:21)
      at CliApplication.Application.getDependenciesData (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:11176:40)
      at E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:10985:23 {
    path: 'E:/Programming/Web/storybookErrorTest/src/test/test-routing.ts',
    code: 'ENOENT'
  }
} reason: FileNotFoundError: File not found: E:/Programming/Web/storybookErrorTest/src/test/test-routing.ts
    at DirectoryCoordinator.addSourceFileAtPath (E:\Programming\Web\storybookErrorTest\node_modules\ts-morph\dist\ts-morph.js:18643:19)
    at Project.addSourceFileAtPath (E:\Programming\Web\storybookErrorTest\node_modules\ts-morph\dist\ts-morph.js:20088:51)
    at _loop_3 (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6567:33)
    at RouterParserUtil.cleanFileSpreads (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:6597:17)
    at AngularDependencies.getSourceFileDecorators (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9605:32)
    at E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9397:31
    at Array.map (<anonymous>)
    at AngularDependencies.getDependencies (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:9386:21)
    at CliApplication.Application.getDependenciesData (E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:11176:40)
    at E:\Programming\Web\storybookErrorTest\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:10985:23 {
  path: 'E:/Programming/Web/storybookErrorTest/src/test/test-routing.ts',
  code: 'ENOENT'
}

**Comment by kingdom84521** [comment]
Anything new on this issue? still need help here.
