### ISSUE TITLE
[Bug]: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by KevinMind** [storybookjs/storybook#20644]
### Describe the bug

When migrating to storybook v7 public beta (v25) storybook addon action throws an error

```js
module is not defined
ReferenceError: module is not defined
    at ./node_modules/@storybook/addon-actions/dist/chunk-3CDXZIO2.mjs (http://localhost:55292/vendors-node_modules_shopify_channels-ui_build_esm_components_EmbeddedModal_EmbeddedModal_js--02727c.iframe.bundle.js:2563:1)
    at __webpack_require__ (http://localhost:55292/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:55292/runtime~main.iframe.bundle.js:323:25)
    at ./node_modules/@storybook/addon-actions/dist/index.mjs (http://localhost:55292/vendors-node_modules_shopify_channels-ui_build_esm_components_EmbeddedModal_EmbeddedModal_js--02727c.iframe.bundle.js:2629:77)
    at __webpack_require__ (http://localhost:55292/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:55292/runtime~main.iframe.bundle.js:323:25)
    at ./frontend/web/brand-app/features/Catalogs/components/CatalogConnectionsCard/CatalogConnectionsCard.stories.tsx (http://localhost:55292/brand-app-features-Catalogs-components-CatalogConnectionsCard-CatalogConnectionsCard-stories.iframe.bundle.js:1352:82)
    at __webpack_require__ (http://localhost:55292/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:55292/runtime~main.iframe.bundle.js:323:25)
    at http://localhost:55292/main.iframe.bundle.js:424:10
```

After digging into the vendor chunks, it looks like this HMR snippet is ultimately causing the problem.

https://github.com/storybookjs/storybook/blob/main/addons/actions/src/index.ts#L5-L7

I'm trying to determine if this is an issue with my storybook webpack/babel setup or if there is a bug in the beta.

### To Reproduce

```shell
This is an internal company repo, so I cannot share the code but you would need to setup a react repo with ^7.0.0-beta.25 using actions.
```

### System

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.dev/yarn/1.22.17/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.1
  npmPackages:
    @storybook/addon-actions: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/addon-essentials: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/addon-interactions: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/addon-links: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/react: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/react-webpack5: ^7.0.0-beta.28 => 7.0.0-beta.28 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

Potentially this is a webpack5 issue? https://stackoverflow.com/questions/66085425/webpack-5-module-hot-is-undefined

**Comment by KevinMind** [comment]
FWIW, when I replace the code in the referenced actions file with import.meta.webpackHot then the issue goes away.

```js
import.meta&&import.meta.webpackHot&&import.meta.webpackHot.decline&&import.meta.webpackHot.decline();
```

**Comment by shilman** [comment]
This is not a widespread error. But it's an easy fix -- we should remove the code entirely because we're no longer building the manager using Webpack in 7.0. We should do this in any core addon with a `manager.js` entry point @ndelangen

**Comment by ndelangen** [comment]
I found an problem specific in addon-action that was causing this, fixing..

**Comment by shilman** [comment]
Whoopee!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20649 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
