### ISSUE TITLE
Ensure users have a main.js framework field as part of the boot-up experience

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20651]
### Describe the bug

SB7 requires that the user have a valid framework defined in their `.storybook/main.js` config. We have automigrations to address this, but apparently users are still getting caught without it, either due to problems with the automigration or users skipping the automigrations entirely.

When you have an invalid string as your `framework`, e.g. `foo`, it will throw the following error:

```
TypeError: Cannot destructure property 'renderer' of '(intermediate value)' as it is undefined.
    at buildDevStandalone ($SNIP/node_modules/@storybook/core-server/dist/index.js:33:1795)
    at async withTelemetry ($SNIP/node_modules/@storybook/core-server/dist/index.js:33:5533)
    at async dev ($SNIP/node_modules/@storybook/cli/dist/generate.js:441:440)
```

For reference, when you start Storybook with NO framework it reports the following: 

```
shilman@MBP14 react-vite-default-ts % yst
@storybook/cli v7.0.0-beta.29

WARN you have not specified a framework in your /Users/shilman/projects/storybookjs/storybook/sandbox/react-vite-default-ts/.storybook/main.js
✖ Would you like to send crash reports to Storybook? … yes
```

And when you have a renderer set as your framework `@storybook/react` it throws the following error:

```
ERR! Error: Invalid value of @storybook/react in the 'framework' field of Storybook config.
ERR! 
ERR! Please run 'npx sb@next automigrate'
...
```

### To Reproduce

```shell
Edit your `main.js` to set `framework` to `foo` and run `yarn storybook`
```

### Additional context

Suggested fixes:
- [x] Add old-style frameworks (`react`/`vue`/`vue3`/etc. to the list of known renderers)
- [x] Add check for invalid frameworks like "foo" and report the same error message as known renderers
- [x] Add the check for no framework & report the same error message as known renderers

**Comment by shilman** [comment]
Hurrah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.56 containing PR #21299 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
