### ISSUE TITLE
[Bug]: Cannot find @storybook/html/package.json

### ISSUE THREAD

**Issue by mohyddintash** [storybookjs/storybook#20900]
### Describe the bug

Hey there,
This is my first attempt to use storybook and I ran into this error when starting from an empty project.
reproduce:

yarn init -2
npx sb@next init --type html

I tried without -2 flag and got the same outcome.

Stacktrace:

Error: Cannot find module '@storybook/html/package.json'

Require stack:

- [/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js)

- [/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/bin/index.js](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/bin/index.js)

    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)

    at Function.resolve (node:internal/modules/cjs/helpers:109:19)

    at getRendererDir ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:1:6836](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:1:6836))

    at componentsPath ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:11:1474](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:11:1474))

    at copyComponents ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:11:2661](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:11:2661))

    at async baseGenerator ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:36:738](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:36:738))

    at async generator15 ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:57:2253](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:57:2253))

    at async doInitiate ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:374:78](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:374:78))

    at async withTelemetry ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/core-server/dist/index.js:33:5568](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/core-server/dist/index.js:33:5568))

    at async initiate ([/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:380:133](mailto:/home/mo/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:380:133))

### System

```shell
Environment Info:

 

  System:

    OS: Linux 5.15 elementary OS 6.1 Jólnir

    CPU: (4) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

  Binaries:

    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node

    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm

  Browsers:

    Chrome: 109.0.5414.74

    Firefox: 108.0.2
```

**Comment by ndelangen** [comment]
This is likely a connection issue or some npm registry outage / configuration problem.

Without a reproduction there's nothing we can do..
We have CI running these commands many times a day.
