### ISSUE TITLE
[Bug]: No configuration files have been found in your configDir after updating to 7.0.0-beta.42

### ISSUE THREAD

**Issue by nzacca** [storybookjs/storybook#20928]
### Describe the bug

After updating to `7.0.0-beta.42`, we're receiving the following error after starting storybook:

```bash
ERR! Error: No configuration files have been found in your configDir (C:\dev\.storybook).
ERR! Storybook needs "main.js" file, please add it.
ERR!     at validateConfigurationFiles (C:\dev\node_modules\@storybook\core-common\dist\index.js:12:21)
ERR!     at async loadMainConfig (C:\dev\node_modules\@storybook\core-common\dist\index.js:22:5699)
ERR!     at async buildDevStandalone (C:\dev\node_modules\@storybook\core-server\dist\index.js:33:1294)
ERR!     at async withTelemetry (C:\dev\node_modules\@storybook\core-server\dist\index.js:33:5568)
```

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Binaries:
    Node: 16.16.0 - C:\dev\nodejs\node.EXE
    npm: 8.13.2 - C:\dev\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.120
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
  npmPackages:
    @storybook/addon-actions: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/addon-essentials: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/addon-links: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/addon-postcss: 2.0.0 => 2.0.0
    @storybook/addons: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/angular: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/builder-webpack5: 7.0.0-beta.42 => 7.0.0-beta.42
    @storybook/core-server: 7.0.0-beta.42 => 7.0.0-beta.42
```
```


### Additional context

Additional Notes:

- This works fine with `7.0.0-beta.41`
- We are using a main.ts in our config folder.
- We have tried a clean install (remove node_modules, lock file then reinstall)

Contents of `main.ts`:

```ts
export default {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: '@storybook/angular',
  core: {
    builder: '@storybook/builder-webpack5',
    disableTelemetry: true,
  },
};

```

**Comment by shilman** [comment]
This looks like a regression caused by #20927. I'm guessing it's a windows bug.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.43 containing PR #20929 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by nzacca** [comment]
I can confirm `7.0.0-beta-43` has fixed the issue. Thank you very much @shilman ! I noticed we're getting a peer dependency issue for glob now. I'll file a separate ticket for that.
