### ISSUE TITLE
[Bug]: Angular - StorybookWrapperComponent - ChangeDetectorRef injection undefined (7.0 beta)

### ISSUE THREAD

**Issue by ak99372** [storybookjs/storybook#21006]
### Describe the bug

ChangeDetectorRef constructor injection to StorybookWrapperComponent is undefined 
```
@Inject(ChangeDetectorRef) private changeDetectorRef: ChangeDetectorRef
```
resulting in error during ngAfterViewInit 
```
core.mjs:9171 ERROR TypeError: Cannot read properties of undefined (reading 'detectChanges')
    at StorybookWrapperComponent.ngAfterViewInit (StorybookWrapperComponent.js:93:1)
    at callHook (core.mjs:2498:1)
    at callHooks (core.mjs:2467:1)
    at executeInitAndCheckHooks (core.mjs:2418:1)
    at refreshView (core.mjs:12082:1)
    at detectChangesInternal (core.mjs:13229:1)
    at RootViewRef.detectChanges (core.mjs:13741:1)
    at ApplicationRef.tick (core.mjs:27377:1)
    at ApplicationRef._loadComponent (core.mjs:27415:1)
    at ApplicationRef.bootstrap (core.mjs:27352:1)
```

### To Reproduce

(angular-cli v14)
```shell
ng new angular-book
npx storybook@7.0.0-beta.43 init
npm run storybook
```
```


### System

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/addon-interactions: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/addon-links: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/angular: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/blocks: ^7.0.0-beta.43 => 7.0.0-beta.43
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by ak99372** [comment]
Closing this seems to be fixed in [7.0.0-beta.44]
