### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by peterbenoit** [storybookjs/storybook#21033]
### Describe the bug

`npm install @storybook/addon-a11y`

**In main.js added**
`module.exports = {
  addons: ['@storybook/addon-a11y'],
};
`

`npm run storybook` 

**This message appears on every screen**
`TypeError: Cannot read properties of undefined (reading 'document')
    at ./node_modules/@storybook/addon-a11y/dist/esm/a11yRunner.js (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_preview_js-node_modules_storybook_addon-essentials_-c91644.iframe.bundle.js:400:63)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:328:25)
    at ./node_modules/@storybook/addon-a11y/dist/esm/preview.js (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_preview_js-node_modules_storybook_addon-essentials_-c91644.iframe.bundle.js:655:69)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:328:25)
    at ./node_modules/@storybook/addon-a11y/preview.js (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_preview_js-node_modules_storybook_addon-essentials_-c91644.iframe.bundle.js:670:75)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:328:25)
    at Object.getProjectAnnotations [as nextFn] (http://localhost:6006/main.iframe.bundle.js:370:1512)`

### To Reproduce

```shell
https://github.com/peterbenoit/DFE-storybook-public

https://peterbenoit-curly-dollop-6pqj9r6r7f477j-6006.preview.app.github.dev/
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 19.0.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Safari: 15.5
  npmPackages:
    @storybook/addon-a11y: ^6.5.16 => 6.5.16 
    @storybook/addon-actions: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-essentials: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-interactions: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-links: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/blocks: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/html: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/html-webpack5: ^7.0.0-beta.43 => 7.0.0-beta.43 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by zhyd1997** [comment]
Hi @peterbenoit 

try to upgrade your `@storybook/addon-a11y` version:

```shell
npm i @storybook/addon-a11y@7.0.0-beta.43
```

**Comment by peterbenoit** [comment]
@zhyd1997 That worked, thank you so much!
