### ISSUE TITLE
[Bug]: Storybook shows error 'The glob specified in main.js isn't correct' on first page load

### ISSUE THREAD

**Issue by pimventureiq** [storybookjs/storybook#21153]
### Describe the bug

Storybook shows this error when app first loads (console). But after I add a space in 'ActionbarButon.styles.js' and save it recovers. Seems to me that there is a problem with the instantiation order of components,
   
`index.js:56 Unexpected error while loading ./components/atoms/Buttons/Button/Button.stories.jsx: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
 ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (http://localhost:6006/main.iframe.bundle.js:1163:42)
    at ./src/components/molecules/Buttons/ActionbarButton/ActionbarButon.styles.js (http://localhost:6006/main.iframe.bundle.js:7102:186)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:681:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:338:21)
    at ./src/components/molecules/Buttons/ActionbarButton/ActionbarButton.jsx (http://localhost:6006/main.iframe.bundle.js:7166:124)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:681:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:338:21)
    at ./src/components/organisms/Snackbars/Actionbar/Actionbar.jsx (http://localhost:6006/main.iframe.bundle.js:19158:118)`

### To Reproduce

Couldn't reproduce, seems random

### System

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 16.15.0 - /usr/local/opt/node@16/bin/node
    npm: 8.5.5 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 15.5
  npmPackages:
    @storybook/addon-a11y: ^6.5.16 => 6.5.16 
    @storybook/addon-actions: ^6.5.16 => 6.5.16 
    @storybook/addon-coverage: ^0.0.8 => 0.0.8 
    @storybook/addon-docs: ^6.5.16 => 6.5.16 
    @storybook/addon-essentials: ^6.5.16 => 6.5.16 
    @storybook/addon-interactions: ^6.5.16 => 6.5.16 
    @storybook/addon-links: ^6.5.16 => 6.5.16 
    @storybook/builder-webpack5: ^6.5.16 => 6.5.16 
    @storybook/jest: ^0.0.10 => 0.0.10 
    @storybook/manager-webpack5: ^6.5.16 => 6.5.16 
    @storybook/node-logger: ^6.5.16 => 6.5.16 
    @storybook/preset-create-react-app: ^4.1.2 => 4.1.2 
    @storybook/react: ^6.5.16 => 6.5.16 
    @storybook/test-runner: ^0.9.4 => 0.9.4 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
    @storybook/testing-react: ^1.3.0 => 1.3.0
```

### Additional context

I am using absolute paths to resolve the modules. Maybe it is related
```
jsconfig.json 

{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

**Comment by shilman** [comment]
Does this problem also occur in the latest prerelease?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by kherock** [comment]
I ran into this issue when upgrading to CSF3 as part of my 7.0 upgrade - my issue is probably unrelated, but I was getting this error because my MDX document page and the stories file were circularly importing each other.
