### ISSUE TITLE
[Bug]:  <Meta> on MDX fail in first install

### ISSUE THREAD

**Issue by geongeorge** [storybookjs/storybook#21256]
### Describe the bug

On fresh next js and storybook `<Meta>` component is failing.

```
Cannot destructure property 'window' of 'global__WEBPACK_IMPORTED_MODULE_7__.default' as it is undefined.
```

```
TypeError: Cannot destructure property 'window' of 'global__WEBPACK_IMPORTED_MODULE_7__.default' as it is undefined.
    at ./node_modules/@storybook/blocks/dist/index.mjs (http://localhost:6006/vendors-node_modules_storybook_addon-docs_node_modules_mdx-js_react_lib_index_js-node_modules-8ad795.iframe.bundle.js:491:9202)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:298:25)
    at ./src/stories/Introduction.mdx (http://localhost:6006/stories-Introduction-mdx.iframe.bundle.js:18:75)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:298:25)
    at http://localhost:6006/main.iframe.bundle.js:296:10
```

### To Reproduce

1. Initialize a next js project
2. `npx storybook@next init`
3. `yarn storybook`

The introduction page will not load and will have this issue

### System

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 19.4.0 - ~/.n/bin/node
    Yarn: 1.22.19 - ~/npm/bin/yarn
    npm: 9.2.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-interactions: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/addon-links: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-alpha.8 
    @storybook/nextjs: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/react: ^7.0.0-beta.54 => 7.0.0-beta.54 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

Thank you so much for making bug reporting very easy. Other libraries make you jump through hoops

**Comment by geongeorge** [comment]
Adding screenshot for additional context.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/29296982/221340120-176041cf-b7a2-4658-999a-27d9488ac377.png">

MDX Content:

```
import { Meta } from '@storybook/blocks';

<Meta title="Hermes/Introduction" />


# Welcome to Storybook

Storybook helps you build UI components in isolation from your app's business logic, data, and context.
That makes it easy to develop hard-to-reach states. Save these UI states as **stories** to revisit during development, testing, or QA.

Browse example stories now by navigating to them in the sidebar.
View their code in the `stories` directory to learn how they work.
We recommend building UIs with a [**component-driven**](https://componentdriven.org) process starting with atomic components and ending with pages.

```

**Comment by geongeorge** [comment]
Changing from `"@storybook/blocks": "^7.0.0-alpha.8",` to `"@storybook/blocks": "^7.0.0-alpha.34",` Fixed the issue

**Comment by AleksRap** [comment]
Hello. I have the same problem. I used the comand `pnpm dlx sb@next init --builder webpack5`. Version 7.0.0-beta.59 was installed

**Comment by geongeorge** [comment]
@AleksRap Try changing the version of "@storybook/blocks" to 34
