### ISSUE TITLE
[Bug]: 7.0.0-beta.54 vite-react does not work with --config-dir

### ISSUE THREAD

**Issue by dbrelovsky** [storybookjs/storybook#21266]
### Describe the bug

When I setup storybook 7 in a vite project everything works fine. When I move the .storybook folder in a nested directory and use --config-dir option to point to that directory, the stories can no longer be loaded. This is the error:

``` cmd
TypeError: importers[path] is not a function
    at importFn (http://localhost:6006/virtual:/@storybook/builder-vite/storybook-stories.js:8:31)
    at StoryStore.loadEntry (http://localhost:6006/sb-preview/runtime.mjs:40:10586)
    at async CsfDocsRender.prepare (http://localhost:6006/sb-preview/runtime.mjs:74:4645)
    at async PreviewWeb.renderSelection (http://localhost:6006/sb-preview/runtime.mjs:83:3054)
    at async PreviewWeb.selectSpecifiedStory (http://localhost:6006/sb-preview/runtime.mjs:83:247)
```

### To Reproduce

https://github.com/dbrelovsky/storybook-config-dir-error

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/addon-interactions: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/addon-links: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/blocks: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/react: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/react-vite: ^7.0.0-beta.54 => 7.0.0-beta.54
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by yannbf** [comment]
Hey @dbrelovsky thanks for reporting! I checked your repro and I was not able to reproduce it.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1671563/222789517-e933c1f0-dc26-40a7-8f6c-175a4c70cd80.png">

**Comment by dbrelovsky** [comment]
I think the problem was solved with https://github.com/storybookjs/storybook/issues/21101
