### ISSUE TITLE
[Bug] Composition of 6.5 storybook has extra refreshes

### ISSUE THREAD

**Issue by ndelangen** [storybookjs/storybook#21352]

**Comment by ndelangen** [comment]
I added the 6.5 `Storybook design-system` as a ref to `code/ui/.storybook/main.ts`.

- I noticed that everytime when switching between stories inside the ref, the iframe refreshes.
- It failed with "cannot read properties of undefined" "reading trim" (as reported by @tmeasday here: https://www.notion.so/Storybook-composition-407aded137424209953308c36083ca3b?d=b7e53002bee145769011a5c8f2da36b3) I changed a little bit of code here, to make it work:
  ![Image](https://user-images.githubusercontent.com/3070389/222402959-156978c0-94c2-4135-a60e-3f96698d0ac7.png)
- The tree-structure looks incorrect: ![Image](https://user-images.githubusercontent.com/3070389/222403156-37ecc040-cbcc-4c20-97b4-88ac1694da20.png)
- There are some items seemingly duplicated, but they are in fact represented by the wrong name (they are unique stories)
- MDX pages seems completely broken with an error:
  ```
  vendors~main.f9f8c42f829f600491af.bundle.js:2 Uncaught (in promise) DOMException: Blocked a frame with origin "https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com" from accessing a cross-origin frame.
    at Link (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:287598)
    at oh (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1512414)
    at Rj (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1558359)
    at Qj (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1551004)
    at Kj (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1550933)
    at yj (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1547997)
    at Ig (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1544789)
    at bk (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1566066)
    at https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1567315
    at Nj (https://5ccbc373887ca40020446347-ojlvawpnsi.chromatic.com/vendors~main.f9f8c42f829f600491af.bundle.js:2:1548332)
  ``` 
- The version picker works, but is slow. it does not give feedback, it doesn't close
  ![Image](https://user-images.githubusercontent.com/3070389/222403936-96528760-00d6-4f07-84ef-7ec5346d824b.png)
- the info button does not look right in dark mode, it also doesn't close
  ![Image](https://user-images.githubusercontent.com/3070389/222404110-91c7f5dc-4385-44f9-83f8-ef04fa217b91.png)

**Comment by ndelangen** [comment]
The CORS error is because of some code in 6.5:
```
storybookBaseUrl=void 0!==_global.window?_global.window.parent.document.location
```
... which I've been saying is a 'CORS incompatible' pattern, since forever

**Comment by ndelangen** [comment]
It seems there's in-proper handing of v2 `stories.json` files in 7.0 which is causing the bad rendering of the sidebar for the ref.

1 major difference, that's already clear is that v2 doesn't have the `title` property. But there's obviously also other things that are different.

comparing:
![Screenshot 2023-03-02 at 13 10 39](https://user-images.githubusercontent.com/3070389/222425098-97710565-94ed-4e9d-9da3-f46d3e289334.png)

I'm adjusting my hack from above to:
```ts
    // First, split the title into a set of names, separated by '/' and trimmed.
    // @ts-expect-error (this is to support stories.json v2)
    const title = item.title || item.kind;
    const groups = title.trim().split(TITLE_PATH_SEPARATOR);
```

**Comment by ndelangen** [comment]
I think we should remove this log:
> unable to connect to top frame for connecting dev tools

I can't remove it from old storybooks, but we can remove it from 7.0.. I think we should:
https://github.com/storybookjs/storybook/blob/24eafb9928919f615086ff90267b0fbd853bfd3d/code/lib/core-common/templates/base-preview-head.html#L327

It adds no useful information to the user, and will always fail for refs.
Each ref will log this once.

**Comment by tmeasday** [comment]
@ndelangen I'd suggest let's split this ticket into a few different ones:

- Basic functionality (flashing up error state, erroring in weird ways)
- CORS problems.
- MDX in 6.x storybooks.
- Back compatibility to old versions of SB (i.e. index v2).
