### ISSUE TITLE
[Bug]: No JSDoc generation when story outside root or symlinked (MonoRepo Blocker) `ts` + `vite` + `storybook@7.0.0-beta.61`

### ISSUE THREAD

**Issue by D1no** [storybookjs/storybook#21399]
### Describe the bug

Spend a couple hours trying to get storybooks typescript JSDoc to storybook ArgDocs working, but to no avail. As typical with MonoRepos, the UI library sits outside of the testing / build toolchain.

Components render, but there is no ArgDocs generation...

- when stories are included via `"../../"` in `.storybook/main.ts`
or
- when stories are included via a symlink (pnpm workspaces mount project libraries into `node_modules/*lib*/**/*stories*`) — but symlinks anywhere wont work for docgen (see reproduction)

This means docgen doesn't work here:

```js
.
└── MonoRepo/           // git root
    ├── tools/
    │   ├── ...
    │   └── storybook   // <- Storybook root
    │                    
    └── ui/             // React Components
        ├── Component
        ├── Component
        └── ...


### To Reproduce

You find a reproduction as the following git repo:
https://github.com/D1no/reproduction-storybook-symlinks-pnpm

The same component is included as (1) local copy inside `stories/`, (2) as reference in `.storybook/main.ts` and as a (3) symbolic link into `stories/`.

✅ All three types render successfully in storybook.

❌ Only variant (1) has JSDoc converted to story docs (!)

Exact same component and story, but as you see = different location = no JSDocGen.
![storybook_no_jsdocgen](https://user-images.githubusercontent.com/2397125/222922498-ed8c6d83-c2f8-4f0f-b570-30e955ccdc6c.gif)

The Component `index.tsx`

```ts
import React from "react";

interface ComponentProps {
  /**
   * Set the text of the component. This is a JSDoc of the text property.
   */
  text?: string;
}

/**
 * This is the description of the Component as JSDoc.
 */
const Component = ({ text }: ComponentProps) => {
  return <div>This component text says: {text}</div>;
};

export default Component;

```

The Component Story `index.stories.tsx`

```ts
import type { Meta, StoryObj } from "@storybook/react";

import { default as LocalComponent } from "./index";

// More on how to set up stories at: https://storybook.js.org/docs/7.0/react/writing-stories/introduction
const meta = {
  title: "stories/Component (local)",
  component: LocalComponent,
  tags: ["autodocs"],
} satisfies Meta<typeof LocalComponent>;

export default meta;
type Story = StoryObj<typeof meta>;

// More on writing stories with args: https://storybook.js.org/docs/7.0/react/writing-stories/args
export const Component: Story = {
  args: {
    text: "I am a local component inside of tools/stories/Component. And I have docs from the JSDoc comments.",
  },
};

```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.14.1 - ~/.nvs/default/bin/node
    npm: 9.3.1 - ~/.nvs/default/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 97.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-interactions: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-links: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/blocks: ^7.0.0-alpha.8 => 7.0.0-alpha.8
    @storybook/react: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/react-vite: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

I have the feeling, the problem lies in [@joshwooding/vite-plugin-react-docgen-typescript](https://github.com/joshwooding/vite-plugin-react-docgen-typescript) 👀

<sub>_I really love storybook and have mad respect of what you guys are dealing with. For me, to get storybook into more larger projects, it would be important to have reliable mono repository functionality. In the past I recall from engineers issues with SB, be it with nx (or here, pnpm), that some features seem to always not quite work... Not sure what the SB test suit is, but it would be nice to know that common mono repo tools (pnpm worspaces, nx, turborepo, lerna, etc) are — in a basic set-up — in your test suit for features and add-ons. As single root projects seem to be a thing of the past (which is a great thing for test driven development and team scalability). Anyway: Tip to the hat; I hope this repro is helpful!_<sub>

**Comment by D1no** [comment]
Updated Reproduction to `storybook@7.0.0-beta.62`

**Comment by tmeasday** [comment]
I'm not 100% sure about Vite but my best guess is the plugin isn't configured to run on files outside of the CWD.

**Comment by D1no** [comment]
@tmeasday yeah since the Vite configuration is coming from storybook dependencies, and the reproduction simply creates a Vite based storybook set-up:

Manually overwriting / tinkering with how storybook instruments the bundler would be a hack - but not proper functionality.

**Comment by tmeasday** [comment]
I get it, I am just interested in what the source of the problem @D1no

**Comment by D1no** [comment]
@tmeasday I sadly don't understand enough about vite (which is actually the benefit, that you don't need to). I have the gut feeling that this has something to do with this dependency [@joshwooding/vite-plugin-react-docgen-typescript](https://github.com/joshwooding/vite-plugin-react-docgen-typescript) by @joshwooding

**Comment by D1no** [comment]
@tmeasday I've just tried to update the [reproduction](https://github.com/D1no/reproduction-storybook-symlinks-pnpm) from `7.0.0-rc.1` to `7.0.0-rc.3` in hope that it helps you. But now the vite bundler seems to be missing all together 😅 oh boy

`pnpx storybook@next upgrade --prerelease --skip-check`

```bash
➜  tools git:(master) ✗ pnpm run storybook                                   

> tools@ storybook /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools
> storybook dev -p 6006

@storybook/cli v7.0.0-rc.3

ERR! Error: Cannot find module '@storybook/builder-vite'
ERR! Require stack:
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getPreviewBuilder (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:10:1789)
ERR!     at buildDevStandalone (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!     at async dev (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:446:400)
ERR!     at async Command.<anonymous> (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:448:327)
ERR!  Error: Cannot find module '@storybook/builder-vite'
ERR! Require stack:
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js
ERR! - /Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getPreviewBuilder (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:10:1789)
ERR!     at buildDevStandalone (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!     at async dev (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:446:400)
ERR!     at async Command.<anonymous> (/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js:448:327) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.3/node_modules/@storybook/core-server/dist/index.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/dist/generate.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/@storybook+cli@7.0.0-rc.3/node_modules/@storybook/cli/bin/index.js',
ERR!     '/Users/worker/development/_REPRODUCTIONS/reproduction-storybook-symlinks-pnpm/tools/node_modules/.pnpm/storybook@7.0.0-rc.3/node_modules/storybook/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

✔ Would you like to help improve Storybook by sending anonymous crash reports? … yes
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by IanVS** [comment]
@jonniebigodes have you thought about having a section of the docs dedicated to monorepos and the things that need to be done in some situations to get things like the above working?

**Comment by D1no** [comment]
@IanVS I have extended the ticket to a test rig. I hope it helps you.

**Comment by jonniebigodes** [comment]
@IanVS to answer your question, yes, I've considered it, but before committing to it I wanted to collect some information beforehand from our community sources (e.g., here in the issue tracker, and Discord) and see what are the major pain points and how to address them to avoid having the information scattered all around. If you could assist me with this, I'd be thankful for it. We could probably collaborate on it after the 7.0 launch. What do you think? Sounds like a reasonable plan?

**Comment by shilman** [comment]
Can you try out the following canary in your project and let me know whether it resolves any of your issues (or generates new ones)? We're looking to switch the default docgen from `react-docgen-typescript` to `react-docgen`, which is much faster and may also fix some long-standing bugs. Many thanks!

https://github.com/storybookjs/storybook/pull/23825

**Comment by AMSTKO** [comment]
> We need to do a better job documenting this, obviously, but there is a setting that you can use to control which files are included for processing by react-docgen-typescript:
> 
> ```ts
> //.storybook/main.ts
> 
> export default {
> 	//... rest of config
> 	typescript: {
> 		reactDocgenTypescriptOptions: {
> 			include: ['**/**.tsx', '../ui/**/**.tsx'],
> 		},
> 	},
> }
> ```
> 
> This doesn't fix the symlinks. Normally I would suggest setting https://vitejs.dev/config/shared-options.html#resolve-preservesymlinks to true, but that causes other things to break in your repo, likely because of pnpm.

Haha thanks you my god I'm looking for this since 2 days at work

**Comment by Sidnioulz** [comment]
Thanks for reporting this issue. As we've switched the default docgen algorithm for React, we're going to go ahead and close this issue. Please reopen it if you can reproduce it in Storybook 10.1 or more recent. Thanks.
