### ISSUE TITLE
[Bug]: setConfig is not a function

### ISSUE THREAD

**Issue by reskir** [storybookjs/storybook#21423]
### Describe the bug

Getting error in storybook nextjs project `"@storybook/nextjs": "^7.0.0-beta.61",`

Next: `v13.2.3`

```
(0 , import_config.setConfig) is not a function
TypeError: (0 , import_config.setConfig) is not a function
    at ./node_modules/@storybook/nextjs/dist/preview.js (http://localhost:6006/vendors-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_runtime-1fd054.iframe.bundle.js:2770:1173)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:336:25)
    at Object.getProjectAnnotations [as nextFn] (http://localhost:6006/main.iframe.bundle.js:1037:82)
    at http://localhost:6006/sb-preview/runtime.mjs:4:78491
    at Array.forEach (<anonymous>)
    at SynchronousPromise4._runResolutions (http://localhost:6006/sb-preview/runtime.mjs:4:78432)
    at SynchronousPromise4.then (http://localhost:6006/sb-preview/runtime.mjs:4:75974)
    at PreviewWeb.getProjectAnnotationsOrRenderError (http://localhost:6006/sb-preview/runtime.mjs:66:13305)
    at PreviewWeb.initialize (http://localhost:6006/sb-preview/runtime.mjs:66:12623)
```

### System

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-actions: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-essentials: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/addon-interactions: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/nextjs: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/react: ^7.0.0-beta.61 => 7.0.0-beta.61
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context
https://github.com/storybookjs/storybook/blob/c16f84e135a96aa13e23b0516ae26b761d287b0a/code/frameworks/nextjs/src/config/preview.ts#L1-L4

**Comment by dealvz** [comment]
@reskir I know this is old but what was the resolution? Running into something similar as I update our storybook configuration.

**Comment by ritingliudd01** [comment]
Met with the same issue. Appreciate much if you share your solution.
