### ISSUE TITLE
[Bug]: v7. Storyshots stopped working due to failed mocking (between `beta.52` & `rc.3`)

### ISSUE THREAD

**Issue by o-alexandrov** [storybookjs/storybook#21588]
### Describe the bug

Storyshots stopped working due to failed mocking (between `beta.52` & `rc.3`)
Failing trace in `rc.3`:

```
TypeError: Cannot read properties of undefined (reading 'clientApi')

> 13 | initStoryshots()

  at node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:25:49
  at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/react/loader.js:30:23)
  at loadFramework (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:36:19)
  at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:28:99)
```

### To Reproduce

1. Install pkgs (replace `rc.3` w/ `beta.52` to toggle working state)

```
"@storybook/addons": "7.0.0-rc.3",
"@storybook/addon-storyshots": "7.0.0-rc.3",
"@storybook/react-vite": "7.0.0-rc.3",
"storybook": "7.0.0-rc.3",
```

2. Run the following `storyshots.test.js` in `beta.52` (works) & `rc.3` (doesn't work).

```ts
import initStoryshots from "@storybook/addon-storyshots"

initStoryshots()
```

**Comment by o-alexandrov** [comment]
My bad, the issue was in the packages' hoisting during installation, apologies for the noise here.
`rc.3` works for storyshots addon
