### ISSUE TITLE
[Bug]: Bad error message when trying to use JSX in .js file

### ISSUE THREAD

**Issue by C-Higgins** [storybookjs/storybook#21662]
### Describe the bug

```
[storybook:inject-export-order-plugin] Parse error @:22:29
file: ........./src/stories/ApiDocumentation.stories.js
ERR! Error: Parse error @:22:29
ERR!     at parse ........./node_modules/es-module-lexer/dist/lexer.cjs:1:402)
ERR!     at Object.transform (........./node_modules/@storybook/builder-vite/dist/index.js:1:3217)
ERR!     at file:///.........//node_modules/rollup/dist/es/shared/node-entry.js:24343:40
```

The above error will happen if your `.stories.js` file contains any JSX. Renaming the file to `.jsx` fixes the issue. I spent hours trying to figure out the problem. Some better error messaging would be nice here. 

### To Reproduce

Happens in sandbox project with React and Vite.

**Comment by sanchezg7** [comment]
@C-Higgins Thank you! Saved me a bunch of time chasing this error. I had some React jsx in my story file as well. I renamed a storyfile to .jsx extension and the issue went away.

**Comment by kiran-chikkala** [comment]
thank you

**Comment by tadger** [comment]
Is there a workaround for this issue? Eg: continue using `.js` extensions in files containing JSX

If so, I think it could be a great addition to the [Troubleshooting](https://storybook.js.org/docs/builders/vite#troubleshooting) section of the vite-builder setup in the docs.

I run this [vite.config.js](https://gist.github.com/tadger/52136b9afa072013e82db8d47d2fc4d7) as a workaround, but can't seem to get it to work with Storybook.

**Comment by rqzheng2015** [comment]
This post saved my day!!! Thanks @C-Higgins !!!

**Comment by katiaku** [comment]
thanks! spent hours trying to solve that...
