### ISSUE TITLE
[Bug]: Injector has already been destroyed error when opening story for second time

### ISSUE THREAD

**Issue by Adam-Michalski** [storybookjs/storybook#21738]
### Describe the bug

When any story is opened for first time is displayed correctly but when I open other story and return to one which was already opened I get error.

```
ERROR Error: NG0205: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (core.mjs:7986:1)
    at R3Injector.get (core.mjs:7893:1)
    at ChainedInjector.get (core.mjs:12088:1)
    at lookupTokenUsingModuleInjector (core.mjs:3217:1)
    at getOrCreateInjectable (core.mjs:3262:1)
    at NodeInjector.get (core.mjs:3527:1)
    at ViewContainerRef.createComponent (core.mjs:21300:1)
    at FormlyConfig.resolveFieldTypeRef (ngx-formly-core.mjs:411:1)
    at FormlyConfig.getMergedField (ngx-formly-core.mjs:390:1)
    at CoreExtension.initFieldOptions (ngx-formly-core.mjs:2111:1)
```

I have found that some similar issues were solved by angularLegacyRendering: true in preview.js but it does not work for my issue

![image](https://user-images.githubusercontent.com/5684123/226998982-2f77f69d-9fc3-46dd-bb75-dc868c21cc6c.png)

### To Reproduce

https://stackblitz.com/edit/storybook-angular-inline-story-controls-reproduct-w8zp7h

### System

```shell
"dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "@babel/runtime-corejs3": "^7.21.0",
    "@here/maps-api-for-javascript": "1.37.2",
    "@ngx-formly/bootstrap": "^6.1.1",
    "@ngx-formly/core": "^6.1.1",
    "bootstrap": "^5.2.3",
    "bootstrap-icons": "^1.10.3",
    "bs-stepper": "^1.7.0",
    "country-list-js": "^3.1.7",
    "ngx-bootstrap": "^10.2.0",
    "rxjs": "~7.8.0",
    "simple-element-resize-detector": "^1.3.0",
    "storybook": "^6.5.16",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.5",
    "@angular/cli": "~15.1.5",
    "@angular/compiler-cli": "^15.1.0",
    "@babel/core": "^7.20.12",
    "@babel/plugin-transform-runtime": "^7.21.0",
    "@babel/preset-typescript": "^7.21.0",
    "@babel/runtime": "^7.21.0",
    "@compodoc/compodoc": "^1.1.19",
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/angular": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/testing-library": "^0.0.13",
    "@types/country-list-js": "^3.1.2",
    "@types/jasmine": "~4.3.0",
    "@types/simple-element-resize-detector": "^1.3.0",
    "babel-loader": "^8.3.0",
    "copyfiles": "^2.4.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "lint-staged": "^13.1.2",
    "ng-packagr": "^15.1.0",
    "prettier": "2.8.4",
    "typescript": "~4.9.4"
  }
```

### Additional context

My application depends on lib build around FormlyModule (ngx-formly) which is extending available controls, I am using FormlyModule.forRoot in story config and this configuration works in angular app just fine

**Comment by shilman** [comment]
Is this still a problem in 7.0? We're currently in RC and will mainly be supporting that starting in a week or two.

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by losbeekos** [comment]
@shilman I'm running into this problem with 7.0.0-rc.6 as well and have the exact same error as @Adam-Michalski. For me personally it's stories that depend on Angular elements, these web components won't render the second time, the story component itself will render just fine. Refreshing the page will render these Angular elements in the story like it's supposed to. 

I'm using `moduleMetaData` to import the module that will define these Angular elements. This is the only module I've added.

```js
// preview.ts
decorators: [
  moduleMetadata({
    imports: [SomeModuleForTheAngularElements],
  }),
],
```

**Comment by Adam-Michalski** [comment]
> Is this still a problem in 7.0? We're currently in RC and will mainly be supporting that starting in a week or two.
> 
> Migration guide: https://storybook.js.org/migration-guides/7.0

After update to 7.0.0 rc6 issue was still there, downgrading from last 6 version to 6.0.0 also has this issue

**Comment by Adam-Michalski** [comment]
Reproduction is available [HERE](https://stackblitz.com/edit/storybook-angular-inline-story-controls-reproduct-w8zp7h)

**Comment by ryandegruyter** [comment]
@Adam-Michalski did you ever find a solution to this issue?

**Comment by vabelous** [comment]
Without delving into deep details, I can suggest the following solution:
In the file src/core/src/lib/services/formly.config.ts, find the method resolveFieldTypeRef, and replace the code at line 169:
```ts
const componentRef = _viewContainerRef.createComponent<FieldType>(type.component, { injector: _injector });
```
with:
```ts
const componentRef = new type.component();
```

**Comment by fgabrieli** [comment]
I still see this issue just as soon as webpack recompiles, my config is:

```
"@nx/angular": "20.2.1",
"@nx/eslint-plugin": "20.2.1",
"@nx/jest": "20.0.3",
"@nx/js": "20.2.1",
"@nx/storybook": "20.2.1",
"@nx/web": "20.2.1",
"@nx/workspace": "20.2.1",


"@storybook/addon-essentials": "8.4.7",
"@storybook/addon-interactions": "8.4.7",
"@storybook/angular": "8.4.7",
"@storybook/core-server": "8.4.7",
"@storybook/jest": "^0.2.3",
"@storybook/test-runner": "0.19.1",
"@storybook/testing-library": "^0.2.2",
"@storybook/types": "^8.4.7",
```

I have decorators to set up the Application config and theme loading

**Comment by NogaMan** [comment]
Had similar issue when using Angular custom element directly in the component's template, e.g.
```html
<div>
  <some-custom-link href="#">Content</some-custom-link>
</div>
```

I switched to using `innerHTML` to insert such HTML and the problem was gone:
```html
<div [innerHtml]="html"></div>
```

```ts
import {DomSanitizer, SafeHtml} from '@angular/platform-browser';

...

constructor(private sanitizer: DomSanitizer) {}

get html(): SafeHtml {
  return this.sanitizer.bypassSecurityTrustHtml('<some-custom-link href="#">Content</some-custom-link>')
}
```
