### ISSUE TITLE
[Bug]: Error during loading presets, slice of undefined @babel\helper-plugin-utils, @babel\helper-plugin-utils

### ISSUE THREAD

**Issue by Adam-Michalski** [storybookjs/storybook#21737]
### Describe the bug

During start of storybook I get error error TypeError: Cannot read property 'slice' of undefined/
Storybook starts and is usable
Instaling @babel\helper-plugin-utils, @babel\helper-plugin-utils does not fix this issue

```
info @storybook/angular v6.5.16
info
info => Loading presets
WARN   Failed to load preset: {"type":"presets","name":"C:\\Projects\\storybook\\node_modules\\@babel\\plugin-transform-runtime\\lib\\index.js"} on level 1
ERR! TypeError: Cannot read property 'slice' of undefined
ERR!     at throwVersionError (C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:122:15)
ERR!     at Object.assertVersion (C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:24:5)
ERR!     at builder (C:\Projects\storybook\node_modules\@babel\plugin-transform-runtime\src\index.ts:65:7)
ERR!     at C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:64:12
ERR!     at loadPreset (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:207:18)
ERR!     at C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18)
ERR!     at loadPreset (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:225:81)
ERR!     at C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18)
ERR!     at getPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:313:23)
ERR!     at loadAllPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:365:10)
ERR!     at buildDevStandalone (C:\Projects\storybook\node_modules\@storybook\core-server\dist\cjs\build-dev.js:108:48)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at Object.buildDev (C:\Projects\storybook\node_modules\@storybook\core-server\dist\cjs\build-dev.js:174:5)
ERR!  TypeError: Cannot read property 'slice' of undefined
ERR!     at throwVersionError (C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:122:15)
ERR!     at Object.assertVersion (C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:24:5)
ERR!     at builder (C:\Projects\storybook\node_modules\@babel\plugin-transform-runtime\src\index.ts:65:7)
ERR!     at C:\Projects\storybook\node_modules\@babel\helper-plugin-utils\src\index.ts:64:12
ERR!     at loadPreset (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:207:18)
ERR!     at C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18)
ERR!     at loadPreset (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:225:81)
ERR!     at C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:255:18)
ERR!     at getPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:313:23)
ERR!     at loadAllPresets (C:\Projects\storybook\node_modules\@storybook\core-common\dist\cjs\presets.js:365:10)
ERR!     at buildDevStandalone (C:\Projects\storybook\node_modules\@storybook\core-server\dist\cjs\build-dev.js:108:48)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!     at Object.buildDev (C:\Projects\storybook\node_modules\@storybook\core-server\dist\cjs\build-dev.js:174:5)
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Loading angular-cli config for angular >= 13.0.0

```

### Additional context

```
"dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "@here/maps-api-for-javascript": "^1.37.2",
    "@ngx-formly/bootstrap": "^6.1.1",
    "@ngx-formly/core": "^6.1.1",
    "@ngxs/storage-plugin": "^3.7.6",
    "@ngxs/store": "^3.7.6",
    "bootstrap": "^5.2.3",
    "bootstrap-icons": "^1.10.3",
    "bs-stepper": "^1.7.0",
    "country-list-js": "^3.1.7",
    "ngx-bootstrap": "^10.2.0",
    "rxjs": "~7.8.0",
    "simple-element-resize-detector": "^1.3.0",
    "storybook": "^6.5.16",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.5",
    "@angular/cli": "~15.1.5",
    "@angular/compiler-cli": "^15.1.0",
    "@babel/core": "^7.20.12",
    "@babel/helper-plugin-utils": "^7.20.2",
    "@babel/plugin-transform-runtime": "^7.20.2",
    "@babel/preset-typescript": "^7.21.0",
    "@babel/runtime": "^7.21.0",
    "@compodoc/compodoc": "^1.1.19",
    "@storybook/addon-actions": "^6.5.16",
    "@storybook/addon-essentials": "^6.5.16",
    "@storybook/addon-interactions": "^6.5.16",
    "@storybook/addon-links": "^6.5.16",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/angular": "^6.5.16",
    "@storybook/builder-webpack5": "^6.5.16",
    "@storybook/manager-webpack5": "^6.5.16",
    "@storybook/testing-library": "^0.0.13",
    "@types/country-list-js": "^3.1.2",
    "@types/jasmine": "~4.3.0",
    "@types/simple-element-resize-detector": "^1.3.0",
    "babel-loader": "^8.3.0",
    "copyfiles": "^2.4.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "lint-staged": "^13.1.2",
    "ng-packagr": "^15.1.0",
    "prettier": "2.8.4",
    "typescript": "~4.9.4"
  }
```

**Comment by shilman** [comment]
Are you also seeing this error in 7.0? We've made a bunch of Angular improvements there. Please let us know!

Migration guide: https://storybook.js.org/migration-guides/7.0
