### ISSUE TITLE
[Bug]: storybook build not working due to error from `react-refresh-webpack-plugin`: `Cannot read properties of undefined (reading 'tapPromise')`

### ISSUE THREAD

**Issue by lsbyerley** [storybookjs/storybook#21751]
### Describe the bug

After upgrading from `babel-loader` v8 to v9, storybook fails to compile with the following error:

```
ERR! TypeError: Cannot read properties of undefined (reading 'tapPromise')
ERR!     at /app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:104:35
ERR!     at Array.forEach (<anonymous>)
ERR!     at ReactRefreshPlugin.apply (/app/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:103:33)
ERR!     at webpack (/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/webpack.js:51:13)
ERR!     at starterGeneratorFn (/app/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:137:18)
ERR!     at starterGeneratorFn.next (<anonymous>)
ERR!     at Object.start (/app/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:275:34)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer (/app/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/app/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
```

// storybook/config/main.js
```
module.exports = {
  stories: [
    '../../src/**/*.stories.jsx'
  ],
  addons: ['@storybook/addon-essentials'],
  reactOptions: {
    fastRefresh: true,
  },
  features: {
    emotionAlias: false,
  },
};
```

### System

```shell
"babel-loader": "9.1.2",
"@storybook/addon-essentials": "6.5.16",
"@storybook/core": "6.5.16",
"@storybook/react": "6.5.16",
```
```


### Additional context

_No response_

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease. I suspect this is a webpack4/5 issue and 7.0 is webpack5 only, which simplifies things.

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by lsbyerley** [comment]
@shilman upgrading to storybook v7 seems to have resolved the issue, thank you!
