### ISSUE TITLE
[Bug]: CSF does not allow template literal (tags)

### ISSUE THREAD

**Issue by connorjs** [storybookjs/storybook#21761]
### Describe the bug

Using template literals in the CSF default export for `tags` crashes storybook rendering.

```
Error: CSF: Expected tag to be string literal
```

Expected: Template literal should work.

I prefer template literals because it makes it easier to change to interpolation. I use ESLint to auto-fix all strings to template literals for consistency.

### To Reproduce

1. Use any auto docs reference: <https://storybook.js.org/docs/7.0/react/writing-docs/autodocs>

2. Replace single quotes around `autodocs`  with backticks (make it a template literal)

   ```
   //👇 Enables auto-generated documentation for the component story
   tags: [`autodocs`],
   ```

_I can build a sample repo if desired/this weekend 👍🏻_

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.14.2 - ~/.local/share/nvm/v18.14.2/bin/node
    Yarn: 3.5.0 - ~/.local/share/nvm/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.local/share/nvm/v18.14.2/bin/npm
  Browsers:
    Firefox: 111.0.1
    Safari: 16.3
```

### Additional context

Full stack trace

```txt
  Error: CSF: Expected tag to be string literal
    at /ROOT/node_modules/@storybook/csf-tools/dist/index.js:1:3240
    at Array.map (<anonymous>)
    at parseTags (/ROOT/node_modules/@storybook/csf-tools/dist/index.js:1:3186)
    at /ROOT/node_modules/@storybook/csf-tools/dist/index.js:9:558
    at Array.forEach (<anonymous>)
    at CsfFile._parseMeta (/ROOT/node_modules/@storybook/csf-tools/dist/index.js:9:75)
    at enter (/ROOT/node_modules/@storybook/csf-tools/dist/index.js:9:2211)
    at NodePath._call (/ROOT/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/ROOT/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/ROOT/node_modules/@babel/traverse/lib/path/context.js:80:31)
    at TraversalContext.visitQueue (/ROOT/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/ROOT/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/ROOT/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/ROOT/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/ROOT/node_modules/@babel/traverse/lib/path/context.js:86:52)
    at TraversalContext.visitQueue (/ROOT/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/ROOT/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/ROOT/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/ROOT/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at Object.traverse (/ROOT/node_modules/@babel/traverse/lib/index.js:49:34)
    at CsfFile.parse (/ROOT/node_modules/@storybook/csf-tools/dist/index.js:9:1284)
    at Object.indexer (/ROOT/node_modules/@storybook/core-server/dist/presets/common-preset.js:100:69)
    at async StoryIndexGenerator.extractStories (/ROOT/node_modules/@storybook/core-server/dist/index.js:13:3554)
    at async /ROOT/node_modules/@storybook/core-server/dist/index.js:13:1869
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async StoryIndexGenerator.updateExtracted (/ROOT/node_modules/@storybook/core-server/dist/index.js:13:1641)
    at async StoryIndexGenerator.ensureExtracted (/ROOT/node_modules/@storybook/core-server/dist/index.js:13:2262)
    at async StoryIndexGenerator.getIndex (/ROOT/node_modules/@storybook/core-server/dist/index.js:17:3330)
    at async /ROOT/node_modules/@storybook/core-server/dist/index.js:10:5054
```

**Comment by shilman** [comment]
This is a designed limitation of CSF so that it's easier to statically analyze for performance purposes. I don't think we're going to fix this any time soon, but we should document it better.

**Comment by connorjs** [comment]
> so that it's easier to statically analyze for performance purposes

That's good to know. Thanks for that knowledge; I agree documenting it could be helpful.

@shilman - are there any references I can read regarding static analysis issues? I know template literals are different from string literals in JS parsing (AST-wise), but this represents the first mention I've heard regarding static analysis performance concerns.

**Comment by agodinhost** [comment]
Hi,  
I got this very same error message when trying to use concatenated arrays:  

```
export const META_COMMON_INPUT = {
  tags: ['autodocs', 'onefa', 'atoms', 'form-group']
};

const meta: Meta<OnefaTextAreaComponent> = {
  title: 'Lib/FormGroup/TextArea',
  id: 'OnefaTextAreaComponent',
  tags: [... META_COMMON_INPUT.tags, 'Text-Area']
};
```
IMHO it should be acceptable, I mean - the compiler should not complain, right?

**Comment by coopbri** [comment]
Not sure if anyone has any workarounds for this issue, but I opened a discussion last month related to this here: https://github.com/storybookjs/storybook/discussions/24192
