### ISSUE TITLE
[Bug]: Storybook 7.0.0-rc.8 Error: Cannot find module '@storybook/angular/preset' in monorepo (only affects @storybook/angular)

### ISSUE THREAD

**Issue by nstuyvesant** [storybookjs/storybook#21775]
### Describe the bug

Storybook 7.0.0-rc.8 is installed in the package.json for a package within a monorepo. When I run `yarn install`, `@storybook/angular` is installed in the node_modules directory for that package.

However, when I try to run or build the storybook, I get this error that shows it's looking for @storybook/angular/preset in the root for the monorepo. Some @storybook packages are being hoisted and some are not.

```
WARN   Failed to load preset: "@storybook/angular/preset"
ERR! Error: Cannot find module '@storybook/angular/preset'
ERR! Require stack:
ERR! - /Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/nates/dev/carbon-charts/packages/charts-angular/node_modules/@storybook/angular/dist/builders/start-storybook/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-command-module.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/commands/build/cli.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/command-runner.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/cli/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/init.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Module._resolveFilename (/Users/nates/dev/carbon-charts/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!     at interopRequireDefault (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:6:21)
ERR!     at getContent (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:13:332)
ERR!     at loadPreset (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:13:517)
ERR!     at /Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:15:411
ERR!     at Array.map (<anonymous>)
ERR!  Error: Cannot find module '@storybook/angular/preset'
ERR! Require stack:
ERR! - /Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js
ERR! - /Users/nates/dev/carbon-charts/packages/charts-angular/node_modules/@storybook/angular/dist/builders/start-storybook/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-command-module.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/commands/build/cli.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/command-runner.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/cli/index.js
ERR! - /Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/init.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Module._resolveFilename (/Users/nates/dev/carbon-charts/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!     at interopRequireDefault (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:6:21)
ERR!     at getContent (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:13:332)
ERR!     at loadPreset (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:13:517)
ERR!     at /Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js:15:411
ERR!     at Array.map (<anonymous>) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@storybook/core-common/dist/index.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js',
ERR!     '/Users/nates/dev/carbon-charts/packages/charts-angular/node_modules/@storybook/angular/dist/builders/start-storybook/index.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular-devkit/architect/node/index.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/architect-command-module.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/commands/build/cli.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/src/command-builder/command-runner.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/cli/index.js',
ERR!     '/Users/nates/dev/carbon-charts/node_modules/@angular/cli/lib/init.js'
ERR!   ]
ERR! }
ERR! Error: no builder configured!
ERR!     at getPreviewBuilder (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:10:1912)
ERR!     at buildDevStandalone (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!  Error: no builder configured!
ERR!     at getPreviewBuilder (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:10:1912)
ERR!     at buildDevStandalone (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:40:2022)
ERR!     at async withTelemetry (/Users/nates/dev/carbon-charts/node_modules/@storybook/core-server/dist/index.js:27:3469)
```

### To Reproduce

1. Make sure yarn 3.5.0 is installed then...
```
git clone https://github.com/nstuyvesant/carbon-charts.git
cd carbon-charts
git checkout next
git pull
# Remove the line nmHoistingLimits: workspaces from the top-level .yarnrc.yml file then perform these steps...
yarn install
yarn build
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.15.0 - /opt/homebrew/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0
    Safari: 16.3
  npmPackages:
    @storybook/angular: ^7.0.0-0 => 7.0.0-rc.8 
    @storybook/theming: ^7.0.0-0 => 7.0.0-rc.8
```

For me, the workaround was to add this line:
```
nmHoistingLimits: workspaces
```
to my .yarnrc.yml file.

**Comment by nstuyvesant** [comment]
Actually, I see that it is assuming @storybook/angular will be on the monorepo's root node_modules (not a good assumption).

**Comment by nstuyvesant** [comment]
Additionally, this Angular component library is in an Angular Workspace within a larger monorepo. It's also looking for the @storybook/angular package in the root node_modules folder rather than the local package for some reason.

**Comment by nstuyvesant** [comment]
Updated the steps above to take out my workaround.

That workaround involves forcing yarn to not hoist any package dependencies by adding this line to the top-level `.yarnrc.yml`...
```
nmHoistingLimits: workspaces
```

But it's not an ideal workaround.

**Comment by david-diaz1** [comment]
Getting the same error with "@storybook/vue-webpack5/preset"

<img width="1194" alt="Screen Shot 2023-03-27 at 5 08 14 PM" src="https://user-images.githubusercontent.com/124402937/228077931-564ef897-70cb-4308-8aa7-5c5094f3c336.png">

**Comment by shilman** [comment]
closing as dupe to #21710 cc @yannbf
