### ISSUE TITLE
[Bug]: Module not found: Error: Resolving to directories is not possible with the exports field

### ISSUE THREAD

**Issue by theMasix** [storybookjs/storybook#21787]
### Describe the bug

I migrated from `v6` to `v7` by running the migration script:

```
npx storybook@next upgrade --prerelease
```

Then I followed these two links to make sure that everything has been migrated successfully and no more breakchanges remain:

- [From version 6.5.x to 7.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700)
- [Migration guide for Storybook 7.0](https://storybook.js.org/docs/7.0/react/migration-guide)

After running `storybook dev` or `storybook build` I get the following error:

```txt
99% end closing watch compilationWARN Force closed preview build
/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2016
                                        const notFoundError = new ModuleNotFoundError(
                                                              ^

ModuleNotFoundError: Module not found: Error: Resolving to directories is not possible with the exports field (request was ./)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2016:28)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:798:13)
    at eval (eval at create (/Users/user/project/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:10:1)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:270:22)
    at eval (eval at create (/Users/user/project/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:9:1)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:434:22)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:116:11)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:670:25)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:855:8)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:975:5)
/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2016
                                        const notFoundError = new ModuleNotFoundError(
                                                              ^

ModuleNotFoundError: Module not found: Error: Resolving to directories is not possible with the exports field (request was ./)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compilation.js:2016:28)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:798:13)
    at eval (eval at create (/Users/user/project/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:10:1)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:270:22)
    at eval (eval at create (/Users/user/project/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:9:1)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:434:22)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:116:11)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:670:25)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:855:8)
    at null.<anonymous> (/Users/user/project/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/NormalModuleFactory.js:975:5)
```

### System

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-essentials: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-interactions: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-links: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/addon-mdx-gfm: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/react: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/react-webpack5: ^7.0.0-rc.8 => 7.0.0-rc.8 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by theMasix** [comment]
The issue was about importing components from `@storybook/addon-docs/` instead of `@storybook/addon-docs` (Look at trailing extra `/` at the end of import path.

It seems that webpack@4 can handle this import path but 5 can't.

Issue closed
