### ISSUE TITLE
[Bug]: Storybook migrate (7) doesn't work with workspace:*

### ISSUE THREAD

**Issue by yarinsa** [storybookjs/storybook#21806]
### Describe the bug

SB Migration tool is trying to detect the typescript version in order to determine the project type, but it fails because of the syntax "workspace:*" which is adopted by yarn/pnpm
run:  `pnpm dlx storybook@next init`

### To Reproduce

Add typescript as dependency to your project.
Change the version field to "workspace:*"
Run `

### System

  System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Max
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.1
### Additional context

```

 storybook init - the simplest way to add a Storybook to your project. 

 • Detecting project type. ✓
ERR! TypeError: Invalid Version: null
ERR!     at new SemVer (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/classes/semver.js:19:13)
ERR!     at compare (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/compare.js:3:3)
ERR!     at Object.gte (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/gte.js:2:30)
ERR!     at /Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:6403
ERR!     at hasDependency (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:3968)
ERR!     at detectLanguage (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:6332)
ERR!     at installStorybook (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:354:363)
ERR!     at doInitiate (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:384:84)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async withTelemetry (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.9/node_modules/@storybook/core-server/dist/index.js:27:3469)
ERR!  TypeError: Invalid Version: null
ERR!     at new SemVer (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/classes/semver.js:19:13)
ERR!     at compare (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/compare.js:3:3)
ERR!     at Object.gte (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/semver@7.3.8/node_modules/semver/functions/gte.js:2:30)
ERR!     at /Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:6403
ERR!     at hasDependency (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:3968)
ERR!     at detectLanguage (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:13:6332)
ERR!     at installStorybook (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:354:363)
ERR!     at doInitiate (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+cli@7.0.0-rc.9/node_modules/@storybook/cli/dist/generate.js:384:84)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async withTelemetry (/Users/yarinsasson/Library/pnpm/store/v3/tmp/dlx-1060/node_modules/.pnpm/@storybook+core-server@7.0.0-rc.9/node_modules/@storybook/core-server/dist/index.js:27:3469)

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

Waiting for the debugger to disconnect...
 ERROR  Command failed with exit code 1: storybook init

pnpm: Command failed with exit code 1: storybook init
    at makeError (/Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:23351:17)
    at handlePromise (/Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:23922:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:219659:7)
    at async /Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:227399:21
    at async main (/Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:227366:34)
    at async runPnpm (/Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:227621:5)
    at async /Users/yarinsasson/.cache/node/corepack/pnpm/7.29.2/dist/pnpm.cjs:227613:7
Waiting for the debugger to disconnect...
```

**Comment by yannbf** [comment]
Seems like this is an issue when passing an invalid version to semver in [this line](https://github.com/storybookjs/storybook/blob/next/code/lib/cli/src/detect.ts#L174). We could do an early check and if the version is not parseable, we just use typescript 3.8 templates as long as the user has Typescript installed!

**Comment by yannbf** [comment]
As a workaround for now @yarinsa please change the typescript version to any valid version, and after initiating Storybook, change it back to what it was!

**Comment by dannyhw** [comment]
@yannbf what do you mean by valid version? is there a specific version range supported? Or you mean like malformed?

**Comment by yarinsa** [comment]
@dannyhw He means server compliant version I believe

**Comment by dannyhw** [comment]
Hmm ok well someone was commenting on about a similar issue here and it was with typescript 5 https://github.com/storybookjs/react-native/issues/464

**Comment by prodkt** [comment]
We receive the same errors working with SB7 with pnpm workspaces (pnpm v 8.2.0). No fix has been found on our end and are unable to use storybook at the moment. Look forward to seeing what the fix ends up being.

**Comment by yannbf** [comment]
Hey there, especially OP @yarinsa, this issue should be fixed in recent versions of Storybook! It now has a different logic to assert installed versions of packages, and therefore `workspace:*` should work as well.

**Comment by yarinsa** [comment]
Thanks, I will check it soon
