### ISSUE TITLE
[Bug]: Angular - NullInjectorError: No provider for InjectionToken

### ISSUE THREAD

**Issue by habertm** [storybookjs/storybook#21896]
### Describe the bug

When having a story similar to 
```
export default {
  title: 'MyComponent',
  component: MyComponent,
  decorators: [
    moduleMetadata({
      imports: [MyModule.forRoot('foo')],
    }),
  ],
}
```

with 
```
export const MY_TOKEN = new InjectionToken<string>('MY_TOKEN');

@NgModule({})
export class MyModule {
  public static forRoot(value: string): ModuleWithProviders<MyModule> {
    return {
      ngModule: MyModule,
      providers: [{ provide: MY_TOKEN , useValue: value}],
    };
  }
}
```
and the component (or any dependant child) is injecting `MY_TOKEN`
it throws the following error within the story:
`NullInjectorError: No provider for InjectionToken MY_TOKEN!`

### To Reproduce

Sandbox failed:

```
npx sb@next sandbox

√ 🌈 Select the template » Angular CLI (latest)   
√ Enter the output directory ... angular-cli/default-ts
🏃 Adding Angular CLI (latest) into C:\code\code3\angular-cli\default-ts
📦 Downloading sandbox template...
🚨 Failed to download sandbox template: fetch failed
🚨 Failed to create sandbox
ERR! TypeError: fetch failed
ERR!     at Object.fetch (node:internal/deps/undici/undici:14152:11)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async sendFetch (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:63:10)  
ERR!     at async download (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:29:20)   
ERR!     at async downloadTemplate (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:246:5)
ERR!     at async sandbox (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:407:1505)      
ERR!  TypeError: fetch failed
ERR!     at Object.fetch (node:internal/deps/undici/undici:14152:11)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async sendFetch (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:63:10)  
ERR!     at async download (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:29:20)   
ERR!     at async downloadTemplate (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\giget\dist\shared\giget.a16f8b31.cjs:246:5)
ERR!     at async sandbox (C:\Users\habertm\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@stortorybook\cli\dist\generate.js:407:1505) {
ERR!   cause: Error: connect ECONNREFUSED 140.82.121.4:443
ERR!       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
ERR!     errno: -4078,
ERR!     code: 'ECONNREFUSED',
ERR!     syscall: 'connect',
ERR!     address: '140.82.121.4',
ERR!     port: 443
ERR!   }
ERR! }
```

### System

```shell
$ npx sb@next info

Environment Info:

  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
  npmPackages:
    @storybook/addon-essentials: 7.0.2 => 7.0.2
    @storybook/addons: 7.0.2 => 7.0.2
    @storybook/angular: 7.0.2 => 7.0.2
    @storybook/core-server: 7.0.2 => 7.0.2
    @storybook/theming: 7.0.2 => 7.0.2
```

### Additional context

Error does not occur in <=`7.0.0-rc.10` but for  >`7.0.0-rc.11`
Running with `pnpm v7.29.3`
Running with `ng v15.2.1`

**Comment by valentinpalkovic** [comment]
@habertm please follow the migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

**Comment by habertm** [comment]
@valentinpalkovic Following the migration guide helps, thank you.

Although I dont like the idea of breaking the API to standalone API,
while Angular leaves the option to devs which way to go.
