### ISSUE TITLE
[Bug]: Unexpected Token on valid TS syntax (generic in function body)

### ISSUE THREAD

**Issue by thomas-at-perdoo** [storybookjs/storybook#21903]
### Describe the bug

I'm on Storybook 6.5 and for the first time in our project we have added this syntax:

```tsx
// path/Select.ts
export function Select<Item>() {
  const Dropdown = SelectDropdown;
  const Options = SelectOptions;
  const Option = SelectOption<Item>;
  // ...
}
```

It compiles just fine with `yarn tsc` but `yarn storybook` gives us this:

```
ModuleBuildError: Module build failed (from ./node_modules/@storybook/builder-webpack5/node_modules/babel-loader/lib/index.js):
SyntaxError: /path/src/common/inputs/Select/Select.ts: Unexpected token (13:35)

  11 |   const Dropdown = SelectDropdown;
  12 |   const Options = SelectOptions;
> 13 |   const Option = SelectOption<Item>;
     |                                    ^
  14 |   const Root = SelectRoot<Item>;
  15 |   const Searchbox = SelectSearchbox;
  16 |   const Trigger = SelectTrigger;
    at Parser._raise (/path/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:798:17)
```

Is Storybook on another version of TypeScript or am I missing some Babel plugins?

### To Reproduce

I can't reproduce on 7.0+ and I can't find a way to create a sanbox for 6.5. Please let me know if there's a way.

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.14.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Edge: 111.0.1661.62
    Firefox: 109.0
    Safari: 16.3
```

**Comment by shilman** [comment]
Is this only a problem on 6.5?

**Comment by thomas-at-perdoo** [comment]
> Is this only a problem on 6.5?

Not sure. But I've tried to reproduce it in 7.0 and I couldn't.

**Comment by thomas-at-perdoo** [comment]
This is our `.storybook/main.js` (it's inside a NextJS 13 project):

```js
const path = require('path');

// Based on: https://theodorusclarence.com/blog/nextjs-storybook-tailwind
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  staticDirs: ['../public'],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "storybook-addon-next",
    "storybook-addon-apollo-client",
    {
      /**
       * Fix Storybook issue with PostCSS@8
       * @see https://github.com/storybookjs/storybook/issues/12668#issuecomment-773958085
       */
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "webpack5"
  },
  webpackFinal: async (config) => {
    // This enables absolute imports from within src
    config.resolve.modules = [
      ...(config.resolve.modules || []),
      path.resolve(__dirname, "../src"),
    ];

    return config;
  },
}
```

**Comment by ndelangen** [comment]
It's confusing to me.how this is a problem in 6.5 and not in 7.0.

I's expect this issue to come from the babel-config-file not being setup to deal with typescript.

last line of the error:
```
at Parser._raise (/path/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:798:17)
```

**Comment by thomas-at-perdoo** [comment]
Is there a way for me to create a 6.5 sandbox? If so I might be able to create a reproducible example.

**Comment by ndelangen** [comment]
Is the file in a location that's much different from other files where this syntax works?

**Comment by thomas-at-perdoo** [comment]
Nope it's located in `src/common/inputs` where there are about 30 other components and some of those have `.stories.tsx` files as well.

**Comment by ndelangen** [comment]
Hey @thomas-at-perdoo I suggest you debug what babel is doing for the problematic file (and 1 that does work) with this debugging tool by babel:
https://babeljs.io/docs/configuration#print-effective-configs

**Comment by thomas-at-perdoo** [comment]
@ndelangen Thanks, this is the output:

```
Babel configs on "/path/src/common/inputs/Select/Select.ts" (ascending priority):
programmatic options from babel-loader
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "/path/node_modules/@babel/preset-env/lib/index.js",
      {
        "shippedProposals": true,
        "loose": true
      }
    ],
    "/path/node_modules/@babel/preset-typescript/lib/index.js",
    [
      "/path/node_modules/@babel/preset-react/lib/index.js",
      {
        "runtime": "automatic"
      }
    ],
    "/path/node_modules/@babel/preset-flow/lib/index.js"
  ],
  "plugins": [
    "/path/node_modules/@babel/plugin-transform-shorthand-properties/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-block-scoping/lib/index.js",
    [
      "/path/node_modules/@babel/plugin-proposal-decorators/lib/index.js",
      {
        "legacy": true
      }
    ],
    [
      "/path/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
      {
        "loose": true
      }
    ],
    [
      "/path/node_modules/@babel/plugin-proposal-private-property-in-object/lib/index.js",
      {
        "loose": true
      }
    ],
    [
      "/path/node_modules/@babel/plugin-proposal-private-methods/lib/index.js",
      {
        "loose": true
      }
    ],
    "/path/node_modules/@babel/plugin-proposal-export-default-from/lib/index.js",
    "/path/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js",
    [
      "/path/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js",
      {
        "loose": true,
        "useBuiltIns": true
      }
    ],
    "/path/node_modules/@babel/plugin-transform-classes/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-parameters/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-destructuring/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-spread/lib/index.js",
    "/path/node_modules/@babel/plugin-transform-for-of/lib/index.js",
    "/path/node_modules/babel-plugin-macros/dist/index.js",
    "/path/node_modules/@babel/plugin-proposal-optional-chaining/lib/index.js",
    "/path/node_modules/@babel/plugin-proposal-nullish-coalescing-operator/lib/index.js",
    [
      "/path/node_modules/@storybook/core-common/node_modules/babel-plugin-polyfill-corejs3/lib/index.js",
      {
        "method": "usage-global",
        "absoluteImports": "/path/node_modules/@storybook/core-common/node_modules/core-js/index.js",
        "version": "3.15.2"
      }
    ],
    "/path/node_modules/babel-plugin-add-react-displayname/index.js",
    "styled-jsx/babel"
  ],
  "filename": "/path/src/common/inputs/Select/Select.ts",
  "sourceMaps": true,
  "sourceFileName": "/path/src/common/inputs/Select/Select.ts",
  "caller": {
    "name": "babel-loader",
    "target": "web",
    "supportsStaticESM": true,
    "supportsDynamicImport": true,
    "supportsTopLevelAwait": true
  }
}
-----End Babel configs-----
```

**Comment by thomas-at-perdoo** [comment]
> Hey @thomas-at-perdoo I suggest you debug what babel is doing for the problematic file (and 1 that does work) with this debugging tool by babel: https://babeljs.io/docs/configuration#print-effective-configs

Btw there no file that works with that syntax. It's the first we use generics like that. We have many other files using "regular" TS features such as `type`, `interface`, etc. but this is the first time we get an error that is different from `yarn tsc`.
I think that this specific use of generics is giving some issues. If I remove those generics `Select.ts` works just fine.

**Comment by ndelangen** [comment]
@thomas-at-perdoo Maybe try upgrading dependencies? re-generate your lockfile?

**Comment by thomas-at-perdoo** [comment]
@ndelangen Thanks everybody for the quick replies but we had to move on. We reverted the change that added that code and will focus on upgrading to Storybook 7 relatively soon.
Closing this for now.
