### ISSUE TITLE
[Bug]: Storybook v7 migration fails with ELSPROBLEMS

### ISSUE THREAD

**Issue by brightsider** [storybookjs/storybook#21904]
### Describe the bug

I can't migrate because some versions require an old version of packages, but I try to start with downgrading react-dom, but It doesn't help because some of the legacy packages want to use 16.8.5. If I downgraded all these packages, the project wouldn't be compiled.

I need ability to migrate with skipping this step.

```
ERR! Error: npm ERR! code ELSPROBLEMS
ERR! npm ERR! invalid: react-dom@18.2.0../node_modules/react-dom
ERR! npm ERR! invalid: react@18.2.0../node_modules/react
ERR! npm ERR! invalid: typescript@5.0.3../node_modules/typescript
ERR! npm ERR! missing: webrtc-adapter@>=4.1.1, required by mic-recorder-to-mp3@2.2.2
ERR! npm ERR! invalid: postcss@7.0.39../node_modules/postcss
ERR! npm ERR! invalid: acorn@7.4.1../node_modules/acorn
ERR! npm ERR! invalid: ajv@6.12.6../node_modules/ajv
ERR! npm ERR! invalid: rollup@3.20.2../node_modules/rollup
ERR! {
ERR!   "error": {
ERR!     "code": "ELSPROBLEMS",
ERR!     "summary": "invalid: react-dom@18.2.0../node_modules/react-dom\ninvalid: react@18.2.0../node_modules/react\ninvalid: typescript@5.0.3../node_modules/typescript\nmissing: webrtc-adapter@>=4.1.1, required by mic-recorder-to-mp3@2.2.2\ninvalid: postcss@7.0.39../node_modules/postcss\ninvalid: acorn@7.4.1../node_modules/acorn\ninvalid: ajv@6.12.6../node_modules/ajv\ninvalid: rollup@3.20.2../node_modules/rollup",
ERR!     "detail": ""
ERR!   }
ERR! }
ERR! 
ERR!     at NPMProxy.executeCommand (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:39:1669)
ERR!     at NPMProxy.findInstallations (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:39:2303)
ERR!     at automigrate (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:317:1066)
ERR!     at async doUpgrade (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:390:2893)
ERR!     at async withTelemetry (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async upgrade (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:390:3336)
ERR!  Error: npm ERR! code ELSPROBLEMS
ERR! npm ERR! invalid: react-dom@18.2.0../node_modules/react-dom
ERR! npm ERR! invalid: react@18.2.0../node_modules/react
ERR! npm ERR! invalid: typescript@5.0.3../node_modules/typescript
ERR! npm ERR! missing: webrtc-adapter@>=4.1.1, required by mic-recorder-to-mp3@2.2.2
ERR! npm ERR! invalid: postcss@7.0.39../node_modules/postcss
ERR! npm ERR! invalid: acorn@7.4.1../node_modules/acorn
ERR! npm ERR! invalid: ajv@6.12.6../node_modules/ajv
ERR! npm ERR! invalid: rollup@3.20.2../node_modules/rollup
ERR! {
ERR!   "error": {
ERR!     "code": "ELSPROBLEMS",
ERR!     "summary": "invalid: react-dom@18.2.0../node_modules/react-dom\ninvalid: react@18.2.0../node_modules/react\ninvalid: typescript@5.0.3../node_modules/typescript\nmissing: webrtc-adapter@>=4.1.1, required by mic-recorder-to-mp3@2.2.2\ninvalid: postcss@7.0.39../node_modules/postcss\ninvalid: acorn@7.4.1../node_modules/acorn\ninvalid: ajv@6.12.6../node_modules/ajv\ninvalid: rollup@3.20.2../node_modules/rollup",
ERR!     "detail": ""
ERR!   }
ERR! }
ERR! 
ERR!     at NPMProxy.executeCommand (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:39:1669)
ERR!     at NPMProxy.findInstallations (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:39:2303)
ERR!     at automigrate (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:317:1066)
ERR!     at async doUpgrade (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:390:2893)
ERR!     at async withTelemetry (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/core-server/dist/index.js:35:3422)
ERR!     at async upgrade (/Users/user/.npm/_npx/eb8bf615e50a412a/node_modules/@storybook/cli/dist/generate.js:390:3336)
```

**Comment by shilman** [comment]
Can you explain a bit more about what's going on here?

**Comment by brightsider** [comment]
@shilman I just run `npx storybook@next upgrade`. Option --debug doesn't show more info.

**Comment by ndelangen** [comment]
@brightsider I am also confused what it is you're trying to do, and what the expected outcome it.

It sounds as if you want to upgrade storybook, but keep an older version of react?
Have you considered using a yarn resolution?

**Comment by brightsider** [comment]
@ndelangen no, I want to leave the newer versions of packages, but some packages want the older versions.

Switching to yarn2 for migration helps me.
