### ISSUE TITLE
[Bug]: Vite Storybook's fails silently with a blank screen if globs target `.mdx` files but `addon-docs` is not configured.

### ISSUE THREAD

**Issue by JReinhold** [storybookjs/storybook#21914]
### Describe the bug

In the following scenario:

1. Uses a Vite based framework
2. Stories globs targets `.mdx` somehow (like the default)
3. `@storybook/addon-docs` is not configured in main, both not explicitly and the `@storybook/addon-essentials` must also not be there.

Storybook starts up "fine", but shows a blank screen without content, no error in the terminal. The browser console has a React error.

### Additional context

Webpack-based projects will instead fail to start with:

```
ModuleParseError: Module parse failed: Unexpected token (11:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import StackAlt from './assets/stackalt.svg';
|
> <Meta title="Example/Introduction" />
|
| <style>
    at handleParseError (/Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/webpack/lib/NormalModule.js:741:23)
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/webpack/lib/NormalModule.js:843:9
    at processResult (/Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/webpack/lib/NormalModule.js:597:14)
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/webpack/lib/NormalModule.js:646:9
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/loader-runner/lib/LoaderRunner.js:368:5
    at iterateNormalLoaders (/Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/loader-runner/lib/LoaderRunner.js:213:12)
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/loader-runner/lib/LoaderRunner.js:205:7
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/webpack/lib/NormalModule.js:626:20
    at Array.eval (eval at create (/Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/tapable/lib/HookCodeFactory.js:28:14), <anonymous>:12:1)
    at runCallbacks (/Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:18:17)
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:149:7
    at /Users/jeppe/dev/temp/sb-no-addons-wp/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by angeloreis** [comment]
solution?

**Comment by JReinhold** [comment]
@angeloreis I can't tell from that if your problem is related to this issue or not. I think your best bet is to open a support thread in Discord.

discord.gg/storybook
