### ISSUE TITLE
[Bug]: MDX, MD import throwing missing OverlayScrollbarsComponent import

### ISSUE THREAD

**Issue by FBNitro** [storybookjs/storybook#21987]
### Describe the bug

I have a readme that I import using the new raw import format with the <Markdown> wrapper. 

I am on SB@7.0.2

A basic one is working fine, but the second I add a code block, the MD file fails to load with what appears to be a missing import.  I didn't trace very far, but looking at the @addon-docs, the overlayscrollbars is listed as a dev dependency, maybe it should be a non-dev dependency (I didn't dig into it that hard, maybe it's a dependency that import it).

The MDX file is similar to the one provided in the upgrade to 7.x docs:
```mdx
import { Meta, Markdown } from '@storybook/addon-docs';
import Readme from './README.md?raw';

<Meta title="README" />

<Markdown>{Readme}</Markdown>
```

The README.md file
```
This is my MD file.  

Here's a code sample:
```tsx
const MyComponent = () => {
    const [someState, setSomeState] = useState({
        a: 'b',
        c: 'd',
        e: true,
    });

    return (
        <>
            <button type="button" onClick={() => setSomeState(old => ({
                ...old,
                e:false,
            }))}>
            <Something
                state={someState} 
                aBoolean
            >
                <SomethingElse/> ...
            </Something>
        </>
    );
}
```

callstack:
```
caught TypeError: (0 , import_overlayscrollbars.default) is not a function
    at index.js:12:26334
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1
    at workLoop (scheduler.development.js:266:1)
(anonymous) @ index.js:12
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18687 The above error occurred in the <OverlayScrollbarsComponent> component:

    at OverlayScrollbarsComponent (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:26256)
    at Suspense
    at Scroller (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:28662)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at UnstyledScroller (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:32304)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at SyntaxHighlighter2 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:33525)
    at Suspense
    at SyntaxHighlighter3 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2431:8224)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at Source (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:393:2254)
    at CodeOrSourceMdx (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:455:2804)
    at p
    at div
    at __WEBPACK_DEFAULT_EXPORT__ (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:4659:12874)
    at Markdown2 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:455:6157)
    at MDXContent (http://localhost:6007/MyComponent-MyComponent-stories-mdx.iframe.bundle.js:249:111)
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at DocsPageWrapper (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:393:10196)
    at ThemeProvider (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:4615)
    at SourceContainer (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:414:1562)
    at DocsContainer (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:471:3601)
    at Docs (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:473:2557)
    at MDXProvider (http://localhost:6007/MyComponent-MyComponent-migration-stories-mdx.iframe.bundle.js:196:23)
    at ErrorBoundary (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:256:300)
    at WithCallback (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_preview_mjs-node_modules_storybook_addon-essen-b5084f.iframe.bundle.js:1169:34)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushPassiveEffectsImpl @ react-dom.development.js:27060
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
5react-dom.development.js:18687 The above error occurred in the <OverlayScrollbarsComponent> component:

    at OverlayScrollbarsComponent (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:26256)
    at Suspense
    at Scroller (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:28662)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at UnstyledScroller (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:32304)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at SyntaxHighlighter2 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2095:33525)
    at Suspense
    at SyntaxHighlighter3 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2431:8224)
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at Source (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:393:2254)
    at CodeOrSourceMdx (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:455:2804)
    at pre
    at div
    at __WEBPACK_DEFAULT_EXPORT__ (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:4659:12874)
    at Markdown2 (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:455:6157)
    at MDXContent (http://localhost:6007/MyComponent-MyComponent-stories-mdx.iframe.bundle.js:249:111)
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at div
    at http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:3324
    at DocsPageWrapper (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:393:10196)
    at ThemeProvider (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:2698:4615)
    at SourceContainer (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:414:1562)
    at DocsContainer (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:471:3601)
    at Docs (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:473:2557)
    at MDXProvider (http://localhost:6007/MyComponent-MyComponent-migration-stories-mdx.iframe.bundle.js:196:23)
    at ErrorBoundary (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:256:300)
    at WithCallback (http://localhost:6007/vendors-node_modules_storybook_addon-docs_dist_preview_mjs-node_modules_storybook_addon-essen-b5084f.iframe.bundle.js:1169:34)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
flushPassiveEffectsImpl @ react-dom.development.js:27060
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
```

### To Reproduce

100% honesty up front, I cannot reproduce if I use the sb@next sandbox.  I don't know if it was fixed in the alpha, or if I just cannot repo it.

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by SanderWorxs** [comment]
I have the exact same error when attempting to create or open a Source Doc Block. I am using Storybook 7.0.10 with Angular v15. No custom webpack in use. I have already attempted installing the OverlayScrollbars package to no avail.

`react-dom.production.min.js:189 TypeError: (0 , import_overlayscrollbars.default) is not a function
    at OverlayScrollbars-VAV6LJAB.mjs:9:1
    at Rj (react-dom.production.min.js:244:1)
    at Ik (react-dom.production.min.js:286:1)
    at react-dom.production.min.js:282:1
    at J (scheduler.production.min.js:13:1)
    at MessagePort.R (scheduler.production.min.js:14:1)
Mi @ react-dom.production.min.js:189
Ri.f.componentDidCatch.c.callback @ react-dom.production.min.js:190
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:261
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Ik @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14`

Yarn: 1.22.19
Node: 18.12.1
Npm: 8.19.2
Angular: 15.2.6
Chrome: 112.0.5615.138
Windows: 10
