### ISSUE TITLE
[Bug]: Cannot read file "src/util": is a directory

### ISSUE THREAD

**Issue by BrunoQuaresma** [storybookjs/storybook#22060]
### Describe the bug

When running `yarn storybook` I get the error: `Cannot read file "src/util": is a directory`

### System

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Xeon(R) E-2176G CPU @ 3.70GHz
  Binaries:
    Node: 16.19.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - /usr/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
  npmPackages:
    @storybook/addon-actions: 7.0.4 => 7.0.4 
    @storybook/addon-essentials: 7.0.4 => 7.0.4 
    @storybook/addon-links: 7.0.4 => 7.0.4 
    @storybook/addon-mdx-gfm: 7.0.4 => 7.0.4 
    @storybook/react: 7.0.4 => 7.0.4 
    @storybook/react-vite: 7.0.4 => 7.0.4
```

### Additional context

Error:
```
yarn storybook
yarn run v1.22.19
$ storybook dev -p 6006
@storybook/cli v7.0.4

WARN The "@storybook/addon-mdx-gfm" addon is meant as a migration assistant for Storybook 7.0; and will likely be removed in a future version.
WARN It's recommended you read this document:
WARN https://storybook.js.org/docs/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm
WARN 
WARN Once you've made the necessary changes, you can remove the addon from your package.json and storybook config.
info => Serving static files from ././static at /
info => Starting manager..
╭─────────────────────────────────────────────────╮
│                                                 │
│   Storybook 7.0.4 for react-vite started        │
│   572 ms for manager and 7.65 s for preview     │
│                                                 │
│    Local:            http://localhost:6006/     │
│    On your network:  http://172.20.0.3:6006/    │
│                                                 │
╰─────────────────────────────────────────────────╯
✘ [ERROR] Cannot read file "src/util": is a directory

    node_modules/graceful-fs/graceful-fs.js:6:19:
      6 │ var util = require('util')
        ╵                    ~~~~~~

/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/graceful-fs/graceful-fs.js:6:19: ERROR: Cannot read file "src/util": is a directory
    at failureErrorWithLog (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1575:15)
    at <anonymous> (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1033:28)
    at runOnEndCallbacks (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1031:7)
    at <anonymous> (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:1143:14)
    at responseCallbacks.<computed> (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/home/coder/coder/site/node_modules/vite/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: 'node_modules/graceful-fs/graceful-fs.js',
        length: 6,
        line: 6,
        lineText: "var util = require('util')",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Cannot read file "src/util": is a directory'
    }
  ],
  warnings: []
}
````

**Comment by BrunoQuaresma** [comment]
We had an alias on vite that had the name "util" conflicting with the nodejs standard package "util"
