### ISSUE TITLE
[Bug]: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"

### ISSUE THREAD

**Issue by DavidArmendariz** [storybookjs/storybook#22252]
### Describe the bug

When running `storybook build` in the new version 7.0.7 I am getting this error:
```
✘ [ERROR] No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"

    node_modules/@storybook/preview-api/dist/chunk-3B6HRLCB.mjs:11:526:
      11 │ ...m"@storybook/global";import{CURRENT_STORY_WAS_SET,DOCS_PREPARED,PRELOAD_ENTRIES,PREVIEW_KEYDOWN,SET_CURRENT_STORY...
         ╵                                                      ~~~~~~~~~~~~~

ERR! Error: Build failed with 1 error:
ERR! node_modules/@storybook/preview-api/dist/chunk-3B6HRLCB.mjs:11:526: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR!     at failureErrorWithLog (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1636:15)
ERR!     at /home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1048:25
ERR!     at runOnEndCallbacks (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1471:45)
ERR!     at buildResponseToResult (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1046:7)
ERR!     at /home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1075:16
ERR!     at responseCallbacks.<computed> (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:697:9)
ERR!     at handleIncomingPacket (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:752:9)
ERR!     at Socket.readFromStdout (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:673:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:324:12)
ERR!  Error: Build failed with 1 error:
ERR! node_modules/@storybook/preview-api/dist/chunk-3B6HRLCB.mjs:11:526: ERROR: No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"
ERR!     at failureErrorWithLog (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1636:15)
ERR!     at /home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1048:25
ERR!     at runOnEndCallbacks (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1471:45)
ERR!     at buildResponseToResult (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1046:7)
ERR!     at /home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:1075:16
ERR!     at responseCallbacks.<computed> (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:697:9)
ERR!     at handleIncomingPacket (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:752:9)
ERR!     at Socket.readFromStdout (/home/david/eVisit/evisit-ui/node_modules/esbuild/lib/main.js:673:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:324:12) {
ERR!   errors: [
ERR!     {
ERR!       detail: undefined,
ERR!       id: '',
ERR!       location: [Object],
ERR!       notes: [],
ERR!       pluginName: '',
ERR!       text: 'No matching export in "global-externals:@storybook/core-events" for import "DOCS_PREPARED"'
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }
```

### To Reproduce

Upgrade to storybook 7.0.7 and run `storybook build`

### System

```shell
Environment Info:

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
  npmPackages:
    @storybook/addon-actions: ^7.0.6 => 7.0.7 
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/node-logger: ^7.0.7 => 7.0.7 
    @storybook/preset-create-react-app: ^7.0.6 => 7.0.6 
    @storybook/react: ^7.0.5 => 7.0.5 
    @storybook/react-webpack5: ^7.0.4 => 7.0.4
```

**Comment by cbovis** [comment]
Also ran into this. Issue introduced in 7.0.7 and downgrading to 7.0.6 was an effective fix.

**Comment by tmeasday** [comment]
How did y'all upgrade? The issue here is mismatching version of SB packages. Note in the Environment info, there's:

```
    @storybook/addon-actions: ^7.0.6 => 7.0.7 
    @storybook/addon-essentials: ^7.0.7 => 7.0.7 
    @storybook/addon-links: ^7.0.6 => 7.0.6 
    @storybook/node-logger: ^7.0.7 => 7.0.7 
    @storybook/preset-create-react-app: ^7.0.6 => 7.0.6 
    @storybook/react: ^7.0.5 => 7.0.5 
    @storybook/react-webpack5: ^7.0.4 => 7.0.4
```

That's not right, it all needs to be 7.0.7.

**Comment by ndelangen** [comment]
I'm also fairly certain there's a versioning issue occurring here, not a issue with our code @tmeasday 

Here's the code:
https://github.com/storybookjs/storybook/blob/2c8999166b83e426527942dda61087ed050d0d95/code/ui/manager/src/globals/exports.ts#L121

added 1 week ago:
![Screenshot 2023-04-26 at 12 22 46](https://user-images.githubusercontent.com/3070389/234547265-20338386-e218-4da5-bba2-28879fd4d34c.png)

**Comment by tmeasday** [comment]
@craigbehnke did you run `npx sb@latest upgrade`? That's the way to upgrade, anything else is unreliable I think.

**Comment by tmeasday** [comment]
I'm going to close this as I'm fairly sure the above (or similar) is likely the issue in all cases.

**Comment by ackvf** [comment]
I am getting this after upgrading all storybook packages to `7.0.12`.
