### ISSUE TITLE
 Storybook 7.0.7 throws error: Type Component is part of the declaration of 2 modules.

### ISSUE THREAD

**Issue by Geetha2290** [storybookjs/storybook#22282]
### Describe the bug

Storybook 6.5.9 was working fine with Angular 14. I recently upgraded to Angular 15 and it throws below error. 

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@storybook/preview-api' in /node_modules/storybook-addon-angular-router/dist'
    at /node_modules/webpack/lib/Compilation.js:2016:28
    at /node_modules/webpack/lib/NormalModuleFactory.js:798:13
```

So, assuming 6.5.9 is not supported with angular 15, I upgraded storybook to recent version 7.0.7 and it throws below error:

```
 Type UserComponent is part of the declarations of 2 modules: StorybookComponentModule and StorybookComponentModule! Please consider moving UserComponent to a higher module that imports StorybookComponentModule and StorybookComponentModule. You can also create a new NgModule that exports and includes UserComponent then import that NgModule in StorybookComponentModule and StorybookComponentModule.
```

### System

```shell
Enviroment Info:
Node: 16.18.1
npm: 8.19.2
npmPackages:
@storybook/addon-actions: "^7.0.7",
@storybook/addon-essentials: "^7.0.7",
@storybook/addon-links: "^7.0.7",
@storybook/angular: "^7.0.7",
```

**Comment by shilman** [comment]
Has `storybook-addon-angular-router` been upgraded to v7? See https://github.com/storybookjs/storybook/issues/20529 for more info

**Comment by Geetha2290** [comment]
> Has `storybook-addon-angular-router` been upgraded to v7? See #20529 for more info

The above issue `Type ButtonComponent is part of the declarations of 2 modules: StorybookComponentModule and StorybookComponentModule!` is reproducible even without `storybook-addon-angular-router`

**Comment by SuneRadich** [comment]
I just migrated my nx monorepo to the latest, and therefore also from Storybook 6 to 7. I see this error in my existing storybooks. It does not happen the first time you view a story, but if you navigate between two stories. It seems like the old Story views are not correctly "unloaded" ?

**Comment by SuneRadich** [comment]
I have tracked it down to be in stories where I have configured `moduleMetadata`. In many of those stories we have reused the setup between stories like this

```
const getDecorator = (data = defaultData) => {
  return [
    moduleMetadata({
      providers: [
        {
          provide: ApiService,
          useFactory: () => ({
            fetchDocument: noop,
          }),
        },
        provideMockStore({
          initialState: {
            [LIST_FEATURE_KEY]: {
              data: {
                status: 'success',
                meta: [
                    data
                ]
              },
            },
          },
        }),
      ],
    }),
  ];
};
```

These stories cause the error. Stories without this does not.

I guess its related to the changes also mentioned in https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders

Maybe I missed some notification in the migration scripts, but I was not aware of this change. Did the migration somehow miss this?

**Comment by valentinpalkovic** [comment]
@Geetha2290.

I have checked out your example and we have to be a bit more precise here:

After you switch Stories, indeed this kind of error is shown. But if you go to one of the affected Stories and you refresh the page, you get another error: 

![image](https://user-images.githubusercontent.com/5889929/235892271-e53cca2d-3510-4df3-9f10-73bee4a2c55a.png)

And this error makes sense, because the HttpClientModule is imported by using the `moduleMetadata` instead of the `applicationConfig` decorator. Please take a closer look to the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders) to understand, why you need to use the `applicationConfig` decorator in this particular scenario. Essentially, you want to register some providers on the application level, and therefore you have to use the applicationConfig provider as shown in this [PR](https://github.com/Geetha2290/angular-storybook/pull/1) (which fixes the issue).

I am still not sure, why Storybook shows another error when switching stories, but the thrown error "Type X is part of the declarations of 2 modules: StorybookComponentModule and StorybookComponentModule! ..." was just a side-effect and was caused by the fact, that the Providers from "HttpClientModule" where not found.

**Comment by valentinpalkovic** [comment]
@SuneRadich Please provide a minimal reproduction to be able to analyze your special use case. You can create a stackblitz sandbox for this if you want: https://new-storybook.netlify.app/

**Comment by Geetha2290** [comment]
> @Geetha2290.
> 
> I have checked out your example and we have to be a bit more precise here:
> 
> After you switch Stories, indeed this kind of error is shown. But if you go to one of the affected Stories and you refresh the page, you get another error:
> 
> ![image](https://user-images.githubusercontent.com/5889929/235892271-e53cca2d-3510-4df3-9f10-73bee4a2c55a.png)
> 
> And this error makes sense, because the HttpClientModule is imported by using the `moduleMetadata` instead of the `applicationConfig` decorator. Please take a closer look to the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#angular-application-providers-and-modulewithproviders) to understand, why you need to use the `applicationConfig` decorator in this particular scenario. Essentially, you want to register some providers on the application level, and therefore you have to use the applicationConfig provider as shown in this [PR](https://github.com/Geetha2290/angular-storybook/pull/1) (which fixes the issue).
> 
> I am still not sure, why Storybook shows another error when switching stories, but the thrown error "Type X is part of the declarations of 2 modules: StorybookComponentModule and StorybookComponentModule! ..." was just a side-effect and was caused by the fact, that the Providers from "HttpClientModule" where not found.

@valentinpalkovic It works thanks :)

**Comment by shilman** [comment]
Closing this as answered. Please feel free to re-open if you think there's more to do here! 🙏

**Comment by mbjelac** [comment]
For anyone looking into this - as described, the error effectively masks the cause.

However, console output still contains the causes (missing providers, child components, etc.), so check out the developer console.

**Comment by AngularIsAwfull** [comment]
For anyone who had to deal with deprecated RouterTestingModule use this inside storybook meta decorators:
```
applicationConfig({
  providers: [
    provideRouter([
      { path: '', component: YourStoryComponent },
      { path: '**', redirectTo: '' }
    ])
  ],
})
```
