### ISSUE TITLE
[Bug]: 2 or more nested div's in a CSF template result in SyntaxError

### ISSUE THREAD

**Issue by gluecksmensch** [storybookjs/storybook#22307]
### Describe the bug

When using a custom render function for Vue 3 components with `args` provided, 2 or more nested `<div>`'s will result in an syntax error:

```console
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (11:36) (at config.mjs:4:2233)
    at u (config.mjs:4:2233)
    at Zl (config.mjs:36:6398)
    at gs (config.mjs:36:7902)
    at Object.parse (config.mjs:36:8674)
    at getTemplates (config.mjs:37:106)
    at sourceDecorator (config.mjs:43:793)
    at runtime.mjs:7:17015
    at chunk-2GDW2BFM.mjs:1:1411
    at runtime.mjs:7:17791
    at unboundStoryFn (runtime.mjs:34:3333)
g
```

### To Reproduce

Just create a simple story **and** pass the `args` argument:

```js
// won't work
export const divTest = {
  render: (args) => ({
    template: `<div><div>test</div></div>`,
  }),
};

// won't work
export const divTest = {
  render: (args) => ({
    components: { MyButton },
    setup() {
      return { args };
    },
    template: `<my-button v-bind="args"><div><div>test</div></div></my-button>`,
  }),
};

// works
export const divTest = {
  render: () => ({
    template: `<div><div>test</div></div>`,
  }),
};

// works
export const divTest = {
  render: (args) => ({
    template: `<div>test</div>`,
  }),
};

// works
export const divTest = {
  render: (args) => ({
    components: { MyButton },
    setup() {
      return { args };
    },
    template: `<my-button v-bind="args"><div>test</div></my-button>`,
  }),
};
```

### System

```shell
Environment Info:

  System:
    OS: macOS 12.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @storybook/testing-library: 0.1.0 => 0.1.0 
    @storybook/vue3-vite: 7.0.1 => 7.0.1
```

**Comment by shilman** [comment]
closing as dupe to #21424
