### ISSUE TITLE
[Bug]: MDX, MD import throwing missing OverlayScrollbarsComponent import

### ISSUE THREAD

**Issue by SanderWorxs** [storybookjs/storybook#22527]
### Describe the bug

I am using Storybook 7.0.10 with Angular v15. When I attempt to open a Source Doc Block of a story's documentation page generated by autodocs or when I create a custom '.mdx' file containing a Source Block, I get the following error:

`react-dom.production.min.js:189 TypeError: (0 , import_overlayscrollbars.default) is not a function
    at OverlayScrollbars-VAV6LJAB.mjs:9:1
    at Rj (react-dom.production.min.js:244:1)
    at Ik (react-dom.production.min.js:286:1)
    at react-dom.production.min.js:282:1
    at J (scheduler.production.min.js:13:1)
    at MessagePort.R (scheduler.production.min.js:14:1)
Mi @ react-dom.production.min.js:189
Ri.f.componentDidCatch.c.callback @ react-dom.production.min.js:190
ih @ react-dom.production.min.js:144
lk @ react-dom.production.min.js:261
jk @ react-dom.production.min.js:260
ik @ react-dom.production.min.js:259
Xk @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:281
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
Ik @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
`

This issue seems related to [#21987](https://github.com/storybookjs/storybook/issues/21987) but we do not use custom webpack in our solutions.

### To Reproduce

Cannot be reproduced with 'npx sb@next sandbox' sadly

### System

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
  npmPackages:
    @storybook/addon-a11y: ^7.0.10 => 7.0.10
    @storybook/addon-docs: ^7.0.10 => 7.0.10
    @storybook/addon-essentials: 7.0.10 => 7.0.10
    @storybook/addon-interactions: 7.0.10 => 7.0.10
    @storybook/addon-links: 7.0.10 => 7.0.10
    @storybook/angular: 7.0.10 => 7.0.10
    @storybook/blocks: 7.0.10 => 7.0.10
    @storybook/jest: ^0.1.0 => 0.1.0
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/test-runner: ^0.10.0 => 0.10.0
    @storybook/testing-library: 0.1.0 => 0.1.0
```

**Comment by SanderWorxs** [comment]
I have been able to solve the issue in our case. We had some extra scripts  added via the 'scripts' array in the angular.json file which interfered with the overlayScrollbars. In our case the scripts were related to 'SystemJs'. We can work around this issue by not providing the scripts in the array, although it is rather remarkable it can break something like this and is quite an inconvenience.
