### ISSUE TITLE
[Bug]: Why I can not use vite with Storybook Angular, Angular v16 is surport with Vite,thank U!

### ISSUE THREAD

**Issue by yangfan100** [storybookjs/storybook#22544]
### Describe the bug

Why I can not use vite with Storybook Angular, Angular v16 is surport with Vite

**Comment by usrrname** [comment]
Please include a reproduction so folks can understand what you're stuck on!

**Comment by valentinpalkovic** [comment]
This is currently not supported. But we evaluate possible solutions soon.

**Comment by nstuyvesant** [comment]
That would be appreciated. For the monorepo I am working on, there are 5 packages and 5 Storybooks. Out of the 10 items that need to be bundled, only one uses webpack.

**Comment by brandonroberts** [comment]
I maintain [Analog](https://analogjs.org), which has integration for Angular using Vite's build pipeline. I have a working example of Angular with the Storybook Vite Builder.

https://github.com/brandonroberts/analog-angular-storybook-vite

Not sure why yet, but I have to use a different import for the `@storybook/angular` imports. If anyone has any insight there, that would help.

Noted in this commit

https://github.com/brandonroberts/analog-angular-storybook-vite/commit/194c380dc4a1c8fc342a812f460e9422307f3b8d

**Comment by asifaminb** [comment]
> I maintain [Analog](https://analogjs.org), which has integration for Angular using Vite's build pipeline. I have a working example of Angular with the Storybook Vite Builder.
> 
> https://github.com/brandonroberts/analog-angular-storybook-vite
> 
> Not sure why yet, but I have to use a different import for the `@storybook/angular` imports. If anyone has any insight there, that would help.
> 
> Noted in this commit
> 
> [brandonroberts/analog-angular-storybook-vite@194c380](https://github.com/brandonroberts/analog-angular-storybook-vite/commit/194c380dc4a1c8fc342a812f460e9422307f3b8d)

I got an error when I tried to run this project locally, 
![image](https://github.com/storybookjs/storybook/assets/30643973/6f22f00f-fd6d-418a-aa84-4196572914c8)

**Comment by brandonroberts** [comment]
@rvale01 I think the team is still working to integrate the new esbuild based Angular setup with Storybook. I pushed an updated repo with Analog and Angular v16

https://github.com/brandonroberts/analog-angular-storybook-v16

**Comment by pumano** [comment]
would love to use that when support provided

**Comment by brandonroberts** [comment]
> would love to use that when support provided

Yep, they are working towards a solution and will show it at some point

**Comment by byjokese** [comment]
Any expected timeframe for this?

**Comment by VaniaBlanar** [comment]
any update on it?

**Comment by bastiW** [comment]
"We’re also working with the Angular core team to support new high-performance build options in a future version."

https://storybook.js.org/blog/storybook-8/

**Comment by sod** [comment]
You need any help? We use both, storybook8 and angular18/esbuild/vite.

**Comment by VaniaBlanar** [comment]
Eventually, I made it work. Changing the property in angular.json helped.
from "outputPath": { "base": "./dist"} to "outputPath": "./dist",

**Comment by LeoLetourneur** [comment]
For anyone interrested, it's working with Angular 18.2.3 & Storybook 8.3.0.
I made it work thanks to this repo https://github.com/brandonroberts/angular-v17-vite-storybook

I also had some path alias (typescript & scss) working with webpack. So I needed to add this to the .stroybook/main.ts 
```
resolve: {
        alias: {
          '@env': path.resolve(__dirname, '../src/environments/environment'),
          '@features': path.resolve(__dirname, '../src/app/features/'),
          '@shared': path.resolve(__dirname, '../src/app/shared'),
          '@core': path.resolve(__dirname, '../src/app/core'),
          shared: path.resolve(__dirname, '../src/styles/shared.scss'), // <- scss alias @import 'shared'
    },
},
```

**Comment by sinaa** [comment]
@brandonroberts  / @LeoLetourneur did you guys figure out how to sort out CSS post processing? e.g., tailwind.

**Comment by brandonroberts** [comment]
> @brandonroberts / @LeoLetourneur did you guys figure out how to sort out CSS post processing? e.g., tailwind.

What issue are you having? 

Vite has PostCSS support built in https://vitejs.dev/guide/features.html#postcss

**Comment by elirov** [comment]
> For anyone interrested, esbuild/vite are working with Angular 18.2.3 & Storybook 8.3.0. I made it work thanks to this repo https://github.com/brandonroberts/angular-v17-vite-storybook
> 
> ## For serve
> I also had some path alias (typescript & scss) working with webpack. So I needed to add this to the .storybook/main.ts
> 
> ```
> resolve: {
>     alias: {
>           '@env': path.resolve(__dirname, '../src/environments/environment'),
>           '@features': path.resolve(__dirname, '../src/app/features/'),
>           '@shared': path.resolve(__dirname, '../src/app/shared'),
>           '@core': path.resolve(__dirname, '../src/app/core'),
>           shared: path.resolve(__dirname, '../src/styles/shared.scss'), // <- scss alias @import 'shared'
>     },
> },
> ```
> 
> I also had some old internal libraries in CommonJS with errors at runtime like `Module xxx doesn't not provide exported name { XXX } for file://xxx/xxx/xxx`
> 
> Make sure to build libraries in ESM.
> 
> ## For the build (& hosting), I had two more issues :
> **Workers output format at build time** I have web workers in my app. Build failed like :
> 
> `[vite:worker-import-meta-url] Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.`
> 
> You should add to your esbuild config
> 
> ```
> worker: {
>     format: 'esm',
> },
> ```
> 
> **ngDevMode not defined at run time (in storybook frame)**
> 
> `ReferenceError: ngDevMode is not defined`
> 
> You should add to your esbuild config
> 
> ```
> define: {
>     ngDevMode: 'undefined',
> },
> ```

Getting that same ngDevMode undefined error. Where exactly can I add that define: {...} or worker: {...} clauses? what files?

**Comment by brandonroberts** [comment]
@elirov that issue has been resolved in Analog version `1.9.1`.

**Comment by elirov** [comment]
Interesting. I was getting the same error on analog 1.9.1. I had to add the following to my .storybook/main.ts:
  async viteFinal(config: UserConfig) {
    // Merge custom configuration into the default config
    const { mergeConfig } = await import('vite');
    const { default: angular } = await import('@analogjs/vite-plugin-angular');
    const tailwindcss = await import('tailwindcss');
    const autoprefixer = await import('autoprefixer');

    return mergeConfig(config, {
      define: {
        ngDevMode: 'false',
      },

**Comment by brandonroberts** [comment]
Interesting. What version of Storybook/Angular/Analog plugin are you on?

**Comment by elirov** [comment]
"@analogjs/vite-plugin-angular": "^1.9.1",
    "@chromatic-com/storybook": "3.2.2",
    "@storybook/addon-designs": "8.0.4",
    "@storybook/addon-docs": "8.4.1",
    "@storybook/addon-essentials": "8.4.1",
    "@storybook/addon-interactions": "8.4.1",
    "@storybook/addon-links": "8.4.1",
    "@storybook/angular": "8.4.1",
    "@storybook/blocks": "8.4.1",
    "@storybook/builder-vite": "^8.4.1",
    "@storybook/test": "8.4.1",
    "eslint-plugin-storybook": "0.10.2",
    "storybook": "^8.4.1",
    "storybook-addon-angular-router": "1.10.1",
    "storybook-addon-mock": "5.0.0",
    "storybook-addon-mock-date": "^0.6.0",
    "vite": "^5.4.10",
    "vite-tsconfig-paths": "^5.0.1",

**Comment by elirov** [comment]
and here's my storybook main.ts: import { StorybookConfig } from '@storybook/angular';
import { StorybookConfigVite } from '@storybook/builder-vite';
import { resolve } from 'path';
import { UserConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';

const config: StorybookConfig & StorybookConfigVite = {
  // other config, addons, etc.
  stories: ['../src/**/*.stories.ts'],
  //staticDirs: ['../storybook-static'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-mock',
    'storybook-addon-mock-date',
  ],

  framework: {
    name: '@storybook/angular',
    options: {},
  },
  core: {
    builder: '@storybook/builder-vite',
  },
  async viteFinal(config: UserConfig) {
    // Merge custom configuration into the default config
    const { mergeConfig } = await import('vite');
    const { default: angular } = await import('@analogjs/vite-plugin-angular');
    const tailwindcss = await import('tailwindcss');
    const autoprefixer = await import('autoprefixer');

    return mergeConfig(config, {
      define: {
        ngDevMode: 'false',
      },
      // Add dependencies to pre-optimization
      resolve: {
        alias: {
          app: resolve(__dirname, '../src/app'),
          features: resolve(__dirname, '../src/features'),
          shared: resolve(__dirname, '../src/shared'),
          theme: resolve(__dirname, '../src/theme'),
          environments: resolve(__dirname, '../src/environments'),
          licenses: resolve(__dirname, '../src/licenses'),
          '@syncfusion': resolve(__dirname, '../node_modules/@syncfusion'),
        },
      },
      optimizeDeps: {
        include: [
          '@storybook/angular',
          '@storybook/angular/dist/client',
          '@angular/compiler',
          '@storybook/blocks',
          'tslib',
        ],
        exclude: ['@analogjs/vite-plugin-angular'],
      },
      plugins: [
        tsconfigPaths(),
        angular({ jit: true, tsconfig: './.storybook/tsconfig.json' }),
      ],
      css: {
        postcss: {
          plugins: [tailwindcss.default(), autoprefixer.default()],
        },
        preprocessorOptions: {
          scss: {
            includePaths: [
              resolve(__dirname, '../src'),
              resolve(__dirname, '../node_modules'),
              resolve(__dirname, '../node_modules/@syncfusion'),
              resolve(__dirname, '../node_modules/@syncfusion/ej2-base/styles'),
              resolve(
                __dirname,
                '../node_modules/@syncfusion/ej2-icons/styles'
              ),
            ],
          },
        },
      },
    });
  },
};
export default config;

**Comment by elirov** [comment]
I did figure out how to add the ngDevMode: false option to the vite storybook config. But now, I'm getting an error in chromatic:
✖ Failed to extract stories from your Storybook
This is usually a problem with your published Storybook, not with Chromatic.

Build and open your Storybook locally and check the browser console for errors.
Visit your published Storybook at https://64fa03becc73b87df3e86ba7-obvhxqpaxm.chromatic.com/
The following error was encountered while running your Storybook:

Error: Error: page.evaluate: TypeError: Cannot add property verbosity, object is not extensible
    at zi (https://64fa03becc73b87df3e86ba7-obvhxqpaxm.capture-loopback.chromatic.com/assets/DocViewerPanel-BE1RnWcD.js:332:23561)
    at https://64fa03becc73b87df3e86ba7-obvhxqpaxm.capture-loopback.chromatic.com/assets/DocViewerPanel-BE1RnWcD.js:332:23609

**Comment by brandonroberts** [comment]
Yea, `ngDevMode` should be `undefined` when doing a build. I'm seeing the issue here also https://github.com/brandonroberts/angular-v17-vite-storybook with the latest version of the plugin.

We changed the detection of production mode to be based on the vite config mode, but its not being set in the config. Will get a fix in shortly on the plugin side

**Comment by brandonroberts** [comment]
@elirov landed a fix in Analog `1.9.2-beta.2` you can test

**Comment by SeraphCoding** [comment]
> [@elirov](https://github.com/elirov) landed a fix in Analog `1.9.2-beta.2` you can test
```
The requested module '/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/@storybook_angular.js?v=0f388471' does not provide an export named 'applicationConfig'
```
Is all I get after a lot of troubleshooting. The storybook compiles and the example stories work fine - until I open anything relying on Angular.

**Comment by SeraphCoding** [comment]
> [@SeraphCoding](https://github.com/SeraphCoding) if you're importing something from `@storybook/angular` that's not a type, try using `@storybook/angular/dist/client` instead. For some reason, direct imports work incorrectly in an ESM-only setup. We have some checks for this in the angular vite plugin, but it may not catch everything

This compiles, but I end up with numerous issues that did not previously arise using the Webpack builder for Storybook.
Namely, my console is spammed with
```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
```
whenever I hover over any menu item.

There is a massive error in the browser console, when opening documentation page for any story.
```
chunk-LNLQDV5X.js?v=925b8701:521 Warning: validateDOMNesting(...): <pre> cannot appear as a descendant of <p>.
    at pre
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at SyntaxHighlighter (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:916:15)
    at div
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:4356:18
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:4722:26
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:4356:18
    at Provider (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:4471:16)
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:4679:26
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:5282:15
    at UnstyledScroller (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:5402:15)
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at SyntaxHighlighter (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:5465:15)
    at default
    at Suspense
    at SyntaxHighlighter (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-3VGQZPW7.js?v=925b8701:23827:6)
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at Source (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:2362:3)
    at CodeOrSourceMdx (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:8875:3)
    at p
    at div
    at index_modern_default (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:3937:15)
    at Markdown (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:8996:14)
    at DescriptionContainer (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:9062:5)
    at DocsPage (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:9374:20)
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at div
    at http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1315:41
    at DocsPageWrapper (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:2783:3)
    at ThemeProvider (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-BSMZKW2J.js?v=925b8701:1349:13)
    at SourceContainer (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:8572:3)
    at DocsContainer (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:9183:3)
    at Docs (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-UDBVHBLW.js?v=925b8701:9384:3)
    at MDXProvider (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-I3WTTUWZ.js?v=925b8701:25:18)
    at ErrorBoundary (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-PKG4WHJN.js?v=925b8701:77:5)
    at WithCallback (http://localhost:6006/node_modules/.cache/storybook/1c3385a5d25e538d10b518b310c74d3ca2690b6aaffeadccd74da79736171f86/sb-vite/deps/chunk-PKG4WHJN.js?v=925b8701:28:3)
```

However - the biggest issues are
- tailwindcss (version 4) styles are not loaded
- None of the fonts/icon sets are loaded (using fontsource)
- All Angular Material (19) CSS Variables are undefined ![Image](https://github.com/user-attachments/assets/fe3b10d0-7218-40d2-b059-d4c9553bea90)

Albeit tailwindcss 4 didn't even manage to compile when using Webpack (because of https://github.com/storybookjs/storybook/issues/30208 ), every other issue does not happen when using Webpack.

**Comment by brandonroberts** [comment]
@SeraphCoding create and share a GitHub repo showing the issue, and I'll take a look.

**Comment by brandonroberts** [comment]
@SeraphCoding  here's the changes I made to your branch to get Tailwind working with Storybook

https://github.com/brandonroberts/AngularTW4SBVite/commit/89e3a223a4df56892dc3ce8f9eb07942cb5da43d

**Comment by SeraphCoding** [comment]
@brandonroberts 
Thanks a lot!

Adding imports present in "styles" directly as imports to the styles.scss or as imports to the preview.ts if importing them to the styles.scss isn't viable, also helped with missing fonts.

It's very odd, how Angular using esbuild seemingly can't consume the `postcss.config.js`, while storybook fails to consume the `postcss.config.json`, that Angular needs to compile.

I was able to remove the autoprefixer from `postcss.config.js` without issue, as the tailwindcss plugin has autoprefixer built in.

Using the postcss.config.js causes a soft warning which can be solved by using it as an `.mjs` file instead.

**Comment by mimse** [comment]
Hi @brandonroberts I´m trying to get angular vite and storybook to play nice with each other as well.
I have come so fare, that storybook starts, but getting this error

<img width="1711" alt="Image" src="https://github.com/user-attachments/assets/cfc12895-fa19-4a52-a393-2130912d608c" />

This is the branch https://github.com/Energinet-DataHub/greenforce-frontend/tree/chore/use-vite-in-storybook with the relevant changes.

It seems to me like storybook is unable to find nx libraries in the monorepo, but cannot figure out why that is.

I would be grateful if you could give some pointers

With regards 
Morten

**Comment by pumano** [comment]
@mimse looks like you start storybook using old storybook executor, that executor doesn't support vite (and provide no proper errors,  just "silent" errors from internal code) You should update `project.json` with actual data on how to start storybook / build using `nx-commands`. Check details at analogjs Website in vite angular storybook guide.

**Comment by mimse** [comment]
@pumano it worked, thank you so much

**Comment by mimse** [comment]
One more question :-) before we provided style configuration 

Like this

<img width="532" alt="Image" src="https://github.com/user-attachments/assets/80ee94a6-1bf6-46f2-8558-c4143cb427c0" />

Do you know how to do this with storybook cli?

**Comment by brandonroberts** [comment]
@mimse the styles can be imported in the `.storybook/preview.ts` file.

**Comment by mimse** [comment]
Sorry for keep asking, but I´m keep hitting a road block.. and cannot seem to find any documentation or examples to help me out.

In our style.scss that i now imports in the preview.ts file 

<img width="402" alt="Image" src="https://github.com/user-attachments/assets/c2f9a5b8-8927-45ca-9815-37c38c2849d2" />

We have two use statements. Vite cannot figure out how to resolve @energinet-datahub/watt 

I have tried 

`css: {
  preprocessorOptions: {
    scss: {
     includePaths: ['libs/watt/src/lib/styles'],
    },
  },
},`

And

`css: {
  preprocessorOptions: {
    scss: {
     loadPaths: ['libs/watt/src/lib/styles'],
    },
  },
},`

And adding an alias, but nothing is working.

Any thoughts?

**Comment by brandonroberts** [comment]
@mimse try adding the relevant tsconfig plugin

https://analogjs.org/docs/features/testing/vitest#using-typescript-config-path-aliases

**Comment by mimse** [comment]
This worked for me, thank you all, for the points ❤ 

<img width="735" alt="Image" src="https://github.com/user-attachments/assets/998364c0-2413-4b12-90d7-1f5a951a42b8" />

**Comment by brandonroberts** [comment]
Thanks @mimse, we'll get sections added to the docs for style imports and tsconfig paths

**Comment by brandonroberts** [comment]
We've introduced the `@analogjs/storybook-angular` package as an integration for Angular & Vite.

Docs: https://analogjs.org/docs/integrations/storybook

**Comment by sebastien-closs** [comment]
To Storybook team:  
I think there are 2 solutions: integrate AnalogsJs in Storybook per default, as the official solution and support..   or do a native implementation...  please update us on this topic.  Angular is rid from webpack since v16.   :)  
thanks ! Any update would be much appreciated

**Comment by ricovitch** [comment]
Trying to setup storybook in an angular 21 project, I feel like adding bloatware to my project.
Before storybook : 800 npm packages
After storybook setup : 1400 npm packages (almost doubling)
Even with analogjs integration we still end up with a mix of webpack and vite in the dependencies.
That does not feel like proper support of the angular framework to me to be honest and I ended the day by removing everything.
I want to use it, but I can't see how to do it properly.

**Comment by sebastien-closs** [comment]
> Trying to setup storybook in an angular 21 project, I feel like adding bloatware to my project. Before storybook : 800 npm packages After storybook setup : 1400 npm packages (almost doubling) Even with analogjs integration we still end up with a mix of webpack and vite in the dependencies. That does not feel like proper support of the angular framework to me to be honest and I ended the day by removing everything. I want to use it, but I can't see how to do it properly.

I stayed with the default storybook-angular (webpack and no vite). AnalogJs appeared to me ....  just a tricky workaround making a big mess. I started to install and stopped quickly.
But I would like Vite for all the new testing features.

Storybook was simple and easy.. Yet...  more and more complex. Not very happy for the moment.
I have the feeling that Storybook doesn't want to do any effort for Angular...

**Comment by petterhoel** [comment]
Yes, Vite would be awesome!

**Comment by brandonroberts** [comment]
> > Trying to setup storybook in an angular 21 project, I feel like adding bloatware to my project. Before storybook : 800 npm packages After storybook setup : 1400 npm packages (almost doubling) Even with analogjs integration we still end up with a mix of webpack and vite in the dependencies. That does not feel like proper support of the angular framework to me to be honest and I ended the day by removing everything. I want to use it, but I can't see how to do it properly.
> 
> I stayed with the default storybook-angular (webpack and no vite). AnalogJs appeared to me .... just a tricky workaround making a big mess. I started to install and stopped quickly. But I would like Vite for all the new testing features.
> 
> Storybook was simple and easy.. Yet... more and more complex. Not very happy for the moment. I have the feeling that Storybook doesn't want to do any effort for Angular...

The Storybook team has put lots of effort into trying to make Angular work with esbuild before, which is different than switching to Vite natively. I'd be interested to hear the challenges you had switching to the Analog integration.

**Comment by sebastien-closs** [comment]
My Point is:
- I don't want a solution/workaround to add Vite on top of webpack.  I prefer a native Vite **instead** of Webpack. 
The advantage of Vite is to replace Webpack...  not continuing adding more and more things on the top of the Pise-tower. (to make it more and more messy... and falling).
- Webpack is..  history.  Angular-team got rid of it in 2023.

Not wanting to hurt anyone..   Thanks to all for efforts of everyone, though.

**Comment by brandonroberts** [comment]
No offense taken, I agree with you. Having a Vite-native solution with no Webpack dependencies would be great. Just as a bit of context, Analog currently re-uses the `@storybook/angular` package for less duplication and upkeep with Storybook, but it could drop the Webpack dependencies altogether.

**Comment by ricovitch** [comment]
Yes same.
I know everyone puts a lot of efforts (angular team, storybook team, and community maintainers like you @brandonroberts) and I don't want to blame anyone.

I'm just frustrated when I compare the situation today between my motivation to use storybook (because I believe from my experience it brings a lot of value) and the difficulty to setup storybook in an efficient way on top of a recent angular cli project

I think you did a good job Brandon at providing a working solution, and if possible to improve this approach by completely getting rid of webpack based dependencies that would be a great starting point, maybe for storybook/angular maintainers to move forward at some point...

**Comment by shilman** [comment]
Can we close this as dupe to https://github.com/storybookjs/storybook/issues/34012?

AFAIK we've discussed with the Angular core team and:
- `@storybook/angular-vite` is our best attempt at following their recommendations
- We are in the process of releasing `@storybook/angular-vite` as preview and will be looking for user feedback soon
- We plan to make `@storybook/angular-vite` the default once it's reached stability, similar to how `@storybook/nextjs-vite` has become the default for Next.js users

@brandonroberts @valentinpalkovic y'all are leading the charge on this so please correct me if I got any of this wrong, or if there are important nuances that I missed. Thank you so much for making this happen. ❤️
