### ISSUE TITLE
[Bug]: [vite] Internal server error: Missing "#build/app.config.mjs" specifier in "nuxt" package

### ISSUE THREAD

**Issue by Ibochkarev** [storybookjs/storybook#22568]
### Describe the bug

"nuxt": "^3.4.3"

``` shell
❯ yarn storybook
@storybook/cli v7.0.12

WARN Could not resolve addon "@storybook/addon-mdx-gfm", skipping. Is it installed?
info Found existing addon {"name":"@storybook/addon-docs","options":{"configureJSX":true,"babelOptions":{},"sourceLoaderOptions":null,"transcludeMarkdown":true}}, skipping.
info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
info Found existing addon "@storybook/addon-viewport", skipping.
WARN Could not resolve addon "@storybook/addon-mdx-gfm", skipping. Is it installed?
info Found existing addon {"name":"@storybook/addon-docs","options":{"configureJSX":true,"babelOptions":{},"sourceLoaderOptions":null,"transcludeMarkdown":true}}, skipping.
info Found existing addon "@storybook/addon-controls", skipping.
info Found existing addon "@storybook/addon-actions", skipping.
info Found existing addon "@storybook/addon-viewport", skipping.
info => Starting manager..
WARN No story files found for the specified pattern: stories/**/*.stories.@(js|jsx|ts|tsx)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
╭───────────────────────────────────────────────────╮
│                                                   │
│   Storybook 7.0.12 for vue3-vite started          │
│   3.15 s for manager and 728 ms for preview       │
│                                                   │
│    Local:            http://localhost:6006/       │
│    On your network:  http://192.168.1.45:6006/    │
│                                                   │
╰───────────────────────────────────────────────────╯
Missing "#build/app.config.mjs" specifier in "nuxt" package
Missing "#build/nuxt.config.mjs" specifier in "nuxt" package
ENOTDIR: not a directory, open '/Users/ibochkarev/Projects/project/node_modules/nuxt/dist/app/index.d.ts/nuxt'
10:45:24 [vite] Internal server error: Missing "#build/app.config.mjs" specifier in "nuxt" package
  Plugin: vite:import-analysis
  File: /Users/ibochkarev/Projects/project/node_modules/nuxt/dist/app/config.js?v=91a35272
      at e (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:25)
      at n (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:627)
      at f (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:1357)
      at resolveExportsOrImports (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23407:20)
      at resolveSubpathImports (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22944:23)
      at Context.resolveId (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22751:37)
      at Object.resolveId (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42811:46)
      at async TransformContext.resolve (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42539:23)
      at async normalizeUrl (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:40502:34)
      at async file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:40653:47
10:45:25 [vite] Internal server error: Missing "#build/nuxt.config.mjs" specifier in "nuxt" package
  Plugin: vite:import-analysis
  File: /Users/ibochkarev/Projects/project/node_modules/nuxt/dist/app/composables/payload.js?v=91a35272
      at e (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:25)
      at n (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:627)
      at f (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:16649:1357)
      at resolveExportsOrImports (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:23407:20)
      at resolveSubpathImports (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22944:23)
      at Context.resolveId (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:22751:37)
      at Object.resolveId (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42811:46)
      at async TransformContext.resolve (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42539:23)
      at async normalizeUrl (file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:40502:34)
      at async file:///Users/ibochkarev/Projects/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:40653:47
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 3.2.4 - ~/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 107.0
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.12 => 7.0.12 
    @storybook/addon-essentials: ^7.0.12 => 7.0.12 
    @storybook/vue3: ^7.0.12 => 7.0.12 
    @storybook/vue3-vite: ^7.0.12 => 7.0.12
```

**Comment by jay-p-b-7span** [comment]
Facing same issue in Nuxt `3.4.3`

**Comment by vanessayuenn** [comment]
Hi, thanks for reporting this. Do you have a reproduction repo you can share? If not, can you create one from [storybook.new](https://new-storybook.netlify.app/). We prioritize bug reports that have reproduction. Thank you! 🙏
