### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by leegee** [storybookjs/storybook#22573]
### Describe the bug

lee@20230516-12:14:50:/s/src/xxx/packages/client$ node -v; npm -v
v18.4.0
8.19.0

lee@20230516-12:14:50:/s/src/xxx/packages/client$ npx sb init
Need to install the following packages:
  sb@7.0.12
Ok to proceed? (y) y

 storybook init - the simplest way to add a Storybook to your project. 

(node:11420) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 • Detecting project type. ✓
TypeError: Invalid version. Must be a string. Got type "object".
    at new SemVer (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\semver\classes\semver.js:19:13)
    at compare (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\semver\functions\gte.js:2:30)
    at C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:12:6404
    at hasDependency (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:12:3581)
    at detectLanguage (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:12:6333)
    at installStorybook (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:70:2808)
    at async doInitiate (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:79:704)
    at async withTelemetry (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\core-server\dist\index.js:35:3422)
    at async initiate (C:\Users\xxx\AppData\Local\npm-cache\_npx\d28cfb4b54958d89\node_modules\@storybook\cli\dist\generate.js:90:108)

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

lee@20230516-12:16:02:/s/src/xxx/packages/client$ 

### To Reproduce

npx sb init

### System

```shell
npx storybook@latest info
Need to install the following packages:
  storybook@7.0.12
Ok to proceed? (y) y

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 18.4.0 - H:\Program Files\nvm-node-js\node.EXE
    npm: 8.19.0 - H:\Program Files\nvm-node-js\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
```

**Comment by leegee** [comment]
```bash
 npx sb@next init
Need to install the following packages:
  sb@7.0.14
Ok to proceed? (y) y

 storybook init - the simplest way to add a Storybook to your project. 

(node:1840) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 • Detecting project type. ✓
TypeError: Invalid version. Must be a string. Got type "object".
    at new SemVer (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\semver\classes\semver.js:19:13)
    at compare (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\semver\functions\compare.js:3:3)
    at Object.gte (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\semver\functions\gte.js:2:30)
    at C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:12:6408
    at hasDependency (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:12:3585)
    at detectLanguage (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:12:6337)
    at installStorybook (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:79:2809)
    at async doInitiate (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:88:772)
    at async withTelemetry (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\core-server\dist\index.js:35:3620)
    at async initiate (C:\Users\leege\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\generate.js:99:108)
lee@20230523-14:38:39:/s/src/project/packages/client$ 
lee@20230523-14:38:39:/s/src/project/packages/client$
```

**Comment by leegee** [comment]
Looks like Storybook can't install into a 'package' within an NPM monrepo.

**Comment by shilman** [comment]
Possibly fixed by https://github.com/storybookjs/storybook/pull/22642

**Comment by aanti** [comment]
I faced the same issue in a project made on top of create-vite (react). The problem disapeared when I upgraded TypeScript from 4.x.x to 5.x.x
