### ISSUE TITLE
[Bug]: Application breaks after storybook7 migration from 6.2 - chunk loading error - React app

### ISSUE THREAD

**Issue by npovatho** [storybookjs/storybook#22589]
### Describe the bug

I have a storybook configured React components library. After migration to storybook7 facing chunk loading issue[ ~10 components loads fine, post that it gives chunk error and the application exits with a console error in internal node modules
<img width="1025" alt="Screenshot 2023-05-17 at 3 45 04 PM" src="https://github.com/storybookjs/storybook/assets/108645765/992aa6c8-2f1b-4123-afa6-59f0075d06f2">

The below is the console output post that chunk error. As you can see the process exits post the error.
```
`info => Using implicit CSS loaders
info => Using React fast refresh
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
╭──────────────────────────────────────────────────╮
│                                                  │
│   Storybook 7.0.12 for react-webpack5 started    │
│   3.63 s for manager and 1.67 min for preview    │
│                                                  │
│    Local:            http://localhost:9009/      │
│    On your network:  http://192.168.1.6:9009/    │
│                                                  │
╰──────────────────────────────────────────────────╯
node:internal/streams/readable:866
      dests[i].emit('unpipe', this, { hasUnpiped: false });
               ^

TypeError: dests[i].emit is not a function
    at Readable.unpipe (node:internal/streams/readable:866:16)
    at unpipe (/Users/Shared/IBMDocs/node-18/docs-components-react/node_modules/unpipe/index.js:47:12)
    at send (/Users/Shared/IBMDocs/node-18/docs-components-react/node_modules/finalhandler/index.js:311:3)
    at Immediate.<anonymous> (/Users/Shared/IBMDocs/node-18/docs-components-react/node_modules/finalhandler/index.js:133:5)
    at Immediate.<anonymous> (/Users/Shared/IBMDocs/node-18/docs-components-react/node_modules/express/lib/router/index.js:646:15)
    at process.processImmediate (node:internal/timers:478:21)

Node.js v18.15.0
nz@nz MacBook-Pro docs-components-react % 
```

Below is my main.js file which has the webpack configuration as well.

```
const path = require("path");
const remarkGfm = require("remark-gfm");

// Export a function. Accept the base config as the only param.

export default {
  framework: {
    name: "@storybook/react-webpack5",
    options: {
      fastRefresh: true,
      lazyCompilation: false,
      storyStoreV7:false
    },
  },
  features: {
    legacyMdx1: true, //for mdx1 support
  },
  staticDirs: ["../public"],
  stories: [
    "../src/docs/*.stories.@(js|mdx)",
    "../src/components/**/*-story.@(js|mdx)",
    "../src/DataHooks/**/*-story.@(js|mdx)",
  ],
  addons: [
    "@storybook/addon-actions",
    "@storybook/addon-knobs",
    "@storybook/addon-links",
    "@storybook/addon-storysource",
    {
      name: "@storybook/addon-docs",
      options: {
        mdxPluginOptions: {
          mdxCompileOptions: {
            remarkPlugins: [remarkGfm],
          },
        },
      },
    },
    "@storybook/addon-essentials",
    "@storybook/addon-mdx-gfm",
    "@storybook/preview-api",
    "@storybook/manager-api",
  ],
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Make whatever fine-grained changes you need
    config.module.rules.push({
      test: /\.scss$/,
      use: [
        { loader: "style-loader" },
        {
          loader: "css-loader",
          options: {
            url: false,
          },
        },
        // sass to import global scss file for each story
        {
          loader: "sass-loader",
          options: {
            sassOptions: {
              includePaths: ["node_modules"],
            },
          },
        },
      ],
      include: path.resolve(__dirname, "../"),
    });
    config.module.rules.push({
      test: /story\.js$/,
      use: [
        {
          loader: require.resolve("@storybook/source-loader"),
        },
      ],
      enforce: "pre",
    });
    config.module.rules.push({
      test: /\.html$/,
      use: [
        {
          loader: "raw-loader",
          options: {
            esModule: false,
          },
        },
      ],
    });
    /*    config.node = {
      fs: "empty",
    }; */
    // Return the altered config
    return config;
  },
  docs: {
    autodocs: true,
  },
};

```

### System

```shell
react % npx storybook@latest info

Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 99.0.1
    Safari: 16.4
  npmPackages:
    @storybook/addon-docs: ^7.0.12 => 7.0.12 
    @storybook/addon-essentials: ^7.0.12 => 7.0.12 
    @storybook/addon-knobs: ^7.0.2 => 7.0.2 
    @storybook/addon-links: ^7.0.12 => 7.0.12 
    @storybook/addon-mdx-gfm: ^7.0.12 => 7.0.12 
    @storybook/addon-storysource: ^7.0.12 => 7.0.12 
    @storybook/manager-api: ^7.0.12 => 7.0.12 
    @storybook/mdx1-csf: ^1.0.0 => 1.0.0 
    @storybook/preview-api: ^7.0.12 => 7.0.12 
    @storybook/react: ^7.0.12 => 7.0.12 
    @storybook/react-webpack5: ^7.0.12 => 7.0.12 
    @storybook/source-loader: ^7.0.12 => 7.0.12 
    @storybook/storybook-deployer: ^2.8.16 => 2.8.16
```

**Comment by leonardofficial** [comment]
+1

**Comment by npovatho** [comment]
I could get issue resolved at my end by using node fetch instead of axios in my route
`const fetch = require('node-fetch');
// Get the requested document content with preferredLocale
function get(req, res) {

  const newUrl = `https://dev.console.test.cloud.ibm.com/docs-content${req.url}`;
  fetch(newUrl).then(x => {
    x.body.pipe(res)
  })
  }`
  The issue was with how the pipe was done on the axios response. and with fetch, could fix this. Closing the issue.
