### ISSUE TITLE
[Bug]: not working with vite v4.2.x+

### ISSUE THREAD

**Issue by iTonyYo** [storybookjs/storybook#22808]
### Describe the bug

From **v4.2.x+**, the following error is reported. After downgrading to v4.1.4, Storybook works fine.

Installed dependencies for the first time, but the **node_modules/.cache/.vite-storybook** directory was missing, causing the run to fail. 

```shell
info => Starting manager..
WARN No story files found for the specified pattern: src/**/*.mdx
╭───────────────────────────────────────────────────╮                                                                                                                                                                                                11:32:13
│                                                   │
│   Storybook 7.0.18 for react-vite started         │
│   329 ms for manager and 4.74 s for preview       │
│                                                   │
│    Local:            http://localhost:6006/       │
│    On your network:  http://192.168.2.60:6006/    │
│                                                   │
╰───────────────────────────────────────────────────╯
11:32:14 [vite] .env changed, restarting server...                                                                                                                                                                                                   11:32:14
11:32:14 [vite] .env.development changed, restarting server...                                                                                                                                                                                       11:32:14
11:32:14 [vite] .env.production changed, restarting server...                                                                                                                                                                                        11:32:14
11:32:14 [vite] .env.test changed, restarting server...                                                                                                                                                                                              11:32:14
11:32:14 [vite] .env.uat changed, restarting server...                                                                                                                                                                                               11:32:14
11:32:14 [vite] .env.uat.local changed, restarting server...                                                                                                                                                                                         11:32:14
✘ [ERROR] The build was canceled

...

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/channel-postmessage.js

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/client-api.js

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/channel-websocket.js

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/client-logger.js

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/preview-api.js

✘ [ERROR] Could not read from file: /Users/iyowei/rongmai/development/buffett/node_modules/.cache/vite-plugin-externals/@storybook/preview-web.js

...

✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]

    node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^

    at handleRequest (/Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:728:13)
    at handleIncomingPacket (/Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:745:7)
    at Socket.readFromStdout (/Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

  The plugin "JavaScript plugins" was triggered by this import

    node_modules/.pnpm/@storybook+blocks@7.0.17_react-dom@18.2.0_react@18.2.0/node_modules/@storybook/blocks/dist/index.mjs:21:24:
      21 │ import { Channel } from '@storybook/channels';
...
```

Storybook displays the following error message.
```
TypeError: Failed to fetch dynamically imported module: http://localhost:6006/node_modules/.cache/.vite-storybook/deps/@storybook_addon-essentials_outline_preview.js?v=d7d4deae
```

On the second run, the **node_modules/.cache/.vite-storybook** directory was present, resulting in a successful run. However, the browser console will report the following error.

<img width="855" alt="image" src="https://github.com/storybookjs/storybook/assets/5499703/24a4add6-57b8-4467-9e64-04032e59feaf">

**During the running process of Storybook, installing new dependencies or running again after the first failed attempt will directly result in the following error.**
```
10:24:19 [vite] .env changed, restarting server...                                                                  10:24:19
10:24:19 [vite] .env.development changed, restarting server...                                                      10:24:19
10:24:19 [vite] .env.production changed, restarting server...                                                       10:24:19
10:24:19 [vite] .env.test changed, restarting server...                                                             10:24:19
10:24:19 [vite] .env.uat changed, restarting server...                                                              10:24:19
10:24:19 [vite] .env.uat.local changed, restarting server...                                                        10:24:19
file:///Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1_terser@5.17.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:58726
      throw new Error(
      ^

Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (file:///Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1_terser@5.17.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:58726:13)
    at WebSocketServer.handleUpgrade (file:///Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1_terser@5.17.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:58702:10)
    at Server.<anonymous> (file:///Users/iyowei/rongmai/development/buffett/node_modules/.pnpm/vite@4.3.9_@types+node@20.2.5_sass@1.62.1_terser@5.17.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:58927:21)
    at Server.emit (node:events:525:35)
    at onParserExecuteCommon (node:_http_server:772:14)
    at onParserExecute (node:_http_server:686:3)
 ELIFECYCLE  Command failed with exit code 1.
```

### System

```shell
Environment Info:

  Vite: 4.3.9 darwin-arm64 node-v16.19.1

  System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Edge: 114.0.1823.55
    Safari: 16.5
  npmPackages:
    @storybook/addon-actions: ^7.0.22 => 7.0.22
    @storybook/addon-essentials: ^7.0.22 => 7.0.22
    @storybook/addon-interactions: ^7.0.22 => 7.0.22
    @storybook/addon-links: ^7.0.22 => 7.0.22
    @storybook/blocks: ^7.0.22 => 7.0.22
    @storybook/client-api: ^7.0.22 => 7.0.22
    @storybook/jest: ^0.1.0 => 0.1.0
    @storybook/preview-api: ^7.0.22 => 7.0.22
    @storybook/react: ^7.0.22 => 7.0.22
    @storybook/react-vite: ^7.0.22 => 7.0.22
    @storybook/testing-library: 0.1.0 => 0.1.0
  npmGlobalPackages:
    @storybook/cli: 7.0.18
```

**Comment by iTonyYo** [comment]
Why does Storybook read my vite.config.ts in the root directory? Can I make it not read it?

**Comment by johanhenrikssn** [comment]
I have a similar issue where the storybook vite server restarts. In the preview the stories shows a spinner and the runtime logs loops on 
```[vite] server connection lost. polling for restart...
VM7338 client:245 WebSocket connection to 'ws://localhost:6006/' failed:
```

CLI log
```
platform-ui:storybook: │                                                    │
platform-ui:storybook: │   Storybook 7.0.18 for react-vite started          │
platform-ui:storybook: │   138 ms for manager and 2.85 s for preview        │
platform-ui:storybook: │                                                    │
platform-ui:storybook: │    Local:            http://localhost:6006/        │
platform-ui:storybook: │    On your network:  http://192.168.86.40:6006/    │
platform-ui:storybook: │                                                    │
platform-ui:storybook: ╰────────────────────────────────────────────────────╯
platform-ui:storybook: 4:53:52 PM [vite] .env changed, restarting server...
platform-ui:storybook: 4:53:52 PM [vite] .env.development changed, restarting server...
platform-ui:storybook: 4:53:52 PM [vite] .env.staging changed, restarting server...
platform-ui:storybook: 4:53:52 PM [vite] .env.test changed, restarting server...
platform-ui:storybook: 4:53:52 PM [vite] server restarted.
platform-ui:storybook: 4:53:57 PM [vite] ✨ new dependencies optimized: msw-storybook-addon, @tanstack/react-query-devtools
platform-ui:storybook: 4:53:57 PM [vite] ✨ optimized dependencies changed. reloading
platform-ui:storybook: 4:53:57 PM [vite] hmr update /.storybook/ProviderWrapper.tsx
platform-ui:storybook: 4:53:57 PM [vite] hmr update /virtual:/@storybook/builder-vite/vite-app.js
platform-ui:storybook: 4:53:57 PM [vite] hmr update /virtual:/@storybook/builder-vite/vite-app.js
platform-ui:storybook: 4:53:57 PM [vite] hmr update /src/components/DropdownArrowDownIcon.tsx
platform-ui:storybook: 4:53:57 PM [vite] hmr update /.storybook/ProviderWrapper.tsx
platform-ui:storybook: 4:53:57 PM [vite] hmr update /.storybook/ProviderWrapper.tsx
platform-ui:storybook: 4:53:57 PM [vite] hmr update /.storybook/ProviderWrapper.tsx, /src/components/DropdownArrowDownIcon.tsx
platform-ui:storybook: 4:53:57 PM [vite] hmr update /.storybook/ProviderWrapper.tsx
platform-ui:storybook: 4:53:57 PM [vite] .env changed, restarting server...
platform-ui:storybook: 4:53:57 PM [vite] .env.development changed, restarting server...
platform-ui:storybook: 4:53:57 PM [vite] .env.staging changed, restarting server...
platform-ui:storybook: 4:53:57 PM [vite] .env.test changed, restarting server...
platform-ui:storybook: 4:53:58 PM [vite] server restarted.
```

**System** (`npx storybook@latest info`)
```
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/dev/starhive/starhive-client/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.4
```

 **Versions**
```
 "@storybook/addon-essentials": "^7.0.18",
"@storybook/addon-interactions": "^7.0.18",
"@storybook/addon-links": "^7.0.18",
"@storybook/react": "^7.0.18",
"@storybook/react-vite": "^7.0.18",    
"storybook-addon-react-router-v6": "^1.0.1",
"vite": "^4.3.9",
"storybook": "^7.0.18"
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by avoidwebid** [comment]
Same issue here with vite v4.3.9 and storybook v6.5.16. As a workaround, I deleted the .cache folder in node_modules and restarted storybook
`rm -rf node_modules/.cache`

**Comment by stephenhebert** [comment]
I've been seeing this issue for a while.  The workaround is no longer working for me.

**Comment by lritter79** [comment]
> I've been seeing this issue for a while. The workaround is no longer working for me.

Same here unfortunately

**Comment by Digital-Coder** [comment]
downgrading to vite v4.1.4 seems to work as temporal solution

**Comment by cmolenda** [comment]
Anecdotally, I'm seeing the same problem any time a server restart is logged.

```
11:40:15 AM [vite] .env.local changed, restarting server...
11:40:17 AM [vite] server restarted.
```

With `vite@4.1.4`, `yarn storybook` will start the server but no server restarts are logged. If I subsequently change a `.env` file, the server restart is logged and the described problem is present.

With anything higher than `vite@4.1.4`, `yarn storybook` will start the server and immediately log a server restart for every `.env[.mode]` file present in the directory.

E.g. 
```
11:33:14 AM [vite] hmr update /virtual:/@storybook/builder-vite/vite-app.js
11:33:14 AM [vite] .env changed, restarting server...
11:33:14 AM [vite] .env.development changed, restarting server...
11:33:14 AM [vite] .env.local changed, restarting server...
11:33:14 AM [vite] .env.production changed, restarting server...
11:33:14 AM [vite] .env.test changed, restarting server...
11:33:14 AM [vite] .env.test.local changed, restarting server...
```

This will occur only the first time I start the server. Killing it and restarting it will, like `vite@4.1.4`, will not log any restarts and will work until I again make a change to any of the `.env` files, triggering a restart.

**Comment by danielvinter** [comment]
Still occurs with the following versions:
```

  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@esbuild-plugins/node-globals-polyfill": "^0.2.3",
    "@storybook/addon-essentials": "^7.2.2",
    "@storybook/addon-interactions": "^7.2.2",
    "@storybook/addon-links": "^7.2.2",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/addons": "^7.2.2",
    "@storybook/blocks": "^7.2.2",
    "@storybook/react": "^7.2.2",
    "@storybook/react-vite": "^7.2.2",
    "@storybook/testing-library": "^0.2.0",
    "@vitejs/plugin-react": "^4.0.4",
    "concurrently": "^8.2.0",
    "env-cmd": "^10.1.0",
    "eslint": "^8.46.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-plugin-storybook": "^0.6.13",
    "npm-run-all": "^4.1.5",
    "storybook": "^7.2.2",
    "storybook-addon-react-router-v6": "^2.0.2",
    "vite": "^4.4.9",
    "vite-bundle-visualizer": "^0.10.0",
    "vite-plugin-eslint": "^1.8.1"
  },
```

**Comment by IanVS** [comment]
@danielvinter please see https://github.com/storybookjs/storybook/issues/22253#issuecomment-1686663577

**Comment by danielvinter** [comment]
As per #22253 if you're having this issue, try
`npm up fsevents`
