### ISSUE TITLE
[Bug]: ERR! class IssueWebpackError extends webpack_1.default.WebpackError

### ISSUE THREAD

**Issue by dep** [storybookjs/storybook#22901]
### Describe the bug

When trying to build my storybook, I'm getting the following error:

```
info => Cleaning outputDir: /storybook-static/src
info => Loading presets
WARN   Failed to load preset: "/home/runner/work/Box/Box/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js"
ERR! /home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:[13](https://github.com/Foo/Box/actions/runs/5159306116/jobs/9294066744?pr=1676#step:10:14)
ERR! class IssueWebpackError extends webpack_1.default.WebpackError {
ERR!                                                   ^
ERR! 
ERR! TypeError: Class extends value undefined is not a constructor or null
ERR!     at Object.<anonymous> (/home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13:51)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:[14](https://github.com/Foo/Box/actions/runs/5159306116/jobs/9294066744?pr=1676#step:10:15))
ERR!     at Module._compile (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1[15](https://github.com/Foo/Box/actions/runs/5159306116/jobs/9294066744?pr=1676#step:10:16)9:10)
ERR!     at Object.newLoader (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:18)
ERR!  /home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13
ERR! class IssueWebpackError extends webpack_1.default.WebpackError {
ERR!                                                   ^
ERR! 
ERR! TypeError: Class extends value undefined is not a constructor or null
ERR!     at Object.<anonymous> (/home/runner/work/Box/Box/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:13:51)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ERR!     at Module._compile (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2258:26)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ERR!     at Object.newLoader (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/home/runner/work/Box/Box/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
ERR!     at require (node:internal/modules/cjs/helpers:102:[18](https://github.com/Foo/Box/actions/runs/5159306116/jobs/9294066744?pr=1676#step:10:19))
```

and also further down:

```
ERR! TypeError: module2.rules is not iterable
ERR!     at Object.webpack (/Users/dpeck/Foo/Box/node_modules/@storybook/addon-docs/dist/preset.js:100:210)
ERR!     at async starter (/Users/dpeck/Foo/Box/node_modules/@storybook/builder-webpack5/dist/index.js:63:16)
ERR!     at async Module.start (/Users/dpeck/Foo/Box/node_modules/@storybook/builder-webpack5/dist/index.js:128:14)
ERR!     at async storybookDevServer (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:35:7330)
ERR!     at async buildDevStandalone (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:35:3620)
ERR!     at async dev (/Users/dpeck/Foo/Box/node_modules/@storybook/cli/dist/generate.js:430:400)
ERR!     at async Command.<anonymous> (/Users/dpeck/Foo/Box/node_modules/@storybook/cli/dist/generate.js:432:225)
ERR!  TypeError: module2.rules is not iterable
ERR!     at Object.webpack (/Users/dpeck/Foo/Box/node_modules/@storybook/addon-docs/dist/preset.js:100:210)
ERR!     at async starter (/Users/dpeck/Foo/Box/node_modules/@storybook/builder-webpack5/dist/index.js:63:16)
ERR!     at async Module.start (/Users/dpeck/Foo/Box/node_modules/@storybook/builder-webpack5/dist/index.js:128:14)
ERR!     at async storybookDevServer (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:35:7330)
ERR!     at async buildDevStandalone (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/Users/dpeck/Foo/Box/node_modules/@storybook/core-server/dist/index.js:35:3620)
ERR!     at async dev (/Users/dpeck/Foo/Box/node_modules/@storybook/cli/dist/generate.js:430:400)
ERR!     at async Command.<anonymous> (/Users/dpeck/Foo/Box/node_modules/@storybook/cli/dist/generate.js:432:225)
```

### To Reproduce

Here's my dependency tree:

```
"devDependencies": {
  "@storybook/addon-actions": "7.0.18",
  "@storybook/addon-controls": "7.0.18",
  "@storybook/addon-docs": "7.0.18",
  "@storybook/addon-knobs": "7.0.2",
  "@storybook/addon-links": "7.0.18",
  "@storybook/addons": "7.0.18",
  "@storybook/preset-scss": "1.0.3",
  "@storybook/react": "7.0.18",
  "@storybook/theming": "7.0.18",
  "@storybook/react-webpack5": "7.0.18",
  "file-loader": "6.2.0",
  "storybook": "7.0.18",
  "storybook-addon-designs": "6.3.1",
}
```

And my .storybook/main.js:

```
addons: [
  "@storybook/addon-actions",
  "@storybook/addon-docs",
  "@storybook/addon-knobs",
  "@storybook/preset-scss",
],
stories: ["../src/**/*.stories.{mdx,js}"],
features: {
  buildStoriesJson: true,
  storyStoreV7: true,
},
framework: {
  name: "@storybook/react-webpack5",
  options: {},
},
webpackFinal: async (config) => {
  config.module.rules.push(
    {
      test: /\.jst$/,
      use: [
        {
          loader: "underscore-template-loader",
        },
      ],
    },
    {
      test: /\.(gql|graphql)$/,
      exclude: /node_modules/,
      loader: "graphql-tag/loader",
    }
  );

  return config;
},
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 109.0
    Safari: 16.4
```

**Comment by dep** [comment]
An update to this. This is in a monorepository using `lerna` to bootstrap dependencies across several child instances of Storybook. I was able to fix this by setting `nohoist` rules on both `@storybook/react-webpack5` and `storybook`, and including those two dependencies within each app's `package.json` instead of allowing them to inherit those dependencies from other internal `devDependencies`.

**Comment by carlos-pisarello-trinet** [comment]
> An update to this. This is in a monorepository using `lerna` to bootstrap dependencies across several child instances of Storybook. I was able to fix this by setting `nohoist` rules on both `@storybook/react-webpack5` and `storybook`, and including those two dependencies within each app's `package.json` instead of allowing them to inherit those dependencies from other internal `devDependencies`. I also needed to install `file-loader` as a `devDependency` to each app also.

Coming across this exact same issue as well, could you provide more details on how you solved this? specially the `nohoist` rules
