### ISSUE TITLE
[Bug]: context.resolveOf is not a function

### ISSUE THREAD

**Issue by st-pl** [storybookjs/storybook#22935]
### Describe the bug

I automatically migrated to Storybook 7. Now autogenerated Docs page renders with error. Single stories are generated ok. I use mdx.

The error:

`TypeError: context.resolveOf is not a function
    at ArgsTable2 (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:1767:358)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:53423:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:56249:13)
    at beginWork (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:57487:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:42383:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:42432:16)
    at invokeGuardedCallback (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:42494:31)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:62397:7)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:61212:12)
    at workLoopSync (http://localhost:6006/vendors-node_modules_storybook_addon-a11y_dist_preview_mjs-node_modules_storybook_addon-docs_-5747ae.iframe.bundle.js:61140:5)`

### System

```shell
Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 16.4
  npmPackages:
    @storybook/addon-a11y: ^7.0.18 => 7.0.18 
    @storybook/addon-docs: ^7.0.18 => 7.0.18 
    @storybook/addon-essentials: ^7.0.18 => 7.0.18 
    @storybook/addon-mdx-gfm: ^7.0.18 => 7.0.18 
    @storybook/addon-toolbars: ^7.0.18 => 7.0.18 
    @storybook/addons: ^7.0.18 => 7.0.18 
    @storybook/react: ^7.0.18 => 7.0.18 
    @storybook/react-webpack5: ^7.0.18 => 7.0.18
```

**Comment by st-pl** [comment]
It looks like the problem in <ArgsTable of={Aside} /> If I delete it, problem disappears

**Comment by shilman** [comment]
ArgsTable uses React context to get a reference to the story/component it is displaying. It might be a problem with your project settings -- multiple versions of React? Multiple versions of `@storybook/addon-docs`?

Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
