### ISSUE TITLE
[Bug]:After migrating to node18 and building storybook,  importAssertions and importAttributes conflict.

### ISSUE THREAD

**Issue by nagaoka1166** [storybookjs/storybook#23063]
###  issue
I'm having an issue with '@babel/plugin-syntax-import-assertions' and '@babel/plugin-syntax-import-attributes' causing an error in Storybook.

### background 
After migrating from node16 to 18, the storybook stopped launching when performing a yarn storybook.
First, I got  [this](https://github.com/storybookjs/storybook/issues/16555#issuecomment-1426888852) error.
Then I added NODE_OPTIONS=--openssl-legacy-provider before the yarn script and ran yarn storybook again and got the following error message

 
###  Done list
 - Search for importAssertions and importAttributes in node_modules to see if there are any places where they are used together
 - Update babel (@babel/parser, @babel/core) to the latest

Here's the error message I'm receiving:

#### error message
```
$ NODE_OPTIONS=--openssl-legacy-provider start-storybook -p 6006
info @storybook/react v6.5.16
info
info => Loading presets
info => Serving static files from ././public at /
info Addon-docs: using MDX1
info => Using implicit CSS loaders
(node:38971) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use node --trace-deprecation ... to show where the warning was created)
info => Using default Webpack4 setup
12% building 17/23 modules 6 active /Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@storybook/core-client/dist/esm/globals/globals.js
info => Using cached manager
webpack built preview 5c3904f8c75445f5a5a5 in 7873ms
:x_黒太字: ｢wdm｣: Hash: 5c3904f8c75445f5a5a5
Version: webpack 4.46.0
Time: 7873ms
Built at: 2023/06/12 19:07:17
                            Asset       Size        Chunks                          Chunk Names
               0.iframe.bundle.js    289 KiB             0  [emitted]        [big]
           0.iframe.bundle.js.map    339 KiB             0  [emitted] [dev]
               1.iframe.bundle.js   1.04 MiB             1  [emitted]        [big]
           1.iframe.bundle.js.map    942 KiB             1  [emitted] [dev]
               2.iframe.bundle.js    130 KiB             2  [emitted]
           2.iframe.bundle.js.map    128 KiB             2  [emitted] [dev]
               3.iframe.bundle.js    890 KiB             3  [emitted]        [big]
           3.iframe.bundle.js.map    874 KiB             3  [emitted] [dev]
               4.iframe.bundle.js   83.8 KiB             4  [emitted]
           4.iframe.bundle.js.map   85.3 KiB             4  [emitted] [dev]
               5.iframe.bundle.js   15.7 KiB             5  [emitted]
           5.iframe.bundle.js.map   16.6 KiB             5  [emitted] [dev]
               6.iframe.bundle.js    295 KiB             6  [emitted]        [big]
           6.iframe.bundle.js.map    325 KiB             6  [emitted] [dev]
               7.iframe.bundle.js  992 bytes             7  [emitted]
           7.iframe.bundle.js.map  928 bytes             7  [emitted] [dev]
                      iframe.html   12.2 KiB                [emitted]
            main.iframe.bundle.js   12.5 KiB          main  [emitted]               main
        main.iframe.bundle.js.map  243 bytes          main  [emitted] [dev]         main
    runtime~main.iframe.bundle.js   36.3 KiB  runtime~main  [emitted]               runtime~main
runtime~main.iframe.bundle.js.map   37.6 KiB  runtime~main  [emitted] [dev]         runtime~main
    vendors~main.iframe.bundle.js   3.66 MiB  vendors~main  [emitted]        [big]  vendors~main
vendors~main.iframe.bundle.js.map   3.57 MiB  vendors~main  [emitted] [dev]         vendors~main
Entrypoint main [big] = runtime~main.iframe.bundle.js runtime~main.iframe.bundle.js.map vendors~main.iframe.bundle.js vendors~main.iframe.bundle.js.map main.iframe.bundle.js main.iframe.bundle.js.map
[0] multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/storybook-addon-pseudo-states/dist/esm/preset/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js 196 bytes {main} [built]
[./.storybook/preview.js-generated-config-entry.js] 1.4 KiB {main} [built] [failed] [1 error]
[./generated-stories-entry.js] 1.4 KiB {main} [built] [failed] [1 error]
[./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js] 2.84 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js] 2.85 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js] 2.84 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js] 2.84 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js] 2.84 KiB {vendors~main} [built]
[./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js] 2.84 KiB {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/globals.js] 105 bytes {vendors~main} [built]
[./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js] 97 bytes {vendors~main} [built]
[./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js] 2.85 KiB {vendors~main} [built]
[./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js] 2.85 KiB {vendors~main} [built]
[./node_modules/storybook-addon-pseudo-states/dist/esm/preset/preview.js-generated-config-entry.js] 2.86 KiB {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined] (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined 7.67 KiB {vendors~main} [built]
    + 1014 hidden modules
ERROR in ./generated-stories-entry.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot combine importAssertions and importAttributes plugins.
    at validatePlugins (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/parser/lib/index.js:10480:11)
    at getParser (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/parser/lib/index.js:14409:5)
    at parse (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/parser/lib/index.js:14366:22)
    at parser (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/core/lib/transformation/normalize-file.js:64:38)
    at normalizeFile.next (<anonymous>)
    at run (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/gensync/index.js:261:32)
    at /Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/nagaokaryuunotasuku/es-maker-frontend/node_modules/gensync/index.js:223:11)
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/preview.js-generated-config-entry.js ./node_modules/storybook-addon-pseudo-states/dist/esm/preset/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js main[14]
 ```

**Comment by awinograd** [comment]
I ran into this upgrading from v6 to v7. The solution for me was to patch @storybook/next to use `babel-plugin-import-attributes` instead of `babel-plugin-import-assertions`

**Comment by Renmang** [comment]
> I ran into this upgrading from v6 to v7. The solution for me was to patch @storybook/next to use `babel-plugin-import-attributes` instead of `babel-plugin-import-assertions`

Im getting the same error but with storybook 6.4.
Did you just install that plugin and then included in the plugins section of babel config?
I did that and it doesnt work

**Comment by awinograd** [comment]
@Renmang `@storybook/nextjs` adds `babel-plugin-import-assertions` to the build process. If you aren't using `@storybook/nextjs` your root cause is likely different from this issue. My suggestion is to find out where `babel-plugin-import-assertions` is being added

**Comment by Renmang** [comment]
Yes, in this branch im just using the old storybook without frameworks. I updated some packages and ive got this error.
Ill track where this comes from. Thanks!

**Comment by darelover** [comment]
I am also facing this issue when updating from v6.3 to v6.4. The project uses @storybook/react

> I ran into this upgrading from v6 to v7. The solution for me was to patch @storybook/next to use `babel-plugin-import-attributes` instead of `babel-plugin-import-assertions`

@awinograd how would one go about doing this?

**Comment by awinograd** [comment]
@darelover if you use yarn v1 you can try https://github.com/ds300/patch-package. Yarn 2+ has built-in `yarn patch` functionality. I'm not familiar with options for other package managers

**Comment by harel-tussi** [comment]
Any updates on this?

**Comment by byseop** [comment]
I also got this error when updating node version from v16 to v18.

In my case, The dependency packages `@babel/plugin-syntax-import-assertions` and `@babel/plugin-syntax-import-attributes` in `@babel/preset-env@7.23.8` seem to be in conflict.

So I fixed `@babel/preset-env@7.12.11` in yarn.lock. and remove node_modules, next `yarn install`.
After that, the error was fixed.

**Comment by nagaoka1166** [comment]
thank you for answers, solved it !

**Comment by glassdimlygr** [comment]
Here's a related ticket: https://github.com/babel/babel/issues/16754

**Comment by juanmigdr** [comment]
I had this exact same error `Cannot combine importAssertions and importAttributes plugins` and was able to resolve it by adding the following resolution in my package.json:

```
"resolutions": {
    "babel-preset-current-node-syntax": "1.0.0"
},
```

**Comment by bertho-zero** [comment]
Still an issue with `@storybook/nextjs`

https://github.com/storybookjs/storybook/blob/9c2e6241586f432fb59c58cb85962e2b4d563ae7/code/frameworks/nextjs/src/babel/preset.ts#L151
