### ISSUE TITLE
[Bug]: Cannot find module '$SNIP/packages/storybook/package.json'

### ISSUE THREAD

**Issue by ntucker** [storybookjs/storybook#23252]
### Describe the bug

Upgrading from 7.0.23 -> 7.0.24

```bash
ERR! Error: Cannot find module '$SNIP/packages/storybook/package.json'
ERR! Require stack:
ERR! - /home/circleci/project/node_modules/@storybook/telemetry/dist/index.js
ERR! - /home/circleci/project/node_modules/@storybook/cli/dist/generate.js
ERR! - /home/circleci/project/node_modules/@storybook/cli/bin/index.js
ERR! - /home/circleci/project/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
ERR!     at Module._resolveFilename (/home/circleci/project/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getActualPackageJson (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:2095)
ERR!     at getFrameworkInfo (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:5518)
ERR!     at computeStorybookMetadata (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:7772)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async getStorybookMetadata (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:9731)
ERR!     at async extractStorybookMetadata (/home/circleci/project/node_modules/@storybook/core-server/dist/index.js:20:6098)
ERR!     at async Promise.all (index 5)
ERR!  Error: Cannot find module '$SNIP/packages/storybook/package.json'
ERR! Require stack:
ERR! - /home/circleci/project/node_modules/@storybook/telemetry/dist/index.js
ERR! - /home/circleci/project/node_modules/@storybook/cli/dist/generate.js
ERR! - /home/circleci/project/node_modules/@storybook/cli/bin/index.js
ERR! - /home/circleci/project/node_modules/storybook/index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
ERR!     at Module._resolveFilename (/home/circleci/project/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
ERR!     at getActualPackageJson (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:2095)
ERR!     at getFrameworkInfo (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:5518)
ERR!     at computeStorybookMetadata (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:7772)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async getStorybookMetadata (/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js:1:9731)
ERR!     at async extractStorybookMetadata (/home/circleci/project/node_modules/@storybook/core-server/dist/index.js:20:6098)
ERR!     at async Promise.all (index 5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/home/circleci/project/node_modules/@storybook/telemetry/dist/index.js',
ERR!     '/home/circleci/project/node_modules/@storybook/cli/dist/generate.js',
ERR!     '/home/circleci/project/node_modules/@storybook/cli/bin/index.js',
ERR!     '/home/circleci/project/node_modules/storybook/index.js'
ERR!   ]
ERR! }
```

### To Reproduce

https://github.com/ntucker/anansi/pull/2061

### System

```shell
Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 AMD Ryzen 9 7950X 16-Core Processor
  Binaries:
    Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
    Yarn: 3.5.0 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
```

### Additional context

storybook with react and webpack

https://app.circleci.com/pipelines/github/ntucker/anansi/9350/workflows/c40db23e-7d88-4bf1-9f36-103b8bcc2245/jobs/50149

**Comment by yannbf** [comment]
Thank you so so much for this issue report and the reproduction! It should be fixed in the next release, we'll first release the fix in the alpha release here https://github.com/storybookjs/storybook/pull/23262 and shortly after we'll bring to a new patch release like 7.0.25.

Thanks once again!
