### ISSUE TITLE
[Bug]: Using command 'npx storybook@latest upgrade --prerelease' addReact automigration throws an error (Cannot find package '@babel/preset-react')

### ISSUE THREAD

**Issue by AasmundEndresen** [storybookjs/storybook#23320]
### Describe the bug

✔ Do you want to run the 'addReact' migration on your project? … yes
✅ ran addReact migration
⚠️  failed to check fix missing-babelrc
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find package '@babel/preset-react' imported from /home/vagrant/git/ui-library/babel-virtual-resolve-base.js
    at __node_internal_ (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:233:9)
    at new NodeError (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
    at packageResolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
    at moduleResolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:902:20)
    at defaultResolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:985:15)
    at resolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:999:12)
    at resolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/files/import-meta-resolve.js:13:10)
    at tryImportMetaResolve (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/files/plugins.js:137:45)
    at resolveStandardizedNameForImport (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/files/plugins.js:159:19)
    at resolveStandardizedName (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/files/plugins.js:168:12)
    at loadPreset (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/files/plugins.js:56:20)
    at loadPreset.next (<anonymous>)
    at createDescriptor (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-descriptors.js:139:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:291:5)
    at /home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:43:15)
    at Function.all (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-descriptors.js:101:41)
    at createDescriptors.next (<anonymous>)
    at createPresetDescriptors (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-descriptors.js:95:17)
    at createPresetDescriptors.next (<anonymous>)
    at /home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/gensync-utils/functional.js:21:23
    at Generator.next (<anonymous>)
    at mergeChainOpts (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-chain.js:348:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-chain.js:314:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-chain.js:192:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/config-chain.js:109:31)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/partial.js:79:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at /home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@babel/core/lib/config/partial.js:122:25
    at Generator.next (<anonymous>)
    at step (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:269:25)
    at /home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:223:11)
    at /home/vagrant/.npm/_npx/bc7e1e37fcb46ffc/node_modules/gensync/index.js:37:40 {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by valentinpalkovic** [comment]
Closing in favour of https://github.com/storybookjs/storybook/issues/23505
