### ISSUE TITLE
[Bug]: runGetVersions doesn't always return an array causing errors

### ISSUE THREAD

**Issue by malwatkins** [storybookjs/storybook#23619]
### Describe the bug

the code calls `constraint?(await this.runGetVersions(packageName, !0)).reverse()`, however rungetVersions does not always return an array

If there is only 1 version available (e.g. in a company npm registry) this throws the error "(intermediate value).reverse is not a function" (.reverse is a function that exists on arrays)

Workaround:
Add another older version of the packages to the registry so that runGetVersions returns an array with 2 entries

Potential fix:
runGetVersions should return an array with 1 entry

**Comment by valotas** [comment]
We run into the same issue having the following error while trying to resolve the versions of the libraries:
```
 • Adding Storybook support to your "Vue 3" app
  ⠼ Getting the correct version of 10 packages
     (intermediate value).reverse is not a function

     Error: (intermediate value).reverse is not a function
    at NPMProxy.getVersion (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:56:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:54:738
    at async Promise.all (index 7)
    at async baseGenerator (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:76:477)
    at async generator9 (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:105:1002)
    at async installStorybook (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:109:789)
    at async doInitiate (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:114:845)
    at async withTelemetry (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\core-server\dist\index.js:113:3630)
    at async initiate (C:\Users\foo\AppData\Local\npm-cache\_npx\bc7e1e37fcb46ffc\node_modules\@storybook\cli\dist\generate.js:126:250)
```
