### ISSUE TITLE
[Bug]: addon-storyshots 7.2.1 Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by francesc79** [storybookjs/storybook#23720]
### Describe the bug

when use addon-storyshots in a jest tests a receive

TypeError: Class extends value undefined is not a constructor or null

    > 1 | import initStoryshots from '@storybook/addon-storyshots';
        | ^
      2 |
      3 | initStoryshots();

      at Object.<anonymous> (node_modules/path-scurry/src/index.ts:218:35)
      at Object.<anonymous> (node_modules/glob/src/glob.ts:3:1)
      at Object.<anonymous> (node_modules/glob/src/index.ts:10:1)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/integrityTestTemplate.js:8:16)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/index.js:10:49)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:21:31)
      at Object.<anonymous> (test/test.ts:1:1)

in a https://github.com/francesc79/test-sb repository you found a minimal project

### To Reproduce

https://github.com/francesc79/test-sb

npm i && npm t

**Comment by krkaa** [comment]
i have the same problem

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
