### ISSUE TITLE
[Bug]: nx angular build with enabled sourcemaps throws error

### ISSUE THREAD

**Issue by alexciesielski** [storybookjs/storybook#23747]
### Describe the bug

I have only enabled sourcemaps for the production build of our Angular app and upon running `build-storybook` I almost immediately get this error:

```
info => Using default Webpack5 setup
9% setup compilation SourceMapDevToolPlugin/Users/alexciesielski/Documents/app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:151
			throw new TypeError(
			      ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at JavascriptModulesPlugin.getCompilationHooks (/Users/alexciesielski/Documents/app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:151:10)
    at SourceMapDevToolModuleOptionsPlugin.apply (/Users/alexciesielski/Documents/app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/SourceMapDevToolModuleOptionsPlugin.js:50:27)
    at /Users/alexciesielski/Documents/app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/SourceMapDevToolPlugin.js:183:53
    at _next0 (eval at create (/Users/alexciesielski/Documents/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:207:1)
    at Hook.eval [as call] (eval at create (/Users/alexciesielski/Documents/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:286:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/alexciesielski/Documents/app/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/alexciesielski/Documents/app/node_modules/webpack/lib/Compiler.js:1126:26)
    at /Users/alexciesielski/Documents/app/node_modules/webpack/lib/Compiler.js:1170:29
    at _next1 (eval at create (/Users/alexciesielski/Documents/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at eval (eval at create (/Users/alexciesielski/Documents/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:1)

Node.js v18.17.0
```

Disabling the sourcemap generation fixes it.

I tried setting `enableProdMode` to `false` but it doesn't help.

### To Reproduce

1. In the app's `project.json` set `targets.build.configurations.production.sourceMap` to `true`.
2. Run `npm run build-storybook`
3. Observe error

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.188
    Safari: 16.5.1
  npmPackages:
    @storybook/addon-docs: 7.2.1 => 7.2.1
    @storybook/addon-essentials: 7.2.1 => 7.2.1
    @storybook/addon-interactions: 7.2.1 => 7.2.1
    @storybook/angular: 7.2.1 => 7.2.1
    @storybook/core-server: 7.2.1 => 7.2.1
    @storybook/jest: 0.1.0 => 0.1.0
    @storybook/test-runner: 0.11.0 => 0.11.0
    @storybook/testing-library: 0.2.0 => 0.2.0
    @storybook/theming: 7.2.1 => 7.2.1
```

**Comment by alaaahmedmu** [comment]
I am facing the same issue, but when disable `sourceMap` in `angular.json` it resolved.

Anyways to fix this without disabling `sourceMap`?

**Comment by valentinpalkovic** [comment]
I think this issue happens because two different versions of Webpack are in place. Angular defines one, and Storybook represents the other one. Can you clear your lock files or ensure that just one Webpack dependency is installed by settings resolutions/overrides fields for `webpack` in your package.json?

**Comment by shilman** [comment]
Does anybody have a reproduction repo they can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
