### ISSUE TITLE
[Bug]: Failed to run on sveltekit monorepo(pnpm workspace)

### ISSUE THREAD

**Issue by ryoppippi** [storybookjs/storybook#23777]
### Describe the bug

I got error with sveltekit+pnpm monorepo

### To Reproduce

```sh
pnpx create-turbo@latest -e with-svelte turbo
cd turbo/apps/web
pnpx storybook@latest init -y
```

And you got error like

```
> web@0.0.0 storybook /private/tmp/turbo/apps/web
> storybook dev -p 6006 "--quiet"

@storybook/cli v7.2.2

info => Starting manager..
The following Vite config options will be overridden by SvelteKit:
  - base

ERR! Error: We've detected a SvelteKit project using the @storybook/svelte-vite framework, which is not supported in Storybook 7.0
ERR! Please use the @storybook/sveltekit framework instead.
ERR! You can migrate automatically by running
ERR!
ERR! npx storybook@latest automigrate
ERR!
ERR! See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sveltekit-needs-the-storybooksveltekit-framework
ERR!     at handleSvelteKit (/private/tmp/turbo/node_modules/.pnpm/@storybook+svelte-vite@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/svelte-vite/dist/preset.js:1:1635)
ERR!     at async viteFinal (/private/tmp/turbo/node_modules/.pnpm/@storybook+svelte-vite@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/svelte-vite/dist/preset.js:9:2478)
ERR!     at async Object.viteFinal (/private/tmp/turbo/node_modules/.pnpm/@storybook+sveltekit@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/sveltekit/dist/preset.js:1:1319)
ERR!     at async createViteServer (/private/tmp/turbo/node_modules/.pnpm/@storybook+builder-vite@7.2.2_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/builder-vite/dist/index.js:159:10530)
ERR!     at async Module.start (/private/tmp/turbo/node_modules/.pnpm/@storybook+builder-vite@7.2.2_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/builder-vite/dist/index.js:159:12527)
ERR!     at async storybookDevServer (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:113:7873)
ERR!     at async buildDevStandalone (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:128:2872)
ERR!     at async withTelemetry (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:113:3630)
ERR!     at async dev (/private/tmp/turbo/node_modules/.pnpm/@storybook+cli@7.2.2/node_modules/@storybook/cli/dist/generate.js:457:401)
ERR!     at async Command.<anonymous> (/private/tmp/turbo/node_modules/.pnpm/@storybook+cli@7.2.2/node_modules/@storybook/cli/dist/generate.js:459:225)
ERR!  Error: We've detected a SvelteKit project using the @storybook/svelte-vite framework, which is not supported in Storybook 7.0
ERR! Please use the @storybook/sveltekit framework instead.
ERR! You can migrate automatically by running
ERR!
ERR! npx storybook@latest automigrate
ERR!
ERR! See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#sveltekit-needs-the-storybooksveltekit-framework
ERR!     at handleSvelteKit (/private/tmp/turbo/node_modules/.pnpm/@storybook+svelte-vite@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/svelte-vite/dist/preset.js:1:1635)
ERR!     at async viteFinal (/private/tmp/turbo/node_modules/.pnpm/@storybook+svelte-vite@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/svelte-vite/dist/preset.js:9:2478)
ERR!     at async Object.viteFinal (/private/tmp/turbo/node_modules/.pnpm/@storybook+sveltekit@7.2.2_svelte@3.58.0_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/sveltekit/dist/preset.js:1:1319)
ERR!     at async createViteServer (/private/tmp/turbo/node_modules/.pnpm/@storybook+builder-vite@7.2.2_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/builder-vite/dist/index.js:159:10530)
ERR!     at async Module.start (/private/tmp/turbo/node_modules/.pnpm/@storybook+builder-vite@7.2.2_typescript@4.9.5_vite@4.2.1/node_modules/@storybook/builder-vite/dist/index.js:159:12527)
ERR!     at async storybookDevServer (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:113:7873)
ERR!     at async buildDevStandalone (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:128:2872)
ERR!     at async withTelemetry (/private/tmp/turbo/node_modules/.pnpm/@storybook+core-server@7.2.2/node_modules/@storybook/core-server/dist/index.js:113:3630)
ERR!     at async dev (/private/tmp/turbo/node_modules/.pnpm/@storybook+cli@7.2.2/node_modules/@storybook/cli/dist/generate.js:457:401)
ERR!     at async Command.<anonymous> (/private/tmp/turbo/node_modules/.pnpm/@storybook+cli@7.2.2/node_modules/@storybook/cli/dist/generate.js:459:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

✔ Would you like to help improve Storybook by sending anonymous crash reports? … yes
 ELIFECYCLE  Command failed with exit code 1.
```

### System

```shell
pnpm: 8.6.3
node: v18.16.0
```

**Comment by hugotox** [comment]
Got the same issue and can confirm the suggested change worked!

**Comment by jobnbackpack** [comment]
Noticed that this issue probably has to do with the Windows file system, but I'm not sure. I set up a pnpm workspace in my wsl and had no problems, but my co-worker working on Windows got this issue.  Thanks to this issue we have a workaround.

**Comment by ryoppippi** [comment]
@jobnbackpack this happened on my MacBook btw

**Comment by jobnbackpack** [comment]
We just upgraded to Storybook 8 and got the same issue from the migration? Any news on this problem?

**Comment by phillx** [comment]
I've been facing several issues while trying to use Svelte 4+ Vite 5.4 + Storybook 8.3 inside of PNPM monorepo. 
What resolved my issues was removing "getAbsolutePath" for plugins and framework:

```
import type { StorybookConfig } from '@storybook/svelte-vite';


const config: StorybookConfig = {
	stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|ts|svelte)'],
	addons: [
		'@storybook/addon-svelte-csf',
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@chromatic-com/storybook',
		'@storybook/addon-interactions',
		'@storybook/addon-a11y'
	],
	framework: {
		name: '@storybook/svelte-vite',
		options: {}
	},
	docs: {
        autodocs: 'tag'
    }
};
export default config;
```

**Comment by akb5566** [comment]
Same problem happened to me today (2026 Jan 15)

- Windows 11
- Node 22
- pnpm 10.20.0
- turbo repo 2.7.4
- vite 7.1.9
- Svelte 5.39.9
- SvelteKit 2.44
- storybook 10.1.11

As @phillx said, removing the getAbsolutePath() solved the problem. 👏

**Comment by ndelangen** [comment]
Hi,

Thanks for the report, and thanks to everyone who shared workarounds over the years.

**What's going on**

This thread is about preset and framework resolution in **pnpm monorepos** (originally SvelteKit + Turborepo). Storybook's FAQ recommends a `getAbsolutePath()` helper using `require.resolve()` so addons and frameworks resolve correctly when pnpm's strict dependency layout hoists packages differently than npm/yarn:

https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments

That workaround helps in many monorepo setups, but it can also cause problems depending on your Storybook version, framework, and workspace layout. Several reports here (including on Storybook 8 and 10) found that **removing** `getAbsolutePath()` was what fixed their setup instead.

The underlying friction is pnpm's module resolution combined with how Storybook discovers and loads framework presets — not purely an ESM-vs-CJS bug, though the old CJS preset loader made it worse.

**Where we're headed**

Storybook 10's ESM migration ([#31787](https://github.com/storybookjs/storybook/issues/31787)) removed the old CJS preset loader and improved module resolution paths. That likely helps some pnpm monorepo setups, but we know strict hoisting and workspace layouts can still be tricky, and we're not treating this as fully resolved.

We have planned work around **modern preset loading** to address remaining pnpm and monorepo resolution pain more directly. I have not retried every setup from this thread on Storybook 10.5+ at this time.

We're leaving this issue open to track that remaining friction.

**In the meantime**

- Try with and without `getAbsolutePath()` depending on your package manager layout
- See the FAQ link above for pnpm/NX monorepo guidance
- Prefer running Storybook from a local install rather than `pnpx`/`npx` dlx

If you're still hitting preset resolution failures on Storybook 10.5+ with a local install, please comment with your monorepo layout, Storybook version, and `.storybook/main.ts`.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).

**Comment by LeonxLJX** [comment]
I'd like to take this one.

I've read through the report. Before changing anything I'd like to reproduce it against current `main` first — my reasoning is that a fix anchored to the actual observed behavior is much easier to review than one inferred from the report alone, especially if the surrounding code has moved since this was filed.

Plan: reproduce and confirm the root cause, then make the smallest change that addresses it (plus a regression test if the repo has coverage for this area). If the root cause turns out to live somewhere other than where the report points, I'll report back here before forcing a change.

Anything already known about this that I should read first?

(claiming via @LeonxLJX)
