### ISSUE TITLE
[Bug]: Invariant failed, no builder configured!

### ISSUE THREAD

**Issue by jndietz** [storybookjs/storybook#23829]
### Describe the bug

I gutted my old storybookjs 6.x configuration from my project, and ran `npx storybook@latest init`.  I chose Vite as my builder.  When trying to start storybook I get the following error:

```
PS C:\projects\captain-caption> npm run storybook

> caption-captain@1.0.0 storybook
> storybook dev -p 6006

@storybook/cli v7.2.3

WARN   Failed to load preset: "@storybook\\react-vite\\preset"
ERR! Error: Cannot find module 'vite'
ERR! Require stack:
ERR! - C:\projects\captain-caption\node_modules\@storybook\builder-vite\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\react-vite\dist\preset.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\react-vite\preset.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\cli\bin\index.js
ERR! - C:\projects\captain-caption\node_modules\storybook\index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!     at Object.<anonymous> (C:\projects\captain-caption\node_modules\@storybook\builder-vite\dist\index.js:1:6471)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ERR!     at Object.newLoader (C:\projects\captain-caption\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at extensions..js (C:\projects\captain-caption\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
ERR!  Error: Cannot find module 'vite'
ERR! Require stack:
ERR! - C:\projects\captain-caption\node_modules\@storybook\builder-vite\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\react-vite\dist\preset.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\react-vite\preset.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\core-common\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\telemetry\dist\index.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js
ERR! - C:\projects\captain-caption\node_modules\@storybook\cli\bin\index.js
ERR! - C:\projects\captain-caption\node_modules\storybook\index.js
ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!     at Object.<anonymous> (C:\projects\captain-caption\node_modules\@storybook\builder-vite\dist\index.js:1:6471)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
ERR!     at Object.newLoader (C:\projects\captain-caption\node_modules\esbuild-register\dist\node.js:2262:9)
ERR!     at extensions..js (C:\projects\captain-caption\node_modules\esbuild-register\dist\node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\builder-vite\\dist\\index.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\react-vite\\dist\\preset.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\react-vite\\preset.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\core-common\\dist\\index.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\telemetry\\dist\\index.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\cli\\dist\\generate.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\@storybook\\cli\\bin\\index.js',
ERR!     'C:\\projects\\captain-caption\\node_modules\\storybook\\index.js'
ERR!   ]
ERR! }
ERR! Error: Invariant failed: no builder configured!
ERR!     at invariant (C:\projects\captain-caption\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
ERR!     at buildDevStandalone (C:\projects\captain-caption\node_modules\@storybook\core-server\dist\index.js:128:1818)
ERR!     at async withTelemetry (C:\projects\captain-caption\node_modules\@storybook\core-server\dist\index.js:113:3630)
ERR!     at async dev (C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js:457:401)
ERR!     at async Command.<anonymous> (C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js:459:225)
ERR!  Error: Invariant failed: no builder configured!
ERR!     at invariant (C:\projects\captain-caption\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
ERR!     at buildDevStandalone (C:\projects\captain-caption\node_modules\@storybook\core-server\dist\index.js:128:1818)
ERR!     at async withTelemetry (C:\projects\captain-caption\node_modules\@storybook\core-server\dist\index.js:113:3630)
ERR!     at async dev (C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js:457:401)
ERR!     at async Command.<anonymous> (C:\projects\captain-caption\node_modules\@storybook\cli\dist\generate.js:459:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### To Reproduce

`git clone https://github.com/jndietz/caption-captain.git`
`git checkout feature/select-option-value`
`npm install --legacy-peer-deps` 👈 i'm using an old library
`npm run storybook`

### System

```shell
PS C:\projects\captain-caption> npx storybook@latest info 

Environment Info:

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.203)
  npmPackages:
    @storybook/addon-actions: ^7.2.3 => 7.2.3
    @storybook/addon-essentials: ^7.2.3 => 7.2.3
    @storybook/addon-interactions: ^7.2.3 => 7.2.3
    @storybook/addon-links: ^7.2.3 => 7.2.3
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8
    @storybook/blocks: ^7.2.3 => 7.2.3
    @storybook/builder-vite: ^7.2.3 => 7.2.3
    @storybook/react: ^7.2.3 => 7.2.3
    @storybook/react-vite: ^7.2.3 => 7.2.3
    @storybook/testing-library: ^0.0.13 => 0.0.13
```
```


### Additional context

_No response_

**Comment by stilt0n** [comment]
This is happening because you don't have Vite installed. Vite is listed as a peer dependency for `@storybook/react-vite` but the `--legacy-peer-deps` flag will prevent npm from installing it automatically. Installing Vite yourself (probably as a dev dependency) should solve the issue.

I was able to clone your repo and get storybook running by installing Vite (also needed to change `.storybook/preview.js` to `.storybook/preview.jsx`).

**Comment by jndietz** [comment]
That did it - thanks for looking at that for me.  I swear I installed vite but clearly did not.
