### ISSUE TITLE
[Bug]: after 7.2.3 upgrade, initial click on any story renders blank page at first - Ctrl-R works for that component - Angular

### ISSUE THREAD

**Issue by elirov** [storybookjs/storybook#23845]
### Describe the bug

After upgrading from 7.2.2 to 7.2.3 (and 7.3.0), then initial click from one story to another always renders a blank page, and I need to click Control-R to get the new story to render.

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v20.5.0/bin/npm
  Browsers:
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-designs: 7.0.4 => 7.0.4 
    @storybook/addon-docs: 7.3.0 => 7.3.0 
    @storybook/addon-essentials: 7.3.0 => 7.3.0 
    @storybook/addon-interactions: 7.3.0 => 7.3.0 
    @storybook/addon-links: 7.3.0 => 7.3.0 
    @storybook/angular: 7.3.0 => 7.3.0 
    @storybook/blocks: 7.3.0 => 7.3.0 
    @storybook/jest: 0.1.0 => 0.1.0 
    @storybook/testing-library: 0.2.0 => 0.2.0
```

**Comment by elirov** [comment]
As I'm stripping down our repo, trying to create a sample - I noticed that when I removed the SyncFusion "registerLicense" call in preview.ts, everything seemed to go back to normal.

**Comment by elirov** [comment]
I've narrowed it down to mockData. When I have any mockData at all in any stories, I get the browser blanking behavior. Removing all the mockdata or removing the mock add-on immediately fixes the issue. I'll upload a demo repo in a bit.

**Comment by elirov** [comment]
OK. Here's the public repo that shows the issue: https://github.com/eSpoc/sb-broken-refresh

**Comment by elirov** [comment]
in .storybook/main.ts if you comment out the mock addon, then everything will work smoothly. if it's in, then clicking around in storybook quickly blanks the entire page.

**Comment by elirov** [comment]
also I am getting a browser error that seems to mention some mock-addon properties: Uncaught TypeError: Cannot read properties of undefined (reading 'disableUsingOriginal')
    at wu (index.js:42:42)
    at renderWithHooks (chunk-SJD7EFYL.js:69:936)
    at updateFunctionComponent (chunk-SJD7EFYL.js:69:48263)
    at beginWork (chunk-SJD7EFYL.js:71:21338)
    at HTMLUnknownElement.callCallback2 (chunk-SJD7EFYL.js:2:1918)
    at Object.invokeGuardedCallbackDev (chunk-SJD7EFYL.js:2:2442)
    at invokeGuardedCallback (chunk-SJD7EFYL.js:2:3700)
    at beginWork$1 (chunk-SJD7EFYL.js:90:39484)
    at performUnitOfWork (chunk-SJD7EFYL.js:90:21018)
    at workLoopSync (chunk-SJD7EFYL.js:90:20642)
wu @ index.js:42
renderWithHooks @ chunk-SJD7EFYL.js:69
updateFunctionComponent @ chunk-SJD7EFYL.js:69
beginWork @ chunk-SJD7EFYL.js:71
callCallback2 @ chunk-SJD7EFYL.js:2
invokeGuardedCallbackDev @ chunk-SJD7EFYL.js:2
invokeGuardedCallback @ chunk-SJD7EFYL.js:2
beginWork$1 @ chunk-SJD7EFYL.js:90
performUnitOfWork @ chunk-SJD7EFYL.js:90
workLoopSync @ chunk-SJD7EFYL.js:90
performSyncWorkOnRoot @ chunk-SJD7EFYL.js:90
(anonymous) @ chunk-SJD7EFYL.js:9
unstable_runWithPriority @ chunk-SJD7EFYL.js:1
runWithPriority$1 @ chunk-SJD7EFYL.js:9
flushSyncCallbackQueueImpl @ chunk-SJD7EFYL.js:9
flushSyncCallbackQueue @ chunk-SJD7EFYL.js:9
discreteUpdates$1 @ chunk-SJD7EFYL.js:90
discreteUpdates @ chunk-SJD7EFYL.js:2
dispatchDiscreteEvent @ chunk-SJD7EFYL.js:8

**Comment by elirov** [comment]
after more testing, it looks like everything works fine when I downgrade the storybook-addon-mock plugin to 4.1.0.
I'll close this issue here and open one there..
