### ISSUE TITLE
[Bug]: I cannot name stories `stories.tsx`

### ISSUE THREAD

**Issue by MoSattler** [storybookjs/storybook#23923]
### Describe the bug

When naming stories like this: `stories.tsx`, I get this error:
```
 Error: Invariant failed: No matching indexer found for /Users/user/server/app/components/Link/stories.tsx
    at invariant (/Users/user/server/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at StoryIndexGenerator.extractStories (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:4143)
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2601
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2058
    at Array.map (<anonymous>)
    at /Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1965
    at Array.map (<anonymous>)
    at StoryIndexGenerator.updateExtracted (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1718)
    at StoryIndexGenerator.ensureExtracted (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:2517)
    at StoryIndexGenerator.initialize (/Users/user/server/node_modules/@storybook/core-server/dist/index.js:60:1622)
```

This on the other hand works:
```
Something.stories.tsx
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.2
  npmPackages:
    @storybook/addon-essentials: 7.3.2 => 7.3.2 
    @storybook/addon-interactions: 7.3.2 => 7.3.2 
    @storybook/addon-links: 7.3.2 => 7.3.2 
    @storybook/addon-onboarding: 1.0.8 => 1.0.8 
    @storybook/addon-styling: 1.3.6 => 1.3.6 
    @storybook/blocks: 7.3.2 => 7.3.2 
    @storybook/react: 7.3.2 => 7.3.2 
    @storybook/react-vite: 7.3.2 => 7.3.2 
    @storybook/testing-library: 0.2.0 => 0.2.0
```

### Additional context

main.ts file:

```ts
import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
  stories: [
    "../app/components/**/stories.tsx",
    "../app/components/**/*.stories.@(ts|tsx)",
    "../app/utils/styles/**/*.stories.@(ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
    {
      name: "@storybook/addon-styling",
      options: {},
    },
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  docs: {
    autodocs: "tag",
  },
};
export default config;
```

**Comment by sudiptosen** [comment]
For now I reverted back to my v7.0.26 to get it working.

**Comment by tommiv** [comment]
I have the same issue with plain .ts stories (without TSX), even with minimal ones like below. It works well with SB v7.2.1, without any other changes in a build config (actually without any changes whatsoever)

```ts
import Component from './component.vue';

export default {
    title: 'Some/Path',
    component: Component,
};

export const Default = {
    args: {
        id: 1,
        title: 'Title',
    },
};
```
