### ISSUE TITLE
[Bug]: Throw compile error using tsconfig multiple extend

### ISSUE THREAD

**Issue by anneau** [storybookjs/storybook#24010]
### Describe the bug

TypeScript5.0 provides the ability to extend from multiple configs at once.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends

But Storybook throw error on using this.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1175:7)
    at loadTsconfig (./node_modules/esbuild-register/dist/node.js:4232:37)
    at loadSyncDefault (./node_modules/esbuild-register/dist/node.js:4178:18)
    at tsConfigLoader (./node_modules/esbuild-register/dist/node.js:4165:22)
    at configLoader (./node_modules/esbuild-register/dist/node.js:4493:22)
    at loadConfig2 (./node_modules/esbuild-register/dist/node.js:4476:12)
    at registerTsconfigPaths (./node_modules/esbuild-register/dist/node.js:4752:67)
    at register (./node_modules/esbuild-register/dist/node.js:4884:35)
    at interopRequireDefault (./node_modules/@storybook/core-common/dist/index.js:32:3142)
    at serverRequire (./node_modules/@storybook/core-common/dist/index.js:37:373)
    at loadMainConfig (./node_modules/@storybook/core-common/dist/index.js:50:6889)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:116:1244)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:101:4155)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:502:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:504:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### To Reproduce

https://stackblitz.com/edit/github-jrbz2p?file=tsconfig.json

### System

```bash
Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/addon-interactions: ^7.4.0 => 7.4.0 
    @storybook/addon-links: ^7.4.0 => 7.4.0 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.4.0 => 7.4.0 
    @storybook/nextjs: ^7.4.0 => 7.4.0 
    @storybook/react: ^7.4.0 => 7.4.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by anneau** [comment]
I have confirmed that this issue is caused by an esbuild problem.

https://github.com/evanw/esbuild/issues/3019

**Comment by anneau** [comment]
same as https://github.com/storybookjs/storybook/issues/21792#issuecomment-1533356647
close this.
