### ISSUE TITLE
[Bug]: import { composeStories } from "@storybook/react" in a playwright environment creates TypeError

### ISSUE THREAD

**Issue by cassus** [storybookjs/storybook#24056]
### Describe the bug

I use composeStories in my playwright component tests and it worked fine before the upgrade.

As `composeStories` moved from an addon to the core the import changed to `import { composeStories } from "@storybook/react"`.

Now when I have the import `import { composeStories } from "@storybook/react"` in the playwright test I get a TypeError 
```
at getSelectionSpecifierFromPath (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/preview-api/dist/index.js:66:1115)
```

at the expression
```let query=import_qs2.default.parse(document.location.search, [...]```

It would be great if I could continue to use composeStories from a playwright environment (that has no local DOM api in globals)

### To Reproduce

Repo: https://github.com/cassus/repro-nextjs-storybook-playwright-import-error

It's based on `create-next-app`, `sb init` and `npm init playwright@latest --yes -- --quiet --browser=chromium`

### Setup and test

```sh
yarn install
yarn playwright test
```

### My result

```
yarn run v1.22.19
TypeError: Cannot read properties of undefined (reading 'location')

   at example.spec.ts:6

  4 | // triggers the playwright error: Cannot read properties of undefined (reading 'location')
  5 | // if the following two lines are commented out the tests run fine
> 6 | import { composeStories } from "@storybook/react";
    | ^
  7 | const {Primary} = composeStories(ButtonStories);
  8 |
  9 |

    at getSelectionSpecifierFromPath (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/preview-api/dist/index.js:66:1115)
    at UrlStore (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/preview-api/dist/index.js:66:1627)
    at PreviewWeb (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/preview-api/dist/index.js:69:1158)
    at start (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/preview-api/dist/index.js:90:2130)
    at Object.<anonymous> (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/node_modules/@storybook/react/dist/index.js:1:3007)
    at Object.<anonymous> (/Users/cassus/Dev/repro-nextjs-storybook-playwright-import-error/tests/example.spec.ts:6:1)

Error: No tests found
```

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.4.0 => 7.4.0 
    @storybook/addon-interactions: ^7.4.0 => 7.4.0 
    @storybook/addon-links: ^7.4.0 => 7.4.0 
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
    @storybook/blocks: ^7.4.0 => 7.4.0 
    @storybook/nextjs: ^7.4.0 => 7.4.0 
    @storybook/react: ^7.4.0 => 7.4.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

Importing from `@storybook/preview-api` seems not to trigger a TypeError
```ts
import { composeStories } from "@storybook/preview-api"
```

**Comment by EvgenyWaveBL** [comment]
I just switched to experimental playwright component testing and got just exactly the same

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease:

```
npx storybook@next upgrade --prerelease
```

Does that fix it?

**Comment by yannbf** [comment]
Hey everyone, I'm closing this as the issue has been fixed in the latest version of Storybook (both in 7 and 8)!
