### ISSUE TITLE
[Bug]: Support for defaultProps will be removed from function components in a future major release.

### ISSUE THREAD

**Issue by ecoms-ye** [storybookjs/storybook#24305]
### Describe the bug

Some built-in components like `<Stories>` and `<Link2>` would trigger this console error from react:

```
Warning: Stories: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Stories (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:493:1011)
    at DocsPage (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:493:1730)
    at div
    at http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:1527:2994
    at div
    at http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:1527:2994
    at DocsPageWrapper (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:413:10296)
    at ThemeProvider (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:1527:3996)
    at SourceContainer (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:434:1566)
    at DocsContainer (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:491:6335)
    at Docs (http://localhost:6006/vendors-node_modules_pnpm_storybook_blocks_7_4_5__types_react-dom_18_2_7__types_react_18_2_22-0a8250.iframe.bundle.js:493:2565)
    at MDXProvider (http://localhost:6006/node_modules_pnpm_mdx-js_react_2_3_0_react_18_2_0_node_modules_mdx-js_react_index_js.iframe.bundle.js:127:23)
    at ErrorBoundary (http://localhost:6006/node_modules_pnpm_storybook_addon-docs_7_4_5__types_react-dom_18_2_7__types_react_18_2_22_rea-e406c9.iframe.bundle.js:40:300)
    at WithCallback (http://localhost:6006/vendors-node_modules_pnpm_babel_runtime_7_22_15_node_modules_babel_runtime_helpers_esm_extend-a21569.iframe.bundle.js:2740:34)
```

### To Reproduce

Creat a autodoc page with multiple stories (`<Stories>`) or a component without args (`<Link2>`)

<img width="1038" alt="image" src="https://github.com/storybookjs/storybook/assets/117143128/42b73ffa-fc0b-4a77-86a9-a1c36594e7b2">

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
  Binaries:
    Node: 18.18.0
    pnpm: 8.7.6
  Browsers:
    Chrome: 117.0.5938.62
  npmPackages:
    @storybook/addon-essentials: 7.4.5 => 7.4.5
    @storybook/addon-interactions: 7.4.5 => 7.4.5
    @storybook/addon-links: 7.4.5 => 7.4.5
    @storybook/blocks: 7.4.5 => 7.4.5
    @storybook/nextjs: 7.4.5 => 7.4.5
    @storybook/react: 7.4.5 => 7.4.5
    @storybook/testing-library: 0.2.1 => 0.2.1
```

### Additional context

It seems didn't see this error massage last week

**Comment by ananddoesembed** [comment]
Any update?

**Comment by fabpico** [comment]
Reopen, Link2 error still happens in Storybook `7.6.7`. In the linked merge https://github.com/storybookjs/storybook/pull/24506, just Stories.tsx was addressed.
