### ISSUE TITLE
[Bug]: Minified React error #321

### ISSUE THREAD

**Issue by symphony2014** [storybookjs/storybook#24321]
### Describe the bug

I am trying to upgrade the storybook by : **npx storybook@latest upgrade** , and then run **ng run plot3d:storybook**
the error was thrown:
![image](https://github.com/storybookjs/storybook/assets/6380601/88a436f5-373a-4330-ac7c-0e1fca8fc36f)
```
Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Q (http://localhost:6006/vendors-node_modules_storybook_addon-docs_dist_chunk-S4VUQJ4A_mjs.iframe.bundle.js:34898:9)
    at exports.useContext (http://localhost:6006/vendors-node_modules_storybook_addon-docs_dist_chunk-S4VUQJ4A_mjs.iframe.bundle.js:39871:20)
    at useMDXComponents (http://localhost:6006/vendors-node_modules_mdx-js_react_lib_index_js-node_modules_storybook_addon-docs_dist_index_m-b2769b.iframe.bundle.js:86:64)
    at Object.Template (http://localhost:6006/tool-tool-stories-mdx.iframe.bundle.js:179:165)
    at undecoratedStoryFn (http://localhost:6006/sb-preview/runtime.js:41:2791)
    at hookified (http://localhost:6006/sb-preview/runtime.js:7:18973)
    at http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-docs_-609119.iframe.bundle.js:85947:29
    at http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-docs_-609119.iframe.bundle.js:85942:14
    at cleanArgsDecorator (http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-docs_-609119.iframe.bundle.js:85996:10)
    at http://localhost:6006/vendors-node_modules_storybook_addon-docs_angular_index_js-node_modules_storybook_addon-docs_-609119.iframe.bundle.js:85941:28
```
here is my code:
![image](https://github.com/storybookjs/storybook/assets/6380601/70117e30-5a8c-4d03-958b-9b303d4df857)

I am trying to debug this issue, just found two react-dom versions were applied.  when the  debug tool is inspected version is:
react-dom 16.14.0, and my installed version is react-dom 18.2.0

![image](https://github.com/storybookjs/storybook/assets/6380601/ab235355-af2f-47b3-866e-311e1c843906)
 
![image](https://github.com/storybookjs/storybook/assets/6380601/fd3cf2b5-c51f-4f5a-9697-c4b4743d5f3a)

**Comment by petterhoel** [comment]
Same here with standalone angular (v17-lts) app after  upgrading storybook from 8.2.9 to 8.3.0

**Comment by liquidg3** [comment]
Just hit for me too. `"storybook": "^8.3.0"`

**Comment by RemiKalbe** [comment]
Same with turborepo + nextjs

**Comment by shilman** [comment]
If you're hitting this error, please try
1. upgrading `@chromatic-com/storybook` to the `latest` release
2. restarting your storybook

**Comment by KateCakeLife** [comment]
> Same with turborepo + nextjs与 turborepo + nextjs 相同

I meet the same question. How do u solve this

**Comment by KateCakeLife** [comment]
> Same with turborepo + nextjs与 turborepo + nextjs 相同

i meet the same question, how do u solve it?
