### ISSUE TITLE
[Bug]: CORS issue with Storybook composer and hostname

### ISSUE THREAD

**Issue by bitttttten** [storybookjs/storybook#24329]
### Describe the bug

I'm using the Storybook composer to load in other Storybooks, these Storybooks also have a custom hostname. When running the composer I hit the following issue:

```sh
Uncaught TypeError: Cannot read properties of null (reading 'storyId')
    at chunk-45GKKSU6.js:398:54577
    at Array.map (<anonymous>)
    at chunk-45GKKSU6.js:398:54428
    at renderWithHooks (chunk-NBCGHFLK.js:69:936)
    at updateFunctionComponent (chunk-NBCGHFLK.js:69:48263)
    at updateSimpleMemoComponent (chunk-NBCGHFLK.js:69:46640)
    at updateMemoComponent (chunk-NBCGHFLK.js:69:44544)
    # ....

Access to fetch at 'https://web.bitttttten.com:7007/index.json' from origin 'https://web.bitttttten.com:7006' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
:7007/stories.json:1
```

The composer is run with `storybook dev -p 6006 -h 'web.bitttttten.com'`, and there is a proxy that proxies 7006 to 6006 so you're able to have storybook running locally on 6006, and with SSL at https://web.bitttttten.com:7006.

The storybook is run with `storybook dev -p 6007 -h 'web.bitttttten.com'`.

**Comment by Yasir761** [comment]
@bitttttten , can you assign this to me  under hacktoberfest tag.
