### ISSUE TITLE
[Bug]: `mainConfigMatches is not iterable` error after upgrading to `7.4.6` from `6.5.13`

### ISSUE THREAD

**Issue by dimitur2204** [storybookjs/storybook#24374]
### Describe the bug

After running `npx storybook@latest upgrade`, applying all automigrations (excluding eslint) and fixing all typing errors. I am getting the following error:
```
TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (./node_modules/@storybook/core-common/dist/index.js:6:1094)
    at async loadMainConfig (./node_modules/@storybook/core-common/dist/index.js:19:6698)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:116:1244)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:101:4155)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:473:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:475:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (/Users/dimitar.nizamov/dev/uniwise/flow-ui-react/node_modules/@storybook/core-common/dist/index.js:6:1094)
```

It seems like this is the line that breaks in that case:
https://github.com/storybookjs/storybook/blob/109eb206966452fbc5c2fff683939277f1b0ead3/code/lib/core-common/src/utils/validate-configuration-files.ts#L13

### To Reproduce

I did not find a way to initialize a project on a lower version using the sandbox utility.

### System

```bash
Environment Info:

  System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.132
    Safari: 17.0
  npmPackages:
    @storybook/addon-actions: 7.4.6 => 7.4.6 
    @storybook/addon-essentials: 7.4.6 => 7.4.6 
    @storybook/addon-knobs: 7.0.2 => 7.0.2 
    @storybook/addon-links: 7.4.6 => 7.4.6 
    @storybook/addons: 7.4.6 => 7.4.6 
    @storybook/api: 7.4.6 => 7.4.6 
    @storybook/components: 7.4.6 => 7.4.6 
    @storybook/react: 7.4.6 => 7.4.6 
    @storybook/react-webpack5: 7.4.6 => 7.4.
```

### Additional context

I have tried multiple versions of node (15, 16, 17, 19) - all throw the same error. I have tested on an Intel Based Macbook pro and

**Comment by dimitur2204** [comment]
The bug was coing from a resolution of `glob` in my `package.json`
```
"resolutions": {
    "glob": "^7.1",
    "glob-parent": "6.0.2",
    "trim-newlines": "4.0.2",
    "trim": "1.0.1",
    "@types/react": "16.9.49"
  }
```
This `glob` version is probably old and does not have the same API.
