### ISSUE TITLE
[Bug]: mainConfigMatches is not iterable error for `storybook` >= `7.4.3`

### ISSUE THREAD

**Issue by nicolasvienot** [storybookjs/storybook#24520]
### Describe the bug

I tried to upgrade `storybook` from the version `7.4.0` to the current latest one `7.5.1` as well as all add-ons & dependencies. I'm using the `@storybook/react-webpack5` framework in a React (CRA) app with React 17.

I now have the following error when launching `storybook dev -p 6006`
```bash
yarn run v1.22.19
$ storybook dev -p 6006
@storybook/cli v7.5.1

TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (./node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:6:1094)
    at async loadMainConfig (./node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:19:6698)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:119:1244)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:103:3903)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:473:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:475:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

/Users/.../node_modules/@storybook/cli/bin/index.js:23
  throw error;
  ^

TypeError: mainConfigMatches is not iterable
    at validateConfigurationFiles (/Users/.../node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js:6:1094)

Node.js v18.17.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have tried other versions and it seems to be happening with `storybook` >= `7.4.3`.

Here are my dependencies in my `package.json`:
```js
  "devDependencies": {
    ..., // removed for readability
    "@storybook/addon-actions": "^7.5.1",
    "@storybook/addon-essentials": "^7.5.1",
    "@storybook/addon-interactions": "^7.5.1",
    "@storybook/addon-links": "^7.5.1",
    "@storybook/node-logger": "^7.5.1",
    "@storybook/preset-create-react-app": "^7.5.1",
    "@storybook/react": "^7.5.1",
    "@storybook/react-webpack5": "^7.5.1",
    "@storybook/testing-library": "^0.2.2",
    "storybook": "^7.5.1",
    "storybook-addon-mock": "^4.3.0",
  }
```

I found [a similar issue](https://github.com/storybookjs/storybook/issues/24374) in the closed issues, but I don't have any `resolutions`.

Any idea on how to fix this?
Thanks.

### To Reproduce

I could not reproduce with `storybook.new` as the base sandbox for TS+CRA is not working. I can try to reproduce in a specific repository.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn <----- active
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.4
  npmPackages:
    @storybook/addon-actions: ^7.5.1 => 7.5.1 
    @storybook/addon-essentials: ^7.5.1 => 7.5.1 
    @storybook/addon-interactions: ^7.5.1 => 7.5.1 
    @storybook/addon-links: ^7.5.1 => 7.5.1 
    @storybook/node-logger: ^7.5.1 => 7.5.1 
    @storybook/preset-create-react-app: ^7.5.1 => 7.5.1 
    @storybook/react: ^7.5.1 => 7.5.1 
    @storybook/react-webpack5: ^7.5.1 => 7.5.1 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: ^7.5.1 => 7.5.1 
    storybook-addon-mock: ^4.3.0 => 4.3.0
```

### Additional context

Just tried with only `storybook` `7.6.0-alpha.0` and I don't have the error.

**Comment by nicolasvienot** [comment]
Fixed by removing yarn cache (`yarn cache clean`) and node modules 😓
