### ISSUE TITLE
[Bug]: Storybook doesnt render stories when starting and after changes.

### ISSUE THREAD

**Issue by AmirSasson** [storybookjs/storybook#24609]
i have upgraded from storybook 6.5 to 7.5.
when running the 'strorybook dev' command the browser is opened and the shimmer is shown,
but will never render the component.

only when webpack finishes, 
and i refresh the pasge from the browser am i able to see my story component rendered.
if i change the story code, the browser will show the shimmer (loading) again, but as well will not render anything until i refresh the browser page.
 seems something with HOT Reload

![image](https://github.com/storybookjs/storybook/assets/11300892/d27114b4-54e0-46e0-a96f-ec52f5c5ad66)

i have no build errors neither do console/network errors and it seems like the websocket managesto recieve the messages.

i dont know what logs i should be looking for?

### To Reproduce 
this is my main.js addons setup:

```json

  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-a11y",
    "@storybook/addon-interactions",
    {
      name: "storybook-addon-swc",
      options: {
        swcLoaderOptions: {
          isModule: true,
          module: {
            type: "es6",
            noInterop: true,
          },
        },
      },
    },
  ],
```
  

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.10 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm <----- active
    pnpm: 8.10.0 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  npmPackages:
    @storybook/react: ^7.5.1 => 7.5.1 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.5.1 => 7.5.1
```

**Comment by valentinpalkovic** [comment]
Does the error also happen without the `storybook-addon-swc` addon?

**Comment by AmirSasson** [comment]
thanks @valentinpalkovic 
the build doesnt seem to pass without the SWC.
it complains about typescript,
and there is no error that i can see, it is just doesnt render the component. (only if i manually refresh the browser, am i able to see the component).

do you know if there is some kind of logs that are available, or maybe even debug

**Comment by valentinpalkovic** [comment]
Could you post the content of your whole `.storybook/main.js`? It is strange that without the addon Storybook isn't able to render the component, since per default we set up babel for all webpack5 based projects.

**Comment by AmirSasson** [comment]
this is the error:
```
=> Failed to build the preview
=> Failed to build the preview
99% end closing watch compilationWARN Force closed preview build
ModuleBuildError: Module build failed (from ../../../../common/temp/node_modules/.pnpm/babel-loader@9.1.2_@babel+core@7.23.2_webpack@5.79.0/node_modules/babel-loader/lib/index.js):
SyntaxError: /workspaces/ASI-Portal/src/Modules/configs/tools/.storybook/Button.stories.tsx: Unexpected token, expected "from" (1:12)

> 1 | import type { Meta, StoryObj } from "@storybook/react";
    |             ^
  2 | import React from "react";
  3 | const meta: Meta<typeof Button> = {
  4 |   component: Button
    at constructor (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:356:19)
    at JSXParserMixin.raise (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:3223:19)
    at JSXParserMixin.unexpected (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:3253:16)
    at JSXParserMixin.expectContextual (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:3567:12)
    at JSXParserMixin.parseImportSpecifiersAndAfter (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:14158:10)
    at JSXParserMixin.parseImport (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:14150:17)
    at JSXParserMixin.parseStatementContent (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:12715:27)
    at JSXParserMixin.parseStatementLike (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:12593:17)
    at JSXParserMixin.parseModuleItem (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:12570:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:13194:36)
    at JSXParserMixin.parseBlockBody (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:13187:10)
    at JSXParserMixin.parseProgram (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:12469:10)
    at JSXParserMixin.parseTopLevel (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:12459:25)
    at JSXParserMixin.parse (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:14381:10)
    at parse (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/lib/index.js:14422:38)
    at parser (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/transformation/normalize-file.js:64:37)
    at normalizeFile.next (<anonymous>)
    at run (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:261:32)
    at /workspaces/ASI-Portal/common/temp/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:223:11)
    at processResult (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/webpack@5.79.0_@swc+core@1.3.24_esbuild@0.17.17/node_modules/webpack/lib/NormalModule.js:761:19)
    at /workspaces/ASI-Portal/common/temp/node_modules/.pnpm/webpack@5.79.0_@swc+core@1.3.24_esbuild@0.17.17/node_modules/webpack/lib/NormalModule.js:863:5
    at /workspaces/ASI-Portal/common/temp/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /workspaces/ASI-Portal/common/temp/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/workspaces/ASI-Portal/common/temp/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /workspaces/ASI-Portal/common/temp/node_modules/.pnpm/babel-loader@9.1.2_@babel+core@7.23.2_webpack@5.79.0/node_modules/babel-loader/lib/index.js:41:103

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

(node:29743) [DEP_WEBPACK_COMPILATION_ADDITIONAL_CHUNK_ASSETS] DeprecationWarning: additionalChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:29743) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:29743) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:29743) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
 ELIFECYCLE  Command failed with exit code 1.
```


and this is my MAIN.TS:
```ts
export default {
  stories: ["**/Button.stories.@(ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-a11y",
    "@storybook/addon-interactions",
    // {
    //   name: "storybook-addon-swc",
    //   options: {
    //     swcLoaderOptions: {
    //       isModule: true,
    //       module: {
    //         type: "es6",
    //         noInterop: true,
    //       },
    //     },
    //   },
    // },
  ],
  framework: "@storybook/react-webpack5",
  //resolvePath: (file) => path.resolve(process.cwd(), file),
  webpackFinal: async (config) => {
    config.devtool = "eval-cheap-module-source-map";

    // Sass Modules
    config.module.rules.push({
      test: /\.(scss|sass)$/,
      exclude: /node_modules/,
      use: [
        // Creates `style` nodes from JS strings
        "style-loader",
        // Create type definitions for Sass modules.
        {
          loader: "css-modules-typescript-loader",
        },
        // Translates CSS into CommonJS.
        {
          loader: "css-loader",
          options: {
            modules: {
              localIdentName: "[local]__[hash:base64:5]",
            },
          },
        },
        // Compiles Sass to CSS.
        {
          loader: "sass-loader",
          options: {
            sourceMap: true,
          },
        },
      ],
    });

    return config;
  },
  docs: {
    autodocs: true,
  },
};
```

**Comment by jalovatt** [comment]
I'm experiencing the same issue. 
- Was able to bisect it down to something in Storybook 7.1.0 - everything works fine on 7.0.27.
- Like the OP, no errors are logged in my terminal, the console, or the websocket. Storybook "crashes" to the static progress bar the instant I hit _Save_ in my editor.

#### `main.js`
```
// This file has to be CommonJS - test-storybook fails to load it if it's ESM.
const path = require('path');

module.exports = {
  stories: [
    '../src/**/*.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  webpackFinal: (config) => {
    config.resolve.alias.jsdom = path.resolve(__dirname, 'noop.js');

    return config;
  },
};
```

#### Storybook Info
```
  System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v18.17.1/bin/yarn <----- active
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.7.5 - ~/Library/pnpm/pnpm
```

**Comment by AmirSasson** [comment]
update:
installing version "storybook": "^7.5.3"
fixed the problem i had.
