### ISSUE TITLE
[Bug]: Can't resolve 'child_process' due to a .filter() method in a component

### ISSUE THREAD

**Issue by nagman** [storybookjs/storybook#24619]
### Describe the bug

I have a component that accepts an array of objects:
```tsx
<Group sections={sections} />
```
If I filter on this array like so:
```tsx
<Group sections={sections.filter(isSectionWithId)} />
// ...
function isSectionWithId(section: Section): section is SectionWithId {
	return 'id' in section;
}
```
Then Storybooks fails to start and I get this big error:
```
ERROR in ./node_modules/detect-libc/lib/detect-libc.js 6:21-45
Module not found: Error: Can't resolve 'child_process' in '/Users/quint/Desktop/frm/frm.front/node_modules/detect-libc/lib'
 @ ./node_modules/sharp/lib/utility.js 9:19-41
 @ ./node_modules/sharp/lib/index.js 14:0-20
 @ ./node_modules/plaiceholder/dist/plaiceholder.esm.js 1:0-26 185:27-32 206:44-49
 @ ./app/models/image.ts 9:0-47 178:44-59
 @ ./app/components/Donations/Donations.model.ts 5:0-52 25:17-35
 @ ./app/components/DynamicZone/DynamicZone.model.ts 18:0-60 113:17-29
 @ ./app/components/DynamicSections/DynamicSections.tsx 7:0-67 14:39-54
 @ ./app/components/DynamicSections/DynamicSections.stories.tsx 5:0-48 8:13-28
 @ ./app/ lazy ^\.\/.*$ include: (?:\/app(?:\/(?%21\.)(?:(?:(?%21(?:^%7C\/)\.).)*?)\/%7C\/%7C$)(?%21\.)(?=.)[^/]*?\.stories\.tsx)$ chunkName: [request] namespace object ./components/DynamicSections/DynamicSections.stories.tsx ./components/DynamicSections/DynamicSections.stories
 @ ./storybook-stories.js 10:11-14:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

ERROR in ./node_modules/sharp/build/Release/sharp-darwin-x64.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/sharp/build/Release/ sync ^\.\/sharp\-.*\.node$ ./sharp-darwin-x64.node
 @ ./node_modules/sharp/lib/sharp.js 10:19-76
 @ ./node_modules/sharp/lib/input.js 8:14-32
 @ ./node_modules/sharp/lib/index.js 7:0-18
 @ ./node_modules/plaiceholder/dist/plaiceholder.esm.js 1:0-26 185:27-32 206:44-49
 @ ./app/models/image.ts 9:0-47 178:44-59
 @ ./app/components/Donations/Donations.model.ts 5:0-52 25:17-35
 @ ./app/components/DynamicZone/DynamicZone.model.ts 18:0-60 113:17-29
 @ ./app/components/DynamicSections/DynamicSections.tsx 7:0-67 14:39-54
 @ ./app/components/DynamicSections/DynamicSections.stories.tsx 5:0-48 8:13-28
 @ ./app/ lazy ^\.\/.*$ include: (?:\/app(?:\/(?%21\.)(?:(?:(?%21(?:^%7C\/)\.).)*?)\/%7C\/%7C$)(?%21\.)(?=.)[^/]*?\.stories\.tsx)$ chunkName: [request] namespace object ./components/DynamicSections/DynamicSections.stories.tsx ./components/DynamicSections/DynamicSections.stories
 @ ./storybook-stories.js 10:11-14:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

ERROR in ./node_modules/sharp/lib/libvips.js 9:18-52
Module not found: Error: Can't resolve 'child_process' in '/Users/quint/Desktop/frm/frm.front/node_modules/sharp/lib'
 @ ./node_modules/sharp/lib/constructor.js 10:0-39
 @ ./node_modules/sharp/lib/index.js 6:14-38
 @ ./node_modules/plaiceholder/dist/plaiceholder.esm.js 1:0-26 185:27-32 206:44-49
 @ ./app/models/image.ts 9:0-47 178:44-59
 @ ./app/components/Donations/Donations.model.ts 5:0-52 25:17-35
 @ ./app/components/DynamicZone/DynamicZone.model.ts 18:0-60 113:17-29
 @ ./app/components/DynamicSections/DynamicSections.tsx 7:0-67 14:39-54
 @ ./app/components/DynamicSections/DynamicSections.stories.tsx 5:0-48 8:13-28
 @ ./app/ lazy ^\.\/.*$ include: (?:\/app(?:\/(?%21\.)(?:(?:(?%21(?:^%7C\/)\.).)*?)\/%7C\/%7C$)(?%21\.)(?=.)[^/]*?\.stories\.tsx)$ chunkName: [request] namespace object ./components/DynamicSections/DynamicSections.stories.tsx ./components/DynamicSections/DynamicSections.stories
 @ ./storybook-stories.js 10:11-14:5
 @ ./storybook-config-entry.js 6:0-50 25:21-29 28:2-31:4 28:58-31:3 30:31-39

preview compiled with 3 errors
WARN Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
WARN Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
=> Failed to build the preview
99% end closing watch compilationWARN Force closed preview build
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:6698)
    at starter.next (<anonymous>)
    at Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:8727)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async storybookDevServer (./node_modules/@storybook/core-server/dist/index.js:104:2460)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:119:3007)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:103:3903)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:473:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:475:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
`
``

### To Reproduce

_No response_

### System

```bash
System:
  OS: macOS 13.4
  CPU: (8) x64 Apple M1
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - ~/.yarn/bin/yarn <----- active
  npm: 7.20.0 - ~/.npm-global/bin/npm
  pnpm: 8.9.0 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 118.0.5993.117
  Safari: 16.5
npmPackages:
  @storybook/addon-a11y: ^7.5.2 => 7.5.2 
  @storybook/addon-essentials: ^7.5.2 => 7.5.2 
  @storybook/addon-interactions: ^7.5.2 => 7.5.2 
  @storybook/addon-links: ^7.5.2 => 7.5.2 
  @storybook/addon-onboarding: ^1.0.8 => 1.0.8 
  @storybook/blocks: ^7.5.2 => 7.5.2 
  @storybook/nextjs: ^7.5.2 => 7.5.2 
  @storybook/react: ^7.5.2 => 7.5.2 
  @storybook/testing-library: ^0.2.2 => 0.2.2 
  chromatic: ^7.2.0 => 7.2.0 
  eslint-plugin-storybook: ^0.6.15 => 0.6.15 
  storybook: ^7.5.2 => 7.5.2 
  storybook-addon-rem: ^1.3.0 => 1.3.0
```

**Comment by nagman** [comment]
Woupsies, my bad, actually I was importing the filter function from another file which was starting with `import "server-only";`.

So I leave this issue here for anyone encountering similar issues: this may have to do with the `server-only` package. So you'll have to check each one of your imports because storybook can't guess the source of the issue.
