### ISSUE TITLE
[Bug]: Cannot find type definition file for 'sass'

### ISSUE THREAD

**Issue by robkroll** [storybookjs/storybook#24686]
### Describe the bug

I am using Storybook with an Angular project, and I have been using 7.0.8 successfully for a while with Angular 16 but using legacy (non-MDC) components. I have just updated Nx to 16.7.4 (which updates @angular packages and @angular/material to 16.2, and Storybook to 7.1.0) and switched most components to their MDC versions. 

I now cannot run Storybook and I am getting the error:

```
Error: error TS2688: Cannot find type definition file for 'sass'.
  The file is in the program because:
    Entry point for implicit type library 'sass'

    at addError (C:\Projects\datahub\DataHub.UI\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:31:29)
    at C:\Projects\datahub\DataHub.UI\node_modules\@ngtools\webpack\src\ivy\diagnostics.js:17:17
    at AngularWebpackPlugin.updateJitProgram (C:\Projects\datahub\DataHub.UI\node_modules\@ngtools\webpack\src\ivy\plugin.js:452:9)
    at AngularWebpackPlugin.setupCompilation (C:\Projects\datahub\DataHub.UI\node_modules\@ngtools\webpack\src\ivy\plugin.js:175:20)
    at C:\Projects\datahub\DataHub.UI\node_modules\@ngtools\webpack\src\ivy\plugin.js:103:22
    at Hook.eval [as call] (eval at create (C:\Projects\datahub\DataHub.UI\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:19:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Projects\datahub\DataHub.UI\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Projects\datahub\DataHub.UI\node_modules\webpack\lib\Compiler.js:1125:30)
    at C:\Projects\datahub\DataHub.UI\node_modules\webpack\lib\Compiler.js:1170:29
    at _next0 (eval at create (C:\Projects\datahub\DataHub.UI\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
```

I am importing a global style in through the Nx `project.json` file:

```json
"build-storybook": {
      "executor": "@storybook/angular:build-storybook",
      "outputs": ["{options.outputDir}"],
      "options": {
        "outputDir": "dist/storybook/storybook-host",
        "configDir": "libs/storybook-host/.storybook",
        "browserTarget": "storybook-host:build-storybook",
        "compodoc": false,
        "styles": [
          "apps/bsm/src/theme/styles.scss"
        ]
```

This always worked fine, and I was always using `@use 'sass:map'` for example in the stylesheet just fine. I can't find any details about this issue, help would be greatly appreciated.

### System

```bash
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 AMD EPYC 7763 64-Core Processor
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD <----- active
    pnpm: 3.8.1 - C:\Projects\datahub\DataHub.UI\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.76)
  npmPackages:
    @storybook/addon-actions: 7.1.0 => 7.1.0
    @storybook/addon-essentials: 7.1.0 => 7.1.0
    @storybook/addon-interactions: 7.1.0 => 7.1.0
    @storybook/angular: 7.1.0 => 7.1.0
    @storybook/blocks: ^7.1.0 => 7.4.1
    @storybook/core-common: ^7.1.0 => 7.3.2
    @storybook/core-server: 7.1.0 => 7.1.0
    @storybook/jest: ^0.2.2 => 0.2.2
    @storybook/testing-library: ^0.2.1 => 0.2.1
```

**Comment by robkroll** [comment]
I found out the problem and it's not related to Storybook. I have a transitive dependency on the deprecated `@types/sass` package. In the `node_modules/@types/sass` folder there is no `index.d.ts` file and the typescript compiler complains about that. Removing that directory fixes the issue.
