### ISSUE TITLE
[Bug]: Using code block in .mdx does not work

### ISSUE THREAD

**Issue by elliason** [storybookjs/storybook#24769]
### Describe the bug

I have a .mdx file that documents a tab component. It looks like this:
`import { Meta } from '@storybook/blocks';
import * as TabsStories from './Tabs.stories';

<Meta of={TabsStories} />

# Tabs

## Usage

```
    <Tabs defaultValue="account" className="">
        <TabsList>
            <TabsTrigger value="account">Můj profil</TabsTrigger>
            <TabsTrigger value="edit">Editace profilu</TabsTrigger>
        </TabsList>
        <TabsContent value="account">Obsah profilu</TabsContent>
        <TabsContent value="edit">Editace profilu</TabsContent>
    </Tabs>
````

Rendering this mdx file throws the following error (nodejs environment):
Error: Could not parse expression with acorn: Unterminated regular expression
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at /var/www/html/node_modules/@storybook/core-server/dist/index.js:54:2245
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at async Promise.all (index 1)
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at async Promise.all (index 0)
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at async StoryIndexGenerator.updateExtracted (/var/www/html/node_modules/@storybook/core-server/dist/index.js:54:1653)
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at async StoryIndexGenerator.ensureExtracted (/var/www/html/node_modules/@storybook/core-server/dist/index.js:54:2609)
2023-11-08 16:28:52 @cuni-is-persons/ui:dev: [1] WARN     at async StoryIndexGenerator.initialize (/var/www/html/node_modules/@storybook/core-server/dist/index.js:54:1580)

Also in browser page there is this error:
chunk-V3JBNODJ.mjs:27  Uncaught TypeError: Cannot read properties of undefined (reading 'defaultText')
    at newStyled.div.theme.theme (chunk-V3JBNODJ.mjs:27:43661)
    at handleInterpolation (index.mjs:14:3193)
    at serializeStyles (index.mjs:19:1660)
    at index.mjs:24:1381
    at index.mjs:19:2916
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)

Removing the code block in backtics fixes the error.

Storybook addon setup in main.ts file looks like this:
`/** @type { import('@storybook/react-vite').StorybookConfig } */
const config: StorybookConfig = {
    stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],

    addons: [
        getAbsolutePath('@storybook/addon-links'),
        getAbsolutePath('@storybook/addon-essentials'),
        getAbsolutePath('@storybook/addon-interactions'),
        getAbsolutePath('@storybook/addon-a11y'),
        getAbsolutePath('@storybook/addon-themes'),
        getAbsolutePath('@storybook/addon-coverage'),
    ],

    framework: {
        name: '@storybook/react-vite',
        options: {},
    },

    async viteFinal(config, { configType }) {
        // Be sure to return the customized config
        return mergeConfig(config, {
            server: IS_RUNNING_BEHIND_PROXY
                ? {
                      hmr: {
                          clientPort: 443,
                      },
                  }
                : {},
        });
    },

    docs: {
        autodocs: false,
    },

    features: {
        buildStoriesJson: true,
    },
};`

**Comment by PetterRuud** [comment]
Temp fix for me

```
# file.mdx
import { Source } from '@storybook/addon-docs';

<Source
  code={`
  // sm, md, lg
<UserIcon fontSize="sm" />
// pixels
<UserIcon sx={{ fontSize: 40 }} />`}
  language="jsx"
/>
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
