### ISSUE TITLE
[Bug]: No matching export in "global-externals:@storybook/components"

### ISSUE THREAD

**Issue by SuryaprakashCIT** [storybookjs/storybook#24929]
### Describe the bug

Post migrating the storybook to the latest v7.5.3, facing the following issue. The same issue was mentioned [here](https://github.com/storybookjs/storybook/issues/24906) but the solution proposed didnt solve the problem for me.  #24906 

```
yarn run v1.22.19
$ storybook build
@storybook/cli v7.5.3

info => Cleaning outputDir: /storybook-static
info => Loading presets
info => Building manager..
✘ [ERROR] No matching export in "global-externals:@storybook/components" for import "ArgsTable"

    node_modules/@storybook/addon-controls/dist/esm/ControlsPanel.js:31:9:
      31 │ import { ArgsTable, NoControlsWarning } from '@storybook/components';
         ╵          ~~~~~~~~~

✘ [ERROR] No matching export in "global-externals:@storybook/components" for import "NoControlsWarning"

    node_modules/@storybook/addon-controls/dist/esm/ControlsPanel.js:31:20:
      31 │ import { ArgsTable, NoControlsWarning } from '@storybook/components';
         ╵                     ~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "global-externals:@storybook/addons" for import "useEffect"

    node_modules/@storybook/addon-actions/dist/esm/preview/withActions.js:45:9:
      45 │ import { useEffect, makeDecorator } from '@storybook/addons';
         ╵          ~~~~~~~~~

✘ [ERROR] No matching export in "global-externals:@storybook/addons" for import "makeDecorator"

    node_modules/@storybook/addon-actions/dist/esm/preview/withActions.js:45:20:
      45 │ import { useEffect, makeDecorator } from '@storybook/addons';
         ╵                     ~~~~~~~~~~~~~

Error: Build failed with 4 errors:
node_modules/@storybook/addon-actions/dist/esm/preview/withActions.js:45:9: ERROR: No matching export in "global-externals:@storybook/addons" for import "useEffect"
node_modules/@storybook/addon-actions/dist/esm/preview/withActions.js:45:20: ERROR: No matching export in "global-externals:@storybook/addons" for import "makeDecorator"
node_modules/@storybook/addon-controls/dist/esm/ControlsPanel.js:31:9: ERROR: No matching export in "global-externals:@storybook/components" for import "ArgsTable"
node_modules/@storybook/addon-controls/dist/esm/ControlsPanel.js:31:20: ERROR: No matching export in "global-externals:@storybook/components" for import "NoControlsWarning"
    at failureErrorWithLog (./node_modules/esbuild/lib/main.js:1649:15)
    at ./node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (./node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (./node_modules/esbuild/lib/main.js:1056:7)
    at ./node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (./node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (./node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (./node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

```

**Comment by valentinpalkovic** [comment]
Hi @SuryaprakashCIT,

Can you provide a reproduction?

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏
