### ISSUE TITLE
[Bug]: Theme is not defined when try to use it inside a component

### ISSUE THREAD

**Issue by slim-hmidi1** [storybookjs/storybook#25010]
### Describe the bug

I'm using emotion/react and @emotion/styled v11 with storybook v7 in a nextjs app.
I add a custom theme to the preview and try to use it inside the components and stories but it's empty.

### To Reproduce

- create a next project using `npx create-next-app myapp`
- install storybook using `npx storybook@latest init`
- then add `@storybook/addon-themes` using `npx storybook@latest add @storybook/addon-themes`
- I updated the `preview.tsx` :
```tsx
import { withThemeFromJSXProvider } from '@storybook/addon-themes';
import { ThemeProvider } from '@emotion/react';

import { THEME } from 'lib';
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
   decorators = [
  withThemeFromJSXProvider({
  themes: {
    light: THEME.light,
    dark: THEME.dark,
  }
  defaultTheme: 'light',
  Provider: ThemeProvider,
})];
}
```
- I created a simple `Button.tsx`:
```tsx
import React from 'react';
import {Box} from '@gemini/core'
import styled from '@emotion/styled'

const CustomButton = styled('button')(({ theme }) => `
background-color: #04AA6D;
color: ${theme.color.primary};
`)

interface ButtonProps {
  label: string;
  onClick?: () => void;
}

export const Button = ({
  label,
}: ButtonProps) => {
  return (
    <Box as={CustomButton}>
      {label}
    </Box>
  );
};
```
- the `Button.stories.tsx` looks like:
```tsx
import type { Meta } from '@storybook/react';
import {useTheme} from '@emotion/react'

import { Button } from './Button';

const meta = {
  title: 'Example/Button',
  component: Button,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
} satisfies Meta<typeof Button>;

export default meta;

export const ButtonUsage = () => {
  const theme = useTheme()

  console.log('theme: ', theme)

  return (
      <Button label='label'/>
     
  );
};
```

### System

```bash
"@storybook/addon-essentials": "^7.5.3",
    "@storybook/addon-interactions": "^7.5.3",
    "@storybook/addon-links": "^7.5.3",
    "@storybook/addon-onboarding": "^1.0.8",
    "@storybook/addon-themes": "^7.5.3",
    "@storybook/blocks": "^7.5.3",
    "@storybook/nextjs": "^7.5.3",
    "@storybook/react": "^7.5.3",
    "@storybook/testing-library": "^0.2.2",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.0.3",
    "eslint-plugin-storybook": "^0.6.15",
    "storybook": "^7.5.3",
    "typescript": "^5"
```
```


### Additional context

```
TypeError: Cannot read properties of undefined (reading 'primary')
    at http://localhost:6006/stories-Button-stories.iframe.bundle.js:88:69
    at handleInterpolation (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:1376:24)
    at serializeStyles (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:1490:15)
    at http://localhost:6006/vendors-node_modules_pnpm_babel_runtime_7_23_4_node_modules_babel_runtime_helpers_esm_defineP-4c9cac.iframe.bundle.js:479:91
    at http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:994:12
    at renderWithHooks (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:38898:18)
    at updateForwardRef (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:43554:20)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:46297:16)
    at beginWork (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:54630:14)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_pnpm_emotion_react_11_11_1__types_react_18_2_39_react_18_2_0_node_module-8c2920.iframe.bundle.js:53476:12)
```

**Comment by slim-hmidi1** [comment]
I finally fixed the issue by updating the `.storybook/preview.tsx` accordingly:
```tsx
import React from "react";
import type { Preview } from "@storybook/react";
import { ThemeProvider } from '@emotion/react';
import { Theme } from "@theme-lib";


const CustomTheme = (Story, args) => {
  return (
      <ThemeProvider theme={Theme}>
        <Story {...args} />
      </ThemeProvider>
  )
}

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    CustomTheme,
  ]
};

export default preview;
```
