### ISSUE TITLE
[Bug]: Build error after addon updates

### ISSUE THREAD

**Issue by oytuncoban** [storybookjs/storybook#25505]
### Describe the bug

I'm getting this error while starting storybook.
```
Error: Build failed with 10 errors:
node_modules/@storybook/addon-essentials/dist/actions/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-actions/manager"
node_modules/@storybook/addon-essentials/dist/backgrounds/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-backgrounds/manager"
node_modules/@storybook/addon-essentials/dist/controls/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-controls/manager"
node_modules/@storybook/addon-essentials/dist/measure/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-measure/manager"
node_modules/@storybook/addon-essentials/dist/outline/manager.js:1:14: ERROR: Could not resolve "@storybook/addon-outline/manager"
...
    at failureErrorWithLog (./node_modules/esbuild/lib/main.js:1649:15)
    at ./node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (./node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (./node_modules/esbuild/lib/main.js:1056:7)
    at ./node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (./node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (./node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (./node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
```
    
Yarn=^3.7.0
Webpack=^5.87.0
React=^18.2.0
Babel=^7.22.8
.storybook/main.js file is updated with getAbsolutePath for Yarn PnP even though I'm not using it but the library does.
My webpack configuration has resolve field.

Tried solutions:
I've deleted all the packages and configurations related to storybook and re-installed with,  `yarn dlx storybook@latest init`. The addon dirs are available and getAbsolutePath should do the necessary work but I'm still getting the error.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /private/var/folders/mm/1l9vdg1n7cz99rxt4nbfytxw0000gn/T/xfs-4f24bb23/node
    Yarn: 3.7.0 - /private/var/folders/mm/1l9vdg1n7cz99rxt4nbfytxw0000gn/T/xfs-4f24bb23/yarn <----- active
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.7 => 7.6.7 
    @storybook/addon-interactions: ^7.6.7 => 7.6.7 
    @storybook/addon-links: ^7.6.7 => 7.6.7 
    @storybook/addon-onboarding: ^1.0.10 => 1.0.10 
    @storybook/blocks: ^7.6.7 => 7.6.7 
    @storybook/react: ^7.6.7 => 7.6.7 
    @storybook/react-webpack5: ^7.6.7 => 7.6.7 
    @storybook/test: ^7.6.7 => 7.6.7 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.7 => 7.6.7
```

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by oytuncoban** [comment]
You can mark it as "duplicate". 
The solution is discussed in an older [issue.](https://github.com/storybookjs/storybook/issues/20876#issuecomment-1542668305)
