### ISSUE TITLE
[Bug]:  Modules cannot be resolved using swc compiler in CI

### ISSUE THREAD

**Issue by undesicimo** [storybookjs/storybook#25901]
### Describe the bug

Running `storybook build` with `useSWC` on our github action workflow triggers the following errors 
```
=> Failed to build the preview
SB_BUILDER-WEBPACK5_0002 (WebpackInvocationError): Module not found: Error: Can't resolve '@/monitoring/hoge' in './src/common/hoge/fuge'
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:10546
    at ./node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (./node_modules/webpack/lib/Cache.js:150:23)
    at ./node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (./node_modules/webpack/lib/Compiler.js:1222:23)
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:10531
```

The same error is non-reproducible in local storybook build. 

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm <----- active
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.1
  npmPackages:
    @storybook/addon-actions: 7.6.8 => 7.6.12 
    @storybook/addon-essentials: 7.6.8 => 7.6.12 
    @storybook/addon-interactions: 7.6.8 => 7.6.12 
    @storybook/addon-links: 7.6.8 => 7.6.12 
    @storybook/addon-toolbars: 7.6.8 => 7.6.12 
    @storybook/react: 7.6.8 => 7.6.12 
    @storybook/react-webpack5: 7.6.8 => 7.6.12 
    @storybook/testing-library: 0.2.2 => 0.2.2 
    chromatic: 10.3.0 => 10.3.0 
    storybook: 7.6.8 => 7.6.12 
    storybook-addon-mock: 4.3.0 => 4.3.0
```

### Additional context

`main.ts`
```ts
import {StorybookConfig} from '@storybook/react-webpack5';
// import path from 'path';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-actions',
    '@storybook/addon-toolbars',
    'storybook-addon-mock',
    'storycap',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {
      builder: {
        useSWC: true,
      },
    },
  },
  staticDirs: ['./public'],
  docs: {
    autodocs: true,
  },
};

export default config;
```
`.swcrc` config  on root
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "baseUrl": "src",
    "paths": {
      "@/*": ["./*"],
    },
  },
}
```
`tsconfig.json`
```
{
  "compilerOptions": {
    "target": "ES2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": false,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noImplicitAny": false,
    "useUnknownInCatchVariables": false,
    "baseUrl": "src",
    "paths": {
      "@/*": ["./*"],
    },
    "sourceMap": true,
    "types": ["vitest/globals"],
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__mocks__/*.ts"],
}

```

**Comment by undesicimo** [comment]
The following issue might be related.
https://github.com/storybookjs/storybook/issues/3916#issuecomment-871283551
Changing `main.ts` to the following seems to solve the issue. 
```ts
...
 swc: () => {
    return {
      jsc: {
        baseUrl: 'src',
        paths: {
          '@/*': ['./*'],
        },
        transform: {
          react: {
            runtime: 'automatic',
          },
        },
      },
    };
  },
  webpackFinal: config => {
    if (config.resolve && config.resolve.alias) {
      config.resolve.alias['@'] = path.resolve(__dirname, '../src');
    }

    return config;
  },
...
```

**Comment by valentinpalkovic** [comment]
So it seems that your `.swcrc` file isn’t picked up. Is your cwd root? Or do you have a monorepo setup?

**Comment by undesicimo** [comment]
Please ignore my previous comment. It seems to not have solved the issue....
Our project isnt a monorepo.  
I have removed `.swcrc` from root. The same problem but got a different error message 
`swc config on main.ts + without .swcrc on root` 
```ts
swc: () => {
    return {
      jsc: {
        baseUrl: `${process.cwd()}/src`,
        paths: {
          '@/*': ['./*'],
        },
        transform: {
          react: {
            runtime: 'automatic',
          },
        },
      },
    };
  },
```
```
=> Failed to build the preview
SB_BUILDER-WEBPACK5_0002 (WebpackInvocationError): Module not found: Error: Can't resolve '../../../../../../../../../.././monitoring/datadog' in './src/common/redux/slices'
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:10546
    at ./node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (./node_modules/webpack/lib/Cache.js:150:23)
    at ./node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (./node_modules/webpack/lib/Compiler.js:1222:23)
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:10531
```
