### ISSUE TITLE
[Bug]: Error: Cannot find module '@storybook/vue3-vite/preset' inside PNPM monorepo

### ISSUE THREAD

**Issue by drennerpfc6** [storybookjs/storybook#25966]
### Describe the bug

Storybook cannot resolve modules in a PNPM monorepo when run inside a linux docker container. I have been banging my head on this problem all afternoon. Everything works fine locally on my Mac...

```javascript
const config = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: "@storybook/vue3-vite",
  docs: {
    autodocs: "tag",
  },
}
export default config
```

```text
storybook build
@storybook/cli v7.6.13
info => Cleaning outputDir: /storybook-static
info => Loading presets
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/vue3-vite/preset.
Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.
If you believe this is a bug, please open an issue on Github.
Error: Cannot find module '@storybook/vue3-vite/preset'
Require stack:
- /<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js
- /<project>/node_modules/.pnpm/@storybook+telemetry@7.6.13/node_modules/@storybook/telemetry/dist/index.js
- /<project>/node_modules/.pnpm/@storybook+cli@7.6.13/node_modules/@storybook/cli/dist/generate.js
- /<project>/node_modules/.pnpm/@storybook+cli@7.6.13/node_modules/@storybook/cli/bin/index.js
- /<project>/node_modules/.pnpm/storybook@7.6.13/node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._resolveFilename (/<project>/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.18.20/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:[98](5:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at interopRequireDefault (/<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js:6:21)
    at getContent (/<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js:13:332)
    at loadPreset (/<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js:13:540)
    at /<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js:15:549
    at Array.map (<anonymous>)
    at loadPreset (/<project>/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js:15:82)
```

I've even tried to host @storkbook dependencies
```text
public-hoist-pattern[]=@storybook/*
```

### To Reproduce

I am still trying to figure out how to get a reproduction for this since I can only get it to fail inside a docker container. 

### System

```bash
Storybook Environment Info:
  System:
    OS: Linux 3.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8488C
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-essentials: ^7.6.13 => 7.6.13 
    @storybook/addon-interactions: ^7.6.13 => 7.6.13 
    @storybook/addon-links: ^7.6.13 => 7.6.13 
    @storybook/blocks: ^7.6.13 => 7.6.13 
    @storybook/builder-vite: ^7.6.13 => 7.6.13 
    @storybook/test: ^7.6.13 => 7.6.13 
    @storybook/vue3: ^7.6.13 => 7.6.13 
    @storybook/vue3-vite: ^7.6.13 => 7.6.13 
    chromatic: ^10.9.2 => 10.9.2 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.13 => 7.6.13 

🩺 checking the health of your Storybook..
🥳 Your Storybook project looks good!
```

**Comment by SalahAdDin** [comment]
I'm having the same issue but with `postcss-import`:
```bash

- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/open-props@1.6.18/node_modules/open-props/postcss.config.cjs
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/loaders.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explorer.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/utils.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/cjs.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/webpack@5.90.1_@swc+core@1.4.0_esbuild@0.18.20/node_modules/webpack/lib/ProgressPlugin.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/webpack@5.90.1_@swc+core@1.4.0_esbuild@0.18.20/node_modules/webpack/lib/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/@storybook+nextjs@7.6.13_@swc+core@1.4.0_esbuild@0.18.20_next@14.1.0_react-dom@18.2.0_react@1_hira244ys3bq3vxf32k3zzxybi/node_modules/@storybook/nextjs/dist/preset.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/@storybook+core-common@7.6.13/node_modules/@storybook/core-common/dist/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/@storybook+telemetry@7.6.13/node_modules/@storybook/telemetry/dist/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/@storybook+cli@7.6.13/node_modules/@storybook/cli/dist/generate.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/@storybook+cli@7.6.13/node_modules/@storybook/cli/bin/index.js
- /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/storybook@7.6.13/node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._resolveFilename (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.18.20/node_modules/esbuild-register/dist/node.js:4799:36)
    at /home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/open-props@1.6.18/node_modules/open-props/postcss.config.cjs:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.18.20/node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/esbuild-register@3.5.0_esbuild@0.18.20/node_modules/esbuild-register/dist/node.js:4838:24)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
    at module.exports (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/import-fresh@3.3.0/node_modules/import-fresh/index.js:32:59)
    at loadJsSync (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/loaders.js:17:12)
    at #loadConfiguration (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explorer.js:92:30)
    at #readConfiguration (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explorer.js:77:80)
    at async search (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explorer.js:44:40)
    at async Explorer.search (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explorer.js:71:20)
    at async loadConfig (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/utils.js:118:16)
    at async Object.loader (/home/luisalaguna/Projects/TRT/twe_fe_next/node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/index.js:45:22)
 @ ./node_modules/.pnpm/css-loader@6.10.0_webpack@5.90.1/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[8].use[1]!./node_modules/.pnpm/postcss-loader@7.3.4_postcss@8.4.35_typescript@5.3.3_webpack@5.90.1/node_modules/postcss-loader/dist/cjs.js!./src/app/[locale]/globals.css 5:0-400 20:26-59
 @ ./src/app/[locale]/globals.css 8:6-323 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-293 77:0-293 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./.storybook/preview.ts 4:0-41
 @ ./storybook-config-entry.js 9:2900-2975 33:2-36:4 33:2868-36:3
 ```

**Comment by SalahAdDin** [comment]
Related [issue](https://github.com/storybookjs/storybook/issues/25981).

**Comment by shilman** [comment]
@drennerpfc6 @JReinhold any chance you can try this in a different package manager to help debug the problem? There have been a bunch of recent pnpm-related issues all at once and I'm wondering whether it's due to a bug (or just a change?) in the latest release of pnpm?

**Comment by drennerpfc6** [comment]
@shilman unfortunately I don't have anything for yarn setup in our CI that we use. I see that @SalahAdDin has tried a few more things without any luck. I can keep digging into my build failure, just let me know what to look for.

**Comment by superdrenner** [comment]
@shilman, we can close this issue. I discovered that my gitlab pipeline was caching dist directores in node_modules which was causing issues.

**Comment by SalahAdDin** [comment]
> @shilman, we can close this issue. I discovered that my GitLab pipeline was caching dist directories in node_modules which was causing issues.

Close it with a comment, please.

**Comment by superdrenner** [comment]
Issue was caused by cached node_modules in a ci pipeline preventing esbuild from doing what it needed to do.

**Comment by VaclavS16** [comment]
I had the same error. I have storybook in yarn workspace with own package.json. I solve it with using getAbsolutePath from https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments in my main.ts
