### ISSUE TITLE
[Bug]: StoryBook server crashing when using PNPM with NODE 20.11

### ISSUE THREAD

**Issue by ggualbertosouza** [storybookjs/storybook#25983]
### Describe the bug

Project setup: 
- Node 20.11.0
- PNPM 8.15.1
- Next 14.1.0
- Storybook 7.6.13

When you start Storybook, the server runs and interface shows up, the list of components in sidebar it shows but the main part of the page keeps loading forever and server crash instantly, this is the error: 
```
=> Failed to build the preview
Error: Cannot find package 'C:\Users\\\\\\node_modules\.pnpm\@storybook+preset-react-webpack@7.6.13_@babel+core@7.23.9_@swc+core@1.4.0_esbuild@0.18.20_rea_wlzunnjwmz32gifcmi56jmbtsm\node_modules\@storybook\react-docgen-typescript-plugin\package.json' imported from C:\Users\\\\\\\node_modules\.pnpm\@storybook+preset-react-webpack@7.6.13_@babel+core@7.23.9_@swc+core@1.4.0_esbuild@0.18.20_rea_wlzunnjwmz32gifcmi56jmbtsm\node_modules\@storybook\preset-react-webpack\dist\framework-preset-react-docs.js
Did you mean to import @storybook+react-docgen-typescript-plugin@1.0.6--canary.9.0c3f3b7.0_typescript@5.3.3_webpack@5.90.1/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js?
    at legacyMainResolve (node:internal/modules/esm/resolve:214:26)
    at packageResolve (node:internal/modules/esm/resolve:840:14)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:328:34)
    at importModuleDynamically (node:internal/modules/cjs/loader:1261:33)
    at importModuleDynamicallyWrapper (node:internal/vm/module:431:21)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:207:14)
    at Object.webpackFinal (.\node_modules\.pnpm\@storybook+preset-react-webpack@7.6.13_@babel+core@7.23.9_@swc+core@1.4.0_esbuild@0.18.20_rea_wlzunnjwmz32gifcmi56jmbtsm\node_modules\@storybook\preset-react-webpack\dist\framework-preset-react-docs.js:1:2025)
    at async Object.webpack (.\node_modules\.pnpm\@storybook+builder-webpack5@7.6.13_esbuild@0.18.20_typescript@5.3.3\node_modules\@storybook\builder-webpack5\dist\presets\custom-webpack-preset.js:1:3214)
    at async starter (.\node_modules\.pnpm\@storybook+builder-webpack5@7.6.13_esbuild@0.18.20_typescript@5.3.3\node_modules\@storybook\builder-webpack5\dist\index.js:1:7688)
    at async Module.start (.\node_modules\.pnpm\@storybook+builder-webpack5@7.6.13_esbuild@0.18.20_typescript@5.3.3\node_modules\@storybook\builder-webpack5\dist\index.js:1:11672)
    at async storybookDevServer (.\node_modules\.pnpm\@storybook+core-server@7.6.13\node_modules\@storybook\core-server\dist\index.js:66:2459)
    at async buildOrThrow (.\node_modules\.pnpm\@storybook+core-server@7.6.13\node_modules\@storybook\core-server\dist\index.js:60:8290)
    at async buildDevStandalone (.\node_modules\.pnpm\@storybook+core-server@7.6.13\node_modules\@storybook\core-server\dist\index.js:120:1397)
    at async withTelemetry (.\node_modules\.pnpm\@storybook+core-server@7.6.13\node_modules\@storybook\core-server\dist\index.js:65:3948)
    at async dev (.\node_modules\.pnpm\@storybook+cli@7.6.13\node_modules\@storybook\cli\dist\generate.js:514:401)
    at async Command.<anonymous> (.\node_modules\.pnpm\@storybook+cli@7.6.13\node_modules\@storybook\cli\dist\generate.js:529:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

This error only occurs when you are using PNPM with NODE 20.11.0, apparently the error is in when the preview of components are building.

### To Reproduce

1. Create `NextJs 14.1` project
2. Install the depencies usign `PNPM`
3. Install Storybook 
4. Run Storybook using Pnpm Storybook

### System

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12450H
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD <----- active
  Browsers:
    Edge: Chromium (121.0.2277.112)
  npmPackages:
    @storybook/addon-essentials: ^7.6.13 => 7.6.13
    @storybook/addon-interactions: ^7.6.13 => 7.6.13
    @storybook/addon-links: ^7.6.13 => 7.6.13
    @storybook/addon-onboarding: 1.0.11 => 1.0.11
    @storybook/blocks: ^7.6.13 => 7.6.13
    @storybook/nextjs: ^7.6.13 => 7.6.13
    @storybook/react: ^7.6.13 => 7.6.13
    @storybook/test: ^7.6.13 => 7.6.13
    eslint-plugin-storybook: ^0.6.15 => 0.6.15
    storybook: ^7.6.13 => 7.6.13
```

### Additional context

**Temporary solution**

You can use NPM instead PNPM, the project will run or you can downgrade your NODE to 18.17.1 or any previous version and keep using PNPM.

**Comment by valentinpalkovic** [comment]
Hi @ggualbertosouza 

You have delivered some important insights. What were the reasons to close this issue? Was it a duplicate? If so, can you link it eventually?

**Comment by Rodge** [comment]
Yes, why? Unable or unwilling to support Pnpm?
