### ISSUE TITLE
[Bug]: 8.0.0-beta.1 breaks storybook build in yarn pnp

### ISSUE THREAD

**Issue by bryanjtc** [storybookjs/storybook#26070]
### Describe the bug

Vite fails to build the preview. Rollup can't resolve the import "@storybook/locks" from "@storybook/addon-docs"

```ps
x Build failed in 1.76s
=> Failed to build the preview
Error: [vite]: Rollup failed to resolve import "@storybook/blocks" from "G:/repo/storybook-7-vite-test/.yarn/cache/@storybook-addon-docs-npm-8.0.0-beta.1-b40e5b7489-8848ff0944.zip/node_modules/@storybook/addon-docs/dist/chunk-HLWAVYOI.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///G:/repo/storybook-7-vite-test/.yarn/__virtual__/vite-virtual-b96dca4f1e/0/cache/vite-npm-5.1.3-ed3f8d8e35-d3b19607d7.zip/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:67046:27)
    at onRollupWarning (file:///G:/repo/storybook-7-vite-test/.yarn/__virtual__/vite-virtual-b96dca4f1e/0/cache/vite-npm-5.1.3-ed3f8d8e35-d3b19607d7.zip/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:67074:9)
    at onwarn (file:///G:/repo/storybook-7-vite-test/.yarn/__virtual__/vite-virtual-b96dca4f1e/0/cache/vite-npm-5.1.3-ed3f8d8e35-d3b19607d7.zip/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:66778:13)
    at file:///G:/repo/storybook-7-vite-test/.yarn/cache/rollup-npm-4.12.0-f631a9b21e-1650168231.zip/node_modules/rollup/dist/es/shared/node-entry.js:18308:13
    at Object.logger [as onLog] (file:///G:/repo/storybook-7-vite-test/.yarn/cache/rollup-npm-4.12.0-f631a9b21e-1650168231.zip/node_modules/rollup/dist/es/shared/node-entry.js:19965:9)
    at ModuleLoader.handleInvalidResolvedId (file:///G:/repo/storybook-7-vite-test/.yarn/cache/rollup-npm-4.12.0-f631a9b21e-1650168231.zip/node_modules/rollup/dist/es/shared/node-entry.js:18909:26)
    at file:///G:/repo/storybook-7-vite-test/.yarn/cache/rollup-npm-4.12.0-f631a9b21e-1650168231.zip/node_modules/rollup/dist/es/shared/node-entry.js:18867:26
```

### To Reproduce

https://github.com/bryanjtc/storybook-7-vite-test

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.1.0 - C:\Program Files\nodejs\yarn.CMD <----- active
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
```

### Additional context

The problem may be related to the change introduced in this pr https://github.com/storybookjs/storybook/pull/25925

**Comment by bryanjtc** [comment]
Can be fixed with https://github.com/storybookjs/storybook/pull/26024
Waiting until beta 3 to the test the fix.

**Comment by valentinpalkovic** [comment]
8.0.0-beta.3 is released. @bryanjtc Can you give it a try?

**Comment by bryanjtc** [comment]
It's fixed.
