### ISSUE TITLE
[Bug]: Haven't been able to run `npx storybook@latest upgrade` or `init` successfully since 7.5.3

### ISSUE THREAD

**Issue by KennethSlade** [storybookjs/storybook#26136]
### Describe the bug

I'm behind a corporate firewall, so I use a proxy.  This has worked successfully for prior software updates.  I tried upgrading our storybook to 7.6 and it downloads all of the dependencies, the progress bar in the command line reaches 100%, and then it spits out the following error that appears to be related to a proxy:

```
Need to install the following packages:
storybook@7.6.17
Ok to proceed? (y) 
/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/bin/index.js:23
  throw error;
  ^

InvalidArgumentError: Invalid URL protocol: the URL must start with `http:` or `https:`.
    at parseURL (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:1:16479)
    at Object.parseOrigin (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:1:17723)
    at new Pool (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:6390)
    at defaultFactory (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:42495)
    at new ProxyAgent (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:43707)
    at new UndiciProxyAgent (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:1383)
    at createProxy (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3071)
    at createFetch (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3218)
    at Object.<anonymous> (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3353)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
  code: 'UND_ERR_INVALID_ARG'
}

Node.js v20.9.0
```

`7.5.3` works just fine, but nothing after that.

### To Reproduce

Not entirely sure what the problem is, so not sure how to ensure someone can reproduce it.  That said, this seems to be an undici error (hence the UND_ prefix).  Here's the basics of my setup though:
1. running on the command line inside a RHEL 8 container
2. Node 20.9.0
3. proxy configuration is correctly set in a `.npmrc` file (`proxy` and `https-proxy` both start with `http://` and `no-proxy` includes `localhost` and `127.0.0.1` as well as some others)

### System

```bash
[root@e8c7f42bf623 workspace]# npx storybook@latest info
Need to install the following packages:
storybook@7.6.17
Ok to proceed? (y) y
/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/bin/index.js:23
  throw error;
  ^

InvalidArgumentError: Invalid URL protocol: the URL must start with `http:` or `https:`.
    at parseURL (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:1:16479)
    at Object.parseOrigin (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:1:17723)
    at new Pool (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:6390)
    at defaultFactory (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:42495)
    at new ProxyAgent (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:47:43707)
    at new UndiciProxyAgent (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:1383)
    at createProxy (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3071)
    at createFetch (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3218)
    at Object.<anonymous> (/root/.npm/_npx/bc7e1e37fcb46ffc/node_modules/node-fetch-native/dist/proxy.cjs:61:3353)
    at Module._compile (node:internal/modules/cjs/loader:1241:14) {
  code: 'UND_ERR_INVALID_ARG'
}

Node.js v20.9.0
```

### Additional context

Node v20.9.0

**Comment by KennethSlade** [comment]
Found a workaround!  It turns out that instead of using the `npm config` values for `http-proxy` and `https-proxy` that the shell's `https_proxy` must be set to a full URL value, and our value is currently set to exclude the protocol (e.g., `www.example.com` instead of `http://www.example.com`).  So by running `https_proxy=http://$https_proxy && npx storybook@latest upgrade` I can get the upgrade to run.
