### ISSUE TITLE
[Bug]: Can't update to Storybook 8 because of node version

### ISSUE THREAD

**Issue by KwinnyboiXPAR** [storybookjs/storybook#26453]
### Describe the bug

The updating process goes fine, all dependencies get updated. Then when trying to start Storybook using 'yarn storybook' I'm getting the following error:
```
@storybook/cli v8.0.0

info => Starting manager..
✘ [ERROR] Cannot start service: Host version "0.18.20" does not match binary version "0.20.1"

1 error
Error: The service was stopped: write EPIPE
    at ./node_modules/node_modules/esbuild/lib/main.js:1083:25
    at responseCallbacks.<computed> (./node_modules/node_modules/esbuild/lib/main.js:703:9)
    at afterClose (./node_modules/node_modules/esbuild/lib/main.js:693:28)
    at ./node_modules/node_modules/esbuild/lib/main.js:2143:11
    at onwriteError (node:internal/streams/writable:589:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

### To Reproduce

1. Update to Storybook v8 using instructions found [here](https://storybook.js.org/docs/migration-guide)
2. Run `yarn storybook`
3. Get errors

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 4.1.0 - /usr/local/bin/yarn <----- active
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  npmPackages:
    @storybook/addon-essentials: ^8.0.0 => 8.0.0 
    @storybook/addon-interactions: ^8.0.0 => 8.0.0 
    @storybook/addon-links: ^8.0.0 => 8.0.0 
    @storybook/blocks: ^8.0.0 => 8.0.0 
    @storybook/test: ^8.0.0 => 8.0.0 
    @storybook/test-runner: ^0.17.0 => 0.17.0 
    @storybook/vue3: ^8.0.0 => 8.0.0 
    @storybook/vue3-vite: ^8.0.0 => 8.0.0 
    eslint-plugin-storybook: ^0.8.0 => 0.8.0 
    storybook: ^8.0.0 => 8.0.0
```

**Comment by vanessayuenn** [comment]
This happens because of a `esbuild` version mismatch between vite and storybook. Please use the workaround mentioned [here](https://github.com/storybookjs/storybook/issues/26112#issuecomment-1979013129).
