### ISSUE TITLE
[Bug]: import_channels.default is not a constructor

### ISSUE THREAD

**Issue by C0ZEN** [storybookjs/storybook#26468]
### Describe the bug

In Storybook `8.0.0`, when serving a very minimalistic story with React/Vite:

```shell
TypeError: import_channels.default is not a constructor
    at mockChannel (http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:3132:10)
    at AddonStore2.getChannel (http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:3357:28)
    at useArgs (http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:6104:24)
    at wrapper (http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:6366:41)
    at http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:3584:18
    at http://localhost:4400/@fs/Users/mac//node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-context.js?v=b81ed463:3602:50
    at hookified (http://localhost:4400/sb-preview/runtime.js:84:10607)
    at http://localhost:4400/sb-preview/runtime.js:100:3256
    at http://localhost:4400/sb-preview/runtime.js:100:3717
    at e (http://localhost:4400/@fs/Users/mac/Documents/github/quality-linqueo-back/front/node_modules/.cache/storybook/0ef746ba8a4a30e8870f627459fed3284b52011fc2b4ddf00dca68b8f6e055a6/sb-vite/deps/storybook-react-i18next_preview.js?v=b81ed463:19:11)
```

### System

```bash
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm <----- active
  Browsers:
    Chrome: 122.0.6261.128
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-a11y: 8.0.0 => 8.0.0 
    @storybook/addon-essentials: 8.0.0 => 8.0.0 
    @storybook/addon-links: 8.0.0 => 8.0.0 
    @storybook/addon-storysource: 8.0.0 => 8.0.0 
    @storybook/core-server: 8.0.0 => 8.0.0 
    @storybook/manager-api: 8.0.0 => 8.0.0 
    @storybook/preset-scss: 1.0.3 => 1.0.3 
    @storybook/react-vite: 8.0.0 => 8.0.0 
    storybook-dark-mode: 3.0.3 => 3.0.3 
    storybook-react-context: 0.6.0 => 0.6.0 
    storybook-react-i18next: 2.1.1 => 2.1.1
```

**Comment by valentinpalkovic** [comment]
Hi @C0ZEN 

Please provide a minimal reproduction via https://storybook.new or share a minimal reproduction repo. Issues with reproductions are more likely to get prioritized.

**Comment by C0ZEN** [comment]
After some digging, the root cause is [storybook-react-context dependency](https://github.com/tyom/storybook-addons/tree/master/packages/storybook-react-context).
I opened an [issue](https://github.com/tyom/storybook-addons/issues/44) in the repository.
