### ISSUE TITLE
[Bug]: Storybook 8 + Vue 3 + Vite Installation failed (following the guide)

### ISSUE THREAD

**Issue by jankapunkt** [storybookjs/storybook#26738]
### Describe the bug

Following the guide for vue 3 + vite failed to run Storybook.
At first, because it missed `vite`, which I installed as dev-dependency but then, it fails to run, due to the following error:

```shell
npm run storybook                          

> storybook-testing@1.0.0 storybook
> storybook dev -p 6006

@storybook/cli v8.0.5

info => Starting manager..
info => Starting preview..
╭─────────────────────────────────────────────────────╮
│                                                     │
│   Storybook 8.0.5 for vue3-vite started             │
│   312 ms for manager and 186 ms for preview         │
│                                                     │
│    Local:            http://localhost:6006/         │
│    On your network:  http://192.168.178.46:6006/    │
│                                                     │
╰─────────────────────────────────────────────────────╯
2:41:32 PM [vite] warning: rewrote vue to vue/dist/vue.esm-bundler.js but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias
✘ [ERROR] Could not read from file: /home/jankapunkt/dev/zemki/storybook-testing/vue/dist/vue.esm-bundler.js

    node_modules/@storybook/vue3/dist/index.mjs:6:18:
      6 │ import { h } from 'vue';
        ╵                   ~~~~~

2:41:32 PM [vite] warning: rewrote vue to vue/dist/vue.esm-bundler.js but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
  Plugin: alias (x2)
Unhandled promise rejection: Error: Build failed with 1 error:
node_modules/@storybook/vue3/dist/index.mjs:6:18: ERROR: Could not read from file: /home/jankapunkt/dev/zemki/storybook-testing/vue/dist/vue.esm-bundler.js
    at failureErrorWithLog (/home/jankapunkt/dev/zemki/storybook-testing/node_modules/esbuild/lib/main.js:1651:15)
    at /home/jankapunkt/dev/zemki/storybook-testing/node_modules/esbuild/lib/main.js:1059:25
    at /home/jankapunkt/dev/zemki/storybook-testing/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

### To Reproduce

- Create a new storybook project, following https://storybook.js.org/docs/get-started/vue3-vite 
- Then install missing `vite` as dev dependency
- fail when execute `npm run storybook` with the error above

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm <----- active
  Browsers:
    Chrome: 121.0.6167.184
  npmPackages:
    @storybook/addon-essentials: ^8.0.5 => 8.0.5 
    @storybook/addon-interactions: ^8.0.5 => 8.0.5 
    @storybook/addon-links: ^8.0.5 => 8.0.5 
    @storybook/blocks: ^8.0.5 => 8.0.5 
    @storybook/test: ^8.0.5 => 8.0.5 
    @storybook/vue3: ^8.0.5 => 8.0.5 
    @storybook/vue3-vite: ^8.0.5 => 8.0.5 
    storybook: ^8.0.5 => 8.0.5
```

### Additional context

My colleague did the same sucessfully and without any errors, using the following environment:

```shell
Storybook Environment Info:
  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm <----- active
  Browsers:
    Chrome: 123.0.6312.105
    Safari: 16.1
  npmPackages:
    @storybook/addon-essentials: ^8.0.5 => 8.0.5 
    @storybook/addon-interactions: ^8.0.5 => 8.0.5 
    @storybook/addon-links: ^8.0.5 => 8.0.5 
    @storybook/blocks: ^8.0.5 => 8.0.5 
    @storybook/test: ^8.0.5 => 8.0.5 
    @storybook/vue3: ^8.0.5 => 8.0.5 
    @storybook/vue3-vite: ^8.0.5 => 8.0.5 
    storybook: ^8.0.5 => 8.0.5
```

**Comment by gangsthub** [comment]
To make the vue-vite project work, I had not only to add the `vite` dependency but also `vue` and `@vitejs/plugin-vue` and add a minimal `vite.config.ts`:

```ts
// ./vite.config.ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
  plugins: [vue()],
});
```

**Comment by fallemand** [comment]
Same issue for me. I was missing the vite config file.

**Comment by fallemand** [comment]
Checking the docs, the vite file is now mandatory: https://storybook.js.org/docs/8.0/migration-guide?ref=storybookblog.ghost.io

**Comment by shilman** [comment]
@jankapunkt @gangsthub @fallemand When I create a new Vue Vite project from scratch it already creates the vite config and installs the Vue plugin automically, so no extra configuration is needed for Storybook. Can you explain a situation in which this is not the case, other than upgrading from a Storybook 7.x project? Many thanks!

**Comment by jankapunkt** [comment]
@shilman I provided steps to reproduce with the given guide linked at the day I created this issue.

**Comment by shilman** [comment]
@jankapunkt those instructions are just about how to add storybook to an existing project. it doesn't say anything about your existing vue project setup. when i create a new vue vite project it is set up correctly. i'm trying to understand the cases in which vue vite projects are setup without a vite config and without the vue vite plugin installed etc.
