### ISSUE TITLE
[Bug]: storybook V8.0.8 cli failed with Vue3+vite+yarn 4.1.1-workspace project[ Error: @chromatic-com/storybook tried to access @storybook/client-logger]

### ISSUE THREAD

**Issue by jasonljohn** [storybookjs/storybook#26819]
### Describe the bug

**Bug Report Summary:**

When running `yarn dlx storybook@latest init`( in an fresh vue3 project which created by run `yarn create vue@latest` ), the following error occurs:

```
Error: @chromatic-com/storybook tried to access @storybook/client-logger, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Additionally, there are deprecation warnings about the `punycode` module being deprecated.

**Steps to Reproduce:**

1. create a new Vue3 project by running `yarn create vue@latest` in a empty directory.
2. Run `yarn dlx storybook@latest init`.

**Expected Behavior:**

Storybook should be installed without errors and should run successfully.

**Actual Behavior:**

The installation process fails with the error mentioned above.

**Environment:**

- Yarn version: 4.1.1
- Operating System: macOS
- Node.js version: v21.7.2

**Additional Information:**

- Storybook version: 8.0.8
- The error occurs when `@chromatic-com/storybook` attempts to access `@storybook/client-logger`, which is not declared in its dependencies.

### Full terminal output of errors are as follows:

Macintosh  ~/scraches/experiment01/packages/component-lib   master ± > **yarn dlx storybook@latest init**
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + storybook@npm:8.0.8, @ampproject/remapping@npm:2.3.0, @aw-web-design/x-default-browser@npm:1.4.126, and 615 more.
➤ YN0000: └ Completed in 2s 140ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 596 packages were added to the project (+ 82.23 MiB).
➤ YN0000: └ Completed in 0s 289ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 733ms
➤ YN0000: · Done with warnings in 4s 249ms

(node:2317) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Adding Storybook version 8.0.8 to your project..   │
│                                                      │
╰──────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2s 174ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ experiment01@workspace:. doesn't provide vite (pcb53a), requested by @storybook/vue3-vite.
➤ YN0002: │ experiment01@workspace:. doesn't provide vue (p8eb9c), requested by @storybook/vue3.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 582ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 2s 920ms
 • Adding Storybook support to your "Vue 3" app • Detected Vite project. Setting builder to Vite. ✓

  ✔ Getting the correct version of 0 packages
. ✓
Installing dependencies...

➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2s 44ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ experiment01@workspace:. doesn't provide vite (pcb53a), requested by @storybook/vue3-vite.
➤ YN0002: │ experiment01@workspace:. doesn't provide vue (p8eb9c), requested by @storybook/vue3.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 583ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 2s 790ms
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│   Storybook was successfully installed in your project! 🎉                   │
│   To run Storybook manually, run yarn storybook. CTRL+C to stop.             │
│                                                                              │
│   Wanna know more about Storybook? Check out https://storybook.js.org/       │
│   Having trouble or want to chat? Join us at https://discord.gg/storybook/   │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

Running Storybook
@storybook/cli v8.0.8

(node:2392) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: @chromatic-com/storybook tried to access @storybook/client-logger, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @storybook/client-logger
Required by: @chromatic-com/storybook@npm:1.3.2 (via /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/)

Require stack:
- /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-telemetry-npm-8.0.8-0bbc440e85-ca75fce31d.zip/node_modules/@storybook/telemetry/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/dist/generate.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/bin/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/storybook-npm-8.0.8-e2ae468c20-a74a7ae0a0.zip/node_modules/storybook/index.js
    at require$0.Module._resolveFilename (/Users/jason/scraches/experiment01/.pnp.cjs:15802:13)
    at Module._resolveFilename (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/__virtual__/esbuild-register-virtual-e61ad14c91/0/cache/esbuild-register-npm-3.5.0-d823f64ce0-9ccd0573cb.zip/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at require$0.Module._load (/Users/jason/scraches/experiment01/.pnp.cjs:15693:31)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js:449:2879
    at /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js:23:594
    at Object.<anonymous> (/Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js:452:91)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at loadPreset (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js:12:59)
    at loadPreset (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js:12:59)
    at async Promise.all (index 1)
    at async loadPresets (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js:12:483)
    at async getPresets (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js:12:1503)
    at async buildDevStandalone (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-server-npm-8.0.8-f08a52b71c-58331ef13c.zip/node_modules/@storybook/core-server/dist/index.js:65:2020)
    at async withTelemetry (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-server-npm-8.0.8-f08a52b71c-58331ef13c.zip/node_modules/@storybook/core-server/dist/index.js:28:3579)
    at async dev (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/dist/generate.js:669:563)
    at async Command.<anonymous> (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/dist/generate.js:671:250)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN   Failed to load preset: {"type":"presets","name":"/Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js"} on level 1
Error: @chromatic-com/storybook tried to access @storybook/client-logger, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @storybook/client-logger
Required by: @chromatic-com/storybook@npm:1.3.2 (via /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/)

Require stack:
- /Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-core-common-npm-8.0.8-2bacffabf6-872d7b682f.zip/node_modules/@storybook/core-common/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-telemetry-npm-8.0.8-0bbc440e85-ca75fce31d.zip/node_modules/@storybook/telemetry/dist/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/dist/generate.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/@storybook-cli-npm-8.0.8-c4c44157d7-baacf2e84f.zip/node_modules/@storybook/cli/bin/index.js
- /private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/cache/storybook-npm-8.0.8-e2ae468c20-a74a7ae0a0.zip/node_modules/storybook/index.js
    at require$$0.Module._resolveFilename (/Users/jason/scraches/experiment01/.pnp.cjs:15802:13)
    at Module._resolveFilename (/private/var/folders/79/l8nxvwdx6jx5jq2myf1gfm4w0000gn/T/xfs-1a3687c4/dlx-2287/.yarn/__virtual__/esbuild-register-virtual-e61ad14c91/0/cache/esbuild-register-npm-3.5.0-d823f64ce0-9ccd0573cb.zip/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at require$$0.Module._load (/Users/jason/scraches/experiment01/.pnp.cjs:15693:31)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at config (/Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/src/index.ts:264:16)
    at config (/Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/node_modules/ts-dedent/src/index.ts:49:15)
    at Object.<anonymous> (/Users/jason/.yarn/berry/cache/@chromatic-com-storybook-npm-1.3.2-6a28b0f7a2-10c0.zip/node_modules/@chromatic-com/storybook/src/index.ts:264:16)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)

### System

```bash
- Yarn version: 4.1.1
- Operating System: macOS
- Node.js version: v21.7.2
```#26820

**Comment by 53v3n3d4** [comment]
I got the same error with presets for html or webcomponents. With yarn, I could not get to work. Pnpm and npm work.
