### ISSUE TITLE
[Bug]: Uncaught TypeError: Refresh.isLikelyComponentType is not a function

### ISSUE THREAD

**Issue by CaptainN** [storybookjs/storybook#26822]
### Describe the bug

Storybook won't load any stories - I get this runtime error:

```
Uncaught TypeError: Refresh.isLikelyComponentType is not a function
    at registerExportsForReactRefresh (RefreshUtils.js:157:1)
    at Object.executeRuntime (RefreshUtils.js:205:1)
    at $ReactRefreshModuleRuntime$ (index.ts:6:1)
    at ./src/util/index.ts (index.ts:6:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/console-browserify/index.js (index.js:2:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
```

### To Reproduce

I'm really not sure, but here are my configs:

.storybook/main.js:
```javascript
const path = require("path");

/** @type { import('@storybook/nextjs').StorybookConfig } */
module.exports = {
  stories: ["../src/**/*.stories.@(js|jsx|ts|tsx)"],
  staticDirs: ["../public"],
  addons: [
    "@storybook/addon-onboarding",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@chromatic-com/storybook",
    "@storybook/addon-interactions",
  ],
  framework: {
    name: "@storybook/nextjs",
    options: {},
  },
  webpackFinal: async (config) => {
    config.resolve.modules = [
      ...(config.resolve.modules || []),
      path.resolve("../web/src"),
    ];
    return config;
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) =>
        prop.parent ? !/node_modules/.test(prop.parent.fileName) : true,
    },
  },
};
```

preview-head.html
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<style>
:root {
  --font-roboto: "Roboto";
}
</style>
```

```javascript
import { themes } from "@storybook/theming";

import "styles/main.scss";

/** @type { import('@storybook/react').Preview } */
const preview = {
  parameters: {
    // actions: { argTypesRegex: "^on[A-Z].*" },
    backgrounds: {
      default: "light",
    },
    darkMode: {
      dark: { ...themes.dark, appBg: "black" },
      light: { ...themes.normal, appBg: "red" },
    },
  },
};

export default preview;
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm <----- active
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 123.0.6312.123
    Edge: 123.0.2420.81
    Safari: 17.4
  npmPackages:
    @storybook/addon-essentials: ^8.0.8 => 8.0.8 
    @storybook/addon-interactions: ^8.0.8 => 8.0.8 
    @storybook/addon-links: ^8.0.8 => 8.0.8 
    @storybook/addon-onboarding: ^8.0.8 => 8.0.8 
    @storybook/blocks: ^8.0.8 => 8.0.8 
    @storybook/nextjs: ^8.0.8 => 8.0.8 
    @storybook/react: ^8.0.8 => 8.0.8 
    @storybook/test: ^8.0.8 => 8.0.8 
    storybook: ^8.0.8 => 8.0.8
```

**Comment by valentinpalkovic** [comment]
Hi @CaptainN 

Can you provide a reproduction? https://storybook.new

**Comment by CaptainN** [comment]
Weird, it was just the presence of this file in my source tree:

src/util/index.ts:

```ts
export function withGlobalProps(pageProps) {
  return {
    globalProps: {},
    ...pageProps,
  };
}
```

It wasn't even being imported by anything
