### ISSUE TITLE
[Bug]: find-implicit-spies codemod doesn't exist

### ISSUE THREAD

**Issue by tleunen** [storybookjs/storybook#26839]
### Describe the bug

When doing the migration to storybook v8, I got this message, which tells me to run the following command, but the codemod doesn't exist

```
npx storybook migrate find-implicit-spies --glob="**/*.stories.@(js|jsx|ts|tsx)"
```

```
found a 'remove-argtypes-regex' migration:
╭ Manual migration detected ────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                               │
│   Attention: We've detected that you're using argTypesRegex:                                                  │
│                                                                                                               │
│   .storybook/preview.tsx                                                                                      │
│      9 |                                                                                                      │
│     10 | export const parameters = {                                                                          │
│   > 11 |   actions: { argTypesRegex: '^on[A-Z].*' },                                                          │
│        |              ^^^^^^^^^^^^^                                                                           │
│     12 |   layout: 'centered',                                                                                │
│     13 |   darkMode: {                                                                                        │
│     14 |     darkClass: 'dark',                                                                               │
│                                                                                                               │
│   In Storybook you can write so-called play functions, which are used to render your stories interactively.   │
│   Mocking action args in play functions was done implicitly by analyzing the argTypesRegex.                   │
│                                                                                                               │
│   Since Storybook 8, implicit action args mocking isn't supported anymore.                                    │
│                                                                                                               │
│   Use the following command to check for mocked action usages in your play functions:                         │
│   npx storybook migrate find-implicit-spies --glob="**/*.stories.@(js|jsx|ts|tsx)"                            │
│                                                                                                               │
│   And follow the documentation to migrate your play functions:                                                │
│   https://storybook.js.org/docs/8.0/essentials/actions#via-storybooktest-fn-spy-function                      │
│                                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

```
❯ npx storybook migrate find-implicit-spies --glob="**/*.stories.@(js|jsx|ts|tsx)"
Error: Unknown codemod find-implicit-spies. Run --list for options.
    at runCodemod (./node_modules/@storybook/codemod/dist/index.js:1:4862)
    at migrate (./node_modules/@storybook/cli/dist/generate.js:429:513)
    at Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:474:1227)
    at Command.listener [as _actionHandler] (./node_modules/@storybook/cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (./node_modules/@storybook/cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (./node_modules/@storybook/cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (./node_modules/@storybook/cli/node_modules/commander/index.js:970:12)
    at Command.parse (./node_modules/@storybook/cli/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:478:125)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```
```
❯ npx storybook migrate --list
add-component-parameters
csf-2-to-3
csf-hoist-story-annotations
mdx-to-csf
move-builtin-addons
storiesof-to-csf
update-addon-info
update-organisation-name
upgrade-deprecated-types
upgrade-hierarchy-separators
```

### To Reproduce

Simply run `npx storybook@latest upgrade` in a v7 project containing `argTypesRegex`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/87738_1713131302453/bin/node
    Yarn: 4.0.2 - ~/Library/Caches/fnm_multishells/87738_1713131302453/bin/yarn <----- active
    npm: 10.5.2 - ~/Library/Caches/fnm_multishells/87738_1713131302453/bin/npm
  Browsers:
    Chrome: 123.0.6312.123
    Safari: 17.4.1
```

**Comment by yannbf** [comment]
Hey @tleunen could you please specify which version you have? If you run `npx storybook` it will use the version of Storybook that you have installed in your project. Is that maybe not fully upgraded? Can you try `npx storybook --version` and let us know which version that is?

If you ran `npx storybook@latest migrate`, you should definitely not have this error.

**Comment by tleunen** [comment]
Hmm... I may have ran this without `@latest`, because `npx storybook@latest migrate --list` definitely returns the list containing `find-implicit-spies`.

Closing the issue. Sorry about that.
