### ISSUE TITLE
[Bug]: Error with static storybook

### ISSUE THREAD

**Issue by AmirL** [storybookjs/storybook#27009]
### Describe the bug

I'm trying to upgrade storybook v7 to v8 in my project. It works well in the dev mode. But when I build it to deploy to Chromatic, it shows an error on every page:

`$RefreshSig$ is not defined`.  

The error goes right from the `preview.tsx`, after I import a file, that uses `react-redux`.  

I use webpack:
```
// .babelrc
{
  "presets": ["next/babel"],
  "plugins": ["relay", "babel-plugin-macros"]
}
```

It worked well with Storybook v7, and unfortunately, I can't use it with Chromatic in v8.

### To Reproduce

It's a big project, and it's hard to reproduce the problem. 

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/opt/node@18/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/opt/node@18/bin/npm <----- active
    pnpm: 8.3.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.91
    Safari: 17.4.1
  npmPackages:
    @storybook/react: ^8.0.9 => 8.0.9
```

### Additional context

from package.json
```
    "build-storybook": "NODE_ENV=development storybook build --webpack-stats-json ",
    "serve-storybook": "http-server storybook-static" // tried to debug the build locally
```

full error stack:
```
ReferenceError: $RefreshSig$ is not defined
    at ./src/reduxStore/user.slice.ts (http://localhost:8080/main.91ad2f21.iframe.bundle.js:1:71503)
    at __webpack_require__ (http://localhost:8080/runtime~main.8c5cbf51.iframe.bundle.js:1:381)
    at ./src/reduxStore/index.ts (http://localhost:8080/main.91ad2f21.iframe.bundle.js:1:60067)
    at __webpack_require__ (http://localhost:8080/runtime~main.8c5cbf51.iframe.bundle.js:1:381)
    at ./.storybook/preview.tsx (http://localhost:8080/main.91ad2f21.iframe.bundle.js:1:28197)
    at __webpack_require__ (http://localhost:8080/runtime~main.8c5cbf51.iframe.bundle.js:1:381)
    at PreviewWeb.getProjectAnnotations (http://localhost:8080/main.91ad2f21.iframe.bundle.js:1:23187)
    at PreviewWeb.getProjectAnnotationsOrRenderError (http://localhost:8080/sb-preview/runtime.js:129:6367)
    at PreviewWeb.initialize (http://localhost:8080/sb-preview/runtime.js:129:5672)
    at new PreviewWithSelection (http://localhost:8080/sb-preview/runtime.js:132:4977)
```

**Comment by AmirL** [comment]
Ok, I partly solved it. It can work if I run it in NODE_ENV = production, **and** explicitly set a list of plugins in babelrc
```json
{
  "presets": ["next/babel"],
  "plugins": ["relay", "babel-plugin-macros"],
  "env": {
    "storybook": {
      "plugins": [
        // Explicitly restate plugins without react-refresh
        "relay",
        "babel-plugin-macros"
      ]
    }
  }
}
```

But it doesn't work if I use NODE_ENV = development. And without it, relay testing tools don't work. (Obviously, they are never supposed to be run in production mode)

**Comment by AmirL** [comment]
I've solved the problem using babel settings from the previous message, and NODE_ENV=test.
