### ISSUE TITLE
[Bug]: docs tab not display in storybook ui

### ISSUE THREAD

**Issue by jon9090** [storybookjs/storybook#27023]
### Describe the bug

I utilize Storybook alongside Angular. I've included `@storybook/addon-docs` to showcase the code tab, but it's not rendering in the Storybook UI. 

What might be causing this issue? Am I overlooking something, or could it be a bug?

package.json:
```
"@storybook/addon-docs": "^8.0.9",
"@nx/storybook": "18.3.4",
"@storybook/angular": "7.6.18",
```

main.ts:
```
import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  stories: ['../../../**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: ['@storybook/addon-essentials', '@storybook/addon-interactions', 'storybook-addon-angular-router', "@storybook/addon-docs"],
  framework: {
    name: '@storybook/angular',
    options: { },
  },
};

export default config;

// To customize your webpack configuration you can use the webpackFinal field.
// Check https://storybook.js.org/docs/react/builders/webpack#extending-storybooks-webpack-config
// and https://nx.dev/recipes/storybook/custom-builder-configs
```

<img width="1003" alt="image" src="https://github.com/storybookjs/storybook/assets/74149517/f3373763-f420-4aaa-bce7-1665dad03d11">

### To Reproduce

```
const meta: Meta<FooComponent> = {
  component: FooComponent,
  title: 'FooComponent'
};

export default meta;
type Story = StoryObj<FooComponent>;

export const Primary: Story = {
  parameters: {
    docs: { source: { state: 'open' } },
  },
  args: {}
};
```

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn <----- active
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.6.11 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.119
    Edge: 124.0.2478.80
    Safari: 17.4.1
  npmPackages:
    @storybook/addon-docs: ^8.0.9 => 8.0.9
    @storybook/addon-essentials: 7.6.18 => 7.6.18
    @storybook/addon-interactions: ^7.5.3 => 7.6.18
    @storybook/addon-storysource: ^8.0.9 => 8.0.9
    @storybook/angular: 7.6.18 => 7.6.18
    @storybook/core-server: 7.6.18 => 7.6.18
    @storybook/html-vite: ^8.0.9 => 8.0.9
    @storybook/jest: ^0.2.3 => 0.2.3
    @storybook/test-runner: ^0.13.0 => 0.13.0
    @storybook/testing-library: ^0.2.2 => 0.2.2
    storybook-addon-angular-router: ^1.10.0 => 1.10.0
```
```


### Additional context

_No response_

**Comment by kangaroo19** [comment]
```js
import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
  stories: ['../../../**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  addons: ['@storybook/addon-essentials', '@storybook/addon-interactions', 'storybook-addon-angular-router', "@storybook/addon-docs"],
  framework: {
    name: '@storybook/angular',
    options: { },
  },
  docs: {   /* add this code */
    autodocs: true,
  },
};

export default config;
```
i 've solved that problem by adding that code

**Comment by jon9090** [comment]
@kangaroo19 I did:
```
 docs: {   /* add this code */
    autodocs: true,
  },
```

but it throw an error:
```
(0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...).componentStoriesFromCSFFile is not a function
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...).componentStoriesFromCSFFile is not a function
    at Primary (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:5836:83)
    at Nh (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:38555:7)
    at Vk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41737:11)
    at Uk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41431:11)
    at Tk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41425:23)
    at Ik (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41411:5)
    at Nk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41134:7)
    at Gk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41071:51)
    at J (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:42973:17)
    at MessagePort.R (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:43004:11)
```

**Comment by kangaroo19** [comment]
could you show me your any stories.ts code?

**Comment by wangmeijian** [comment]
> @kangaroo19 I did:
> 
> ```
>  docs: {   /* add this code */
>     autodocs: true,
>   },
> ```
> 
> but it throw an error:
> 
> ```
> (0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...).componentStoriesFromCSFFile is not a function
> TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.useContext)(...).componentStoriesFromCSFFile is not a function
>     at Primary (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:5836:83)
>     at Nh (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:38555:7)
>     at Vk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41737:11)
>     at Uk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41431:11)
>     at Tk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41425:23)
>     at Ik (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41411:5)
>     at Nk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41134:7)
>     at Gk (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:41071:51)
>     at J (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:42973:17)
>     at MessagePort.R (http://localhost:4400/vendors-node_modules_storybook_addon-docs_dist_DocsRenderer-K4EAMTCU_mjs.iframe.bundle.js:43004:11)
> ```

the same issue

**Comment by valentinpalkovic** [comment]
You have a mix of Storybook 8 and 7 dependencies. Please make sure that all Storybook dependencies are using the same version.

**Comment by wangmeijian** [comment]
> You have a mix of Storybook 8 and 7 dependencies. Please make sure that all Storybook dependencies are using the same version.

no, my dependencies version is 8.1.1 all
```
"@chromatic-com/storybook": "^1",
"@storybook/addon-essentials": "^8.1.1",
"@storybook/addon-interactions": "^8.1.1",
"@storybook/addon-links": "^8.1.1",
"@storybook/addon-mdx-gfm": "^8.1.1",
"@storybook/blocks": "^8.1.1",
"@storybook/testing-library": "^0.2.2",
"@storybook/vue3": "^8.1.1",
"@storybook/vue3-vite": "^8.1.1",
"storybook": "^8.1.1",
```

**Comment by Adhiman26** [comment]
> ```js
> import type { StorybookConfig } from '@storybook/angular';
> 
> const config: StorybookConfig = {
>   stories: ['../../../**/*.stories.@(js|jsx|ts|tsx|mdx)'],
>   addons: ['@storybook/addon-essentials', '@storybook/addon-interactions', 'storybook-addon-angular-router', "@storybook/addon-docs"],
>   framework: {
>     name: '@storybook/angular',
>     options: { },
>   },
>   docs: {   /* add this code */
>     autodocs: true,
>   },
> };
> 
> export default config;
> ```
> 
> i 've solved that problem by adding that code

**I Have Tried method, but I still don't see the "Docs" addon.**
anyone found the solution?

**Comment by Adhiman26** [comment]
I found a solution in the official Storybook documentation.
Sharing it for your reference:
https://storybook.js.org/docs/writing-docs/autodocs

Enjoy the Learning...

**Comment by thescientist13** [comment]
Thank you @Adhiman26 , adding the `tags` in _preview.js_ per your link resolved the issue for me 💯
