### ISSUE TITLE
[Bug]: Unable to add storybook to existing nextjs project

### ISSUE THREAD

**Issue by Profesor08** [storybookjs/storybook#28298]
### Describe the bug

When i try to add storybook to project `npx storybook@latest init`, I get unexpected weird error. Error is weird because file `node_modules\@emnapi\runtime\index.js` exists as on screenshot, but it is not accessible at all. I think there is something weird with `@emnapi` package. This package is added is you have installed `sharp`.

![image](https://github.com/storybookjs/storybook/assets/8218016/608464e6-6ca3-49da-a2ee-e52ed1b2fbfc)

### Reproduction link

https://stackblitz.com/edit/stackblitz-starters-jxb9h4

### Reproduction steps

1. create nextjs project
2. `npm i sharp`
3. `npx storybook@latest init`

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD <----- active
    pnpm: 8.6.12 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (126.0.2592.61)
```

### Additional context

```bash
$ npx storybook@latest init
╭───────────────────────────────────────────────────────╮
│                                                       │
│   Adding Storybook version 8.1.10 to your project..   │
│                                                       │
╰───────────────────────────────────────────────────────╯
 • Detecting project type. ✓
Installing dependencies...

npm ERR! code EPERM
npm ERR! syscall lstat
npm ERR! path D:\git\app\node_modules\@emnapi\runtime\index.js
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, lstat 'D:\git\app\node_modules\@emnapi\runtime\index.js'
npm ERR!     at async Object.lstat (node:internal/fs/promises:1018:18)
npm ERR!     at async moveFile (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\fs\lib\move-file.js:33:26)
npm ERR!     at async Promise.all (index 1)
npm ERR!     at async moveFile (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\fs\lib\move-file.js:36:9)
npm ERR!     at async Promise.allSettled (index 0)
npm ERR!     at async [reifyPackages] (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:251:11)
npm ERR!     at async Arborist.reify (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:170:5)
npm ERR!     at async Install.exec (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:149:5)
npm ERR!     at async module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js:61:5)
npm ERR!  Error: EPERM: operation not permitted, lstat 'D:\git\app\node_modules\@emnapi\runtime\index.js'     
npm ERR!     at async Object.lstat (node:internal/fs/promises:1018:18)
npm ERR!     at async moveFile (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\fs\lib\move-file.js:33:26)
npm ERR!     at async Promise.all (index 1)
npm ERR!     at async moveFile (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\fs\lib\move-file.js:36:9) 
npm ERR!     at async Promise.allSettled (index 0)
st\reify.js:251:11)
npm ERR!     at async Arborist.reify (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:170:5)
npm ERR!     at async Install.exec (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:149:5)
npm ERR!     at async module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js:61:5) {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path: 'D:\\git\\app\\node_modules\\@emnapi\\runtime\\index.js'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2024-06-20T11_55_47_166Z-debug-0.log       
An error occurred while installing dependencies.
```

**Comment by vanessayuenn** [comment]
@Profesor08 i am not able to see the same error in the repro you shared. it looks to be a windows permission issue have you checked the permissions of that file as suggested?
