### ISSUE TITLE
[Bug]: `storybook@next init` fails on svelte(-kit) project

### ISSUE THREAD

**Issue by manuel3108** [storybookjs/storybook#28475]
### Describe the bug

Looks like this is only happening on the beta build @8.2.0-beta.0.
The cli fails with an unexpected error:

```
Error: TypeError: wnt.default is not a function
```

Relates https://github.com/storybookjs/storybook/issues/27096
Relates https://github.com/storybookjs/storybook/issues/28474
Relates https://github.com/svelte-add/svelte-add/issues/475

### Reproduction link

https://github.com/manuel3108/storybook-missing-packages-repro (Reused from related issue)

### Reproduction steps

- Checkout this repo [https://github.com/manuel3108/storybook-missing-packages-repr](https://github.com/manuel3108/storybook-missing-packages-repro)
- switch to branch `test-2`
- run `npx storybook@next init`

<details><summary>Exception details:</summary>
<p>

An error occurred while installing dependencies:
wnt.default is not a function

     Error: TypeError: wnt.default is not a function
    at QJ.addDependencies (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\@storybook\core\dist\common\index.cjs:153207:72)
    at async baseGenerator (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\storybook\dist\generate.cjs:96:1229)
    at async generator15 (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\storybook\dist\generate.cjs:133:3110)
    at async installStorybook (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\storybook\dist\generate.cjs:145:4887)
    at async doInitiate (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\storybook\dist\generate.cjs:155:894) 
    at async withTelemetry (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\@storybook\core\dist\core-server\index.cjs:188662:12)
    at async initiate (C:\Users\manue\AppData\Local\npm-cache\_npx\eb8bf615e50a412a\node_modules\storybook\dist\generate.cjs:180:214)   
  ⠏ Installing Storybook dependencies
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL: 
https://storybook.js.org/telemetry

</p>
</details> 

Even easier is to have a look at this CI output: https://github.com/manuel3108/storybook-missing-packages-repro/actions/runs/9825360106/job/27125418556

### System

```bash
(from CI)

Storybook Environment Info:

  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.0 - /opt/hostedtoolcache/node/20.15.0/x64/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.7.0 - /opt/hostedtoolcache/node/20.15.0/x64/bin/npm <----- active
    pnpm: 9.4.0 - /opt/hostedtoolcache/node/20.15.0/x64/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.126
```

### Additional context

Very similar issue to https://github.com/storybookjs/storybook/issues/28474. The difference is that this issue even happens without adding any additional commands, and the generated exception is a totally different one from the related issue.

**Comment by valentinpalkovic** [comment]
This should be fixed. Can you please try it out?

**Comment by manuel3108** [comment]
This is resolved!

**Comment by DemaPy** [comment]
I have the same problem with storybook if using react 17 version.

Just update to the latest one.

**Comment by dep** [comment]
Same problem today in my React 18 + SB 8.2 codebase.

```
npx storybook@latest migrate mdx-to-csf --glob "src/**/*.stories.mdx"
✅ Adding "@storybook/blocks" package

An error occurred while installing dependencies:
wnt.default is not a function
Error: TypeError: wnt.default is not a function
    at QJ.addDependencies (/Users/dpeck/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/core/dist/common/index.cjs:153206:72)
    at async addStorybookBlocksPackage (/Users/dpeck/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:665:3906)
    at async migrate (/Users/dpeck/.npm/_npx/bc7e1e37fcb46ffc/node_modules/storybook/dist/generate.cjs:665:3374)
```

**Comment by thulasi127** [comment]
Also getting the same exact output/problem in my Angular CLI 17.2.3 + Node: 18.15.0 codebase

**Comment by ben-hamel** [comment]
getting this in Vue3+Vite project as well

**Comment by indapublic** [comment]
React 18.2 + Storybook 8.2.9

<img width="843" alt="image" src="https://github.com/user-attachments/assets/7d5a3df2-355d-4e9f-aa85-eb0ac5d3a962">
