### ISSUE TITLE
[Bug]: storybook build fails no such file or directory 

### ISSUE THREAD

**Issue by seb-lean** [storybookjs/storybook#28551]
### Describe the bug

```
Error: ENOENT: no such file or directory, open '/Users/sebastian/Code/frontend/link-sdk-web-v2/dist/assets/index-DiMIrLXo.js'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Object.writeBundle (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/vite-plugin-banner/dist/index.cjs:7:1618)
    at file:///Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
    at async Promise.all (index 0)
    at async PluginDriver.hookParallel (file:///Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/rollup/dist/es/shared/node-entry.js:19702:9)
    at async file:///Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/rollup/dist/es/shared/node-entry.js:20699:13
    at async catchUnfinishedHookActions (file:///Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/rollup/dist/es/shared/node-entry.js:20119:16)
    at async build (file:///Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:65670:16)
    at async build (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/@storybook/builder-vite/dist/index.js:58:230)
    at async Promise.all (index 0)
    at async Module.build2 (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/@storybook/builder-vite/dist/index.js:58:1784)
    at async Promise.all (index 0)
    at async buildStaticStandalone (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/@storybook/core/dist/core-server/index.cjs:188405:3)
    at async withTelemetry (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/@storybook/core/dist/core-server/index.cjs:188662:12)
    at async build (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/storybook/dist/generate.cjs:727:1337)
    at async Command.<anonymous> (/Users/sebastian/Code/frontend/link-sdk-web-v2/node_modules/storybook/dist/generate.cjs:730:145) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/sebastian/Code/frontend/link-sdk-web-v2/dist/assets/index-DiMIrLXo.js'
}
```

It's looking for the Storybook built files in /dist, when by default they should be in `/storybook-static`.

I based my project on the Vite installer, and somewhere along the way this error has appeared. 

A workaround is to set the output dir with `storybook build --output-dir ./dist`. Actually any dir works, _except_ for `storybook-static`! 

I concede this does not happen in a freshly installed project, so something has gone wrong, but I've I've searched my codebase for `dist` and it's not in any related references. I definitely think something odd is happening. Posting here in case it help someone else. 

### Reproduction link

-

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm <----- active
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.3
  npmPackages:
    @storybook/addon-coverage: ^1.0.4 => 1.0.4
    @storybook/addon-essentials: ^8.2.1 => 8.2.1
    @storybook/addon-interactions: ^8.2.1 => 8.2.1
    @storybook/addon-links: ^8.2.1 => 8.2.1
    @storybook/addon-onboarding: ^8.2.1 => 8.2.1
    @storybook/blocks: ^8.2.1 => 8.2.1
    @storybook/react: ^8.2.1 => 8.2.1
    @storybook/react-vite: ^8.2.1 => 8.2.1
    @storybook/test: ^8.2.1 => 8.2.1
    @storybook/test-runner: ^0.19.0 => 0.19.0
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.2.1 => 8.2.1
```
```


### Additional context

_No response_

**Comment by seb-lean** [comment]
There may be some option in there which needs to be tweaked, but it's not obvious to me which it would be. I tried messing with `viteFinal` but it just broke the build. 

I know Vite has a default output dir of `dist` so maybe that's influencing it somehow. If `@storybook/react-vite` pulls in the Vite config could it be overwriting the output dir? 🤷

**Comment by seb-lean** [comment]
This turned out to be an issue with Vite, specifically the banner plugin - it was looking for a dist dir.
