### ISSUE TITLE
[Bug]: error when starting `storybook` using `postcss-url` plugin to inline assets

### ISSUE THREAD

**Issue by ciepol** [storybookjs/storybook#28635]
### Describe the bug

When using `PostCSS` plugin ([postcss-url](https://www.npmjs.com/package/postcss-url)) to inline assets using base64 encoding in `url()` error pops up during `storybook` start:
```shell
Unhandled promise rejection: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/home/projects/github-txbnpe-gdeiug/\x00/sb-common-assets/nunito-sans-regular.woff2'
```

Feels like the issue has been introduced while doing https://github.com/storybookjs/storybook/pull/27110

### Reproduction link

https://stackblitz.com/edit/github-txbnpe-gdeiug?file=postcss.config.js

### Reproduction steps

1. add `PostCSS` configuration in `postcss.config.js`:
```js
import url from 'postcss-url';

/** @type {import('postcss-load-config').Config} */
const config = {
  extract: false,
  inject: true,
  plugins: [
    url({
      url: 'inline',
    }),
  ],
  sourceMap: true,
};

export default config;
```
2. run `storybook dev -p 6006`

### System

```bash
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm <----- active
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-essentials: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/addon-interactions: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/addon-links: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/addon-onboarding: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/blocks: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/react: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/react-vite: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    @storybook/test: ^8.3.0-alpha.1 => 8.3.0-alpha.1 
    storybook: ^8.3.0-alpha.1 => 8.3.0-alpha.1
```

**Comment by Th3S4mur41** [comment]
I'm facing a similar issue, but with Vite instead of Webpack

```sh
[build:watch] [storybook] Sourcemap for "/virtual:/@storybook/builder-vite/setup-addons.js" points to missing source files
[build:watch] [storybook] C:\src\core\node_modules\storybook\bin\index.cjs:23
[build:watch] [storybook]   throw error;
[build:watch] [storybook]   ^
[build:watch] [storybook]
[build:watch] [storybook] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'C:\\src\\core\\\x00\\sb-common-assets\\nunito-sans-regular.woff2'
[build:watch] [storybook]     at Object.access (node:fs:227:10)
[build:watch] [storybook]     at C:\src\core\node_modules\postcss-url\src\lib\get-file.js:21:12
[build:watch] [storybook]     at new Promise (<anonymous>)
[build:watch] [storybook]     at existFileAsync (C:\src\core\node_modules\postcss-url\src\lib\get-file.js:20:12)
[build:watch] [storybook]     at C:\src\core\node_modules\postcss-url\src\lib\get-file.js:32:20
[build:watch] [storybook]     at Array.map (<anonymous>)
[build:watch] [storybook]     at C:\src\core\node_modules\postcss-url\src\lib\get-file.js:31:36
[build:watch] [storybook]     at new Promise (<anonymous>)
[build:watch] [storybook]     at findExistsPath (C:\src\core\node_modules\postcss-url\src\lib\get-file.js:30:12)
[build:watch] [storybook]     at getFile (C:\src\core\node_modules\postcss-url\src\lib\get-file.js:61:12)
[build:watch] [storybook]     at processCopy (C:\src\core\node_modules\postcss-url\src\type\copy.js:57:12)
[build:watch] [storybook]     at C:\src\core\node_modules\postcss-url\src\lib\decl-processor.js:67:9
[build:watch] [storybook]     at process (C:\src\core\node_modules\postcss-url\src\lib\decl-processor.js:95:16)
[build:watch] [storybook]     at replaceUrl (C:\src\core\node_modules\postcss-url\src\lib\decl-processor.js:111:25)      
[build:watch] [storybook]     at C:\src\core\node_modules\postcss-url\src\lib\decl-processor.js:139:35
[build:watch] [storybook]     at String.replace (<anonymous>) {
[build:watch] [storybook]   code: 'ERR_INVALID_ARG_VALUE'
[build:watch] [storybook] }
[build:watch] [storybook]
[build:watch] [storybook] Node.js v20.14.0
[build:watch] [storybook] npm run storybook exited with code 7
```

**Comment by kerryj89** [comment]
I tried out Tailwind v4 Beta today with Storybook + Vite setup.
https://tailwindcss.com/docs/v4-beta

To isolate the issue, I removed all plugins but Tailwind v4's postcss plugin:

```js
// postcss.config.js
/** @type {import('postcss-load-config').Config} */
const config = {
    plugins: {
        '@tailwindcss/postcss': {}
    },
};

export default config;
```

But get an immediate error in Storybook:

```
[postcss] The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00/iframe.html?html-proxy&index=1.css'
```

I believe this issue is related to what I'm experiencing here.

**Comment by 58bits** [comment]
We're receiving the same error - but in our case all that changed in our 'postcss.config.mjs' file - was adding support for css modules  - everything was working fine before we enabled postcss-modules. We're using Storybook with the Vite framework.

```js
// postcss.config.mjs
const config = {
  plugins: {
    'postcss-import': {},
    'postcss-nested': {},
    'postcss-modules': {
      generateScopedName: '[name]__[local]__[hash:base64:5]',
      globalModulePaths: [/src\/styles\/.*\.css$/] // Ensure global CSS isn't processed as modules
    },
    tailwindcss: {},
    autoprefixer: {},
    cssnano: process.env.NODE_ENV === 'production' ? {} : false
  }
}

export default config
``

**Comment by 58bits** [comment]
Ah okay in our case - for Storybook at least, we don't need the postcss-modules plugin in our  postcss.config.mjs config - since both Vite has built-in support for css modules.

**Comment by Th3S4mur41** [comment]
I hoped it might have been resolved with Storybook 9, but it's unfortunately not the case.
A workaround that seem to be working for our use case, is to move the postcss config in a `.config` folder.
PostCSS itself still picks it up as one of the supported default location while Storybook is not affected by it
