### ISSUE TITLE
[Bug]: SB_CORE-SERVER_0002 torybook failed to load the following preset: ./.storybook/main.ts.

### ISSUE THREAD

**Issue by omarkhatibco** [storybookjs/storybook#28725]
### Describe the bug

Hi Everyone, I can not update to storybook v8.2, the last working version is v8.1.11 it's always complains about the same error.

here is my log

```bash
bun run build
$ storybook build --docs
storybook v8.2.6

info => Cleaning outputDir: storybook-static
info => Loading presets
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: /Users/userme/GitHub/repo/node_modules/@storybook/addon-console/dist/index.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module 'storybook/internal/preview-api'
Require stack:
- /Users/userme/GitHub/repo/node_modules/@storybook/preview-api/shim.js
- /Users/userme/GitHub/repo/node_modules/@storybook/addon-actions/dist/index.js
- /Users/userme/GitHub/repo/node_modules/@storybook/addon-console/dist/index.js
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/telemetry/index.cjs
- ./node_modules/storybook/dist/generate.cjs
- ./node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._resolveFilename (/Users/userme/GitHub/repo/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/userme/GitHub/repo/node_modules/@storybook/preview-api/shim.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)

More info:

    at loadPreset (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs:150276:13)

More info:

    at loadPreset (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs:150276:13)
    at async Promise.all (index 2)
    at async loadPresets (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs:150286:55)
    at async getPresets (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs:150319:11)
    at async buildStaticStandalone (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/core-server/index.cjs:255381:11)
    at async withTelemetry (/Users/userme/GitHub/repo/node_modules/@storybook/core/dist/core-server/index.cjs:255711:12)
    at async build (./node_modules/storybook/dist/generate.cjs:738:1337)
    at async Command.<anonymous> (./node_modules/storybook/dist/generate.cjs:741:145)
WARN   Failed to load preset: {"type":"presets","name":"/Users/userme/GitHub/repo/node_modules/@storybook/addon-console/dist/index.js"} on level 1
Error: Cannot find module 'storybook/internal/preview-api'
Require stack:
- /Users/userme/GitHub/reponode_modules/@storybook/preview-api/shim.js
- /Users/userme/GitHub/repo/node_modules/@storybook/addon-actions/dist/index.js
- /Users/userme/GitHub/repo/node_modules/@storybook/addon-console/dist/index.js
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/telemetry/index.cjs
- ./node_modules/storybook/dist/generate.cjs
- ./node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._resolveFilename (/Users/userme/GitHub/repo/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/userme/GitHub/repo/node_modules/@storybook/preview-api/shim.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
WARN   Failed to load preset: {"options":{"backgrounds":false},"type":"presets","name":"/Users/userme/GitHub/repo/node_modules/@storybook/addon-essentials/dist/index.js"} on level 1
Error: Cannot find module 'storybook/internal/node-logger'
Require stack:
- /Users/userme/GitHub/repo/node_modules/@storybook/addon-essentials/dist/index.js
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/common/index.cjs
- /Users/userme/GitHub/repo/node_modules/@storybook/core/dist/telemetry/index.cjs
- ./node_modules/storybook/dist/generate.cjs
- ./node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._resolveFilename (/Users/userme/GitHub/repo/node_modules/esbuild-register/dist/node.js:4799:36)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/userme/GitHub/repo/node_modules/@storybook/addon-essentials/dist/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
✔ Would you like to help improve Storybook by sending anonymous crash reports? … yes
error: script "build" exited with code 1
```

### Reproduction link

https://github.com/omarkhatibco/storybook-bug

### Reproduction steps

Run bun install and then either `bun dev` or `bun run build`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - ~/.local/state/fnm_multishells/87651_1722089979737/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.local/state/fnm_multishells/87651_1722089979737/bin/npm <----- active
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.72
    Safari: 17.5
  npmPackages:
    storybook: 8.2.6 => 8.2.6
```

### Additional context

I'm using bun as a package mamanger

**Comment by omarkhatibco** [comment]
I tried to switch to pnpm v9.6.0

I also got error for both dev and build, here is the log 


```bash
pn run build

> repo@ build /Users/omarkhatib/GitHub/storybook-bug
> turbo build --cache-dir=.turbo

• Packages in scope: storybook
• Running build in 1 packages
• Remote caching disabled
┌ storybook#build > cache miss, executing 89e733db1277728e
│
│ > storybook@0.0.0 build /Users/omarkhatib/GitHub/storybook-bug/apps/storybook
│ > storybook build --docs
│
│ storybook v8.2.6
│
│ info => Cleaning outputDir: storybook-static
│ info => Loading presets
│ info => Building manager..
│ info => Manager built (66 ms)
│ info => Building preview..
│ info Using tsconfig paths for react-docgen
│ vite v5.3.5 building for production...
│ ✓ 18 modules transformed.
│ x Build failed in 96ms
│ => Failed to build the preview
│ [vite]: Rollup failed to resolve import "storybook/internal/docs-tools" from "/Users/omarkhatib/GitHub/storybook-bug/node_modules/@storybook/react/dist/entry-preview-docs.mjs".
│ This is most likely unintended because it can break your application at runtime.
│ If you do want to externalize this module explicitly add it to
│ `build.rollupOptions.external`
│     at viteWarn (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.12_lightningcss@1.25.1/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65265:17)
│     at onwarn (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/@vitejs/plugin-react-swc/index.mjs:203:9)
│     at onRollupWarning (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.12_lightningcss@1.25.1/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65
│ 295:5)
│     at onwarn (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/vite@5.3.5_@types+node@20.14.12_lightningcss@1.25.1/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:64960:7)
│     at file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:18606:13
│     at Object.logger [as onLog] (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:20254:9)
│     at ModuleLoader.handleInvalidResolvedId (file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:19196:26)
│     at file:///Users/omarkhatib/GitHub/storybook-bug/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:19154:26
│ transforming (153) ../../node_modules/.pnpm/@storybook+blocks@8.2.6_react-dom@18.3.1_react@18.3.1__react@18.3.1_storybook@8.2.6_@babel+pr_neuokea5tjmhvdxasytuqhsoxa/node_modules/@storybook/block
│ transforming (230) ../../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/identity.js🐼 info [hrtime] Extracted in (5.04ms)
│ transforming (361) ../../node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/_getAllKeysIn.js
└────>
 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by shilman** [comment]
I was able to get your storybook running in pnpm by adding two missing dependencies:
- @vitejs/plugin-react-swc 
- @storybook/react

I'm not sure what's going on with bun.

**Comment by daaashley** [comment]
I spent a few weeks debugging this same error ('storybook/internal missing') message when upgrading from v7 to v8, so I thought I would share my scenario to maybe help others save time. If you've come across this page/error and already tried everything else, theres a chance your issue might be similar. In my case, I was using storybook in a turbo monorepo. In the monorepo root package.json I declared two npm workspaces 
```
"workspaces": [
    "apps/*",
    "packages/*"
  ],
```
my storybook application was located at 'apps/storybook'. If you are using an npm workspace, npm will create a copy of your workspace folder application under that applications package.json "name" key and place it in your root node_modules. If your packages.json "name" key is "storybook" (like it is in OP's linked repro project), then npm will copy your application into the root node_modules as 'storybook'. This creates a node_modules folder name conflict with the real 'storybook' dependency, and npm hoisting behavior can become unpredictable and move the actual storybook dependency to a different node_modules folder in your monorepo because it treats it as a different version--causing storybook internals not to be found. I'm not sure if this applies to yarn, pnpm, or bun, but this could be something to look at.

**Comment by shilman** [comment]
Would somebody be interested in adding a simple check for this in our CLI? Sounds like it would save some folks some pain when they upgrade?!

**Comment by tobiasdiez** [comment]
Since at least 4 days ago, we are experiencing a similar issue - but only on Windows and Node 20:
```
@storybook/core v8.6.8

info => Cleaning outputDir: storybook-static
info => Loading presets
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook-vue\nuxt\preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

ReferenceError: module is not defined
    at file:///D:/a/_temp/example/node_modules/.pnpm/@storybook-vue+nuxt@8.3.3_m_42e4855ad6d3147eebf72dcff17d7227/node_modules/@storybook-vue/nuxt/preset.js:1:1
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:387:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:323:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1371:24)
    at Module._compile (node:internal/modules/cjs/loader:1511:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1572:16)
    at Object.newLoader (.\node_modules\.pnpm\esbuild-register@3.6.0_esbuild@0.25.1\node_modules\esbuild-register\dist\node.js:2262:9)
    at extensions..js (.\node_modules\.pnpm\esbuild-register@3.6.0_esbuild@0.25.1\node_modules\esbuild-register\dist\node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)

More info: 

    at loadPreset (.\node_modules\.pnpm\@storybook+core@8.6.8_storybook@8.6.8\node_modules\@storybook\core\dist\common\index.cjs:16515:13)
```
https://github.com/nuxt-modules/storybook/actions/runs/14127429015/job/39579933083

A couple days ago, this was still working (without any changes on our end): https://github.com/nuxt-modules/storybook/actions/runs/14010606203/job/39229929907

(This particular CI run is an e2e test, so it always installs the latest version of all dependencies; so either something broke between storybook 8.6.8 and the 8.6.11; or its a problem triggered by a dependency update further down in the tree.)

**Comment by whdjh** [comment]
Hi @shilman, I'd like to work on this — specifically adding a CLI automigrate check
that warns users when their package.json "name" is "storybook", as you suggested.
Plan: add a new fix in `code/lib/cli-storybook/src/automigrate/fixes/` that detects
the naming conflict and shows a notification prompt.
