### ISSUE TITLE
[Bug]: `npx storybook@next init --skip-install` fails when no package manager can be detected

### ISSUE THREAD

**Issue by AdrianGonz97** [storybookjs/storybook#28818]
### Describe the bug

Issue started in `storybook@8.3.0-alpha.4`.

If the CLI is unable to detect a package manager (i.e. no lockfile and no `node_modules`), the following error gets thrown:

<details>
<summary>Error + Stacktrace</summary>

```bash
     Error: Cannot find @storybook/svelte/package.json, Error: Cannot find module '@storybook/svelte/package.json'
Require stack:
- /home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs
- /home/koala/.npm/_npx/8a8987c4af98d381/node_modules/storybook/core/cli/index.cjs
- /home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs
- /home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.resolve (node:internal/modules/helpers:190:19)
    at getRendererDir (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17796:15)
    at templatePath (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17905:19)
    at copyTemplateFiles (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17922:35)
    at async baseGenerator (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:56:766)
    at async generator14 (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:72:3170)
    at async installStorybook (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:84:5217)
    at async doInitiate (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:94:963)
    at async withTelemetry (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/core-server/index.cjs:99712:12)

TypeError: (0 , i_.default) is not a function
    at resolveUsingBranchInstall (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17787:114)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRendererDir (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17804:12)
    at async templatePath (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17905:13)
    at async copyTemplateFiles (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17922:29)
    at async baseGenerator (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:56:766)
    at async generator14 (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:72:3170)
    at async installStorybook (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:84:5217)
    at async doInitiate (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:94:963)
    at async withTelemetry (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/core-server/index.cjs:99712:12)
    at getRendererDir (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17808:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async templatePath (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17905:13)
    at async copyTemplateFiles (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/cli/index.cjs:17922:29)
    at async baseGenerator (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:56:766)
    at async generator14 (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:72:3170)
    at async installStorybook (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:84:5217)
    at async doInitiate (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:94:963)
    at async withTelemetry (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/@storybook/core/dist/core-server/index.cjs:99712:12)
    at async initiate (/home/koala/.npm/_npx/8a8987c4af98d381/node_modules/create-storybook/dist/bin/index.cjs:119:214)
```
</details>

### Reproduction link

https://github.com/AdrianGonz97/storybook-init-skip-install-reproduction

### Reproduction steps

1. Clone reproduction: `git clone https://github.com/AdrianGonz97/storybook-init-skip-install-reproduction`
2. cd into the project: `cd storybook-init-skip-install-reproduction`
3. Run: `npx storybook@next init --skip-install`

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.volta/tools/image/node/20.15.0/bin/node
    Yarn: 1.22.21 - ~/.volta/tools/image/yarn/1.22.21/bin/yarn
    npm: 10.7.0 - ~/.volta/tools/image/node/20.15.0/bin/npm <----- active
    pnpm: 9.5.0 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.207
```

**Comment by AdrianGonz97** [comment]
closing in favor of #28819
