### ISSUE TITLE
[Bug]: Using a project with PNPM and Vite cannot find 

### ISSUE THREAD

**Issue by eTech-Source** [storybookjs/storybook#28845]
### Describe the bug

When running `pnpx storybook dev` I get an error:
```
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/react-vite/preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module '@storybook/react-vite/preset'
Require stack:
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/telemetry/index.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/storybook@8.2.8_@babel+preset-env@7.25.3_@babel+core@7.25.2_/node_modules/storybook/dist/generate.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/storybook@8.2.8_@babel+preset-env@7.25.3_@babel+core@7.25.2_/node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._resolveFilename (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/esbuild-register@3.6.0_esbuild@0.21.5/node_modules/esbuild-register/dist/node.js:4794:36)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at interopRequireDefault (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:145609:11)
    at getContent (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:150235:10)
    at loadPreset (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:150241:51)

More info: 

    at loadPreset (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:150276:13)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.


    ~/git/etech-ui/apps/storybook/vite-react  on   2-create-etech-ui-utils ⇡10 !21 ?2 ────────────────────────────────────────── at 05:02:11 PM  
❯ pnpx storybook build
storybook v8.2.8

info => Cleaning outputDir: storybook-static
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
info => Loading presets
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: @storybook/react-vite/preset.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module '@storybook/react-vite/preset'
Require stack:
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/telemetry/index.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/storybook@8.2.8_@babel+preset-env@7.25.3_@babel+core@7.25.2_/node_modules/storybook/dist/generate.cjs
- /Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/storybook@8.2.8_@babel+preset-env@7.25.3_@babel+core@7.25.2_/node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._resolveFilename (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/esbuild-register@3.6.0_esbuild@0.21.5/node_modules/esbuild-register/dist/node.js:4794:36)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at require (node:internal/modules/helpers:123:16)
    at interopRequireDefault (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:145609:11)
    at getContent (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:150235:10)
    at loadPreset (/Users/ekrich/Library/Caches/pnpm/dlx/fstaswuptgmqoc2ie5unfomv7m/1912f4ffac9-14d0d/node_modules/.pnpm/@storybook+core@8.2.8/node_modules/@storybook/core/dist/common/index.cjs:150241:51)
```

### Reproduction link

https://github.com/eTech-Source/sb-repro

### Reproduction steps

1. Clone the repo
2. Run `pnpm install`
3. Run `pnpx storybook dev`

You should get the above error.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.6
    CPU: (12) arm64 Apple M2 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.5.1/bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Safari: 17.6
  npmPackages:
    @storybook/addon-essentials: 8.2.8 => 8.2.8 
    @storybook/addon-interactions: 8.2.8 => 8.2.8 
    @storybook/builder-vite: 8.2.8 => 8.2.8 
    @storybook/core-server: 8.2.8 => 8.2.8 
    @storybook/react: ^8.2.8 => 8.2.8 
    @storybook/react-vite: 8.2.8 => 8.2.8 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    storybook: 8.2.8 => 8.2.8
```

### Additional context

This issue was originally found in NX project. However, it is still reproducible without NX. This error only occurs with pnpm and the latest SB version.

**Comment by guidari** [comment]
I'm having the exact same issue. Did you manage to solve it @eTech-Source ?

**Comment by guenyoobaywa** [comment]
I also have this problem.

**Comment by elisehein** [comment]
Using Node 20 doesn't make a difference to me.

`pnpm i --shamefully-flatten` gets rid of the error, but is not a desirable solution.

`public-hoist-pattern[]=@storybook/*` in the root `.npmrc` seems to work though!

**Comment by HHogg** [comment]
https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments

This worked for me.

**Comment by ndelangen** [comment]
Hi,

Thanks for the report, and thanks to everyone who shared workarounds in this thread.

**What's going on**

This error usually happens when Storybook is run via `pnpx storybook dev` (dlx cache) while `@storybook/react-vite` lives in the project's own `node_modules`. Storybook 8.x's CJS preset loader couldn't resolve the framework preset through pnpm's strict dependency layout:

```
Error: Cannot find module '@storybook/react-vite/preset'
```

Several workarounds in this thread still apply today: hoisting patterns like `public-hoist-pattern[]=@storybook/*`, or the [FAQ guidance for module resolution](https://storybook.js.org/docs/faq#how-do-i-fix-module-resolution-in-special-environments). Running Storybook from a local install (`pnpm storybook dev`) instead of `pnpx` also helps.

**Where we're headed**

Storybook 10's ESM migration ([#31787](https://github.com/storybookjs/storybook/issues/31787)) removed the old CJS preset loader and improved module resolution paths. That may help some pnpm setups, but pnpm monorepos and strict hoisting can still be tricky, and we're not treating this as fully resolved.

We have planned work around modern preset loading to address remaining pnpm and monorepo resolution pain more directly. I have not retried this specific reproduction on Storybook 10.5+ at this time.

We're leaving this issue open to track that remaining friction.

**In the meantime**

- Prefer `pnpm storybook dev` from a locally installed `storybook` package
- See the FAQ link above for pnpm/NX monorepo setups

If you can still reproduce on Storybook 10.5+ with a **local** install (not dlx), please comment here with your setup. That helps us prioritize the modern preset loading work.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).
