### ISSUE TITLE
[Bug]: Storybook fails to launch whith `NODE_OPTIONS=--experimental-strip-types`

### ISSUE THREAD

**Issue by silverwind** [storybookjs/storybook#28880]
### Describe the bug

Storybook fails to launch when `NODE_OPTIONS=--experimental-strip-types` is present in the environment. Remove the variable makes it work.

```
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

Original error:
Error [ERR_REQUIRE_ESM]: require() of ES Module /.storybook/main.ts from /node_modules/@storybook/core/dist/common/index.cjs not supported.
Instead change the require of main.ts in /node_modules/@storybook/core/dist/common/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at interopRequireDefault (/node_modules/@storybook/core/dist/common/index.cjs:145609:11)
    at serverRequire (/node_modules/@storybook/core/dist/common/index.cjs:145623:14)
    at loadMainConfig (/node_modules/@storybook/core/dist/common/index.cjs:151297:18)
    at loadMainConfig (./node_modules/@storybook/core/dist/common/index.cjs:151315:11)
    at async buildDevStandalone (./node_modules/@storybook/core/dist/core-server/index.cjs:256949:11)
    at async withTelemetry (./node_modules/@storybook/core/dist/core-server/index.cjs:255711:12)
    at async dev (./node_modules/storybook/dist/generate.cjs:738:506)
    at async Command.<anonymous> (./node_modules/storybook/dist/generate.cjs:740:245)
```

### Reproduction link

https://github.com/silverwind/storybook-node-strip

### Reproduction steps

1. Have Node.js 22.6.0 or higher installed
2. Clone repo
3. Run `npm run storybook`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm <----- active
    pnpm: 9.7.0 - ~/.npm-global/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
  npmPackages:
    @storybook/addon-essentials: 8.2.9 => 8.2.9
    @storybook/addon-interactions: 8.2.9 => 8.2.9
    @storybook/addon-links: 8.2.9 => 8.2.9
    @storybook/addon-onboarding: 8.2.9 => 8.2.9
    @storybook/blocks: 8.2.9 => 8.2.9
    @storybook/react: 8.2.9 => 8.2.9
    @storybook/react-vite: 8.2.9 => 8.2.9
    @storybook/test: 8.2.9 => 8.2.9
    eslint-plugin-storybook: 0.8.0 => 0.8.0
    storybook: 8.2.9 => 8.2.9
```

**Comment by ndelangen** [comment]
Hi,

Thanks for the report and for the minimal reproduction repo.

**What was going wrong**

With `NODE_OPTIONS=--experimental-strip-types` set, Node treats TypeScript files as native ESM. Storybook 8.x still evaluated `.storybook/main.ts` through a CJS-first pipeline (`@storybook/core/dist/common/index.cjs`, `require()`, `interopRequireDefault`). That produced:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .storybook/main.ts from .../index.cjs not supported.
```

Removing `NODE_OPTIONS=--experimental-strip-types` worked around it because Storybook fell back to its own esbuild-based transform path. But if you want Node to run TypeScript natively globally, the CJS loader was the blocker.

Same general class of bug as [storybookjs/storybook#30195](https://github.com/storybookjs/storybook/issues/30195) (CJS config loading vs ESM `main.ts`).

**What changed**

This was addressed as part of Storybook's ESM migration:

- Storybook 10 is ESM-only. Config files load via native `import()` instead of the old CJS loader ([#31787](https://github.com/storybookjs/storybook/issues/31787), [10.0.0 release notes](https://github.com/storybookjs/storybook/releases/tag/v10.0.0)).
- CJS bundles were removed in [#31819](https://github.com/storybookjs/storybook/pull/31819) (merged August 2025, shipped in 10.0.0).

**Closing**

We're closing this issue. The reproduction ([silverwind/storybook-node-strip](https://github.com/silverwind/storybook-node-strip)) targets Storybook 8.2.9 with the old CJS distribution, which no longer reflects current behavior.

I have not retried reproducing this at this time. Based on the error mechanism and the ESM migration above, we believe this is resolved in Storybook 10+.

If you're still hitting this on Storybook 10.5+ with `NODE_OPTIONS=--experimental-strip-types` set, please open a new issue with a minimal reproduction and we'll take another look.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).
