### ISSUE TITLE
[Bug]: `better-opn` is bundled and therefore `openChrome.applescript` is missing.

### ISSUE THREAD

**Issue by clintandrewhall** [storybookjs/storybook#29123]
### Describe the bug

As titled.  Setting `OPEN_MATCH_HOST_ONLY` has no effect, as `better-opn` always fails.

Logging the error within `better-opn`:

```
e Error: Command failed: osascript ../openChrome.applescript "http://localhost:6006/" "http://localhost:6006" "Google Chrome"
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at startBrowserProcess (/Users/clint/Projects/clintandrewhall.com/node_modules/@storybook/core/dist/core-server/index.cjs:42243:51)
    at m8.exports (/Users/clint/Projects/clintandrewhall.com/node_modules/@storybook/core/dist/core-server/index.cjs:42272:16)
    at /Users/clint/Projects/clintandrewhall.com/node_modules/@storybook/core/dist/core-server/index.cjs:47275:107
    at W6.exports (/Users/clint/Projects/clintandrewhall.com/node_modules/@storybook/core/dist/core-server/index.cjs:41908:122) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 48538,
  stdout: null,
  stderr: null
}
```

Script missing from `../`:

<img width="424" alt="Screenshot 2024-09-13 at 12 18 17 PM" src="https://github.com/user-attachments/assets/fbb191d9-2e84-4d98-9000-1f090efebec9">

## Fix

Placing `openChrome.applescript` in the root of `core-server` fixes the issue.  But I doubt this is what you'd want to do.

### Reproduction link

https://storybook.js.org

### Reproduction steps

1. Setup `storybook` launch script with `cross-env` in `package.json`:

`"storybook": "cross-env BROWSER=\"google chrome\" OPEN_MATCH_HOST_ONLY=true storybook dev -p 6006"`

2. Run `yarn storybook` - browser tab is not reused.

Fix:

1. Paste [`openChrome.applescript`](https://raw.githubusercontent.com/michaellzc/better-opn/master/openChrome.applescript) to `node_modules/@storybook/core/dist/openChrome.applescript`
2. Run `yarn storybook` - browser tab is reused.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 4.4.1 - ~/.nvm/versions/node/v20.12.2/bin/yarn <----- active
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.5
  npmPackages:
    @storybook/addon-essentials: ^8.2.8 => 8.3.0
    @storybook/addon-interactions: ^8.2.8 => 8.3.0
    @storybook/addon-links: ^8.2.8 => 8.3.0
    @storybook/blocks: ^8.2.8 => 8.3.0
    @storybook/react: ^8.2.8 => 8.3.0
    @storybook/react-vite: ^8.2.8 => 8.3.0
    @storybook/test: ^8.2.8 => 8.3.0
    chromatic: ^11.8.0 => 11.10.0
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.2.8 => 8.3.0
    storybook-addon-remix-react-router: ^3.0.0 => 3.0.0
```

**Comment by clintandrewhall** [comment]
Confirmed: patching the package fixes the issue.

`.yarn/patches/@storybook-core-npm-8.3.0-833013f32e.patch`:

```
diff --git a/dist/openChrome.applescript b/dist/openChrome.applescript
deleted file mode 100644
index 5b1390749e3ada541f57aa8647f5819a484678a9..0000000000000000000000000000000000000000
--- a/dist/openChrome.applescript
+++ /dev/null
@@ -1,94 +0,0 @@
-(*
-Copyright (c) 2015-present, Facebook, Inc.
-This source code is licensed under the MIT license found in the
-LICENSE file in the root directory of this source tree.
-*)
-
-property targetTab: null
-property targetTabIndex: -1
-property targetWindow: null
-property theProgram: "Google Chrome"
-
-on run argv
-  set theURL to item 1 of argv
-  set matchURL to item 2 of argv
-
-  -- Allow requested program to be optional,
-  -- default to Google Chrome
-  if (count of argv) > 2 then
-    set theProgram to item 3 of argv
-  end if
-
-  using terms from application "Google Chrome"
-    tell application theProgram
-
-      if (count every window) = 0 then
-        make new window
-      end if
-
-      -- 1: Looking for tab running debugger
-      -- then, Reload debugging tab if found
-      -- then return
-      set found to my lookupTabWithUrl(matchURL)
-      if found then
-        set targetWindow's active tab index to targetTabIndex
-        tell targetTab to reload
-        tell targetWindow to activate
-        set index of targetWindow to 1
-        return
-      end if
-
-      -- 2: Looking for Empty tab
-      -- In case debugging tab was not found
-      -- We try to find an empty tab instead
-      set found to my lookupTabWithUrl("chrome://newtab/")
-      if found then
-        set targetWindow's active tab index to targetTabIndex
-        set URL of targetTab to theURL
-        tell targetWindow to activate
-        return
-      end if
-
-      -- 3: Create new tab
-      -- both debugging and empty tab were not found
-      -- make a new tab with url
-      tell window 1
-        activate
-        make new tab with properties {URL:theURL}
-      end tell
-    end tell
-  end using terms from
-end run
-
--- Function:
--- Lookup tab with given url
--- if found, store tab, index, and window in properties
--- (properties were declared on top of file)
-on lookupTabWithUrl(lookupUrl)
-  using terms from application "Google Chrome"
-    tell application theProgram
-      -- Find a tab with the given url
-      set found to false
-      set theTabIndex to -1
-      repeat with theWindow in every window
-        set theTabIndex to 0
-        repeat with theTab in every tab of theWindow
-          set theTabIndex to theTabIndex + 1
-          if (theTab's URL as string) contains lookupUrl then
-            -- assign tab, tab index, and window to properties
-            set targetTab to theTab
-            set targetTabIndex to theTabIndex
-            set targetWindow to theWindow
-            set found to true
-            exit repeat
-          end if
-        end repeat
-
-        if found then
-          exit repeat
-        end if
-      end repeat
-    end tell
-  end using terms from
-  return found
-end lookupTabWithUrl
\ No newline at end of file
```
