### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'navigator') on node with globals

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#29314]
### Describe the bug

I have a project containing both server and client code.
So I want to run tests also in `node`.

When I run `vitest`, I get `Cannot read properties of undefined (reading 'navigator')` error:

```sh
TypeError: Cannot read properties of undefined (reading 'navigator')
 ❯ resetClipboardStubOnView node_modules/.pnpm/@storybook+test@8.3.5_storybook@8.3.5/node_modules/@storybook/test/dist/index.mjs:178:7052
 ❯ node_modules/.pnpm/@storybook+test@8.3.5_storybook@8.3.5/node_modules/@storybook/test/dist/index.mjs:178:8238
```

This occurs when I set `test.globals: true` in `vite.config.ts`.

### Reproduction link

https://github.com/cyberuni/sb-test-nav

### Reproduction steps

run `pnpm test`

### System

npx storybook@latest info

Storybook Environment Info:

  System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.local/state/fnm_multishells/74613_1728508612022/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.8.3 - ~/.local/state/fnm_multishells/74613_1728508612022/bin/npm <----- active
    pnpm: 8.15.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 18.0
  npmPackages:
    @storybook/addon-essentials: ^8.3.5 => 8.3.5 
    @storybook/addon-interactions: ^8.3.5 => 8.3.5 
    @storybook/addon-links: ^8.3.5 => 8.3.5 
    @storybook/addon-onboarding: ^8.3.5 => 8.3.5 
    @storybook/blocks: ^8.3.5 => 8.3.5 
    @storybook/react: ^8.3.5 => 8.3.5 
    @storybook/react-vite: ^8.3.5 => 8.3.5 
    @storybook/test: ^8.3.5 => 8.3.5 
    eslint-plugin-storybook: ^0.9.0 => 0.9.0 
    storybook: ^8.3.5 => 8.3.5 

### Additional context

The `@storybook/test` is probably doing some work at load time which is not ideal.

It should avoid that or at least check for `window?...`

**Comment by Siddhant-Kashyap** [comment]
want to work on this @unional ,please assign it to me

**Comment by shilman** [comment]
@Siddhant-Kashyap No need to assign. If you make a PR we'd be happy to review

**Comment by unional** [comment]
I didn't solve it. I'm working on https://github.com/repobuddy/storybook-addon-vis which I actually recommend setting `global` to `false`

**Comment by CHC383** [comment]
Maybe related to https://github.com/vitest-dev/vitest/issues/6187?

**Comment by tillypick** [comment]
@shilman Is there an update on this issue?

**Comment by mikevoets** [comment]
We're seeing this as well. Here's the stacktrace:

```
info => Loading presets
SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./.storybook/main.ts.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

SB_CORE-SERVER_0002 (CriticalPresetLoadError): Storybook failed to load the following preset: ./node_modules/@storybook/addon-docs/dist/blocks.js.

Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

TypeError: Cannot read properties of undefined (reading 'navigator')
    at qo (./node_modules/storybook/dist/components/index.cjs:9691:13)
    at ./node_modules/storybook/dist/components/index.cjs:9739:11
    at ./node_modules/storybook/dist/components/index.cjs:8:36
    at Object.<anonymous> (./node_modules/storybook/dist/components/index.cjs:20005:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at node:internal/modules/cjs/loader:1689:10
    at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (./node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)

More info: 

    at loadPreset (./node_modules/storybook/dist/common/index.cjs:23615:13)

More info: 

    at loadPreset (./node_modules/storybook/dist/common/index.cjs:23615:13)
    at async Promise.all (index 2)
    at async loadPresets (./node_modules/storybook/dist/common/index.cjs:23625:55)
    at async getPresets (./node_modules/storybook/dist/common/index.cjs:23658:11)
    at async buildStaticStandalone (./node_modules/storybook/dist/core-server/index.cjs:39688:11)
    at async withTelemetry (./node_modules/storybook/dist/core-server/index.cjs:42279:12)
    at async build (./node_modules/storybook/dist/cli/bin/index.cjs:5849:3)
    at async r.<anonymous> (./node_modules/storybook/dist/cli/bin/index.cjs:6036:7)
  Failed to load preset: {"type":"presets","name":"/home/runner/work/foo/node_modules/@storybook/addon-docs/dist/blocks.js"} on level 1
TypeError: Cannot read properties of undefined (reading 'navigator')
    at qo (./node_modules/storybook/dist/components/index.cjs:9691:13)
    at ./node_modules/storybook/dist/components/index.cjs:9739:11
    at ./node_modules/storybook/dist/components/index.cjs:8:36
    at Object.<anonymous> (./node_modules/storybook/dist/components/index.cjs:20005:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at node:internal/modules/cjs/loader:1689:10
    at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
    at extensions..js (./node_modules/esbuild-register/dist/node.js:4833:24)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
```

**Comment by ndelangen** [comment]
Hi,

Thanks for the report, the reproduction repo, and thanks to everyone who added context over the life of this thread.

**What was going wrong**

The original report was `Cannot read properties of undefined (reading 'navigator')` when running Vitest in a Node environment with `test.globals: true`. `@storybook/test` appeared to do browser-oriented work at module load time instead of guarding for a non-browser environment.

A later report in this thread showed a related failure mode during Storybook startup: `@storybook/addon-docs/dist/blocks.js` was being loaded as a preset in Node, which pulled in browser UI code (`storybook/dist/components/index.cjs`) that also accessed `navigator` at import time. That looks like a browser entry point getting evaluated on the Node preset-loading path, made worse by Storybook 8.x's CJS-first loader (`index.cjs`, `esbuild-register`).

**What changed**

A lot has changed since Storybook 8.3.x:

- Storybook 10 is ESM-only ([#31787](https://github.com/storybookjs/storybook/issues/31787), [10.0.0 release notes](https://github.com/storybookjs/storybook/releases/tag/v10.0.0)). Presets and config load via native `import()` instead of the old CJS pipeline ([#31819](https://github.com/storybookjs/storybook/pull/31819)).
- Addon and package boundaries were reworked (including docs/blocks and test utilities), which should reduce browser code being pulled into Node-side preset loading.

We believe this class of problem is resolved in Storybook 10+, but we have not re-verified every scenario from this thread (Vitest Node globals, shared mocks, addon-docs blocks as preset).

**Closing**

We're closing this issue based on the architectural changes above. If you're still hitting `navigator` errors on Storybook 10.5+ — whether in Vitest Node tests or during preset loading — please **re-open this issue** (or file a new one) with a minimal reproduction and your Storybook/Vitest/Node versions.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).
