### ISSUE TITLE
[Bug]: Investigate Next.js v15 features

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#29421]
### Describe the bug

Next.js 15 is now stable.

### Reproduction link

-

### System

-

**Comment by terrymun** [comment]
@valentinpalkovic Thanks for looking into this! I have personally been experimenting with next@15 with storybook (using webpack under the hood), and the only major issue I'm running into is the invalid paths that `@storybook/nextjs` tries to use when accessing server-related internals on next.js.

If this sounds familiar to you, that's because I've opened a related issue #29380 some days ago... but I've had time to fully try to debug the issue today and finally found the root cause + create a reproducible example for you to work with.

Apologies in advance if I end up hijacking/derailing the purpose of this ticket, feel free to remove this comment so the issue stays on track 👍

**Comment by valentinpalkovic** [comment]
Hi @terrymun 

Thank you very much for providing this detailed information! We will take a look as soon as we are able to work on this issue.

**Comment by DrewLandgraveCbsi** [comment]
For the Next15 release. It looks like the next/dist/client/components/headers file was moved to next/headers

**Comment by tiavina-mika** [comment]
I also encountered this issue with Next.js 15 and Storybook/Next.js. I hope it gets resolved quickly.

![Image](https://github.com/user-attachments/assets/ca8239ad-781c-4556-a2a9-d67c95c6c8e2)

**Comment by bmuenzenmeyer** [comment]
I tried created a minimal reproduction to start exploring this compatibility, but until official [`^15.0.0` support](https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/package.json#L179) lands, resolution errors prevent a clean install. Of course we could override, but I'm using this as a clear indicator to wait until maintainers can help.

cc https://github.com/nodejs/nodejs.org/pull/7155

**Comment by yannbf** [comment]
Hey everyone! Next.js 15 support has landed in Storybook [v8.4.3](https://github.com/storybookjs/storybook/releases/tag/v8.4.3) as well as Storybook [v8.5.0-alpha.4](https://github.com/storybookjs/storybook/releases/tag/v8.5.0-alpha.4). Please give it a try and provide us feedback <3

We will do more investigations about the other topics mentioned in this issue, but you should be able to use Next.js 15 with Storybook now!

**Comment by terrymun** [comment]
@yannbf Can confirm this is working great for us :)

**Comment by zigang93** [comment]
does `next.config.ts` work out of box? if no, what's workaround

**Comment by dmitrc** [comment]
> does `next.config.ts` work out of box? if no, what's workaround

In `.storybook/main.ts`:

```js
framework: {
    name: "@storybook/nextjs",
    options: {
      nextConfigPath: path.resolve(__dirname, "../next.config.ts"),
    },
  },
```

**Comment by kamilgrzegorczyk** [comment]
We have an issue that when using `next.config.ts` - if that file contains any relative imports these are not resolved properly and the build process fails.

```
info => Using implicit CSS loaders
=> Failed to build the preview
Error: Cannot find module './common/constants.mjs'
Require stack:
- /Users/someUser/project/next/bnd/next.config.compiled.js
- ./node_modules/next/dist/build/next-config-ts/transpile-config.js
- ./node_modules/next/dist/server/config.js
- ./node_modules/@storybook/nextjs/dist/preset.js
- ./node_modules/@storybook/core/dist/common/index.cjs
- ./node_modules/storybook/dist/proxy.cjs
- ./node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._resolveFilename (./node_modules/esbuild-register/dist/node.js:4794:36)
    at ./node_modules/next/dist/server/require-hook.js:55:36
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at mod.require (./node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/someUser/project/next/bnd/next.config.compiled.js:14:58)
```

This is not something we can affect by changing the tsconfig of the storybook nor using WebpackFinal as that happens before webpack is firing

Is anyone having any insight about it? Thank you

**Comment by oskari** [comment]
> > [@yannbf](https://github.com/yannbf) Can confirm this is working great for us :)
> 
> Are you using App Router? If yes, how are you handling async params when rendering a page with MSW? It renders non-stop.
> 
> Tried a bunch of things to prevent it from re-render without luck 😕

Did you find any solution? Having same issue

**Comment by trappar** [comment]
> > [@yannbf](https://github.com/yannbf) Can confirm this is working great for us :)
> 
> Are you using App Router? If yes, how are you handling async params when rendering a page with MSW? It renders non-stop.

Also seeing this among other issues after trying to upgrade https://github.com/storybookjs/storybook-rsc-demo to Next 15.3.1 / Storybook 9.0.0-beta.10

**Comment by RicardoAvans** [comment]
> `next/image` is also an issue.
> 
> This is our setup, worked great prior to next.js upgrade
> 
> import type {Meta, StoryObj} from '@storybook/react'
> import Image from 'next/image'
> 
> export function CustomImage({src, alt}: {src: string; alt: string}) {
>   return <Image src={src} alt={alt} width={200} height={200} />
> }
> 
> // More on how to set up stories at: https://storybook.js.org/docs/writing-stories#default-export
> const meta = {
>   title: 'Examples/Image',
>   component: CustomImage,
>   parameters: {
>     // Optional parameter to center the component in the Canvas. More info: https://storybook.js.org/docs/configure/story-layout
>     // layout: 'centered',
>   },
>   // This component will have an automatically generated Autodocs entry: https://storybook.js.org/docs/writing-docs/autodocs
>   // tags: ['autodocs'],
>   // More on argTypes: https://storybook.js.org/docs/api/argtypes
>   // argTypes: {
>   //   backgroundColor: {control: 'color'},
>   // },
>   // Use `fn` to spy on the onClick arg, which will appear in the actions panel once invoked: https://storybook.js.org/docs/essentials/actions#action-args
>   // args: {onClick: fn()},
> } satisfies Meta<typeof CustomImage>
> 
> export default meta
> type Story = StoryObj<typeof meta>
> 
> // More on writing stories with args: https://storybook.js.org/docs/writing-stories/args
> export const Primary: Story = {
>   args: {
>     src: 'https://png.pngtree.com/element_our/20190530/ourmid/pngtree-correct-icon-image_1267804.jpg',
>     alt: 'Image',
>   },
> }
> <img alt="Image" width="931" src="https://private-user-images.githubusercontent.com/186006228/420504078-a21f89ac-4fc9-40ed-be27-dfdd15b35cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc5MjEzMjIsIm5iZiI6MTc0NzkyMTAyMiwicGF0aCI6Ii8xODYwMDYyMjgvNDIwNTA0MDc4LWEyMWY4OWFjLTRmYzktNDBlZC1iZTI3LWRmZGQxNWIzNWNiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMlQxMzM3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTYyMWU5MDIyOGM1MzNhNGUyMDNjMWUzYjllYjlhM2JiNDFmZjgwZTUyNWYwZmViZTE5OTM1YzE3YTIzOWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E4xC8UnUBPkfSim40paqzFDe-ZOwvlgxBITasHDMfIY">

Any updates on this? I'm encountering the same problem when using next/image
