### ISSUE TITLE
Angular - Assertion failed: Unsupported workflow in Yarn projects

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#29689]
### Describe the bug

When installing Storybook for angular in Yarn projects, users will face the following error:

```ts
➤ YN0000: · Yarn 4.2.1
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @thednp/shorty@https://github.com/thednp/shorty.git#commit=1453fc6b7c9d7df1f8854146921082175dbc99a5: Assertion failed: Unsupported workflow
    at /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:189:1611
    at async Tn.mktempPromise (/Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:9:44849)
    at async /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:186:56
    at async Tn.mktempPromise (/Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:9:44849)
    at async /Users/username/Dev/project/.yarn/releases/yarn-4.2.1.cjs:181:3066
➤ YN0000: └ Completed in 2s 435ms
➤ YN0000: · Failed with errors in 2s 441ms
```

That is due to this issue:
https://github.com/thednp/position-observer/issues/1

It happens because there is a chain of dependencies as part of compodoc, which end up hitting that package.
```
@compodoc/compodoc -> bootstrap.native -> @thednp/shorty -> @thednp/position-observer
```

### How to fix it
This issue can only be fixed by its maintainer, so for now you can work around it by adding a package resolution to your package.json:
```
{
  "resolutions": {
    "@thednp/shorty": "2.0.7"
  },
}
```

**Comment by yannbf** [comment]
This issue has been resolved!
