### ISSUE TITLE
[Bug]: Running Storybook with vite v6.0.0

### ISSUE THREAD

**Issue by omarihab99** [storybookjs/storybook#29719]
### Describe the bug

Hi,
I tried running `npx storybook@latest init` after `npm create vite@latest` (using react + typescript) . I got the following from storybook.log:

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: storybook-vitev6@0.0.0
npm error Found: vite@6.0.0
npm error node_modules/vite
npm error   dev vite@"^6.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^4.0.0 || ^5.0.0" from @storybook/react-vite@8.4.5
npm error node_modules/@storybook/react-vite
npm error   dev @storybook/react-vite@"^8.4.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/omarihab/.npm/_logs/2024-11-26T20_17_48_529Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/omarihab/.npm/_logs/2024-11-26T20_17_48_529Z-debug-0.log

### Reproduction link

https://github.com/omarihab99/storybook-vitev6

### Reproduction steps

- `npm create vite@latest`. using react + ts template.
- `npm install`
- `npx storybook@latest init`

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.2/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.2/bin/npm <----- active
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
```

**Comment by hobadams** [comment]
Bump this. I know vite 6 is VERY new but this would be a cool add.

**Comment by yannbf** [comment]
Hey everyone, we appreciate the report! As you know Vite 6 was released yesterday, but we already have code to support it prepared for our upcoming release. However, the ecosystem is still catching up (given Vite 6 was just released), so it's not a straightforward release. Support is coming really soon 🤞

**Comment by rothsandro** [comment]
`@storybook/react-vite@8.5.0` supports Vite v6 as peer dependency. Is there still something missing or is Vite v6 now officially supported?

**Comment by todor-a** [comment]
Hey, any update here? It's still failing with:

```
10:10:14 AM [vite] (client) warning: Failed to resolve "\u0000/virtual:/@storybook/builder-vite/storybook-stories.js" from /virtual:/@storybook/builder-vite/vite-app.js. An id should be written. Did you pass a URL?
  Plugin: vite:import-analysis
  File: /virtual:/@storybook/builder-vite/vite-app.js:32:30
  30 |      
  31 |      if (import.meta.hot) {
  32 |        import.meta.hot.accept('/virtual:/@storybook/builder-vite/storybook-stories.js', (newModule) => {
     |                               ^
  33 |        // importFn has changed so we need to patch the new one in
  34 |        window.__STORYBOOK_PREVIEW__.onStoriesChanged({ importFn: newModule.importFn });
10:10:15 AM [vite] (client) Pre-transform error: [sass] [sass] spawn EBADF
  Plugin: vite:css
10:10:15 AM [vite] Internal server error: [sass] [sass] [sass] spawn EBADF
  Plugin: vite:css
      at ChildProcess.spawn (node:internal/child_process:420:11)
      at spawn (node:child_process:762:9)
      at AsyncCompiler.<instance_members_initializer> (~/project/node_modules/sass-embedded/lib/src/compiler/async.ts:39:35)
      at new AsyncCompiler (~/project/node_modules/sass-embedded/lib/src/compiler/async.ts:147:3)
      at Object.initAsyncCompiler (~/project/node_modules/sass-embedded/lib/src/compiler/async.ts:199:10)
      at Object.run (file://~/project/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:49687:32)
      at async process (file://~/project/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:49788:24)
      at async compileCSSPreprocessors (file://~/project/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:48851:28)
      at async compileCSS (file://~/project/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:48898:32)
      at async TransformPluginContext.transform (file://~/project/node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js:48271:11)
```

Versions:
- vite: 6.1.0
- @storybook/addon-actions: 8.5.3
- @storybook/addon-designs: 8.1.0
- @storybook/addon-docs: 8.5.3
- @storybook/addon-essentials: 8.5.3
- @storybook/addon-interactions: 8.5.3
- @storybook/addon-links: 8.5.3
- @storybook/addon-storysource: 8.5.3
- @storybook/blocks: 8.5.3
- @storybook/builder-vite: 8.5.3
- @storybook/node-logger: 8.5.3
- @storybook/react: 8.5.3
- @storybook/react-vite: 8.5.3
- @storybook/test: 8.5.3
- @storybook/test-runner: 0.21.0

**Comment by vanessayuenn** [comment]
Vite 6 should be supported! Can @todor-a or anyone provide a reproduction please?

**Comment by vanessayuenn** [comment]
Vite 6 should be supported by now, so i will be closing this issue. If you encounter any compatibility issue with vite 6, please open a new bug report of the specific issue along with a repro. Thank you!
