### ISSUE TITLE
[Bug]: [addon-docs] MDX stories not working at all

### ISSUE THREAD

**Issue by ayZagen** [storybookjs/storybook#30016]
### Describe the bug

I tried the code example in [code/addons/docs/vue3/README.md#mdx](https://github.com/storybookjs/storybook/blob/next/code/addons/docs/vue3/README.md#mdx) but it does not work at all.

I tried with both `8.4.7` and `8.5.0-alpha.20` both versions fails. Also without creating `mdx` file (which does not throw the error) `Docs` tab is not shown at all.

Following error is thrown:
```
Unable to index ./src/stories/Test.stories.mdx:
WARN   Error: Invariant failed: No matching indexer found for /home/projects/llqiwrnnox.github/src/stories/Test.stories.mdx
WARN     at invariant (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34558:11)
WARN     at Si.extractStories (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34758:5)
WARN     at eval (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34703:53)
WARN     at eval (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34679:30)
WARN     at eval (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34676:26)
WARN     at Si.updateExtracted (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34668:23)
WARN     at Si.ensureExtracted (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34702:16)
WARN     at Si.initialize (/home/projects/llqiwrnnox.github/node_modules/@storybook/core/dist/core-server/index.cjs:34663:16)
```

### Reproduction link

https://stackblitz.com/edit/github-tyj2nvxh?file=src%2Fstories%2FTest.stories.mdx

### Reproduction steps

- add `addon-docs` addon
- create an mdx file like in example

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.local/share/mise/installs/node/22.12.0/bin/node
    npm: 10.9.0 - ~/.local/share/mise/installs/node/22.12.0/bin/npm
    pnpm: 9.15.0 - ~/.local/share/mise/installs/node/22.12.0/bin/pnpm <----- active
  npmPackages:
    @storybook/addon-docs: ^8.4.7 => 8.4.7 
    @storybook/addon-essentials: ^8.4.7 => 8.4.7 
    @storybook/addon-interactions: ^8.4.7 => 8.4.7 
    @storybook/addon-onboarding: ^8.4.7 => 8.4.7 
    @storybook/blocks: ^8.4.7 => 8.4.7 
    @storybook/test: ^8.4.7 => 8.4.7 
    @storybook/vue3: ^8.4.7 => 8.4.7 
    @storybook/vue3-vite: ^8.4.7 => 8.4.7 
    storybook: ^8.4.7 => 8.4.7
```

**Comment by shilman** [comment]
This is a documentation bug. MDX stories was removed in 8.0

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropping-support-for-storiesmdx-csf-in-mdx-format-and-mdx1-support

I'll remove those old docs to avoid confusion.

**Comment by andreieftimie** [comment]
So is MDX out completely? 

I do get the error as well: 

```
 Unable to index ./docs/Community/CodeOfConduct/Communication.stories.mdx:
  Error: Invariant failed: No matching indexer found for
```

When trying to load any `*.mdx` file as a story. 

The docs mention that this should work https://storybook.js.org/docs/writing-docs/mdx#working-with-standalone-documentation-pages

> [Working with standalone documentation pages](https://storybook.js.org/docs/writing-docs/mdx#working-with-standalone-documentation-pages)
Writing standalone documentation pages is a common use case that applies not only on a per-component but also on a per-project basis. For example, you might want to document your project's onboarding process with instructions on using it. To do so, you can create a new MDX file containing your documentation using a similar structure and content:

**Comment by tgelu** [comment]
> This is a documentation bug. MDX stories was removed in 8.0
> 
> https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#dropping-support-for-storiesmdx-csf-in-mdx-format-and-mdx1-support
> 
> I'll remove those old docs to avoid confusion.

experiencing the same issue with storbyook v7

**Comment by 1andee** [comment]
@andreieftimie I also encountered this error in v9.1 and managed to resolve by removing `.stories.` from the filename.

The standalone page _should_ load if renamed from `Communication.stories.mdx` → `Communication.mdx`, assuming the pattern in your StorybookConfig can match the path.

**Comment by jonniebigodes** [comment]
Closing this as documentation is updated and we're no longer supporting this format since the 8.0
