### ISSUE TITLE
[Bug]: Storybook couldn't evaluate your .storybook/main.ts file

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#30115]
### Describe the bug

Error message:

```
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.
             Original error:
             Error: Transform failed with 1 error:
             (define name):1:0: ERROR: Expected identifier but found "import"
```

`esbuild` released a new version recently, containing a [bug](https://github.com/evanw/esbuild/issues/4010), affecting all Vite-based Storybooks.

### Workaround

Pin the version of `esbuild` to the latest known working version, `0.24.0` (npm, pnpm):
```jsonc
// package.json
{
  "overrides": {
    "esbuild": "0.24.0"
  }
}
```

Use `resolutions` field in `yarn` projects:

```jsonc
// package.json
{
  "resolutions": {
    "esbuild": "0.24.0"
  }
}
```

**Comment by valentinpalkovic** [comment]
Related esbuild bug: https://github.com/evanw/esbuild/issues/4010
fix: https://github.com/evanw/esbuild/pull/4013

**Comment by patak-dev** [comment]
vite@6.0.5 is out pinning to esbuild 0.24.0 until this is fixed in esbuild, you can update to vite instead of doing the override

**Comment by yannbf** [comment]
This issue has been (esbuild downgraded) fixed in 8.5.0-beta.4 and will be fixed in 8.4.8, follow the release PR here: https://github.com/storybookjs/storybook/pull/29834

**Comment by yannbf** [comment]
Update, the maintainer of esbuild made a fix and will release a new version soon, so all you'll have to do is update your yarn lock once that happens.

**Comment by jmuzina** [comment]
Esbuild 0.24.2 has released and seems to have fixed this issue for me - update your lockfiles and you should be fine :)

**Comment by BretPehrsonWTW** [comment]
Confirm that updating Esbuild from 0.24.1 to 0.24.2 fixed it for me.

**Comment by ugokoli** [comment]
I am still getting this same error after upgrading.

```
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

Original error:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at matchFromAbsolutePaths (/.yarn/__virtual__/esbuild-register-virtual-8fdb41b5c7/0/cache/esbuild-register-npm-3.6.0-72017fa8ae-9221e26dde.zip/node_modules/esbuild-register/dist/node.js:2821:27)
    at /.yarn/__virtual__/esbuild-register-virtual-8fdb41b5c7/0/cache/esbuild-register-npm-3.6.0-72017fa8ae-9221e26dde.zip/node_modules/esbuild-register/dist/node.js:2809:14
    at Module._resolveFilename (/.yarn/__virtual__/esbuild-register-virtual-8fdb41b5c7/0/cache/esbuild-register-npm-3.6.0-72017fa8ae-9221e26dde.zip/node_modules/esbuild-register/dist/node.js:4788:21)
    at require (node:internal/modules/esm/translators:197:30)
    at interopRequireDefault (/.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/common/index.cjs:11666:11)
    at serverRequire (/.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/common/index.cjs:11680:14)
    at loadMainConfig (/.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/common/index.cjs:17493:18)
    at async buildDevStandalone (/.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/core-server/index.cjs:37134:11)
    at async withTelemetry (/.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
    at loadMainConfig (./.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/common/index.cjs:17511:11)
    at async buildDevStandalone (./.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/core-server/index.cjs:37134:11)
    at async withTelemetry (./.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/core-server/index.cjs:35757:12)
    at async dev (./.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/cli/bin/index.cjs:2591:3)
    at async s.<anonymous> (./.yarn/__virtual__/@storybook-core-virtual-3267528e49/0/cache/@storybook-core-npm-8.4.7-69e17b4cab-969cde2203.zip/node_modules/@storybook/core/dist/cli/bin/index.cjs:2643:74)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by georgibakken** [comment]
I experienced the error still after upgrading, but that was with node version `22.13.1`. If I use version `22.11` or `22.2` it works

**Comment by ajnozari** [comment]
I'm getting this issue on node 23 as well

**Comment by PsVenom** [comment]
I'm getting the same issue in Node 24.0.2. esbuild version is 0.25.9
I'm very new to webdev in general, so please excuse my naivety

**Comment by zlargon** [comment]
My teammate ran into the same issue, but only on his Windows machine. He's using Node 22.18.0, pnpm 10.14.0, storybook 9.1.3, and esbuild 0.25.9.
