### ISSUE TITLE
[Bug]: Missing "./vite" specifier in "@testing-library/svelte" package

### ISSUE THREAD

**Issue by tobiasdiez** [storybookjs/storybook#30150]
### Describe the bug

When running `yarn start` on the next branch:

```
🥾 Bootstrapping
> npx nx run-many -t build --parallel=15
An error occurred while executing: `npx nx run-many -t build --parallel=15`
❌ Failed to bootstrap

Error running task compile for react-vite/default-ts:
{
  "shortMessage": "Command failed with exit code 1: npx nx run-many -t build --parallel=15",
  "command": "npx nx run-many -t build --parallel=15",
  "escapedCommand": "\"npx nx run-many -t build --parallel=15\"",
  "exitCode": 1,
  "stdout": "\r\n NX   Unable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin. \r\n\r\n\r\n\t Inner Error: Error: Build failed with 1 error:\r\nnode_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing \"./vite\" specifier in \"@testing-library/svelte\" package\r\n    at failureErrorWithLog (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1472:15)\r\n    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:945:25\r\n    at runOnEndCallbacks (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1315:45)\r\n    at buildResponseToResult (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:943:7)\r\n    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:970:16\r\n    at responseCallbacks.<computed> (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:622:9)\r\n    at handleIncomingPacket (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:677:12)\r\n    at Socket.readFromStdout (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:600:7)\r\n    at Socket.emit (node:events:513:28)\r\n    at addChunk (node:internal/streams/readable:559:12)\r\n",
  "stderr": "X [ERROR] Missing \"./vite\" specifier in \"@testing-library/svelte\" package [plugin externalize-deps]\n\n    node_modules/esbuild/lib/main.js:1225:27:\n      1225 │         let result = await callback({\n           ╵                            ^\n\n    at e (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:25)\n    at n (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:627)\n    at o (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:1297)\n    at resolveExportsOrImports (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28746:20)\n    at resolveDeepImport (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28765:31)\n    at tryNodeResolve (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)\n    at resolveByViteResolver (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66224:32)\n    at file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66265:40\n    at requestCallbacks.on-resolve (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1225:28)\n    at handleRequest (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:647:17)\n\n  This error came from the \"onResolve\" callback registered here:\n\n    node_modules/esbuild/lib/main.js:1150:20:\n      1150 │       let promise = setup({\n           ╵                     ^\n\n    at setup (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66250:27)\n    at handlePlugins (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1150:21)\n    at buildOrContextImpl (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:873:5)\n    at Object.buildOrContext (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:699:5)\n    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:2024:15\n    at new Promise (<anonymous>)\n    at Object.build (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:2023:25)\n    at build (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1874:51)\n    at bundleConfigFile (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66201:26)\n\n  The plugin \"externalize-deps\" was triggered by this import\n\n    renderers/svelte/vitest.config.ts:10:13:\n      10 │       import('@testing-library/svelte/vite').then(({ svelteTesting...\n         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n\u001b[33mThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\u001b[39m\n\u001b[31mfailed to load config from D:\\Programming\\storybook\\code\\renderers\\svelte\\vitest.config.ts\u001b[39m\nUnable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin. \n\n\t Inner Error: Error: Build failed with 1 error:\nnode_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing \"./vite\" specifier in \"@testing-library/svelte\" package\n    at failureErrorWithLog (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1472:15)\n    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:945:25\n    at runOnEndCallbacks (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1315:45)\n    at buildResponseToResult (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:943:7)\n    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:970:16\n    at responseCallbacks.<computed> (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:622:9)\n    at handleIncomingPacket (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:677:12)\n    at Socket.readFromStdout (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:600:7)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:559:12)",
  "failed": true,
  "timedOut": false,
  "isCanceled": false,
  "killed": false
}

Error: Command failed with exit code 1: npx nx run-many -t build --parallel=15
X [ERROR] Missing "./vite" specifier in "@testing-library/svelte" package [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1225:27:
      1225 │         let result = await callback({
           ╵                            ^

    at e (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:25)
    at n (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:627)
    at o (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:1297)
    at resolveExportsOrImports (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28746:20)
    at resolveDeepImport (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28765:31)
    at tryNodeResolve (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)
    at resolveByViteResolver (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66224:32)
    at file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66265:40
    at requestCallbacks.on-resolve (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1225:28)
    at handleRequest (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:647:17)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66250:27)
    at handlePlugins (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:699:5)
    at D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:2024:15
    at new Promise (<anonymous>)
    at Object.build (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:2023:25)
    at build (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1874:51)
    at bundleConfigFile (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66201:26)

  The plugin "externalize-deps" was triggered by this import

    renderers/svelte/vitest.config.ts:10:13:
      10 │       import('@testing-library/svelte/vite').then(({ svelteTesting...
         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from D:\Programming\storybook\code\renderers\svelte\vitest.config.ts
Unable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin.

         Inner Error: Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing "./vite" specifier in "@testing-library/svelte" package
    at failureErrorWithLog (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1472:15)
    at D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1315:45)
    at buildResponseToResult (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:943:7)
    at D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:559:12)

 NX   Unable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin.


         Inner Error: Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing "./vite" specifier in "@testing-library/svelte" package
    at failureErrorWithLog (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1472:15)
    at D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:945:25
    at runOnEndCallbacks (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:1315:45)
    at buildResponseToResult (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:943:7)
    at D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:970:16
    at responseCallbacks.<computed> (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (D:\Programming\storybook\code\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:559:12)

    at makeError (D:\Programming\storybook\scripts\node_modules\execa\lib\error.js:59:13)
    at handlePromise (D:\Programming\storybook\scripts\node_modules\execa\index.js:119:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async exec (D:\Programming\storybook\scripts\utils\exec.ts:43:7)
    at async runTask (D:\Programming\storybook\scripts\task.ts:319:24)
    at async run (D:\Programming\storybook\scripts\task.ts:489:28) {
  shortMessage: 'Command failed with exit code 1: npx nx run-many -t build --parallel=15',
  command: 'npx nx run-many -t build --parallel=15',
  escapedCommand: '"npx nx run-many -t build --parallel=15"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\r\n' +
    ' NX   Unable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin. \r\n' +
    '\r\n' +
    '\r\n' +
    '\t Inner Error: Error: Build failed with 1 error:\r\n' +
    'node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing "./vite" specifier in "@testing-library/svelte" package\r\n' +
    '    at failureErrorWithLog (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1472:15)\r\n' +
    '    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:945:25\r\n' +
    '    at runOnEndCallbacks (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1315:45)\r\n' +
    '    at buildResponseToResult (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:943:7)\r\n' +
    '    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:970:16\r\n' +
    '    at responseCallbacks.<computed> (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:622:9)\r\n' +
    '    at handleIncomingPacket (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:677:12)\r\n' +
    '    at Socket.readFromStdout (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:600:7)\r\n' +
    '    at Socket.emit (node:events:513:28)\r\n' +
    '    at addChunk (node:internal/streams/readable:559:12)\r\n',
  stderr: 'X [ERROR] Missing "./vite" specifier in "@testing-library/svelte" package [plugin externalize-deps]\n' +
    '\n' +
    '    node_modules/esbuild/lib/main.js:1225:27:\n' +
    '      1225 │         let result = await callback({\n' +
    '           ╵                            ^\n' +
    '\n' +
    '    at e (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:25)\n' +
    '    at n (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:627)\n' +
    '    at o (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:21445:1297)\n' +
    '    at resolveExportsOrImports (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28746:20)\n' +
    '    at resolveDeepImport (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28765:31)\n' +
    '    at tryNodeResolve (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:28453:20)\n' +
    '    at resolveByViteResolver (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66224:32)\n' +
    '    at file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66265:40\n' +
    '    at requestCallbacks.on-resolve (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1225:28)\n' +
    '    at handleRequest (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:647:17)\n' +
    '\n' +
    '  This error came from the "onResolve" callback registered here:\n' +
    '\n' +
    '    node_modules/esbuild/lib/main.js:1150:20:\n' +
    '      1150 │       let promise = setup({\n' +
    '           ╵                     ^\n' +
    '\n' +
    '    at setup (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66250:27)\n' +
    '    at handlePlugins (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1150:21)\n' +
    '    at buildOrContextImpl (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:873:5)\n' +
    '    at Object.buildOrContext (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:699:5)\n' +
    '    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:2024:15\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.build (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:2023:25)\n' +
    '    at build (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1874:51)\n' +
    '    at bundleConfigFile (file:///D:/Programming/storybook/code/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66201:26)\n' +
    '\n' +
    '  The plugin "externalize-deps" was triggered by this import\n' +
    '\n' +
    '    renderers/svelte/vitest.config.ts:10:13:\n' +
    "      10 │       import('@testing-library/svelte/vite').then(({ svelteTesting...\n" +
    '         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n' +
    '\n' +
    "\x1B[33mThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\x1B[39m\n" +
    '\x1B[31mfailed to load config from D:\\Programming\\storybook\\code\\renderers\\svelte\\vitest.config.ts\x1B[39m\n' +
    'Unable to create nodes for renderers/svelte/vitest.config.ts using plugin @nx/vite/plugin. \n' +
    '\n' +
    '\t Inner Error: Error: Build failed with 1 error:\n' +
    'node_modules/esbuild/lib/main.js:1225:27: ERROR: [plugin: externalize-deps] Missing "./vite" specifier in "@testing-library/svelte" package\n' +
    '    at failureErrorWithLog (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1472:15)\n' +
    '    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:945:25\n' +
    '    at runOnEndCallbacks (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:1315:45)\n' +
    '    at buildResponseToResult (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:943:7)\n' +
    '    at D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:970:16\n' +
    '    at responseCallbacks.<computed> (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:622:9)\n' +
    '    at handleIncomingPacket (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:677:12)\n' +
    '    at Socket.readFromStdout (D:\\Programming\\storybook\\code\\node_modules\\esbuild\\lib\\main.js:600:7)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:559:12)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Reproduction link

next branch

### System

```bash
Windows
```

**Comment by Al38andr0** [comment]
If it can help, I had the same issue, first locally, then on GHA, during my upgrade to Svelte 5.
In both cases, there was a cache issue. Deleting the node_modules fixed it locally, but in my pipeline, where I cache my dependencies, it raised a misconfiguration. Making the cache specific for every pipeline solved the issue.

**Comment by ndelangen** [comment]
Hi,

Thanks for the report, and thanks for the cache-related note in the thread.

**What was going wrong**

Bootstrapping the Storybook monorepo on Windows (`yarn start` / `nx run-many -t build`) could fail during NX project graph creation. In this case, loading `renderers/svelte/vitest.config.ts` hit a Vite/NX resolution error (`Missing "./vite" specifier in "@testing-library/svelte" package`), alongside the deprecated Vite CJS Node API path.

At the time, native Windows development builds in the monorepo were not reliably supported, and we often pointed contributors toward WSL2.

**What changed**

This was addressed as part of Storybook's ESM migration and ongoing monorepo tooling updates:

- Storybook 10 is ESM-only ([#31787](https://github.com/storybookjs/storybook/issues/31787), [10.0.0 release notes](https://github.com/storybookjs/storybook/releases/tag/v10.0.0)).
- Build and task scripts run via native Node with TypeScript support instead of the old `esbuild-register` loader path.
- We now compile Storybook packages on Windows daily in CI. The scheduled **daily** workflow on CircleCI includes a **`Build (windows)`** job that runs `yarn task compile` in the `code/` directory: https://app.circleci.com/pipelines/github/storybookjs/storybook/128110/workflows/e78f073c-0867-4acf-9c06-80e7590bb39c

**Closing**

We're closing this issue. The original report targeted an older monorepo bootstrap path on Windows that no longer reflects current behavior.

I haven't personally verified a fresh native Windows checkout with `yarn start` on my machine, but the underlying build-tooling causes described here were addressed in the ESM migration and are covered by our daily Windows CI builds above.

If you're still unable to bootstrap the monorepo on a current `next` checkout with Node 22+, please open a new issue with your exact command output and environment info.

For upgrade help, see [Migration from 9.x to 10.0.0](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-9x-to-1000).
