### ISSUE TITLE
Support dynamic imports for non CRA-apps without explicit configuration

### ISSUE THREAD

**Issue by dburles** [storybookjs/storybook#5792]
Storybook 4+ appears to no longer support dynamic imports out of the box. I think it makes reasonable sense to enable this feature by default. I've created a [simple reproduction](https://github.com/dburles/storybook-dynamic-import-issue). Running storybook will result in a build error.

```
ERROR in ./src/components/CounterButton.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/dave/Projects/storybook-dynamic-import-issue/src/components/CounterButton.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled (10:1):

   8 | }
   9 | 
> 10 | import('../math').then(math => {
     | ^
  11 |   console.log(math.add(16, 26));
  12 | });
  13 | 

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.
    at Object.raise (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3831:17)
    at Object.expectPlugin (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5148:18)
    at Object.parseExprAtom (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6129:14)
    at Object.parseExprAtom (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3552:20)
    at Object.parseExprSubscripts (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5862:23)
    at Object.parseMaybeUnary (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5842:21)
    at Object.parseExprOps (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5729:23)
    at Object.parseMaybeConditional (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5702:23)
    at Object.parseMaybeAssign (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5647:21)
    at Object.parseMaybeAssign (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2621:18)
    at Object.parseExpression (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5595:23)
    at Object.parseStatementContent (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7378:23)
    at Object.parseStatement (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7243:17)
    at Object.parseStatement (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:1977:26)
    at Object.parseBlockOrModuleBlockBody (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7810:25)
    at Object.parseBlockBody (/Users/dave/Projects/storybook-dynamic-import-issue/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7797:10)
 @ ./stories/index.stories.js 6:0-60 24:29-42
 @ ./stories sync .stories.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true
```

**Comment by shilman** [comment]
@dburles To confirm, you're upgrading from SB3?

**Comment by dburles** [comment]
Yep, 3 has no issues

**Comment by ndelangen** [comment]
I'm on it

**Comment by ndelangen** [comment]
I'm not able to reproduce on `5.1.0-rc.4` (next) branch

**Comment by ndelangen** [comment]
I just verified that using an externally installed project, `5.1.0-rc.4`has this feature
