### ISSUE TITLE
Error on PropTypes.shape()

### ISSUE THREAD

**Issue by 1Jesper1** [storybookjs/storybook#6617]
Using "@storybook/react": "4.0.4",

Using:

```
static propTypes = {
		style: PropTypes.shape(),
	}
```
crashes on `return originalKeys(object);` in _es5-shim_ package.

**Comment by 1Jesper1** [comment]
```
 TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Function.keys (http://localhost:9001/static/iframe.bundle.js:42468:24)
    at Shape.render (http://localhost:9001/static/iframe.bundle.js:18793:39)
    at finishClassComponent (http://localhost:9001/static/iframe.bundle.js:155929:31)
    at updateClassComponent (http://localhost:9001/static/iframe.bundle.js:155884:24)
    at beginWork (http://localhost:9001/static/iframe.bundle.js:156832:16)
    at performUnitOfWork (http://localhost:9001/static/iframe.bundle.js:160500:12)
    at workLoop (http://localhost:9001/static/iframe.bundle.js:160540:24)
    at renderRoot (http://localhost:9001/static/iframe.bundle.js:160623:7)
    at performWorkOnRoot (http://localhost:9001/static/iframe.bundle.js:161530:7)
```

I think the problem is in Storybook Shape.js class: `Object.keys(propTypes).map(function`

**Comment by Armanio** [comment]
Hmm, could you share a code snippet? I'll try to fix it.

**Comment by 1Jesper1** [comment]
@Armanio 

```
static propTypes = {
		style: PropTypes.shape(),
	}
```
Using PropTypes.share() in proptypes in a React class.

**Comment by 1Jesper1** [comment]
@Armanio Is the code snippet above enough for you to reproduce the problem?
