### ISSUE TITLE
Storyshots failing for node >v10.15.3

### ISSUE THREAD

**Issue by iMarv** [storybookjs/storybook#6724]
**Describe the bug**
Storyshots plugin fails for node version higher than v10.15.3

**To Reproduce**
- Add storyshot plugin
- Install accordingly with wrapper-file calling `initStoryshots`
- Run Jest

**Expected behavior**
No errors

**Code snippets**
```
 FAIL  src/tests.story.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'get' of undefined

    > 1 | import initStoryshots from '@storybook/addon-storyshots';
        | ^
      2 | 
      3 | initStoryshots();
      4 | 

      at _interopRequireWildcard (node_modules/@storybook/addon-storyshots/dist/api/index.js:22:331)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/index.js:8:15)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:52:35)
      at Object.<anonymous> (src/tests.story.spec.js:1:1)

```

**System:**
 - Framework: Angular
 - Addons: Storyshots
 - Version: latest
 - NodeJS: >v10.15.3

**Comment by iMarv** [comment]
Would be really nice to have this rather sooner than later as angular 8 now requires node >12

**Comment by ThorWithoutTheH** [comment]
Having similar issues even with node version 10.15.1,I think there is a deeper issue than node versioning here.
