### ISSUE TITLE
Addon-docs: hot module replacement throws error

### ISSUE THREAD

**Issue by glappsi** [storybookjs/storybook#6738]
**Describe the bug**
I am using storybook for angular. Since I installed the addon-docs and created my first mdx file, the hot moddule replacement crashes with following error
```
Unhandled Promise rejection: Manifest request to b3fa85f7c6693e1eaa33.hot-update.json timed out. ; Zone: <root> ; Task: Promise.then ; Value: Error: Manifest request to b3fa85f7c6693e1eaa33.hot-update.json timed out.
at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (runtime~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:91)
    at XMLHttpRequest.wrapFn (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:208211)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:207302)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:207074)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:207377)
    at invokeTask (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:208623)
    at XMLHttpRequest.globalZoneAwareCallback (vendors~main.b3fa85f7c6693e1eaa33.bundle.js:sourcemap:208649) Error: Manifest request to b3fa85f7c6693e1eaa33.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (http://localhost:6006/runtime~main.b3fa85f7c6693e1eaa33.bundle.js:91:16)
    at XMLHttpRequest.wrapFn (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:208211:39)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:207302:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:207074:47)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:207377:34)
    at invokeTask (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:208623:14)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:6006/vendors~main.b3fa85f7c6693e1eaa33.bundle.js:208649:17)
```

**To Reproduce**
1. Set up storybook for angular
2. Install and configure addon-docs
3. Create mdx

**Expected behavior**
Hot module replacement should work.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
 - Browser: chrome
 - Framework: angular
 - Addons: docs
 - Version: 5.2.0-alpha.3

**Comment by shilman** [comment]
@glappsi Sorry I missed this one. Are you still seeing this issue on the latest beta?

**Comment by rijkvanzanten** [comment]
Hi @shilman, I'm encountering this issue on `5.3.3` using `mdx` + `vue` files for stories.

**Comment by shilman** [comment]
@rijkvanzanten this exact error? i thought zone-xxx was an angular thing..

**Comment by rijkvanzanten** [comment]
Hmm, same symptom caused by something else 

```
runtime~main.c914f7f22c1adf320e20.bundle.js:sourcemap:92 Uncaught (in promise) Error: Manifest request to c914f7f22c1adf320e20.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (runtime~main.c914f7f22c1adf320e20.bundle.js:sourcemap:92)
request.onreadystatechange @ runtime~main.c914f7f22c1adf320e20.bundle.js:sourcemap:92
Promise.then (async)
check @ vendors~main.c914f7f22c1adf320e20.bundle.js:sourcemap:195524
push../node_modules/webpack-hot-middleware/process-update.js.module.exports @ vendors~main.c914f7f22c1adf320e20.bundle.js:sourcemap:195486
processMessage @ vendors~main.c914f7f22c1adf320e20.bundle.js:sourcemap:195379
handleMessage @ vendors~main.c914f7f22c1adf320e20.bundle.js:sourcemap:195239
handleMessage @ vendors~main.c914f7f22c1adf320e20.bundle.js:sourcemap:195202
```

**Comment by rijkvanzanten** [comment]
It starts happening to me as soon as I have more than 1 `<Story>` component inside a `<Preview>` component. 

Works:

```
<Preview mdxSource={`<v-icon name="person" color="--blue-grey" />`}>
	<Story name='intro' height='40px'>{{
	components: { VIcon },
	template: '<v-icon name="person" color="--blue-grey" />',
	}}</Story>
</Preview>
```

Causes the error:

```
<Preview mdxSource={`
<v-icon name="star" color="--light-blue" sup />
<v-icon name="accessibility_new" color="--red" x-small />
<v-icon name="warning" color="--purple" small />
<v-icon name="gesture" color="--blue" />
<v-icon name="security" color="--green" large />
<v-icon name="person" color="--orange" x-large />
`}>
	<Story name="sup" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="star" color="--light-blue" sup />`
		}}
	</Story>
	<Story name="x-small" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="accessibility_new" color="--red" x-small />`
		}}
	</Story>
	<Story name="small" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="warning" color="--purple" small />`
		}}
	</Story>
	<Story name="default" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="gesture" color="--blue" />`
		}}
	</Story>
	<Story name="large" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="security" color="--green" large />`
		}}
	</Story>
	<Story name="x-large" height="60px">
		{{
			components: { VIcon },
			template: `<v-icon name="person" color="--orange" x-large />`
		}}
	</Story>
</Preview>
```

**Comment by rijkvanzanten** [comment]
Scratch that, I'm seeing it without multiple items per preview now too. Maybe it's caused by the total item of <Story> elements.. ?

**Comment by shilman** [comment]
@rijkvanzanten Are you using inline story rendering for vue, or iframes?

**Comment by rijkvanzanten** [comment]
I tried both, doesn't seem to make a difference

**Comment by shilman** [comment]
@rijkvanzanten I tried adding your example to our `vue-kitchen-sink` and could not repro. Can you check your setup?

https://github.com/storybookjs/storybook/commit/ee29dbaf0aaf01a95f94bc88a6f9e6276653acaf

**Comment by rijkvanzanten** [comment]
This is happening for me in a pretty big project. Let me try to delete everything but the storybook story so you have an accurate reproduction 👍

**Comment by tommyc38** [comment]
I get this error all the time and now the only way I can fix it is by restarting the server which is really painful.  I did notice that it seems to happen with particular stories.  Once those stories are introduced, everytime there is an update I get a similar hot update error message.  Below is a snapshot of my deps that might be helpful.

```
    "@angular/core": "^8.2.14",
    "@storybook/addon-actions": "5.3.5",
    "@storybook/addon-centered": "5.3.5",
    "@storybook/addon-docs": "5.3.5",
    "@storybook/addon-knobs": "5.3.5",
    "@storybook/addon-links": "5.3.5",
    "@storybook/addon-notes": "5.3.5",
    "@storybook/addon-storysource": "5.3.5",
    "@storybook/addon-viewport": "5.3.5",
    "@storybook/addons": "5.3.5",
    "@storybook/angular": "5.3.5",
    "@storybook/react": "5.3.5",
    "@storybook/source-loader": "5.3.5",

```

**Comment by shilman** [comment]
@tommyc38 do you have a repro I can look at?

**Comment by maxigimenez** [comment]
Same error on angular too

![image (1)](https://user-images.githubusercontent.com/1178139/77305755-e6505380-6cf6-11ea-8cb0-e9798c2b66ff.png)

**Comment by shilman** [comment]
@maxigimenez do you have a repro repo?

**Comment by maxigimenez** [comment]
> @maxigimenez do you have a repro repo?

Sadly no, is a private repository. I will try to set-up a new one!

**Comment by ChazUK** [comment]
This is also happening for me, will see if I can reproduce it, but it seems to happen when I have around 5 stories in MDX docs
