### ISSUE TITLE
React Native Storyshots - RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by nigelsim** [storybookjs/storybook#6902]
**Describe the bug**
When running `storyshots` the following error occurs. Running the storybook within the app on the device works as expected:
```
 FAIL  ./storyshots.test.ts
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded
        at Function.get [Symbol.species] (<anonymous>)
        at Array.slice (<anonymous>)

      at Resolver.resolveStubModuleName (node_modules/jest-resolve/build/index.js:375:49)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:75)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
      at Symbol (node_modules/core-js/modules/es.symbol.description.js:25:106)
```
**To Reproduce**
1. Setup React Native Story book and test
2. Add `@storybook/addon-storyshots`
3. Setup `storyshots.test.ts` as per README
4. Run `yarn test`

**Expected behavior**
Snapshots to be generated

**Code snippets**
storybook/index.ts
```typescript
import { getStorybookUI, configure } from '@storybook/react-native';
import { loadStories } from './storyLoader';


configure(() => {
  loadStories()
}, module);

configure(loadStories, module);
// Refer to https://github.com/storybooks/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI
const StorybookUIRoot = getStorybookUI({});

export default StorybookUIRoot;
```
storyshots.test.ts
```typescript
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots();
```

button.stories.ts
```typescript
import { Button } from './Button';
import { storiesOf } from '@storybook/react-native';

storiesOf('Button', module)
    .add('Default', () => (<Button title='My Button' color='#fafafa' onPress={null}></Button>
    ));
```

**System:**
 - OS: Linux
 - Device: NA
 - Browser: NA
 - Framework: React Native 0.57.8
 - Addons: @storybook/addon-storyshots
 - Version: 5.1.0-rc.2

**Comment by jamsch** [comment]
We use Storybook at our business and are having the same exception after upgrading to 5.1.3

We are using it as a component inside our live app which is conditionally bundled based on environment variables. Our minimal repro is the following:

```js
// StorybookComponent.js
import { getStorybookUI } from "@storybook/react-native";
const StorybookUIRoot = getStorybookUI({ port: 7007, onDeviceUI: true });
export default StorybookUIRoot;
```

This, however does work

```js
// StorybookComponent.js
import { View } from "react-native";
export default View;
```

The stack trace isn't so helpful either.

![Screenshot_1559869099](https://user-images.githubusercontent.com/12927717/59075301-fa6fc380-8923-11e9-8883-38cbadad9b7f.png)

**Comment by nigelsim** [comment]
This is still an issue with React Native 0.59.9 and Storybook 5.1.3

**Comment by insidewhy** [comment]
Getting the same thing here, did you guys give up on storyshot or did you find a fix?

**Comment by kyle-ssg** [comment]
I find that this is an issue when passing an element as a prop, otherwise, it works fine.

```
 const icon = <Text>Hi</Text>;
            return (
                <ListItem icon={icon}>
                    <View>
                        <Text style={Styles.listItemTitle}>
                            Button
                        </Text>
                        <Text style={Styles.listItemText}>
                            Text
                        </Text>
                    </View>
                    <ION style={Styles.listIcon} name="ios-arrow-forward"/>
                </ListItem>
            )
```

**Comment by ENT108** [comment]
It's still an issue :/
