### ISSUE TITLE
Syntax error on Windows when trying to debug

### ISSUE THREAD

**Issue by mihaisavezi** [storybookjs/storybook#6980]
**Describe the bug**
trying to debug via ```node --inspect node_modules/.bin/storybook-start -p 9001``` on windows, throws this

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**To Reproduce**
1. Install a basic storybook example on a windows machine.
2. Run the command ```node --inspect node_modules/.bin/storybook-start -p 9001``` to try and debug your storybook application.

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
 - OS: Windows 7
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: [e.g. chrome, safari]
 - Framework: [e.g. react, vue, angular]
 - Addons: [if relevant]
 - Version: 5.0.0 rc. 8

**Additional context**

**Comment by mihaisavezi** [comment]
Also, it would help to have some documentation to debug the storybook command that starts the live server locally

**Comment by lonyele** [comment]
I have a same problem. After I type `yarn test` and select anything such as `Core & Examples`, I get
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
```

It is happening at Windows 10. On Ubuntu, It works fine. Maybe because of some commands that are only working at linux system?
