### ISSUE TITLE
Storybook v5 breaks when using Storybook Info Addon

### ISSUE THREAD

**Issue by chandanaswal18** [storybookjs/storybook#7021]
**Describe the bug**
I am trying to implement Storybook Info Addon and it is breaking the storybook. All other addons are working fine, only in case of info addon it's breaking.

**Code snippets**

**Config.js**

```
import { configure, setAddon, addDecorator } from '@storybook/react';
import JSXAddon from 'storybook-addon-jsx';
import { withInfo } from '@storybook/addon-info';
import '../frontend/styles/v2/app.scss';

addDecorator(withInfo);
setAddon(JSXAddon);

const req = require.context('../frontend/modules/stories', true, /\.jsx?$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}
configure(loadStories, module);
```

**Story.button.jsx**

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';

import Button from '../components/buttons/button';

const styles = {
  textAlign: 'center',
  marginTop: 200,
};
const CenterDecorator = storyFn => <div style={styles}>{storyFn()}</div>;

storiesOf('Button', module)
  .addDecorator(CenterDecorator)
  .add(
    'Button',
    () => <Button buttonClass="button-default" value="Button Default" onClick={action('button-default-click')} />,
    { info: '☹️ no emojis' },
    {
      notes: 'This button is default button of Project ',
    },
  );
```

**webpack.config.js**
```
module.exports = {
  resolve: {
    extensions: ['.js', '.jsx', '.css', '.scss'],
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: ['babel-loader'],
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
      },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' },
      {
        test: /\.(pdf|gif|svg)$/,
        use: 'file-loader?name=[path][name].[ext]',
      },
      {
        test: /\.(json|txt|csv)$/i,
        loader: 'raw-loader',
      },
    ],
  },
};
```

**Package.json library versions I am using**
```
    "@storybook/react": "^5.1.3",
    "storybook-addon-jsx": "^7.1.2",
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-info": "^5.1.3",
    "@storybook/addon-notes": "^5.1.3",
    "core-js": "^3.1.3", 
```

i have installed core-js to resolve issue https://github.com/storybookjs/storybook/issues/6204.

**Error**

```
ERROR in ./node_modules/nested-object-assign/package.json
Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:461:32)
    at runLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:343:12)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at process.nextTick (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/nested-object-assign/index.js 1:10-35
 @ ./node_modules/@storybook/addon-info/dist/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

ERROR in ./node_modules/character-entities-legacy/index.json
Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:461:32)
    at runLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:343:12)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./node_modules/parse-entities/index.js 3:13-49
 @ ./node_modules/refractor/core.js
 @ ./node_modules/react-syntax-highlighter/prism-light.js
 @ ./node_modules/@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.js
 @ ./node_modules/@storybook/components/dist/index.js
 @ ./node_modules/@storybook/addon-info/dist/components/markdown/code.js
 @ ./node_modules/@storybook/addon-info/dist/components/markdown/index.js
 @ ./node_modules/@storybook/addon-info/dist/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

ERROR in ./node_modules/character-reference-invalid/index.json
Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n ...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:461:32)
    at runLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/webpack/lib/NormalModule.js:343:12)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/chandanaswal/My_Data/Workspace/phai_web/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 @ ./node_modules/parse-entities/index.js 4:14-52
 @ ./node_modules/refractor/core.js
 @ ./node_modules/react-syntax-highlighter/prism-light.js
 @ ./node_modules/@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.js
 @ ./node_modules/@storybook/components/dist/index.js
 @ ./node_modules/@storybook/addon-info/dist/components/markdown/code.js
 @ ./node_modules/@storybook/addon-info/dist/components/markdown/index.js
 @ ./node_modules/@storybook/addon-info/dist/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
Child HtmlWebpackCompiler:
                          Asset     Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  559 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/core/node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/@storybook/core/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {HtmlWebpackPlugin_0} [built]
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.69 KiB {HtmlWebpackPlugin_0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {HtmlWebpackPlugin_0} [built]

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

```

**System:**
 - OS: [ MacOS]
 - Browser: [ chrome, safari]
 - Framework: [react]
 - Addons: [info addon]
 - Version: ["@storybook/react": "^5.1.3",]

**Additional context**
Earlier I was getting issue https://github.com/storybookjs/storybook/issues/6204.
Was able to fix by manually installing latest npm i core-js -D.

**Comment by ndelangen** [comment]
We indeed use `nested-object-assign` in addon-info, but your stack trace seems to have the package.json file imported from that module, that is then unloadable by node.

Very very confusing..

Could you please remove all node_modules and lockfiles and re-install? Before i start debugging further, I'd like to eliminate the issues isn't a corrupt node_modules / lockfile situation.

**Comment by ChandanPHAI** [comment]
I removed all node_modules and lockfiles and re-install it. Still getting the same error.

**Comment by chandanaswal18** [comment]
I have removed all node_modules and lock files and re-installed it. Still getting the same error.

**Comment by ndelangen** [comment]
@chandanaswal18 @borisdiakur would you have a way for me to reproduce this bug locally on my own machine?

**Comment by joehuanguf** [comment]
I'm getting this exact same issue. I'm using `@storybook/addon-info v5.1.3` and '@storybook/react v4.1.18'.

**Comment by shilman** [comment]
@joehuanguf in general you should use `@storybook/*` of the same version

**Comment by joehuanguf** [comment]
@shilman Thanks for the advice. Updating all `@storybook/*` dependencies to 5.1.3 seemed to fix the problem.
