### ISSUE TITLE
Error on start: Failed to load preset: framework-preset-cra.js

### ISSUE THREAD

**Issue by JasonTheAdams** [storybookjs/storybook#7055]
**Describe the bug**
I'm attempting to do `npm run storybook` and getting the following error:
```bash
> @ storybook /Users/jason/Sites/giveio/app
> start-storybook

info @storybook/react v5.1.3
info 
info => Loading presets
WARN   Failed to load preset: "/Users/jason/Sites/giveio/app/node_modules/@storybook/react/dist/server/framework-preset-cra.js"
ERR! TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!  { TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!   stack:
ERR!    "TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.\n    at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)\n    at Module._compile (internal/modules/cjs/loader.js:723:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)\n    at Module.load (internal/modules/cjs/loader.js:620:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:552:3)\n    at Module.require (internal/modules/cjs/loader.js:659:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)\n    at Module._compile (internal/modules/cjs/loader.js:723:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)\n    at Module.load (internal/modules/cjs/loader.js:620:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:552:3)\n    at Module.require (internal/modules/cjs/loader.js:659:17)\n    at require (internal/modules/cjs/helpers.js:22:18)" }
info => Loading presets
WARN   Failed to load preset: "/Users/jason/Sites/giveio/app/node_modules/@storybook/react/dist/server/framework-preset-cra.js"
ERR! TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!  { TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!     at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:723:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:620:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:659:17)
ERR!     at require (internal/modules/cjs/helpers.js:22:18)
ERR!   stack:
ERR!    "TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.\n    at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/index.js:25:5)\n    at Module._compile (internal/modules/cjs/loader.js:723:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)\n    at Module.load (internal/modules/cjs/loader.js:620:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:552:3)\n    at Module.require (internal/modules/cjs/loader.js:659:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/Users/jason/Sites/giveio/app/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)\n    at Module._compile (internal/modules/cjs/loader.js:723:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)\n    at Module.load (internal/modules/cjs/loader.js:620:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:552:3)\n    at Module.require (internal/modules/cjs/loader.js:659:17)\n    at require (internal/modules/cjs/helpers.js:22:18)" }
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
 10% building 1/1 modules 0 active(node:34975) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:34975) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
/Users/jason/Sites/giveio/app/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17
                compilation.templatesPlugin("render-with-entry", (source, chunk, hash) => {
                            ^

TypeError: compilation.templatesPlugin is not a function
    at SetVarMainTemplatePlugin.apply (/Users/jason/Sites/giveio/app/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17:15)
    at Compilation.apply (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/tapable/lib/Tapable.js:79:16)
    at Compilation.deprecated [as apply] (internal/util.js:73:15)
    at compiler.plugin (/Users/jason/Sites/giveio/app/node_modules/webpack/lib/LibraryTemplatePlugin.js:45:18)
    at SyncHook.eval [as call] (eval at create (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:580:30)
    at hooks.beforeCompile.callAsync.err (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:617:29)
    at _err0 (eval at create (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at compiler.inputFileSystem.readFile (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/webpack/lib/DllReferencePlugin.js:72:15)
    at process.nextTick (/Users/jason/Sites/giveio/app/node_modules/@storybook/core/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ storybook: `start-storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jason/.npm/_logs/2019-06-11T20_59_24_412Z-debug.log
```

Here is my `config.php`:
```
import { configure } from '@storybook/react';

function loadStories() {
    require('../resources/js/components/index.stories');
}

configure(loadStories, module);
```

**To Reproduce**
1. Run `npm run storybook`

**System:**
 - OS: MacOS 10.14.5
 - Device: MacBook Pro 2015
 - Browser: Chrome
 - Framework: React
 - Addons: knobs, actions, links
 - Version: 5.1.3

**Additional context**
It was working a sub-package within the project. It stopped working as a result of moving the `.storybook` to the root, and moving the dependencies to the root `package.json` file. Could moving things break something?

**Comment by JasonTheAdams** [comment]
I just tried deleting the `.storybook` directory and all the npm packages, then starting from scratch with `npx -p @storybook/cli sb init --use-npm --type react`. This produced the exact same error, so it seems I'm pretty stuck. 😕

**Comment by JasonTheAdams** [comment]
I deleted the `node_modules` and `package-lock.json` file and tried installing fresh again. It did the trick this time. Clearly something got garbled up, but I'm not sure what. 🤷‍♂
