### ISSUE TITLE
React.createElement: type is invalid -- expected a string but got: object.     

### ISSUE THREAD

**Issue by stereodenis** [storybookjs/storybook#7412]
```
console.error node_modules/react/cjs/react.development.js:188
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    
    Check the render method of `Presenter`.
        in Presenter

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9215
    The above error occurred in the <Presenter> component:
        in Presenter
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.


Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Presenter`.

    at invariant (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:55:15)
    at createFiberFromTypeAndProps (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2056:11)
    at createFiberFromElement (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2077:15)
    at reconcileSingleElement (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4629:23)
    at reconcileChildFibers (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4686:35)
    at reconcileChildren (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6500:28)
    at finishClassComponent (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6856:5)
    at updateClassComponent (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6794:24)
    at beginWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7742:16)
    at performUnitOfWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11413:12)
    at workLoop (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11445:24)
    at renderRoot (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11528:7)
    at performWorkOnRoot (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12416:7)
    at performWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12328:7)
    at performSyncWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12302:3)
    at requestWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12171:5)
    at scheduleWork (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11986:5)
    at scheduleRootUpdate (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12585:3)
    at updateContainerAtExpirationTime (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12613:10)
    at updateContainer (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12624:10)
    at create (/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13057:5)
    at getRenderedTree (/node_modules/@storybook/addon-storyshots/dist/frameworks/react/renderTree.js:24:16)
    at /node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:18
    at Object.<anonymous> (/node_modules/@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js:42:33)
    at Object.asyncJestTest (/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (<anonymous>)
    at mapper (/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /node_modules/jest-jasmine2/build/queueRunner.js:73:41
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Code snippets**
```
import { getStorybookUI, configure } from '@storybook/react-native'
import { loadStories } from './storyLoader'

configure(loadStories, module)

const StorybookUI = getStorybookUI({
  port: 7007,
  onDeviceUI: true,
})

export default StorybookUI
```
```
import initStoryshots from '@storybook/addon-storyshots'
initStoryshots({})
```

**System:**
 - OS: MacOS
 - Device: Jest
 - Framework: React Native 0.59.10
 - Addons: Storyshots
 - Version: 
"@storybook/addon-storyshots": "5.1.9"
"@storybook/react-native": "5.1.9"

**Comment by chess-octane** [comment]
@stereodenis how could you solve this issue? I am facing the same error.
