### ISSUE TITLE
Creating angular project with no initial app throws sb init error

### ISSUE THREAD

**Issue by kroeder** [storybookjs/storybook#7442]
Angular allows to create an empty project with an almost empty `angular.json`. Later you can add projects by using `ng generate app` or `ng generate lib`.

However, running `sb init` on an empty project causes a hard error while it should bring up a user-friendly message.

```
     TypeError: Cannot read property 'architect' of undefined
    at architect (C:\Users\roede\AppData\Roaming\npm-cache\_npx\14008\node_modules\@storybook\cli\generators\ANGULAR/angular-helpers.js:8:61)
    at getAngularAppTsConfigPath (C:\Users\roede\AppData\Roaming\npm-cache\_npx\14008\node_modules\@storybook\cli\generators\ANGULAR/angular-helpers.js:17:24)
    at editAngularAppTsConfig (C:\Users\roede\AppData\Roaming\npm-cache\_npx\14008\node_modules\@storybook\cli\generators\ANGULAR/index.js:57:24)
    at editAngularAppTsConfig (C:\Users\roede\AppData\Roaming\npm-cache\_npx\14008\node_modules\@storybook\cli\generators\ANGULAR/index.js:76:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

At this moment you need to create an app or project and re-run `sb init --force` or else storybook won't run even though it has created all its angular related files.

**To Reproduce**
1. `ng new awesome-project --create-application=false`
2. `npx @storybook/cli init`
3. `ng generate lib awesome-lib`
4. `npx @storybook/cli init --force`

**Expected behavior**
A soft exit where the user gets informed that he needs at least one angular project in his workspace. It also should abort `sb init` so a user can just run `sb init` again after creating a project

**System:**
 - Framework: [angular]
 - Version: [5.1.9]

**Comment by Enuvid** [comment]
Can I take this?

**Comment by kroeder** [comment]
@Enuvid sure! Do you need any guidance?

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.12 containing PR #7574 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
