### ISSUE TITLE
Running some storybook examples not working.

### ISSUE THREAD

**Issue by lonyele** [storybookjs/storybook#7505]
**Describe the bug**
Most of the storybook examples have a white page with an error when `yarn storybook` 

**To Reproduce**
1. Go to any specific framework folders under `examples`
2. `yarn storybook`
3. White page with an error on console
```
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://localhost:9009/sb_dll/storybook_ui_dll.js:2:849303
    at a (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:849406)
    at Gr (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:891706)
    at p (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:897588)
    at v (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:898861)
    at http://localhost:9009/sb_dll/storybook_ui_dll.js:2:900837
    at xi (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:907780)
    at Ii (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:917649)
    at Va (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:939563)
    at qa (http://localhost:9009/sb_dll/storybook_ui_dll.js:2:939947)
```

**Expected behavior**
It should run storybook when `yarn storybook`

**Screenshots**
![nodllerror](https://user-images.githubusercontent.com/15892571/61578264-0b207580-ab2f-11e9-97f4-2bec2361b6c4.png)

**System:**
 - OS: [Windows10]
 - Device: []
 - Browser: [chrome, firefox]
 - Framework: [many]
 - Addons: [if relevant]
 - Version: [5.2.0-beta.4]

**Comment by fvg-elearning** [comment]
I am having this same issue, did you solved it?
