### ISSUE TITLE
[5.2.0-beta.x] addon-knobs error: Storybook preview hooks can only be called inside decorators and story functions.

### ISSUE THREAD

**Issue by jrsearles** [storybookjs/storybook#7638]
**Describe the bug**
I'm trying to update a project to use latest beta (5.2.0-beta.18), but running into issues which i think i've narrowed down to the knobs addon. I've stripped out all other addons and am still receiving this. 

Full stack:
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at useHook (http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:25399:9)
    at useMemoLike (http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:25403:18)
    at useEffect (http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:25499:16)
    at registerKnobs (http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:19524:28)
    at wrapper (http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:19392:38)
    at http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:20805:14
    at http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:20819:26
    at http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:29383:21
    at http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:28843:14
    at http://localhost:58156/vendors~main.1935f7d6221d9ef1417b.bundle.js:28844:16

**To Reproduce**
1. This happens upon launch using `start-storybook` script.

**Code snippets**
```js
// config.js
import { configure, addDecorator } from "@storybook/react";
import { withKnobs } from "@storybook/addon-knobs";

addDecorator(withKnobs);

configure(require.context("../src", true, /\.stories\.(js|tsx?)$/), module);
```

```js
// addons.js
import "@storybook/addon-knobs/register";
```

```js
// presets.js
module.exports = [
  {
    name: "@storybook/preset-scss",
    options: {
      cssLoaderOptions: {
        importLoaders: 1,
        modules: true,
        camelCase: true,
        localIdentName: "[name]__[local]___[hash:base64:5]"
      }
    }
  }
];
```

```js
// webpack.config.js
const { resolve } = require("path");

module.exports = async ({ config, mode }) => ({
  ...config,
  module: {
    ...config.module,
    rules: [
      ...config.module.rules,
      {
        test: /\.tsx?$/,
        include: resolve(__dirname, "../src"),
        use: [
          require.resolve("babel-loader"),
          ...(mode !== "TEST" ? [require.resolve("react-docgen-typescript-loader")] : [])
        ]
      }
    ]
  },
  resolve: {
    ...config.resolve,
    modules: [...config.resolve.modules, resolve(__dirname, "../src")],
    extensions: [...config.resolve.extensions, ".ts", ".tsx"]
  }
});
```

**System:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.10.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18941.1001.0

**Comment by jrsearles** [comment]
I've installed beta.20 and seems to be working now.
