### ISSUE TITLE
Latest storybook and angular doesn't work together

### ISSUE THREAD

**Issue by arthurpumpa** [storybookjs/storybook#7722]
**Describe the bug**
Latest storybook and angular doesn't work together
@angular version: 8.2.0
@storybook/angular version: 5.1.10

**To Reproduce**
1. npm install -g @angular/cli
2. ng new my-dream-app
3. cd my-dream-app
4. npx -p @storybook/cli sb init --type angular
5. npm run storybook
6. open any story

**Expected behavior**
No exceptions

**Additional context**
Downgrading the storybook dependencies (to 5.1.9) solved my issue

**Comment by shilman** [comment]
@arthurpumpa Can you include the errors to make it easier to review? Thanks!

**Comment by arthurpumpa** [comment]
![image](https://user-images.githubusercontent.com/930487/62710736-807db880-ba00-11e9-83ca-8ecfa123ef21.png)

```
Can't resolve all parameters for AppComponent: (?, ?, [object Object]).
Error: Can't resolve all parameters for AppComponent: (?, ?, [object Object]).
    at syntaxError (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:9483:17)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28502:35)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28394:26)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28013:24)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28598:28)
    at http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28257:163
    at Array.map (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:28257:128)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:34297:51)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (http://localhost:6006/vendors~main.b62229f805266467b58e.bundle.js:34278:36)
```

**Comment by kroeder** [comment]
Duplicates https://github.com/storybookjs/storybook/issues/6804#issuecomment-518198870

@arthurpumpa I'm working on a fix. I haven't found the problem, though
I also added a workaround in the linked issue https://github.com/storybookjs/storybook/issues/6804#issuecomment-519149065

**Comment by Soifer** [comment]
I have the same issue:
"@angular/core": "8.2.2"
@storybook/angular : 5.1.11
with monorepo project without "src" folder in the project root

**Comment by ediabal** [comment]
Following this as the solution I've had to solve this is quite complex. I was able to use the latest versions of storybook and angular but i have to render complied components using a complex build process to watch all my files and build them so storybook can retrieve the latest from my `dist` directory. If I try to directly import components that aren't compiled into stories I get errors where my templates are not type string.

This is all very concerning that there isn't a way to easily set up an angular project in storybook. Please keep us updated on the work for this.

My dependencies are this for my component library:
```
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.2",
    "@angular-devkit/build-ng-packagr": "~0.802.2",
    "@angular/cli": "~8.2.2",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@babel/core": "^7.6.0",
    "@storybook/addon-actions": "^5.2.0-rc.6",
    "@storybook/addon-links": "^5.2.0-rc.6",
    "@storybook/addon-notes": "^5.2.0-rc.6",
    "@storybook/addons": "^5.2.0-rc.6",
    "@storybook/angular": "^5.2.0-rc.6",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "babel-loader": "^8.0.6",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^5.3.0",
    "npm-run-all": "^4.1.5",
    "protractor": "~5.4.0",
    "rimraf": "^3.0.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.36.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "wait-on": "^3.3.0"
  }
```
