### ISSUE TITLE
storybook throw error after update action

### ISSUE THREAD

**Issue by malkovDanik** [storybookjs/storybook#7867]
**Describe the bug**
Launching a storybook:serve: `vue-cli-service storybook:serve -p 6005 -c config/storybook  in intelij idea. the storybook periodically falls with an error.

**reproduce**
1. correct app file
2. Storybook automatically updates sources files
3. throw error with error
4. See log error

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'storybook:serve',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'prestorybook:serve',
4 verbose run-script   'storybook:serve',
4 verbose run-script   'poststorybook:serve' ]
5 info lifecycle ru.niicps.mchs.avalanche@1.1.0~prestorybook:serve: ru.niicps.mchs.avalanche@1.1.0
6 info lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: ru.niicps.mchs.avalanche@1.1.0
7 verbose lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: unsafe-perm in lifecycle true
8 verbose lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\project\ru.niicps.mchs.avalanche\avalanche-front\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\Adobe\CS5\jre\bin;c:\Program Files (x86)\QUART\pgbin92;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: CWD: E:\project\ru.niicps.mchs.avalanche\avalanche-front
10 silly lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: Args: [ '/d /s /c',
10 silly lifecycle   'vue-cli-service storybook:serve -p 6005 -c config/storybook' ]
11 silly lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: Returned: code: 3  signal: null
12 info lifecycle ru.niicps.mchs.avalanche@1.1.0~storybook:serve: Failed to exec storybook:serve script
13 verbose stack Error: ru.niicps.mchs.avalanche@1.1.0 storybook:serve: `vue-cli-service storybook:serve -p 6005 -c config/storybook`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ru.niicps.mchs.avalanche@1.1.0
15 verbose cwd E:\project\ru.niicps.mchs.avalanche\avalanche-front
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "storybook:serve" "--scripts-prepend-node-path=auto"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 3
22 error ru.niicps.mchs.avalanche@1.1.0 storybook:serve: `vue-cli-service storybook:serve -p 6005 -c config/storybook`
22 error Exit status 3
23 error Failed at the ru.niicps.mchs.avalanche@1.1.0 storybook:serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]

**Expected behavior**
not error

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Binaries:
    Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by malkovDanik** [comment]
it's not storybook. It' npm imho
