### ISSUE TITLE
[addon-docs] breaks if components feature dynamic title

### ISSUE THREAD

**Issue by thebuilder** [storybookjs/storybook#7932]
**Describe the bug**
Using `addon-docs` with `CSF` components, that feature a dynamic title fails to load, throwing an error instead.

This happens if the `title` is using a function or a tagged template string.

**Stacktrace**
```
Module build failed (from ./node_modules/@storybook/source-loader/dist/server/index.js):
TypeError: Cannot read property 'toLowerCase' of undefined
  at sanitize (./node_modules/@storybook/router/dist/utils.js:64:17)
  at sanitizeSafe (./node_modules/@storybook/router/dist/utils.js:72:19)
  at toId (./node_modules/@storybook/router/dist/utils.js:82:20)
  at handleExportedName (./node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/parse-helpers.js:87:6)
  at Controller.enter (./node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/traverse-helpers.js:109:60)
  at Controller.__execute (./node_modules/estraverse/estraverse.js:330:31)
  at Controller.traverse (./node_modules/estraverse/estraverse.js:434:28)
  at Object.traverse (./node_modules/estraverse/estraverse.js:646:27)
  at findExportsMap (./node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/traverse-helpers.js:101:14)
  at generateStoriesLocationsMap (./node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/generate-helpers.js:138:63)
  at inject (./node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/inject-decorator.js:74:56)
  at readAsObject (./node_modules/@storybook/source-loader/dist/server/dependencies-lookup/readAsObject.js:45:47)
  at readStory (./node_modules/@storybook/source-loader/dist/server/dependencies-lookup/readAsObject.js:100:10)
  at Object.transform (./node_modules/@storybook/source-loader/dist/server/build.js:15:38)
```

**Expected behavior**
Docs should be able to load files with dynamic title

**Code snippets**
```js
import * as React from 'react'
import base from 'paths.macro'

export default {
  title: `Modules|${base}`
}

export const example = () => <div />
```

or 

```js
import * as React from 'react'
import base from 'paths.macro'

export default {
  title: `${base}` // Template strings causes the same issue
}

export const example = () => <div />
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.9.1 - ~/.config/nvm/12.9.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.config/nvm/12.9.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-actions: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-docs: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-links: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addon-viewport: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/addons: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/react: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/source-loader: ^5.2.0-rc.0 => 5.2.0-rc.0 
    @storybook/theming: ^5.2.0-rc.0 => 5.2.0-rc.0 
```

**Additional context**
This is based on the documented approach to generating path names use babel macros:
https://github.com/storybookjs/storybook/blob/next/docs/src/pages/basics/writing-stories/index.md#generating-nesting-path-based-on-__dirname

**Comment by thebuilder** [comment]
Is it possible for the `source-loader` to lazy evaluate the title?

**Comment by shilman** [comment]
Yippee!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.14 containing PR #8995 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
