### ISSUE TITLE
start-storybook crashes with:  identifier.indexOf is not a function

### ISSUE THREAD

**Issue by losh11** [storybookjs/storybook#7958]
**Describe the bug**
Running `start-storybook` doesn't work. Instead the process crashes and gives the following error: 
```
/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:254
                const idxQuery = identifier.indexOf("?");
                                            ^

TypeError: identifier.indexOf is not a function
    at Resolver.parse (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:254:31)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/ParsePlugin.js:16:28)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:34:13)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:43:13)
    at _next0 (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:638:1)
    at _fn0 (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:660:1)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/AliasPlugin.js:53:11)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:652:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at DescriptionFileUtils.loadDescriptionFile (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:38:14)
    at forEachBail (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:51:12)
    at args (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
```

**To Reproduce**
1. Create new react-native project.
2. `$ npx -p @storybook/cli sb init --type react_native`
3. `$ npm run storybook`

**Expected behavior**
Storybook should work.

**System:**
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v11.14.0/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-links: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/react-native: ^5.1.11 => 5.1.11 
    @storybook/react-native-server: ^5.1.11 => 5.1.11 
  npmGlobalPackages:
    @storybook/cli: 5.1.11

**Additional context**
This is a duplicate of issue https://github.com/storybookjs/storybook/issues/5223. Unfortunately that issue received no replies and was auto closed by the bot due to inactivity.

**Comment by fozhao** [comment]
Can't believe this one is ignored. Having the same problem and it's blocking me half of the day. Any luck? @losh11

**Comment by losh11** [comment]
No update @fozhao

**Comment by mphasak** [comment]
Running into this too.  Had it working in a previous node_modules state which I can't now recreate, if that's any clue to anyone.

**Comment by mphasak** [comment]
I need to set aside the problem for now; here's the diff list of the working node_modules (`node_modules.works`) and the broken one (`node_modules.broke`).  I'll hold on to the folder, feel free to ping me if anyone wants to see the specific diff of one of these files:

```
Only in node_modules.works/.cache/storybook: records.json
Only in node_modules.broke/@reach/router/node_modules: react
Only in node_modules.works/@storybook/react-native-server/node_modules/@storybook/core/dist: public

Files node_modules.works/are-we-there-yet/node_modules/readable-stream/readable.js and node_modules.broke/are-we-there-yet/node_modules/readable-stream/readable.js differ

Files node_modules.works/assert/assert.js and node_modules.broke/assert/assert.js differ

Files node_modules.works/bl/node_modules/readable-stream/lib/_stream_readable.js and node_modules.broke/bl/node_modules/readable-stream/lib/_stream_readable.js differ
Files node_modules.works/bl/node_modules/readable-stream/lib/_stream_writable.js and node_modules.broke/bl/node_modules/readable-stream/lib/_stream_writable.js differ
Files node_modules.works/bl/node_modules/readable-stream/readable.js and node_modules.broke/bl/node_modules/readable-stream/readable.js differ

Files node_modules.works/concat-stream/node_modules/readable-stream/readable.js and node_modules.broke/concat-stream/node_modules/readable-stream/readable.js differ

Files node_modules.works/crypto-browserify/node_modules/pbkdf2/lib/default-encoding.js and node_modules.broke/crypto-browserify/node_modules/pbkdf2/lib/default-encoding.js differ

Files node_modules.works/duplexify/node_modules/readable-stream/readable.js and node_modules.broke/duplexify/node_modules/readable-stream/readable.js differ

Files node_modules.works/extract-zip/node_modules/readable-stream/readable.js and node_modules.broke/extract-zip/node_modules/readable-stream/readable.js differ

Files node_modules.works/flush-write-stream/node_modules/readable-stream/readable.js and node_modules.broke/flush-write-stream/node_modules/readable-stream/readable.js differ

Files node_modules.works/from2/node_modules/readable-stream/readable.js and node_modules.broke/from2/node_modules/readable-stream/readable.js differ

Files node_modules.works/fs-write-stream-atomic/node_modules/readable-stream/readable.js and node_modules.broke/fs-write-stream-atomic/node_modules/readable-stream/readable.js differ

Files node_modules.works/fsevents/node_modules/node-pre-gyp/node_modules/.bin/semver and node_modules.broke/fsevents/node_modules/node-pre-gyp/node_modules/.bin/semver differ
Files node_modules.works/fsevents/node_modules/readable-stream/readable.js and node_modules.broke/fsevents/node_modules/readable-stream/readable.js differ
Files node_modules.works/fsevents/node_modules/semver/README.md and node_modules.broke/fsevents/node_modules/semver/README.md differ
Files node_modules.works/fsevents/node_modules/semver/bin/semver and node_modules.broke/fsevents/node_modules/semver/bin/semver differ
Files node_modules.works/fsevents/node_modules/semver/semver.js and node_modules.broke/fsevents/node_modules/semver/semver.js differ

Files node_modules.works/fwd-stream/node_modules/readable-stream/lib/_stream_readable.js and node_modules.broke/fwd-stream/node_modules/readable-stream/lib/_stream_readable.js differ
Files node_modules.works/fwd-stream/node_modules/readable-stream/lib/_stream_writable.js and node_modules.broke/fwd-stream/node_modules/readable-stream/lib/_stream_writable.js differ
Files node_modules.works/fwd-stream/node_modules/readable-stream/readable.js and node_modules.broke/fwd-stream/node_modules/readable-stream/readable.js differ

Files node_modules.works/get-uri/node_modules/readable-stream/readable.js and node_modules.broke/get-uri/node_modules/readable-stream/readable.js differ

Files node_modules.works/htmlparser2/node_modules/readable-stream/readable.js and node_modules.broke/htmlparser2/node_modules/readable-stream/readable.js differ

Files node_modules.works/levelup/lib/util.js and node_modules.broke/levelup/lib/util.js differ
Files node_modules.works/levelup/node_modules/readable-stream/lib/_stream_readable.js and node_modules.broke/levelup/node_modules/readable-stream/lib/_stream_readable.js differ
Files node_modules.works/levelup/node_modules/readable-stream/lib/_stream_writable.js and node_modules.broke/levelup/node_modules/readable-stream/lib/_stream_writable.js differ
Files node_modules.works/levelup/node_modules/readable-stream/readable.js and node_modules.broke/levelup/node_modules/readable-stream/readable.js differ

Files node_modules.works/memory-fs/node_modules/readable-stream/readable.js and node_modules.broke/memory-fs/node_modules/readable-stream/readable.js differ

Files node_modules.works/merge-stream/node_modules/readable-stream/readable.js and node_modules.broke/merge-stream/node_modules/readable-stream/readable.js differ

Files node_modules.works/mississippi/node_modules/readable-stream/readable.js and node_modules.broke/mississippi/node_modules/readable-stream/readable.js differ

Files node_modules.works/node-libs-browser/node_modules/assert/assert.js and node_modules.broke/node-libs-browser/node_modules/assert/assert.js differ
Files node_modules.works/node-libs-browser/node_modules/readable-stream/readable.js and node_modules.broke/node-libs-browser/node_modules/readable-stream/readable.js differ
Files node_modules.works/node-libs-browser/node_modules/stream-browserify/index.js and node_modules.broke/node-libs-browser/node_modules/stream-browserify/index.js differ

Files node_modules.works/parallel-transform/node_modules/readable-stream/readable.js and node_modules.broke/parallel-transform/node_modules/readable-stream/readable.js differ

Files node_modules.works/parse-asn1/node_modules/pbkdf2/lib/default-encoding.js and node_modules.broke/parse-asn1/node_modules/pbkdf2/lib/default-encoding.js differ

Only in node_modules.works/react-native/scripts: .packager.env
Only in node_modules.works/react-native: third-party

Files node_modules.works/react-native-crypto/node_modules/pbkdf2/browser.js and node_modules.broke/react-native-crypto/node_modules/pbkdf2/browser.js differ

Files node_modules.works/readable-stream/lib/_stream_readable.js and node_modules.broke/readable-stream/lib/_stream_readable.js differ
Files node_modules.works/readable-stream/lib/_stream_writable.js and node_modules.broke/readable-stream/lib/_stream_writable.js differ

Files node_modules.works/readdirp/node_modules/readable-stream/readable.js and node_modules.broke/readdirp/node_modules/readable-stream/readable.js differ

Files node_modules.works/socketcluster/sample/node_modules/readable-stream/readable.js and node_modules.broke/socketcluster/sample/node_modules/readable-stream/readable.js differ
Files node_modules.works/socketcluster/sample/node_modules/socketcluster/sample/node_modules/debug/browser.js and node_modules.broke/socketcluster/sample/node_modules/socketcluster/sample/node_modules/debug/browser.js differ
Files node_modules.works/socketcluster/sample/node_modules/socketcluster/sample/node_modules/readable-stream/readable.js and node_modules.broke/socketcluster/sample/node_modules/socketcluster/sample/node_modules/readable-stream/readable.js differ

Files node_modules.works/stream-browserify/index.js and node_modules.broke/stream-browserify/index.js differ

Files node_modules.works/stream-http/node_modules/readable-stream/readable.js and node_modules.broke/stream-http/node_modules/readable-stream/readable.js differ

Files node_modules.works/superagent/node_modules/readable-stream/readable.js and node_modules.broke/superagent/node_modules/readable-stream/readable.js differ

Files node_modules.works/through2/node_modules/readable-stream/readable.js and node_modules.broke/through2/node_modules/readable-stream/readable.js differ

```

**Comment by olddustysocksunderthecouch** [comment]
This issue is not resolved
