### ISSUE TITLE
 TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by Alfr3d** [storybookjs/storybook#8014]
**Describe the bug**
During storybook install ( npx -p @storybook/cli sb init ) 
.
.
TypeError: Cannot read property 'undefined' of undefined

**To Reproduce**
1. npm install ionic@3.0.0
2. ionic start myApp tabs --type=ionic-angular
2.bis cd myApp
3. npx -p @storybook/cli sb init

**Screenshots**
```
+ @storybook/angular@5.1.11
+ babel-loader@8.0.6
+ @babel/core@7.5.5
+ @storybook/addon-actions@5.1.11
+ @storybook/addons@5.1.11
+ @storybook/addon-notes@5.1.11
+ @storybook/addon-links@5.1.11
added 828 packages from 673 contributors and audited 34803 packages in 42.529s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

     TypeError: Cannot read property 'undefined' of undefined
    at getAngularAppTsConfigPath (/Users/...../.npm/_npx/52114/lib/node_modules/@storybook/cli/generators/ANGULAR/angular-helpers.js:8:24)
    at getAngularAppTsConfigPath (/Users/...../.npm/_npx/52114/lib/node_modules/@storybook/cli/generators/ANGULAR/angular-helpers.js:17:24)
    at editAngularAppTsConfig (/Users/...../.npm/_npx/52114/lib/node_modules/@storybook/cli/generators/ANGULAR/index.js:57:24)
    at editAngularAppTsConfig (/Users/...../.npm/_npx/52114/lib/node_modules/@storybook/cli/generators/ANGULAR/index.js:76:3)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-links: ^5.1.11 => 5.1.11 
    @storybook/addon-notes: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/angular: ^5.1.11 => 5.1.11 

```

/myApp/package.json
```
"dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.20.0",
    "@ionic-native/splash-screen": "~4.20.0",
    "@ionic-native/status-bar": "~4.20.0",
    "@ionic/storage": "2.2.0",
    "ionic-angular": "3.9.5",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@ionic/app-scripts": "3.2.2",
    "@storybook/addon-actions": "^5.1.11",
    "@storybook/addon-links": "^5.1.11",
    "@storybook/addon-notes": "^5.1.11",
    "@storybook/addons": "^5.1.11",
    "@storybook/angular": "^5.1.11",
    "babel-loader": "^8.0.6",
    "typescript": "~2.6.2"
  },
```

**Additional context**
After install, I have tried `npm run storybook` but 

```
info => Loading custom addons config.
info => Found custom tsconfig.json
info => Using default webpack setup.
Starting type checking service...
Using 1 worker with 2048MB memory limit
10% building 1/1 modules 0 active(node:52175) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:52175) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
/....../myApp/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17
                compilation.templatesPlugin("render-with-entry", (source, chunk, hash) => {
                            ^

TypeError: compilation.templatesPlugin is not a function
```

**Comment by shilman** [comment]
you need to run that inside `myApp`

**Comment by Alfr3d** [comment]
Hi shilman. 
I've just update topic, I had forgotten to write: cd myApp after start ionic proj.
