### ISSUE TITLE
Docs throws error after 5.2 upgrade

### ISSUE THREAD

**Issue by daverau-optimizely** [storybookjs/storybook#8136]
Both the short and long way, I ran into the same error, stories work, but Docs throws an error:

```
TypeError: _react.default.useEffect is not a function
    at DocsContainer (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:5582:21)
    at renderWithHooks (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:170366:157)
    at mountIndeterminateComponent (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:170629:883)
    at beginWork (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:170783:144)
    at performUnitOfWork (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171460:350)
    at workLoop (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171467:45)
    at renderRoot (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171482:174)
    at performWorkOnRoot (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171671:31)
    at performWork (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171653:795)
    at performSyncWork (http://localhost:9009/vendors~main.a47810b33d24c8d0e9b7.bundle.js:171651:143)
```

**To Reproduce**
1. Upgrade from Storybook `5.0.11` (both short or manual path)
2. Stories load fine, without error
3. Click Docs tab for error

**Expected behavior**
Should be able to view Docs

**System:**
```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-a11y: ^5.2.1 => 5.2.1
    @storybook/addon-actions: ^5.2.1 => 5.2.1
    @storybook/addon-docs: ^5.3.0-alpha.0 => 5.3.0-alpha.0
    @storybook/addon-info: ^5.2.1 => 5.2.1
    @storybook/addon-knobs: ^5.2.1 => 5.2.1
    @storybook/addon-notes: ^5.2.1 => 5.2.1
    @storybook/addon-options: ^5.2.1 => 5.2.1
    @storybook/addon-viewport: ^5.2.1 => 5.2.1
    @storybook/react: ^5.2.1 => 5.2.1
    @storybook/theming: ^5.2.1 => 5.2.1
```

**Comment by shilman** [comment]
What version of React are you using?

**Comment by Uyarn** [comment]
Do you import useEffect from React?

**Comment by Mark24Code** [comment]
+1

**Comment by shilman** [comment]
React 16.8 Is the minimum requirement for docs. You can still use the rest of Storybook with earlier react versions.

**Comment by Mark24Code** [comment]
Thanks a lot! My problem is solved.
