### ISSUE TITLE
backend.js:6 Adding a click listener to iframe failed:  DOMException: Blocked..

### ISSUE THREAD

**Issue by orpheus** [storybookjs/storybook#8231]
> Storybook 5.2.1

Whenever I open Chrome console while storybook is open, and drag it's height, I get this error:

`backend.js:6 Adding a click listener to iframe failed:  DOMException: Blocked a frame with origin "http://localhost:9001" from accessing a cross-origin frame`

```
 at bind (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:21611:36)
    at http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:21626:7
    at Array.forEach (<anonymous>)
    at http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:21608:13
    at commitHookEffectList (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:106891:26)
    at commitPassiveHookEffects (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:106921:11)
    at HTMLUnknownElement.callCallback (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:87252:14)
    at Object.invokeGuardedCallbackDev (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:87302:16)
    at invokeGuardedCallback (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:87359:31)
    at flushPassiveEffectsImpl (http://localhost:9001/vendors~main.4d3c50fe0bff40d4926c.bundle.js:109773:7) 
    in WithToolTipState (created by SidebarHeading)
    in SidebarHeading (created by Context.Consumer)
    in Context.Consumer (created by Context.Consumer)
    in Context.Consumer (created by Styled(SidebarHeading))
    in Styled(SidebarHeading) (created by Sidebar)
    in Sidebar (created by Context.Consumer)
    in Context.Consumer (created by ManagerConsumer)
    in ManagerConsumer (created by _default)
    in _default (created by Layout)
    in Layout (created by Context.Consumer)
    in Context.Consumer (created by WithTheme(Layout))
    in WithTheme(Layout) (created by Anonymous)
    in Anonymous
```

I've tried recreating the most simplest story (render a blank div) and it still happens. I've had time where it went away if I created a new blank story, but I cannot reproduce it. It might stop erring for a bit If I add a new story, but once I refresh it goes back to erring.

It's quite a big error and I get spammed with them everything I switch a story or drag the console height. 

Let me know what other information I can give, I know this isn't too much to go on.

**Comment by orpheus** [comment]
found the problem:

`storybook-addon-figma`

Is causing multiple errors. Weird behavior too. I have two stories that import and use this addon via `addDecorator` and they cause a React keys error and the error posted above. But they affect other stories as well which is why it wasn't obvious to debug.
