### ISSUE TITLE
Error when following the guide for setting up storybook with Angular

### ISSUE THREAD

**Issue by beelio** [storybookjs/storybook#8475]
### Steps to reproduce

I tried to follow the steps described here: https://storybook.js.org/docs/guides/guide-angular/

When running _run storybook_  I get SyntaxError: Unexpected token ] in JSON at position 195

###  Version of Storybook

 "@storybook/addon-actions": "^5.2.4",
  "@storybook/addon-links": "^5.2.4",
  "@storybook/addon-notes": "^5.2.4",
  "@storybook/addons": "^5.2.4",
  "@storybook/angular": "^5.2.4",

### Console error output

```
ERR! SyntaxError: Unexpected token ] in JSON at position 195
ERR!     at JSON.parse (<anonymous>)
ERR!     at getTsConfigOptions (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:32:25)
ERR!     at Object.getAngularCliWebpackConfigOptions (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:57:20)
ERR!     at Object.webpackFinal (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js:7:56)
ERR!     at /Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/core/dist/server/presets.js:82:72
ERR!     at processTicksAndRejections (internal/process/task_queues.js:89:5)
ERR!  SyntaxError: Unexpected token ] in JSON at position 195
ERR!     at JSON.parse (<anonymous>)
ERR!     at getTsConfigOptions (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:32:25)
ERR!     at Object.getAngularCliWebpackConfigOptions (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:57:20)
ERR!     at Object.webpackFinal (/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js:7:56)
ERR!     at /Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/core/dist/server/presets.js:82:72
ERR!     at processTicksAndRejections (internal/process/task_queues.js:89:5) {
ERR!   stack: 'SyntaxError: Unexpected token ] in JSON at position 195\n    at ' +
ERR!     'JSON.parse (<anonymous>)\n    at getTsConfigOptions ' +
ERR!     '(/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:32:25)\n' +
ERR!     '    at Object.getAngularCliWebpackConfigOptions ' +
ERR!     '(/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/angular-cli_config.js:57:20)\n' +
ERR!     '    at Object.webpackFinal ' +
ERR!     '(/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/angular/dist/server/framework-preset-angular-cli.js:7:56)\n' +
ERR!     '    at ' +
ERR!     '/Users/joelsjostrom/sr/seating-project/seating-client/node_modules/@storybook/core/dist/server/presets.js:82:72\n' +
ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:89:5)'
ERR! }
```

**Comment by NilsEngelbach** [comment]
@beelio I had a similar issue and was able to fix it by checking the `angular.json` file. It contained a wrong `,` (comma).

**Comment by sanjay51** [comment]
Found the culprit - 
![image](https://user-images.githubusercontent.com/4214056/90708631-23d9ee00-e24f-11ea-8ca6-0c46116296f3.png)

**Comment by IsaacSomething** [comment]
In my case the `stories` folder was in the `src`. Moving this out to the root of the project and updating the `storybook/main.js` to 

```
module.exports = {
  stories: ['../stories/**/*.stories.mdx', '../stories/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials']
};
```

solved the issue for me
