### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined with Docs Addon

### ISSUE THREAD

**Issue by Undistraction** [storybookjs/storybook#8554]
**Describe the bug**
I've tried to get the following working with the Docs Addon, but compilation results in an error:

**To Reproduce**
Javascript version (`Button.stories.js`):
```
import { Button } from '@example/components'
import React from 'react'

export default {
  title: `buttons/Button`,
  component: Button,
}

export const basic = () => <Button>Button</Button>

export const withIcon = () => <Button icon="placeholder">Button</Button>
```

**Expected behaviour**
Story compilation succeeds

**Actual behaviour**
An error is thrown:
```
Module build failed (from ./node_modules/@storybook/addon-storysource/loader.js):
TypeError: Cannot read property 'toLowerCase' of undefined
    at sanitize (/Users/me/Sites/frontend/node_modules/@storybook/router/dist/utils.js:63:17)
    at sanitizeSafe (/Users/me/Sites/frontend/node_modules/@storybook/router/dist/utils.js:70:19)
    at toId (/Users/me/Sites/frontend/node_modules/@storybook/router/dist/utils.js:80:20)
    at handleExportedName (/Users/me/Sites/frontend/node_modules/@storybook/source-loader/dist/server/abstract-syntax-tree/parse-helpers.js:87:6)
```

**Modules**
```
"@storybook/addon-actions": "^5.2.5",
"@storybook/addon-docs": "^5.2.5",
"@storybook/addon-links": "^5.2.5",
"@storybook/addon-storysource": "^5.2.5",
"@storybook/addons": "^5.2.5",
"@storybook/react": "^5.2.5",
```

**System:**
```
Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v8.13.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
```

**Comment by Undistraction** [comment]
Closing as this is already an issue: https://github.com/storybookjs/storybook/issues/8353
