### ISSUE TITLE
v5.2.5: Only first change of a knob is registered

### ISSUE THREAD

**Issue by fatso83** [storybookjs/storybook#8614]
**Describe the bug**
Only the first change to a text or number field (probably other types as well) registers and causes the component to update.

**To Reproduce**
1. Add a string knob to any component
2. See it render on the storybook
3. Change the value
4. See it update. The console will say something about `storybookjs/knobs/set`
5. Change the value again
6. Assert there has been no change/rerender. The console will say something about `storybookjs/knobs/change` for each subsequent change

**Expected behavior**
The console should rerender

**Screenshots**
This screenshot shows there are 0 listeners registered for the change event:
![screenshot](https://user-images.githubusercontent.com/618076/67763310-ab980700-fa47-11e9-8610-1d0d4c315664.png)

**Code snippets**
```javascript
    <ConversationSummary
        mostRecentMessage={text('Most recent message', "hey, there, is it me you're looking for?")}
        numberOfUnreadMessages={number('Unread messages', 2)}
      })}
    />
```
**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**
Reverting the system to v5.1.9 will fix the issue.

**Comment by shilman** [comment]
@Hypnosphi is this hooks-related?

**Comment by Hypnosphi** [comment]
Maybe

**Comment by shilman** [comment]
@Hypnosphi I think there might be a hooks patch that didn't make it into `master` yet due to merge conflicts: https://github.com/storybookjs/storybook/pull/8287

Would you mind patching it over?

**Comment by Hypnosphi** [comment]
Weird, I only see conflicts in `package.json` & `yarn.lock`

**Comment by Hypnosphi** [comment]
@shilman unfortunately, I can't fix it on `master`: `yarn bootstrap --core` fails with typescript errors:

```
lerna ERR! yarn run prepare exited 1 in '@storybook/theming'
lerna ERR! yarn run prepare stdout:
$ node ../../scripts/prepare.js
src/animation.ts(54,14): error TS2742: The inferred type of 'animation' cannot be named without a reference to '@emotion/css/node_modules/@emotion/serialize'. This is likely not portable. A type annotation is necessary.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run prepare stderr:
ERR! FAILED (ts) :  
ERR! FAILED to compile ts: @storybook/theming@5.2.5 
error Command failed with exit code 1.

lerna ERR! yarn run prepare exited 1 in '@storybook/theming'
error Command failed with exit code 1.

```

**Comment by KeionneDerousselle** [comment]
I'm also having this issue, but when I downgrade @storybook/* from 5.2.5 to 5.1.9, I get an error saying that none of my stories can be found. Is there a difference in setup between version 5.2.x and 5.1.x?

**Comment by pladaria** [comment]
Same issue here. We cannot downgrade because we already migrated several stories to the new format :/

Is anything we can do to help merging the fix?

**Comment by shilman** [comment]
@Hypnosphi Here's what I did:

```
git cherry-pick -m 1 b51f52d
# resolve conflicts manually
yarn bootstrap --core
yarn test --core --update
```

However, the test fails:

```
 FAIL  lib/client-api/src/hooks.test.js
  ● Preview hooks › useEffect › doesn't retrigger the effect from if decorator calls story twice

    expect(jest.fn()).toHaveBeenCalledTimes(1)

    Expected mock function to have been called one time, but it was called two times.

      135 |       };
      136 |       run(story, [decorator]);
    > 137 |       expect(effect).toHaveBeenCalledTimes(1);
          |                      ^
      138 |     });
```

**Comment by Hypnosphi** [comment]
I have 2 failing tests on clean master:

```
Summary of all failing tests
 FAIL  addons/storyshots/storyshots-core/stories/storyshot.specificConfig.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'get' of undefined

    > 1 | import global, { describe } from 'global';
        | ^
      2 | import addons, { mockChannel } from '@storybook/addons';
      3 | import ensureOptionsDefaults from './ensureOptionsDefaults';
      4 | import snapshotsTests from './snapshotsTestsTemplate';

      at _interopRequireWildcard (node_modules/@babel/runtime/helpers/interopRequireWildcard.js:12:20)
      at Object.<anonymous> (addons/storyshots/storyshots-core/src/api/index.js:1:1)
      at Object.<anonymous> (addons/storyshots/storyshots-core/src/index.js:2:1)
      at Object.<anonymous> (addons/storyshots/storyshots-core/stories/storyshot.specificConfig.test.js:2:1)

 FAIL  addons/storyshots/storyshots-core/stories/storyshot.renderOnly.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'get' of undefined

    > 1 | import global, { describe } from 'global';
        | ^
      2 | import addons, { mockChannel } from '@storybook/addons';
      3 | import ensureOptionsDefaults from './ensureOptionsDefaults';
      4 | import snapshotsTests from './snapshotsTestsTemplate';

      at _interopRequireWildcard (node_modules/@babel/runtime/helpers/interopRequireWildcard.js:12:20)
      at Object.<anonymous> (addons/storyshots/storyshots-core/src/api/index.js:1:1)
      at Object.<anonymous> (addons/storyshots/storyshots-core/src/index.js:2:1)
      at Object.<anonymous> (addons/storyshots/storyshots-core/stories/storyshot.renderOnly.test.js:2:1)
```

**Comment by Hypnosphi** [comment]
@shilman it passes for me

**Comment by shilman** [comment]
@Hypnosphi yes please!

**Comment by Hypnosphi** [comment]
OK I did, but wasn't able to test it manually because "Hooks" kind gives me a blank page with following exception: 

```
main.b692a25009555ef73b0c.bundle.js:3357 Uncaught TypeError: list.find is not a function
    at getSelectedBackgroundColor (main.b692a25009555ef73b0c.bundle.js:3357)
    at main.b692a25009555ef73b0c.bundle.js:3450
    at main.b692a25009555ef73b0c.bundle.js:12870
    at updateContextConsumer (vendors~main.3034e68520978db5a7f6.bundle.js:127048)
    at beginWork (vendors~main.3034e68520978db5a7f6.bundle.js:127236)
    at performUnitOfWork (vendors~main.3034e68520978db5a7f6.bundle.js:130876)
    at workLoop (vendors~main.3034e68520978db5a7f6.bundle.js:130916)
    at HTMLUnknownElement.callCallback (vendors~main.3034e68520978db5a7f6.bundle.js:111713)
    at Object.invokeGuardedCallbackDev (vendors~main.3034e68520978db5a7f6.bundle.js:111763)
    at invokeGuardedCallback (vendors~main.3034e68520978db5a7f6.bundle.js:111820)
```

An express debugging showed that `parameters.backgrounds` is `"_duplicate_root.event.args.0.stories.addons-a11y-basebutton--default.parameters.backgrounds"`

Looks like something went wrong with telejson deserialization cc @ndelangen

**Comment by sanbornhilland** [comment]
It's unclear to me if you guys have a handle on this or not but with `5.2.6` I am seeing similar behaviour after a `useState` setter is called so I thought I'd provide some information about what I'm seeing.

For example this will cause the knob to stop applying changes AFTER the `onClick` handler is run. If the `onClick` handler is run then the `range` knob working but if the setter never gets called the `knob` works. 

```jsx
.add('Default', () => {
    const [name, setName] = useState('')
    const width = number(
      'Width',
      42,
      {
        min: 1,
        max: 100,
        step: 1,
        range: true,
      },
    )

	return (
      <div 
        style={{ width }}
        onClick={() => setName('foo')}
      >
       { foo }
      </div>
  })

```

**Comment by shilman** [comment]
Hi gang, We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Please upgrade and try them out today. Thanks for your help and support getting this stable for release!

**Comment by shilman** [comment]
For anybody who is interested in Controls but don't know where to start, I've created a quick & dirty step-by-step walkthrough to go from a fresh CRA project to a working demo. Check it out:

=> [Storybook Controls w/ CRA & TypeScript](https://gist.github.com/shilman/69c1dd41a466bae137cc88bd2c6ef487)

There are also some "knobs to controls" migration docs in the Controls README:

=> [How do I migrate from addon-knobs?](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)
