### ISSUE TITLE
Jest doesn't properly import `@storybook/vue` exports.

### ISSUE THREAD

**Issue by pedrozath** [storybookjs/storybook#8811]
**Describe the bug**
Jest doesn't properly import `@storybook/vue` exports.

it shouts:
```
 FAIL  js_specs/components/storyshots.test.js
  ● Test suite failed to run

    TypeError: (0 , _vue.addParameters) is not a function

      10 |
    > 11 | addParameters({
         | ^
      12 |   options: {
      13 |     theme: require('@storybook/theming').create({
      14 |       base: 'light',

      at Object.<anonymous> (storybook/config.js:11:1)
      at Object.requireActual [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/configure.js:22:13)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/vue/loader.js:20:5)
      at Object.load [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:31:19)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:48:14)
      at Object.<anonymous> (js_specs/components/storyshots.test.js:4:1)
```

if commenting out `addParameters`, then:
```
 PASS  js_specs/modules/array_history.spec.js
 FAIL  js_specs/components/storyshots.test.js
  ● Test suite failed to run

    TypeError: (0 , _vue.configure) is not a function

      19 | // })
      20 |
    > 21 | configure(requireContext('./components/', true, /.(js|mdx)$/ ), module)
         | ^
      22 |

      at Object.<anonymous> (storybook/config.js:21:1)
      at Object.requireActual [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/configure.js:22:13)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/vue/loader.js:20:5)
      at Object.load [as default] (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:31:19)
      at testStorySnapshots (node_modules/@storybook/addon-storyshots/dist/api/index.js:48:14)
      at Object.<anonymous> (js_specs/components/storyshots.test.js:4:1)
```

**To Reproduce**

Setup the following scenario:

**storybook/config.js**
```js
import { configure, addParameters, addDecorator } from '@storybook/vue';
import Vue from 'vue'

import requireContext from 'require-context.macro';

addParameters({
  options: {
    theme: require('@storybook/theming').create({
      base: 'light',
      brandTitle: 'Octopi Design System',
      colorPrimary: '#3910E6'
    })
  }
})

configure(requireContext('./components/', true, /.(js|mdx)$/ ), module)
```

**storyshots.test.js**
```js
import initStoryshots from '@storybook/addon-storyshots';

initStoryshots({
  suite: 'Image storyshots',
  configPath: './storybook'
})
```

**jest.config.js**
```js
module.exports = {
  clearMocks: true,
  coverageDirectory: "coverage",
  moduleDirectories: [
    ".",
    "app/packs/javascripts",
    "app/assets/javascripts",
    "node_modules"
  ],

  // An array of file extensions your modules use
  moduleFileExtensions: [
    "js",
    "json",
    "jsx",
    "ts",
    "tsx",
    "node"
  ],

  // A map from regular expressions to module names that allow to stub out resources with a single module
  moduleNameMapper: {
    "\\.(scss|css)$": "identity-obj-proxy",
    "^@/(.*)$": "<rootDir>/src/$1"
  },

  testEnvironment: "jsdom",
  transform: {
    ".*.js$": "<rootDir>/js_specs/jest_transform.js",
    ".*.ts$": "<rootDir>/js_specs/jest_transform.js",
    '.*\\.(vue)$': '<rootDir>/node_modules/jest-vue-preprocessor'
  },

  transformIgnorePatterns: [
    'node_modules(?!(.*@storybook.*))',
  ],

  moduleFileExtensions: ['vue', 'js', 'jsx', 'json', 'node']
};
```

**package.json**
```js
{
  "license": "UNLICENSED",
  "scripts": {
    "test": "jest js_specs",
    "storybook": "start-storybook -p 6006 -c storybook",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@babel/core": "^7.7.2",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-member-expression-literals": "^7.2.0",
    "@babel/plugin-transform-modules-commonjs": "^7.7.0",
    "@babel/plugin-transform-property-literals": "^7.2.0",
    "@babel/plugin-transform-reserved-words": "^7.2.0",
    "@rails/webpacker": "^4.0.7",
    "@vue/babel-preset-app": "^3.10.0",
    "babel-preset-vue": "^2.0.2",
    "bootstrap": "^3",
    "css-loader": "^2.1.1",
    "jquery": "^3.4.1",
    "lodash": "4.17.13",
    "mixin-deep": "1.3.2",
    "node-sass": "^4.13.0",
    "pluralize": "^8.0.0",
    "pug": "^2.0.4",
    "pug-plain-loader": "^1.0.0",
    "sass-loader": "^7.1.0",
    "select2": "^4.0.12",
    "select2-bootstrap-theme": "^0.1.0-beta.10",
    "set-value": "2.0.1",
    "vue": "^2.6.10",
    "vue-loader": "^15.7.1",
    "vue-template-compiler": "^2.6.10",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/helper-module-imports": "^7.7.0",
    "@babel/plugin-proposal-export-default-from": "^7.5.2",
    "@babel/plugin-transform-react-jsx": "^7.7.0",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.7.1",
    "@babel/preset-typescript": "^7.7.2",
    "@storybook/addon-docs": "^5.3.0-alpha.41",
    "@storybook/addon-storyshots": "^5.3.0-alpha.41",
    "@storybook/addon-storyshots-puppeteer": "^5.2.6",
    "@storybook/vue": "^5.3.0-alpha.41",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-add-module-exports": "^1.0.2",
    "babel-plugin-dynamic-import-node": "^2.3.0",
    "babel-plugin-macros": "^2.6.1",
    "babel-plugin-require-context-hook": "^1.0.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "core-js": "^3.4.0",
    "expect.js": "^0.3.1",
    "identity-obj-proxy": "^3.0.0",
    "jest-serializer-vue": "^2.0.2",
    "jest-vue-preprocessor": "^1.7.0",
    "mocha": "^6.2.0",
    "react": "^16.11.0",
    "react-is": "^16.11.0",
    "require-context.macro": "^1.2.2",
    "storybook": "^5.1.11",
    "storybook-addon-vue-info": "^1.3.2",
    "vue-jest": "^3.0.5",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.7.1"
  }
}
```

**Expected behavior**
Not crash. Run tests.

**System:**
```
╰─ npx -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 69.0
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-docs: ^5.3.0-alpha.41 => 5.3.0-alpha.43
    @storybook/addon-storyshots: ^5.3.0-alpha.41 => 5.3.0-alpha.43
    @storybook/addon-storyshots-puppeteer: ^5.2.6 => 5.2.6
    @storybook/vue: ^5.3.0-alpha.41 => 5.3.0-alpha.43
```

**Additional context**

**Comment by pedrozath** [comment]
never mind, i got it working by using `babel-jest` and `babel.config.js` exclusively
