### ISSUE TITLE
First story is missing from the stories list

### ISSUE THREAD

**Issue by iamdriz** [storybookjs/storybook#8823]
I presume this is by design... by I find it kind of strange that the first story is missing from the stories list when viewing the Docs for a component.

For example if you look at the Storybook Design System story for Avatar's: https://storybook-design-system.netlify.com/?path=/docs/design-system-avatar--large

The Large story is shown at the top and above the props table and the rest of the stories are shown under the stories header... So the Large story loses its header... and is the only story to have the zoom controls, etc...

Would it not make more sense to have all of the stories appear under the stories and then have the props at the top with the ability to have an optional promo/hero story or other content instead?

To get around this we've had to duplicate the first story content like this:

```jsx
// the initial story you see in the Docs
export const promo = () => first_story()

// the stories under 'Stories'
export const first_story = () => (
    <div class="content"></div>
)

export const second_story = () => (
    <div class="content"></div>
}
```

**Comment by atanasster** [comment]
with #8855 you will be able to fully customize the DocsPage, including changing the slot property to not filter any of the stories. Here is are two examples: 
```
import { Title, Subtitle, Description, Primary, PrimaryProps, Stories } from '@storybook/addon-docs/blocks';
...
parameters: {
    docs: {
      page: () => (
        <>
          <Title />
          <Subtitle />
          <Description />
          <Primary />
          <PrimaryProps />
          <Stories slot={componentStories => componentStories} />
        </>
      ),
    },
```
or shorter using the default DocsPage
```
import { DocsPage } from '@storybook/addon-docs/blocks';
...
parameters: {
    docs: {
      page: () => <DocsPage storiesSlot={stories => stories} />,
    },
  },
```

will that work for you ?

**Comment by iamdriz** [comment]
@atanasster Quite possibly... I take it that on this line: `<Stories slot={componentStories => componentStories} />` you'd be passing a list of stories `componentStories`?

**Comment by atanasster** [comment]
@iamdriz yes, its a list of the enabled stories and you can filter them or return them all as in the example. By default this function filters out the first story.

**Comment by iamdriz** [comment]
@atanasster Are we waiting for your code to be merged before we can do this then?

**Comment by atanasster** [comment]
@iamdriz its merged now, you can try wither option from above.

**Comment by iamdriz** [comment]
I updated all my packages to `5.3.0-beta.11` and it broke everything 🤣 

```js
WARNING in ./src/components/Button.stories.js 581:11
Module parse failed: Unexpected token (581:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/@storybook/source-loader/dist/server/index.js
You may need an additional loader to handle the result of these loaders.
|   title: 'FUI|Components/Button',
|   decorators: [function (storyFn) {
>     return <div style={{
|       backgroundColor: 'black',
|       padding: '24px'
 @ ./src sync \.stories\.(js|mdx)$ ./components/Button.stories.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by atanasster** [comment]
Hmm - is your repo public to take a look? Or can you check what code exactly is causing the parsing error in that story.

**Comment by iamdriz** [comment]
Unfortunately it's all on a private bitbucket server.
All of our stories are failing now... here's an example Story:

../src/components/LinkButton.stories.js`

```jsx
import React from 'react';

export default {
    title: 'FUI|Components/Link Button',
    decorators: [storyFn => <div style={{ backgroundColor: 'black', padding: '24px' }}>{storyFn()}</div>],
};

export const overview = () => buttons()

export const buttons = () => (
    <div class="fui-button-group">
        <div class="fui-button-group">
            <button class="fui-link-button">Default</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--primary">Primary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--secondary">Secondary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--tertiary">Tertiary</button>
        </div>
    </div>
);

export const large_buttons = () => (
    <div class="fui-button-group">
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--large">Default</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--large fui-link-button--primary">Primary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--large fui-link-button--secondary">Secondary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--large fui-link-button--tertiary">Tertiary</button>
        </div>
    </div>
);

export const small_buttons = () => (
    <div class="fui-button-group">
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--small">Default</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--small fui-link-button--primary">Primary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--small fui-link-button--secondary">Secondary</button>
        </div>
        <div class="fui-button-group">
            <button class="fui-link-button fui-link-button--small fui-link-button--tertiary">Tertiary</button>
        </div>
    </div>
);
```

**Comment by atanasster** [comment]
The story you posted works fine for me. (One thing you might want to upgrade your story title separators to `FUI/Components/Link Button`.
Something in your config may be off - can you reinstall packages from scratch and remove your .lock files

**Comment by iamdriz** [comment]
@atanasster Why has separators been changed? My config is:
```
    hierarchySeparator: /\/|\./,
    hierarchyRootSeparator: /\|/,
```

**Comment by iamdriz** [comment]
@atanasster No still fails after reinstalling all of the packages.
Error:
```jsx
Module parse failed: Unexpected token (666:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/@storybook/source-loader/dist/server/index.js
You may need an additional loader to handle the result of these loaders.
| });
| export var buttons = addSourceDecorator(function () {
>   return <div class="fui-button-group">
|         <div class="fui-button-group">
|             <button class="fui-button">Default</button>
Error: Module parse failed: Unexpected token (666:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/@storybook/source-loader/dist/server/index.js
You may need an additional loader to handle the result of these loaders.
| });
| export var buttons = addSourceDecorator(function () {
>   return <div class="fui-button-group">
|         <div class="fui-button-group">
|             <button class="fui-button">Default</button>
    at Object../src/components/Button.stories.js (http://localhost:6006/main.a6ea2d1dad4f3f4661c5.bundle.js:1042:7)
    at __webpack_require__ (http://localhost:6006/runtime~main.a6ea2d1dad4f3f4661c5.bundle.js:786:30)
    at fn (http://localhost:6006/runtime~main.a6ea2d1dad4f3f4661c5.bundle.js:151:20)
    at webpackContext (http://localhost:6006/main.a6ea2d1dad4f3f4661c5.bundle.js:202:9)
    at http://localhost:6006/vendors~main.a6ea2d1dad4f3f4661c5.bundle.js:40692:31
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.a6ea2d1dad4f3f4661c5.bundle.js:40691:22
    at Array.forEach (<anonymous>)
    at http://localhost:6006/vendors~main.a6ea2d1dad4f3f4661c5.bundle.js:40690:14
    at render (http://localhost:6006/vendors~main.a6ea2d1dad4f3f4661c5.bundle.js:38810:13)
```

**Comment by shilman** [comment]
@iamdriz can you create a minimal reproduction repo for us to look at?

Here's an explanation of the difference between 5.2.x and 5.3.x as far as hierarchy separators are concerned: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#simplified-hierarchy-separators
