### ISSUE TITLE
Issues with @storybook/addon-storyshots

### ISSUE THREAD

**Issue by jonniebigodes** [storybookjs/storybook#8853]
While working on rewriting the tutorial storybook tutorial with angular, i'm running into some issues with both angular and @storybook/addon-storyshots.

Below are the steps taken for the issue:

- Created a new angular app using the cli with the following command `npx -p @angular/cli ng new example --style css`
- cd into into the folder created. 
- Ran `npx -p @storybook/cli sb init` to add the storybook. 
- Created a new component for testing purposes. The component is based on the example provided in the tutorial.
- Installed Jest and it's dependencies with `npm install -D jest @types/jest jest-preset-angular@7.1.1 @testing-library/angular @testing-library/jest-dom @storybook/addon-storyshots`
- Following the tutorial, created the same file structure necessary
- Updated `package.json` with the following key:
```json
"jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/src/jest-config/setup.ts",
      "@testing-library/jest-dom/extend-expect"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/old/",
      "<rootDir>/node_modules/",
      "<rootDir>/dist/",
      "<rootDir>/storybook-static/",
      "<rootDir>/src/test.ts"
    ],
    "coveragePathIgnorePatterns": [
      "/jest-config/",
      "/node_modules/"
    ],
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-preset-angular/AngularSnapshotSerializer.js",
      "<rootDir>/node_modules/jest-preset-angular/HTMLCommentSerializer.js"
    ],
    "globals": {
      "ts-jest": {
        "tsConfig": "<rootDir>/tsconfig.spec.json",
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "<rootDir>/node_modules/jest-preset-angular/InlineHtmlStripStylesTransformer"
        ]
      }
    },
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/src/jest-config/styleMock.js",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/jest-config/fileMock.js"
    },
    "transform": {
      "^.+\\.(ts|js|html)$": "ts-jest"
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node",
      ".html"
    ]
  }
```

- Run `npm run jest` for the first time and i'm presented with the following error:

```bash
src/storybook.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

   \example\.storybook\config.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from "@storybook/angular";
```
That's to be expected as it does not know how to parse js files
- Updated `tsconfig.json` with the following:
```json
{
....
"compilerOptions"{
 "allowJs": true,
...
}
}
```
- Running `npm run jest` yelds the following error:
```bash
 FAIL  src/storybook.test.ts
  ● Test suite failed to run

    TypeError: require.context is not a function

      2 | import "../src/assets/index.css";
      3 | // automatically import all files ending in *.stories.ts
    > 4 | configure(require.context("../src/app/", true, /\.stories\.ts$/), module);
        |                   ^

      at Object.<anonymous> (.storybook/config.js:4:19)
      at configure (node_modules/@storybook/addon-storyshots/dist/frameworks/configure.js:38:11)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:45:26)
      at loadFramework (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:31:17)
      at Object.testStorySnapshots [as default] (node_modules/@storybook/addon-storyshots/dist/api/index.js:55:36)
      at Object.<anonymous> (src/storybook.test.ts:4:15)
```

That's to be expected as this is a well documented issue in here.
- Added `babel-plugin-require-context-hook` and changed `/src/jest-config/setup.ts` to the following:

```typescript
import 'jest-preset-angular';
import './globalMocks';
require('babel-plugin-require-context-hook/register')();
```
- Configured `.babelrc` with the following content:
```json
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ],
    ],
    "env": {
        "test": {
            "plugins": [
                "babel-plugin-require-context-hook"
            ]
        }
    }
}
```
- Did a bit of research and changed from the `.babelrc` to `babel.config.js` and either yeld the same issue.
- Tried changing the jest `transform` key to the following:
```json
{
....
"transform": {
      "^.+\\.(ts|html)$": "ts-jest",
      "^.+\\.stories\\.[jt]sx?$": "@storybook/addon-storyshots/injectFileName",
      "^.+\\.jsx?$": "babel-jest"
    },
}
```
Running `npm run jest` now yelds the following:
```bash
 FAIL  src/storybook.test.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    \example\node_modules\@storybook\addon-storyshots\dist\frameworks\angular\helpers.ts:2
    import { Component, Type, NgModule } from '@angular/core';
           ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/renderTree.js:22:16)
```
Any help would be appreciated. I've setup a dummy repo [here](https://github.com/jonniebigodes/storybook-angular-storyshots-issue) that illustrates the issue.

**Comment by cloakedninjas** [comment]
Maybe related to #5869 ?

**Comment by andrei-ilyukovich** [comment]
@jonniebigodes I have the same issue on Storybook 5.2.4 version.
```
Details:

    C:\Work\planck\web-components\node_modules\@storybook\addon-storyshots\dist\frameworks\angular\helpers.ts:2
    import { Component, Type, NgModule } from '@angular/core';
           ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (../../../../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../../../../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (../../../../node_modules/@storybook/addon-storyshots/dist/frameworks/angular/renderTree.js:22:16)
```
Jest configuration is similar to yours (I use jest.config.js instead of package.json jest section):
```
module.exports = {
    roots: ["<rootDir>/../../"],
    // setupFilesAfterEnv: ["<rootDir>/setup.ts"],
    setupFiles: ["<rootDir>/setup.ts"],
    globals: {
        "ts-jest": {
            tsConfig: "<rootDir>/../tsconfig.json",
            stringifyContentPathRegex: "\\.html$",
            astTransformers: [
                require.resolve("jest-preset-angular/InlineHtmlStripStylesTransformer")
            ]
        }
    },
    moduleNameMapper: {
        "\\.(md)$": "<rootDir>/htmlMock.js",
        "^@sdo/web-components/(.*)$": "<rootDir>/../../../lib/$1/public_api.ts"
    },
    modulePathIgnorePatterns: ["dist", "src/lib"],
    transform: {
        "^.+\\.js$": "<rootDir>/babel-jest.js",
        "^.+[/\\\\]config[/\\\\]config\\.ts$": "<rootDir>/jest-ts-babel.js",
        "^.+\\.(ts|tsx|html)$": "ts-jest"
    },
    snapshotSerializers: [
        "jest-preset-angular/AngularSnapshotSerializer.js",
        "jest-preset-angular/HTMLCommentSerializer.js"
    ],
    moduleFileExtensions: ["ts", "tsx", "js", "html", "json"],
    reporters: [
        "default",
        [
            "jest-html-reporter",
            {
                pageTitle: "Test Report",
                outputPath: "test-reports/storybook/test-report.html",
                includeFailureMsg: true,
                includeConsoleLog: true
            }
        ]
    ],
    testMatch: ["<rootDir>../../image-snapshots.runner.ts"]
};

```

**Comment by cloakedninjas** [comment]
The following changes to `jest.config.js` managed to get my tests to pass.

```
{
  globals: {
    'ts-jest': {
      diagnostics: false,
      isolatedModules: true
    }
  },
  transformIgnorePatterns: [
    'node_modules/(?!@storybook/*)'
  ]
}
```

It's not ideal turning from a type-checking perspective, but we have eslint running on our codebase as a separate check step

**Comment by andrei-ilyukovich** [comment]
@cloakedninjas thanks for sharing this, but unfortunately it still doesn't work for me. It looks like something specific using "@storybook/addon-storyshots-puppeteer". Now I see another error:
```
 FAIL  src/storybook/image-snapshots.runner.ts
  ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

      1 | import * as path from "path";
      2 | import initStoryshots,  { multiSnapshotWithOptions } from "@storybook/addon-storyshots";
    > 3 | import { imageSnapshot } from "@storybook/addon-storyshots-puppeteer";
        | ^
      4 | 
      5 | const customizePage: any = (page) => {
      6 |     return page.setViewport({ width: 1920, height: 1080 });

      at ../../../../node_modules/@storybook/addon-storyshots-puppeteer/dist/index.js:36:16
      at Object.<anonymous> (../../../../node_modules/@storybook/addon-storyshots-puppeteer/dist/index.js:36:16)
      at Object.<anonymous> (../../image-snapshots.runner.ts:3:1)

```

**Comment by andrei-ilyukovich** [comment]
Eventually I managed to get it to work. In addition to @cloakedninjas hints I had to get rid of `"^.+\\.js$": "<rootDir>/babel-jest.js",` line in transform section. 
Also I've created an issue related to necessity to transpile `@storybook/addon-storyshots` files on the fly: https://github.com/storybookjs/storybook/issues/9042

**Comment by jonniebigodes** [comment]
i'm going to check this out and see if it works out for me.

**Comment by jonniebigodes** [comment]
been testing the the solutions here and now i'm only getting 
```bash
 src/storybook.test.js
  ● Test suite failed to run

    TypeError: require.context is not a function

      14 |
      15 | import "../src/assets/index.css";
    > 16 | configure(require.context("../src/app/", true, /\.stories\.ts$/), module);
         |                   ^

      at Object.<anonymous> (.storybook/config.js:16:19)
      at configure (node_modules/@storybook/addon-storyshots/dist/frameworks/configure.js:38:11)
      at Object.load (node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.js:45:26)
      at loadFramework (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:31:17)
      at Object.testStorySnapshots [as default] (node_modules/@storybook/addon-storyshots/dist/api/index.js:57:36)
      at Object.<anonymous> (src/storybook.test.js:15:15)
```

Tried with the `babel-plugin-require-context-hook/register` approach and the macros approach and still hitting a brick wall.....

**Comment by andrei-ilyukovich** [comment]
@jonniebigodes it looks like your babel config is not picked up properly. I had the similar issue as well and had to add specific transform line for managing `config.ts` file:
```
"^.+[/\\\\]config[/\\\\]config\\.ts$": "<rootDir>/jest-ts-babel.js",
```
You can find `jest-ts-babel.js` in storybook repository, it force usage of babel config where you set up `babel-plugin-require-context-hook`

**Comment by jonniebigodes** [comment]
@andrei-ilyukovich and @cloakedninjas thank you for your help. It seems that the issue lies elsewhere.
Here are the steps i took to solve this:
- Added the following packages `@babel/preset-env`, `@babel/preset-typescript`.
- Created a `babel.config.js` with the following content:
```js

module.exports = function(api) {
    const isTest = api.env('test');
    api.cache(true);
    const presets = [[
      "@babel/preset-env",
      {
        targets: {
          node: "current"
        }
      }
    ],
    "@babel/preset-typescript"];
    const plugins = [];
    return {
      presets,
      plugins: isTest?["require-context-hook"] :[]
    };
  };
```
- Changed the `jest` key in `package.json` to the following:
```json
{
...
"jest": {
    "preset": "jest-preset-angular",
    "setupFilesAfterEnv": [
      "<rootDir>/src/jest-config/setup.ts"
    ],
    "transformIgnorePatterns":[
      "node_modules/(?!@storybook/*)"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/old/",
      "<rootDir>/node_modules/",
      "<rootDir>/dist/",
      "<rootDir>/storybook-static/",
      "<rootDir>/src/test.ts"
    ],
    "coveragePathIgnorePatterns": [
      "/jest-config/",
      "/node_modules/"
    ],
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-preset-angular/AngularSnapshotSerializer.js",
      "<rootDir>/node_modules/jest-preset-angular/HTMLCommentSerializer.js"
    ],
    "globals": {
      "ts-jest": {
        "tsConfig": "<rootDir>/tsconfig.spec.json",
        "stringifyContentPathRegex": "\\.html$",
        "diagnostics": false,
        "isolatedModules": true,
        "astTransformers": [
          "<rootDir>/node_modules/jest-preset-angular/InlineHtmlStripStylesTransformer"
        ]
      }
    },
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/src/jest-config/styleMock.js",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/src/jest-config/fileMock.js"
    },
    "transform": {
      "^.+\\.(ts|html)$": "ts-jest",
      "^.+\\.js$": "babel-jest",
      "^.+\\.stories\\.[jt]sx?$": "@storybook/addon-storyshots/injectFileName"
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node",
      ".html"
    ]
  }
}
```
And the key to solving this was the addition of `transformIgnorePatterns` element in the configuration.
- Changed `src/storybook.test.ts` to `src/storybook.test.js`
- Added the `"emitDecoratorMetadata":true,` to `tsconfig.json`
- Changed `tsconfig.spec.json` to:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "module": "commonjs",
    "allowJs": true,
    "types": [
      "jest",
      "jquery",
      "jsdom",
      "node"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```
- Ran the jest script and all greens across the board.

Thank you very much for your help. Going to close this now. The repo used for this example was updated with the changes made, so that anyone that encounters this issue might get the code used and see it for themselves.
