### ISSUE TITLE
Storyshots fails to run on CRA setup 5.3-beta 3

### ISSUE THREAD

**Issue by kfayelun** [storybookjs/storybook#8938]
**Describe the bug**
I've been following [this description](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-core) for setting up storyshots for a CRA project. I get this error message when running npm run test :
```
 PASS  src/components/App/App.test.js
 FAIL  src/Storyshots.test.js
  ● Test suite failed to run

    /Users/kristi/Prosjekter/imdi-design-system/node_modules/@storybook/addon-storyshots/dist/frameworks/angular/loader.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'core-js';
                                                                                                    ^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:23:41
          at Array.map (<anonymous>)
      at getLoaders (node_modules/@storybook/addon-storyshots/dist/frameworks/frameworkLoader.js:23:10)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.267s
Ran all test suites.

Watch Usage: Press w to show more.
```

**To Reproduce**
1. Follow guide linked to above. I did the following: add storyshots, install require-contex macro as recommended, installed react-test-renderer, added the Storyshots.test.js to initStoryshots();
2. Run: npm run test
3. See error

**Expected behavior**
I expect the storyshots to be created and then used in later npm run test

**Screenshots**

**Repo**
Code here: https://github.com/netliferesearch/imdi-design-system/tree/add_snapshot_testing
Had the same issue before adding react-app-rewired. Had to add that to get less to work. 

**System:**
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.2
  npmPackages:
    @storybook/addon-a11y: ^5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-actions: ^5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-docs: ^5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-links: ^5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/addon-storyshots: ^5.3.0-beta.3 => 5.3.0-beta.6 
    @storybook/addons: ^5.3.0-beta.3 => 5.3.0-beta.3 
    @storybook/preset-create-react-app: ^1.3.1 => 1.3.1 
    @storybook/react: ^5.3.0-beta.3 => 5.3.0-beta.3 
```

**Additional context**
Working on a design system for a client, where these tests were a prerequisite and need to hand it over by mid-december.

**Comment by shilman** [comment]
@Hypnosphi @ndelangen any recent storyshots changes that might lead to this problem?

**Comment by Hypnosphi** [comment]
Same as #8908, please follow there
