### ISSUE TITLE
Add-on docs in vue 'h is not defined'

### ISSUE THREAD

**Issue by NathanVG** [storybookjs/storybook#9411]
**Describe the bug**
We are trying to implement storybook in our Vue.js application. Normal stories work fine, but when trying to implement docs in storybook 5.3.1, mdx stories give the following error: 

```
ReferenceError: h is not defined
    at page (http://localhost:6006/main.81332ea9b001b122ead2.bundle.js:14995:5)
    at renderWithHooks (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:228299:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:230833:13)
    at beginWork$1 (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:232201:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:212375:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:212424:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:212479:31)
    at beginWork$$1 (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:237819:7)
    at performUnitOfWork (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:236737:12)
    at workLoopSync (http://localhost:6006/vendors~main.81332ea9b001b122ead2.bundle.js:236710:22)
```
![image](https://user-images.githubusercontent.com/3620183/72265459-d6dccc00-361c-11ea-864d-96288283313e.png)

I found this [closed issue](https://github.com/storybookjs/storybook/issues/6722), however it references the old documentation and way of writing stories (StoriesOf).

**To Reproduce**
mdx file: 

```
import { ActionButton } from '@/components/action-buttons/ActionButton.vue';
import { PrimaryActionButton } from '@/components/action-buttons/PrimaryActionButton.vue';
import { SecondaryActionButton } from '@/components/action-buttons/SecondaryActionButton.vue';
import { TertiaryActionButton } from '@/components/action-buttons/TertiaryActionButton.vue';
import { Meta, Story, Preview } from '@storybook/addon-docs/blocks';


<Meta title="MDX/ActionButton" component={ActionButton} />

# Action Button

The ActionButton is a component that accepts an _ItemAction_ object as prop.

There are 3 components that use the ActionButton.

- PrimaryActionButton.vue
- SecondaryActionButton.vue
- TertiaryActionButton.vue

<Preview>
  <Story name="All Action Buttons">
    {{
      components: {
        PrimaryActionButton
      },
      template: '<PrimaryActionButton :action="{action}" />',
    }}
  </Story>
</Preview>
```

Webpack config: 

```
const path = require('path');
const custom = require('@vue/cli-service/webpack.config');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const createCompiler = require('@storybook/addon-docs/mdx-compiler-plugin');

module.exports = async ({ config, mode }) => {
  const conf = {
    ...config,
    module: {
      ...config.module,
      rules: custom.module.rules,
    },
  };

  conf.module.rules.push({
    rules: [
      {
        test: /\.md$/,
        use: [
          {
            loader: 'html-loader',
          },
          {
            loader: 'markdown-loader',
            options: {},
          },
        ],
      },
    ],
  });

  conf.module.rules.push({
    test: /\.(stories|story)\.[tj]sx?$/,
    loader: require.resolve('@storybook/source-loader'),
    exclude: [/node_modules/],
    enforce: 'pre',
  });

  conf.module.rules.push({
    test: /\.vue$/,
    loader: 'vue-docgen-loader',
    enforce: 'post',
  });

  conf.module.rules.push({
    test: /\.(stories|story)\.mdx$/,
    use: [
      {
        loader: 'babel-loader',
        // may or may not need this line depending on your app's setup
        options: {
          plugins: ['@babel/plugin-transform-react-jsx'],
        },
      },
      {
        loader: '@mdx-js/loader',
        options: {
          compilers: [createCompiler({})],
        },
      },
    ],
  });

  conf.resolve.alias = {
    ...conf.resolve.alias,
    '@': path.join(__dirname, '..', '/src'),
  };

  conf.resolve.extensions.push('.ts');

  conf.plugins.push(
    new MiniCssExtractPlugin({
      filename: `styles/[name].css`,
    })
  );

  return conf;
};

```

Preview.js

```
import { addParameters } from '@storybook/vue';
import { DocsPage, DocsContainer } from '@storybook/addon-docs/blocks';

import Vue from 'vue';
import PopoverPlugin from '@/plugins/popover';
import VueResize from 'vue-resize';
import SelectablePlugin from '@/plugins/selectable';
import ElementsPlugin from '@/plugins/elements';

import TrapFocus from '@/directives/trap-focus';

import IconPlugin from '../src/plugins/icon/plugin.ts';

import '../src/main.css';

Vue.use(IconPlugin);
Vue.use(PopoverPlugin);
Vue.use(VueResize);
Vue.use(SelectablePlugin);
Vue.use(ElementsPlugin);

Vue.directive('trap-focus', TrapFocus);

addParameters({
  docs: {
    container: DocsContainer,
    page: DocsPage,
  },
});
```
main.js

```
module.exports = {
  stories: ['../stories/**/*.stories.(js|mdx)'],
  addons: [
    '@storybook/addon-knobs/register',
    '@storybook/addon-actions/register',
    '@storybook/addon-links/register',
    '@storybook/addon-a11y/register',
    '@storybook/addon-storysource/register',
    '@storybook/addon-notes/register',
    '@storybook/addon-docs/register',
  ],
};

```

**Expected behavior**
Expect mdx stories to render

**System:**
System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: 5.3.1 => 5.3.1
    @storybook/addon-actions: 5.3.1 => 5.3.1
    @storybook/addon-console: 1.2.1 => 1.2.1
    @storybook/addon-docs: ^5.3.1 => 5.3.1
    @storybook/addon-knobs: 5.3.1 => 5.3.1
    @storybook/addon-links: ^5.3.1 => 5.3.1
    @storybook/addon-notes: 5.3.1 => 5.3.1
    @storybook/addon-storysource: 5.3.1 => 5.3.1
    @storybook/addons: ^5.3.1 => 5.3.1
    @storybook/vue: ^5.3.1 => 5.3.1

**Comment by shilman** [comment]
Closing as duplicate to #8096

**Comment by danilovaz** [comment]
@NathanVG take a look at: https://github.com/storybookjs/storybook/issues/9316 maybe can help you.
