### ISSUE TITLE
Module build failed with thread-loader for javascript modules

### ISSUE THREAD

**Issue by lozinsky** [storybookjs/storybook#9515]
**Describe the bug**
When javascript modules build with [thread-loader](https://github.com/webpack-contrib/thread-loader), building fails with the error:

```
ERROR in ./.storybook/generated-entry.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
ENOENT: no such file or directory, open '/storybook-webpack-config-with-thread-loader/.storybook/generated-entry.js'
    at PoolWorker.fromErrorObj (/storybook-webpack-config-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /storybook-webpack-config-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/storybook-webpack-config-with-thread-loader/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/storybook-webpack-config-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /storybook-webpack-config-with-thread-loader/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Socket.onChunk (/storybook-webpack-config-with-thread-loader/node_modules/thread-loader/dist/readBuffer.js:36:9)
    at Socket.emit (events.js:321:20)
    at Socket.Readable.read (_stream_readable.js:527:10)
    at Socket.read (net.js:618:39)
    at flow (_stream_readable.js:998:34)
    at emitReadable_ (_stream_readable.js:591:3)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true main[2]
```

**To Reproduce**

1. Add `thread-loader@2.1.3` dependency
2. Add `thread-loader` to javascript webpack rule
3. Run `start-storybook`

**Expected behavior**
There should be no error.

**Code snippets**
https://github.com/lozinsky/storybook-webpack-with-thread-loader

**Additional context**
I guess that `webpack-virtual-modules` plugin
https://github.com/storybookjs/storybook/blob/3bcaaeb769ef21234837cc755a27c056092d1f00/lib/core/src/server/preview/iframe-webpack.config.js#L52-L60
is not compatible with `thread-loader`.

**Comment by chloeleichen** [comment]
Having same issue, any updates? @lozinsky

**Comment by fernandopasik** [comment]
Might be related to https://github.com/storybookjs/vue-cli-plugin-storybook/issues/84#issuecomment-574810669

**Comment by hasable** [comment]
Hi, I am having the same issue. Any update or maybe workaround? @lozinsky @chloeleichen

**Comment by lozinsky** [comment]
@hasable we stopped using `thread-loader` for javascript code in storybook config ☹️

**Comment by chrisgbaker** [comment]
Still seeing this issue running Storybook@latest, webpack@latest, and thread-loader@latest

**Comment by lisaschumann** [comment]
Same for @nuxtjs/storybook!
