### ISSUE TITLE
Failed to load custom addon

### ISSUE THREAD

**Issue by andrei-ilyukovich** [storybookjs/storybook#9830]
There is an error during loading custom addon in storybook **5.3.*** and **6.0.0-alpha***.
```console
> start-storybook -p 6006

info @storybook/angular v6.0.0-alpha.9
info 
info => Loading presets
WARN   Failed to load preset: "C:\\Work\\planck\\storybook-addon-loading\\storybook-addons-loading\\.storybook\\changelog\\register.js" on level 1
ERR! C:\Work\planck\storybook-addon-loading\storybook-addons-loading\.storybook\changelog\register.js:1
ERR! (function (exports, require, module, __filename, __dirname) { import React from "react";
ERR!                                                                      ^^^^^
ERR! 
ERR! SyntaxError: Unexpected identifier
ERR!     at new Script (vm.js:79:7)
ERR!     at createScript (vm.js:251:10)
```

 In **5.2.*** version it was necessary to create `managerWebpack` config which was loaded by `presets.js` file. This allowed storybook to properly transpile custom addon files. Below is custom webpack manager config that I used:
```typescript
module.exports = {
    async managerWebpack(baseConfig, options) {
        baseConfig.module.rules.push({
            test: /(\.jsx?|\.tsx?)$/,
            use: [
                {
                    loader: require.resolve("ts-loader"),
                    options: {
                        transpileOnly: true,
                        configFile: path.resolve(__dirname, "./tsconfig.json")
                    }
                }
            ]
        });
        baseConfig.module.rules.push({ test: /\.md$/, use: [{ loader: "raw-loader" }] });
        baseConfig.resolve.extensions.push(".ts", ".tsx");
        return baseConfig;
    }
};
```
As I understand in **5.3.*** `presets.js` should not be used anymore, we should set needed config in `main.js` instead. But this config is not working anymore. Here is an example of `main.js` 
```typescript
module.exports = {
  stories: ['../src/**/*.stories.ts'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    require.resolve('./changelog/register.js')
  ],
  
  // This config seems not working anymore
  managerWebpack: async (baseConfig, options) => {
    baseConfig.module.rules.push({
      test: /(\.jsx?|\.tsx?)$/,
      use: [
        {
          loader: require.resolve("ts-loader"),
          options: {
            transpileOnly: true,
            configFile: path.resolve(__dirname, "./tsconfig.json")
          }
        }
      ]
    });
    baseConfig.module.rules.push({ test: /\.md$/, use: [{ loader: "raw-loader" }] });
    baseConfig.resolve.extensions.push(".ts", ".tsx");
    return baseConfig;
  }
};
```

Please feel free to check this out in [repo](https://github.com/andrei-ilyukovich/storybook-addons-loading). Just make `npm i`, then `npm run storybook` to get the error loading addon.

System:
```
...
    "@storybook/addon-actions": "6.0.0-alpha.9",
    "@storybook/addon-links": "6.0.0-alpha.9",
    "@storybook/addons": "6.0.0-alpha.9",
    "@storybook/angular": "6.0.0-alpha.9",
...
```

**Comment by shilman** [comment]
cc @ndelangen

**Comment by ndelangen** [comment]
Is this fixed in the newest alpha release?

**Comment by ndelangen** [comment]
Assuming yes.
