### ISSUE TITLE
Invalid metadata set via setCustomElements() - Addon docs for webcomponents

### ISSUE THREAD

**Issue by dmartinjs** [storybookjs/storybook#9848]
**Describe the bug**
Addon docs for webcomponents readme say that custom-elements.json generated by Stencil are supported by [Storybook addon docs](https://github.com/storybookjs/storybook/tree/v5.3.13/addons/docs/web-components#custom-elementsjson) to generate metadata for webcomponents.

When I reproduce the way to handle it from the readme, I have 
```
You need to setup valid meta data in your config.js via setCustomElements().
See the readme of addon-docs for web components for more details.

Error: You need to setup valid meta data in your config.js via setCustomElements().
    See the readme of addon-docs for web components for more details.
    at isValidMetaData (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:26852:9)
    at extractComponentDescription (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:7492:95)
    at getDescriptionProps (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:3275:19)
    at DescriptionContainer (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:3286:30)
    at renderWithHooks (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:146514:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:149048:13)
    at beginWork$1 (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:150416:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:130590:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:130639:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.1d2920aabfc482aadff4.bundle.js:130694:31)
```

it seems that the format is different from the example in the readme.
In the example, we have
```
  "version": 1.2,
  "tags": [
    {
      "name": "demo-wc-card",
      "description": "This is a container looking like a card with a back and front side you can switch",
      "attributes": [
        {
          "name": "back-side",
          "description": "Indicates that the back of the card is shown",
          "type": "boolean",
          "defaultValue": false
        },
        {
          "name": "header",
          "description": "Header message",
          "type": "string",
          "defaultValue": "Your message"
        },
        {
          "name": "rows",
          "description": "Data rows",
          "type": "never[]"
        }
      ],
      "properties": [
        {
          "name": "backSide",
          "description": "Indicates that the back of the card is shown",
          "type": "boolean"
        },
        {
          "name": "header",
          "description": "Header message",
          "type": "string"
        },
        {
          "name": "rows",
          "description": "Data rows",
          "type": "never[]"
        }
      ],
      "events": [
        {
          "name": "side-changed",
          "description": "Fires whenever it switches between front/back"
        }
      ],
      "slots": [
        {
          "name": "",
          "description": "This is an unnamed slot (the default slot)"
        }
      ],
      "cssProperties": [
        {
          "name": "--demo-wc-card-back-color",
          "description": "Font color for back"
        },
        {
          "name": "--demo-wc-card-front-color",
          "description": "Font color for front"
        },
        {
          "name": "--demo-wc-card-header-font-size",
          "description": "Header font size"
        }
      ]
    }
  ]
}
```

Stencil generate this format

```
{
  "compiler": {
    "name": "@stencil/core",
    "version": "1.8.8",
    "typescriptVersion": "3.7.5"
  },
  "tags": [
    {
      "filePath": "src/components/accordion/accordion.tsx",
      "encapsulation": "shadow",
      "name": "roadtrip-accordion",
      "readme": "# roadtrip-accordion\n\n\n",
      "docs": "",
      "docsTags": [
        {
          "description": "- content of hidden in the accordion",
          "name": "slot"
        }
      ],
      "usage": {},
      "attributes": [
        {
          "name": "header",
          "type": "string",
          "mutable": false,
          "attributes": "header",
          "reflectToAttr": false,
          "description": "Text in the header row",
          "docsTags": [],
          "values": [
            {
              "type": "string"
            }
          ],
          "optional": false,
          "required": false
        },
        {
          "name": "isOpen",
          "type": "boolean",
          "mutable": false,
          "attributes": "is-open",
          "reflectToAttr": false,
          "description": "Set open to true to show the accordion element and to false to hide it.",
          "docsTags": [],
          "defaultValue": "false",
          "values": [
            {
              "type": "boolean"
            }
          ],
          "optional": false,
          "required": false
        }
      ],
      "methods": [],
      "events": [],
      "styles": [],
      "slots": [
        {
          "name": "",
          "docs": "content of hidden in the accordion"
        }
      ],
      "dependents": [],
      "dependencies": [],
      "dependencyGraph": {}
    },
]
}
```

If I edit the file manually to have the same attributes has in the Storybook example, it works.

**To Reproduce**
1. Create the same example as  with Stencil
2. Add --docs-json custom-elements.json to the npm "build" in package.json
3. Configure Storybook for webcomponents
4. Add the story and config to have metadata like said in the readme

**Expected behavior**
The format generated by Stencil should works as said in the [documentation](https://github.com/storybookjs/storybook/tree/v5.3.13/addons/docs/web-components#custom-elementsjson)

**Screenshots**

![Capture d’écran 2020-02-13 à 18 05 47](https://user-images.githubusercontent.com/53537199/74459604-e190b800-4e8b-11ea-8e77-e281287f6304.png)

**Comment by dmartinjs** [comment]
Fixed by using the docs-vscode to outputTargets in my stencil.config.ts

```
    {
      type: 'docs-vscode',
      file: 'custom-elements.json'
    },
```
 I'll make a PR to add this information in the Stencil section in the Docs addon for webcomponent
