### ISSUE TITLE
Svelte with addon-viewport throws TypeError

### ISSUE THREAD

**Issue by KhaledPendleton** [storybookjs/storybook#9852]
**The Rundown**
Trying to run Storybook results in the error listed below. Upon further research I found that in the file `node_modules/@storybook/svelte/dist/client/preview/globals.js` a string with the value of `"svelte"` is trying to be assigned to the property `STORYBOOK_ENV` on the non-existent `window` property on `_global` (Code included below for clarity). Setting window equal to an empty object does stop the error from occurring **BUT** then the Storybook webpage no longer loads. 

I followed the tutorial for @storybook/addon-viewport that can be found [here](https://www.npmjs.com/package/@storybook/addon-viewport). The tutorial is specifically for React but I figured the logic would be the same for Svelte. Has anyone else encountered this problem/ is there a fix?

```
// node_modules/@storybook/svelte/dist/client/preview/globals.js
"use strict";

var _global = require("global");

// _global.window === null
_global.window.STORYBOOK_ENV = 'svelte';
```

**My code**
```
// .storybook/main.js
const { addParameters } = require('@storybook/svelte');
const newViewports = {
         iPhone11Pro: {
		name: 'Apple iPhone 11 Pro',
		styles: { width: '375px', height: '812px' },
		type: 'mobile'
	},
	iPhone11ProMax: {
		name: 'Apple iPhone 11 Pro Max',
		styles: { width: '414px', height: '896px' },
		type: 'mobile'
	},
};

addParameters({
	viewport: {
		viewports: { ...newViewports }
	}
});

module.exports = {
	stories: ['../src/components/**/*.stories.js'],
	addons: [
		'@storybook/addon-actions',
		'@storybook/addon-links',
		'@storybook/addon-viewport/register'
	]
};
```

**The error**
```
TypeError: Cannot set property 'STORYBOOK_ENV' of undefined
ERR!     at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/preview/globals.js:5:30)
ERR!     at Module._compile (internal/modules/cjs/loader.js:971:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:822:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:864:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/preview/index.js:12:1)
ERR!     at Module._compile (internal/modules/cjs/loader.js:971:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:822:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:730:14)
ERR!     at Module.require (internal/modules/cjs/loader.js:864:19)
ERR!     at require (internal/modules/cjs/helpers.js:74:18)
ERR!     at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/index.js:55:16)
ERR!     at Module._compile (internal/modules/cjs/loader.js:971:30) {
ERR!   stack: "TypeError: Cannot set property 'STORYBOOK_ENV' of undefined\n" +
ERR!     '    at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/preview/globals.js:5:30)\n' +
ERR!     '    at Module._compile (internal/modules/cjs/loader.js:971:30)\n' +
ERR!     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)\n' +
ERR!     '    at Module.load (internal/modules/cjs/loader.js:822:32)\n' +
ERR!     '    at Function.Module._load (internal/modules/cjs/loader.js:730:14)\n' +
ERR!     '    at Module.require (internal/modules/cjs/loader.js:864:19)\n' +
ERR!     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
ERR!     '    at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/preview/index.js:12:1)\n' +
ERR!     '    at Module._compile (internal/modules/cjs/loader.js:971:30)\n' +
ERR!     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)\n' +
ERR!     '    at Module.load (internal/modules/cjs/loader.js:822:32)\n' +
ERR!     '    at Function.Module._load (internal/modules/cjs/loader.js:730:14)\n' +
ERR!     '    at Module.require (internal/modules/cjs/loader.js:864:19)\n' +
ERR!     '    at require (internal/modules/cjs/helpers.js:74:18)\n' +
ERR!     '    at Object.<anonymous> (/Users/khaled/Sites/clients/bdc/node_modules/@storybook/svelte/dist/client/index.js:55:16)\n' +
ERR!     '    at Module._compile (internal/modules/cjs/loader.js:971:30)'
ERR! }
```

**Comment by KhaledPendleton** [comment]
This is my first time submitting an issue, sorry in advance if I made any sort of mistakes with my post
