### ISSUE TITLE
Passing in an unknown command throws error

### ISSUE THREAD

**Issue by jamesgeorge007** [storybookjs/storybook#9887]
**Describe the bug**
With #9881 passing in an unknown command results in an error being thrown:
```bash
Invalid command: Command {
  commands: [],
  options: [],
  _execs: Set {},
  _allowUnknownOption: false,
  _args: [],
  _name: '*',
  _optionValues: {},
  _storeOptionsAsProperties: true,
  _passCommandToAction: true,
  _actionResults: [],
  _helpFlags: '-h, --help',
  _helpDescription: 'output usage information',
  _helpShortFlag: '-h',
  _helpLongFlag: '--help',
  _noHelp: true,
  _exitCallback: undefined,
  _executableFile: undefined,
  parent: [Command]
}.
 See --help for a list of available commands.
Arguments are: undefined
/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/node_modules/leven/index.js:26
	while (leftLength > 0 && (left.charCodeAt(~-leftLength) === right.charCodeAt(~-rightLength))) {
	                                                                  ^

TypeError: right.charCodeAt is not a function
    at leven (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/node_modules/leven/index.js:26:68)
    at /home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/lib/cli/dist/generate.js:79:73
    at Array.find (<anonymous>)
    at Command.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/lib/cli/dist/generate.js:79:42)
    at Command.listener (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/node_modules/commander/index.js:370:29)
    at Command.emit (events.js:203:13)
    at Command.parseArgs (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/node_modules/commander/index.js:894:12)
    at Command.parse (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/storybook/lib/cli/dist/generate.js:88:85)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
```

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.14 containing PR #9888 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.
