### ISSUE TITLE
Can't build Storybook for Web Components

### ISSUE THREAD

**Issue by whoisryosuke** [storybookjs/storybook#9955]
**Describe the bug**
Tried building Storybook for Web Components. Crashes at ~96% with error from `core-js`.

```
yarn run v1.19.0
$ build-storybook
info @storybook/web-components v5.3.13
info 
info clean outputDir..
info => Copying prebuild dll's..
info => Building manager..
info => Loading manager config..
info => Loading presets
info => Compiling manager..
info => manager built (43 s)
info => Building preview..
info => Loading preview config..
info => Loading presets
info => Loading config/preview file in "./.storybook".
info => Adding stories defined in ".storybook/main.js".
info => Using default Webpack setup.
info => Compiling preview..
ERR! => Failed to build the preview
ERR! ./dist/esm/polyfills/core-js.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error: /Users/ryo/Dev/JS/sui-web-components/dist/esm/polyfills/core-js.js: don't know how to turn this value into a node
ERR!     at Object.valueToNode (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/types/lib/converters/valueToNode.js:87:9)
ERR!     at PluginPass.Expression (/Users/ryo/Dev/JS/sui-web-components/node_modules/babel-plugin-minify-constant-folding/lib/index.js:195:26)
ERR!     at PluginPass.newFn (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/visitors.js:220:17)
ERR!     at newFn (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/visitors.js:179:21)
ERR!     at NodePath._call (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/path/context.js:55:20)
ERR!     at NodePath.call (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/path/context.js:42:17)
ERR!     at NodePath.visit (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/path/context.js:90:31)
ERR!     at TraversalContext.visitQueue (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!     at NodePath.visit (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/path/context.js:97:18)
ERR!     at TraversalContext.visitQueue (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/Users/ryo/Dev/JS/sui-web-components/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!  @ ./dist/esm/polyfills/index.js 1:1379-1401
ERR!  @ ./loader/index.mjs
ERR!  @ ./.storybook/preview.js
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/web-components/config.js ./.storybook/preview.js ./.storybook/generated-entry.js
(node:27540) UnhandledPromiseRejectionWarning: [object Object]
(node:27540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It still builds partially, with a `storybook-static` folder being generated. But when you open the `index.html` in there, you see the Storybook interface and an error in the main window.

[You can see it live here](https://sui-web-components.netlify.com/?path=/story/*)

**To Reproduce**
1. Clone repo: https://github.com/whoisryosuke/sui-web-components
1. `yarn && yarn build && yarn build-storybook`

> Must build the StencilJS components to provide Storybook the necessary files (hence the `yarn build` preceding the Storybook build).

**Expected behavior**
Storybook is built fully.

**System:**

```
x -p @storybook/cli@next sb info

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 61.0.1
    Safari: 13.0.3
  npmPackages:
    @storybook/addon-a11y: ^5.3.13 => 5.3.13 
    @storybook/addon-actions: ^5.3.13 => 5.3.13 
    @storybook/addon-backgrounds: ^5.3.13 => 5.3.13 
    @storybook/addon-docs: ^5.3.13 => 5.3.13 
    @storybook/addon-knobs: ^5.3.13 => 5.3.13 
    @storybook/addon-links: ^5.3.13 => 5.3.13 
    @storybook/addon-storysource: ^5.3.13 => 5.3.13 
    @storybook/web-components: ^5.3.13 => 5.3.13 
  npmGlobalPackages:
    @storybook/cli: 3.4.10
```

> This script was intense and took a long time to load. In the future I'd recommend a different method for determining local versioning.

**Additional context**

**Comment by whoisryosuke** [comment]
After looking into the error, it looks like an issue on Stencil's end, so I'll approach it from there!

Closed 👌

**Comment by 10chars** [comment]
> After looking into the error, it looks like an issue on Stencil's end, so I'll approach it from there!
> 
> Closed 👌

@whoisryosuke  Did you manage to sort this out with the Stencil team?

**Comment by whoisryosuke** [comment]
@10chars I didn’t make an issue on their repo. 

ended up using the distribution build of Stencils components and importing that, instead of using the Stencil loader and polyfills (which I think were the issue, since core-js is used for polyfillng). 

Doesn’t allow for hot reloading though, which is lame 😭 I honestly would go back and [use the Enjin method to copy files using Webpack](https://whoisryosuke.com/blog/2019/using-stencil-with-storybook/).

**Comment by 10chars** [comment]
@whoisryosuke Thanks! Will take a look at your method and see if I can get it working

**Comment by mkay581** [comment]
Just ran into this same `polyfills/core-js.js: don't know how to turn this value into a node` error specifically because we've been trying to get hot reloading working 😞 . 

@whoisryosuke were you ever able to get this working with Stencil's built dist files while also hot reloading?

**Comment by nanandn** [comment]
I have similar problem, but not with core-js, but simplebar.

```
ERR! => Failed to build the preview
ERR! ./node_modules/simplebar/dist/simplebar.min.js
ERR! Module build failed (from ./node_modules/babel-loader/lib/index.js):
ERR! Error: /home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/simplebar/dist/simplebar.min.js: don't know how to turn this value into a node
ERR!     at Object.valueToNode (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/types/lib/converters/valueToNode.js:87:9)
ERR!     at PluginPass.Expression (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/babel-plugin-minify-constant-folding/lib/index.js:195:26)
ERR!     at PluginPass.newFn (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/visitors.js:220:17)
ERR!     at newFn (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/visitors.js:179:21)
ERR!     at NodePath._call (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/path/context.js:55:20)
ERR!     at NodePath.call (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/path/context.js:42:17)
ERR!     at NodePath.visit (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/path/context.js:90:31)
ERR!     at TraversalContext.visitQueue (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!     at NodePath.visit (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/path/context.js:97:18)
ERR!     at TraversalContext.visitQueue (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:112:16)
ERR!     at TraversalContext.visitSingle (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:84:19)
ERR!     at TraversalContext.visit (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/context.js:140:19)
ERR!     at Function.traverse.node (/home/gitlab_ci_multi_runner/builds/26860574/0/web-ui/storybook/node_modules/@babel/traverse/lib/index.js:84:17)
ERR!  @ ./node_modules/simplebar-react/dist/simplebar-react.js 8:171-191 8:231-275
ERR!  @ ./node_modules/@storybook/components/dist/ScrollArea/ScrollArea.js
ERR!  @ ./node_modules/@storybook/components/dist/index.js
ERR!  @ ./node_modules/@storybook/addon-docs/dist/blocks/index.js
ERR!  @ ./node_modules/@storybook/addon-docs/blocks.js
ERR!  @ ./.storybook/preview.js
ERR!  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ```
